### ISSUE TITLE
[1.0.0-pre-release] c.SaveFile undefined 

### ISSUE THREAD

**Issue by cheft** [gofiber/fiber#1]
c.SaveFile undefined (type *fiber.Ctx has no field or method SaveFile)

**Comment by Fenny** [comment]
Hi @cheft ,

Could you share the source code?

SaveFile is used for MultipartForm uploads, you can see that in [this example](https://gofiber.github.io/fiber/#/examples?id=multiple-file-upload)

**Comment by cheft** [comment]
Resolved on `v1.0.1-beta`. Thx !
