### ISSUE TITLE
🤗 How can change filename in SendFile method

### ISSUE THREAD

**Issue by mossnana** [gofiber/fiber#1003]
**no filename in my downloaded file with SendFile()**

**Code snippet**
```go
package main

import "github.com/gofiber/fiber/v2"

func MyController(ctx *fiber.Ctx) error {
  return ctx.SendFile("demo.tsv", false)
}
```

and filename that downloaded was `tsv`
It should be `demo.tsv` not "`tsv`

Thank you for attention in my question

**Comment by Fenny** [comment]
```go
func MyController(ctx *fiber.Ctx) error {
  return ctx.SendFile("./demo.tsv", false)
}
```

**Comment by mossnana** [comment]
> ```go
> func MyController(ctx *fiber.Ctx) error {
>   return ctx.SendFile("./demo.tsv", false)
> }
> ```

Thank you
