### ISSUE TITLE
🤗how logger get requestid ??

### ISSUE THREAD

**Issue by cyanBone** [gofiber/fiber#1007]
**Question description**

how logger get requestid ??

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  // ..
}
```

**Comment by hi019** [comment]
Try this:

```go
​app​.​Use​(​logger​.​New​(logger.​Config​{
        ​Format​:     ​"${pid} ${header:X-Request-ID} ${status} - ${method} ${path}​\n​"​,
}))
```

**Comment by cyanBone** [comment]
@hi019 Can't get it, is there any demo or document

**Comment by cyanBone** [comment]
@hi019 
ctx.Locals ("requestid")

Okay, I can get it

**Comment by Fenny** [comment]
To log it, you can use
```go
​app​.​Use​(​logger​.​New​(logger.​Config​{
        ​Format​: "${pid} ${locals:requestid} ${status} - ${method} ${path}​\n​"​,
}))
```

**Comment by sali2801** [comment]
> To log it, you can use
> 
> ```go
> ​app​.​Use​(​logger​.​New​(logger.​Config​{
>         ​Format​: "${pid} ${locals:requestid} ${status} - ${method} ${path}​\n​"​,
> }))
> ```

@Fenny why is comes form `locals` while it is set in `header` X-Request-ID

**Comment by ReneWerner87** [comment]
Since it is added to the response header and the locals

Why in the locals? So that the access is easier
So you can use also the header in the log Format

**Comment by sanyuanya** [comment]
![QQ_1730688774994](https://github.com/user-attachments/assets/ab969f8d-724d-42ea-a060-63a0fd20fb2b)
> To log it, you can use
> 
> ```go
> ​app​.​Use​(​logger​.​New​(logger.​Config​{
>         ​Format​: "${pid} ${locals:requestid} ${status} - ${method} ${path}​\n​"​,
> }))
> ```

This cannot be recorded
![QQ_1730688774994](https://github.com/user-attachments/assets/1d4810f2-3d9a-4bd9-9ac2-fa52f0cd78cb)
