### ISSUE TITLE
🤗 BodyParser error ？？？

### ISSUE THREAD

**Issue by cyanBone** [gofiber/fiber#1010]
**Question description**

err:=ctx.BodyParser(obj)
How does this err assert

this err type is "*errors.errorString" 

I will get err type

```go
if err != nil {
		switch err.(type) {
		case validator.ValidationErrors:
			translate := err.(validator.ValidationErrors).Translate(trans)
			for _, v := range translate {
				errStr = errors.New(v)
			}
		case *json.UnmarshalTypeError:
			unmarshalTypeError := err.(*json.UnmarshalTypeError)
			if unmarshalTypeError.Field == "" {
				errStr = fmt.Errorf("%s 类型错误，期望类型 %s", unmarshalTypeError.Field, "json")
			} else {
				errStr = fmt.Errorf("%s 类型错误，期望类型 %s", unmarshalTypeError.Field, unmarshalTypeError.Type.String())
			}
		case *json.SyntaxError:
			unmarshalTypeErrors := err.(*json.SyntaxError)
			errStr = fmt.Errorf("第%d个字符错误，不是一个正确的json", unmarshalTypeErrors.Offset)
		default:
			errStr = errors.New("数据类型错误")
		}
	}
```
**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  // ..
}
```

**Comment by cyanBone** [comment]
https://github.com/gofiber/fiber/blob/060a10d822a628d084cf2061f49d90c7917b6dc8/ctx.go#L281

none type is err type is "*errors.errorString"

**Comment by codemicro** [comment]
Hi @cyanBone!

It's most likely that this is the error being thrown: https://github.com/gofiber/fiber/blob/060a10d822a628d084cf2061f49d90c7917b6dc8/ctx.go#L281

You can't assert the error type using the same method as you've been doing for other errors returned by `ctx.BodyParser`. If you wanted to, you could directly compare the error string.

This is branching into more general Go usage, but the text of an error can be obtained using `err.Error()`. Using that, you could probably do something like:
```go
if err := ctx.BodyParser(out); err != nil {
    if strings.Contains(err.Error(), "cannot parse content-type") {
        // handle that here
    }
}
```

**Comment by cyanBone** [comment]
I hope there is a type in this err
Other errors in this function seem to have types

thanks

**Comment by codemicro** [comment]
This error has no type, and probably won't do, ever. It doesn't really make sense for an error that's going to be used in a one-off context like this to be defined as an exported `const` at the package level.

**Comment by cyanBone** [comment]
OK, I'll solve it with default
thanks
