### ISSUE TITLE
🤗 This result is one more point？？

### ISSUE THREAD

**Issue by cyanBone** [gofiber/fiber#1012]
**Question description**

`curl --location --request POST 'http://app.test:8080/category' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id":"123"
}'`

unmarshalTypeError.Field value is "id." not is "id"
This result is one more point

**Code snippet** _Optional_

```go
type Cc struct {
	Id   int    `json:"id" xml:"id" form:"id"`
	Name string `json:"name" xml:"name" form:"name"`
}

err := ctx.BodyParser(obj)
	switch err.(type) {
	case *json.SyntaxError:
		unmarshalTypeErrors := err.(*json.SyntaxError)
		err = fmt.Errorf("第%d个字符错误，不是一个正确的json", unmarshalTypeErrors.Offset)
	case *json.UnmarshalTypeError:
		unmarshalTypeError := err.(*json.UnmarshalTypeError)
		if unmarshalTypeError.Field == "" {
			err = fmt.Errorf("%s 类型错误，期望类型 %s", unmarshalTypeError.Field, "json")
		} else {
			fmt.Printf("%+v\n",unmarshalTypeError)
			err = fmt.Errorf("%s 类型错误，期望类型 %s", unmarshalTypeError.Field, unmarshalTypeError.Type.String())
		}
	}
```

**Comment by hi019** [comment]
We don't convert strings into integers for you. Sending `'{ "id":123 }'` works.

**Comment by cyanBone** [comment]
@hi019 
I just want him to make a mistake and get the error inside. The problem now is the result multiple points of unmarshalTypeError.Field.

**Comment by cyanBone** [comment]
@hi019 
`curl --location --request POST 'http://app.test:8080/category' \ --header 'Content-Type: application/json' \ --data-raw '{ "id":"123" }'`

This request is wrong (id is string type)
I want to get the field of the structure(Cc{}) in the error, but it has an extra "."(What I want is "id", not "id.")
"Id" is parsed in the json parsing of other frameworks

```go
type Cc struct {
	Id   int    `json:"id" xml:"id" form:"id"`
	Name string `json:"name" xml:"name" form:"name"`
}

err := ctx.BodyParser(obj)
switch err.(type) {
case *json.UnmarshalTypeError:
	unmarshalTypeError := err.(*json.UnmarshalTypeError)
	fmt.Printf("%v\n",unmarshalTypeError.Field)
}
```

**Comment by hi019** [comment]
Our upstream patch has been merged in https://github.com/segmentio/encoding/pull/57 . Please try again.
