### ISSUE TITLE
🐛 Document threading behavior

### ISSUE THREAD

**Issue by kiwec** [gofiber/fiber#1020]
When you start a Fiber app, there is a big block displaying the version, address, and other relevant information. In it, there is a line containing the number of "Threads" that are started. Depending on whether or not prefork is enabled, those can be threads or processes.

When those are processes, using globals with the usual `sync` utils will not work and create race conditions when a unique global state is expected. Documentation should clearly explain that stateful applications should use `prefork: false` in the configuration settings for this reason, and the start banner should display "processes" instead of "threads" when prefork is enabled.

**Comment by Fenny** [comment]
Fixed in https://github.com/gofiber/fiber/pull/1039

![](https://i.imgur.com/mOJEZJh.png)
![](https://i.imgur.com/68zHeF0.png)
