### ISSUE TITLE
🚀 Render HTML string

### ISSUE THREAD

**Issue by akshaybabloo** [gofiber/fiber#1023]
**Is your feature request related to a problem?**

No

**Describe the solution you'd like**

There is a HTML renderer using `ctx.Render`, but I have a string of HTML that I would like to render but `Render()` looks for file name in `html.new()`. It would be good to have a `ctx.RenderString()` (or something like that) that takes in the HTML string and its bindings

**Describe alternatives you've considered**

For now I am using Go's HTML module to render the string and return it using `ctx.Type("html").SendString(htmlVar)`

**Comment by Fenny** [comment]
Do you need to parse template variables? If not, you can just do the following:
```go
app.Get("/", func(c *fiber.Ctx) error {
    c.Set(fiber.HeaderContentType, fiber.MIMETextHTML)
    return c.SendString("<h1>Hello, World!</h1>"
})
```

**Comment by akshaybabloo** [comment]
Nice. I will wait for the implementation

**Comment by akshaybabloo** [comment]
Should I close this issue or should I keep it open till the support is added? As in for your reference?

**Comment by Fenny** [comment]
We can keep it open until we have time to add this to the Template package 👍

**Comment by akshaybabloo** [comment]
@Fenny were you able to add this?

**Comment by akshaybabloo** [comment]
@Fenny were you able to add this?
