### ISSUE TITLE
filesystem: cache busting 

### ISSUE THREAD

**Issue by aep** [gofiber/fiber#1026]
browsers are inconsistent in their cache handling,
so a common strategy is to append the hash of the content to file names,
like 

    img src="cover-123123.png"

should this be part of filesystem or should i do this external?

**Comment by Fenny** [comment]
Maybe https://github.com/gofiber/fiber/tree/master/middleware/etag is what you are looking for or https://github.com/gofiber/fiber/tree/master/middleware/cache
