### ISSUE TITLE
🤗 Session cookie will be sent every request, wasting bandwidth

### ISSUE THREAD

**Issue by chinaapus** [gofiber/fiber#1033]
**Question description**
Session cookie will be sent every request, wasting bandwidth
**Code snippet** _Optional_

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
)

func main() {
	store := session.New()

	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {

		sess, err := store.Get(c)
		if err != nil {
			panic(err)
		}
		defer sess.Save()

		sess.Set("name", "john")

		return c.SendString("ok")
	})

	app.Get("/session", func(c *fiber.Ctx) error {
		sess, err := store.Get(c)
		if err != nil {
			panic(err)
		}
		defer sess.Save()

		name := sess.Get("name")

		fmt.Println("name:", name)

		return c.SendString("ok")
	})

	app.Listen("127.0.0.1:3008")
}

```
![截图_20201125085705](https://user-images.githubusercontent.com/46473093/100168468-4c335180-2efc-11eb-934a-4ce28b203cf5.png)

**Comment by Fenny** [comment]
We should only ser the cookie if it's a "fresh" session, this us one of the things being fixed this week. Merging this issue with https://github.com/gofiber/fiber/issues/1030

**Comment by Fenny** [comment]
@chinaapus <https://github.com/gofiber/fiber/pull/1032/commits/711911aeea3f92bc4401882e212e12a6bdc9ca9c>
