### ISSUE TITLE
🚀 Streaming?

### ISSUE THREAD

**Issue by Nv7-GitHub** [gofiber/fiber#1034]
**Is your feature request related to a problem?**
I need a way of pushing data to the client because busy waiting is bad. I am familiar with SSE and I was hoping to use this. When I set up SSE though, it didn't work. Instead, the server just returned `Streaming unsupported!`. Is there a way to use SSE in fiber? 

**Describe the solution you'd like**
I would like streaming to be supported.

**Describe alternatives you've considered**
If this doesn't work, I will use websockets, but I would prefer to use SSE.

**Comment by Nv7-GitHub** [comment]
I found [https://github.com/gofiber/fiber/issues/646](https://github.com/gofiber/fiber/issues/646) but I am using an adaptor and I just get the message `Streaming unsupported!`. To be more specific, I am using the SSE library [https://github.com/r3labs/sse](https://github.com/r3labs/sse) with an adaptor.

**Comment by Fenny** [comment]
I'm not familiar with sse nor net/http based libraries. Our adaptor package is not designed to be used for production because it will slow things down ( converting fasthttp -> net/http on each request )

Fiber/Fasthttp supports response streaming to the client using the `SetBodyStreamWriter`
```go
app.Get("/flush", func(c *fiber.Ctx) (err error) {
	c.Set(fiber.HeaderContentType, fiber.MIMEApplicationJSONCharsetUTF8)
	c.Context().SetBodyStreamWriter(func(w *bufio.Writer) {
		// Create stream encoder
		enc := json.NewEncoder(w)
		// It will flush automatically on every 4KB
		if err = enc.Encode(data); err != nil {
			return
		}
		// Flush remaining buffer
		w.Flush()
	})
	return
})
```

**Comment by Nv7-GitHub** [comment]
Wow, I didn't notice this! Thank you!
