### ISSUE TITLE
🐛  no cors headers while using proxy and cors

### ISSUE THREAD

**Issue by jney** [gofiber/fiber#1037]
**Fiber version**

v2.2.0

**Issue description**

cors headers not added using both middlewares proxy and cors

**Code snippet**

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/proxy"
)

func main() {
	app := fiber.New()
	app.Use(cors.New(cors.Config{AllowCredentials: true}))

	app.Use(proxy.Balancer(proxy.Config{
		Servers: []string{fmt.Sprintf("http://localhost:%s", cfg.ProxyPort)},
		ModifyRequest: func(c *fiber.Ctx) error {
			if c.Method() == fiber.MethodOptions {
				return c.SendStatus(fiber.StatusNoContent)
			}
			return nil
		},
		ModifyResponse: func(c *fiber.Ctx) error {

			return nil
		},
	}))

	log.Fatal(app.Listen(":8888"))
}

```

**Comment by K0enM** [comment]
A hacky way to fix this is doing this:

```golang

ModifyResponse: cors.New(cors.Config{AllowCredentials: true})

```

**Comment by Fenny** [comment]
I tested your example, and it seems to work well for me. I'm closing this issue, feel free to re-open 👍

**Comment by pejeio** [comment]
@K0enM @Fenny  Looks like I have the same issue. Do you have an example using the [proxy.Do](https://pkg.go.dev/github.com/gofiber/fiber/v2/middleware/proxy#Do) function?

**Comment by pejeio** [comment]
> @K0enM @Fenny Looks like I have the same issue. Do you have an example using the [proxy.Do](https://pkg.go.dev/github.com/gofiber/fiber/v2/middleware/proxy#Do) function?

Just found a way. This is example when you use [proxy.Do](https://pkg.go.dev/github.com/gofiber/fiber/v2/middleware/proxy#Do):

```go
err = proxy.Do(c, "http://localhost")
if err != nil {
    return err
}
c.Response().Header.Set("Access-Control-Allow-Origin", "http://host.com")
c.Response().Header.Set("Access-Control-Allow-Credentials", "true")
return nil
```

**Comment by gaby** [comment]
@pejeio Can you open a new issue, so that we can look at it. Thanks! 

My guess is the Proxy middleware is removing the headers.

**Comment by guvenaltunsoyy** [comment]
Is there any development here to not remove those header during proxy?
