### ISSUE TITLE
is there any solution for Localization,that we can switch muti languages?🚀 

### ISSUE THREAD

**Issue by TheFirstCoins** [gofiber/fiber#1041]
https://www.iris-go.com/docs/#/?id=localization

the iris framework has this feature!!

**Comment by codemicro** [comment]
Hi @TheFirstCoins!

As mentioned in #1001, **Fiber has no built in localisation options.** This would be something you'd have to implement yourself, since Fiber is purely a web framework to build your app on top of.

At present, there are no plans to implement localisation functionality.
