### ISSUE TITLE
🚀  provide an option to use json-iterator

### ISSUE THREAD

**Issue by huangciyin** [gofiber/fiber#1047]
**Is your feature request related to a problem?**
The `encoding/json` do not support zero values of structs with omitempty(https://github.com/golang/go/issues/11939), But json-iterator support.
Related issue: https://jira.mongodb.org/browse/GODRIVER-1332

**Describe the solution you'd like**
provide an option to use jsoniter, for example `go build -tags=jsoniter .`
https://github.com/json-iterator/go
Reference implementation: https://github.com/gin-gonic/gin/blob/master/internal/json/jsoniter.go

**Comment by moneszarrugh** [comment]
fiber uses jsoniter by default according to docs

https://docs.gofiber.io/api/ctx#json

**Comment by hi019** [comment]
> fiber uses jsoniter by default according to docs
> 
> https://docs.gofiber.io/api/ctx#json

We use https://github.com/segmentio/encoding now, I'll update that shortly

**Comment by Fenny** [comment]
I think it's best to use your own json encoding logic on application level, and just use `c.Send` to pass the encoded json to the response. Do you have an example regarding the `omitempty` of zero values?

PS: Updated docs <https://docs.gofiber.io/api/ctx#json> 👍

**Comment by huangciyin** [comment]
example: https://jira.mongodb.org/browse/GODRIVER-1332

**Comment by Fenny** [comment]
Maybe we could post this behavior on <https://github.com/segmentio/encoding>?

**Comment by Fenny** [comment]
Moving this to https://github.com/gofiber/fiber/issues/1108
