### ISSUE TITLE
🐛 Session id cookie will not be added when don't save any data.

### ISSUE THREAD

**Issue by nupamore** [gofiber/fiber#1048]
**Fiber version**
v2.2.2

**Issue description**
Session id cookie will not be added when don't save any data.

**Code snippet**
Example: Just use session id as oauth state
```go
// Login : [GET] /auth/login
func (ctrl *Controller) Login(c *fiber.Ctx) error {
	sess, _ := store.Get(c)
	sess.Save()

	url := oauth.LoginURL(sess.ID())
	return c.Redirect(url)
}

// LoginCallback : [GET] /auth/callback
func (ctrl *Controller) LoginCallback(c *fiber.Ctx) error {
	sess, _ := store.Get(c)

	if c.Query("state") != sess.ID() {
		return errors.New("Invalid session state")
	}
...
```

**Comment by Fenny** [comment]
Do we need to re-set the cookie even if there is no update? In your example, the cookie that holds the session ID is still present in the client browser? Correct me if I'm wrong.

**Comment by nupamore** [comment]
If any data is saved with `sess.Set()`, the cookie creation is fine, but if `sess.Save()` is executed without `sess.Set()`, the cookie is not created. So the cookie does not exist, it will continue to recognize it as a new session

**Comment by nupamore** [comment]
session_test.go
```go
// cookie should not be set if empty data
utils.AssertEqual(t, 0, len(ctx.Response().Header.PeekCookie(store.CookieName)))
```
Session middleware explicitly use a method called `Save()`, I think it should be saved regardless of the empty data.

**Comment by chinaapus** [comment]
I think the session cookie is only created when the value is set
To avoid meaningless visitor cookies

**Comment by nupamore** [comment]
I think meaningless visitors can skip programmatically. If going to skip it automatically, why is there a `Save()` method.

**Comment by Fenny** [comment]
The `Save` method is intended to save data to the Storage, but it makes sense that if `Save` is called it should create a session cookie even if no data is present. I will merge your PR 👍

**Comment by Fenny** [comment]
This PR will be tagged under `v2.2.3` today 👍

**Comment by nupamore** [comment]
Thank you for your kind response.
