### ISSUE TITLE
🤗 Using context being returned from third party library

### ISSUE THREAD

**Issue by hulk-baba** [gofiber/fiber#1052]
**Question description**
How can I make use of context.Context being returned from the third party library
**Code snippet** _Optional_
```
span, tracectx := opentracing.StartSpanFromContext(fiberCtx.Context(), "HTTP - ")
```

**Comment by hi019** [comment]
I don't understand, can you give an example of what you would like to do with the context?

**Comment by hulk-baba** [comment]
With the received trace context, we later retrieve span details when we log the request details

**Comment by WLun001** [comment]
Not sure what are you trying to achieve. Could you provide code snippet or pseudocode ?
