### ISSUE TITLE
Downstream logging always showing status=200

### ISSUE THREAD

**Issue by evreng** [gofiber/fiber#1060]
I have got a downstream logger, configured as follows:
	app.Static("/", "/path")
	app.Use(FiberLogger)

that is doing something like:
	switch c.Response().StatusCode()

working perfectly for all my handlers except from app.Static() handler, always returning 200:
```
curl -i http://localhost:7001/favicon.ico
HTTP/1.1 404 Not Found
Date: Mon, 07 Dec 2020 15:00:12 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 23

Cannot GET /favicon.ico

```
My logger:
`{"ip":"127.0.0.1","level":"info","method":"GET","msg":"","path":"/favicon.ico","status":200,"time":"2020-12-07T15:00:12Z"}
`
Reference: https://github.com/gofiber/fiber/blob/c9df437c7954df8948f7260698bd75ffbfebead5/router.go#L376

**Comment by Fenny** [comment]
Just like in expressjs, order matters. Try to place your logger middleware on top.

**Comment by evreng** [comment]
The logger needs to access the status code and maybe things like bytes sent, which are set after other handlers have processed the request

**Comment by Fenny** [comment]
Fiber has a flexible stack chain where you can call the next handler within another handler, this is exactly what many middleware packages do ( including logger ) see <https://github.com/gofiber/fiber/blob/master/middleware/logger/logger.go#L152>

```go
app.Use(logger.New())
app.Static("/", "/static")
// Logger > Static > Logger
```

**Comment by evreng** [comment]
Thanks vm Fenny, that's the trick, I need to call next within my Use handler prior to logging
