### ISSUE TITLE
🐛 Cache middleware causes 32-Bit builds to crash

### ISSUE THREAD

**Issue by moneszarrugh** [gofiber/fiber#1061]
**Fiber version**
v2.2.3

**Issue description**
cache middleware causes 32-bit builds to crash

**Code snippet**

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cache"
)

func main() {
	app := fiber.New()

	// Steps to reproduce
	app.Use(cache.New())

	log.Fatal(app.Listen(":3000"))
}

```

```sh
GOARCH=386 go build -o myapp
./myapp
```

Output:

```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804a04b]

goroutine 14 [running]:
runtime/internal/atomic.Store64(0xa9f431c, 0x5fceac5c, 0x0)
	/usr/local/go/src/runtime/internal/atomic/asm_386.s:205 +0xb
github.com/gofiber/fiber/v2/internal/memory.(*Storage).updater(0xa9f4300, 0x3b9aca00, 0x0)
	/home/mones/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.3/internal/memory/memory.go:69 +0x44
created by github.com/gofiber/fiber/v2/internal/memory.New
	/home/mones/go/pkg/mod/github.com/gofiber/fiber/v2@v2.2.3/internal/memory/memory.go:26 +0x11b
```

**Comment by Fenny** [comment]
Related to https://www.programmersought.com/article/69621805140/, I'm in no rush to support 32 bit systems ( a bit outdated ) . But I can accept PR's regarding this issue 👍

**Comment by moneszarrugh** [comment]
> Related to https://www.programmersought.com/article/69621805140/, I'm in no rush to support 32 bit systems ( a bit outdated ) . But I can accept PR's regarding this issue

This was not an issue with v2.2.0 I only updated today and it crashed :disappointed: 
I'm running 32 bit in prod :smile:

**Comment by Fenny** [comment]
I'm still confused why `v2.2.0` worked on your 32-bit machine and the current version does not. I double-checked the changes and we did not change anything regarding the `atomic` operators. Are you sure `v2.2.0` had no problems? Or did you change something in your application?

**Comment by moneszarrugh** [comment]
> I'm still confused why `v2.2.0` worked on your 32-bit machine and the current version does not. I double-checked the changes and we did not change anything regarding the `atomic` operators. Are you sure `v2.2.0` had no problems? Or did you change something in your application?

Yes I'm sure I just downgraded to `v2.2.0` and it doesn't panic.

**Comment by moneszarrugh** [comment]
> > I'm still confused why `v2.2.0` worked on your 32-bit machine and the current version does not. I double-checked the changes and we did not change anything regarding the `atomic` operators. Are you sure `v2.2.0` had no problems? Or did you change something in your application?
> 
> Yes I'm sure I just downgraded to `v2.2.0` and it doesn't panic.

Panics also on `v.2.2.1` so better check there.

**Comment by Fenny** [comment]
Out of curiosity, can I ask why you are deploying a web server on a 32-bit machine?

**Comment by moneszarrugh** [comment]
> Out of curiosity, can I ask why you are deploying a web server on a 32-bit machine?

The 32-bit machine hosts an older version of the app written in php that I'm currently porting to Go with the help of fiber. There's no requirement for 32-bit it's just what's running at the moment. It'll probably be migrated to a newer one when the app is fully ported.
