### ISSUE TITLE
Zero Allocation misunderstanding 🤗 

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#1063]
@Fenny

This is the example is the documentation:

```go
func handler(c *fiber.Ctx) error {
    // Variable is only valid within this handler
    result := c.Params("foo")

    // Make a copy
    buffer := make([]byte, len(result))
    copy(buffer, result)
    resultCopy := string(buffer) 
    // Variable is now valid forever

    // ...
}
```

This is from godoc:
```go
func (c *Ctx) Params(key string, defaultValue ...string) string
```

Perhaps I have a misunderstanding of Go, but `Params()` returns a `string` (not a pointer).
In the example: `result := c.Params("foo")`, `result` creates a **BRAND NEW** copy of the string  via "`:=`".
There is no need for using a buffer to create a `resultCopy`.

Also, `Params()` returns a **BRAND NEW** string. Not the underlying pointer that fiber reuses.

**Comment by pjebs** [comment]
See https://play.golang.org/p/-y53a2reCe0 for an example

**Comment by Fenny** [comment]
The underlying string is a pointer to a byte array which is from the Ctx pool ( re-used on every request )
We use the following trick to convert bytes to string without allocation:
```go
func UnsafeString(b []byte) string {
	return *(*string)(unsafe.Pointer(&b))
}
```

When returned from the handler, all values within the `Ctx` are cleared and re-used for the next request ( hence the insane performance ).  So your string value is not a copy as you mentioned, but rather a pointer to the original byte slice which is possible with the `unsafe` package.

See <https://github.com/gofiber/fiber/blob/master/utils/convert.go> for more information regarding the converting process.

**Comment by pjebs** [comment]
Okay so `Params()` returns pointer.

But `result := ` creates a copy according to https://blog.golang.org/slices (under "strings" section)

**Comment by Fenny** [comment]
It creates a variable that holds a string type pointing to a byte slice, this might be confusing. But long story short, the `result :=` variable is only holding a string type that is under the hood is referring to a byte slice in memory ( which is re-used later on and therefore not immutable unless copied )

**Comment by pjebs** [comment]
> result := does not allocate anything

@Fenny can you show me where you got that from. To me, it doesn't seem correct. If you are correct, I have a fundamental misunderstanding of Go which I would like to correct.

**Comment by Fenny** [comment]
I might rephrase it wrong, what I'm trying to explain is that the `:=` does not necessarily mean that you are gonna allocate memory. The actual value that is being set determines the action. Maybe this benchmark will clear that up.
```go
// go test -v -run=^$ -bench=Benchmark_Allocations -benchmem -count=4
func Benchmark_Allocations(b *testing.B) {
	var john = "doe"
	b.ReportAllocs()
	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		mark := john
		if mark != john {
			b.Fatal("mark is still here")
		}
	}
}
```
```
Benchmark_Allocations-16        705877784                1.68 ns/op            0 B/op          0 allocs/op
Benchmark_Allocations-16        697684558                1.67 ns/op            0 B/op          0 allocs/op
Benchmark_Allocations-16        714285714                1.69 ns/op            0 B/op          0 allocs/op
Benchmark_Allocations-16        701760130                1.70 ns/op            0 B/op          0 allocs/op
```

**Comment by pjebs** [comment]
That benchmark output doesn't show allocations in stack. Only heap.

**Comment by kiyonlin** [comment]
> That benchmark output doesn't show allocations in stack. Only heap.

Hey @pjebs  How about 
```go
// go test -v -run=^$ -bench=Benchmark_Allocations -benchmem -count=4
func Benchmark_Allocations(b *testing.B) {
	var john = strings.Repeat("doe", 1e6)
	b.ReportAllocs()
	b.ResetTimer()
	for n := 0; n < b.N; n++ {
		mark := john
		if mark != john {
			b.Fatal("mark is still here")
		}
	}
}
```
```hs
Benchmark_Allocations-16    	700668340	         1.65 ns/op	       0 B/op	       0 allocs/op
```

**Comment by pjebs** [comment]
@kiyonlin I don't understand how your example is different from @Fenny 's example in the relevant sense.

https://www.ardanlabs.com/blog/2013/07/understanding-pointers-and-memory.html

**Comment by kiyonlin** [comment]
Okey, let me show you something interesting
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	var a string

	app.Get("/:a", func(c *fiber.Ctx) error {
		if a == "" {
			a = c.Params("a")
		}
		log.Println(c.Params("a"), a)
		return c.SendString(a)
	})

	app.Listen(":3000")
}
```

**Comment by Fenny** [comment]
Like @kiyonlin mentioned, we re-use byte slices in Fiber to avoid allocations. Most of our context methods return references to these byte slices. It's hard to control what values are living on the stack or heap, there is a reason why Go does not document this.
```
➜  ~ curl 127.0.0.1:3000
favicon.ico
➜  ~ curl 127.0.0.1:3000/johndoe
johndoe.ico
```

**Comment by pjebs** [comment]
I tried your demo. I don't know what it's meant to demonstrate. `c.Params()` returns and logs the route parameter.
`log(a)` logs to console the outer variable a, which was `""` initially, but later got set to `"a"` after the first curl request.

**Comment by Fenny** [comment]
It demonstrates that `result := c.Params("key")` is just creating a reference to a specific part in memory that will get overwritten at some point and therefore is necessary to copy it (allocate) if you want to move it outside of the handler.

> Params() returns a BRAND NEW string. Not the underlying pointer that fiber reuses.

And this should answer the above question?

**Comment by pjebs** [comment]
Yes I can see that. Thanks @Fenny  and @kiyonlin

**Comment by kiyonlin** [comment]
> See https://play.golang.org/p/00Yw0GPztEV for an example

And in this example, you should print the pointers not just the values.

https://play.golang.org/p/Uubh-1zbXGy

**Comment by pjebs** [comment]
@kiyonlin I just made a small adjustment to your code.

```go
func main() {
	app := fiber.New()

	var a string

	app.Get("/:a", func(c *fiber.Ctx) error {
		if a == "" {
			b := c.Params("a") // The change
			a = b
		}
		log.Println(c.Params("a"), a)
		return c.SendString(a)
	})

	app.Listen(":3000")
}
```

If you now run your input again, you will see that: `result := c.Params("foo")` will create a new alloc that is independent of the underlying byte array, thus demonstrating that the official recommendation of:

```go
    // Variable is only valid within this handler
    result := c.Params("foo")

    // Make a copy
    buffer := make([]byte, len(result))
    copy(buffer, result)
    resultCopy := string(buffer) 
    // Variable is now valid forever
```

is unnecessary.

**Comment by kiyonlin** [comment]
No I don't think so. Have you ever try your code? I got same result here.

**Comment by Fenny** [comment]
I don't think you fully understand what we are trying to explain here.
```
2020/12/09 02:32:48 favicon.ico favicon.ico
2020/12/09 02:32:50 john johncon.ico
```

**Comment by pjebs** [comment]
I'm asserting that you don't need to use `utils.CopyString` because `:=` does that already and I believe my tests confirmed it for me.

Now you guys are confidently saying that I am wrong and you guys are also authorities on the matter.

Due to that conflict, I need to rethink everything tomr when my mind clears up and I'm less confused.

Thank you for your time and consideration.

**Comment by Fenny** [comment]
![tenor](https://user-images.githubusercontent.com/25108519/101563201-1a74bd00-39c9-11eb-8632-fe1c59e41d38.gif)

**Comment by kiyonlin** [comment]
Please see this [StringHeader](https://github.com/golang/go/blob/master/src/reflect/value.go#L1977-L1986).

> StringHeader is the runtime representation of a string.

`:=` just gets a copy of `StringHeader` but not the [real underlying data](https://github.com/golang/go/blob/master/src/reflect/value.go#L1984).

**Comment by pjebs** [comment]
Yes. I realised that before closing the issue. I wanted to think about it more deeply tomr.
