### ISSUE TITLE
how to remove the headers X-Xss-Protection X-Content-Type-Options and X-Frame-Options

### ISSUE THREAD

**Issue by zkdfbb** [gofiber/fiber#1065]
If I don't want to use the default headers X-Xss-Protection X-Content-Type-Options and X-Frame-Options
how to completely remove them

this is my solution but it still exists
`c.Set("X-Xss-Protection", "")`

**Comment by kiyonlin** [comment]
`c.Set("X-Xss-Protection", "")` This just set the value to empty string.

I think you should use `c.Response().Header.Del("X-Xss-Protection")` instead.

**Comment by zkdfbb** [comment]
@kiyonlin thanks! it works
