### ISSUE TITLE
how to get logger in handler 

### ISSUE THREAD

**Issue by zkdfbb** [gofiber/fiber#1066]
**Question description**

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  // ..
}
```

**Comment by Fenny** [comment]
Could you try to be more specific about your issue?

**Comment by zkdfbb** [comment]
@Fenny 

In function handler, I want to use logger configured in app, but I don't know how to get it

`
func handler(c *fiber.Ctx) error {
   // ...
}

func main(){
    // ...
    file, err := os.OpenFile("./logs/index.log", os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
    if err != nil {
        log.Error("error open log file")
    }
    defer file.Close()
    app.Use(logger.New(logger.Config{
        Format:     "[${time}] ${status} ${method} ${path} (${ips}) (${referer}) ${latency}\n",
        TimeFormat: "2006-01-02 15:04:05",
        Output:     file,
    }))

    app.Get("/item/:id.:format", handler)
    // ..
`

**Comment by Fenny** [comment]
```go
package main

import (
	"log"
	"os"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
	file, err := os.OpenFile("./item.log", os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
	if err != nil {
		panic(err)
	}
	defer file.Close()
	app := fiber.New()
	app.Use(logger.New(logger.Config{
		Format:     "[${time}] ${status} ${method} ${path} (${ips}) (${referer}) ${latency}\n",
		TimeFormat: "2006-01-02 15:04:05",
		Output:     file,
	}))

	app.Get("/item/:id.:format", func(c *fiber.Ctx) error {
		return c.SendString("Hello 👋")
	})
	log.Fatal(app.Listen(":3000"))
}
```
`http://localhost:3000/item/123.txt`

```go
// item.log
[2020-12-11 01:48:57] 200 GET /item/123.txt () () 0s
[2020-12-11 01:48:57] 404 GET /favicon.ico () (http://localhost:3000/item/123.txt) 0s
```
