### ISSUE TITLE
🤗 BodyParser (Refactor)

### ISSUE THREAD

**Issue by moneszarrugh** [gofiber/fiber#1067]
`BodyParser` uses a series of `if-else` statements with calls to `strings.HasPrefix` to match the content type

Any reason why it wan't implemented with a simple `switch-case`?

Also, the `else` part is useless since it's returning when a type is matched.

I also suggest defining a global `fiber.Err` type for body parser to better identify body parse errors.

https://github.com/gofiber/fiber/blob/9049720218a875a03dd6f272743c13774a6dcb2b/ctx.go#L247-L282

**Comment by Fenny** [comment]
Tagged in https://github.com/gofiber/fiber/releases/tag/v2.2.5, thanks for the report 👍
