### ISSUE TITLE
🤗 Passing value from fiber context

### ISSUE THREAD

**Issue by ridhoperdana** [gofiber/fiber#1071]
Hi Fiber team,

Thank you for the awesome package. I've got a question regarding assigning value into Fiber Context. We know that we can assign value to Golang Context, and this is very useful.

I've 2 use-cases for this assigned value's context:
1. Retrieving data in custom middleware, assign the value into context, and the data can be retrieved later.
2. Setting up context timeout so the request can be cut when it passed the timeout limitation. 

For now, I have some solutions for them:
1. Using Fiber session with a short time limit of expiration. 
2. Using timeout middleware, but I need to define the timeout to all of my routes.

Is there any way better to solve my case? 

Thank you

**Comment by Fenny** [comment]
Hi, regarding passing values to the Context https://docs.gofiber.io/api/ctx#locals

A better approach is to add the timeout logic to the operation you perform within the handler ( database query for example )

**Comment by Fenny** [comment]
Closing this issue, feel free to re-open 👍
