### ISSUE TITLE
Why isn't TLS setup simpler? 🤗 

### ISSUE THREAD

**Issue by HeCorr** [gofiber/fiber#1077]
**Question description**
Hello! I've been researching the fastest and easiest go web framework for the v3 of my API and ended up chosing Fiber. But when looking at how to listen in TLS mode, the code seemed excessively larger than needed.

In pure Go, you'd use `http.ListenAndServeTLS(":443", "cert.crt", "priv.key", nil)`. a simple one-liner.

But in Fiber:
```
ln, _ := net.Listen("tcp", ":443")

cer, _:= tls.LoadX509KeyPair("cert.crt", "priv.key")

ln = tls.NewListener(ln, &tls.Config{Certificates: []tls.Certificate{cer}})

app.Listener(ln)
```
4 lines, and that's without error handling.

My question is, why doesn't Fiber implement a simpler function like `app.ListenTLS(":80", "cert", "key")`, where all the other stuff is executed in the background? Thanks!

**Comment by Fenny** [comment]
Shipped with https://github.com/gofiber/fiber/releases/tag/v2.3.0

```go
func main() {
    app := fiber.New()
    app.Get("/", func(c *fiber.Ctx) error {
        return c.SendString("Secure connection")
    })
    log.Fatal(app.ListenTLS(":443", "./cert.pem", "./cert.key"))
}
```

Thank you for the feedback 👍

**Comment by HeCorr** [comment]
awesome! thank you very much!
