### ISSUE TITLE
🐛  The process bootstrap slow when many routes

### ISSUE THREAD

**Issue by huangciyin** [gofiber/fiber#1081]
**Fiber version**
2.0.0
**Issue description**
When we have many routes(eg >1000), the process start very slow(>10s).  
Bootstrap speed is important for serverless environment.
**Code snippet**

```go
package main

import (
	"fmt"
	"log"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func main() {
	// Fiber instance
	app := fiber.New()

	for i := 0; i < 1000; i++ {
		url := "/b/" + strconv.Itoa(i)
		fmt.Println(url)
		app.Get(url, hello)
	}

	for i := 0; i < 1000; i++ {
		url := "/c/" + strconv.Itoa(i)
		fmt.Println(url)
		app.Get(url, hello)
	}

	// Routes
	app.Get("/", hello)

	// Start server
	log.Fatal(app.Listen(":3000"))
}

// Handler
func hello(c *fiber.Ctx) error {
	return c.SendString("Hello")
}
```

**Comment by ReneWerner87** [comment]
thanks for the report, we will have a look at it and already have an idea where the problem might be, if this is confirmed we can serve with a pull request in a few days, so it should probably be fixed in the next release.

**Comment by ReneWerner87** [comment]
We will work on it in the new year(january)

**Comment by ReneWerner87** [comment]
with 4002 handlers
![image](https://user-images.githubusercontent.com/7063188/105627674-7f308d80-5e38-11eb-8976-f36d2079372a.png)

with 2 handlers
![image](https://user-images.githubusercontent.com/7063188/105627691-9cfdf280-5e38-11eb-8f04-e7e2e0bcbec3.png)

you are right with the 4000 routes the start process takes quite a bit longer

I will try to optimize this

**Comment by ReneWerner87** [comment]
with 4002 handlers:
![image](https://user-images.githubusercontent.com/7063188/105629658-aab97500-5e44-11eb-94ec-62dd5cc43e62.png)

with 2 handlers:
![image](https://user-images.githubusercontent.com/7063188/105629661-aee59280-5e44-11eb-9452-2c29949ce14e.png)

PR here: https://github.com/gofiber/fiber/pull/1134

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/releases/tag/v2.4.0
