### ISSUE TITLE
Custom Error Func for CSRF Middleware🚀 

### ISSUE THREAD

**Issue by twhit-mrwebapps** [gofiber/fiber#1083]
**Is your feature request related to a problem?**
Not so much a problem, more about improving usability and functionality.

**Describe the solution you'd like**
I'd like the option to be able to add a custom error response (in the way of a func) for the CSRF token as I wish to have a specific response when the CSRF token has expired / failed which would allow me to ensure the practices being used in the project we're developing are followed.

**Describe alternatives you've considered**
None.

**Additional context**
I don't know if I could expand on this request.

**Comment by hi019** [comment]
Agreed this would be a good feature. Should be straightforward, just add the relevant config and replace the two `return fiber.ErrForbidden` with `config.ErrorHandler(c). Would you like to make a PR? We are always available in [the discord](https://gofiber.io/discord) for help.

**Comment by twhit-mrwebapps** [comment]
When I get a chance, I'll look into it, thanks 👍

**Comment by xenowits** [comment]
is this issue resolved?? @hi019

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/releases/tag/v2.4.0
