### ISSUE TITLE
context user value after request's response returned

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#1085]
I am currently injecting my database pool via **pre-request-handler middleware**:

```go
var db = sql.Open(...) // *sql.DB

func injectDB(c *fiber.Ctx) error {
	ctx := c.Context()

	ctx.SetUserValue("db", db) // *sql.DB
	// Reset user value to nil so that Close is not called.
	// See: https://github.com/valyala/fasthttp/issues/926
	defer ctx.SetUserValue("db", struct{}{})

	return c.Next()
}
```

In my request handler:

```go
func Handler(c *fiber.Ctx) error {
	ctx := c.Context()
	db := ctx.UserValue("db").(*sql.DB)
	
	go FuncX(db) // Is this safe to do?
}

```

**Is it safe to use context user values after the response is returned?** `db` is `*sql.DB`. 

Note, the context value gets set to `struct{}{}` after the middleware returns.

**Comment by kiyonlin** [comment]
Maybe you should check this valyala/fasthttp#920

**Comment by pjebs** [comment]
I only ask due to:

```
func handler(c *fiber.Ctx) error {
    // Variable is only valid within this handler
    result := c.Params("foo")

    // Make a copy
    buffer := make([]byte, len(result))
    copy(buffer, result)
    resultCopy := string(buffer) 
    // Variable is now valid forever

    // ...
}
```

**Comment by kiyonlin** [comment]
> In this scenario db can be closed, and hence auto-closed. 

When db is closed, `FuncX` may gets issues.
```go
FuncX(db *sql.DB) {
  // time consuming
  // use a closed db
}
```

So I don't think it's safe.

**Comment by pjebs** [comment]
In my case, db is **not** closed. Would it still be safe?

**Comment by kiyonlin** [comment]
> In my case, db is **not** closed. Would it still be safe?
> I believe it is because although the context user value is cleared, in my handler I create a new pointer to the db pool which will still exist and be valid.

If so it's kinda global db. Yeah, that'd be fine.

**Comment by kiyonlin** [comment]
I'll close it for now. Feel free to re-open it if you have further questions.
