### ISSUE TITLE
🤗 413 Request Entity Too Large

### ISSUE THREAD

**Issue by Nv7-GitHub** [gofiber/fiber#1086]
I am uploading a file. I am using the single file upload recipe. It works fine up to 4 MB, but after 4MB I get a 413 status code and the response is `Request Entity Too Large`. How do I fix this?

**Comment by kiyonlin** [comment]
Please check for `BodyLimit` in [config](https://docs.gofiber.io/api/fiber#config). It's default to 4M.

By the way, what's your version of Fiber?

**Comment by Nv7-GitHub** [comment]
It worked! Thank you! I have fiber version `2.3.0`
