### ISSUE TITLE
🐛 Routing do not differentiate whether an URL element is a parameter or a route

### ISSUE THREAD

**Issue by derkan** [gofiber/fiber#1088]
**Fiber version**
v2.3.0

**Issue description**
Routing do not differentiate whether an URL element is a parameter or a route. Returns first matched.
If you try the given code snippet, all of the following requests runs `/users/:page?`route.;
GET `http://127.0.0.1:3000/users/combo`
GET `http://127.0.0.1:3000/users/combo/`
GET `http://127.0.0.1:3000/users/1`

In [echo](https://github.com/labstack/echo) framework this works normal. To solve problem we should check direct matches first. To do this maybe while sorting routes with same prefix, we can prioritize routes with non-parameter.

If route with `/users/combo` is declared first, there is no problem.

**Code snippet**
```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
	app := fiber.New()

	app.Get("/users/:page?", func(c *fiber.Ctx) error {
		page := c.Params("page")
		if page == "" {
			page = "1"
		}
		msg := fmt.Sprintf("Hello, got page number as %s 👋!!!", c.Params("page"))
		return c.SendString(msg)
	})
	app.Get("/users/combo", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("Hello, this is key value list 👋!")
		return c.SendString(msg)
	})

	log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
Right, the order is important, the first route matched in this case, because it allows a variable string at the end.

This behavior is currently expected and sorting the user specified routes would lead to an unexpected behavior.

**Comment by kiyonlin** [comment]
I think we should up to users to decide the route order. 

And I don't think a const route has higher priority. They are equal.

As @ReneWerner87 mentioned above
> sorting the user specified routes would lead to unexpected behaviors.
