### ISSUE TITLE
🐞 Color residue

### ISSUE THREAD

**Issue by keob** [gofiber/fiber#109]
**Fiber version/commit** 
v1.4.2

**Issue description**
When I run the build binary and exit color residue.(cmd, powershell,powershell core)

**Expected behavior**
no color residue

**Steps to reproduce**
In windows: run binary

**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) {
		c.Send("Hello World!")
	})

	app.Listen("localhost:8080")
}
```

![image](https://user-images.githubusercontent.com/25259671/74209979-e48d7c00-4cc4-11ea-9e1a-21df3fcca4b7.png)

**Comment by Fenny** [comment]
At least the important parts are visible :smile: 
But jokes aside, we might change the dark gray to `default` color.

**Comment by keob** [comment]
Adding a sex line can solve it。
you can see this https://github.com/gofiber/fiber/pull/110/files file changed

**Comment by Fenny** [comment]
@keob, that didn't do the trick for me.
I reset the gray to default in this PR: https://github.com/gofiber/fiber/pull/115
![](https://i.imgur.com/ErW8Osg.png)

Should be fine now

**Comment by keob** [comment]
Ok🤞😊
