### ISSUE TITLE
 How to set encoding format for static files🤗 

### ISSUE THREAD

**Issue by thep0y** [gofiber/fiber#1096]
**Question description**

If there is Chinese in the javascript file, it cannot be decoded normally

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  app.Static("/static", "./static")
}
```

```javascript
// /static/js/index.js
alert('Hello World!')
alert('你好')

var test = '测试中文'
```

The text displayed in the browser:
```javascript
alert('Hello World!')
alert('浣犲ソ')

var test = '娴嬭瘯涓枃'
```
<img width="150" alt="20201228150151" src="https://user-images.githubusercontent.com/51874567/103195776-e6345280-491d-11eb-969e-d0cd5b1b2cd3.png">

**Comment by kiyonlin** [comment]
Hey, what's the encoding of `/static/js/index.js`?

I use `utf-8` and get correct answer
```bash
http :3000/static/js/index.js
HTTP/1.1 200 OK
Content-Length: 88
Content-Type: application/javascript
Date: Mon, 28 Dec 2020 07:17:58 GMT
Last-Modified: Mon, 28 Dec 2020 07:16:39 GMT

// /static/js/index.js
alert('Hello World!')
alert('你好')

var test = '测试中文'
```

**Comment by kiyonlin** [comment]
Oh I also get messy code in the browser.

**Comment by kiyonlin** [comment]
I think it's related with browser encoding setting. Change it to `utf-8` will fix the issue.
![image](https://user-images.githubusercontent.com/1214670/103198782-2991bf80-4924-11eb-9e3e-3735aa2689ac.png)
