### ISSUE TITLE
🐛middleware websocket can't be used together with cache

### ISSUE THREAD

**Issue by edisonqkj** [gofiber/fiber#1097]
**Fiber version**
github.com/gofiber/fiber/v2 v2.2.5
github.com/gofiber/websocket/v2 v2.0.2

**Issue description**
In the test demo at https://github.com/gofiber/recipes/blob/master/websocket/main.go, as following, i just added some middlewares(including cache at https://github.com/gofiber/fiber/tree/master/middleware/cache) for http services.

**Code snippet**

```go
package main

import (
         "github.com/gofiber/fiber/v2"
         "github.com/gofiber/fiber/v2/middleware/cache"
	"github.com/gofiber/fiber/v2/middleware/compress"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/requestid"
	"github.com/gofiber/websocket/v2"
)

func main() {
	app := fiber.New()
	app.Use(cors.New())
	app.Use(recover.New())
	app.Use(requestid.New())

	file, err := os.OpenFile("./mylog.log", os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
	if err != nil {
		log.Fatalf("error opening file: %v", err)
	}
	defer file.Close()
	app.Use(logger.New(logger.Config{
		Format:     "[${time}] ${locals:requestid} ${status} - ${latency} ${method} ${path}\n",
		TimeFormat: "2006-01-02",
		TimeZone:   "Local",
		Output:     file,
	}))
	app.Use(compress.New(compress.Config{
		Level: compress.LevelBestSpeed, // 1
	}))

	app.Use(cache.New(cache.Config{
		Next: func(c *fiber.Ctx) bool {
			return c.Query("refresh") == "true"
		},
		Expiration:   30 * time.Minute,
		CacheControl: true,
	}))


	app.Get("/ws", websocket.New(func (c *websocket.Conn) {
		for {
			mt, msg, err := c.ReadMessage()
			if err != nil {
				log.Println("read:", err)
				break
			}
			log.Printf("recv: %s", msg)
			err = c.WriteMessage(mt, msg)
			if err != nil {
				log.Println("write:", err)
				break
			}
		}
	}))

	log.Fatal(app.Listen(":3000"))
	fmt.Println("app is up")
}
```
When the server started, my client sent websocket messages to the server successfully. However, the second websocket connection failed with console message:
> read: websocket: close 1005 (no status)

I must restart the server to make it. 
Finally, i found the solution that the cache middleware must be removed and it works without failure again.

**Comment by kiyonlin** [comment]
How about skipping cache middleware for path `/ws`?

**Comment by edisonqkj** [comment]
> How about skipping cache middleware for path `/ws`?
@kiyonlin 
thanks for your reply. 
Do you mean setting the cache's Next to nil like following? it does not work either.

```
       app.Use(cache.New(cache.Config{
		// Next: func(c *fiber.Ctx) bool {
		// 	return c.Query("refresh") == "true"
		// },
		Next:         nil,
		Expiration:   30 * time.Minute,
		CacheControl: true,
	}))
```

**Comment by kiyonlin** [comment]
I mean 
```go
app.Use(cache.New(cache.Config{
	Next: func(c *fiber.Ctx) bool {
		return c.Query("refresh") == "true" || c.Path() == "/ws"
	},
	Expiration:   30 * time.Minute,
	CacheControl: true,
}))
```

**Comment by edisonqkj** [comment]
> I mean
> 
> ```go
> app.Use(cache.New(cache.Config{
> 	Next: func(c *fiber.Ctx) bool {
> 		return c.Query("refresh") == "true" || c.Path() == "/ws"
> 	},
> 	Expiration:   30 * time.Minute,
> 	CacheControl: true,
> }))
> ```

it works, thanks!

**Comment by kiyonlin** [comment]
Okey, I'll close this. Feel free to re-open it if you have more questions.
