### ISSUE TITLE
🐛 Getting 404 randomly with response "Cannot GET /"

### ISSUE THREAD

**Issue by majined** [gofiber/fiber#1099]
**Fiber version**
2.1.4
**Issue description**
Getting randomly some 404 from Fiber with the string "Cannot GET /". After some source code reading, it seems to be coming from router.go, line 132, which means the path it has found for my request is "/", but it is not the case. I'm doing requests on the path "/Api/api". I've used your logger middleware to confirm this with the following format: "${ip} - [${time}] \"${method} ${url}\" ${status} ${bytesSent} ${latency}\n".
The logs I have when I receive a 404 look like this:
xxx.xxx.xxx.xxx - [30/Dec/2020 10:49:12] "GET / /Api/api?hsh=xxx&usr=xxx&action=listmail" 404 12 1.408µs
Of course, on a successful request I'm getting something like this:
xxx.xxx.xxx.xxx - [30/Dec/2020 10:58:39] "GET /Api/api /Api/api?hsh=xxx&usr=xxx&action=listmail" 200 30 420.385µs
Where the path is right.
So there seems to be a problem where sometime the path found in the request is "/" (or maybe a default value?).
The weird thing is this exact same request would succeed if it was sent again, meaning the request itself has no problem.
This issue happens on every endpoints randomly, even on POST request, returning "Cannot POST /", so it seems to be a global issue.
I also have my app running on 2 different servers, with one server getting less requests than the other.
On the one that get less requests (around 1900 requests per minute), I don't see this issue. It only appears on the server getting more requests (around 3300 requests per minute).
Knowing that, and knowing Fiber and Fasthttp are based on reusing objects through Pools, I was wondering if this problem was not coming from an object being released in the pool too early or something like that.
To be honest, I'm not even sure if the issue comes from Fiber or from Fasthttp, but being desperate after trying to figure out what's wrong reading the Fiber and Fasthttp source code (with no success), I decided to post an issue here.

**Code snippet**

```go
package main

import (
	"fmt"
	"time"

	cfg "pixapi/config"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/favicon"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
	app := fiber.New(fiber.Config{
		Prefork:		false,
		Concurrency:	400,
		IdleTimeout:	15 * time.Second,
		ReadTimeout:	5 * time.Second,
	})

	app.Use(logger.New(logger.Config{
		Next: func(c *fiber.Ctx) bool {
			return cfg.FiberLogOff
		},
		Format:		cfg.Fiber.Log.Format,
		TimeFormat:	"02/Jan/2006 15:04:05",
		Output:		&cfg.FiberLogOutput,
	}))

	app.Use(favicon.New())

	app.Use(recover.New())

	app.Get("/Api/status", func(c *fiber.Ctx) error {
		// Some code
	})

	app.Get("/Api/api", func(c *fiber.Ctx) error {
		// Some code
	})

	app.Post("/Api/sync_reply", func(c *fiber.Ctx) error {
		// Some code
	})

	app.Get("/iptime", func(c *fiber.Ctx) error {
		// Some code
	})

	app.Post("/admin", func(c *fiber.Ctx) error {
 		// Some code	})

	ln, err := net.Listen("tcp", cfg.Fiber.Listener)
	if err != nil {
		fmt.Println(err)
		return
	}
	if err = app.Listener(ln); err != nil {
		fmt.Println(err)
	}
}
```

**Comment by ReneWerner87** [comment]
thank you for your report, unfortunately I do not get this reproduce.

I took your code and tested it with fiber 2.1.4 and 2.3.0

For this i used bombadier and the browser.
```
bombardier -c 200 -n 6000 -d 1m "http://localhost:3000/Api/api?hsh=xxx&usr=xxx"
```

Fiber v2.3.0
go 1.15
MacOs

```go
package main

import (
	"fmt"
	"net"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/favicon"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
	app := fiber.New(fiber.Config{
		Prefork:		false,
		Concurrency:	400,
		IdleTimeout:	15 * time.Second,
		ReadTimeout:	5 * time.Second,
	})

	app.Use(logger.New(logger.Config{
		TimeFormat:	"02/Jan/2006 15:04:05",
		Format: "${ip} - [${time}] \"${method} ${url}\" ${status} ${bytesSent} ${latency}\n",
	}))

	app.Use(favicon.New())

	app.Use(recover.New())

	app.Get("/Api/status", func(c *fiber.Ctx) error {
		// Some code
		return c.SendString(c.Route().Path)
	})

	app.Get("/Api/api", func(c *fiber.Ctx) error {
		// Some code
		return c.SendString(c.Route().Path)
	})

	app.Post("/Api/sync_reply", func(c *fiber.Ctx) error {
		// Some code
		return c.SendString(c.Route().Path)
	})

	app.Get("/iptime", func(c *fiber.Ctx) error {
		// Some code
		return c.SendString(c.Route().Path)
	})

	app.Post("/admin", func(c *fiber.Ctx) error {
		// Some code
		return c.SendString(c.Route().Path)
	})
	ln, err := net.Listen("tcp", "127.0.0.1:3000")
	if err != nil {
		fmt.Println(err)
		return
	}
	if err = app.Listener(ln); err != nil {
		fmt.Println(err)
	}
}
```

What does your server look like, do you use a reverse proxy ? Nginx ? My log entries also look different from yours 
![image](https://user-images.githubusercontent.com/7063188/103349997-de4fec00-4a9e-11eb-81b9-4967ee75dc76.png)


@kiyonlin maybe you can reproduce it ?

**Comment by kiyonlin** [comment]
Hey @majined I'm curious what does `cfg.FiberLogOff` look like? Would you mind to show us?

**Comment by majined** [comment]
My bad for the log format: I've given you the one I originally used but after encountering this issue I've added the path to verify my suspicions. So the right log format is this one: `"${ip} - [${time}] "${method} ${path} ${url}" ${status} ${bytesSent} ${latency}\n"`.
And yes I'm using Nginx, and also Haproxy. On the server receiving less requests (the one where the bug doesn't appear), the requests come from Nginx only. For the other one, where the bug appears, the requests come from Nginx and Haproxy. But I don't think the usage of Nginx or Haproxy is related to this issue, since I also encounter it when doing requests without going through Nginx or Haproxy, and even on local requests. The `/admin` endpoint, for exemple, is used by an admin client on localhost only, and it receives 404 sometimes also. The `/Api/status` is used from another ip, without going through Nginx or Haproxy and it receives 404 sometimes also.
Every requests going to `/Api/api` or `/Api/sync_reply` go through Haproxy or Nginx. Every requests done on `/Api/status` are done directly from an ip on the same local network. Every requests on `/admin` are made from the same machine on `127.0.0.1`. The `/iptime` endpoint is not used yet.
One more info, the string I use for the listen is `":8080"` and the requests are made in ipv6 (not sure if this is relevant).
Here is a simplified version of my haproxy config:
```haproxy
global
       maxconn 200000
        tune.ssl.cachesize 500000
        max-spread-checks 2s
        log /dev/log    local0 debug
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
        stats timeout 30s
        user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        option log-health-checks
        default-server inter 30s
        timeout connect 5s
        timeout client 120s
        timeout server 120s
        timeout queue 5s
        timeout client-fin 1s

frontend terminate-tls
        bind 0.0.0.0:443 ssl crt /etc/haproxy/certificates/cert.pem ca-file /etc/haproxy/certificates/ca.crt verify optional
        mode tcp
        option tcplog
        log global
        tcp-request inspect-delay 5s
        tcp-request content accept if HTTP
        acl host_newapi hdr(host) -i foo.bar.com:80 foo.bar.com
        acl go_api path /Api/api /Api/sync_reply
        acl sync_reply path /Api/sync_reply
        http-request set-header Content-Type text/plain if sync_reply
        use_backend new-pixapi if go_api host_newapi
        default_backend new-pixapi

frontend terminate-tls-https
        bind 0.0.0.0:80 ssl crt /etc/haproxy/certificates/cert.pem ca-file /etc/haproxy/certificates/ca.crt
        mode http
        option httplog
        acl host_newapi hdr(host) -i foo.bar.com:80 foo.bar.com
        http-request deny unless host_newapi
        acl sync_reply path /Api/sync_reply
        acl db_access_only url_param(action) status listmail listalbums listpics listcontacts
        acl fs_access url_param(action) getpic getvid
        http-request set-header Content-Type text/plain if sync_reply
        use_backend new-pixapi if sync_reply || fs_access || db_access_only
        default_backend no-match-https

backend new-pixapi
        log global
        mode http
        option httpchk GET /Api/status
        http-check expect string UP
        server pixapi hostname:8080 check maxconn 500

backend no-match-https
        log global
        mode http
        http-request deny deny_status 400
```

And here is a simplified version of my nginx config:
```nginx
server {
   include listen.conf;
   listen 443 default ssl;
   server_name www.mywebsiter.com;
   index index.php index.html index.htm;
   ssl_certificate     ssl/current/ccc.bundle.crt;
   ssl_certificate_key ssl/current/cccc.com.key;
    ssl_verify_depth 3;
   access_log off;
   error_log   /var/log/nginx/error.log error;
   rewrite_log on;

   location /Appp {
           include /etc/nginx/proxy_params;
           proxy_set_header Connection "";
           proxy_http_version 1.1;
           proxy_pass http://golang ;
   }
}
```

**Comment by ReneWerner87** [comment]
@majined 
We don't get the error, please prepare a minimal setup with which we can test and adjust it.

**Comment by majined** [comment]
Sorry, I have no time to prepare such setup. I will keep investigating on my side. I'm more and more thinking it is related to Haproxy. I will close this issue. Thanks for your time.

**Comment by catalin-me** [comment]
@majined We're currently facing a similar issue while using Fiber under high traffic. Did you manage to find the root cause? :)

**Comment by daddz** [comment]
@ReneWerner87 I ran into this same issue and found a way to reproduce it:

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
)

func AnyMiddleware() fiber.Handler {
	return func(c *fiber.Ctx) error {
		fmt.Printf("before next c.Route().Path: %s\n", c.Route().Path)
		err := c.Next()
		fmt.Printf("after next c.Route().Path: %s\n", c.Route().Path)
		return err
	}
}
func main() {
	app := fiber.New()

	app.Get("/foo", func(c *fiber.Ctx) error {
		fmt.Printf("no middleware c.Route().Path: %s\n", c.Route().Path)
		return c.SendStatus(200)
	})

	app.Use(AnyMiddleware())

	app.Get("/bar", func(c *fiber.Ctx) error {
		return c.SendStatus(200)
	})

	app.Listen(":3000")
}
```

doing `curl http://localhost:3000/foo`:
```
no middleware c.Route().Path: /foo
```

doint `curl http://localhost:3000/bar`:
```
before next c.Route().Path: /
after next c.Route().Path: /bar
```

It seems like `c.Route().Path is only correct/set after `c.Next()` when used inside a middleware.

fiber: v2.13.0

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/123612886-3c1d8080-d803-11eb-8dc9-3a74b858e4a4.png)
no should not be an error, the route contains the path of the registered route

![image](https://user-images.githubusercontent.com/7063188/123613327-9fa7ae00-d803-11eb-9c35-e41c60163206.png)
c.Route is the route which was executed last, 

that means after the c.Next it is the registered route "/bar" for the handler and before it was the path of the middleware which is empty

if you want to have the path of the request, you have to call c.Path()
![image](https://user-images.githubusercontent.com/7063188/123613748-fca36400-d803-11eb-9e16-4c57371e24c6.png)

**Comment by omarcosr** [comment]
Any update on this bug?
