### ISSUE TITLE
🐛 Memory Leak from Compress middleware

### ISSUE THREAD

**Issue by lian-longfeng** [gofiber/fiber#1105]
**Fiber version**
v2.3.2
**Issue description**
My fiber server got killed several times due to OOM. Log shows the server's memory climbed over time and eventually took 3G ~ 4G before Linux kernel kills it.
Just remove the line `app.Use(compress.New())` made the memory stable at around 100M.

pprof shows brotli was holding the memory.
![image](https://user-images.githubusercontent.com/58188246/103904967-fee5fa80-50cb-11eb-990a-5e913545fec7.png)

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

  // Steps to reproduce
  app.Use(compress.New())

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by kiyonlin** [comment]
Hi, I used your code snippet, but I can't reproduce this issue with [wrk](https://github.com/wg/wrk). I suspect the memory leak is related to your other code.

Could you provide more information?

**Comment by lian-longfeng** [comment]
@kiyonlin Thanks for the help looking, my full code is here:
```
package main

import (
	"crypto/tls"
	"log"
	"net"
	"net/http"
	"strings"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/compress"
	"github.com/gofiber/fiber/v2/middleware/limiter"
	"github.com/gofiber/fiber/v2/middleware/pprof"
	"github.com/valyala/fasthttp"
	"golang.org/x/crypto/acme/autocert"
)

var (
	portHTTP    = ":80"
	portTLS     = ":443"
	searchHost  = "http://127.0.0.1:8000"
	hosts       = []string{"www.example.com"}
	fiberConfig = fiber.Config{
		IdleTimeout: 30 * time.Second,
	}
)

func redirect(w http.ResponseWriter, req *http.Request) {
	target := "https://" + req.Host + portTLS + req.URL.Path
	if len(req.URL.RawQuery) > 0 {
		target += "?" + req.URL.RawQuery
	}
	http.Redirect(w, req, target, http.StatusMovedPermanently)
}

var client = fasthttp.Client{
	NoDefaultUserAgentHeader: true,
	DisablePathNormalizing:   true,
}

func main() {
	app := fiber.New(fiberConfig)

	// Middlewares
	app.Use(pprof.New())
	app.Use(limiter.New(limiter.Config{
		Max:        60,
		Expiration: 30 * time.Second,
		KeyGenerator: func(c *fiber.Ctx) string {
			return c.IP()
		},
		LimitReached: func(c *fiber.Ctx) error {
			return c.SendStatus(fiber.StatusTooManyRequests)
		},
	}))
	app.Use(compress.New())

	// routes
	app.Get("/_search/*", func(c *fiber.Ctx) error {
		addr := searchHost + strings.Replace(c.Path(), "/_search", "", 1)
		req := c.Request()
		res := c.Response()
		req.SetRequestURI(addr)
		req.Header.Del(fiber.HeaderConnection)
		req.URI().SetScheme("http")
		if err := client.Do(req, res); err != nil {
			return err
		}
		res.Header.Del(fiber.HeaderConnection)
		return nil
	})

	app.Static("/robots.txt", "robots.txt")
	app.Static("/public", "public")
	app.Static("/static", "static")
	app.Static("/lamatxt", "lamatxt")
	app.Static("/CMS", "CMS")

	app.Get("/*", func(ctx *fiber.Ctx) error {
		return ctx.SendFile("index.html")
	})

	// Certificate manager
	CertManager := &autocert.Manager{
		Prompt:      autocert.AcceptTOS,
		HostPolicy:  autocert.HostWhitelist(hosts...),
		Cache:       autocert.DirCache("./certs"),
		RenewBefore: 3 * 24 * time.Hour,
	}

	TLSConfig := &tls.Config{
		GetCertificate: CertManager.GetCertificate,
		// By default NextProtos contains the "h2"
		// This has to be removed since Fasthttp does not support HTTP/2
		// Or it will cause a flood of PRI method logs
		// http://webconcepts.info/concepts/http-method/PRI
		NextProtos: []string{"http/1.1", "acme-tls/1"},
	}
	ln, _ := net.Listen("tcp", portTLS)
	ln = tls.NewListener(ln, TLSConfig)

	go http.ListenAndServe(portHTTP, http.HandlerFunc(redirect))
	log.Fatal(app.Listener(ln))
}
```

**Comment by kiyonlin** [comment]
You did not provide static files. Could you give us a runnable repo and the reproduce steps?

**Comment by lian-longfeng** [comment]
@kiyonlin The static file would include my SSL certificate, obviously I can't provide that.
You can use any dummy website static files, html, some js and json.
Also, I found a workaround, which is to "downgrade" the compress middleware to not use "brotli" compression, here is my middleware:
```
// DisableBrotli remove "br" from "Accept-Encoding" header, so compress middleware will not use "brotli" algorism.
func DisableBrotli() fiber.Handler {
	return func(c *fiber.Ctx) error {
		ae := c.Request().Header.Peek("Accept-Encoding")
		c.Request().Header.SetBytesV(
			"Accept-Encoding",
			bytes.Replace(ae, []byte("br"), []byte(""), 1),
		)
		return c.Next()
	}
}
func main() {
  app := fiber.New()

  app.Use(module.DisableBrotli())
  app.Use(compress.New())

  log.Fatal(app.Listen(":3000"))
}
```
No memory issue so far, so I suspect the memory leak is from "brotli" compression, and it's also what pprof indicates. Too bad I didn't save the pprof file, otherwise might be easier for you.

Also can you show me how you did the test with "wrk", I can try if I can reproduce on my local.

**Comment by kiyonlin** [comment]
> Also could you show me how you did the test with "wrk"? maybe I can try if I can reproduce on my local.

You should install wrk and run `wrk "http://127.0.0.1:port"`

**Comment by kiyonlin** [comment]
> The static file would include my SSL certificate, obviously I can't provide that.
> You can use any dummy website static files, html, some js and json.

It's nice if you can simplify the demo(remove ssl) and reproduce this issue.

**Comment by lian-longfeng** [comment]
@kiyonlin I found the autosaved pprof allocs profile, is it helpful for you?
[pprof.server.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz](https://github.com/gofiber/fiber/files/5782156/pprof.server.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz)
[pprof.server.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz](https://github.com/gofiber/fiber/files/5782157/pprof.server.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz)

**Comment by kiyonlin** [comment]
> @kiyonlin I found the autosaved pprof allocs profile, is it helpful for you?
> [pprof.server.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz](https://github.com/gofiber/fiber/files/5782156/pprof.server.alloc_objects.alloc_space.inuse_objects.inuse_space.008.pb.gz)
> [pprof.server.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz](https://github.com/gofiber/fiber/files/5782157/pprof.server.alloc_objects.alloc_space.inuse_objects.inuse_space.007.pb.gz)

I can see this **alloc_space**:
```
      File: server
Type: alloc_space
Time: Jan 6, 2021 at 10:51am (CST)
Showing nodes accounting for 11851.69MB, 100% of 11851.69MB total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                         8005.75MB   100% |   github.com/andybalholm/brotli.ringBufferWrite /go/pkg/mod/github.com/andybalholm/brotli@v1.0.1/ringbuffer.go:96
                                            3.52MB 0.044% |   github.com/andybalholm/brotli.ringBufferWrite /go/pkg/mod/github.com/andybalholm/brotli@v1.0.1/ringbuffer.go:89
 8009.27MB 67.58% 67.58%  8009.27MB 67.58%                | github.com/andybalholm/brotli.ringBufferInitBuffer /go/pkg/mod/github.com/andybalholm/brotli@v1.0.1/ringbuffer.go:51
----------------------------------------------------------+-------------
```
So did you send a **huge** file?

And I have no time to dive deeper into `andybalholm/brotli` at the moment. If you have to use it, you can submit an issue on that repo.

**Comment by lian-longfeng** [comment]
@kiyonlin no, there's no large file.
And I'm able to reproduce it now with wrk.
`server.go`
```
func main() {
	app := fiber.New()
	app.Use(compress.New())

	app.Static("/", "./")

	app.Listen(":4000")
}
```
Put a 1Mb dummy.json in the root, I use this: https://jsonplaceholder.typicode.com/photos
Start the server and run `wrk -H "Accept-Encoding: br" -c 200 http://localhost:4000/dummy.json`

Then you will see the memory go up to 4G:
![image](https://user-images.githubusercontent.com/58188246/103963383-1bfbe700-5127-11eb-9226-26d3b53be5ee.png)

**Comment by kiyonlin** [comment]
I think I know the reason.

When using `br` to compress response, fasthttp uses `sync.Pool` to [reuse](https://github.com/valyala/fasthttp/blob/master/brotli.go#L44-L56) memory. So more concurrency count, more allocated memory. When you use `-c 100`, the memory will be around 2G.

So this is not strictly a memory leak.

**Comment by lian-longfeng** [comment]
> When using `br` to compress response, fasthttp uses `sync.Pool` to [reuse](https://github.com/valyala/fasthttp/blob/master/brotli.go#L44-L56) memory. So more concurrency count, more allocated memory. When you use `-c 100`, the memory will be around 2G.

Yea I also notice it's connection related, but why when the test is done, the memory is not released?

**Comment by kiyonlin** [comment]
They are in `sync.pool` and are slowly releasing, around 2M/s. You can observe the memory usage for minutes.

**Comment by lian-longfeng** [comment]
2M/s is ok, but on my machine, I don't see any decline for minutes. The same thing on my server, memory history is a simple climbing graph.
Also In real cases, 200 connection is pretty normal, so if `br` is problematic, can we add a config to tell compress middleware not to use `br`?

**Comment by kiyonlin** [comment]
I found this issue valyala/fasthttp#782 and may you should try [this solution](https://github.com/valyala/fasthttp/issues/782#issuecomment-617764897) .
