### ISSUE TITLE
How to forcibly close an http connection?

### ISSUE THREAD

**Issue by GarryGaller** [gofiber/fiber#1107]
Fiber does not have a method to close the connection. It is only available in fasthttp. More precisely, fasthttp has a Conn () method, which in turn returns net.Conn and which has a Close method. Access to the fasthhtp instance is not exported (fasthhtp field in the fiber.Ctx structure). How to be?

**Comment by kiyonlin** [comment]
Please see [ctx.Context](https://docs.gofiber.io/api/ctx#context).
