### ISSUE TITLE
c.JSON() driver 🚀 

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#1108]
It would be nice to be able to pick different json marshalling drivers instead of stdlib's "encoding/json".

There is so many faster ones:

1. https://github.com/json-iterator/go (drop in replacement for encoding/json)
2. https://github.com/valyala/fastjson
3. https://github.com/francoispqt/gojay
4. https://github.com/buger/jsonparser

**Comment by hi019** [comment]
We use https://github.com/segmentio/encoding/blob/master/json/README.md for json operations

**Comment by Fenny** [comment]
Fiber currently uses segmentio which is currently the fastest json encoder as a drop in replacement for STF (faster than json iterator https://github.com/json-iterator/go/issues/455 ) without generating files like fastjson.

JSON benchmark results: https://www.techempower.com/benchmarks/#section=test&runid=706be841-9ca9-4930-a8dd-c238592e3767&hw=ph&test=json&l=zijxtr-73&a=2

I would accept an PR where you could override the JSON engine in `Config` 👍

**Comment by yquansah** [comment]
I seek to address this issue here: https://github.com/gofiber/fiber/pull/1121 if you all want to take a look.

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/releases/tag/v2.4.0
