### ISSUE TITLE
🚀  Are there plans to integrate opentelemetry instrumentation

### ISSUE THREAD

**Issue by AchoArnold** [gofiber/fiber#1109]
**Is your feature request related to a problem?**

No  it is not

**Describe the solution you'd like**

Something like this https://github.com/open-telemetry/opentelemetry-go-contrib/tree/master/instrumentation/github.com/astaxie/beego/otelbeego so we get automatic instrumentation  for requests when we use opentelemetry. We could also bind this qith the request ID middleware such that it generates an actual trace/id, spanID for each new requests

**Describe alternatives you've considered**

There are no alternatives. I've had to build this myself into almost every app I build. I have an instrumentation middleware like this which creates trace/span IDs. 

**Sample  middleware fo creating trace/spanID's**

```go
package middlewares

import (
	"context"
	"fmt"
	"github.com/gofiber/fiber/v2"
	log "github.com/sirupsen/logrus"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/label"
	"go.opentelemetry.io/otel/trace"
)

func TraceContext(logger *log.Entry, namespace string) fiber.Handler {
	return func(c *fiber.Ctx) error {
		traceCtx, span := otel.Tracer(namespace).Start(context.Background(), fmt.Sprintf("%s %s", c.Method(), c.OriginalURL()))
		defer span.End()
		ctx := span.SpanContext()

		logger.WithFields(log.Fields{
			"traceID":      ctx.TraceID.String(),
			"spanID":       ctx.SpanID.String(),
			"traceSampled": ctx.IsSampled(),
		}).Trace(
			fmt.Sprintf(
				"trace has been set. traceID = %s spanID = %s, traceSampled = %t",
				ctx.TraceID.String(),
				ctx.SpanID.String(),
				ctx.IsSampled()),
		)


		traceID := ctx.TraceID.String()
		span.SetAttributes(label.Key("traceID").String(traceID))
		span.SetAttributes(label.Key("SpanID").String(span.SpanContext().TraceID.String()))
		span.SetAttributes(label.Key("traceFlags").String(fmt.Sprintf("%v", ctx.TraceFlags)))

		c.Locals("traceContext", trace.ContextWithSpan(traceCtx, span))

		// Go to next middleware:
		response := c.Next()

		return response
	}
}
```
</details>

**Additional context**

I will love to work/help on this project if it's something you guys think is helpful to the community. I also think it will be nice to support this at the level of the `*fiber.Ctx` object such that we can automatically trace every request at the with their specific handlers.

What do you guys think?

**Comment by kiyonlin** [comment]
Thanks for the suggestion! Personally I think this is a good idea for private/upper projects. But it's a little heavy to integrate this feature into fiber framework.

**Comment by AchoArnold** [comment]
Yep, I think perhaps it shouldn't be backed into the framework directly as I guess many people don't care about stuff like this but perhaps have a middleware that can do this. Perhaps the framework itself could support an API to get the complete user context object. but I'm looking at the source code now, it uses the fasthttp to store/retrieve the context values so this is a bit tricky.

**Comment by kiyonlin** [comment]
We are trying to keep fiber slim, so we will control the introduction of external packages. It's good to know you find an expected middleware. 

> Perhaps the framework itself could support an API to get the complete user context object. but I'm looking at the source code now, it uses the fasthttp to store/retrieve the context values so this is a bit tricky.

I believe that `ctx.Local` is already fit for this requirement, like you do in your code snippet. what do you think?

**Comment by AchoArnold** [comment]
Yep that works Thanks @kiyonlin
