### ISSUE TITLE
🚀 Could the "middleware/monitor" show the total and/or free memory of the operating system? 

### ISSUE THREAD

**Issue by hitalos** [gofiber/fiber#1112]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Add a graph line to show the total and/or free memory of OS.

**Additional context**
Can I send a PR with a possible solution?

**Comment by Fenny** [comment]
PR's are always welcome!

**Comment by xenowits** [comment]
> **Is your feature request related to a problem?**
> No.
> 
> **Describe the solution you'd like**
> Add a graph line to show the total and/or free memory of OS.
> 
> **Additional context**
> Can I send a PR with a possible solution?
> 

So are u currently working on this?

**Comment by hitalos** [comment]
> > **Is your feature request related to a problem?**
> > No.
> > **Describe the solution you'd like**
> > Add a graph line to show the total and/or free memory of OS.
> > **Additional context**
> > Can I send a PR with a possible solution?
> 
> So are u currently working on this?

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/releases/tag/v2.4.0
