### ISSUE TITLE
🤗 How to use fasthttp client in fiber?

### ISSUE THREAD

**Issue by gxdvip** [gofiber/fiber#1114]
**Question description**

I don’t know how to get fasthttp client in fiber.
I want to request an open api.

**Comment by kiyonlin** [comment]
Fiber doesn't wrap anything about fasthttp client, you can use it directly.

**Comment by Fenny** [comment]
Fiber does not wrap the fh client like @kiyonlin mentioned. But you can easily import the fh package to use the client along with the `Request` and `Response` properties directly.

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/valyala/fasthttp"
)

func main() {
    app := fiber.New()
    app.Get("/", func(c *fiber.Ctx) error {
        req := c.Request()
        res := c.Response()
        req.SetRequestURI("https://api.ipify.org?format=json")
        return client.Do(req, res)
    })
    log.Fatal(app.Listen(":3000"))
}
```

**Comment by gxdvip** [comment]
@Fenny Why not wrap it up? This is more convenient to use.
