### ISSUE TITLE
🤗 How to get logger...

### ISSUE THREAD

**Issue by itgelo** [gofiber/fiber#1115]
**Question description**
How to get response body and all query string without specific key?

**Code snippet** _Optional_

```go
​app​.​Use​(​logger​.​New​(logger.​Config​{
        ​Format​: "${query} ${res-body}​\n​"​,
}))
```

**Comment by Fenny** [comment]
Full query or response body is not available in logger, PR's are welcome!
https://github.com/gofiber/fiber/tree/master/middleware/logger#constants

**Comment by ReneWerner87** [comment]
thanks @xenowits for the pull request #1132

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/releases/tag/v2.4.0
