### ISSUE TITLE
 Cache Middleware: cache only responses where status == 200

### ISSUE THREAD

**Issue by GarryGaller** [gofiber/fiber#1116]
How to make sure that responses with a status not equal to 200 are not cached?

**Comment by hi019** [comment]
You can use the Next config param to check the status code. Check the documentation in the middleware folder. I'm on mobile right now so let me know if you need a sample later.

**Comment by GarryGaller** [comment]
The Next function is not applicable for the response status, because the status is assigned to the response only before it is sent.
Accordingly, you cannot check the status in the Next function.

**Comment by xenowits** [comment]
Hi @Fenny . I want to solve this issue. Can u plz point me to the correct direction??
Also @GarryGaller How did u know that nothing was cached? Plz help me understand the issue.

**Comment by GarryGaller** [comment]
xenowits, "How did u know that nothing was cached?"
My logger (not the fiber logger) outputs intermediate information about the execution of the work.
If the data is cached, there is no output. There is only the final fiber logger.

**Comment by kiyonlin** [comment]
Please try v2.4.1, and feel free to re-open this if you still have problems.
