### ISSUE TITLE
🚀 Recover Middleware Debug Stacktrace

### ISSUE THREAD

**Issue by OrenBen-Meir** [gofiber/fiber#1119]
I think it would be a good idea that the recover middleware has an option to show the stack trace of your panic. It should be off by default but for development and staging environments, it is very helpful when debugging.

**Comment by ReneWerner87** [comment]
thanks @tianjipeng for the pull request #1131

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/releases/tag/v2.4.0
