### ISSUE TITLE
Can you use websocket from fastws? 

### ISSUE THREAD

**Issue by hiqsociety** [gofiber/fiber#1122]
https://github.com/dgrr/fastws

this is much better than the websocket u are using now

**Comment by kiyonlin** [comment]
Thanks for the suggestion!

I see that fastws now is not going to support `Read message using io.Reader` and `Write message using io.WriteCloser`. 

Further more, `fastws.Conn` does not have same signatures against `websocket.Conn`.

So if we replace gorilla with fastws, it will cause breaking changes.

I think you can develop another websocket middleware on top of fastws and make a PR to our [third part middleware](https://github.com/gofiber/fiber#-third-party-middlewares).
