### ISSUE TITLE
Docs down for some users

### ISSUE THREAD

**Issue by hi019** [gofiber/fiber#1123]
https://docs.gofiber.io is responding with Cloudflare 521's for some users. Please do not create another issue about this as we are aware of the problem and are working to resolve it. The docs are hosted on Gitbook, so it is likely an issue on their side.

For now, affected users can view our Github repository: https://github.com/gofiber/docs

**Comment by Fenny** [comment]
I disabled cloudflare proxy for now, this should resolve the issue for NA clients.
