### ISSUE TITLE
vscode Press F5 to open debugging, print garbled

### ISSUE THREAD

**Issue by da4z** [gofiber/fiber#1124]
**Question description**
vscode Press F5 to open debugging, print garbled
**Code snippet** _Optional_

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/recover"
)

func main() {
	app := fiber.New()
	app.Use(logger.New())
	app.Use(recover.New())

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World 👋!")
	})

	app.Listen(":3000")
}
```
![批注 2021-01-21 215120](https://user-images.githubusercontent.com/46473093/105360165-44a9d380-5c33-11eb-917c-3d1019cc7a5e.png)

**Comment by Fenny** [comment]
@chinaapus, can you try it with the english pack?

**Comment by chinaapus** [comment]
@Fenny using english package , It seems that echo is normal

![批注 2021-01-22 215951](https://user-images.githubusercontent.com/46473093/105500040-46d86480-5cfd-11eb-97d3-40b40dc58187.png)


![批注 2021-01-22 215525](https://user-images.githubusercontent.com/46473093/105499816-f8c36100-5cfc-11eb-996e-b52eaa766d3a.png)

**Comment by sotanodroid** [comment]
Confirm that.

vscode settings:
```
  {
      "name": "Golang Delve Debugger",
      "type": "go",
      "request": "launch",
      "mode": "auto",
      "program": "${workspaceFolder}",
      "env": {},
      "args": []
  },
```

Golang 1.15.4
Fiber 2.3.3

![image](https://user-images.githubusercontent.com/37491198/105886001-f756a900-601a-11eb-996c-6fcc8652d47c.png)
