### ISSUE TITLE
how to use the go-socket.io replace fiber websocket

### ISSUE THREAD

**Issue by svcg** [gofiber/fiber#1126]
I use the `socket.io-client.js` in the front end. Because i want to listen something of events. 
The gofiber/websocket isn't unable the project requirements. 
When i use the `go-socket.io `, appear anything of the error.
the demo link : https://github.com/googollee/go-socket.io/tree/master/_example

that is my code 

```
      
      // Router fiber.Router 

      // server,_ := socketio.NewServer(&opts)  //opts setting cors

	Router.Get("/socket.io/", adaptor.HTTPHandlerFunc(server.ServeHTTP))

	Router.Post("/socket.io/", adaptor.HTTPHandlerFunc(server.ServeHTTP))
```

**Comment by kiyonlin** [comment]
Sorry, I can't understand your issue. Could you give us more error info or a runnable demo to reproduce your issue?

**Comment by kiyonlin** [comment]
```go
package main

import (
	"github.com/gofiber/adaptor/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	socketio "github.com/googollee/go-socket.io"
	"github.com/googollee/go-socket.io/engineio"
)

func main() {
	app := fiber.New()

	app.Use(logger.New())

	server, _ := socketio.NewServer(&engineio.Options{})

	app.Get("/socket.io", adaptor.HTTPHandlerFunc(server.ServeHTTP))

	app.Post("/socket.io", adaptor.HTTPHandlerFunc(server.ServeHTTP))

	_ = app.Listen(":3000")
}
```
I use `websocat` to test it and fail

```hs
websocat ws://127.0.0.1:3000/socket.io
websocat: WebSocketError: Received unexpected status code (400 Bad Request)
websocat: error running
```

I don't think `socket.io` is fit for fiber.

**Comment by hi019** [comment]
Yep, socket.io uses a specific 'protocol' or format on top of websockets (or fallbacks like http) which we don't support.

**Comment by svcg** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Yes, I test always like your. In fact , If I use the fiber/websocket, just use the original websocket request. My project wanna use the socket.io.js like this library  ( Nuxt + fibberr )， listen events and dosomething.Are you plan update fiber/websocket? Support some event listen.. eg: file\msg\ etc
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                cleveng
                            
                    
                        
                            
                                    cleveng@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 01/22/2021 11:28，kiyon<notifications@github.com> wrote： 



package main

import (
	"github.com/gofiber/adaptor/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
	socketio "github.com/googollee/go-socket.io"
	"github.com/googollee/go-socket.io/engineio"
)

func main() {
	app := fiber.New()

	app.Use(logger.New())

	server, _ := socketio.NewServer(&engineio.Options{})

	app.Get("/socket.io", adaptor.HTTPHandlerFunc(server.ServeHTTP))

	app.Post("/socket.io", adaptor.HTTPHandlerFunc(server.ServeHTTP))

	_ = app.Listen(":3000")
}
I use websocat to test it and fail
websocat ws://127.0.0.1:3000/socket.io
websocat: WebSocketError: Received unexpected status code (400 Bad Request)
websocat: error running
I don't think socket.io is fit for fiber.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kiyonlin** [comment]
> Are you plan update fiber/websocket? Support some event listen.

No I don't think so at the moment.

**Comment by doquangtan** [comment]
Using this https://github.com/doquangtan/gofiber-socket.io
