### ISSUE TITLE
Hijack connection🚀 

### ISSUE THREAD

**Issue by LyncHub** [gofiber/fiber#1128]
**Is your feature request related to a problem?**
Yes

**Describe the solution you'd like**
Please add some sort of Hijack method as provided in both the standard http package as well as fasthttp.

**Describe alternatives you've considered**
I can't find any.

**Additional context**
I am trying to use gofiber as a proxy server. I would like to hijack the connection and tunnel the data between a client and another origin server. I can not find any sort of hijack implementation provided in the package. I do see that this framework is built on fasthttp. It does appear that fasthttp providers support for connection hijacking. However it doesn't seem to have been implemented in this framework.

**Comment by kiyonlin** [comment]
Do you mean this?
```go
app.Get("/hijack", func(c *fiber.Ctx) error {
		c.Context().Hijack(func(c net.Conn) {
			// Hi jack!
		})
		return c.SendString("hijacked")
	})
```
