### ISSUE TITLE
🚀 cache middleware: set maximum size of cache

### ISSUE THREAD

**Issue by sweepyoface** [gofiber/fiber#1136]
**Is your feature request related to a problem?**

In a way. My problem is that I want to set `Cache-Control: public, max-age=31536000` on my responses, but when using the cache middleware that also means I have to cache the response on the server side for the same duration. This brings up memory usage concerns. 

**Describe the solution you'd like**

I'd like to set the maximum size that the cache is allowed to be, and have the middleware start expiring the oldest entries when it reaches that limit.

**Describe alternatives you've considered**

I've considered just setting process memory limits, but that doesn't seem ideal. This issue could also be solved by decoupling the server side and client side caching durations and having an option to configure both, but this proposal solves two problems at the same time.

**Additional context**

The duration of my server side cache is not all that important, as it will be behind a CDN caching layer. It's simply there as a fallback, so I'm happy with the duration of 30 minutes. This is too short for `Cache-Control` however.

**Comment by xenowits** [comment]
@ReneWerner87 can u plz assign me to this issue?

**Comment by ReneWerner87** [comment]
Sure

**Comment by xenowits** [comment]
@ReneWerner87 any ideas how this can be implemented? I have been thinking but couldn't get any definitive idea.

**Comment by sweepyoface** [comment]
To take the same approach as many popular caching libraries, one could assign a weight to each entry (based on its size) and then configure the maximum weight of the cache. Lower-weighted items would be evicted first using some sort of logic.

**Comment by ReneWerner87** [comment]
@xenowits i saw something in fasthttp library, will share it with you in some hours

**Comment by ReneWerner87** [comment]
hmm had just looked, but find nothing

think you would have to look in the garbage collector loop again and again, how large the dataset is (unsafe.SiteOf) and then if necessary the oldest out, but for this they must first be marked or you create a slice with the keys in which order was added

would do it concurrently in the garbage collector, of course you can do it every time with the set, but then the time of the handler is extended

if you do it in the garbage collector, you can't be 100% sure that the limit won't be exceeded for a short time, but it would be good for the whole process, maybe you go down 5% from the defined max.

**Comment by conorbros** [comment]
Is this still in progress?

**Comment by ReneWerner87** [comment]
suspect @xenowits had no idea, so he did not continue working

@gofiber/contributors if someone has time and an idea how to solve this, we are always happy about pull requests

**Comment by si3nloong** [comment]
@ReneWerner87 i can handle this

**Comment by ReneWerner87** [comment]
Yes sure

**Comment by ReneWerner87** [comment]
@si3nloong any update to the issue ?
