### ISSUE TITLE
🐛 Session corrupted after save to sqlite3

### ISSUE THREAD

**Issue by hakwerk** [gofiber/fiber#1138]
**Fiber version**
v2.3.3

**Issue description**
When running below test, after setting the name and then getting it, the value is as expected. But after the Save() call the second get fails, the result is nil.
Then when running the test again (now the file fiber.sqlite3 exists) it crashes with a "panic: reflect: New(nil)" and the suggestion to use RegisterType. This is my main issue but I assume the actual problem is that the session is corrupted after saving it.

**Code snippet**

```go
package session

import (
	"testing"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/gofiber/storage/sqlite3"
	"github.com/gofiber/utils"
	"github.com/valyala/fasthttp"
)

func Test_Session(t *testing.T) {
	storage := sqlite3.New()
	store := session.New(session.Config{
		Storage: storage,
	})

	// fiber instance
	app := fiber.New()

	// fiber context
	ctx := app.AcquireCtx(&fasthttp.RequestCtx{})
	defer app.ReleaseCtx(ctx)

	// set cookie
	ctx.Request().Header.SetCookie(store.CookieName, "123")

	// get session
	sess, _ := store.Get(ctx)

	// set value
	sess.Set("name", "john")

	// get value
	name := sess.Get("name")
	utils.AssertEqual(t, "john", name)

	// save session to database
	sess.Save()

	// get value after save
	name = sess.Get("name")
	utils.AssertEqual(t, "john", name)
}
```

**Comment by Refuel-ZL** [comment]
me too

**Comment by Refuel-ZL** [comment]
> 我也是
solved 
store.RegisterType(storage{})

**Comment by tianjipeng** [comment]
Maybe I found the reason. ``session.Save`` will call ``gotiny.Marshal`` and ``gotiny.Marshal`` will  build ``buildEncEngine``. It  will register type name and ``reflect.Type``. But in test case, when we get exist data from storage first, type name and ``reflect.Type`` are not registered. So, as we add ``store.RegisterType("")``, test case can pass, like this:
```go
func Test_SessionSqlite3(t *testing.T) {
	storage := sqlite3.New()
	store := New(Config{
		Storage: storage,
	})

	store.RegisterType("")

	// fiber instance
	app := fiber.New()

	// fiber context
	ctx := app.AcquireCtx(&fasthttp.RequestCtx{})
	defer app.ReleaseCtx(ctx)

	// set cookie
	ctx.Request().Header.SetCookie(store.CookieName, "123")

	// get session
	sess, _ := store.Get(ctx)

	// set value
	sess.Set("name", "john")

	// get value
	name := sess.Get("name")
	utils.AssertEqual(t, "john", name)

	// save session to database
	sess.Save()

	// get value after save
	sess, err := store.Get(ctx)
	utils.AssertEqual(t, nil, err)
	name = sess.Get("name")
	utils.AssertEqual(t, "john", name)
}
```
@Fenny Is it reasonable for  user to register primitive type? Maybe we can initialize this?
ps. @hakwerk you should not use ``sess`` after calling ``sess.Save``.

**Comment by tianjipeng** [comment]
@ReneWerner87 Could you confirm whether it is designed to call ``buildEncEngine `` lazily or kind of bug that need to fix?

**Comment by ReneWerner87** [comment]
I will check this tomorrow

**Comment by ReneWerner87** [comment]
am not an expert with the gotiny library and the session middleware, asked fenny for help

**Comment by Fenny** [comment]
Hmm I need to investigate this, the `RegisterType` is designed to be able to marshal / unmarshal custom types and store them in a database. I didn't test it yet, but I'm not sure why we need to register an empty type for it to work.

**Comment by sixcolors** [comment]
I have the issue too... any type after restarting the service does not work.

**Comment by Thomas-Webber** [comment]
Hello, I had the same issue, I was saving multiple strings and int in a session like so:
```go
sess.Set("name", "john")
sess.Set("code", 1234)
```

Registering the types solved the issue:
```go
...
store := New(Config{Storage: storage})
store.RegisterType("")
store.RegisterType(1)
...
```

**Comment by vietlibads** [comment]
> Hello, I had the same issue, I was saving multiple strings and int in a session like so:
> 
> ```go
> sess.Set("name", "john")
> sess.Set("code", 1234)
> ```
> 
> Registering the types solved the issue:
> 
> ```go
> ...
> store := New(Config{Storage: storage})
> store.RegisterType("")
> store.RegisterType(1)
> ...
> ```

I have tried this, it works but error when trying to intergrate with casbin middleware :( 
Please guide this on Fiber's docs @Fenny

**Comment by hsluoyz** [comment]
@vietlibads can you post the casbin integration code?

**Comment by vietlib** [comment]
I have also removed casbin MW, but it still the same error ```[session] Register this type first with the `RegisterType` method.```
I use Redis Session, here is my Redis Middleware code:

```package middleware

import (
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/gofiber/storage/redis"
)

var SessionStore *session.Store

func init() {
	// Initialize custom config
	store := redis.New(redis.Config{
		Host:     "127.0.0.1",
		Port:     6379,
		Username: "",
		Password: "",
		Database: 0,
		Reset:    false,
	})

	SessionStore = session.New(session.Config{
		Storage: store,
	})
	SessionStore.RegisterType("")
	SessionStore.RegisterType(1)
}
```
