### ISSUE TITLE
🐛 Static File in v2 doesn't work

### ISSUE THREAD

**Issue by ParvizMoshfeg** [gofiber/fiber#1142]
**Fiber version**
v2.4.0

**Issue description**
When I use this simple Code here for v1, it works well. You can see it here http://con.onl/hero/ .
HUGO is used to create the static site "hero". The same code with v2 doesn't work at all.
Would you please check, what is wrong here. Thank you.

**Code snippet**

package main

import  "github.com/gofiber/fiber/v2" 

func main() {
    app := fiber.New()
    app.Static("/hero", "/www/sites/hero/public")
    app.Listen(":80")
}

**Comment by taisph** [comment]
@ParvizMoshfeg Could you add some logs or other indication that supports "doesn't work at all"?

In any case, the code works here. Note that `app.Listen(":80")` will return the error `listen tcp4 :80: bind: permission denied` if it cannot bind to port 80, which is usually the case when not running as root. It could also return `listen tcp4 :80: bind: address already in use` if the port is already in use. Always check for errors.

**Comment by ParvizMoshfeg** [comment]
Hello Taisph. Thank your ro your replay.
I use a fresh Ubuntu 20.04.2 LTS  and there are only a control panel "aaPanel" , Golang and HUGO installed.
I'm sure that port 80 is free, when I start the service, because, first I stoped the service of fiber/v1 and check the service status, second I see the port status on my control panel: "not listening". After that, I change the line with import "github.com/gofiber/fiber/v2" othing else. Then I make a go build on this project directory. There is no errors. After that, I start again the Linux-Service: service fiber-static start   then I check again the status: service fiber-static status  it looks good and confirms that fiber is running without any error: 
     Loaded: loaded (/lib/systemd/system/fiber-static.service; disabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-02-01 17:34:01 UTC; 5s ago
     Fiber v2.4.0   http://127.0.0.1:80   Handlers 1    Processes 1    Prefork Disabled     PID 8009
Right now, this version is running on http://con.onl/hero   The first index.html on main folder appears in browser. The problem are all subfolders, they are not reachable. For example, wenn you click on "Services" you have URL http://con.onl/hero/services/ an you see in browser "Cannot GET /hero/services/" the same with all other Subfolder.
I let the Fiber-v2 running on http://con.onl/hero/   so you can have a look into sourcecode. Be aware, that after first unseccesfull access (for example http://con.onl/hero/services/ ) you don't get even the main URL http://con.onl/hero anymore. I check again the status of service of fiber-static on Ubuntu and it seems exactly the same like before, every things looks running fine. But the Website under http://con.onl/hero/ is not reachable anymore. I restart the service now, that you can get you own experience. Thank you for your help.

**Comment by taisph** [comment]
http://con.onl/hero/index.html works, so try configuring app.Static to use index.html by default. Like so:

```
app.Static("/hero", "/www/sites/hero/public", fiber.Static{Index: "index.html"})
```

**Comment by ParvizMoshfeg** [comment]
Yes, the http://con.onl/hero/index.html  works. Also the http://con.onl/hero works.
The Problem is, as soon as you click on a menu (like Services or Work) then you get in brwoser this:
Cannot GET /hero/services/

services and work are subfolders in Mainfolder hero/public 
I've puted your Code in main.go and stoped the service and again started it. But  it doesn't help. I will try the same thing on my Windows and another Linux, this time a Centos. Just to be sure, that this problem is not related to my OS. I will send you the result in a few hours. Til later.

**Comment by ParvizMoshfeg** [comment]
Hello. I've finished my tests and I can confirm, that the behavior on Windwos10 is excatly the same like on Linux.
But I found out, what works and what dosn't work. In both cases I didn't see any error or messages.

____________________________________________________________________________
What works in v1 and v2:  When not using any prefix neither in Fiber-Code nor in HUGO-Config.toml
HUGO-Config.toml (first line):
baseURL = "/"

package main
import  "github.com/gofiber/fiber/v2" 
func main() {
    app := fiber.New()  
    app.Static("/", "./hero/public")
    app.Listen(":80")

_________________________________________________________________________________
What worked in v1 (but not in v2):  When using prefix "hero" in both Fiber-Code and in HUGO-Config.toml
HUGO-Config.toml (first line):
baseURL = "/hero"

package main
import  "github.com/gofiber/fiber" 
func main() {
    app := fiber.New()  
    app.Static("/hero", "./hero/public")
    app.Listen(":80")

_________________________________________________________________________________
What doesn't worked in both v1 and v2:  When using prefix "hero" in Fiber-Code but not using HUGO-Config.toml or vice vera. It would be a mismatch of configurations anyway. It is logical, when Fiber doesn't show the static Files correctly.

For the moment, I can live with the solution, not to use any prefix. when I use HUGO. But maybe other persons want to use Fiber with prefix based on static Files of HUGO . This case worked in v1 and doesn't work anymore in v2.

**Comment by ParvizMoshfeg** [comment]
Hello, I've checked other SSGs than Hugo, like Gatsby and Jekyll. They have also a concept of baseurl which allows them serve the website from a url that has a sub directory. So I guess, this Issue of using Prefix is not trivial.

**Comment by ParvizMoshfeg** [comment]
You can try HUGO-Theme from here:
https://github.com/zerostaticthemes/hugo-hero-theme

**Comment by pde-rent** [comment]
Hi all, I'm facing the exact same issue with v2.5.0 (only tried on windows)
