### ISSUE TITLE
SetUserValue vs Locals 🤗 

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#1143]
I was wondering what the intended use case of `SetUserValue` vs `Locals` was?

They both seem to be request-scoped and you set data and retrieve the stored value.

**Comment by kiyonlin** [comment]
`Locals` comes from [Express/locals](https://expressjs.com/en/api.html#res.locals), because Fiber is an Express inspired web framework.

**Comment by pjebs** [comment]
which should I use?

**Comment by kiyonlin** [comment]
> which should I use?

`Locals` is only a wrapper of `SetUserValue`, so it's up to you.
