### ISSUE TITLE
Question regarding graceful shutdown.

### ISSUE THREAD

**Issue by dpjungmin** [gofiber/fiber#1146]
I was trying out the **graceful shutdown** example from [recipes](https://github.com/gofiber/recipes/tree/master/graceful-shutdown) and fell into a problem.

I followed the graceful shutdown example and it worked well when I sent an interrupt signal before sending any requests. However, after I send a `GET` request to `/`, the application was hanging on at `app.Shutdown()`.

Could I get any help regarding this issue?

I'm new to **Go** and I'm not sure what is causing this problem. This may be just a problem with my machine. 

This is the code I used.

```go
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello world!")
	})

	// Listen from a different goroutine
	go func() {
		if err := app.Listen(":3000"); err != nil {
			log.Panic(err)
		}
	}()

	c := make(chan os.Signal, 1)  
	signal.Notify(c, os.Interrupt, syscall.SIGTERM) 

	_ = <-c // This blocks the main thread until an interrupt is received
	fmt.Println("Gracefully shutting down...")
	_ = app.Shutdown()

	fmt.Println("Running cleanup tasks...")
}
```

**Comment by kiyonlin** [comment]
Hey @dpjungmin I guess you used a browser to send a request. In this case, you should set a `ReadTimeout` in fiber.Config like
```go
app := fiber.New(fiber.Config{ReadTimeout: time.Second * 5})
```

**Comment by dpjungmin** [comment]
Thank you @kiyonlin ! This solved my problem :)
