### ISSUE TITLE
I cannot find any function to read the headers of request 🚀 

### ISSUE THREAD

**Issue by abhijitgujar86** [gofiber/fiber#1148]
**Is your feature request related to a problem?**
It will be good if we have an  function to head the header(s) from request 
**Describe the solution you'd like**
the function can return a json array containing key value objects of headers  
**Describe alternatives you've considered**

**Additional context**

**Comment by ReneWerner87** [comment]
you can fetch individual headers with the ctx.Get function, which is mapped to express
https://docs.gofiber.io/api/ctx#get
https://expressjs.com/de/4x/api.html#req.get

to get to all headers you have to use the functions of fasthttp
![image](https://user-images.githubusercontent.com/7063188/106859541-7f941880-66c3-11eb-8655-2e7935ea018a.png)

// Header returns request header representation.
c.Request().Header.Header()

// PeekBytes returns header value for the given key.
c.Request().Header.PeekBytes(BYTE_SLICE)

// Peek returns header value for the given key.
c.Request().Header.Peek(STRING)


think with these functions everything should be possible
would close the issue if not still questions arise

**Comment by ReneWerner87** [comment]
Since there are no more questions or comments, I assume that the last comment has given enough information and I can close the issue, if more questions come up, just open the issue again

**Comment by cruzluna** [comment]
![image](https://user-images.githubusercontent.com/73450306/230739075-c0b6b04e-5db7-41ce-8095-d318e77c5be4.png)
