### ISSUE TITLE
Custom 403 Message in github.com/gofiber/fiber/v2/middleware/filesystem

### ISSUE THREAD

**Issue by Failip420** [gofiber/fiber#1153]
hi, it would be nice if i could change the 403 response when using Browse: false, i would like to display a custom page, it would be nice if i could load a custom page instead of showing default text "Forbidden" like you did with the 404 :)

**Comment by kiyonlin** [comment]
You can add another handler before filesystem middleware, something like
```go
func customerForbiddenPage(c *fiber.Ctx) error {
	err := c.Next()
	if err == fiber.ErrForbidden {
		// show your page
		return nil
	}
	return err
}
```

**Comment by Failip420** [comment]
Thank you
