### ISSUE TITLE
🐛  undefined: utils.GetTrimmedParam

### ISSUE THREAD

**Issue by dariuspranskus** [gofiber/fiber#1156]
**Fiber version**
v1.14.6
**Go version**
v1.15.8
**Issue description**
Getting the following error when running or getting packages **pkg/mod/github.com/gofiber/fiber@v1.14.6/path.go:175:15: undefined: utils.GetTrimmedParam**
**Code snippet**
Just importing the fiber package and creating app instance 
```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by kiyonlin** [comment]
If you are creating a new project, I suggest you to use fiber v2 because v1 is no longer maintained.

**Comment by dariuspranskus** [comment]
Oh, I see now. Thanks for letting me know
