### ISSUE TITLE
🤗  Behavior of the body parser

### ISSUE THREAD

**Issue by Refuel-ZL** [gofiber/fiber#1158]
**Question description**
form：
    

> ids[]: 12
>  ids[]: 13

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  // ..
     ******
       .........
        var body struct {
		Ids []string `query:"ids[]" json:"ids[]" xml:"ids[]" form:"ids[]"`
                // Ids []string `query:"ids" json:"ids" xml:"ids" form:"ids"`
	}
	if err := ctx.BodyParser(&body); err != nil {
		return c.Msg(ctx, err)
	} 
        ..............
        ******
}
```

Why?
tag ips[] not equal to ips

**Comment by xenowits** [comment]
Can u elaborate? Sorry I couldn't understand your issue

**Comment by ReneWerner87** [comment]
@Refuel-ZL Thank you for the report, please describe the problem in more detail so that we can help you in the best possible way.

Best you also give us an example request to follow up

**Comment by Refuel-ZL** [comment]
html:
<form>
＜input name="MyArray[]"＞
＜input name="MyArray[]"＞
＜input name="MyArray[]"＞
＜input name="MyArray[]"＞
</form>

go:
var form struct {
      MyArray []string               `query:"MyArray" form:"MyArray"`
}

ctx.BodyParser(&form);

len(form.MyArray) == 0    

why?

**Comment by Refuel-ZL** [comment]
@ReneWerner87 

> 的HTML：
> 
> ```
> <form>
>    ＜input name="MyArray[]"＞
>    ＜input name="MyArray[]"＞
>    ＜input name="MyArray[]"＞
>    ＜input name="MyArray[]"＞
> </form>
> ```
> 
> 去：
> 
> ```
> var form struct {
>       MyArray []string               `query:"MyArray" form:"MyArray"`
> }
> ctx.BodyParser(&form);
> ```
> 
> len（form.MyArray）== 0
> 为什么？

**Comment by ReneWerner87** [comment]
As we say, we need more description, writing only one word and code will not help.

And the html is incomplete, there is no method for post on the form, no submit button and no value attribute on the input box, this will not generate a sufficient post body request.
