### ISSUE TITLE
not detecting when client cancels request 🐛 

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#1160]
```go
func Handler(c *fiber.Ctx) error {
	ctx := c.Context()
	<-ctx.Done()
}
```

With `net/http` server, when the client cancels the request, ctx from the request returns a done signal which you can use to cancel processing the rest of the request.

**Comment by hsblhsn** [comment]
Fiber uses fasthttp under the hood.

And fasthttp doc says the following

> VERY IMPORTANT! Fasthttp disallows holding references to RequestCtx or to its' members after returning from RequestHandler. Otherwise data races are inevitable. Carefully inspect all the net/http request handlers converted to fasthttp whether they retain references to RequestCtx or to its' members after returning. RequestCtx provides the following band aids for this case:
> 1. Wrap RequestHandler into TimeoutHandler.
> 2. Call TimeoutError before returning from RequestHandler if there are references to RequestCtx or to its' members. See the example for more details.

So, you should implement a `TimeoutHandler` and wrap your request into the `TimeoutHandler` instead of calling `ctx.Done()` and holding reference to `RequestCtx`.

**Comment by pjebs** [comment]
How do I do that?

**Comment by pjebs** [comment]
How do I do that? It doesn't say you can't use context while the request is still in operation. Just don't keep a reference to context are request is finished.

**Comment by ReneWerner87** [comment]
@hsblhsn Thanks for the reply, can you please work out or provide a solution with the author, would then take care of the other issues

**Comment by pjebs** [comment]
i'm assuming timeout handler is a fixed max duration rather than a cancel signal.
