### ISSUE TITLE
🚀 Override default text/html type for ctx.Render

### ISSUE THREAD

**Issue by zabil** [gofiber/fiber#1163]
**Is your feature request related to a problem?**

Yes. There is no option to override the `Content-Type` `text/html` for `Render`

```golang
app.Get("/", func(c *fiber.Ctx) error {
 return c.Render("index", fiber.Map{
  "Message": "Hello World!",
 })
})
```

https://github.com/gofiber/fiber/blob/50e02e5149e07c45d67060d32bb8d2ef4f3588d2/ctx.go#L881-L883

**Describe the solution you'd like**

I am new to fiber, but I'd expect something like this to work

```golang
c.Set("Content-Type", "text/vnd.turbo-stream.html; charset=utf-8")
return c.Render("message", fiber.Map{
			"Message": c.Params("message"),
})
```

**Describe alternatives you've considered**

The alternative would be compiling using [template](https://golang.org/pkg/html/template/) and passing the result as a string response.

**Additional context**

Custom content type headers are used for rendering partials in frameworks like [turbo](https://turbo.hotwire.dev/handbook/streams#reusing-server-side-templates)

**Comment by ReneWerner87** [comment]
```go
app.Get("/", func(c *fiber.Ctx) error {
 err := c.Render("index", fiber.Map{
  "Message": "Hello World!",
 })
 if err !== null {
return err
} 
return c.Set("Content-Type", "text/vnd.turbo-stream.html; charset=utf-8")
})
```

Could you try this? 
Just write with my handy, if formatting problems are there please fix, but the basic idea should be clear

**Comment by zabil** [comment]
Thanks! This works. It also works with 

```golang
...
 if err != nil {
    return err
 }
 c.Set("Content-Type", "text/vnd.turbo-stream.html; charset=utf-8")
 return nil
})
```
