### ISSUE TITLE
🐛 404 on go get github.com/gofiber/fiber/v2

### ISSUE THREAD

**Issue by sbimochan** [gofiber/fiber#1164]
no /v2

```cannot find package "github.com/gofiber/fiber/v2" in any of:
	/usr/local/go/src/github.com/gofiber/fiber/v2 (from $GOROOT)
	/Users/{name}/go/src/github.com/gofiber/fiber/v2 (from $GOPATH)
```

navigating to `github.com/gofiber/fiber/v2` in browser results to 404
why is it searching in /usr ? shouldn't it be searching in web?

**Comment by hi019** [comment]
What is the full error? Did you follow the instructions above the go get command in the readme?

**Comment by sbimochan** [comment]
> What is the full error? Did you follow the instructions above the go get command in the readme? We will need more info.

```cannot find package "github.com/gofiber/fiber/v2" in any of:
	/usr/local/go/src/github.com/gofiber/fiber/v2 (from $GOROOT)
	/Users/{name}/go/src/github.com/gofiber/fiber/v2 (from $GOPATH)
```

navigating to `github.com/gofiber/fiber/v2` in browser results to 404
why is it searching in /usr ? shouldn't it be searching in web?

**Comment by hi019** [comment]
Did you follow the installation instructions in the README, including creating a Go Modules project?

**Comment by sbimochan** [comment]
> Did you follow the installation instructions in the README, including creating a Go Module project?

It doesn't say that in https://docs.gofiber.io/

**Comment by hi019** [comment]
Ok, we will update that. In the meantime use this repository's README instructions

**Comment by sbimochan** [comment]
Sure, Thanks!
