### ISSUE TITLE
🐛 Can't run the basic tutorial

### ISSUE THREAD

**Issue by jimitheat** [gofiber/fiber#1167]
For some reason I am unable to run this basic code. Go version 1.15.8

When I'm running it in a debugger, it will work. But cannot run it with command line, go run server.go, at all. The image as shown, shows that occasionally it will work. Same code, just a few seconds apart. Totally random. 

Cannot figure it out. 

![image](https://user-images.githubusercontent.com/61459379/107878217-38a8ed00-6f25-11eb-88f5-f610985f9f24.png)

**Fiber version**
2.5
**Issue description**

**Code snippet**

```
package main

import "github.com/gofiber/fiber/v2"

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World! 3")
	})

	app.Listen(":3000")
}

```

Exception 0xc0000005 0x0 0x7ff9a6fb2fff 0x207f47f0000
PC=0x207f47f0000

syscall.Syscall6(0x7ff9a6d16600, 0x6, 0x2, 0x1, 0x0, 0x0, 0x0, 0x81, 0x0, 0x0, ...)
        C:/Program Files/Go/src/runtime/syscall_windows.go:201 +0xf2
internal/syscall/windows.WSASocket(0x100000002, 0x0, 0x0, 0x8100000000, 0xaa9efd, 0x4, 0xbb8)
        C:/Program Files/Go/src/internal/syscall/windows/zsyscall_windows.go:122 +0xcc
net.sysSocket(0x2, 0x1, 0x0, 0x0, 0xc000006098, 0x1)
        C:/Program Files/Go/src/net/sock_windows.go:20 +0x66
net.socket(0xb14800, 0xc0000120d8, 0xaa9dcd, 0x4, 0x2, 0x1, 0x0, 0x0, 0xb159c0, 0xc0000f3fb0, ...)
        C:/Program Files/Go/src/net/sock_posix.go:19 +0x65
net.internetSocket(0xb14800, 0xc0000120d8, 0xaa9dcd, 0x4, 0xb159c0, 0xc0000f3fb0, 0x0, 0x0, 0x1, 0x0, ...)
        C:/Program Files/Go/src/net/ipsock_posix.go:141 +0x170
net.(*sysListener).listenTCP(0xc00008fe18, 0xb14800, 0xc0000120d8, 0xc0000f3fb0, 0xb12780, 0xc0000f3fb0, 0x4)
        C:/Program Files/Go/src/net/tcpsock_posix.go:168 +0xbe
net.(*ListenConfig).Listen(0xc00008feb0, 0xb14800, 0xc0000120d8, 0xaa9dcd, 0x4, 0xaa9efc, 0x5, 0x1, 0xc000006068, 0x1, ...)
        C:/Program Files/Go/src/net/dial.go:636 +0x5d9
net.Listen(0xaa9dcd, 0x4, 0xaa9efc, 0x5, 0x1, 0xc000006068, 0x1, 0x1)
        C:/Program Files/Go/src/net/dial.go:706 +0x87
github.com/gofiber/fiber/v2.(*App).Listen(0xc00005e3c0, 0xaa9efc, 0x5, 0xc000006068, 0x1)
        C:/Users/Jimmy Ng/go/pkg/mod/github.com/gofiber/fiber/v2@v2.5.0/app.go:587 +0x6a
main.main()
        C:/Users/Jimmy Ng/Documents/goLang/server.go:12 +0xc8
rax     0x7ff9a350d84a
rbx     0x7ff9a350d848
rcx     0x77
rdi     0xffffffffffbadd11
rsi     0x0
rbp     0x207f459d160
rsp     0xabf45feb50
r8      0x94b
r9      0x94b
r10     0x94b
r11     0x94b
r12     0x7ff9a6dc0000
r13     0x0
r14     0x7ff9a350d84a
r15     0xc000007a
rip     0x207f47f0000
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
exit status 2

**Comment by ReneWerner87** [comment]
thanks for the report

please test the same with the standard golang library, assume it is your installation, such an error has not occurred anywhere yet

```go
package main

import (
	"fmt"
	"net/http"
)

func main() {
	http.HandleFunc("/", HelloServer)
	http.ListenAndServe(":3000", nil)
}

func HelloServer(w http.ResponseWriter, r *http.Request) {
	fmt.Fprint(w, "Hello, World! 3")
}
```

**Comment by jimitheat** [comment]
Hi, 

I'm getting the same error message. I've tried reinstalling go and it's the same error. I've also just tried version 1.14.5 and it's the same error. 

Is your recommendation that it's related to the installation and not fiber?

**Comment by ReneWerner87** [comment]
Yes, if the webserver does not even run with the golang standard library it must be the golang installation and has nothing to do with fiber.

**Comment by jimitheat** [comment]
Thanks mate. I reinstalled Go and it failed. Different machine worked. 

Had to reinstall the whole operating system for this to work. So yeah, unrelated to fiber or go, even though other languages worked.
