### ISSUE TITLE
🐛 Possible bug on how `ctx.Locals` stores `interface{}`

### ISSUE THREAD

**Issue by shirshendubhowmick** [gofiber/fiber#1169]
**Fiber version**
2.3.2

**Issue description**
Possible Bug

I have used `ctx.Locals` inside a middleware to store and pass a struct which also got some methods of its own.

Among all the methods the struct has got a method called `Close`. I found that this `Close` method is getting callled from some where outside of my application's code.

Upon debugging I found that it was being called by a method called `Reset` of `fasthttp`.

Here is the call stack:

```
main/internal/tcp/socket.(*Socket).Close (/Users/shirshendubhowmick/smallcase/backend/mofsl-b2b-broker-bridge/internal/tcp/socket/socket.go:84)
github.com/valyala/fasthttp.(*userData).Reset (/Users/shirshendubhowmick/go/pkg/mod/github.com/valyala/fasthttp@v1.19.0/userdata.go:67)
github.com/valyala/fasthttp.(*Server).serveConn (/Users/shirshendubhowmick/go/pkg/mod/github.com/valyala/fasthttp@v1.19.0/server.go:2187)
github.com/valyala/fasthttp.(*Server).serveConn-fm (/Users/shirshendubhowmick/go/pkg/mod/github.com/valyala/fasthttp@v1.19.0/server.go:1957)
github.com/valyala/fasthttp.(*workerPool).workerFunc (/Users/shirshendubhowmick/go/pkg/mod/github.com/valyala/fasthttp@v1.19.0/workerpool.go:223)
github.com/valyala/fasthttp.(*workerPool).getCh.func1 (/Users/shirshendubhowmick/go/pkg/mod/github.com/valyala/fasthttp@v1.19.0/workerpool.go:195)
runtime.goexit (/usr/local/go/src/runtime/asm_amd64.s:1374)
```

This is also confirmed if I change the name of the method from `Close` to something else say `Shutdown` then I don't face this problem.

**Code snippet**

This is how I am storing the the struct from the middleware
```go
ctx.Locals("brokerTCPSocket", brokerTCPSocket)
```

**Comment by kiyonlin** [comment]
Please see valyala/fasthttp#920

**Comment by shirshendubhowmick** [comment]
Since `fasthttp` has mentioned that they won't be able to fix this issue. Is there anything that can be done on `fiber`'s side ?

**Comment by kiyonlin** [comment]
Sorry, I don't think so. 

> Wrapping it in a struct like that is a good way to work around it.

Or you should avoid using `Close` as you described above.
