### ISSUE TITLE
How to use database for routing paths 🤗 

### ISSUE THREAD

**Issue by UlasSAYGINIM** [gofiber/fiber#1174]
**Question description**

I wonder how can i use database for routing paths?
I couldnt find any document.

can i get routes from sqlite3?

**Comment by IGLOU-EU** [comment]
Hi,    
You can build routing dynamically with your DB, routing only use a patern string. I'm not sure if you can do that after a `Listen` (Think not). 

But you can use `Params` to build a custom 'routing/match' https://docs.gofiber.io/api/ctx#params

Sorry if I don't understood your question :)

**Comment by UlasSAYGINIM** [comment]
Thank you for you fast comment @IGLOU-EU , firstly, i want to use SQLite 3 as database to store url paths.
i just want to start with just creating web pages and its url based on language like

samplesite.com/en/aboutus
samplesite.com/fr/àpropos

can i use any spoken real world language in routing? 

thanks.

**Comment by IGLOU-EU** [comment]
You can do that,
build routing string from your db row

Like :
```go
app := fiber.New()

for rows.Next() {
    if err = rows.Scan(language, article); err != nil {
        log.Fatalln(err)
    }

    app.Use(
        fmt.Sprintf(`/%s/%s`, language, article),
        func(c *fiber.Ctx) error {return c.SendString("Hello Dude !!!")},
    )
}

app.Listen(":3000")
```

Or a listening like :
```go
app.Use(
    "/:language/:article", 
    func(c *fiber.Ctx) error {
        fmt.Println(c.Params("language"), c.Params("article"))
        return nil
    },
)
```

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/735#issuecomment-678586434

Creating dynamic routes is not good for microservices, rather create a route that matches for all and then check the contents of the database routes in it and then execute the corresponding handler as described in the other issue.

**Comment by UlasSAYGINIM** [comment]
@ReneWerner87 thank you for your response. if you dont misunderstand, can you give example to be sure what you said to avoid missunderstanding. 

@IGLOU-EU thank you for your solution. i couldnt think the sqlite 3 connection part. you may be omited to be clear but i wonder for performance, how it can be good. thanks a lot.

**Comment by ReneWerner87** [comment]
this way you could e.g. use dynamically registered routes from the database without restarting the service

```go
package main

import "github.com/gofiber/fiber"

func main() {
	app := fiber.New()

	app.Get("*", func(c *fiber.Ctx) {
		// route registered in storage/database ?
		exist, err := storage.Get(c.Path())
		if err != nil {
			panic(err)
		}
		if !exist { // nope -> no found
			c.SendStatus(fiber.StatusNotFound)
		} else { // yes -> do stuff for the route
			c.SendStatus(fiber.StatusOk)
		}
	})

	app.Listen(":8080")
}
```

but if your report aims to fetch the routes from the database at the start of the service and then register them before the start, then you should proceed as in @IGLOU-EU example
