### ISSUE TITLE
Catch 404 Errors

### ISSUE THREAD

**Issue by Koredeoluwafemi** [gofiber/fiber#1179]
**Hi Fiber team, I need help on how to catch 404 error pages. I am currently unable to catch 404 errors when using fiber for a web project but I am able to catch it when using it to build an api, See sample route below...**

** ** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  appRoute := app.Group("", middleware.AdminSession)
  
  appRoute.Post("/signup", controllers.Register)
}
```

**Comment by hi019** [comment]
See https://docs.gofiber.io/extra/faq#how-do-i-handle-custom-404-responses
