### ISSUE TITLE
🤗 CSRF middleware returns forbidden

### ISSUE THREAD

**Issue by neerajbg** [gofiber/fiber#1182]
I am using CSRF middleware with html templates with the custom KeyLookup form:csrf

I add a hidden field in the html form with the name csrf

```
Code of main function

package main
import(

"github.com/gofiber/fiber/v2"
"github.com/gofiber/fiber/v2/middleware/csrf"

)

func main() {
  app := fiber.New()
  // ..

app.Use(csrf.New(csrf.Config{
		KeyLookup:      "form:csrf",
		CookieName:     "csrf_",
		ContextKey:     "csrf",
	}))
}
```

In the handler function I tried to collect the csrf by both ways from contextKey as well as Cookies 

// tk := c.Get("csrf")
tk := c.Cookies("csrf_")

Everytime the contextkey method doesnt work and returns null. However by Cookies method sometimes it works while many time doesnt.

The complete code of handler is below
```
func ContactPage(c *fiber.Ctx) error {
	context := fiber.Map{}

	// tk := c.Get("csrf")
	tk := c.Cookies("csrf_")

	context["cstk"] = tk

	if c.Method() == "POST" {
		// Using struct

		p := new(forms.ContactForm)
		// fmt.Println(p)
		// var p forms.ContactForm
		if err := c.BodyParser(p); err != nil {
			return err
		}

		errors := p.Validate()

		if errors != nil {
			p.Errors = errors

			context["form"] = p
			return c.Render("page/contact", context, "layouts/base")
		}

		// Send mail to the user via smtp
		// mailStatus := sendPlainTextEmail(p)
		// sendPlainTextEmail(*p)

		context["Success"] = "Thanks for contacting."
		c.Redirect("/contact/thanks")
	}

	return c.Render("page/contact", context, "layouts/base")
}
```
In html form I am setting the csrf as 

```
<input type="hidden" name="csrf" value="{{ .csrf }}">

```

I am new to Golang, kindly guide me the best way to implement csrf 

Thanks
Neeraj

**Comment by sixcolors** [comment]
It's a bug.

See PR Fix: CSRF middleware cookie<>storage bug squashed and other improvements #1180

**Comment by neerajbg** [comment]
> It's a bug.
> 
> See PR Fix: CSRF middleware cookie<>storage bug squashed and other improvements #1180

I tried to update my fiber lib with the command

```
go get -u github.com/gofiber/fiber/v2

```
Can you please help me get your changes applied to my local fiber lib. It would have been great if the documentation would have a complete working example.

Also is there any way to uninstall the lib and re install. 

I checked the Golang doc and couldnt find a way to completely uninstall a package lib and  re install a fresh copy.

Thanks
Neeraj

**Comment by sixcolors** [comment]
> Can you please help me get your changes applied to my local fiber lib. It would have been great if the documentation would have a complete working example.

The PR is approved but hasn’t been merged yet.. the Docs PR is also waiting for a merge. 

...

**Comment by ReneWerner87** [comment]
we will merge it at the weekend

**Comment by ReneWerner87** [comment]
Merged:
https://github.com/gofiber/fiber/pull/1180
https://github.com/gofiber/docs/pull/154

fix is in the next fiber version(@sixcolors thanks for the effort)

**Comment by neerajbg** [comment]
I tried to implement csrf middleware again with the updated code and still problem persists.

However I am able to access csrf cookie via contextKey successfully, but the problem is as below. 

1. I am using fiber package as a full fledged web application with traditional html templates. Thus I am setting csrf token to be accessible via form body.
2. When I submit the form, it works fine, no issues. But if I try to submit any other form again even if a different form, it says forbidden.
3. I feel like the problem is after successful form processing, the csrf token is somehow lost or reset but the cookie value is not returned correctly.

Here is my config

```
"github.com/gofiber/fiber/v2/middleware/csrf"
	"github.com/gofiber/fiber/v2/utils"

	"github.com/gofiber/fiber/v2"

func main() {

	// Html template engine
	engine := html.New("./template", ".html")

	app := fiber.New(fiber.Config{
		Views: engine,
	})

	// initDatabase()
	defer database.DBConn.Close()

	app.Static("/", "./static")

	// defer database.DBConn.Close()

	app.Use(logger.New())
	// initDatabase()

	// Load static files
	app.Static("/static", "./static")

	// CSRF Middleware
	app.Use(csrf.New(csrf.Config{
		KeyLookup: "form:csrf",
		// TokenLookup: "form:csrf",
		// CookieName: "csrf_",
		CookieSameSite: "Strict",
		Expiration:     8600,
		KeyGenerator:   utils.UUID,
		ContextKey:     "csrf",
		// CookieSameSite: "Strict",
	}))

	// Setup Routes
	setupRoutes(app)

	app.Use(controller.NotFound)

	app.Listen(":8002")

}
```
Collecting csrf token in controller handler
```
tk := c.Locals("csrf")
	// tk := c.Cookies("csrf_")
	context["token"] = tk
```

Html form have a token filed like
```
<input type="hidden" name="csrf" value="{{ .token }}">
```

I am not sure what I am doing wrong.

**Comment by sixcolors** [comment]
The PR was merged but there hasn’t been a new release yet. So updating the go package wouldn’t get it yet.

**Comment by kiyonlin** [comment]
> The PR was merged but there hasn’t been a new release yet. So updating the go package wouldn’t get it yet.

@neerajbg You can use `go get -u github.com/gofiber/fiber/v2@master` for test.
