### ISSUE TITLE
🤗 Inconsistent Guides Routing / Groups

### ISSUE THREAD

**Issue by lycano** [gofiber/fiber#1183]
**Question description**
On docs.fiber.io Guide Routing -> Example Grouping
```
func main() {
  app := fiber.New()

  api := app.Group("/api", middleware) // /api

  v1 := api.Group("/v1", middleware)   // /api/v1
  v1.Get("/list", handler)             // /api/v1/list
  v1.Get("/user", handler)             // /api/v1/user

  v2 := api.Group("/v2", middleware)   // /api/v2
  v2.Get("/list", handler)             // /api/v2/list
  v2.Get("/user", handler)             // /api/v2/user

  app.Listen(":3000")
}
```
Line `api := app.Group("/api", middleware) // /api` vs. 
Guide Grouping -> Group Handlers
```
func main() {
    app := fiber.New()

    api := app.Group("/api") // /api

    v1 := api.Group("/v1", func(c *fiber.Ctx) error {
        c.JSON(fiber.Map{
            "message": "v1",
        })
        return c.Next()
    })                       // /api/v1
    v1.Get("/list", handler) // /api/v1/list
    v1.Get("/user", handler) // /api/v1/user

    app.Listen(":3000")
}
```
Line `api.Group("/v1", func(c *fiber.Ctx) error {...}` seems inconsistent to me.

Im new to this project and was thinking c.JSON here would in fact send that content as json to the client when calling via GET /api/v1.

This was not the case. I had to register an empty GET handler (see code snippet) to v1 group to return something when calling /api/v1. Is this intentional? Seems a bit odd to me to use an empty path.

What I guess now is that the Routing Guide is correct and says: "Hey, this handler is for middleware not for returning something if you have something under it".

Maybe the Guide "Group Handlers" needs more clarification?

**Code snippet**
Working but doesn't "feel" right

```
func main() {
    app := fiber.New()

    api := app.Group("/api") // /api

    v1 := api.Group("/v1") // /api/v1
    v1.Get("", func(c *fiber.Ctx) error {
        return c.JSON(fiber.Map{
            "message": "v1",
        })
    }
    v1.Get("/list", handler) // /api/v1/list
    v1.Get("/user", handler) // /api/v1/user

    app.Listen(":3000")
}
```

**Comment by hi019** [comment]
Hello! Are you saying we should clarify that the second param of `api.Group` is for middleware, and does not actually create the route?

**Comment by ReneWerner87** [comment]
i know what you mean, the example for the guide is badly chosen, it should actually only show that you can register middlewares directly with and there we directly write a response body, we should replace the writing of the response body there with a task that middlewares map, like setting headers or something similar


with the grouping, only middleware handler should be used, since it is identical with the app.use, thus for all request methods applies, here one can deposit e.g. a caching middleware or the limiter etc.

 would recommend you to declare the main handler for the GET of the group either with empty string or with slash, in the code with us it is the same
https://github.com/gofiber/fiber/blob/master/router.go#L220-L221

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()


	handler := func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusOK)
	}
	api := app.Group("/api") // /api

	v1 := api.Group("/v1") // /api/v1

	v1.Get("/", func(c *fiber.Ctx) error { // /api/v1
		return c.JSON(fiber.Map{
			"message": "v1",
		})
	})
	v1.Get("/list", handler) // /api/v1/list
	v1.Get("/user", handler) // /api/v1/user

	log.Fatal(app.Listen(":3000"))
}

```
or you leave the handler outside the group, as it is equivalent to the group
```go
...
       api.Get("/v1", func(c *fiber.Ctx) error { // /api/v1
		return c.JSON(fiber.Map{
			"message": "v1",
		})
	})

        v1 := api.Group("/v1") // /api/v1
	v1.Get("/list", handler) // /api/v1/list
	v1.Get("/user", handler) // /api/v1/user
...
```


we will of course adapt the documentation for the group guide, would deposit this example
```go
func main() {
	app := fiber.New()

	handler := func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusOK)
	}
	api := app.Group("/api") // /api

	v1 := api.Group("/v1", func(c *fiber.Ctx) error {
		c.Set("Version", "v1")
		return c.Next()
	})                       // /api/v1
	v1.Get("/list", handler) // /api/v1/list
	v1.Get("/user", handler) // /api/v1/user

	log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/docs/pull/155 
is the PR change

**Comment by lycano** [comment]
First of all thanks for your reply! I see there the examples are already going to be updated! Nice =)

@hi019 Yes, as @ReneWerner87 picked up i found it confusing to see c.JSON there which i assumed at first - as a newbee to the project - it would print out the json when finishing that func. I was assuming later - since this was not the case - its not ment to be used that way. This was also clarified by @ReneWerner87 comment why it doesn't.

@ReneWerner87 Thank you for your detailed response and thank you for pointing me into the right direction. Since the empty path is translated to slash i will use the slash notation directly. As im working inside the group "/" does make more sense to me. Didn't know that you could define a route outside of the group scope. Thats also nice! Thanks for pointing that out.

Seeing the changed example it now makes sense to me what purpose that line has especially with the changed comment.

Thanks a lot!
