### ISSUE TITLE
🤗 "Cache hit" and "cache miss" in built-in cache middleware

### ISSUE THREAD

**Issue by hugmouse** [gofiber/fiber#1185]
**Question description**

In [built-in cache middleware](https://docs.gofiber.io/api/middleware/cache) we can cache some of the requests coming from the server. Question - is it possible to know when the server gave the cache and when it gave a new request by ignoring the cache? It seems to be called "cache hit" and "cache miss".

And with the help of this knowledge to make some kind of statistics, by which you can understand the percentage of hits in the cache. :thinking: 

Thank you in advance!

**Comment by kiyonlin** [comment]
You can enable `cfg.CacheControl` so that you'll get additional response header if cache hit.

**Comment by hugmouse** [comment]
I guessed to some simple construction, but how to count those request that did not get into the cache - not quite clear heh

I'll be grateful for any help and apologize if this isn't the right place to discuss this kind of stuff.

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cache"
	"strconv"
)

var cacheMiss int = 0

func main() {
	app := fiber.New()

	app.Use(cache.New())
	
	app.Use(cache.New(cache.Config{
		Next: func(c *fiber.Ctx) bool {
			cacheMiss++
			return c.Query("refresh") == "true"
		},
		CacheControl: true,
	}))

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!\nAmount of cache misses:"+strconv.Itoa(cacheMiss+1))
	})

	app.Listen(":3000")
}
```

**Comment by hi019** [comment]
With this, the cache will only be hit if `c.Query("refresh") == "true"` is false. Since you do `cacheMiss++` before you know if the expression is true or false, every request to the MW will be counted as a miss. You should do something like this

```go
	app.Use(cache.New(cache.Config{
		Next: func(c *fiber.Ctx) bool {
			shouldNotCache := c.Query("refresh") == "true"
            if (shouldNotCache) {
   		        cacheMiss++
            }

            return shouldNotCache
		},
		CacheControl: true,
	}))
```

**Comment by ReneWerner87** [comment]
```go
package main

import (
	"log"
	"sync/atomic"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cache"
)

func main() {
	app := fiber.New()

	var requests uint64
	var requestsWithoutCache uint64

	cacheGroup := app.Group("/test")
	cacheGroup.Use(func (c *fiber.Ctx) error {
		atomic.AddUint64(&requests, 1)
		return c.Next()
	})
	cacheGroup.Use( cache.New())
	cacheGroup.Get("/", func(c *fiber.Ctx) error {
		atomic.AddUint64(&requestsWithoutCache, 1)
		return c.SendStatus(fiber.StatusOK)
	})

	app.Get("/cacheHits", func(c *fiber.Ctx) error {
		// TODO: fix div by zero
		sum := atomic.LoadUint64(&requests)
		cacheHits := (sum - atomic.LoadUint64(&requestsWithoutCache))

		return c.JSON(fiber.Map{
			"requests": sum,
			"cacheHits": cacheHits,
			"cacheHitsPercentage": cacheHits * 100 / sum,
		})
	})

	log.Fatal(app.Listen(":3000"))
}

```

you can do something like this, 

the next function will not work, because it will first check if there is a cache entry and if not the other function will be executed, maybe this is wrong, that could be discussed @hi019 @kiyonlin

**Comment by hugmouse** [comment]
> ```go
> package main
> 
> import (
> 	"log"
> 	"sync/atomic"
> 
> 	"github.com/gofiber/fiber/v2"
> 	"github.com/gofiber/fiber/v2/middleware/cache"
> )
> 
> func main() {
> 	app := fiber.New()
> 
> 	var requests uint64
> 	var requestsWithoutCache uint64
> 
> 	cacheGroup := app.Group("/test")
> 	cacheGroup.Use(func (c *fiber.Ctx) error {
> 		atomic.AddUint64(&requests, 1)
> 		return c.Next()
> 	})
> 	cacheGroup.Use( cache.New())
> 	cacheGroup.Get("/", func(c *fiber.Ctx) error {
> 		atomic.AddUint64(&requestsWithoutCache, 1)
> 		return c.SendStatus(fiber.StatusOK)
> 	})
> 
> 	app.Get("/cacheHits", func(c *fiber.Ctx) error {
> 		// TODO: fix div by zero
> 		sum := atomic.LoadUint64(&requests)
> 		cacheHits := (sum - atomic.LoadUint64(&requestsWithoutCache))
> 
> 		return c.JSON(fiber.Map{
> 			"requests": sum,
> 			"cacheHits": cacheHits,
> 			"cacheHitsPercentage": cacheHits * 100 / sum,
> 		})
> 	})
> 
> 	log.Fatal(app.Listen(":3000"))
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/7063188/108751398-7075ed00-7542-11eb-81f0-efaaf3172806.png)
> 
> you can do something like this,
> 
> the next function will not work, because it will first check if there is a cache entry and if not the other function will be executed, maybe this is wrong, that could be discussed @hi019 @kiyonlin

![image](https://user-images.githubusercontent.com/44648612/108834955-c19ce400-7609-11eb-878c-7a55a82aaa73.png)

This implementation seems to be working fine. Thank you for providing the code ^^

I will close this issue for now. But if there are any additions, I would be happy to see them.
