### ISSUE TITLE
🐛 Session Middlware get problem when add multi key

### ISSUE THREAD

**Issue by vietlib** [gofiber/fiber#1188]
**Fiber version**
v2
**Issue description**
I using session middleware with Redis, it seem work well when add one key-value to session (need to add Session.RegisterType("") if not you will get ```[session] Register this type first with the `RegisterType` method.```

But when add more key-value (also added Session.RegisterType("") and Session.RegisterType(1)) , script not work correctly and ```[session] Register this type first with the `RegisterType` method.``` appear
How can i fix this please ?

**Comment by ReneWerner87** [comment]
@vietlib please provide a short example to reproduce

**Comment by vietlib** [comment]
The error appears when restart server , you should restart session server and clear browser history , it will work again :)
