### ISSUE TITLE
🤔 Travis test for Windows is commented out, but used in the badge

### ISSUE THREAD

**Issue by MarvinJWendt** [gofiber/fiber#119]
Hi, the `README.md` states that the Windows build is passing:
![image](https://user-images.githubusercontent.com/31022056/74286946-25b77780-4d29-11ea-8dfe-d6344bc2bfe7.png)
But windows isn't tested, as it's commented out on the Travis config file:
https://github.com/gofiber/fiber/blob/7946333133c51485fc50dedd42f6d7687574e96b/.travis.yml#L5

So technically Windows builds are never tested, and the badge won't change.
Should that be updated?

**Comment by Fenny** [comment]
`Fiber` works on windows, but I commented it out because this issue is still open https://github.com/gofiber/fiber/issues/71.
I'm working on a fix right now, I will keep this open until fixed.

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/issues/71 is fixed, and windows https://github.com/gofiber/fiber/pull/121 is enabled in travis again.
