### ISSUE TITLE
Static routers should support Go 1.16 fs.FS

### ISSUE THREAD

**Issue by svera** [gofiber/fiber#1190]
**Is your feature request related to a problem?**
I wanted to use `Static` routes with embedded FS. Right now, `app.Static()` just accept `string`s with path to folders 

**Describe the solution you'd like**
Add a new method that allow passing of `fs.FS` when creating static routes.

**Describe alternatives you've considered**

**Additional context**

**Comment by dechristopher** [comment]
@svera fiber targets go 1.14 but it doesn't specifically need to have any direct embed.FS support since it still implements regular fs.FS. I have a PR open (#1189) to add FS support to the favicon middleware. I can take a stab at this if you aren't already on it.

**Comment by dechristopher** [comment]
It's also worth noting that the `filesystem` middleware can handle this use case similarly and already supports providing your own http.Filesystem implementation which can be obtained by wrapping an `embed.FS` in the `http.FS(fsys fs.FS)` function as of go 1.16:
```go
//go:embed /static
var static embed.FS

r.Use(filesystem.New(filesystem.Config{
    Root:   http.FS(static),
}))
```

**Comment by Fenny** [comment]
Thanks for pointing this out, we were waiting to add native support for the new filesystem. However, we do want to support the last 2 versions of Go. So we have to wait until 1.18 before we can add this to `Static`. At that time we might be releasing Fiber v3. 

Regarding your favicon PR, I'm currently on holiday so we have to wait until one of the other maintainers pick it up.

To be continued..
