### ISSUE TITLE
Use internal UUID function outside of Fiber

### ISSUE THREAD

**Issue by MehranGhamaty** [gofiber/fiber#1195]
**Question description**

Use of internal package not allowed. for the internal version of uuid. I'm trying to consolidate needs to import UUID for other parts of my library with the internal services of Fiber having their own UUID. What are my options? 

I almost feel like the most appropriate actions would be to remove it as an internal package or just use external package as for the framework. I know that I'm probably not the only person thats going to run into this problem.

```go
package main

import (
        "github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/internal/uuid"
)

```

**Comment by ReneWerner87** [comment]
Use this exported function

https://github.com/gofiber/fiber/blob/master/utils/common.go#L32

```go
import (
  "github.com/gofiber/fiber/v2/utils"
)

utils.UUID()
```

**Comment by MehranGhamaty** [comment]
I need to use it as a type not for a separate package. I need the exposed UUID object. There are some performance problems with just using it as string. Is there a way to expose the actual type?

**Comment by MehranGhamaty** [comment]
I guess the external packages have the same representation so it doesn't really make a difference.
