### ISSUE TITLE
🐛 in Banner we it always show 127.0.0.1

### ISSUE THREAD

**Issue by guaychou** [gofiber/fiber#1198]
**Fiber version**
V2.5.0
**Issue description**
banner fiber always show 127.0.0.1, i want to show it as 0.0.0.0 / or any ip that i want to listen it for
**Picture**
![image](https://user-images.githubusercontent.com/29087469/109624150-72f2cb00-7b70-11eb-8252-7f297d19114c.png)

**Code**
i use this . . . 
```
 app.Listen(":3000")
```

Can you help me ? is this expected ?

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/master/app.go#L889

It is currently intended that if the host is empty or the 0.0.0.0 host is, this address is shown.

**Comment by Fenny** [comment]
```go
app.Listen("0.0.0.0:3000")
```

**Comment by ReneWerner87** [comment]
so as we said before this is not a bug but an expected behaviour
