### ISSUE TITLE
🤗 Should BodyParser pick up form files for multipart forms?

### ISSUE THREAD

**Issue by andrei-dascalu** [gofiber/fiber#1199]
**Question description**

I am submitting a form (multipart/formdata) that consists of a regular form field and an uploaded file. I am trying to use BodyParser to read the form data into a struct as follows

**Code snippet** 

```go
package dto 

type MyFormStruct struct {
	LanguageCode string               `form:"languageCode"`
	File         multipart.FileHeader `form:"file"`
}
```

then read it as such

```go
        bodyData := new(dto.MyFormStruct)

	if err := c.BodyParser(bodyData); err != nil {
		return c.Status(http.StatusBadRequest).JSON(map[string][string]{
		    "message" : "Unable to parse form body",
		})
	}

```

However, while the "languageCode" field will be correctly read, the file information always appears as empty (empty filename, content, etc) and there are no parsing errors

On the other hand, if I try to manually read the file (for an identical request)

```go
file, err := c.FormFile("file")
```

then everything works.

My question is, should BodyParser read files? Is ```multipart.FileHeader``` the correct type? I've always tried using a pointer (manually created with new) as the FormFile function itself returns a pointer, but there was no change.

Thanks

**Comment by tianjipeng** [comment]
``BodyParser`` only parse text field of form data, not including file field

**Comment by andrei-dascalu** [comment]
@tianjipeng thanks for the fconfirmation, indeed, that's what it does. I'm just wondering whether it shouldn't also handle file fields? If that's not possible/desirable it might be good to clarify this as part of the documentation. Regular form fields can be read with either FormValue or BodyParser, but for files you can use FormFile only.

**Comment by ansidev** [comment]
https://docs.gofiber.io/api/ctx#multipartform
