### ISSUE TITLE
Handlers pre and post execution of a method

### ISSUE THREAD

**Issue by Nick2324** [gofiber/fiber#1200]
I was wondering if there was any possibility to give some difference between handlers that get executed before and after a response is generated

I suppose it's possible to do this if the handler is set directly in the app.Get/Post/etc... method, but it means it is repeated in every route if it's required in all of the routes

So that I would like to add any differentiation factor to a Handler pre and post query solving.

Thanks in advance

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/app#route-handlers
https://docs.gofiber.io/api/middleware

If I understand correctly, you are referring to the concept of middlewares, which enables fiber

you can create handlers that run before or after each route for all request methods or individual request methods

or create multiple handlers when defining the route.
```go
func (app *App) Get(path string, handlers ...Handler) Router
func (app *App) Head(path string, handlers ...Handler) Router
func (app *App) Post(path string, handlers ...Handler) Router
func (app *App) Put(path string, handlers ...Handler) Router
func (app *App) Delete(path string, handlers ...Handler) Router
func (app *App) Connect(path string, handlers ...Handler) Router
func (app *App) Options(path string, handlers ...Handler) Router
func (app *App) Trace(path string, handlers ...Handler) Router
func (app *App) Patch(path string, handlers ...Handler) Router

// examples
app.Get(
    "/myRoute",
    func(c *fiber.Ctx) error {
	    fmt.Println("pre handler")
	    return c.Next()
    },
    func(c *fiber.Ctx) error {
	    fmt.Println("middle handler")
	    if err := c.SendString("Hello World"); err != nil {
		    return err
	    }
	    return c.Next()
    },
    func(c *fiber.Ctx) error {
	    fmt.Println("post handler")
	    return nil
    },
);
// ----
app.Use("/myRoute2", func(c *fiber.Ctx) error {
      fmt.Println("pre handler")
      return c.Next()
})
app.Use("/myRoute2", func(c *fiber.Ctx) error {
      if err := c.Next(); err != nil {
	      return err
      }
      fmt.Println("post handler")
      return nil
})
app.Get("/myRoute2", func(c *fiber.Ctx) error {
      fmt.Println("middle handler")
      return c.SendString("Hello World")
})

```
perhaps i misunderstood your request ?

**Comment by ReneWerner87** [comment]
hope we were able to help you,
if you have further questions or want to get at something else here, please feel free to reopen the issue.
