### ISSUE TITLE
app.Use and app.Group consumes partially matched routes

### ISSUE THREAD

**Issue by drafu** [gofiber/fiber#1204]
**Fiber version**
v2.5.0

**Issue description**

**Current behaviour:**
In the below case `docHandler` intercepts before `/docs/meta` could be executed
```
func New(app *fiber.App) {
  app.Use("/doc", docHandler)
  app.Get("/docs/meta", docsMeta)
}
```
In the below example both queries succeed
```
func New(app *fiber.App) {
  app.Get("/docs/meta", docsMeta)
  app.Use("/doc", docHandler)
}
```
Exact same behaviour happens when using `app.Group` instead of `app.Use`

**Expected behaviour:**
Using `app.Use` or at least `app.Group` should not consume partially matched queries.

I understand, that fiber docs clearly states that Use matches _any paths requested that begin with it_ and it may be an expected behaviuor, but there, in my opinion, should be something to match exact name of query.

There is clearly a workaround to match exact `/doc` and `/doc/*` with two different routing procedures, but that doubles the work for such cases.

I do not know is this is an expected behaviour or should be considered a bug, but it's worth mentioning somewhere in fiber docs.

**Comment by ReneWerner87** [comment]
Should be an expected behavior, middleware always match partial, so at startup with the route

**Comment by ReneWerner87** [comment]
![Screenshot_20210305-213019.jpg](https://user-images.githubusercontent.com/7063188/110170545-a6488a80-7dfa-11eb-9308-66da8b3f593f.jpg)

**Comment by drafu** [comment]
@ReneWerner87 I already acknowledged exaclty that in initial issue, and considered it may be expected behaviour even though it is counterintuitive for this exact example, but nothing states the same for Group.

**Comment by ReneWerner87** [comment]
> I understand, that fiber docs clearly states that Use matches any paths requested that begin with it and it may be an expected behaviuor, but there, in my opinion, should be something to match exact name of query.

If you need a way to check an exact route with your middleware, use router.All()
https://docs.gofiber.io/api/app#route-handlers

// All will register the route on all HTTP methods
// Almost the same as app.Use but not bound to prefixes
func (app *App) All(path string, handlers ...Handler) Router


As you already mentioned, with group only the prefix you specify is automatically added to the other subsequent routes and if you register directly with the call middlewares again the same logic is used that exists with app.use, that here a partial mapping is used.
https://github.com/gofiber/fiber/blob/master/app.go#L535-L540

app.Use
https://github.com/gofiber/fiber/blob/master/router.go#L74
https://github.com/gofiber/fiber/blob/master/path.go#L230
This check is called a partial check and is intended as follows.

In these concepts we have emulated the behaviour of expressjs, as this framework was the inspiration, making the transition easier.
http://expressjs.com/de/api.html#app.use
![image](https://user-images.githubusercontent.com/7063188/110205055-aedea680-7e76-11eb-8243-3c04ef585848.png)


Hope we could help, if you have any ideas how we can better describe this in the documentation, feel free to open a pull request or let us know, any input is welcome.
