### ISSUE TITLE
how do i serve an rss feed? 🤗 

### ISSUE THREAD

**Issue by chovy** [gofiber/fiber#1205]
It seems I can only use .html extension on templates. I want an rss.xml file to be used.

` <?xml version="1.0" encoding="UTF-8"?>`

This piece gets entity encode and it shouldn't be when I use rss.html

**Comment by IGLOU-EU** [comment]
You're probably speaking about
github.com/gofiber/template/html
And I don't know it. 

But Gofiber support more than a simple HTML template engines.
https://docs.gofiber.io/guide/templates

With the standard Go HTML or TEXT engines, you can probably achieve what you want.
https://golang.org/pkg/html/template/ (Auto escape and HTML encode)
https://golang.org/pkg/text/template/ (Need to trust the content ...)

For me the most elegant solution is using `encoding/xml` standard lib to output a good XML. Most particularly for simple RSS feed.
https://golang.org/pkg/encoding/xml/

I hope that can help you.

**Comment by chovy** [comment]
I don't see how to create more than one view.

```
    app := fiber.New(fiber.Config{
        Views: html.New("./views", ".html"),
    })
```

I need an xml template.

**Comment by ReneWerner87** [comment]
Currently it is only possible to register one render engine in the app, but if you need more than one you can easily do it manually

main.go
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	template "github.com/gofiber/template/html"
)

func main() {

	engineHTML := template.New("./views", ".html")
	engineXML := template.New("./xmls", ".xml")

	app := fiber.New(fiber.Config{
		Views: engineHTML,
	})

	app.Get("/rss", func(c *fiber.Ctx) error {

		// Set Content-Type to application/rss+xml
		c.Type("rss")
		// Set rendered template to body
		return engineXML.Render(c, "example", fiber.Map{
			"Lang":  "en",
			"Title": "hello-rss",
			"Greetings": "Hello World",
		})
	})

	app.Get("/html", func(c *fiber.Ctx) error {
		return c.Render("example", fiber.Map{
			"Lang":  "en",
			"Title": "hello",
			"Greetings": "Hello World",
		})
	})

	log.Fatal(app.Listen(":3000"))
}

```
views/example.html
```xml
<?xml version="1.0" encoding="UTF-8"?>
<note>
    <language>{{.Lang}}</language>
    <title>{{.Title}}</title>
    <greeting>{{.Greetings}}</greeting>
</note>
```
views/example.html
```html
<!doctype html>
<html lang="{{.Lang}}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>{{.Title}}</title>
</head>
<body>{{.Greetings}}</body>
```

![image](https://user-images.githubusercontent.com/7063188/110205744-2cf07c80-7e7a-11eb-8d14-6441de491a54.png)

Using several template engines is therefore very simple.

Maybe later we will change the 2nd parameter for the extension to use regular expressions.
The current limitation to one extension is not enough for me. 

@Fenny @kiyonlin what do you mean ? regex for extensions or an slice ?

Hopefully we could help, if there are no more questions, just close the issue.

**Comment by ReneWerner87** [comment]
Oh you can also use other template engines from our repository, the only thing you have to do is to execute the engine.Load method and inside the handler the engine.Render method.

**Comment by chovy** [comment]
I still get this in the output:

`&lt;?xml version="1.0" encoding="UTF-8"?>`

**Comment by chovy** [comment]
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fstartworkingremotely.com%2Fjobs%2Frss%3Fq%3DPhp%2520USA%2520

**Comment by ReneWerner87** [comment]
Please don't use the html engine for the xml, there is a auto encoding activated.

I use the mustache engine in my example.

**Comment by chovy** [comment]
you updated it thanks. works now.
