### ISSUE TITLE
Support Chunked Encoding🚀 

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#1209]
I need to create an endpoint that supports `chunked encoding`: https://www.tradingview.com/rest-api-spec/#operation/streaming

On `net/http` you can implement it like this: https://stackoverflow.com/questions/26769626/send-a-chunked-http-response-from-a-go-server

But on fiber, it doesn't seem to work if I try and copy the general approach.

This person also tried but failed: https://groups.google.com/g/golang-nuts/c/16cWqMIqvSc

**Comment by pjebs** [comment]
Can I use SendStream for this process?

```go
func Streaming(c *fiber.Ctx) error {
	ticker := time.NewTicker(1500 * time.Millisecond)
	defer ticker.Stop()

	for range ticker.C {

		// Create data
		resp := s{}

		// Convert to json
		b, _ := json.Marshal(resp)
		cb := new(bytes.Buffer)
		json.Compact(cb, b)
		b = cb.Bytes()
		log.Println(string(append(b, "\n"...)))

		// Send data
		streamData := bytes.NewReader(append(b, "\n"...))
		err := c.SendStream(streamData, 0)
		if err != nil {
			return err
		}
	}
}
```

**Comment by kiyonlin** [comment]
Maybe this valyala/fasthttp#840 can help you.

**Comment by pjebs** [comment]
@kiyonlin its unrelated

**Comment by kiyonlin** [comment]
Your process won't stop if no error occurs, right?

**Comment by pjebs** [comment]
yes
but I actually can't get anything to work.

**Comment by kiyonlin** [comment]
Have you tried `Ctx.Response().SetBodyStreamWriter`?

**Comment by kiyonlin** [comment]
> I can't see SetBodyStreamWriter in godoc

It's not commonly used, so we don't wrap it in fiber.

> And how do I stop sending data if the client closes connection?

Once client closes connection, write action in SetBodyStreamWriter should get error.

**Comment by pjebs** [comment]
@kiyonlin Thanks for the tip. It appears to work.
But in my case, I need to continually push (i.e. with the timer in the above snippet). I can't see a way to detect when the client closes the connection.

**Comment by pjebs** [comment]
That snippet is fine. But I need to continually push. I need a way to stop the push (i.e. stop the timer, and allow the goroutine to return) when the client closes the connection.

**Comment by pjebs** [comment]
I opened an issue here: https://github.com/valyala/fasthttp/issues/993

**Comment by kiyonlin** [comment]
> That snippet is fine. But I need to continually push. I need a way to stop the push (i.e. stop the timer, and allow the goroutine to return) when the client closes the connection.

If you got error there(no matter what happened), you can do what you want(stop the timer, and allow the goroutine to return)

**Comment by pjebs** [comment]
That approach doesn't seem to work at all. Clients can't even connect to it:


```go

func Streaming(c *fiber.Ctx) error {
	// Test using: curl -iv http://localhost:8080/v1/streaming
	q := make(chan error, 1)	
	c.Response().SetBodyStreamWriter(func(w *bufio.Writer) {
		ticker := time.NewTicker(1500 * time.Millisecond)
		defer ticker.Stop()

		for range ticker.C {
			// Create data
			resp := s{}

			// Convert to json
			b, _ := json.Marshal(resp)
			cb := new(bytes.Buffer)
			json.Compact(cb, b)
			b = cb.Bytes()
			// log.Println(string(append(b, "\n"...)))

			// Send data
			_, err := w.Write(append(b, "\n"...))
			if err != nil {
				q <- err
				return
			}

			err = w.Flush()
			if err != nil {
				q <- err
				return
			}
		}
	})
	return <-q
}

```

**Comment by kiyonlin** [comment]
> It appears for the endpoint to work, the outer request handler must return unimpeded, while the StreamWriter continues to operate in a seperate goroutine.

I don't understand what you do. If you get error, the function in `SetBodyStreamWriter` will return and the ticker will stop.

**Comment by pjebs** [comment]
Okay. I understand what you are saying.

**Comment by pjebs** [comment]
@kiyonlin thanks
