### ISSUE TITLE
Memory corruption in internal/memory/memory.go

### ISSUE THREAD

**Issue by iltish** [gofiber/fiber#1214]
**Fiber version**
2.5.0
**Issue description**
There seems to be some kind of memory corruption happening when using cache middleware without specifying storage that defaults to using https://github.com/gofiber/fiber/blob/master/internal/memory/memory.go

Initially it was noticed that after making many parallel requests to cached endpoints application keeps on having high CPU usage (despite cache being set for only 2 seconds). After running CPU profiler, it showed that most of the time is spent in `fiber/v2/internal/memory/(*Storage).gc` that just keeps on spinning in the loop without deleting cache entries from storage that should have been expired . Further investigation after adding print statements to `(*Storage).Set` and `(*Storage).gc` showed that keys of `Storage.data` keep on changing to fractions of string coming from other requests without any corresponding `Set` method calls.

Finally, when `s.db[key] = entry{val, expire}` is replaced by `s.data[(key + " ")[:len(key)]] = item{val, exp}` that force copies string instead of referencing it, the issue disappears.

**Code snippet**
It's an issues that is quite hard to reproduce, however, it happens when using caching like:
```go
app.Use("/cached/endpoints", cache.New(cache.Config{
		Expiration:   2 * time.Second,
		CacheControl: true,
	}))
```
and it seems to disappear when https://github.com/gofiber/fiber/blob/v2.5.0/internal/memory/memory.go#L48 is replaced with
```go
s.data[(key + " ")[:len(key)]] = item{val, exp}
```

I've also tried to put full write locks `s.Lock()` and `s.Unlock()` for every function call in `Storage` interface just in case, but that didn't have any effect.

Please let me know if there is any other debugging I can do to further clarify this, since shipping the entire application along with frontend and load-tester is not an option and at this stage I'm not sure what exactly triggers this behavior.

**Comment by iltish** [comment]
Looks like I found the issue - default key generator for cache middleware is not safe to use directly as the content of the string it returns seems to get modified later.

When using cache middleware in the following way, the issue also disappears:
```
app.Use("/cached/endpoints", cache.New(cache.Config{
		Expiration:   2 * time.Second,
		CacheControl: true,
                KeyGenerator: func(c *fiber.Ctx) string {return c.Path()+" "},
	}))
```

**Comment by ReneWerner87** [comment]
yes due to our reuse of the memory areas, this is a conceivable error if you adjust the path inside and use the cache middleware around the outside

it is also possible to switch the app back to immutable string, then everything is a bit slower, but you don't run into such errors
https://docs.gofiber.io/api/fiber#config
fiberConfig{Immutable: true}


would close the issue, if you have any comments or suggestions for improvement, just post or reopen it

**Comment by ReneWerner87** [comment]
```go
KeyGenerator: func(c *fiber.Ctx) string {return utils.CopyString(c.Path())},
```
by the way, you can also use our copy string function
