### ISSUE TITLE
API Key & Key=Val middleware

### ISSUE THREAD

**Issue by bogdanciuca** [gofiber/fiber#1216]
**Question description**

Hi, I've recently written 2 `fiber` middlewares: 
- one that checks the `API Key` extracted from the request against a cache and can accept / block the request, perform some custom action, etc.
- the other is a more generic `Key=Val` approach, in which data can be extracted from various sources like headers, query params, form data, etc and can also be used to accept / block requests, perform some custom action, etc.

I think these two should work well with other middleware like `cache`, `limiter`, `jwt`, etc and I was wondering if any of them would make sense as official middleware.

Thanks!

**Comment by kiyonlin** [comment]
Hey thank you for your work! But I don't know if you've noticed we already have [keyauth](https://github.com/gofiber/keyauth), is this similar to what you said?

**Comment by bogdanciuca** [comment]
Yep, pretty much, so It appears that I haven't 😞  I went through `fiber/middleware` mostly. Thanks, `userauth` looks great, you can close this.

**Comment by kiyonlin** [comment]
We also have some [external middlewares](https://github.com/gofiber/fiber#-external-middleware) which may depend on other 3rd packages, so we didn't put them into fiber core repo.
