### ISSUE TITLE
JSON Decoder/Encoder - Segment vs goccy/go-json

### ISSUE THREAD

**Issue by bogdanciuca** [gofiber/fiber#1217]
**segmentio vs go-json**

Hi, I saw you guys recently switched to `segmentio`. I was wondering if you considered [go-json](https://github.com/goccy/go-json)? Its benchmarks look pretty amazing. 

Also, congrats on the latest round of `TechEmpower` benchmarks 🥳

**Comment by hi019** [comment]
Hello! For now you can look at https://github.com/goccy/go-json/issues/149 if you want to use go-json with Fiber. As for making it the default, the other maintainers can chime in.

**Comment by kiyonlin** [comment]
Thanks for the suggestion! We've noticed it last year. It looks promising in benchmarks. But it's younger and less stable. Maybe we can wait a little longer. And you can use it as your json decoder by setting `Config.JSONEncoder`(I think you know it).

**Comment by bogdanciuca** [comment]
Yes, I noticed the JSON Encoder is now configurable, was a bit curious on your assessment of it. Seeing the recurring issue cleared things up. Thanks!
