### ISSUE TITLE
🤗 Request/response interceptor

### ISSUE THREAD

**Issue by artjoma** [gofiber/fiber#1219]
**Request/response interceptor**

Any code examples ? Similar to: https://tomcat.apache.org/tomcat-9.0-doc/servletapi/javax/servlet/Filter.html Servlet API specification.

**Comment by kiyonlin** [comment]
Is this what you want? 
https://docs.gofiber.io/api/ctx#next

**Comment by artjoma** [comment]
Not, I want to have an interceptor(function or method) that called before and after call of each handler. I want to include elapsed time to every response for all my url handlers.

**Comment by kiyonlin** [comment]
It's called [middleware](https://docs.gofiber.io/api/middleware) in fiber.

**Comment by artjoma** [comment]
Thank you!
