### ISSUE TITLE
🤗 Static vs filesystem

### ISSUE THREAD

**Issue by GarryGaller** [gofiber/fiber#1220]
**Question description**
Is there any difference between using the Static method and middleware filesystem?
**Code snippet** _Optional_

```go
doc := filepath.Join(t.Exe.Dir, "../doc")
app.Static("/api", doc, options)
```
vs
```go

doc := filepath.Join(t.Exe.Dir, "../doc")
app.Use("/api", filesystem.New(filesystem.Config{
        Root: http.Dir(doc),
    }))
```
I will add that in both cases I have a problem with the availability of css and js resources along this route.
And, interestingly, when using the route via nginx, there is no problem.

```nginx
location /api {
            alias   /app/doc;
            index  index.html;
            expires 1d;
        }
```

But I would like to understand why there is a problem with routing inside fiber. If you enter the full path to the index file in the browser: server.com/api/index.html
then everything works - all the documentation resources from the app/doc directory are available. Otherwise, they are searched by the path from the root of the server, and not relative to this directory.

**Comment by ReneWerner87** [comment]
Thank you for your report

Both functionalities work a bit differently and the filesystem middleware is rather meant for embedded files, if you want to deliver pure static files that are located next to the golang code or binary, I would recommend app.Static

Unfortunately i can't reproduce the error you describe there without a reproducible setup.
Can you(@GarryGaller ) provide me with a minimal setup, with the content of the files, maybe some very stripped down js, css, html files.

**Comment by GarryGaller** [comment]
Here is a partial structure of the project.
The bin directory contains the binary file of the compiled application.
The app runs on heroku via procfile:
bin/myapp

Application directory on heroku (app):
├───assets
│   ├───css
│   ├───errors
│   ├───fonts
│   ├───js
│   └───templates
│       ├───css
│       └───js
├───bin
│   └───logs
│       └───tr
├───cli
├───config
├───doc
│   ├───css
│   ├───fonts
│   ├───img
│   ├───locales
│   ├───utils
│   └───vendor
│       └───path-to-regexp

When using a router from nginx, all resources inside the doc are available, then taken from the directories inside the doc.
When using Static or middleware filesystem, resources from the doc/vendor directory are requested relative to the site root and therefore get a 404 error when loading the index file.

Perhaps there is some problem with the file paths, which is not related to fiber.
That's why I asked this question, because unfortunately I can't understand it myself.

**Comment by ReneWerner87** [comment]
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	// Pass the engine to the Views
	app := fiber.New()
	app.Static("/api", "./docs")

	log.Fatal(app.Listen(":3000"))
}
```
![image](https://user-images.githubusercontent.com/7063188/111035457-f76c0600-841a-11eb-8502-75b5604a4988.png)

![image](https://user-images.githubusercontent.com/7063188/111035491-1ff40000-841b-11eb-9aae-2b45ed370672.png)
![image](https://user-images.githubusercontent.com/7063188/111035501-27b3a480-841b-11eb-9bd1-268f2f0d19fe.png)

I have started up the bootstrap starter as a test,
unfortunately can not find any error

Maybe this will help you to find the error in your code, unfortunately I can't help you if I don't have a complete setup with all the information to recreate it.
Could be the paths or the settings, unfortunately you didn't share them

How the resources are requested in the browser is up to you, there is nothing fiber can do about it, it is crucial how the paths look in the html and if a base tag is set or how the referencing is within the other files

Fiber delivers the static content in the same way as nginx.

Can you maybe share the paths and the golang code and screenshot the error in the browser ?

**Comment by GarryGaller** [comment]
I don't quite understand what other settings to show you.
I have a huge application (microservice) and it is difficult to give some code.

The problem, as I have already pointed out, is only available from the app/doc documentation directory: more precisely, the app/doc/vendor subdirectory. Resources are extracted from the remaining subdirectories.

![vendor](https://user-images.githubusercontent.com/20813879/111043595-6580ef00-8454-11eb-93f4-ba5a2e38a305.jpg)
![vendor2](https://user-images.githubusercontent.com/20813879/111043877-26ec3400-8456-11eb-897a-d64b662aba84.jpg)

**Comment by ReneWerner87** [comment]
Please use a slash at the end of your route

http://localhost:3001/api/

And give me feedback

**Comment by GarryGaller** [comment]
![api](https://user-images.githubusercontent.com/20813879/111044239-5a2fc280-8458-11eb-93f5-aa13f34cd286.jpg)
-----------------
![api2](https://user-images.githubusercontent.com/20813879/111044242-5dc34980-8458-11eb-96ff-3befbf9a6e60.jpg)
-------------------
![api3](https://user-images.githubusercontent.com/20813879/111044247-6582ee00-8458-11eb-8f17-86459e2796a0.jpg)

**Comment by ReneWerner87** [comment]
Meant the static settings, there in your information you have referred to other variables, but I do not know what is behind the variables, the same with the golang code for the paths, there are variables used that are not known.

Sure you have a big microservice, but to find the error it is sometimes better to cut down the setup to a minimum to find the error, this helps most of the time, this is also good to exclude other parts of the software when acting and to make the code for others shareable and understandable (even if placeholders are used)



In the previous comment I wrote that you should pay attention to the last slash, because the browser removes the last element up to the slash and lets the resources which are relative in their call, start from this url i.e. in this case from the root, because "api" is removed, if it ends with a slash, it starts the relative path from there.

Of course only if no basepath was specified

**Comment by ReneWerner87** [comment]
Leave the settings in the golang code as before, just add the slash to the end in the browser url


So use
 app.Static("/api".....

**Comment by GarryGaller** [comment]
```Index:         t.C.Use.Static["api"].Index,
```

this  this is the setting from the config
[use.static.api] 
 index = "index.html"

**Comment by GarryGaller** [comment]
> Leave the settings in the golang code as before, just add the slash to the end in the browser url

Exact same browser response:
Cannot GET /api/

**Comment by ReneWerner87** [comment]
```go
	app.Get("/api/", func(ctx *fiber.Ctx) error {
		return ctx.SendFile("./docs/index.html")
	})
	app.Static("/api/", "./docs")
```

currently don't know why the index is not loaded if you only store the static url, but this way it should fit for now


if your problem is solved, feel free to close the issue

**Comment by ReneWerner87** [comment]
or leave it as it is and just place a base tag in the head at the top position
![image](https://user-images.githubusercontent.com/7063188/111065007-b2e27800-84b7-11eb-9618-e6ebec539308.png)

![image](https://user-images.githubusercontent.com/7063188/111065003-acec9700-84b7-11eb-85aa-40e1d00dcdd6.png)

**Comment by GarryGaller** [comment]
1)  Yes, that is how it works.

```
    doc = "./doc"
    app.Get("/api/", func(ctx *fiber.Ctx) error {
		return ctx.SendFile(filepath.Join(doc, "index.html"))
	})
    
    app.Static("/api/", doc, options)
```
But shouldn't it work even without sending the file? 


2) Rearranging the positions of the routes did not give any positive result.
