### ISSUE TITLE
🐛 JSON body & FormFile are not captured properly using Lambda Fiber adapter

### ISSUE THREAD

**Issue by greeeg** [gofiber/fiber#1223]
**Fiber version**
v2.5.0

**Issue description**
Hello fellow contributors, first thanks for your amazing work on Fiber, it's a joy to use 🤗

I'm having trouble using Fiber with [AWS Lambda Go proxy for fiber](https://github.com/awslabs/aws-lambda-go-api-proxy/tree/master/fiber) when sending POST requests with JSON or multipart/form-data.

Indeed, using `c.BodyParser()` or `c.FormFile()`, I'm getting errors which seems to be related to how Fiber internally checks the content-type for these requests.

When logging the incoming request of type `events.APIGatewayProxyRequest`, I can see my headers but when I log `c.Request()` I can not see these headers. I believe Fiber and fasthttp rely on these headers to validate the request. Could it be possible that some updates made to Fiber, fasthttp or the adapter introduced this bug or am I missing something?

**Code snippet**

```go
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
	fiberadapter "github.com/awslabs/aws-lambda-go-api-proxy/fiber"
	"github.com/gofiber/fiber/v2"
)

func NewApp() *fiber.App {
	app := fiber.New()

	app.Use(func(c *fiber.Ctx) error {
		marshalledCts, _ := json.Marshal(c.Request().Header)
		fmt.Println(string(marshalledCts))
		fmt.Println(c.Get("Content-Type"))
		return c.Next()
	})

	return app
}

func getLambdaHandler(ctx context.Context, req events.APIGatewayProxyRequest) (events.APIGatewayProxyResponse, error) {
	marshalledCtx, _ := json.Marshal(req)
	fmt.Println(string(marshalledCtx))
	return fiberadapter.New(NewApp()).ProxyWithContext(ctx, req)
}

func main() {
	lambda.Start(getLambdaHandler)
}
```

**Comment by ReneWerner87** [comment]
thanks for the report, we will test it later


Note for me to test:
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-start-api.html

**Comment by mininoz** [comment]
I got the same problem. Any solution or workaround?

**Comment by ReneWerner87** [comment]
not yet, unfortunately had not yet time to take on this problem

**Comment by joliny** [comment]
https://github.com/valyala/fasthttp/issues/968
https://github.com/valyala/fasthttp/issues/781
set Server.DisablePreParseMultipartForm=true

**Comment by ReneWerner87** [comment]
@greeeg does the error still occur ?

**Comment by efectn** [comment]
Fixed by https://github.com/awslabs/aws-lambda-go-api-proxy/pull/115. Thanks to @drakejin
