### ISSUE TITLE
Using context.Render() to render a template with html not being escaped🤗 

### ISSUE THREAD

**Issue by Foosec** [gofiber/fiber#1224]
**Question description**
Ive got some markdown, which i parse into HTML.
I would now like to render that HTML with context.Render() into my template

```
{{template "header" .}}

<div>
    {{ .BlogPost.PostText }}
</div>

{{template "footer" .}}
```

where PostText is HTML that i would like to not be escaped.
It seems that by default it escapes the HTML and it doesn't get rendered by the browser. 
How can i work around this?

**Comment by ReneWerner87** [comment]
Use the same solution as in https://medium.com/@arvindsris/how-did-i-unescape-values-in-a-template-using-go-lang-8ce987e8d1f7

**Comment by Foosec** [comment]
Thank you for the superbly quick response!
