### ISSUE TITLE
🐛 Streaming with SetBodyStreamWriter results in deadlock

### ISSUE THREAD

**Issue by SoftExpert** [gofiber/fiber#1225]
**Fiber version**
2.6.0
**Issue description**
Using **SetBodyStreamWriter** leads to a deadlock: only 5 items are being generated, but the client which makes the call does not receive anything; trying to gracefully shutdown the application does not work either - it waits indefinitely for the connections to be closed; **ReadTimeout** does not seem to have any effect.
I included the full code of a small demo application - once running just visit http://localhost:8080/v1/streaming from a browser / tool and you will be able to see the behavior described.

**Code snippet**

```go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/segmentio/encoding/json"
)

var app *fiber.App

func main() {

	app = fiber.New(fiber.Config{
		Prefork:          false,
		DisableKeepalive: true,
		JSONEncoder:      json.Marshal,
		ReadTimeout:      time.Second * 20,
	})
	app.Use(cors.New())

	// send runtime data to chart
	app.Get("/v1/streaming", StreamingHandler)

	// Listen from a different goroutine
	go func() {
		if err := app.Listen(":8080"); err != nil {
			log.Panic(err)
		}
	}()

	c := make(chan os.Signal, 1)                    // Create channel to signify a signal being sent
	signal.Notify(c, os.Interrupt, syscall.SIGTERM) // When an interrupt or termination signal is sent, notify the channel

	_ = <-c // This blocks the main thread until an interrupt is received
	fmt.Println("Gracefully shutting down...")
	_ = app.Shutdown()

	fmt.Println("Running cleanup tasks...")

	// Your cleanup tasks go here
	// db.Close()
	// redisConn.Close()
}

type dataPoint struct {
	X string
	Y int64
}

// StreamingHandler ...
func StreamingHandler(c *fiber.Ctx) error {
	// Test using: curl -iv http://localhost:8080/v1/streaming
	q := make(chan error, 1)
	c.Response().SetBodyStreamWriter(func(w *bufio.Writer) {
		ticker := time.NewTicker(1500 * time.Millisecond)
		defer ticker.Stop()

		for range ticker.C {
			// Create data
			resp := dataPoint{
				X: "aa",
				Y: 12546,
			}

			// Convert to json
			b, _ := json.Marshal(resp)
			cb := new(bytes.Buffer)
			json.Compact(cb, b)
			b = cb.Bytes()
			log.Println(string(append(b, "\n"...)))

			// Send data
			_, err := w.Write(append(b, "\n"...))
			if err != nil {
				q <- err
				return
			}

			err = w.Flush()
			if err != nil {
				q <- err
				return
			}
		}
	})
	return <-q
}
```

**Comment by tianjipeng** [comment]
You should return ``nil`` instead of ``return <-q``，otherwise it will block. Why is it always 5 items?  For ``streamWriter`` fasthttp  will create ``PipeConns`` like this:
```go
func NewPipeConns() *PipeConns {
	ch1 := make(chan *byteBuffer, 4)
	ch2 := make(chan *byteBuffer, 4)
        ....
}
```

**Comment by SoftExpert** [comment]
Well, the idea was to continuously generate data, every 1.5 sec ...

**Comment by SoftExpert** [comment]
You are right, should use `return nil ` to have the process close.
But ... this is still not working.
With the following handler the content is still not sent and the connection never closes.
Still have to kill the app ...

```go
// StreamingHandler2 ...
func StreamingHandler2(c *fiber.Ctx) error {
	c.Response().Header.SetContentType("text/event-stream")
	c.Response().Header.Set("Transfer-Encoding", "chunked")
	c.Response().Header.Set("Cache-Control", "no-cache")
	c.Response().Header.Set("Connection", "keep-alive")
	c.Response().Header.Set("Access-Control-Allow-Origin", "*")
	c.Response().Header.Set("Access-Control-Allow-Headers", "Cache-Control")
	c.Response().Header.Set("Access-Control-Allow-Credentials", "true")
	c.Response().SetBodyStreamWriter(func(w *bufio.Writer) {
		fmt.Println("BodyStreamWriter")
		for i := 0; i < 10; i++ {
			msg := fmt.Sprintf("%d - the time is %v", i, time.Now())
			fmt.Fprintf(w, "data: Message: %s\n\n", msg)
			fmt.Println(msg)
			// Flush the response. This is only possible if the response supports streaming.
			w.Flush()
			time.Sleep(2 * time.Second)
		}
	})

	c.SendStatus(fiber.StatusOK)
	return c.Next()
}
```

**Comment by kiyonlin** [comment]
Why do you set DisableKeepalive to true?

**Comment by SoftExpert** [comment]
To be able to stop the application; otherwise it will never close.

**Comment by kiyonlin** [comment]
> To be able to stop the application; otherwise it will never close.

I don't follow this. If you disable keep alive, once you sent response, the connection was closed. So you can not send data again through the connection.

**Comment by SoftExpert** [comment]
I see... But the streaming is supposed to keep the connection open, right ? 
In my understanding, the stream keeps on writing data, so the connection is kept alive.
`Disable keep-alive connections, the server will close incoming connections after sending the first response to the client`
Have I misunderstood ?

**Comment by kiyonlin** [comment]
stream relies on tcp connection but you close it via `DisableKeepAlive = true`

**Comment by SoftExpert** [comment]
Ok, I tried with DisableKeepalive: false.
With the first handler (StreamingHandler) the request does not receive data and does not close; I cannot close the app.
With the second handler (StreamingHandler2) the request does not receive data, but when the loop ends the stream closes and I get `Cannot GET /v2/streaming` on the client side.

**Comment by tianjipeng** [comment]
@SoftExpert Try ``return nil`` instead of ``return c.Next()``. When use ``c.Next()``, fiber  will look up handler, but there is no other handler except ``StreamingHandler2``.

**Comment by SoftExpert** [comment]
That did it! Thank you - I really have to brush up my documentation reading !

**Comment by SoftExpert** [comment]
Seems to be related to https://github.com/gofiber/websocket/issues/36
Is this a bug in fasthttp or quirk in fiber ?
If this makes sense, it would be interesting to be able to close connection for http requests as soon as the response is sent, but have the websockets persist.
Is this possible currently ?

**Comment by kiyonlin** [comment]
May I ask why do you set `DisableKeepalive` to true?

**Comment by kiyonlin** [comment]
> why have it as a parameter and not enforce it by default ?

Keepalive is for resource reuse, especially browsers, without establishing a tcp connection every time.
