### ISSUE TITLE
🤗 rerender all views without restart apps

### ISSUE THREAD

**Issue by goldalworming** [gofiber/fiber#1230]
Hello, Thank you for awesome framework.

But how do I rerender all views when I make changes without reload apps.
for now I use this code to set Reload to true in view engine 

    app.Get("/rerender", func(c *fiber.Ctx) error {
        engine.Reload(true)
        return c.Redirect("/")
    })
    app.Get("/fix", func(c *fiber.Ctx) error {
        engine.Reload(false)
        return c.Redirect("/")
    })

but then I have to access all views to make changes saved in cached view system then set Reload to false again so it's cached again. Do you have more effective solution for this problem?

Thank you

**Comment by koddr** [comment]
@goldalworming hi!

As far as I understand, you can add some query to URL with dumpy data and redirect to it. 

For route this query doesn't make any effect:

```go
app.Get("/rerender", func(c *fiber.Ctx) error {
    engine.Reload(true)
    return c.Redirect("/?some_query=123456") // for ex., math random
})
```

**Comment by ReneWerner87** [comment]
@goldalworming have a look at the code and i would try the code snippet

```go
app.Get("/rerender", func(c *fiber.Ctx) error {
    engine.Reload(true)
    if err := engine.Load(); err != nil {
        panic(err)
    }
    engine.Reload(false)
    return c.Redirect("/")
})
```

if your question is answered, please give feedback and close the issue if it is sufficient

**Comment by goldalworming** [comment]
ok thank you. I'll try it

**Comment by goldalworming** [comment]
I've try it @ReneWerner87 and it's still doesn't work

**Comment by Jleagle** [comment]
Adding to @goldalworming's comment, my handlers are in a different package so i do not have access to `engine`.

    engine := html.New()
    engine.Reload(true)
The code and the comments read like it should just always reload all templates.

**Comment by leonklingele** [comment]
I noticed that the `reload` field is no longer checked as of 156b81c768ec3e9e8b4cfdf6a37040fa8daa0e0 where it got removed by accident (I suppose), so this definitely no longer works.

**Comment by Fenny** [comment]
> I noticed that the `reload` field is no longer checked as of [156b81c](https://github.com/gofiber/fiber/commit/156b81c768ec3e9e8b4cfdf6a37040fa8daa0e07) where it got removed by accident (I suppose), so this definitely no longer works.

Templates have been moved to a separate repository, reload is present https://github.com/gofiber/template/blob/master/html/html.go#L127
