### ISSUE TITLE
Flash Messages

### ISSUE THREAD

**Issue by jjude** [gofiber/fiber#1231]
**Describe the solution you'd like**

When we develop web applications, we have to flash messages (your action is not successful...) between requests. Beego has flash messages: https://beego.me/docs/mvc/controller/flash.md. Something similar in Fiber would be helpful.

**Describe alternatives you've considered**

This can be implemented via session cookies. But having this as an explicit middleware would be good.

**Comment by sujit-baniya** [comment]
@jjude Maybe you are looking for this Flash Message implementation on the top of Fiber https://github.com/sujit-baniya/flash

**Comment by Fenny** [comment]
This sounds like something that can be developed as a third party library like https://github.com/sujit-baniya/flash. Thanks for the suggestion though!
