### ISSUE TITLE
Custom marshalers 🚀 

### ISSUE THREAD

**Issue by FedorLap2006** [gofiber/fiber#1232]
**Is your feature request related to a problem?**

Yes, it kinda is. In my case, internal marshalers is not the best ones, so I went into docs trying to find some configuration for those, but I couldn't, that's why I went here.

**Describe the solution you'd like**

An ability to switch marshalers for MIME types. See `grpc-gateway`'s API, it's very comfortable one.

**Describe alternatives you've considered**

There's no alternative. Sometimes we really need to use custom marshaler. You can improve internal/external marshalers, but there must be some room for customization, because they doesn't fit so good in some situations.

**Additional context**

This is feature/question issue.

**Comment by ReneWerner87** [comment]
Thx for the report,

You mean something like that? 
https://github.com/gofiber/fiber/blob/master/app.go#L281

**Comment by ReneWerner87** [comment]
@FedorLap2006

**Comment by FedorLap2006** [comment]
Oh, I'm so sorry, forgot about this thing. @ReneWerner87, yeah, I mean exactly this but for Unmarshaling.

**Comment by FedorLap2006** [comment]
Hope this issue will be reopened :disappointed:

**Comment by FedorLap2006** [comment]
Thanks.

**Comment by Fenny** [comment]
@FedorLap2006 I think we are talking about a
```go
JSONDecoder utils.JSONUnmarshal `json:"-"`
```
feature for `BodyParser`?

**Comment by FedorLap2006** [comment]
> @FedorLap2006 I think we are talking about a
> 
> ```go
> JSONDecoder utils.JSONUnmarshal `json:"-"`
> ```
> 
> feature for `BodyParser`?

Well, yeah
