### ISSUE TITLE
remove endpoint 🚀 

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#1233]
It would be good to be able to remove an endpoint from *App completely at some point after adding it.

i.e. unregister a route

The use case is for testing purposes so it doesn't have to worry about mutexes.

**Comment by kiyonlin** [comment]
It's better to test your route with an independent app instance.

**Comment by pjebs** [comment]
not for purpose. it would be nice to add and remove routes even if it's not wise to remove routes generally.

**Comment by kiyonlin** [comment]
Please see #735 and #600

**Comment by pjebs** [comment]
Yeah that is very disappointing because the creator is thinking about it from a production point of view. I agree routes should not be changed in production.

But for other purposes there are use cases.

**Comment by kiyonlin** [comment]
> But for other purposes there are use cases.

Like what?

**Comment by kiyonlin** [comment]
I'll close it first. Feel free to re-open it if you have any idea.
