### ISSUE TITLE
🤗 How to get "home path" in fiber.Ctx?

### ISSUE THREAD

**Issue by iredmail** [gofiber/fiber#1236]
Dear all, how can i get the homepath of URL in fiber.Ctx? I checked `baseURL`, `Path`, `OriginalURL`, none of them matches my need.

For example, if i run the Go fiber app directly without a Nginx proxy, the URL is `http://server:8080`, the `homepath` should be set to `/`.

If fiber app is running behind a Nginx proxy, and the base url in Nginx for rewritten is `https://server/sub/myapp`, then the `homepath` should be set to `/sub/myapp`.

This way i can use this `homepath` in template engine and set the correct path to CSS/JS files and other URLs served by my fiber app.

I used Python web.py framework, it offers homepath in its ctx. Check here for reference (search "homepath" and you will find it at the bottom):
https://webpy.org/cookbook/ctx

**Comment by ReneWerner87** [comment]
Hope this helps, i subtracted the base url and the route path from the url, so this should be the home url

Go code:
```go
    app.Get("/*", func(c *fiber.Ctx) error {
        fmt.Println("c.Path()", c.Path())
        fmt.Println("c.BaseURL()", c.BaseURL())
        fmt.Println("c.OriginalURL()", c.OriginalURL())
        fmt.Println("c.Context().RequestURI()", string(c.Context().RequestURI()))
        fmt.Println("c.Context().URI().String()", c.Context().URI().String())
        fmt.Println("homePath", strings.TrimSuffix(strings.TrimPrefix(c.Context().URI().String(), c.BaseURL()), c.Path()[1:]))

        return c.SendStatus(200)
    })
```
Request:
GET http://localhost:3000/test/foo/bar

Output:
```text
c.Path() /test/foo/bar
c.BaseURL() http://localhost:3000
c.OriginalURL() /test/foo/bar
c.Context().RequestURI() /test/foo/bar
c.Context().URI().String() http://localhost:3000/test/foo/bar
homePath /
```

**Comment by iredmail** [comment]
Dear @ReneWerner87 

Thank you for the reply.
Can we add a new method for `fiber.Ctx`  to get this path? It will be a lot easier for fiber users.

**Comment by ReneWerner87** [comment]
don't know yet if this is necessary,
but you can create a pull request for it, with unittests, documentation etc. and then we can take it over(if the other maintainers agree)

**Comment by iredmail** [comment]
Can i simply add a new method in `ctx.go` like below?
```
// HomeURL returns the home path which serves the fiber application.
func (c *Ctx) BaseURL() string {
	return strings.TrimSuffix(strings.TrimPrefix(c.Context().URI().String(), c.BaseURL()), c.Path()[1:])
}
```

unitests and documents are on the way?

**Comment by iredmail** [comment]
The sample code doesn't seem right.

Sample Nginx settings (FYI: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass).
Note: the only difference is prepended URI in `proxy_pass` directive.

```
# Sample 1
location /sub/myapp/ {
    proxy_pass http://127.0.0.1:3000;
}

# Sample 2
location /sub/myapp/ {
    proxy_pass http://127.0.0.1:3000/;
}
```

Now run `curl -k https://localhost/sub/myapp/test/abc`, output:

- Sample 1
```
c.Path() /sub/myapp/test/abc
c.BaseURL() http://127.0.0.1:3000
c.OriginalURL() /sub/myapp/test/abc
c.Context().RequestURI() /sub/myapp/test/abc
c.Context().URI().String() http://127.0.0.1:3000/sub/myapp/test/abc
homePath /
```

- Sample 2
```
c.Path() /test/abc
c.BaseURL() http://127.0.0.1:3000
c.OriginalURL() /test/abc
c.Context().RequestURI() /test/abc
c.Context().URI().String() http://127.0.0.1:3000/test/abc
homePath /
```

In sample 2, homePath should be `/sub/myapp`.

**Comment by ReneWerner87** [comment]
oh okay, so the golang service doesn't have the information about the path because it is proxied

so how should we display the information? can you(@iredmail ) find out in the python app how they did it there ?
---
will be hard if we don't have the information in the request, then you would have to inject the information via an environment variable

**Comment by iredmail** [comment]
Check this in web.py source code: https://github.com/webpy/webpy/blob/master/web/application.py#L449
It checks environment variable `REAL_SCRIPT_NAME` first, if not present, checks `SCRIPT_NAME`.

With `proxy_pass`, seems it's ok to set the `[REAL_]SCRIPT_NAME` variable like below:
```
proxy_set_header SCRIPT_NAME /sub/myapp;
```
But i failed to get its value in Go code with `os.Getenv("SCRIPT_NAME")`.

**Comment by ReneWerner87** [comment]
proxy_**set_header**
i think you should ask the headers, not the env

**Comment by iredmail** [comment]
Using `c.Get("SCRIPT_NAME")` is ok in this case. Thanks for helping. :)
