### ISSUE TITLE
🤗 why fiber.Map alters the order ?

### ISSUE THREAD

**Issue by tomaswarynyca** [gofiber/fiber#1239]
Hi, why when I do `fiber.Map{}` it does not return in the same order that I passed things to it?

**Comment by ReneWerner87** [comment]
Hi, thanks for your first post

We use a standard map here, so this behavior you observed is quite normal and golang specific. 

If you want to keep the sorting, you have to use other datatypes

Little bit background information about the map order:
https://www.google.com/amp/s/bitfieldconsulting.com/golang/map-iteration%3fformat=amp

**Comment by tomaswarynyca** [comment]
Hi, @ReneWerner87
Ohh now I understand by default it is sorted alphabetically.
