### ISSUE TITLE
Start gofiber with https on localhost/lan 🤗 

### ISSUE THREAD

**Issue by adnan-kamili** [gofiber/fiber#1245]
Is there a simple way to run gofiber using HTTPS and HTTP both inside LAN/localhost by automatically creating the self-signed certificates on startup? Something similar to what .net core does. It always listens on two ports by default 5000 and 5001 where the other one uses HTTPS using auto-generated self-signed certificates.

**Comment by koddr** [comment]
@adnan-kamili hi!

You can try [this](https://github.com/gofiber/recipes/tree/master/autocert) Fiber's recipe to solve this.

**Comment by adnan-kamili** [comment]
Hi @koddr 

Thanks but this solution is meant for real domains, not the localhost/lan. We want to use self signed certificates because the server will run in an offline environment.

**Comment by koddr** [comment]
Have you tried creating a self-signed SSL certificate like [this](https://www.digitalocean.com/community/tutorials/how-to-create-a-self-signed-ssl-certificate-for-apache-in-ubuntu-18-04) way? Please try it and then just use the standard `app.ListenTLS()` method (from [Fiber docs](https://docs.gofiber.io/api/app#listentls)).

**Comment by ReneWerner87** [comment]
Side note:
Starting a server listening on both ports may not be currently possible, but you can start the server binary 2 times with different parameters (--http and --https) and based on that, listen once on the port for 443 and in the other server start the port 80, from a theoretical point of view there should be nothing against it.

**Comment by G2G2G2G** [comment]
@ReneWerner87 With that answer and just FYI to anyone who is curious. I've been doing this in production on fiber for several months and works fine. Almost all of them have websocket instances going as well... For multiple domains and subdomains that need to access the same backend without allowing CORS or anything. 

```
func main() {
	go runCron()
	go runEmployees()
	go runAdmin()
	go runMain()
	go runClient()
	runManage()
}
```

all listen on different ports, nginx is in front of them reverse proxing those specific ports to actual subdomains/domains
