### ISSUE TITLE
🤗 Context Propagation

### ISSUE THREAD

**Issue by adrianliechti** [gofiber/fiber#1249]
We are currently implementing OpenTelemetry in a huge application. Fiber is our last missing part :)

OpenTelemetry and similar frameworks make use of go's Context propagation. Basically you do something like this:

```
func(ctx context.Context) {
		var span trace.Span
		ctx, span = tracer.Start(ctx, "operation")
		defer span.End()
		
		// continue with this ctx
		// callMyDb(ctx, xxx)
```

invoked sub-systems (think about databases, gprc clients etc), do the same over again and extend the Context with more and more info - or even serialize it to other microservces where this continues.

Now with Fiber v2, I do not know how to overwrite the Context in a middleware. It seems this was somehow possible in version v1 . Maybe also the adapter middleware is doing something like that.

I am are that you want to keep fiber simple - and that's great.

Maybe it's an idea to use your locals or likewise feature:
-> setting a context as local with a special key
-> c.Context() would return this instead the fasthttpctx

Next to tracing, this is of course also an essential feature for distributed logging.

Certainly, we could make a middleware to store the context in a local; and then use a small helper to extract it again and continue with that in functions and sub-systems.

But maybe... you also like the idea or have suggestions in a similar direction.

**Comment by ReneWerner87** [comment]
Maybe this will help you 

https://github.com/gofiber/recipes/tree/master/fiber-opentelemetry

**Comment by adrianliechti** [comment]
thanks for pointing me out to that and your super responsiveness!
I see that this receipt has a similar idea and therefore need to lookup the context to via locals.

A problem with that approach is that it is kind of proprietary to the app and would not scale over the fiber community. As an example your super handy adapter middleware would ignore it that way, and would not propagate it into the request.Context. So if I use as an example a graphql handler, the tracing context would be empty

If you compare this with opentelemetries contrib implementation for gin this might be a disadvantage
https://github.com/open-telemetry/opentelemetry-go-contrib/blob/main/instrumentation/github.com/gin-gonic/gin/otelgin/gintrace.go#L59

I could imagine that something like a c.NextWithContext(ctx) would enable much more cases

**Comment by adrianliechti** [comment]
For this evening we end with this quick workaround, to leverage the official opentelemetry net/http instrumentation and keep having fun with fiber.

We (probably) prefer this over maintaining an own implementation - and benefit from their community too.
(the one referenced in the receipt is currently outdated because of smaller updates of the sdk; and seems to lack some important features like propagation)

```
package fiber

import (
	"net/http"

	"github.com/gofiber/adaptor/v2"
	"github.com/gofiber/fiber/v2"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"
)

func Enable(app *fiber.App) {
	app.Use(adaptor.HTTPMiddleware(func(h http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			operation := r.Method + " " + r.URL.RawPath

			ctx, span := otel.GetTracerProvider().Tracer("fiber").Start(r.Context(), operation)
			defer span.End()

			r = r.WithContext(ctx)
			w.Header().Add("Trace-Id", span.SpanContext().SpanID().String())

			h := otelhttp.NewHandler(h, operation)
			h.ServeHTTP(w, r)
		})
	}))
}
```
