### ISSUE TITLE
Middleware not processing route params 🐛 

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#1250]
**Fiber version**
v2.2.5  
**Issue description**

I have a middleware that is being applied generally:

```go
v1.Use(setAccount) <-----
v1.Get("/accounts/:accountID/orders", orders.GetOrders)
```

This middleware attempts to access: `c.Params("accountID")`.

For some reason it doesn't have access to it when it should.

If I move it do this instead, it works:

```go
v1.Get("/accounts/:accountID/orders", setAccount, orders.GetOrders)
```

Since the route is known from the very beginning, why can't it access the route param?

**Comment by ReneWerner87** [comment]
The routing parameters are only valid for the specific route, if you define a middleware without routing parameters, the parameters can not be accessed, this scope is important and can not be moved.

This behavior should be identical in all web frameworks i know.

**Comment by pjebs** [comment]
thanks

**Comment by ReneWerner87** [comment]
no problem 👯
