### ISSUE TITLE
Some links had gone

### ISSUE THREAD

**Issue by maronghe** [gofiber/fiber#1253]
Some links had gone
--
For README.md of [the summary page](https://github.com/gofiber/fiber#-internal-middleware) , 
Recover middleware recovers from panics anywhere in the stack chain and handles the control to the centralized ErrorHandler.

The `ErrorHandler` 's link was gone, please change it to `https://github.com/gofiber/fiber/blob/master/middleware/recover/README.md`. 
Could you fix it when you have free time. 
And check other links. 
Then it may be useful for every customers.

**Comment by sagar23sj** [comment]
If anyone is not working on this, can I fix this issue?

**Comment by ReneWerner87** [comment]
> If anyone is not working on this, can I fix this issue?

would be cool

**Comment by sagar23sj** [comment]
Just wanted to confirm one more thing @ReneWerner87 
We want ErrorStruct hyper-link to redirect to **https://docs.gofiber.io/guide/error-handling** or **https://github.com/gofiber/fiber/blob/master/middleware/recover/README.md**.
Thanks

**Comment by ReneWerner87** [comment]
you mean 
![image](https://user-images.githubusercontent.com/7063188/113262970-827d4500-92d1-11eb-9cd7-7e20fe3d6958.png)
![image](https://user-images.githubusercontent.com/7063188/113262995-890bbc80-92d1-11eb-985a-95e087736da4.png)

this link is working on my machine

**Comment by sagar23sj** [comment]
> you mean
> ![image](https://user-images.githubusercontent.com/7063188/113262970-827d4500-92d1-11eb-9cd7-7e20fe3d6958.png)
> ![image](https://user-images.githubusercontent.com/7063188/113262995-890bbc80-92d1-11eb-985a-95e087736da4.png)
> 
> this link is working on my machine

The issue is in READMEs at project root located in /.github.

https://github.com/gofiber/fiber#-internal-middleware,
ErrorHandler mentioned in description for **Middleware** : recover

**Comment by sagar23sj** [comment]
Actually, in the issue description, 
This Link - > **https://github.com/gofiber/fiber/blob/master/middleware/recover/README.md** 
is suggested as a fix, but I looked around, and it seems like
This Link -> **https://docs.gofiber.io/guide/error-handling**
is the right link for the fix.

So just wanted to confirm with you first @ReneWerner87 .
Thanks

**Comment by ReneWerner87** [comment]
yes i think that is correct, in the markdown of the github the links of the github should be deposited, because this information can also change in the branches

about the background process for the docs i don't know unfortunately

**Comment by sagar23sj** [comment]
#1256
