### ISSUE TITLE
🤔 Is there any way for handling JSON error?

### ISSUE THREAD

**Issue by 1995parham** [gofiber/fiber#126]
**Question description**
I have used `gofiber` for creating a REST API with JSON. The `JSON` function returns error so I must handle it every time in responses. Is there any better way of doing this?

**Code snippet (optional)**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  app.Get("/json", func (c *fiber.Ctx) {
    if err := c.Status(200).JSON("Hello World"); err != nil {
      panic(err)
    }
  })
}
```

**Comment by koddr** [comment]
@1995parham thx for issue.

We're working around easy way to error handling right now on Fiber. Stay tuned! 😉

**Comment by 1995parham** [comment]
@koddr Thanks for your response 🙌 I will wait.

**Comment by Fenny** [comment]
@1995parham, thanks for submitting your issue.
`JSON` sets the body to `""` and `Content-Type: application/json` by default.
The status code is always 200 by default unless you set it. ( less code :) )
```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  app.Get("/json", func (c *fiber.Ctx) {
    // When working with strings, nothing could go wrong
    // You are not required to check for errors, specially when no structs are serialized
    c.JSON("Hello World");
    // When you work with structs, its a good behavior to check for errors
    // If the JSON serialization goes wrong, it just sets the body to ""
    // For now you can check for errors to display a custom message
    if err := c.JSON(&user); err != nil {
      c.Status(500).JSON("Something went wrong")
    }
  })
}
```
We are working on a better way to handle global errors.

**Comment by 1995parham** [comment]
@Fenny I agree with your solution, we can return an error from the handler. If you want, I can create a PR for it.

**Comment by Fenny** [comment]
@1995parham, PR's are always welcome :+1:
I have time to work in the afternoon :+1:

**Comment by 1995parham** [comment]
I will create PR so we can work on it 🙌

**Comment by Fenny** [comment]
@1995parham, me and @koddr are actually discussing some kind of `recover` feature.
This has nothing to do with the `c.Next(err)`, but we would like to hear your thoughts on this.

```go
package main

import (
	"./fiber"
)

func main() {
  app := fiber.New()
  
  app.Get("/", func(c *fiber.Ctx) {
    panic("I panic")
  })
  
  // app.Recover, app.Error... ?
  app.Panic(func(c *fiber.Ctx) {
    fmt.Println(c.Error()) 	// => "I panic"
    c.SendStatus(500) 	// => 500 "Internal Server Error"
  })
  
  app.Listen(3000)
}
```go

**Comment by 1995parham** [comment]
@Fenny I think to recover from panic in handlers is an excellent feature, and it would be useful in long-running applications. The proposed syntax is simple and useful.

**Comment by Fenny** [comment]
@1995parham 'v1.5.0' is released, docs coming soon.

**Comment by 1995parham** [comment]
@Fenny, sorry for bothering you again. I have checked the new API, and it was good. But is there any way to return an error from the handler, and it automatically passed to the `Next` method? Like handlers of [echo](https://github.com/labstack/echo).
