### ISSUE TITLE
🚀 Add `app.Serve` function which takes net.Listener parameter

### ISSUE THREAD

**Issue by bofeng** [gofiber/fiber#1261]
**Is your feature request related to a problem?**

I was trying to use fiber with [overseer](https://github.com/jpillora/overseer) to support graceful restart. My code is like this:

```go
func prog(state overseer.State) {
    app := fiber.New()
    // I need to pass state.Listener to app like this:
    // but currently this is no such API exposed
    app.Serve(state.Listener)
}

func main() {
	overseer.Run(overseer.Config{
		Program: prog,
		Address: ":3000",
	})
}
```

But currently there is no API for fiber app to take a listener directly.

**Describe the solution you'd like**

The case for `Prefork=true` may need to be handled separately, but the bare bone of the `Serve` function is like this:

```go
func (app *App) Serve(ln net.Listener) error {
    app.startupProcess()
    return app.server.Serve(ln)
}
```

**Alternative solution**

An alternative way might be expose `startupProcess` to `StartupProcess`, such that at least for my case, I could use:
```
app.StartupProcess()
app.Server().Serve(state.Listener)
```
But not sure if this is a good idea, seems just expose `Serve` looks cleaner

**Comment by kiyonlin** [comment]
Hey, we do have [Listener](https://docs.gofiber.io/api/app#listener)
```go
func (app *App) Listener(ln net.Listener) error
```

**Comment by bofeng** [comment]
> Hey, we do have [Listener](https://docs.gofiber.io/api/app#listener)
> 
> ```go
> func (app *App) Listener(ln net.Listener) error
> ```

It works perfectly, thank you 👍
