### ISSUE TITLE
Using colon as normal character instead of route param 🚀 

### ISSUE THREAD

**Issue by mlukasik-dev** [gofiber/fiber#1262]
### Problem
We can't create routes that follow _custom http methods_ convention (more about this at [Google API Design Guide](https://cloud.google.com/apis/design/custom_methods)):
- `/updates:watch`
- `/users/:id:undelete` (`/users/132:undelete`)
- `/events:clear`
All of this route paths don't work as desired.

### Possible solutions
1. `/users/:id\\:undelete` - escaping colon.
2. `/users/:id::undelete` - double colon.
3. Looking forward to seeing your solutions :)

**Comment by ReneWerner87** [comment]
Thanks for the report, I will create the week a pull request for the variant with the escaping

**Comment by ReneWerner87** [comment]
fixed with https://github.com/gofiber/fiber/pull/1280/files
