### ISSUE TITLE
🐛 405 error on DELETE request:

### ISSUE THREAD

**Issue by subzero911** [gofiber/fiber#1264]
**Fiber version 2.7.1**
Trying to create a simple API, got 405 error on DELETE request:
![image](https://user-images.githubusercontent.com/12999702/113521509-901d1e00-95a2-11eb-9748-0980ef3b286d.png)
![image](https://user-images.githubusercontent.com/12999702/113521465-46ccce80-95a2-11eb-8697-9a7ef64a3114.png)
How to fix it? Seems like DELETE method not allowed, and it is an issue with Fiber server configuration.

**Code snippet**

```go
func DeleteBook(c *fiber.Ctx) error {
	id := c.Params("id")
	db := database.DBConn
	var book Book
	db.First(&book, id)
	if book.Title == "" {
		return c.Status(500).SendString("No book find with a given ID")
	}
	db.Delete(&book)
	return c.SendString("Book " + id + " deleted")
}
```

**Comment by ReneWerner87** [comment]
Thanks for the report 

Can you send me an excerpt about the registration of the route

**Comment by subzero911** [comment]
![image](https://user-images.githubusercontent.com/12999702/113549705-87583680-95fa-11eb-8764-27ff520ee5cb.png)

**Comment by ReneWerner87** [comment]
exactly, take a look at your request route and the registered one, there is a difference here
POSTMAN:
/api/v1/book?id=3   --> query param

Registered delete route:
/api/v1/book/:id

-> use
/api/v1/book/3 
in postman

query parameter and resource parameter are not the same, a 405 is correct, no DELETE method was specified for your route given in postman

**Comment by kiyonlin** [comment]
Actually you should do `DELETE http://localhost:3000/api/v1/book/3` according to your given router.
