### ISSUE TITLE
🚀 Monitor Middleware - Remove fmt.Println?

### ISSUE THREAD

**Issue by yk-sgr** [gofiber/fiber#1266]
**Is your feature request related to a problem?**
The monitor middleware prints a warning that the API might be changed in the future.

**Describe the solution you'd like**
 I think this should be moved to the README but not in the code/log.

https://github.com/gofiber/fiber/blob/25868a9be7ce1e21c0319de07071ae11005cfaf0/middleware/monitor/monitor.go#L55

**Comment by hi019** [comment]
I agree, would you like to make a PR?

**Comment by hi019** [comment]
I agree. Would you like to make a PR?

**Comment by sagar23sj** [comment]
If anyone is not working on this issue, I would like to take this up.

**Comment by sagar23sj** [comment]
Along with removing the print statement from the code, is it required to add the warning in the readme file.
**"[Warning] monitor is still in beta, API might change in the future!"**
https://github.com/gofiber/fiber/tree/master/middleware/monitor#readme

**Comment by ReneWerner87** [comment]
looks good, do it in this way

**Comment by sagar23sj** [comment]
> looks good, do it in this way

Sure. Thanks for confirmation @ReneWerner87 .

**Comment by yk-sgr** [comment]
Thanks!
