### ISSUE TITLE
🐛BodyParser allows non specified parameters to pass through 

### ISSUE THREAD

**Issue by wambugucoder** [gofiber/fiber#1267]
**Fiber version**
**_2.0_**

**Issue description**
When i add another json parameter in postman ,the request is sent successfully instead of indicating an error that there is an invalid parameter

### Example:  
For my login which only requires email and password ,i tried adding username to see what happens and to my surprise it went through without any error
```
{
   "username":"gfgfffa",
    "email":"josgfhythgf@gmail.com",
    "password":"123456"

}
```

**Code snippet**

```go
type LoginInputs struct {
	Email    string `json:"email"    validate:"required,email"`
	Password string `json:"password" validate:"required,min=6,max=32"`
}
func LoginUser(ctx *fiber.Ctx) error {
	logindetails := new(LoginInputs)

	err := ctx.BodyParser(logindetails)
	if err != nil {
		return ctx.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"error": err.Error(),
		})
	}
```

**Comment by si3nloong** [comment]
@wambugucoder i don't see any issue, this is the expected behaviour
