### ISSUE TITLE
Client Section on gofiber.io 🐛 

### ISSUE THREAD

**Issue by JeffPHP** [gofiber/fiber#1270]
Hello,

There was a client section in GoFiber's documentation but it seems to have been removed. Is it on purpose?

Best regards,
Jeff

<img width="1393" alt="Capture d’écran 2021-04-08 à 12 19 25" src="https://user-images.githubusercontent.com/6480906/114010955-f9cc4f00-9864-11eb-959d-27beb2d2bc61.png">

**Comment by ReneWerner87** [comment]
you are right, we will fix it today, thx for the report

**Comment by JeffPHP** [comment]
In the meantime, here is a cached version of the page: 
https://webcache.googleusercontent.com/search?q=cache:tqgBSqAtAl0J:https://docs.gofiber.io/api/client+&cd=1&hl=fr&ct=clnk&gl=fr

**Comment by ReneWerner87** [comment]
we fixed it, really thanks for the report

there was a problem with the master
