### ISSUE TITLE
🚀  When to add Swagger?

### ISSUE THREAD

**Issue by helloshaohua** [gofiber/fiber#1273]

**Comment by koddr** [comment]
Hi,

Fiber has its own Swagger middleware: [arsmn/fiber-swagger](https://github.com/arsmn/fiber-swagger).

Also, if you want to see Swagger in action, [this tutorial](https://dev.to/koddr/build-a-restful-api-on-go-fiber-postgresql-jwt-and-swagger-docs-in-isolated-docker-containers-475j) can help you.
