### ISSUE TITLE
Is there a reason why colors are disabled outside the default config ? 🤗 

### ISSUE THREAD

**Issue by nicolasvac** [gofiber/fiber#1281]
**Question description**

Hi everyone. As the question says, "enableColors" is actually private. 
By adding the colors such as ${red}, they dont get displayed correctly.

I'm using pwsl.exe 7.1 inside GoLand, which i'm sure supports colors because by using the default config, colors do work fine.

Is there a reason of why we can't use colors outside of default config ?
Thanks.

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

 app.Use(logger.New(logger.Config{
		TimeZone: "Europe/Rome",
		Format:   "${red} [${time}] Process: ${pid} | Request: ${locals:requestid} | ${ip} | Status: ${status} | Time: ${latency} | Method: ${method} | Path: ${path}\n",
	}))
}
```

Result: 
![Immagine 2021-04-12 211810](https://user-images.githubusercontent.com/45635090/114449080-a5163480-9bd4-11eb-8ae5-1bd108f9c5f4.png)

**Comment by Fenny** [comment]
Did you test this in any other CMD? @nicolasvac

**Comment by nicolasvac** [comment]
Hello @Fenny , apparently this works in other terminals like "Windows Terminal". 
But for example in powershell, like the example i posted up, it does not. 

Is this bug related to fiber, or to go in general ?

**Comment by efectn** [comment]
Can you try to run your app with latest versions of Fiber? I tried to run with pwsh on linux and worked.

**Comment by efectn** [comment]
@nicolasvac

**Comment by ReneWerner87** [comment]
@nicolasvac

**Comment by nicolasvac** [comment]
Hello everyone, it was a problem of goland terminal. 

Sorry for the late answer,
and thank you.
