### ISSUE TITLE
How to get Request body in Fiber framework🤗 

### ISSUE THREAD

**Issue by abhicoder29** [gofiber/fiber#1283]
How to get Request body in Fiber framework
I am tying to write me backend code using go fabric however I have basic question how to get Request body so I can do some backend logic using request body.
**my Controller  code ** 

```go
func CreateFarm(c *fiber.Ctx) error {
	farmCollection := config.MI.DB.Collection(os.Getenv("FARM_COLLECTION"))
    
	data := new(models.Farms)
    log.Println("dasta", data)
	err := c.BodyParser(&data) <---------
	// if error
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"success": false,
			"message": "Cannot parse JSON",
			"error":   err,
		})
	}

	result, err := farmCollection.InsertOne(c.Context(), data)

	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"success": false,
			"message": "Cannot insert todo",
			"error":   err,
		})
	}

	// get the inserted data
	farm := &models.Farms{}
	query := bson.D{{Key: "_id", Value: result.InsertedID}}

	farmCollection.FindOne(c.Context(), query).Decode(farm)

	return c.Status(fiber.StatusCreated).JSON(fiber.Map{
		"success": true,
		"message": "Farm Update successfully",

	})
}



```

**Comment by ReneWerner87** [comment]
Hi, exactly as your code describes it works, the important thing is that you have the annotations attached to your struct, which can then be used by the gorilla schema parser to write the values of the body into the properties of the structs.
f.e.:
![image](https://user-images.githubusercontent.com/7063188/114518106-4d60e300-9c3f-11eb-97ec-8ba982df069f.png)


there are of course also other possibilities, just have a look at our documentation 
https://docs.gofiber.io/api/ctx#formvalue
https://docs.gofiber.io/api/ctx#body
https://docs.gofiber.io/api/ctx#bodyparser

**Comment by abhicoder29** [comment]
Hi @ReneWerner87 I have tried as mention in [bodyparser ](https://docs.gofiber.io/api/ctx#body), however when I am running I am getting nothing. please check screen shot

**Comment by ReneWerner87** [comment]
and the content type is important, which one is it ?

**Comment by christianmellor** [comment]
Does it matter that they are passing in a pointer to a pointer?

```go
data := new(model)
c.BodyParser(&data)
// rather than
c.BodyParser(data)
```

https://stackoverflow.com/questions/67070583/how-to-get-request-body-in-go-fiber-framework?noredirect=1#comment118553598_67070583

**Comment by abhicoder29** [comment]
Hi @ReneWerner87 and @christianmellor thanks both of you  its help me to find issue as @ReneWerner87 mentioned worked for me

**Comment by ReneWerner87** [comment]
@abhicoder29 could you add this article or the solution to the stackoverflow article think this would help the other users

**Comment by abhicoder29** [comment]
added
