### ISSUE TITLE
🚀 ETag Middleware

### ISSUE THREAD

**Issue by fernandobandeira** [gofiber/fiber#1284]
**Is your feature request related to a problem?**
Currently, there's no way to set a custom Etag header on a response, the middleware just ignores it and overrides with it's own hash.

**Why is this even a problem?**
Etags can be used for more things than just saving response bandwidth to your CDN, for example,

Assuming that you have an endpoint that returns a list of products ordered by the creation date, if this list is returning, let's say, 10k products (it's just an example), you could use the id field of the most recent product in this list as the Etag.

When the CDN sends the next request you can pick this Etag up and query in the DB to check if the most recent item has the same id, instead of querying and returning 10k products, the DB would just return 1 product, you can then check if it matches with the Etag and then return the response as Not modified without even querying the DB with the expensive query, saving up a lot of computing resources in the process.

**Describe the solution you'd like**
I think that the only thing that we have to do is to check if the response has an Etag header set and forward it to the client, we could also optionally use it to check if we should send the Not modified status, although I believe that this would already be set by the developer on the handler in this use case.

**Describe alternatives you've considered**
Currently, you can bypass the middleware if you don't have a response body or if the status is different than OK but in this case, the uncached response would have an OK status with a body, skipping the custom header that we set.

Cloning the middleware and patching it myself is always an option but this behavior would fit nicely with the framework by default so I think we could change it.

**Additional context**
If this is an interesting thing we could add this as a tip in the docs as well so people are aware of this and can use on their apps.

https://medium.com/build-succeeded/how-to-properly-use-cloudfront-to-cache-an-api-with-cache-control-and-http-304-to-provide-cache-b893f6822475

I can / would make PR's for this in this repo and on the docs but I'm not familiar with the community here yet, but I certainly want to contribute to this amazing project 🤗

**Comment by kiyonlin** [comment]
Sounds interesting. I'm looking forward to your PR 😃
