### ISSUE TITLE
🤗 How to redirect from http to https when a user visits the site ?

### ISSUE THREAD

**Issue by BlackGopher2030** [gofiber/fiber#1286]
Hi, in my web app, is want the user to be redirected automatically from http to https when he visits the site.

I have a lets encrypt certificate stored in the server and when i start listening i do this:

```
log.Fatal(app.ListenTLS(<server ip address>:443,
"/etc/letsencrypt/live/<my site domain>/fullchain.pem",
"/etc/letsencrypt/live/<my site domain>/privkey.pem")) 
```

This works good, but i have to type `https://<my site domain>.com` whenever i visit the site. If i enter `<my site domain>.com` only it does not work and the server cannot be found.

Any ideas how can i solve this problem ?

**Comment by tianjipeng** [comment]
Maybe you can try two app:
```go
// http
	app := fiber.New()
	app.Use("/", func(ctx *fiber.Ctx) error {
                 // redirect to https
		return ctx.Redirect("https://localhost:3001"+ctx.OriginalURL())
	})

	go func() {
		log.Fatal(app.Listen(":3000"))
	}()

	// https
	app2 := fiber.New()
	app2.Get("/hello", func(ctx *fiber.Ctx) error {
		return ctx.SendString("hello world")
	})
	
	log.Fatal(app2.ListenTLS(":3001", "xx", "xxx"))
```

**Comment by BlackGopher2030** [comment]
Yea that worked fine, thank you
