### ISSUE TITLE
🤗 Path problem in web app

### ISSUE THREAD

**Issue by BlackGopher2030** [gofiber/fiber#1287]
HI, when i try to serve assets (css, js, images etc) by doing this in the routes `app.Static("/", "./assets")` it works fine in the local environment cuz i specify the module in go.mod file, like this `module app`.

However when i compile the app to binary and push it to production server i have to specify the full absolute path for every folder i want to include. for example:

`app.Static("/", "/root/<project name>/app/assets")`

or when loading templates

`var Engine = html.New("/root/<project name>/app/templates", ".html")`

or when making database connection

`db, err := gorm.Open(sqlite.Open("/root/<project name>/app/<project name>.sql"), &gorm.Config{})`

Is the a way to automatically specify the absolute path and attach it to the path string ?

**Comment by tianjipeng** [comment]
@BlackGopher2030 Could you provide  mininal reproducible code or step? I use code like this and  move binary and assets directory  to other place, and it works fine.
```go
func main()  {
	app := fiber.New()

	app.Static("/", "./assets")

	log.Fatal(app.Listen(":3000"))
}
```

**Comment by BlackGopher2030** [comment]
Notice that the production server has linux OS, Yes to works fine when you try to execute the binary from the app folder like this `./main` but in production server when i have to setup a systemd file like this:

```
[Unit]
Description=Ahalyna web app
After=multi-user.target

[Service]
User=root
Group=root
ExecStart=/root/<app name>/app/main

[Install]
WantedBy=multi-user.target

```

and i place it in `/etc/systemd/system/<app name>.service`

so that if the server reboots the process starts automatically.

Then you can check the service status using `systemctl status ahalyna.service`

In the `/etc/systemd/system/<app name>.service` file, i specified the `ExecStart=/root/<app name>/app/main` to absolute path as you see.

**Comment by tianjipeng** [comment]
Maybe you can add flag to specify assets directory:
```go
func main()  {
	var assetsDir string
	flag.StringVar(&assetsDir, "s", "", "assets directory path")
	flag.Parse()

	app := fiber.New()
	app.Static("/", assetsDir)

	log.Fatal(app.Listen(":3000"))
}
```
Then your program can run as :
```shell
/root/<app name>/app/main -s /root/<app name>/app/assets
```

**Comment by BlackGopher2030** [comment]
what is did is specifying the absolute path string in a config package  and then using it throughout the entire app, i think this is more clear.

**Comment by ReneWerner87** [comment]
do you need more information ? otherwise you can close the issue
