### ISSUE TITLE
🐛 JSON Marshal different of golang encoding/json

### ISSUE THREAD

**Issue by t0jc** [gofiber/fiber#1289]
Fiber version:
:x: = different,  :white_check_mark: = same
v2.7.1 :x:
v2.5.0 :white_check_mark:
v2.3.3 :x:
Issue description: JSON Marshal different of golang encoding/json

Code snippet

```
type testaaa struct {
    AA string `json:"aa,omitempty"`
    BB string `json:"bb,omitempty"`
    *Testcc
}
type Testcc struct {
    CC string `json:"cc,omitempty"`
    DD string `json:"dd,omitempty"`
}

var t = &testaaa{
    AA: "AAAAAA",
    Testcc: &Testcc{
        CC: "CCCCCC",
        DD: "DDDDDD",
    },
}

func test4(c *fiber.Ctx) error {
    c.Set(fiber.HeaderCacheControl, "no-store, max-age=0")
    b, _ := json.Marshal(t)
    return c.Type("json", "utf-8").Send(b)

    // {
    //     "aa": "AAAAAA",
    //     "cc": "CCCCCC",
    //     "dd": "DDDDDD"
    // }
}

func test3(c *fiber.Ctx) error {
    c.Set(fiber.HeaderCacheControl, "no-store, max-age=0")
    return c.JSON(t)
    // {
    //     "aa": "AAAAAA"
    // }
```

**Comment by Stitch-Zhang** [comment]
I assume it may be cause by #1211 Actually I tried to cancel this change in local with version(2.7.1) and then it works

**Comment by chenkaiC4** [comment]
@Stitch-Zhang hi, you can set `app.config.JSONEncoder` to what you want to ignore the default. thus not need to broken the main source code and watting this bug fix.

https://github.com/gofiber/fiber/blob/a95e371920a9711155e804808e53dbe3a9fdee9f/app.go#L402

**Comment by hi019** [comment]
We don't use encoding/json anymore as you can see in #1211. We now use https://github.com/segmenti/encoding so I'm thinking this is an issue with that package. We'll need to run your test with their encoder to narrow down the problem. 

For now you can use @chenkaiC4's solution which sets the internal JSON encoder to the standard Golang one.

**Comment by t0jc** [comment]
> We don't use encoding/json anymore as you can see in #1211. We now use https://github.com/segmenti/encoding so I'm thinking this is an issue with that package. We'll need to run your test with their encoder to narrow down the problem.
> 
> For now you can use @chenkaiC4's solution which sets the internal JSON encoder to the standard Golang one.

I test this package is same, 
so I change the JSONEncoder :)

```
import (
jsona "github.com/segmentio/encoding/json"
)
func test3(c *fiber.Ctx) error {
	c.Set(fiber.HeaderCacheControl, "no-store, max-age=0")
	b, _ := jsona.Marshal(t)
	return c.Type("json", "utf-8").Send(b)
	// {
	// 	"aa": "AAAAAA"
	// }
}

```

**Comment by Stitch-Zhang** [comment]
> @Stitch-Zhang hi, you can set `app.config.JSONEncoder` to what you want to ignore the default. So you don't need to modify the source code which will cause broken to the origin Fiber and just watting this bug to be fix by next release.
> 
> https://github.com/gofiber/fiber/blob/a95e371920a9711155e804808e53dbe3a9fdee9f/app.go#L402
> 
> [jsoniter](https://github.com/json-iterator/go) is a good candidate.

ok,that's greate👍

**Comment by Fenny** [comment]
Like @hi019 mentioned in https://github.com/gofiber/fiber/issues/1289#issuecomment-826412802, we are using https://github.com/segmenti/encoding internally as default JSON encoder/decoder. You might want to open an issue on their page regarding the compatibility with the default json package.

```go
app.config.JSONEncoder = json.Marshal 
```
Should solve your problem 👍
