### ISSUE TITLE
🚀 logger middleware with structured logger

### ISSUE THREAD

**Issue by bpatyi** [gofiber/fiber#1293]
new possibility to set structured logger to the middleware like in chi: https://github.com/go-chi/chi/blob/master/middleware/logger.go
example how to set custom structured logger: https://github.com/go-chi/chi/blob/master/_examples/logging/main.go

with this feature we can use logrus or zap for the request logging which can be awesome

**Comment by kiyonlin** [comment]
Maybe have a look [here](https://github.com/gofiber/fiber/issues/683#issuecomment-665446450)

**Comment by bpatyi** [comment]
Thanks for the link @kiyonlin, but i think the structured logger is more complex like a simple json output. (more outputs, hooks, extra fields, log level, etc.) [zap](https://github.com/uber-go/zap) or [logrus](https://github.com/Sirupsen/logrus) are good examples.

With this feature request my aim is to be able to use one structured logger in the project, what we define at the begining of the running and we can give over this for the middleware.

I imagine it like:
```go
package main

import (
    "github.com/gofiber/fiber/v2"
    "github.com/gofiber/fiber/v2/middleware/logger"

    "github.com/uber-go/zap"
    "github.com/uber-go/zap/zapcore"
    "github.com/natefinch/lumberjack"
)

var sugaredLogger *zap.SugaredLogger


func main() {
    fileLogger := &lumberjack.Logger(
        Filename: "/var/log/example.log",
        MaxSize: 10,
        MaxBackups: 5,
        MaxAge: 30,
        Compress: true,
    )
    fileSyncer := zapcore.AddSync(fileLogger)
 
    loggerEncoderConfig := zap.NewProductionEncoderConfig()
    loggerEncoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder
    loggerEncoderConfig.EncodeLevel = zapcore.CapitalLevelEncoder
    loggerEncoder := zapcore.NewConsoleEncoder(loggerEncoderConfig)

    core := zapcore.NewCore(loggerEncoder, fileSyncer, zapcore.DebugLevel)
    logger := zap.New(core)
    defer logger.Sync()

    sugaredLogger = logger.Sugar()

    app := fiber.New()
    app.Use(logger.WithLogger(sugaredLogger))


    app.Listen(":3000")
}

```

Maybe the example of [chi](https://github.com/go-chi/chi/blob/master/_examples/logging/main.go) is more expressive. :)


What do you think how could we incorporate this into the structure of the fiber's middleware? What do you think about this feature? Would it involve a lot of makeovers? (@kiyonlin , @hi019 , @ReneWerner87)

**Comment by kiyonlin** [comment]
> but i think the structured logger is more complex like a simple json output. (more outputs, hooks, extra fields, log level, etc.) zap or logrus are good examples.

Fiber logger is mainly based on template, not interface. It's just a simple build-in/out of box logger middleware/plugin as `nginx` logger does. 

> With this feature request my aim is to be able to use one structured logger in the project, what we define at the beginning of the running and we can give over this for the middleware.

If our logger doesn't meet your needs, I think the best way is that you can make your own logger middleware because it's not hard. And the chi example almost rewrite everything.

Thank you for your suggestions anyway. But we may take this in consideration in v3 😄
