### ISSUE TITLE
🐛 date race when use goroutine 

### ISSUE THREAD

**Issue by hofarah** [gofiber/fiber#1294]
**Fiber version**
v2.1.4

**Code snippet**

```go
package example

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
)

func ExampleHandler(ctx *fiber.Ctx) error {
	var ip = ctx.Get("real-ip")
	go func(ip string) {
		fmt.Println(ip)
	}(ip)
//some code
return ctx.Send(bytes)
}
```
Hi,
**This happens when the number of requests is high**

I didn't set any config and create 5 different handler.
I found out that when i send variable to go function as argument (in handler),when variable is going to use in goroutine , part of the content of the variable changes (not always).

for example if ip was "1.2.3.4" then ip in goroutine is "64.2.3.4"
when number of requests is low its work successfully, but when use in server its work bad

**Comment by ReneWerner87** [comment]
fiber is based on fasthttp and uses the mechanisms of zero memory allocation, i.e. objects are used that come from a pool and after the process they are packed back into the pool for reuse

your go routine breaks out of the process and in this it is not clear if the context is used for another process or not, so it comes to unexpected changes of the value or race conditions

you should make a copy of the values when you break out of the request <-> response process which you can then use in the go routines

**Comment by ReneWerner87** [comment]
normally strings are immutable, but we use a trick here, so that the strings are also concatenated

you can turn this off in the configuration for the whole app if you want, but this will cause the app to slow down

would suggest you just copy the ip with the function provided in the utils and then put this copy into the go routine

**Comment by ReneWerner87** [comment]
@hofarah

**Comment by hofarah** [comment]
Thank you for your answer

**Comment by hofarah** [comment]
i used   ```var ip = string(ctx.Request().Header.Peek("real-ip"))```
and work successfully .
because string() copy new string and we have no reference to ctx.
