### ISSUE TITLE
🚀 Adding MIME types for Static Files (Downloading APK on Android issue)

### ISSUE THREAD

**Issue by moneszarrugh** [gofiber/fiber#1295]
My feature request is regarding serving static files.

https://docs.gofiber.io/#static-files

There is an issue when I'm serving `.apk` files and downloading them from Chrome mobile browser on Android. They download as `.apk.zip` and not just `.apk`.

Apparently, the issue is related to MIME types. Refer to https://serverfault.com/questions/501562/configure-iis-7-0-to-download-apk/501564

If you allow setting custom MIME type it would be very useful. Thanks

**Comment by ReneWerner87** [comment]
thank you for the report

> If you allow setting custom MIME type it would be very useful. Thanks
we allow another way, you can use a middleware after the static route to set this mimi type


since we use fasthttp internally, the bug should be there, can you open a bug there too ?

**Comment by moneszarrugh** [comment]
> since we use fasthttp internally, the bug should be there, can you open a bug there too ?

https://github.com/valyala/fasthttp/issues/1011

**Comment by moneszarrugh** [comment]
> we allow another way, you can use a middleware after the static route to set this mimi type

I would appreciate it if you could provide an example code snippit.

**Comment by ReneWerner87** [comment]
@moneszarrugh 
```go
package main

import (
    "log"

    "github.com/gofiber/fiber/v2"
)

func main() {
    app := fiber.New()

    app.All("/download/*.apk", func(ctx *fiber.Ctx) error {
        ctx.Set(fiber.HeaderContentType, "application/your-type")
        return ctx.Next()
    })
    app.Static("/download", "./static")

    log.Fatalln(app.Listen(":3000"))
}

```
![image](https://user-images.githubusercontent.com/7063188/115985695-4d50d380-a5ad-11eb-9215-c48be65d14e4.png)
![image](https://user-images.githubusercontent.com/7063188/115985707-5641a500-a5ad-11eb-9f50-018d5220730f.png)
![image](https://user-images.githubusercontent.com/7063188/115985720-65c0ee00-a5ad-11eb-9d92-fa6e52636142.png)

is this example enough for you ? otherwise you could close the issue

**Comment by moneszarrugh** [comment]
@ReneWerner87 

This example is excellent, thank you very much.
