### ISSUE TITLE
How to get req * http.Request, for use with appengine 

### ISSUE THREAD

**Issue by AngelCareaga** [gofiber/fiber#1296]
**I'm trying to upload an image, but I can't get the * http.Request to pass it to the appengine and create a Writter.

Any alternative or solution to this?**

**Code snippet**

```go

func HandleFileUploadToBucket(ctx *fiber.Ctx) (string, error) {
...

ctxEngine := appengine.NewContext(ctx.Request()) // Cannot use 'ctx.Request()' (type *"github.com/valyala/fasthttp".Request) as the type *"net/http".Request
	
storageClient, err = storage.NewClient(ctxEngine, option.WithCredentialsFile(configs.GOOGLE_APPLICATION_CREDENTIALS))
	if err != nil {
		...
	}
```

```
github.com/gofiber/fiber/v2 v2.8.0
google.golang.org/appengine v1.6.7
```

**Comment by hi019** [comment]
Check out https://github.com/gofiber/adaptor to convert to net/http. Personally I don't recommend it for production and it comes with performance penalty. 

What about putting the program in a Docker container and then deploying that with App Engine? [This](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/quickstart) may help
