### ISSUE TITLE
Where is Automatic OpenAPI docs page like fastapi for python🚀 

### ISSUE THREAD

**Issue by encryptblockr** [gofiber/fiber#1297]
Is there or will there be an automatic openapi generation like fastapi for python?
if not then WHY?!?

**Comment by hi019** [comment]
There are currently no official middlewares for Swagger. See https://github.com/gofiber/fiber/issues/276

**Comment by deranjer** [comment]
As far as I know, there also aren't any THIRD party middlewares for openapi, all the ones I've seen are for swagger 2.0.
