### ISSUE TITLE
c.Body() can't read raw data

### ISSUE THREAD

**Issue by Aguezz** [gofiber/fiber#130]
I don't get data from c.Body ("email") when I request via postman with Raw Body

**Raw Data**
```json
{
  "email": "myemail@email.com"
}
```

**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  app.Post("/login", func (c *fiber.Ctx) {
    c.Body("email") // no value here
  })

  app.Listen(8080)
}
```

**Comment by MarvinJWendt** [comment]
Hi, you have created an empty issue<sup>1</sup> in the bug-tracker of this repository<sup>2</sup>. 

The `Issue` tab of repositories on [GitHub](https://github.com) is meant to report problems with the repository or to discuss features of the project. If you have an actual issue with the repository, please [open a new issue](../issues/new) with a decent description.

Have fun exploring this repository 🎉 

<sub>If you want to know more about how to write good issues, look here: https://guides.github.com/features/issues/</sub>

---

<sup>1: Issue ⇾ Bug Report / Feature Request / etc..</sup>
<sup>2: Repository ⇾ Project</sup>

**Comment by MarvinJWendt** [comment]
Hi @Aguezz,
If you format your data in this way: `key=value`, it works :)

![image](https://user-images.githubusercontent.com/31022056/74345632-aa98a480-4dae-11ea-8995-4499c3f10a25.png)

**Comment by Aguezz** [comment]
@MarvinJWendt 
Thank you... That works 🥳
