### ISSUE TITLE
🚀 Trusted Reverse Proxy and get c.Hostname() value from X-Forwarded-Host and etc

### ISSUE THREAD

**Issue by 4n70w4** [gofiber/fiber#1300]
**Is your feature request related to a problem?**

Hi!

I tried to find something similar for gofiber on github and google, but the search did not return any results.

I use reverse proxies like nginx and Traefik. It's uses headers `X-Forwarded-Host`, `X-Forwarded-Proto` and `X-Forwarded-For` for pass hostname, protocol and real client ip of original request.

And Trusted Proxies whitelist for describe ip's of reverse proxies on requests from which it is allowed to take values from these headers.

https://symfony.com/doc/3.2/components/http_foundation/trusting_proxies.html
https://github.com/fideloper/TrustedProxy

Examples:

If request ip in Trusted Proxies whitelist then:
- `c.Protocol()` get value from `X-Forwarded-Proto` header
- `c.IP()` get value from `X-Forwarded-For` header
- `c.Hostname()` get value from `X-Forwarded-Host` header

But if request ip NOT in Trusted Proxies whitelist then:
- `c.Protocol()` DON'T get value from `X-Forwarded-Proto` header
- `c.IP()` DON'T get value from `X-Forwarded-For` header
- `c.Hostname()` DON'T get value from `X-Forwarded-Host` header

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oroshnivskyy** [comment]
Hi! May I work on this issue?
