### ISSUE TITLE
Starting the server in a go routine

### ISSUE THREAD

**Issue by adnan-kamili** [gofiber/fiber#1303]
I want to run the server as a service on Windows, Linux and macOS. For that I am using the services package:

https://pkg.go.dev/github.com/kardianos/service

It requires me to start the server in a go routine.

**Code snippet** 

```go
func startServer() {
	logger.LogInfo("Starting server...", "")
	app = fiber.New(fiber.Config{
		DisableStartupMessage: true,
	})
	setupRoutes(app)
	logger.LogInfo("Listening on port:", port)
	error := app.Listen(":" + port)
	if error != nil {
		logger.LogError("The port is already in use!", "")
		os.Exit(1)
	}
}
```

Now the above function is usually called from the main function, but when running as an OS service it has to be called as a go routine:

```go
func (p *program) Start(s service.Service) error {
	// Start should not block. Do the actual work async.
	go p.run()
	return nil
}
func (p *program) run() {
	if app == nil {
		startServer()
	}
}
func (p *program) Stop(s service.Service) error {
	// Stop should not block. Return with a few seconds.
	if app != nil {
		app.Shutdown()
	}
	return nil
}
```
Now this works, but is there any issue it can cause which I need to be aware of or any performance impact it may have?

**Comment by kiyonlin** [comment]
> Now this works, but is there any issue it can cause which I need to be aware of or any performance impact it may have?

I think your approach is fine.
