### ISSUE TITLE
🚀 Default value from QueryParser

### ISSUE THREAD

**Issue by fsanano** [gofiber/fiber#1306]
Does it possible to use the `default` tag in the struct to pass default value of query parameter?

```
type Request struct {
	Limit int `query:"limit" default:"10"`
}
var request Request
ctx.QueryParser(&request);
limit := request.Limit // 10

```

**Comment by hi019** [comment]
No, this is not built in to Fiber. Try this https://github.com/mcuadros/go-defaults

**Comment by gopkg-dev** [comment]
I think this feature is necessary to add. Can it be considered?
