### ISSUE TITLE
VS Code show error warning when using the "Ctx.Status" example from docs🐛 

### ISSUE THREAD

**Issue by whoiscarlo** [gofiber/fiber#1307]
**Fiber version**
Go 1.16
Fiber v2.8.0

**Issue description**
VS Code gives the error when using the example from the docs:
`cannot use "Bad Request" (untyped string constant) as []byte value in argument to c.Status(400).SendcompilerIncompatibleAssign
`

**Code snippet**
```
app.Get("/", func(c *fiber.Ctx) error {
  c.Status(200)
  return nil

  return c.Status(400).Send("Bad Request")
})
```

**Repro**
```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

  // Steps to reproduce

  app.Get("/", func(c *fiber.Ctx) error {
    c.Status(200)
    return nil

    return c.Status(400).Send("Bad Request")
  })

  log.Fatal(app.Listen(":3000"))
}
```

[Link to Documentation](https://docs.gofiber.io/api/ctx#status)

**Comment by ReneWerner87** [comment]
fixed with
https://github.com/gofiber/docs/pull/169
