### ISSUE TITLE
🐛 When Call API Least 1 Time . App Shutdown() not Working

### ISSUE THREAD

**Issue by pagongamedev** [gofiber/fiber#1309]
**Fiber version**
v2 2.8.0

**Issue description**
When Call API Least 1 Time . App Shutdown() not Working

when i use goroutine for run app.Listen(":3000")
and call http://localhost:3000/health
when i ctrl+c for cancel in vs code
it not response

(i check because in gofiber server.go has for loop "open := atomic.LoadInt32(&s.open); open == 0" open is not 0)

but if i call http://localhost:3000/health again (or many time) it's shutdown 
(open is 0 when call again after i ctrl+c)

**Code snippet**

```go
package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	app.Get("/health", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"status": true})
	})
	// ===== Ctrl C for Cancel Goroutine
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)

	done := make(chan bool, 1)
	go func() {
		for sig := range c {
			if sig != nil {
				log.Printf("Close With Ctrl C\n")
				done <- true
			}
		}
	}()

	go func() {
		app.Listen(":3000")
	}()
	<-done

	app.Shutdown()
	log.Println("Shutdown")
}

```

**Comment by kiyonlin** [comment]
Could you try to move this
```go
	go func() {
		app.Listen(":3000")
	}()
```
after routes registrying?

**Comment by kiyonlin** [comment]
Okay, then see [here](https://github.com/gofiber/fiber/issues/1146#issuecomment-771318720).
