### ISSUE TITLE
Fiber sessions not working

### ISSUE THREAD

**Issue by e1engineer** [gofiber/fiber#1312]
Go fiber session variables are returning nil

Can you find flaws in the code, or is this a problem with Fiber (v2.8.0)?

```
package api

import (
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
	"github.com/gofiber/fiber/v2/middleware/proxy"
	"github.com/gofiber/fiber/v2/middleware/session"
)

func Init() {
	app := fiber.New()

	app.Use(logger.New())

	store := session.New()

	app.Post("/xxx/login", func(c *fiber.Ctx) error {
		[...]

		if resp.Status == "200 OK" {
			[...]
                         sess, err := store.Get(c)
			if err != nil {
				log.Println(err.Error())
			}
			sess.Set("Type", "xxx")
			sess.Save()
			return c.SendStatus(200)
		}
		return c.SendStatus(400)
	})

	app.Get("/session/*", func(c *fiber.Ctx) error {
		sess, err := store.Get(c)
		if err != nil {
			log.Println(err.Error())
		}
		
		type2 := fmt.Sprintf("%v", sess.Get("Type"))
		log.Println(type2)
		[...]
	})
}
```

**Comment by hi019** [comment]
Are you sure the if statement is executing? We'll need a reproducible example to help you further

**Comment by e1engineer** [comment]
Thanks.

Just tested for the if statement again, and it is true.

16:39:23 | 200 |   181ms |  xx.xx.xx.xx | POST    | /xxx/login 
2021/05/03 16:39:31 <nil>
16:39:31 | 200 |   144ms |  xx.xx.xx.xx | GET     | /session/xxx

I also just tried getting the session right after it was set within the app.Post("/xxx/login", function, and it's returning nil as well.

I'll test it on a bare fiber installation to see what happens.

**Comment by e1engineer** [comment]
Working on a bare fiber installation... 

Testing a few other things.

**Comment by e1engineer** [comment]
The following code does not work on a bare fiber installation:

`package main

import(
        "log"
        "fmt"

        "github.com/gofiber/fiber/v2"
        "github.com/gofiber/fiber/v2/middleware/session"
)

func main() {

        app := fiber.New()
store := session.New()

        app.Get("/", func(c *fiber.Ctx) error {

    // get session from storage
    sess, err := store.Get(c)
    if err != nil {
        panic(err)
    }

    // save session
    defer sess.Save()

    // Set key/value
    sess.Set("name", "john")

name := sess.Get("name")

    return c.SendString(fmt.Sprintf("Welcome %v", name)) // Returns Welcome john (working)
})

        app.Get("/session/*", func(c *fiber.Ctx) error {
                sess, err := store.Get(c)
                if err != nil {
                        log.Println(err.Error())
                }
                type2 := fmt.Sprintf("%v", sess.Get("type"))
                log.Println(type2) // Returns nil
                // Remove Server header from response
                c.Response().Header.Del(fiber.HeaderServer)
                return nil
        })

log.Fatal(app.Listen(":8081"))
}`

**Comment by e1engineer** [comment]
OK.

Sessions are working in Postman, but not in Vivaldi or Safari. 

Trying to figure this out.

**Comment by e1engineer** [comment]
Here's an example:

```
package main

import(
        "log"
        "fmt"

        "github.com/gofiber/fiber/v2"
        "github.com/gofiber/fiber/v2/middleware/session"
)

func main() {

        app := fiber.New()
store := session.New()

        app.Get("/", func(c *fiber.Ctx) error {

    // get session from storage
    sess, err := store.Get(c)
    if err != nil {
        panic(err)
    }

    // save session
    defer sess.Save()

    // Set key/value
    sess.Set("name", "john")

name := sess.Get("name")

    return c.SendString(fmt.Sprintf("Welcome %v", name))
})

        app.Get("/session/*", func(c *fiber.Ctx) error {
                sess, err := store.Get(c)
                if err != nil {
                        log.Println(err.Error())
                }
                name := fmt.Sprintf("%v", sess.Get("name"))
                log.Println(name)

                return c.SendString(name)
        })

log.Fatal(app.Listen(":8081"))
}
```

**Comment by hi019** [comment]
Are you restarting the app between requests? By default the sessions are stored in memory

**Comment by e1engineer** [comment]
We have a SPA running on domain.com (no port), posting via javascript to domain.com:8081, then we're retrieving the session from domain.com:8081/session/test -- but it's coming up nil in browsers, not in Postman.

This is possibly the issue, but I'm investigating further.

**Comment by e1engineer** [comment]
That was the issue.

Serving the SPA as static files within golang rectifies the issue. I'm not sure if there's anything you can do in fiber for those who are serving up their API and frontend on different ports, but serving static files through golang is a solution that works for us.

**Comment by hi019** [comment]
It probably has to do with cookies and how browsers handle them. What about tweaking the `CookieSameSite` attribute? By default it is set to Lax https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#lax

In the SPA, is the session cookie being sent to `domain.com:8081`?

**Comment by e1engineer** [comment]
I'll give it a try.

What's the performance of app.Static for serving static files compared to, say, nginx?

**Comment by hi019** [comment]
We have done some informal benchmarks in the Discord that found app.Static is faster than HTTP. Nothing official has been done though.
