### ISSUE TITLE
🚀 middleware: monitor: use websockets connection instead.

### ISSUE THREAD

**Issue by imsk17** [gofiber/fiber#1315]
**Is your feature request related to a problem?**
No
**Describe the solution you'd like**
I would prefer if the monitor middleware used the WebSockets instead of multiple get requests.
**Describe alternatives you've considered**
None
**Additional context**
N/A
### I am ready to work on this issue and make relevant commits.

**Comment by imsk17** [comment]
I believe we will need the https://github.com/gofiber/websocket package imported and we will need to setup two routes. One for the WebSocket, and the other to GET the HTML.

**Comment by ReneWerner87** [comment]
yes not a bad idea, but then this would have to happen in a separate repository, as we want to keep the dependencies as low as possible

we have a repository , where you could add such a variant
https://github.com/gofiber/contrib

**Comment by imsk17** [comment]
that makes sense. so I will move this to the contrib repo. I believe this issue can be closed now.
