### ISSUE TITLE
🤗  CreateFile main.go: The system cannot find the file specified. Static file

### ISSUE THREAD

**Issue by dangolbeeker** [gofiber/fiber#1325]
CreateFile main.go: The system cannot find the file specified.  Error created a public folder with a index.html 
 
 My code is as follows
```
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	app.Static("/", "./public")

	log.Fatal(app.Listen(":3000"))
}

```

**Comment by ReneWerner87** [comment]
could not reproduce it (@dangolbeeker)

```go
package main

import (
    "io/ioutil"
    "log"
    "os"

    "github.com/gofiber/fiber/v2"
)

func main() {
    publicDir := "./public";
    if _, err := os.Stat(publicDir); os.IsNotExist(err) {
        os.Mkdir(publicDir, 0777)
    }
    indexFile := publicDir + "/index.html"
    err := ioutil.WriteFile(
        indexFile,
        []byte("<!DOCTYPE html><html lang=\"de\"><head><meta charset=\"utf-8\"><title>Awesome</title></head><body><h1>Fiber</h1></body></html>"),
        0777,
    )
    if err != nil {
        log.Fatal(err)
    }

    app := fiber.New()
    app.Static("/", publicDir)

    log.Fatal(app.Listen(":3000"))
}
```
![image](https://user-images.githubusercontent.com/7063188/117669716-7f665600-b1a7-11eb-80c9-1815d07ba8c5.png)


![image](https://user-images.githubusercontent.com/7063188/117669666-737a9400-b1a7-11eb-93df-41e8c3685c24.png)


please give me more information, about the stucture of the project, error message and please test the standalone script on your machine.

**Comment by dangolbeeker** [comment]
From the quickstart documentation your code works  but looks completely different.
`package main

import "github.com/gofiber/fiber/v2"

func main() {
    app := fiber.New()

    app.Get("/", func(c *fiber.Ctx) error {
        return c.SendString("Hello, World 👋!")
    })

    app.Listen(":3000")
}`

**Comment by ReneWerner87** [comment]
In my example I only created the folder and the index.html dynamically, otherwise it does not differ from your example at the beginning.

However the last code snippet of yours is completely different, there you don't use the static method and use directly a GET resource, this confuses me a bit

How do we want to remain now? I can't see any error with the static method?

**Comment by dangolbeeker** [comment]
Ok I understand now. The Quick start example may not seem clear to those with no or little go experience 
![image](https://user-images.githubusercontent.com/49079747/117724339-9c078b80-b1b1-11eb-8c8b-d5b165b87c6a.png)

**Comment by hi019** [comment]
The quick start code is only supposed to serve a simple GET request, not serve files if that's what you mean.
