### ISSUE TITLE
mtls, socket hang up.🤗 

### ISSUE THREAD

**Issue by pnunn** [gofiber/fiber#1327]
**Question description**
I'm trying to get an api server working with mtls. I seem to have it working OK with one way tls (on the server) and it seems to work if I set the ClientAuth to tls.RequireAnyClientCert, but when I set it as shown in the snippet, all I get back is socket hang up (and it returns really quickly).

What should I get back with a certificate that isn't from the same CA as the server certificate, I'm really not sure what to expect.
A client certificate from the CA also returns the same socket hang up message.

**Code snippet** 
```
config := &tls.Config{
                Certificates: []tls.Certificate{cer},
                ClientCAs:    caCertPool,
                ClientAuth:   tls.RequireAndVerifyClientCert,
                //ClientAuth:   tls.RequireAnyClientCert,
        }

```

**Comment by efectn** [comment]
Can you give more reproducible example? This is unexcepted result @pnunn
