### ISSUE TITLE
🚀 Does fiber have plan to support annotation routing, such as beego does.

### ISSUE THREAD

**Issue by kotlin2018** [gofiber/fiber#1331]
**Is your feature request related to a problem?**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kiyonlin** [comment]
We have no such plan for annotation routing so far.

**Comment by kotlin2018** [comment]
为什么不支持哦?注解路由结合swagger是一个很棒的功能哦

**Comment by kiyonlin** [comment]
So do you have any ideas how to implement this feature?

Btw, could you please use English so that more people can participate in this issue?

**Comment by kotlin2018** [comment]
Thank you for answering me。
sorry my english is too poor。

**Comment by Fenny** [comment]
Fiber build around the router specs of Expressjs, we have no plans to change this.
