### ISSUE TITLE
🤗 Role Based Control Middleware 

### ISSUE THREAD

**Issue by Koredeoluwafemi** [gofiber/fiber#1334]
**Hi people, I will like to know if there is a role based access control middleware in fiber**

**Comment by Koredeoluwafemi** [comment]
I couldnt find any and I am trying to implement one but I am having a hard time getting the route handler in the middleware.

Is there anyway to have access to the route handler in a middleware?

**Comment by ReneWerner87** [comment]
hi, i think there is no such middleware currently available

here is a small code example how you can access the routing information
```go
app.Use(func(c *fiber.Ctx) error {
        // current route
        c.Route().Path
        // all routes - 0=GET - stack[0] -> all registered get routes
        app.Stack()
    })
 ```

![image](https://user-images.githubusercontent.com/7063188/118505148-712ab380-b72c-11eb-9235-2a96499d6c52.png)

feel free to create a pull request for it here
https://github.com/gofiber/contrib

**Comment by sujit-baniya** [comment]
@Koredeoluwafemi Maybe this middleware might help you

https://github.com/arsmn/fiber-casbin
