### ISSUE TITLE
🤗 gob: type not registered for interface: fiber.Map

### ISSUE THREAD

**Issue by Koredeoluwafemi** [gofiber/fiber#1339]
**I am getting this error in my log, gob: type not registered for interface: fiber.Map, what does it mean and how can I resolve it**

**Comment by ReneWerner87** [comment]
we use gob in the session middleware and probably you use there the fiber.map for a type which you store

in order for gob to encode and decode it properly so that it can be stored in the storage, it needs to know the blueprint of the type

for this there is a method in the session middleware, where you can register the types you use once 

https://github.com/gofiber/fiber/tree/master/middleware/session#examples

![image](https://user-images.githubusercontent.com/7063188/118799160-b4a52f00-b89e-11eb-8b1c-27685cb92ae9.png)

**Comment by ReneWerner87** [comment]
here an example for this
https://github.com/gofiber/recipes/blob/master/csrf/routes/mainServer.go#L35

**Comment by Koredeoluwafemi** [comment]
Thanks @ReneWerner87, issue resolved now, will close this issue now but before that can you help look into this session issue

If I get a session key like the example below in my middleware to check user login

    sessionUser := currSession.Get("User").(fiber.Map)		
    // release the currSession		
    err = currSession.Save()		
    if err != nil {			
          return err		
    }

does it delete it key after saving? I discovered that I am getting null on page refresh after getting it the first time

**Comment by ReneWerner87** [comment]
need more code to be able to answer your question 100%.

after the save it stores the data in the storage and releases the data which has been requested for this process

i.e. the save should happen at the end of the middleware run, but before the Next call if you have one

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/master/middleware/session/session.go#L159

https://github.com/gofiber/fiber/blob/master/middleware/session/session.go#L46

**Comment by Koredeoluwafemi** [comment]
The links gave me a better understanding, thanks a lot, lastly at what point is it advisable to call the regenerate function or what's its real use

        err := session.Regenerate()
	    if err != nil {
		    return err
	    }

**Comment by ReneWerner87** [comment]
unfortunately the code is not from me

i guess if you want to renew the cookie for the session and the storage entry, unfortunately i can't think of a usecase right now, maybe have a look at express, i think we have adapted the behavior of express

**Comment by Koredeoluwafemi** [comment]
okay, thanks for your time, really appreciated your help.
