### ISSUE TITLE
🐛 Not Correct return path 

### ISSUE THREAD

**Issue by sciefylab** [gofiber/fiber#1342]
**Fiber version**
Fiber v2.9.0 , Fiber v2.10.0 
**Issue description**
 i cannot return from path /user/index or /user/create, both request towards to /user/:name. see bellow.
**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
	app := fiber.New()

	app.Get("/user/:name", func(c *fiber.Ctx) error {
		return c.SendString("Hello , " + c.Params("name"))
	})

	app.Get("/user/index", func(c *fiber.Ctx) error {
		return c.SendString("user index") // <=== Return Hello , index ??
	})

	app.Get("/user/create", func(c *fiber.Ctx) error {
		return c.SendString("user create") // <=== Return Hello , create ??
	})

	app.Listen(":8080")

}
```

**Comment by ReneWerner87** [comment]
@sciefylab 
fiber works similar to express when defining routes and there the sequence of the declaration is important

if it is not already in the documentation we will add it soon

i.e. the problem with your declaration is that the route which is very unspecific precedes the route which is specific and would match your request

if a route is matched the handler is executed and if there is no next called, the other handler that would be defined under a different declaration and where the route would also match is not used.

so in your example you would just have to declare this very variable route last after the more fixed routes

**Comment by ReneWerner87** [comment]
http://expressjs.com/en/api.html#express
![image](https://user-images.githubusercontent.com/7063188/118942004-9b5dba80-b952-11eb-868c-8506ca8a093e.png)

**Comment by sciefylab** [comment]
Ok, I just realized the sequence in fiber really matters. thanks
