### ISSUE TITLE
🚀 Limiter working with specified methods

### ISSUE THREAD

**Issue by falsandtru** [gofiber/fiber#1345]
**Is your feature request related to a problem?**

I only want to limit POST requests.

```go
	app.Get("/signup", func(c *fiber.Ctx) error {
	})
	app.Post("/signup", func(c *fiber.Ctx) error {
	}).Use(limiter.New(limiter.Config{
		Max:        10,
		Expiration: 60 * time.Second,
	}))
```

**Describe the solution you'd like**

```go
	app.Get("/signup", func(c *fiber.Ctx) error {
	})
	app.Post("/signup", func(c *fiber.Ctx) error {
	}).Use(limiter.New(limiter.Config{
		Method:     {"POST"},
		Max:        3,
		Expiration: 60 * time.Second,
	}))
```

**Describe alternatives you've considered**

**Additional context**

**Comment by hi019** [comment]
We should instead have a function that receives an instance of fiber context and returns a boolean. If it returns true then the request will be counted towards the limit and if not it won't.

**Comment by ReneWerner87** [comment]
app.Use(limiter.New(limiter.Config{
		Next: func(c *fiber.Ctx) {
return c.Method() !== "POST" 
}, 
		Max:        3,
		Expiration: 60 * time.Second,
	}))

app.Post("/signup", func(c *fiber.Ctx) error {
	})

**Comment by falsandtru** [comment]
I adopted the third pattern, thanks!
