### ISSUE TITLE
🤗 Previous Url 

### ISSUE THREAD

**Issue by Koredeoluwafemi** [gofiber/fiber#1348]
**I will like to know if fiber stores the previous url, is it possible to redirect to a previous url, something like this below**

```
return c.Redirect(c.Previous)
```

**Comment by ReneWerner87** [comment]
No, for that you would have to know which request belongs to which user

You could put the information into a storage and map it to a session cookie

However, this is not code that should be provided via the framework, but business logic or customized stuff that comes via third party plug-ins /middlewares

Technically, the framework offers everything to do this

**Comment by Koredeoluwafemi** [comment]
Okay, thanks, I will build it as  a middleware.
