### ISSUE TITLE
💡 v3 discussion

### ISSUE THREAD

**Issue by Fenny** [gofiber/fiber#1354]
<p align="center">
  <a href="https://gofiber.io">
    <img alt="Fiber" height="125" src="https://raw.githubusercontent.com/gofiber/docs/master/static/fiber_v2_logo.svg">
  </a>
</p>

Dear Gophers, we think it's a good idea to start discussions regarding the v3. You are welcome to join us on discord where we created a dedicated channel to pin suggestions for the next update <a href="https://gofiber.io/discord"><img src="https://img.shields.io/discord/704680098577514527?style=flat&label=%F0%9F%92%AC%20discord&color=00ACD7" height="15"></a>.

**Comment by sujit-baniya** [comment]
Features I'm thinking might go with v3

**FEATURE 1:**
Include some features in gofiber client?
1) Timeout
2) Retry mechanism
3) Throttle

**FEATURE 2:**
I think implementing global template layout also a good idea (including option to add properties to template.
For e.g.
```go
app := fiber.New(fiber.Config {
  ...
  Template: html.NewFileSystem(...),
  TemplateLayout: "layouts/main",
})

// Some fiber middleware to add properties to template
app.Use(func (c *fiber.Ctx) error {
  c.LayoutProperty("auth", "blabla")
  return c.Next()
})

// At this point, fiber would auto load view on above mentioned layout including all the properties from middleware
// It would work like it's currently working if user provide layout as 3rd param
// The properties would be available throughout the view file and layout
app.Get("/login", fiber(c *fiber.Ctx) error {
  return c.Render("views/login")
}
```

**Comment by taichi1024** [comment]
Hope v3 app.static support embed

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/120783438-54afb900-c52b-11eb-8534-6faad1d37ef2.png)
static will probably not be rewritten, rather use the filesystem middleware, it currently does not work perfectly with embed, think here you can test again and possibly create a feature report, with which we give better support for embed FS in the filesystem middleware, but otherwise this is usable for now
![image](https://user-images.githubusercontent.com/7063188/120783728-9a6c8180-c52b-11eb-9802-6f1e6abd2dad.png)

**Comment by ubearline** [comment]
I want to be able to generate API interface documents automatically.

**Comment by FlameMida** [comment]
need more documents and examples with different language

**Comment by G2G2G2G** [comment]
"Suggestions for next update"
The "caching properties of cookie so it's user friendly" suggested here:
https://github.com/gofiber/fiber/issues/1127

**Comment by micross** [comment]
I want to be able to disable global layout in special handlers.
For e.g.

```
app := fiber.New(fiber.Config {
  ...
  TemplateLayout: "layouts/main",
})

// disable global layout by passing "" to 3rd param
app.Get("/login", fiber(c *fiber.Ctx) error {
  return c.Render("login", fiber.Map{}, "")
}
```

**Comment by hotrungnhan** [comment]
im suggest that we can 
- Specific quaranty of process instead of max cpucore

**Comment by sujit-baniya** [comment]
@micross Isn't it working with empty string in `c.Render("login", fiber.Map{}, "")`. I checked the current logic and it seems it works as expected i.e. it will disable global layout by passing "" to 3rd param

https://github.com/gofiber/fiber/blob/master/ctx.go#L958-L962

**Comment by micross** [comment]
@sujit-baniya yeah, you are right. maybe is a bug in jet template engine. is says 'template / could not be found'.

_**./views/index.jet**_
```
<h1>in index</h1>
```

_**./views/layouts/main.jet**_
```
<h1>in layout main</h1>
{{ embed() }}
```

```go

app := fiber.New(fiber.Config{
	Views:       engine,
	ViewsLayout: "layouts/main",
})

app.Get("/", func(c *fiber.Ctx) error {
	return c.Render("index", fiber.Map{}, "")
})

```



[https://github.com/gofiber/template/blob/master/jet/jet.go#L220-L229](https://github.com/gofiber/template/blob/master/jet/jet.go#L220-L229)

**Comment by sujit-baniya** [comment]
@micross Yes it's a bug, I added a PR for above: https://github.com/gofiber/template/pull/135/files

**Comment by xdorro** [comment]
v3 need to support gqlgen and jwt for gqlgen :D

**Comment by Fenny** [comment]
Quick update:

We decided to wait with v3 until Go1.18 is released in early 2022 along with generics 🥳 

Keep you updated!

**Comment by efectn** [comment]
Split fasthttp methods as engines/fasthttp. Community can create own engine bindings like net/http. Similar to https://github.com/labstack/echo/tree/v2.2.0/engine but only fasthttp supported as builtin in fiber repo.

**Comment by ZQun** [comment]
> * [🚀HTTP/2 支持 #1541](https://github.com/gofiber/fiber/issues/1541)
> * 添加头盔、keyauth、重定向、重写到光纤存储库。

@efectn 
hi,
Will the V3 version support http2?

**Comment by Rayan1159** [comment]
> > * [🚀HTTP/2 支持 #1541](https://github.com/gofiber/fiber/issues/1541)
> > * 添加头盔、keyauth、重定向、重写到光纤存储库。
> 
> @efectn hi, Will the V3 version support http2?

Fiber is built on fasthttp, so ask there.

**Comment by efectn** [comment]
> > * [🚀HTTP/2 支持 #1541](https://github.com/gofiber/fiber/issues/1541)
> > * 添加头盔、keyauth、重定向、重写到光纤存储库。
> 
> @efectn hi, Will the V3 version support http2?

I don't know but i hope. That's maintainers' decision.

**Comment by li1234yun** [comment]
Explore more effective and efficient development mode, such as: support generic, more convenient tools, built-in OpenAPI doc etc.

**Comment by Jictyvoo** [comment]
Maybe we can add the possibility to create hooks to fiber app to everytime a new handler is registered. So in this way the user can make a way to generate a documenting page for their api

**Comment by ansidev** [comment]
How about a CLI command to list all routes?
Many web frameworks support this one.

For example: `buffalo routes` (https://gobuffalo.io/en/docs/helpers/)

**Comment by efectn** [comment]
- Hooks like https://www.fastify.io/docs/latest/Hooks/

**Comment by esmupamungkas** [comment]
Automatic swagger documentation could be helpful for my case.

**Comment by goofcc** [comment]
1. Routing mapping function to organize code structure in a more elegant way.
2. Command line scaffolding, for example, it is convenient for newbies to create an app faster.

**Comment by ad3n** [comment]
1. Support HTTP/2
2. Support HTTP/3
3. Automatic Swagger Documentation

**Comment by efectn** [comment]
split context into the req, resp and others (like next)
```go
c.Req.GetHeaders()
c.Resp.GetHeaders()
c.Next()
```

**Comment by balcieren** [comment]
Should write with net/http for catching innovations. (While I writing this comment, my hands trembled but I am ready for lynch.)

**Comment by NorbertHauriel** [comment]
An official implementation of burst limiter would be nice in v3, similar to this #486.
As a separate middleware, or including it in the window limiters.

**Comment by sagadsalem** [comment]
- CLI command helper to help you create a new app with a simple project structure or check routes list
- Add support for hot reload
- fiber ORM

**Comment by balcieren** [comment]
1. `fiber.Ctx` should be `interface` (for customize)
2. `fiber.Error`'s message should be `interface` (for multiple error messages)
3. Renaming functions names 
   ##### `fiber.App`
   * `Listen()` --> `Start()`
   * `ListenTLS` --> `StartTLS()`
   *  ....
   ##### `fiber.Ctx`
    * `Query()` --> `QueryParam()`
    * `Param()` --> `PathParam()`
    * `Get() `--> `GetReqHeader()` // `GetRequestHeader()`
    * `Set()` --> `SetReqHeader()` // `SetRequestHeader()`
    *  ...
4.  `Scheme()` --> returns `http` or `https` / `Protocol()` --> returns `HTTP/1.1` or `HTTP/2.0` (for HTTP2)
5. HTTP methods names should be write with uppercase. ( `Get()` --> `GET()`, `Post()` --> `POST()` ... )
6. `HTTP/2.0` Support

**Comment by xdorro** [comment]
Support gRPC (gRPC Gateway)

**Comment by kei-adpopcorn** [comment]
override fiber.Ctx

**Comment by cindRoberta** [comment]
HTTP/2:
- https://github.com/gofiber/fiber/issues/262
- https://github.com/valyala/fasthttp/issues/144
- https://github.com/fasthttp/http2
- https://github.com/dgrr/http2

HTTP/3:
- https://github.com/lucas-clemente/quic-go

**Comment by efectn** [comment]
- One Listen method and StartConfig instead of Listen, ListenTLS, ListenMutualTLS.
- Make own binding instead of Gorilla Schema. Like Echo and escpecially Gin.

**Comment by ReneWerner87** [comment]
Here you can create the feature request for your ideas
https://github.com/gofiber/fiber/milestone/1

Preferably one report per feature or if they go in the same direction, then also grouped together.
And please provide a code example for the usage in the report(not the implementation).

We will then review them and decide which ones will make it into the core and start with the implementation.

You are also welcome to help us

In the next time we will create a beta branch, which will be used for development.

**Comment by taichi1024** [comment]
**suggest：**
1. Use Go1.18+【generics】refactoring
2. Manage versions like Django [https://static.djangoproject.com/img/release-roadmap.3c7ece4f31b3.png](url)
3. Support microservice features

**Comment by xiayulu** [comment]
Suggest：
1. `Login User` is a very common pattern when build a web app. 

I think web developers never say no to this feature.

**Comment by ltns35** [comment]
Enable by default security best practices when protecting against common attacks that an API server could receive.

**Comment by ltns35** [comment]
> > Enable by default security best practices when protecting against common attacks that an API server could receive.
> 
> Good idea, can you create a feature request for this.
Maybe with a list of best practices which we should apply, so that it is clearly defined and you can start with the implementation.

@ReneWerner87 I'll look into it when I get back from vacation (next week) and do a feature request with its implementation.

**Comment by gozeloglu** [comment]
> Features I'm thinking might go with v3
> 
> **FEATURE 1:** Include some features in gofiber client?
> 
> 1. Timeout
> 2. Retry mechanism
> 3. Throttle
> 
> **FEATURE 2:** I think implementing global template layout also a good idea (including option to add properties to template. For e.g.
> 
> ```go
> app := fiber.New(fiber.Config {
>   ...
>   Template: html.NewFileSystem(...),
>   TemplateLayout: "layouts/main",
> })
> 
> // Some fiber middleware to add properties to template
> app.Use(func (c *fiber.Ctx) error {
>   c.LayoutProperty("auth", "blabla")
>   return c.Next()
> })
> 
> // At this point, fiber would auto load view on above mentioned layout including all the properties from middleware
> // It would work like it's currently working if user provide layout as 3rd param
> // The properties would be available throughout the view file and layout
> app.Get("/login", fiber(c *fiber.Ctx) error {
>   return c.Render("views/login")
> }
> ```

I would like to add retry mechanism. It seems that nobody has been started to implement it. If you accept to add this feature to v3, I can start to implement.

**Comment by ReneWerner87** [comment]
> > Features I'm thinking might go with v3
> > **FEATURE 1:** Include some features in gofiber client?
> > 
> > 1. Timeout
> > 2. Retry mechanism
> > 3. Throttle
> > 
> > **FEATURE 2:** I think implementing global template layout also a good idea (including option to add properties to template. For e.g.
> > ```go
> > app := fiber.New(fiber.Config {
> >   ...
> >   Template: html.NewFileSystem(...),
> >   TemplateLayout: "layouts/main",
> > })
> > 
> > // Some fiber middleware to add properties to template
> > app.Use(func (c *fiber.Ctx) error {
> >   c.LayoutProperty("auth", "blabla")
> >   return c.Next()
> > })
> > 
> > // At this point, fiber would auto load view on above mentioned layout including all the properties from middleware
> > // It would work like it's currently working if user provide layout as 3rd param
> > // The properties would be available throughout the view file and layout
> > app.Get("/login", fiber(c *fiber.Ctx) error {
> >   return c.Render("views/login")
> > }
> > ```
> 
> I would like to add retry mechanism. It seems that nobody has been started to implement it. If you accept to add this feature to v3, I can start to implement.

Sounds good, can you first create a feature report for it

unfortunately we have currently a little start issues

we first have to create the base for the start -> when this is done we will inform in the feature reports, so you can start then

**Comment by tristanisham** [comment]
Add built-in type references for `func(c *fiber.CTX) error` called `Route` for clarity.

**Comment by efectn** [comment]
Open issues for new suggestions/features about v3.

**Comment by smitpatelx** [comment]
> I want to be able to generate API interface documents automatically.

You can use go-swagger to generate `swagger.json`. Then, just use `openapi-typescript-codegen` in your front-end.
After that just add this script:
You can change the params, refer docs.
```json
// package.json
"scripts": {
   "gen:types": "openapi --input http://host:port/openapi.json --output ./src/generated --client axios --indent 2 --useOptions",
 }
 ```

**Comment by gaby** [comment]
All,

Fiber v3 is now stable, thanks! 💪

https://github.com/gofiber/fiber/releases/tag/v3.0.0
