### ISSUE TITLE
Can i close the display window in command? 🤗 

### ISSUE THREAD

**Issue by lpf763827726** [gofiber/fiber#1359]
When i go run it, it will show me the host and port window.

Can i close it? I am rookie,please help

<img width="615" alt="微信图片_20210602162657" src="https://user-images.githubusercontent.com/43004977/120462563-a3dfd780-c3cd-11eb-8e35-4e5925c9de9d.png">

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/fiber#config

![image](https://user-images.githubusercontent.com/7063188/120466799-c6f39280-c39f-11eb-96b5-3d9329dd297d.png)

yes sure, please read through our documentation

**Comment by lpf763827726** [comment]
ok, i see it, thank you so much :)
