### ISSUE TITLE
🚀 Configure proxy.Balancer with custom timeout or client

### ISSUE THREAD

**Issue by AndreasStokholm** [gofiber/fiber#1362]
**Is your feature request related to a problem?**

Yes, we need to be able to set a custom timeout on our proxy, since our legacy platform has multiple endpoints that are quite slow, and exceed the 1 second default timeout set in fasthttp's `LBClient`.

**Describe the solution you'd like**

The ability to set a custom fasthttp client for the `proxy.Balancer` config.

**Describe alternatives you've considered**

I spoke with hi019 on the discord server, and they suggested the approach I described above. Initially I was thinking of just being able to set a timeout like the IdleTimeout you can set in your `fiber.New` config. I liked the custom fasthttp client better as that is much more flexible.

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/120756721-e4e00500-c50f-11eb-918f-78bb2e6d10d2.png)
the lbclient offers the possibility to set a timeout, currently the default timeout is one second

wouldn't it be enough to make this timeout configurable and set it in the lbclient when initializing the middleware ?

![image](https://user-images.githubusercontent.com/7063188/120756742-ef020380-c50f-11eb-9e5c-6cae98a115fb.png)

**Comment by AndreasStokholm** [comment]
I was considering this at first too. Maybe it's simpler to just do it like that. I'll let you decide what you prefer.

**Comment by ReneWerner87** [comment]
well then i would do that and quickly create a pull request

then that is also in a few hours through and in the next release
