### ISSUE TITLE
🐛  BUG: If the port is already reserved, the program will be closed without any warnings and errors!

### ISSUE THREAD

**Issue by BaseMax** [gofiber/fiber#1367]
**Fiber version** latest

**Issue description**

If the port is already reserved, the program will be closed without any warnings and errors!

You are expected to display at least one error or text and then close the app!

https://github.com/gofiber/fiber/blob/b14224e5e4a20372025e5d76a54f65830e5eb6b1/app.go#L591

```
[max@workstation API]$ ./api
[max@workstation API]$ echo $?
0
```

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
    app := fiber.New()
    app.Get("/", func(c *fiber.Ctx) error {
        return c.SendString("Hello, World 👋!")
    })
    app.Listen(":3000")
}
```

**Comment by hi019** [comment]
app.Listen returns an error. If you do `panic(app.Listen(...)` or wrap it in a log statement, you will see output.

**Comment by BaseMax** [comment]
> `app.Listen` returns an error.

Yes, I know. I read the code and attached it to the message above.

Dear @hi019, I had this problem and wasted more than 20 minutes of my time figuring out why the program exit without any message. I thought this was an interference with the structure of my libraries, maybe an incomplete file was downloaded! lol (I used a proxy for `go get`)

If you do not decide to solve this, then it is better to change the sample code and examples. to make this clear how it works.

**Comment by hi019** [comment]
Oh, I must have replied to your issue before you added the url. But I'm not sure if this is a bug, `http.ListenAndServe`, gin and probably echo all have the same behaviour. 

I agree the README should make note of this and use log.Fatal.
