### ISSUE TITLE
Nested routes

### ISSUE THREAD

**Issue by milosgajdos** [gofiber/fiber#1374]
**Question description**

I've been playing around with fiber for a bit now and I've come across a case in routing which I can't seem to figure out.

I'd like to have a `/api/v1` group that would have "nested" routes for different resources i.e.

group:
  `/api/v1`

foo routes:
  `/api/v1/foos`
  `/api/v1/foos/:uid`

bar routes:
  `/api/v1/foos/:uid/bars`
  `/api/v1/foos/:uid/bars/:buid`

Following the [mount](https://docs.gofiber.io/api/app#mount) docs I thought I could do something like this:

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {
	b := fiber.New()

	b.Get("/:uid/bars", func(c *fiber.Ctx) error {
		return c.SendString("API path: /:uid/bars" + c.Params("uid"))
	})

	app := fiber.New()
	api := app.Group("/api")
	v1 := api.Group("/v1")

	v1.Get("/foos", func(c *fiber.Ctx) error {
		return c.SendString("API path: /foos")
	})

	app.Mount("/foos", b)

	app.Listen(":3000")
}
```

But this `404`s on `foos/dfd/bars`
```shell
$ curl -I http://127.0.0.1:3000/api/v1/foos/dfd/bars
HTTP/1.1 404 Not Found
Date: Wed, 09 Jun 2021 07:43:41 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 33
```

if I remove `v1.Get("/foos"...` route the `/api/v1/foos/dfd/bars` path does indeed work, but `/api/v1/foos` returns `404` (because there is not `GET` route to `/foos`.

I'm suspecting `Mount` is not capable of merging route paths, but I havent had much time looking into this.

Is there a way I can do this in fiber or is this simply not possible at the moment?

Thanks.

**Comment by ReneWerner87** [comment]
@milosgajdos 

its working for our mount app:
![image](https://user-images.githubusercontent.com/7063188/121318128-3ff86a00-c90b-11eb-9c5a-8c22d0137918.png)


but i think you want
![image](https://user-images.githubusercontent.com/7063188/121318367-7930da00-c90b-11eb-85c1-55bbf7c7eabc.png)

for this you have to mount it on the v1
![image](https://user-images.githubusercontent.com/7063188/121318431-877ef600-c90b-11eb-80ee-1eba1c54c2c9.png)

**Comment by milosgajdos** [comment]
Have you tried `GET`-ing `/api/v1/foos`? (after mounting to `v1`)?

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {
	b := fiber.New()

	b.Get("/:uid/bars", func(c *fiber.Ctx) error {
		return c.SendString("API path: /:uid/bars " + c.Params("uid"))
	})

	app := fiber.New()
	api := app.Group("/api")
	v1 := api.Group("/v1")

	f := fiber.New()
	f.Get("/foos", func(c *fiber.Ctx) error {
		return c.SendString("API path: /foos")
	})

	v1.Mount("/foos", b)

	app.Listen(":3000")
}
```

```shell
$ curl -I http://127.0.0.1:3000/api/v1/foos/dfd/bars
HTTP/1.1 200 OK
Date: Wed, 09 Jun 2021 08:33:14 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 24
```

```shell
$ curl -I http://127.0.0.1:3000/api/v1/foos
HTTP/1.1 404 Not Found
Date: Wed, 09 Jun 2021 08:33:18 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 24
```

**Comment by ReneWerner87** [comment]
Yeah, have tested it, check the second and third screenshot

**Comment by milosgajdos** [comment]
Looks like something like this might do the trick:

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {
	b := fiber.New()

	b.Get("/:uid/bars", func(c *fiber.Ctx) error {
		return c.SendString("API path: /:uid/bars " + c.Params("uid"))
	})

	app := fiber.New()
	api := app.Group("/api")
	v1 := api.Group("/v1")

	f := fiber.New()
	f.Get("/foos", func(c *fiber.Ctx) error {
		return c.SendString("API path: /foos")
	})

	v1.Mount("/", f)
	v1.Mount("/foos", b)

	app.Listen(":3000")
}
```

```shell
$ curl -I http://127.0.0.1:3000/api/v1/foos
HTTP/1.1 200 OK
Date: Wed, 09 Jun 2021 09:58:23 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 15
```

```shell
$ curl -I http://127.0.0.1:3000/api/v1/foos/dfd/bars
HTTP/1.1 200 OK
Date: Wed, 09 Jun 2021 09:58:25 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 24
```
