### ISSUE TITLE
🤗  How to handle errors from internal package?

### ISSUE THREAD

**Issue by jorgii** [gofiber/fiber#1375]
**Question description**
The internal package declares `schema.MultiError` and `schema.ConversionError`. These are returned from ctx.QueryParser or ctx.BodyParser when the input is not in the expected type (for example providing `foo` when expecting an ISO 8601 datetime string). I would like to customise the error message for such errors. Normally I would import the error type and based on it would decide the error message. Since these error types are in the internal package I cannot import them. Is there another way of customising the error messages?

**Code snippet**

```go
package main

import (
    "log"
    "time"

    "github.com/gofiber/fiber/v2"
)

type MyFilter struct {
    CreatedAt time.Time `query:"created_at"`
}

func hello(ctx *fiber.Ctx) error {
    var filter MyFilter
    if err := ctx.QueryParser(&filter); err != nil {
        // handle err
        panic(err)
    }
    return ctx.SendString("Hello, World!")
}

func main() {
    app := fiber.New()
    app.Get("/hello", hello)
    log.Fatalln(app.Listen(":8085"))
}
```
**Request**

```bash
curl --location --request GET 'http://localhost:8085/hello?created_at=foo' 
```

**Comment by ReneWerner87** [comment]
thank you for the report,
you are absolutely right, we should move the errors from the internal package and make them available

can you do that and create a pull request for us, then i will review this?

**Comment by GibranHL0** [comment]
Is @jorgii working on this issue? 🤔 If not, could I give it a try?

**Comment by jorgii** [comment]
@GibranHL0 I was planning to do it around the end of the week. If you can start on it sooner please go ahead.

**Comment by GibranHL0** [comment]
@jorgii I got assigned another issue, I'll focus on the other one.
