### ISSUE TITLE
🐛 

### ISSUE THREAD

**Issue by LianaLing** [gofiber/fiber#1376]
**Fiber version**
2.12.0

**Issue description**
It seems like there is an error with the Fiber library when the `ParseRequest()` function. We used some `Validator` tags in our controller such as `validate:"required"`. When we used this function and sent a `curl` request with a JSON body to test the `controller` , the response we got said that we didn't provide any `value` to the JSON field, but in fact we did. However, when using our own manual unmarshalling, the curl request worked just fine.

This is the error.
![image](https://user-images.githubusercontent.com/68136684/121333906-cc2a8180-c94b-11eb-860f-6b2efd4ad64c.png)

This is the expected result.
![image](https://user-images.githubusercontent.com/68136684/121333944-d482bc80-c94b-11eb-88b5-82cf29ec7e5f.png)

**Code snippet**
```go
func ParseRequest(c *fiber.Ctx, r Request, mode string) error {
	if mode == "query" {
		if err := c.QueryParser(r); err != nil {
			return err
		}
	} else if mode == "body" {
		// NOTE: Fiber's BodyParser is not working for some reason
		// if err := c.BodyParser(r); err != nil {
		// 	return err
		// }
		if unmarshalErr := json.Unmarshal(c.Body(), r); unmarshalErr != nil {
			return unmarshalErr
		}
	}
	return nil
}
```

**Comment by ReneWerner87** [comment]
https://curl.se/docs/manpage.html#-d
you send a POST BODY in the GET request which is very unexpected

https://github.com/gofiber/fiber/blob/master/ctx.go#L266
our functionality looks at the contentType header, based on that we parse the content of the body


https://docs.gofiber.io/api/ctx#bodyparser
and don't forget the identifer names in the json or form parsing anotations
