### ISSUE TITLE
🚀 save or change file app auto restart

### ISSUE THREAD

**Issue by panyox** [gofiber/fiber#1377]
**Is your feature request related to a problem?**
When i edit my programing file and save, i need to use control+Z to stop the running app and then kill -9 to stop the progress absolutely very time, that is annoying.

**Describe the solution you'd like**
Is there possible to add a middleware or plugin to watching the whole project file, when save a file, the app will auto restart so developer no need to stop and rerun.

**Describe alternatives you've considered**
I found these project [https://github.com/silenceper/gowatch](url), [https://github.com/gravityblast/fresh](url), but i don't know how to integrate to Fiber project

**Additional context**

**Comment by tomaswarynyca** [comment]
Hi @panyox, that's what **fiber cli** was created for.
https://github.com/gofiber/cli

**Comment by panyox** [comment]
> Hi @panyox, that's what **fiber cli** was created for.
> https://github.com/gofiber/cli

Just try it, that's Awesome!
