### ISSUE TITLE
🤗  QueryParser does not support time.Time ?

### ISSUE THREAD

**Issue by gopkg-dev** [gofiber/fiber#1378]
**Question description**

QueryParser does not support time.Time

**Code snippet** _Optional_

```go
package main

import (
	"time"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	type TestQuery struct {
		CreateTime time.Time `query:"create_time"`
	}

	app.Get("/", func(c *fiber.Ctx) error {
		var testQuery TestQuery
		err := c.QueryParser(&testQuery)
		if err != nil {
			return err
		}
		return c.JSON(testQuery)
	})

	app.Listen(":3000")
}
```
```
Error  ->   schema: error converting value for "create_time". Details: parsing time "2006-01-02T15:04:05Z07:00": extra text: "07:00"
```

**Comment by ReneWerner87** [comment]
http://localhost:3000/?create_time=2006-01-02T15:04:05Z

so if you choose the right format it runs 


the gorilla schema parser can do the trading
https://github.com/gorilla/schema/blob/8285576f31afd6804df356a38883f4fa05014373/decoder_test.go#L1861

but i think it might be better to register a method for the conversion, which is not possible at the moment
https://github.com/gofiber/fiber/pull/1100

**Comment by gopkg-dev** [comment]
Thanks, i get it

**Comment by ReneWerner87** [comment]
@gopkg-dev check https://docs.gofiber.io/api/ctx#setparserdecoder

**Comment by ReneWerner87** [comment]
its in the newest release https://github.com/gofiber/fiber/releases/tag/v2.20.0
