### ISSUE TITLE
How to create APIs with Protocol Buffer responses🤗 

### ISSUE THREAD

**Issue by abhisamant7** [gofiber/fiber#1379]
go 1.16
fiber 2.12.0

I am trying to implement **Protocol Buffer** into my rest APIs so for that I choose GO lang and fiber framework as its look very easy to use as compare to other framework and also used fasthttp which give good performance however now I am looking to get responses in **Protocol Buffer** instead of json however I couldn't get anything in Fiber document and github.

Anybody have know how to implement it. it will really helpful

Thanks

**Comment by ReneWerner87** [comment]
sorry have no experience with it

can @hi019, @Fenny say something about it ?

**Comment by tianjipeng** [comment]
@abhisamant7 Here is demo, you can have a look:
server:
```go
func main() {
	app := fiber.New()

	app.Post("/demo", func(ctx *fiber.Ctx) error {
		body := ctx.Body()
		req := &demo.DemoReq{}
		err := proto.Unmarshal(body, req)
		if err != nil {
			ctx.SendStatus(http.StatusBadRequest)
			return nil
		}

		rsp := &demo.DemoRsp{
			Data: "hello " + req.Msg,
		}

		b, _ := proto.Marshal(rsp)
		ctx.Send(b)
		return nil
	})

	app.Listen(":8000")
}
```
client:
```go
req := &demo.DemoReq{
		Msg: "world",
	}
	body, err := proto.Marshal(req)
	if err != nil {
		log.Fatal("marshal err", err)
	}
	r, _ := http.NewRequest(http.MethodPost, "http://localhost:8000/demo", bytes.NewReader(body))
	rsp, err := http.DefaultClient.Do(r)
	if err != nil {
		log.Fatalf("post err: %v", err)
	}
	defer rsp.Body.Close()
	b, err := ioutil.ReadAll(rsp.Body)
	if err != nil {
		log.Fatalf("read body err: %v", err)
	}

	demoRsp := &demo.DemoRsp{}
	err = proto.Unmarshal(b, demoRsp)
	if err != nil {
		log.Fatalf("proto unmarshal err: %v", err)
	}

	log.Printf("demo rsp: %v\n", demoRsp.String())
```
proto file:
```proto
syntax = "proto3";

message DemoReq {
    string msg = 1;
}

message DemoRsp {
    string data = 1;
}
```

**Comment by abhisamant7** [comment]
Hi @tianjipeng Thanks for demo code however I am little confused with client code. is it used in fiber framework or you used for simple net/http package for demo.

Thanks

**Comment by tianjipeng** [comment]
@abhisamant7 You can use fiber client to send http request, it's result should be same with net/http package.

**Comment by WLun001** [comment]
@abhisamant7 sorry if i get the idea correctly. 

If you wanted to get response in binary, need to make a RPC call instead of HTTP call, from what I understand. 
Here is an [example recipe](https://github.com/gofiber/recipes/tree/master/fiber-grpc)
Or use [grpc gateway]( https://github.com/grpc-ecosystem/grpc-gateway) to generate REST API from proto, and optionally  serve the HTTP server with Fiber

**Comment by pplmx** [comment]
> Or use [grpc gateway](https://github.com/grpc-ecosystem/grpc-gateway) to generate REST API from proto files, and optionally serve the HTTP server with Fiber

Is there a sample: integration fiber with [buf.build: grpc gateway](https://buf.build/grpc-ecosystem/gateway)?
