### ISSUE TITLE
🐛  Serve SPA with filesystem and cache middleware

### ISSUE THREAD

**Issue by TimeForANinja** [gofiber/fiber#1380]
**Fiber version**
Occurring with v2.12.0 & v2.8.0
on both Debian and Windows Systems

**Issue description**
I am trying to serve a static Angular Page using the filesystem middleware.
For that I am requesting a hand full of files. For some reason requesting `/runtime.f5bd8400324dc53c2e62.js` returns the content of `/styles.e641baa6ca1baa4a0a2c.css`...
Commenting out the cache resolves this issue...

**Code snippet**

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cache"
	"github.com/gofiber/fiber/v2/middleware/filesystem"
)

const DATA_PATH = "./assets"
const PORT = 8081

func main() {
	ex, err := os.Executable()
	if err != nil {
		panic(err)
	}
	exPath := path.Join(filepath.Dir(ex), DATA_PATH)

	app := fiber.New()
	app.Use(cache.New(cache.Config{Expiration: 30 * time.Minute, CacheControl: true}))
	app.Use(filesystem.New(filesystem.Config{Root: http.Dir(exPath), Browse: false, Index: "./"}))

	log.Fatal(app.Listen(fmt.Sprintf(":%d", PORT)))
}

```

**Comment by ReneWerner87** [comment]
thank you for the report


why don't you use app.Static ?
![image](https://user-images.githubusercontent.com/7063188/121801980-6e8f8100-cc3a-11eb-9410-845a45d31b67.png)

have tested it, with me I can not reproduce the error, never get another content
![image](https://user-images.githubusercontent.com/7063188/121801987-7a7b4300-cc3a-11eb-8a69-64e37f44b068.png)

**Comment by TimeForANinja** [comment]
didn't knew app.Static was a thing - reads like it even does caching 👍
guess i'll switch our deploy over to that 

not resolving the problem with the cache middleware though - throwing a
```go
app.Use(cache.New(cache.Config{Expiration: 30 * time.Minute, CacheControl: true}))
```
infront of the `app.Static` still serves invalid content

renaming the files to just `runtime.js` and `styles.css` with the content being sth like `This is content inside of runtime.js` does not resolve the problem either

![image](https://user-images.githubusercontent.com/17046330/121806636-f54f5880-cc50-11eb-90b0-81a2b0cdd9e6.png)

renaming to `runtime.txt` and `styles.txt` seems to resolve this issue

**Comment by ReneWerner87** [comment]
cannot reproduce
![image](https://user-images.githubusercontent.com/7063188/123250311-344f9a80-d4ea-11eb-9cae-4844a99e3f93.png)
