### ISSUE TITLE
render: template main does not exist - When migrating to a remote server 

### ISSUE THREAD

**Issue by sdima75** [gofiber/fiber#1385]
Hello.
Please forgive me - I am not a programmer, but sometimes I program for myself.
I have a strange error. My code works on my home computer. However, when I ran the program on the remote server I got the error - render: template main does not exist.

Part of my code:
`engine := html.New("./templates", ".html");
app := fiber.New(fiber.Config{
		Views: engine,
	})`

fiber - Fiber v2.8.0   
On the server the program is in /var/www/my_program
And when I change the path to /var/www/my_program/templates - the start page loads.
`engine := html.New("/var/www/my_program/templates", ".html")`
Please tell me what may be the error?

**Comment by ReneWerner87** [comment]
can you please post the start commands on your shell from where you start the binaries ?

maybe it also makes sense to just print the cwd in the shell on the server, then you know what the dot is

```go
path, err := os.Getwd()
if err != nil {
    log.Println(err)
}
fmt.Println(path) 
```

**Comment by ReneWerner87** [comment]
@sdima75 any news for this ?

**Comment by sdima75** [comment]
> @sdima75 any news for this ?

Hello.
Please forgive me for not responding quickly.
The result is " / ".

**Comment by sdima75** [comment]
> @sdima75 any news for this ?

Hello.
Please forgive me for not responding quickly.
The result is " / ".

**Comment by ReneWerner87** [comment]
can you please post the start commands on your shell from where you start the binaries ?

**Comment by ReneWerner87** [comment]
if the current directory is the root of the system, then it is clear why the program cannot find the template folder from there relative to this folder

you said the order is /var/www/my_program/templates

and according to your research it then looks in 
/templates

**Comment by sdima75** [comment]
> if the current directory is the root of the system, then it is clear why the program cannot find the template folder from there relative to this folder
> 
> you said the folder is /var/www/my_program/templates
> 
> and according to your research it then looks in
> /templates

Hello.
Before I read your post I specified the path - /var/www/my_program/templates - and the site worked (almost).
Now I will correct the static paht (css, js, img).

**Comment by ReneWerner87** [comment]
the relative path is okay, you just have to make sure that it starts in /var/www/my_program (cwd should be this path), since you haven't answered my question about the start command yet, I can't help you there at the moment.

**Comment by sdima75** [comment]
> the relative path is okay, you just have to make sure that it starts in /var/www/my_program (cwd should be this path), since you haven't answered my question about the start command yet, I can't help you there at the moment.

Does that interest you?
/lib/systemd/system/my_program.service

Description=my_program 

[Service] 
Type=simple 
Restart=always 
RestartSec=5s 
ExecStart=/var/www/my_program/my_program 
User=www-data 

[Install] 
WantedBy=multi-user.target

**Comment by ReneWerner87** [comment]
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=


think you should set the working directory to "/var/www/my_program".
```ini
WorkingDirectory=/var/www/my_program
```

**Comment by sdima75** [comment]
Everything works!
Thank you so much for your help!
I wish you a lot of luck and have a lot of money! :-)

**Comment by sdima75** [comment]
> https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=
> 
> think you should set the working directory to "/var/www/my_program".
> 
> ```ini
> WorkingDirectory=/var/www/my_program
> ```

Everything works!
Thank you so much for your help!
I wish you a lot of luck and have a lot of money! :-)

**Comment by sdima75** [comment]
> https://www.freedesktop.org/software/systemd/man/systemd.exec.html#WorkingDirectory=
> 
> think you should set the working directory to "/var/www/my_program".
> 
> ```ini
> WorkingDirectory=/var/www/my_program
> ```

Everything works!
Thank you so much for your help!
I wish you a lot of luck and have a lot of money! :-)
