### ISSUE TITLE
🚀 OAuth2 middleware support

### ISSUE THREAD

**Issue by yungsem** [gofiber/fiber#1389]
Is there a plan to add a middleware to support oauth2?

**Comment by hi019** [comment]
No, we don't have any plans for direct Oauth2 integration

**Comment by mirusky** [comment]
@yungsem It's a complex task... Because there are many flows and specs like Code Flow, PKCE, Hibrid, Implict, Password and others. Also if user use some MFA mechanism it will be more complex to handle. So I recomend to create your own implementation ( handlers ).
