### ISSUE TITLE
sess.Regenerate() issue 🐛 

### ISSUE THREAD

**Issue by EugeneTorap** [gofiber/fiber#1395]
**Fiber version**
v2.13.0

**Issue description**
I want to write a `refresh` api for regenerating a session but it doesn't regenerate session every second call.
When call `refresh` in first time the `fresh` of sess is true and I have a session. In second time the `fresh` of sess is false and `sess.Save()` doesn't save a new session. In third time the `fresh` of sess is true and I have a session.
I think issue is `sess.Regenerate()` does't set `s.fresh = true`.

**Code snippet**

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
	"log"
)

var store = session.New()

func main() {
	app := fiber.New()

	app.Get("/", func(ctx *fiber.Ctx) error {
		sess, err := store.Get(ctx)
		if err != nil {
			return err
		}
		name := sess.Get("name")
		str := fmt.Sprintf("%v", name)
		return ctx.SendString(str)
	})
	app.Get("/refresh", func(ctx *fiber.Ctx) error {
		sess, err := store.Get(ctx)
		if err != nil {
			return err
		}

		fmt.Println(sess.ID(), sess.Fresh())
		if err = sess.Regenerate(); err != nil {
			return err
		}

		sess.Set("name", "bob")

		fmt.Println(sess.ID(), sess.Fresh())
		if err = sess.Save(); err != nil {
			return err
		}

		fmt.Println("The session is refreshed")
		return ctx.SendString("The session is refreshed")
	})
	log.Fatal(app.Listen(":8080"))
}

```

**Comment by hi019** [comment]
You're right, the issue here are with these lines. The session is only saved if it's new:

https://github.com/gofiber/fiber/blob/master/middleware/session/session.go#L141-L143

Calling `Session.Regenerate` and then `Session.Save` doesn't update the cookie, so in the next request the browser sends the previous session ID which was deleted.
