### ISSUE TITLE
i found a mistake in chinese doc

### ISSUE THREAD

**Issue by flynn-eye** [gofiber/fiber#1399]
![image](https://user-images.githubusercontent.com/23251324/122906045-529b8600-d384-11eb-9915-ccf37b4a827f.png)

========
[url](https://github.com/gofiber/fiber/blob/master/.github/README_zh-CN.md)

**Comment by tomaswarynyca** [comment]
Hi @flynn-eye , what is the problem?
If you think there is a problem, please send a PR to solve it.

**Comment by flynn-eye** [comment]
fiber is spelt wrong
