### ISSUE TITLE
HELP: I want to send image or correct image url stored in local dir to react frontend.

### ISSUE THREAD

**Issue by pratikjagrut** [gofiber/fiber#1403]
**Question description**
I'm new to web dev and I'm trying to play with fiber and react with typescript. I'm uploading an image and saving it using SaveFile to ./image dir. Now I wanna fetch that image using react fetch but I'm not able to figure out the correct way to send the image or image URL to the frontend. Can someone help me here, please?

**Comment by ReneWerner87** [comment]
Hi, there are many ways to deliver static files with fiber

here are some of them, my favorite is app.Static on the dist or asset folders

Docs:
https://docs.gofiber.io/api/ctx#sendfile
https://docs.gofiber.io/api/app#static
https://docs.gofiber.io/api/middleware/filesystem

Recipes:
https://github.com/gofiber/recipes/blob/master/spa/main.go#L19-L23

**Comment by pratikjagrut** [comment]
Hey, @ReneWerner87 app.Static works fine for me. Thanks.

**Comment by pratikjagrut** [comment]
I'll close this issue.
