### ISSUE TITLE
🤗 Documentation inconsistent in fiber.Storage, fiber memory storage and session middleware

### ISSUE THREAD

**Issue by Spedoske** [gofiber/fiber#1406]
**Question description**

In the session middleware, the default storage is the fiber memory storage (`internal/storage/memory`), which implements the interface `fiber.Storage`. According the comments in `app.go`, `Storage.Get` should return `ErrNotFound` if the storage does not contain the key. However, when I check out the implementation in `internal/storage/memory/memory.go`, it returns `nil` even if the key is not in the map.

I want to ask the following questions.
+ What is the appropriate behavior for the function `Storage.Get` ?
+ What does the returned error mean when error is not nil ?
+ What does the returned data (`[]byte`) mean when data is nil ?

**Code snippet** _Optional_

```go
// middleware/session/store.go
type Store struct {
	Config
}
...
func (s *Store) Get(c *fiber.Ctx) (*Session, error) {
        ...
	// Fetch existing data
	if loadData {
		raw, err := s.Storage.Get(id)
		...
	}
        ...
}
```

```go
// middleware/session/config.go
// Config defines the config for middleware.
type Config struct {
        ...
	// Storage interface to store the session data
	// Optional. Default value memory.New()
	Storage fiber.Storage
        ...
}
```

```go
// app.go
// Storage interface for communicating with different database/key-value
// providers
type Storage interface {
	// Get gets the value for the given key.
	// It returns ErrNotFound if the storage does not contain the key.
	Get(key string) ([]byte, error)
        ...
}
```

```go
// internal/storage/memory/memory.go
// Get value by key
func (s *Storage) Get(key string) ([]byte, error) {
	if len(key) <= 0 {
		return nil, nil
	}
	s.mux.RLock()
	v, ok := s.db[key]
	s.mux.RUnlock()
	if !ok || v.expiry != 0 && v.expiry <= time.Now().Unix() {
		return nil, nil
	}

	return v.data, nil
}
```

**Comment by ReneWerner87** [comment]
@Fenny can take a look

**Comment by wirepair** [comment]
+1 to this, I also ran into this when trying to use https://github.com/dgraph-io/ristretto as a backend cache, only by returning nil for the object when a key doesn't exist will it return a valid session object.
