### ISSUE TITLE
🤗 Wildcard Domain management 

### ISSUE THREAD

**Issue by Koredeoluwafemi** [gofiber/fiber#1409]
**How do I manage a wildcard domain where a domain like admin.example.com loads a particular route while other subdomains load a separate route. The sub-domains are meant to be created dynamically. **

**Comment by ReneWerner87** [comment]
Please check https://github.com/gofiber/fiber/issues/750#issuecomment-687787415

**Comment by Koredeoluwafemi** [comment]
Yes, I have checked that example but it does not include how to manage wildcard domains like *.example.com

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/123589648-d375da00-d7e9-11eb-97de-d4bd37a02f72.png)
you would have to adjust this part and match your regex domain here based on the current domain with a regex or another logic, the following process should be the same, the important thing is that you fetch the stored fiber apps

**Comment by Koredeoluwafemi** [comment]
Thanks @ReneWerner87, that solves it.
