### ISSUE TITLE
🔥 Add Websocket Support

### ISSUE THREAD

**Issue by dechristopher** [gofiber/fiber#141]
**Is your feature request related to a problem?** No

**Describe the solution you'd like:** I'd like to see the ability to promote a request to a websocket connection and handle pub-sub messaging therein. This is a big feature present in other libraries like gorilla and it would make fiber more competitive.

**Describe alternatives you've considered:** Use a different web library.

**Additional context:** None.

**Comment by Fenny** [comment]
This is already supported by fasthttp, but we are discussing if we should add it within fiber.
https://github.com/fasthttp/websocket
```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber"
	"github.com/fasthttp/websocket"
)

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) {
		err := upgrader.Upgrade(c.Fasthttp, func(conn *websocket.Conn) {
			// ... Use conn to send and receive messages.
		})
		if err != nil {
			fmt.Println(err)
		}
	})

	app.Listen(3000)
}

```
