### ISSUE TITLE
QueryParser does not parse value of nested key query params

### ISSUE THREAD

**Issue by ansidev** [gofiber/fiber#1412]
**Fiber version**: 2.13.0

**Issue description**: QueryParser does not parse value of nested key query params

**Code snippet**

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

// Field names should start with an uppercase letter
type Person struct {
	Name     string   `query:"p.name"`
	Pass     string   `query:"p.pass"`
	Products []string `query:"p.products"`
}

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		p := new(Person)

		if err := c.QueryParser(p); err != nil {
			return err
		}

		log.Println(p.Name)     // john
		log.Println(p.Pass)     // doe
		log.Println(p.Products) // [shoe, hat]

		return c.SendStatus(fiber.StatusOK)
	})

	app.Listen(":3000")
}
```

**Reproduce steps**

- Start Fiber app
- Run `curl "http://localhost:3000/?p.name=john&p.pass=doe&p.products=shoe,hat"`
- Check Fiber app log.

**Expected logs**

```
2021/06/28 17:46:26 john
2021/06/28 17:46:26 doe
2021/06/28 17:46:26 [shoe,hat]
```

**Actual logs**

```
2021/06/28 17:46:26 
2021/06/28 17:46:26 
2021/06/28 17:46:26 []
```

If you replace log lines by following code snippets:
```go
log.Println(c.Query("p.name"))     // john
log.Println(c.Query("p.pass"))     // doe
log.Println(c.Query("p.products")) // [shoe, hat]
```
you will see expected logs.

**Comment by ReneWerner87** [comment]
a dot in the key is a separator for a new struct, this leads to the need to create a deep struct as well

```go
package main

import (
    "log"

    "github.com/gofiber/fiber/v2"
)

type DeepUrl struct {
    Person *Person `query:"p"`
}
// Field names should start with an uppercase letter
type Person struct {
    Name     string   `query:"name"`
    Pass     string   `query:"pass"`
    Products []string `query:"products"`
}

func main() {
    app := fiber.New()

    app.Get("/", func(c *fiber.Ctx) error {
        d := new(DeepUrl)

        if err := c.QueryParser(d); err != nil {
            return err
        }

        log.Println(d.Person.Name)     // john
        log.Println(d.Person.Pass)     // doe
        log.Println(d.Person.Products) // [shoe, hat]

        return c.SendStatus(fiber.StatusOK)
    })

    app.Listen(":3000")
}

```

**Comment by ReneWerner87** [comment]
https://github.com/gorilla/schema/blob/8285576f31afd6804df356a38883f4fa05014373/cache.go#L53

**Comment by ansidev** [comment]
@ReneWerner87 Sometime, we don't need to make it complicated.

As I mentioned, if we use: `c.Query(queryParam)`, everything is OK.

How do you think about supporting the following syntax:

`c.QueryParser(out interface{}, flatKey bool)`

=> `c.QueryParser(p, true)`

**FYI**

A Real world use case for this issue: https://developers.strava.com/docs/webhooks/

(Example request: `GET https://mycallbackurl.com?hub.verify_token=STRAVA&hub.challenge=15f7d1a91c1f40f8a748fd134752feb3&hub.mode=subscribe`)

**Comment by ReneWerner87** [comment]
hmm, i think this switch is not possible in our solution, because the delimiter cannot be disabled or configured in the gorilla schema parser
