### ISSUE TITLE
🤗  QueryParser : is it possible to set default value to nil if value is empty string

### ISSUE THREAD

**Issue by mininoz** [gofiber/fiber#1413]
fiber : v2.12.0
### Code snippet

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

type Product struct {
	Price    *int `query:"price"`
	Quantity *int `query:"quantity"`
}

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		p := new(Product)

		if err := c.QueryParser(p); err != nil {
			return err
		}

		log.Println(p.Price) // 0
		log.Println(p.Quantity) // 10

		return c.SendStatus(fiber.StatusOK)
	})

	app.Listen("3000")
}

```

I would like the default value  of **price** to be **nil** instead of **0**  when I use QueryParser

the request is 
http://localhost:3000/?price=&quantity=10

Is it possible to do it with QueryParser?

the purpose of this for searching
I want to ignore the field if it is empty string but be able to search for zero value.

**Comment by goldwind-ting** [comment]
Converting `*int` to `interface{}` type can solve this.

**Comment by ReneWerner87** [comment]
think that should be this issue
https://github.com/gorilla/schema/issues/161

can you write your findings in the ticket and help with the solution if necessary, once it is in the master of the library, i can take it over
