### ISSUE TITLE
🚀 add Fiber to OpenTelemetry repo

### ISSUE THREAD

**Issue by WLun001** [gofiber/fiber#1416]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
someone with [OpenTelemetry](https://opentelemetry.io/) experience please help add Fiber to the list [opentelemetry-go-contrib/instrumentation](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation)

**Comment by ReneWerner87** [comment]
please do this and create a pull request in the other repository

**Comment by ReneWerner87** [comment]
@WLun001  could you create a PR for fiber
https://github.com/open-telemetry/opentelemetry-go-contrib/pulls?q=is%3Apr+fiber

**Comment by WLun001** [comment]
@ReneWerner87 I try to work on it this weekend

**Comment by ReneWerner87** [comment]
thx

**Comment by WLun001** [comment]
will close when https://github.com/open-telemetry/opentelemetry-go-contrib/pull/880 is merged

**Comment by ReneWerner87** [comment]
@WLun001  could you check the PR again

**Comment by WLun001** [comment]
@ReneWerner87 Still pending approval from others

**Comment by ReneWerner87** [comment]
Ok

**Comment by ReneWerner87** [comment]
@WLun001 can you update the pull request again and make sure that all annotations are resolved, if necessary also ping the reviewers to speed up the whole process?

**Comment by WLun001** [comment]
@ReneWerner87 I have resolved all comments, will ping the reviewers

**Comment by ReneWerner87** [comment]
thx

**Comment by WLun001** [comment]
@ReneWerner87 the PR will not be accepted, see https://github.com/open-telemetry/opentelemetry-go-contrib/issues/1100
