### ISSUE TITLE
Invalid Handler(switch from tailwind to fiber)

### ISSUE THREAD

**Issue by klikpaspor** [gofiber/fiber#1417]
**Question**
This is example documentation [github.com/gotailwindcss/tailwind](url) :
```
import "github.com/gotailwindcss/tailwind/twembed"
import "github.com/gotailwindcss/tailwind/twhandler"

func main() {
	mux := http.NewServeMux()
	mux.Handle("/", http.FileServer(http.Dir("static")))
	mux.Handle("/css/", twhandler.New(http.Dir("css"), "/css", twembed.New()))

	s := &http.Server{Addr: ":8182", Handler: mux}
	log.Fatal(s.ListenAndServe())
}
```
I'm change mux to fiber, but i got this error : `panic: use: invalid handler *twhandler.Handler` and the error come from this code : `router.Use("/style/css/signin", twhandler.New(http.Dir("css"), "/css", twembed.New()))`

**Code snippet** :

```go
package main

import (
	"net/http"

	"github.com/gofiber/fiber/v2"
	"github.com/gotailwindcss/tailwind/twembed"
	"github.com/gotailwindcss/tailwind/twhandler"
	"klikpaspor.com/BeData/route"
)

func main() {
	app := route.App(fiber.Config{
		ServerHeader:  "Klikpaspor",
		StrictRouting: false,
		CaseSensitive: false,
	})
	router := route.Router{App: app}
	router.Root("./template")
	router.Use("/style/css/signin", twhandler.New(http.Dir("/style/css"), "/style/css", twembed.New()))
	router.Static("./template", "/signin", fiber.Static{
		Browse:   false,
		Compress: true,
	})
	app.Listen(":8080")
}
```

Thank you

**Comment by ReneWerner87** [comment]
```go
twhandler.New(http.Dir("/style/css"), "/style/css", twembed.New())
```
this kind of handler is not compatible to fiber

this is our handler definition
https://github.com/gofiber/fiber/blob/master/app.go#L40
```go
func(*Ctx) error
```

instead of the twhandler, you can use our filesystem middleware
https://github.com/gofiber/fiber/tree/master/middleware/filesystem
https://docs.gofiber.io/api/middleware/filesystem

**Comment by klikpaspor** [comment]
@ReneWerner87 thank you for your answer :+1:

**Comment by klikpaspor** [comment]
@ReneWerner87 thank you for your answer :+1:
