### ISSUE TITLE
🤗 How to manage/log template errors in fiber

### ISSUE THREAD

**Issue by Koredeoluwafemi** [gofiber/fiber#1420]
I am getting these template errors on production app

1. gob: decoding into local type *map[string]interface {}, received remote type unknown type,

2. extra data in buffer,

3. gob: encoded unsigned integer out of range

I use fiber.Map interface type in passing data from the handler to the template. 

I am unable to replicate the issue, it just shows up once in a while.

**Comment by ReneWerner87** [comment]
Gob is used in the session middleware, please share the code for your usage with this here.

**Comment by Koredeoluwafemi** [comment]
Here is an example of my handler

    func Users(c *fiber.Ctx) error {

	db := database.DB
	session, _ := sess.Store.Get(c) // get/create new session

	var users []models.User

	notify := controllers.GetNotify(session)

	db.Find(&users)
	
	output := fiber.Map{
		"Title":     config.App.Name + ": Manage Users",
		"Notify":    notify,
		//"Admin":     admin,
		"Users":     users,
	}

	_ = session.Save()
	return c.Render("users/users", output)
}

**Comment by Koredeoluwafemi** [comment]
@ReneWerner87

**Comment by Koredeoluwafemi** [comment]
Or can you share a pointer to how I can correct or fix it @ReneWerner87

**Comment by ReneWerner87** [comment]
no unfortunately not yet, have the cause of the problem unfortunately not yet found

the report #1419 should have the same cause

not sure where the problem with the gob encoder/decode is at the moment

**Comment by ReneWerner87** [comment]
```go
	"Notify":    notify,
	//"Admin":     admin,
	"Users":     users,
```
Just see that you use some structs, have you registered them ?
![image](https://user-images.githubusercontent.com/7063188/124481661-d1db8180-dda8-11eb-9ec3-01a0bdd6293d.png)
https://github.com/gofiber/fiber/tree/master/middleware/session

f.e.: https://github.com/gofiber/fiber/blob/master/middleware/session/session_test.go#L126
so that the session middleware can pass this information to gob and gob knows how to encode and decode it ?

**Comment by ReneWerner87** [comment]
the question is also what you save in the session

**Comment by Koredeoluwafemi** [comment]
So I run a series of tests and discovered I am getting error while trying to get or set a new session


    func Login(c *fiber.Ctx) error {

	session, err := sess.Store.Get(c) // get/create new session
	if err != nil {
		log.Println("login error")
		log.Println(err.Error())
		return err
	}
	
I am getting *unexpected EOF*. How I test is I logout and login repeatedly on my machine, after like 6 times, it brings up that error. @ReneWerner87

**Comment by Koredeoluwafemi** [comment]
> ```go
> 	"Notify":    notify,
> 	//"Admin":     admin,
> 	"Users":     users,
> ```
> 
> Just see that you use some structs, have you registered them ?
> ![image](https://user-images.githubusercontent.com/7063188/124481661-d1db8180-dda8-11eb-9ec3-01a0bdd6293d.png)
> https://github.com/gofiber/fiber/tree/master/middleware/session
> 
> f.e.:
> https://github.com/gofiber/fiber/blob/master/middleware/session/session_test.go#L126
> https://github.com/gofiber/recipes/blob/master/csrf/routes/mainServer.go#L35
> 
> so that the session middleware can pass this information to gob and gob knows how to encode and decode it ?

Yes I registered all my structs @ReneWerner87

**Comment by ReneWerner87** [comment]
@Koredeoluwafemi could you test it again with commit https://github.com/gofiber/fiber/commit/cd802dfeadcf2579123eafe5b680fdad1bc0a5f7
`cd802dfeadcf2579123eafe5b680fdad1bc0a5f7`

https://jfrog.com/blog/go-big-with-pseudo-versions-and-gocenter/

**Comment by ReneWerner87** [comment]
@Koredeoluwafemi are you still getting errors ?
