### ISSUE TITLE
🚀 Could add a requestId tag in logger middleware? like TagRequestId?

### ISSUE THREAD

**Issue by goldwind-ting** [gofiber/fiber#1422]
```
package main
import (
     "github.com/natefinch/lumberjack"
     "github.com/gofiber/fiber/v2"
     "github.com/gofiber/fiber/v2/middleware/logger"
)
app := fiber.New()
app.Use(requestid.New())
app.Use(logger.New(
logger.Config{
        Output: &lumberjack.Logger{
        Filename:   "./foo.log", 
        MaxSize:    1, 
        MaxBackups: 3, 
        MaxAge:     7, 
        Compress:   true,
        },
        Format: "[${time}] ${status}  ${latency} ${path} ${requestId} ${queryParams} ${body} ${resBody}\n",
}))
```

I use a RequestId middleware and that set a response header, but how could I get this header (default X-Request-Id) and record it in log file?

**Comment by ReneWerner87** [comment]
Please add a description

**Comment by ReneWerner87** [comment]
you could use 

${header:x-request-id} in the log message

https://github.com/gofiber/fiber/tree/master/middleware/logger
![image](https://user-images.githubusercontent.com/7063188/124480901-0864cc80-dda8-11eb-9f7c-3b9b7958e268.png)

**Comment by goldwind-ting** [comment]
it does not work. and when using ${header:x-request-id} in the log message, then c.Get is called,  it means that the x-request-id header is getted from request header, but x-request-id is a response header.
```
func (c *Ctx) Get(key string, defaultValue ...string) string {
	return defaultString(c.app.getString(c.fasthttp.Request.Header.Peek(key)), defaultValue)
}
```

**Comment by ReneWerner87** [comment]
okay, then we should either allow more prefixes like response or request

or add a possibility to define in its own placeholder with function 


i.e. your request is not possible with the current implementation

pull requests are welcome

**Comment by goldwind-ting** [comment]
It can get x-request-id by `c.Response().Header.Peek("X-Request-Id")`,but there is no tag that could get response header

**Comment by goldwind-ting** [comment]
> okay, then we should either allow more prefixes like response or request
> 
> or add a possibility to define in its own placeholder with function
> 
> i.e. your request is not possible with the current implementation
> 
> pull requests are welcome

Thank you very much!

**Comment by dpcks666** [comment]
How about this format?
${locals:requestid}

**Comment by goldwind-ting** [comment]
> How about this format?
> ${locals:requestid}
Could this format is compatible for request header or response header?How about ${reqHeader:xxx} and ${respHeader:xxx}? i.e. ${respHeader:x-request-id}.

**Comment by sali2801** [comment]
> How about this format? ${locals:requestid}

this one is confusing to me, because it is not set in `locals`

**Comment by sali2801** [comment]
> It can get x-request-id by `c.Response().Header.Peek("X-Request-Id")`,but there is no tag that could get response header

it seems to be working , as it renders at different id for every request. However, the format is weired something like `"[87 102 31 101 55 101]".` How to decode this

**Comment by ReneWerner87** [comment]
This is a byteslice
Just convert it to a string
