### ISSUE TITLE
🤗 How can I send a struct with c.Locals?

### ISSUE THREAD

**Issue by anthonycook** [gofiber/fiber#1430]
**Question description**

I want to pass a struct from my middleware to my routes using c.Locals as recommended by the docs, but I can't access the struct fields as it returns an interface? 

**Code snippet** _Optional_

```go
type User struct {
    FirstName string
    LastName string
}


// Middleware
func Auth(c *fiber.Ctx) error {
     u := User{}
    
     c.Locals("user", u)
     return c.Next()
}

// Route

func Home(c *fiber.Ctx) error {
    user := c.Locals("user")

    fmt.Println(user.FirstName) 
    // ERROR: user.FirstName undefined (type interface{} has no field or method FirstName) 
    // compilerMissingFieldOrMethod

}
```

**Comment by ReneWerner87** [comment]
https://goruncode.com/convert-from-interface-to-concrete-type/

You could use type casting.

**Comment by anthonycook** [comment]
> https://goruncode.com/convert-from-interface-to-concrete-type/
> 
> You could use type casting.

Type casting is exactly what I was after, thank you!
