### ISSUE TITLE
Why is TLS 1.2 hard-coded by `ListenTLS`?

### ISSUE THREAD

**Issue by solo-fish** [gofiber/fiber#1434]
### **Question description**
Why is TLS 1.2 hard-coded by [`ListenTLS`](https://github.com/gofiber/fiber/blob/cd802dfeadcf2579123eafe5b680fdad1bc0a5f7/app.go#L678-L684)?

I was wrapping up a template for TLS 1.3 using fiber, while migrating from `*http.ListenAndServeTLS` to `app.ListenTLS` I noticed there was no argument for the `tls.Config`, upon inspecting the function I noticed the config is hard coded inside the function. 

Here is what the hard-coded config looks like (see [`ListenTLS`](https://github.com/gofiber/fiber/blob/cd802dfeadcf2579123eafe5b680fdad1bc0a5f7/app.go#L678-L684))
```
		config := &tls.Config{
			MinVersion:               tls.VersionTLS12,
			PreferServerCipherSuites: true,
			Certificates: []tls.Certificate{
				cert,
			},
		}
```

- - -

### Fix
Either the best or worst fix depending on how you view it would be simply change the arguments of `app.ListenTLS` to accept `tls.Config`. Of course we would break lots of downstream consumers in the process in exchange for TLS 1.3 support, While I don't think this approach is a good idea, I do hold the opinion that users should be controlling their own TLS configs.

A realistic fix would copy `app.ListenTLS` to a new function I'll arbitrarily call it `ListenTLSC` for example. `ListenTLSC` should now take in the additional param `tls.Config` thus enabling a TLS 1.3. Then to remove redundant code from `ListenTLS` it should be modified to solely call `ListenTLSC` passing in both its arguments and the hard-coded TLS 1.2 config that exists at the moment. A poor-mans overloaded method of sorts - Still not clean at all but avoids breaking backwards compatibility and allows TLS 1.3 to exist.

Other thoughts? I have not contributed so likely missing useful context and insight - for all I know this is a very intentional decision to hardcode TLS 1.2 configuration

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/1077
