### ISSUE TITLE
🐛 Examples on front page don't work 

### ISSUE THREAD

**Issue by kobenauf** [gofiber/fiber#1436]
**Fiber version**
2.14.0

**Issue description**
The fiber home page shows an example with several routes.  The first two routes work, but everything else is intercepted by them.

**Code snippet**

```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	// GET /john
	app.Get("/:name", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("Hello, %s 👋!", c.Params("name"))
		return c.SendString(msg) // => Hello john 👋!
	})

	// GET /john/75
	app.Get("/:name/:age", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("👴 %s is %s years old", c.Params("name"), c.Params("age"))
		return c.SendString(msg) // => 👴 john is 75 years old
	})

	// GET /dictionary.txt
	app.Get("/:file.:ext", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("📃 %s.%s", c.Params("file"), c.Params("ext"))
		return c.SendString(msg) // => 📃 dictionary.txt
	})

	// GET /flights/LAX-SFO
	app.Get("/flights/:from-:to", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("💸 From: %s, To: %s", c.Params("from"), c.Params("to"))
		return c.SendString(msg) // => 💸 From: LAX, To: SFO
	})

	// GET /api/register
	app.Get("/api/*", func(c *fiber.Ctx) error {
		msg := fmt.Sprintf("✋ %s", c.Params("*"))
		return c.SendString(msg) // => ✋ register
	})

	log.Fatal(app.Listen(":3000"))
}
```
** Steps to reproduce **
1. Run code above.
2. RIGHT
curl localhost:3000/john
Hello, john 👋!
3. RIGHT
curl localhost:3000/john/30
 john is 30 years old
 4. WRONG
 curl localhost:3000/dictionary.txt
 Hello, dictionary.txt 👋!
 5. WRONG
 curl localhost:3000/flights/LAX-SFO
👴 flights is LAX-SFO years old

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/1090#issuecomment-751335790

Can you please look at the answer from this article, I answered an equivalent question there.

Where do I find this example, is that copied together from several documentation articles or is that directly somewhere? 
Then I would want to change it, because as described in the linked article, the order is decisive.

**Comment by kobenauf** [comment]
That is the exact issue you already answered.  The example is in the project's [README.md](https://github.com/gofiber/fiber#readme).

**Comment by ReneWerner87** [comment]
Thanks for the hint, i will update this example in the next days.

**Comment by ReneWerner87** [comment]
fix https://github.com/gofiber/fiber/commit/c8d0a0c2ae30f87b3a3939a93fd61f83aaf3dbfa
