### ISSUE TITLE
🤗 can logger create different log files according to the date

### ISSUE THREAD

**Issue by jhhuang2000** [gofiber/fiber#1437]
Excuse me, can logger create different log files according to the date. For example, 2021-01-02.log, 2021-01-03.log
thank you

**Comment by ReneWerner87** [comment]
no that is not possible yet, but you can create pull requests for it.

**Comment by goldwind-ting** [comment]
> Excuse me, can logger create different log files according to the date. For example, 2021-01-02.log, 2021-01-03.log
> thank you

You could use logger middleware and change Output config to lumberjack.Logger, the lib lumberjack.Logger can split log file automaticly.

**Comment by jhhuang2000** [comment]
Thank you all
