### ISSUE TITLE
🐛 Custom error handler not working for a mounted app instance

### ISSUE THREAD

**Issue by seamons** [gofiber/fiber#1438]
**Fiber version**

v2.14.0

**Issue description**

I'm creating a sub App instance with a custom error handler, then mount it to the main App instance. I found the custom error handler for the sub App instance is not effective.

I know this may not be a programming bug, but it seems like an unexpected behavior to me.

Also, i believe resolving this issue will help to address the following use case:
Imaging I have an HTTP service (main App instance) with two sub App instances, one for public API access and one for private API access. I'd like to custom different error handling for each instance, for example, outputting error logs to different targets. 

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

// Custom error handler.
func apiErrorHandler = func(c *fiber.Ctx, err error) error {
    // Custom error handling logic here.
    // ...

    // Return from handler
    return nil
}

func main() {
  app := fiber.New()

  // Steps to reproduce  
  api := fiber.New(fiber.Config{
    ErrorHandler: apiErrorHandler,
  })
  
  app.Mount("/api", api)

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by AliasT** [comment]
```go
// may be error middleware on api ?
api.Use(someErrorMiddleware)
```

**Comment by seamons** [comment]
@AliasT Thanks for your advice, but i think middleware is incapable of catching and overriding error from the framework, for example, overriding the default plaintext 404 path not found error response to a json response.

**Comment by ReneWerner87** [comment]
via mount we only copy the routes and handlers, but not the settings of the app.

**Comment by josebalius** [comment]
I've opened a PR #1560 to solve this.
