### ISSUE TITLE
🚀 generic Skip middleware

### ISSUE THREAD

**Issue by andrascz** [gofiber/fiber#1440]
**Is your feature request related to a problem?**

The current middlewares are all need to be configured with a Next predicate to skip the middleware. I think it could be more flexible to provide a `Skip` middleware which can wrap a middleware and based on a predicate skip it. This way specific middlewares do not need to implement this feature.
Somewhat related is that the middlewares are not implementing the skip efficiently:

```go
// Return new handler
return func(c *fiber.Ctx) (err error) {
  // Don't execute middleware if Next returns true
  if cfg.Next != nil && cfg.Next(c) {
	  return c.Next()
  }
  // do middleware stuff...
  return nil
}
```

This could be done instead:
```go
mw := func(c *fiber.Ctx) (err error) {
  // do middleware stuff
  return nil
}

// Return new handler
if c.Next == nil {
  return mw
}

return func(c *fiber.Ctx) (err error) {
  // Don't execute middleware if Next returns true
  if cfg.Next(c) {
	  return c.Next()
  }
  return mw(c)
}
```

**Describe the solution you'd like**

```go
package middleware

import "github.com/gofiber/fiber/v2"

// Skip skips handler if the exclude predicate returns true.
func Skip(handler fiber.Handler, exclude func(c *fiber.Ctx) bool) fiber.Handler {
	if exclude == nil {
		return handler
	}

	return func(c *fiber.Ctx) error {
		if exclude(c) {
			return c.Next()
		}

		return handler(c)
	}
}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by ReneWerner87** [comment]
good idea could be made.

what do you think ?
@gofiber/maintainers @gofiber/contributors

**Comment by WLun001** [comment]
what if only want to skip specific middlewares?

**Comment by andrascz** [comment]
> what if only want to skip specific middlewares?

Usage:
```go
app := fiber.New()
app.Use(Skip(myMiddleware, func(*fiber.Ctx) bool { return true }))
```

So it naturally skips only the middleware you wrap.

**Comment by WLun001** [comment]
@andrascz thanks for the usage example. I think is a great one

**Comment by ReneWerner87** [comment]
can you create a pull request for it ?

**Comment by andrascz** [comment]
Sure, I will.
