### ISSUE TITLE
🚀 unit test example on handler

### ISSUE THREAD

**Issue by Tonghua-Li** [gofiber/fiber#1443]
**Is your feature request related to a problem?**
No
**Describe the solution you'd like**
How to do the unit test on handler without creating fiber.App, because creating fiber.App in api_test.go will cause circular dependency
https://github.com/gofiber/recipes/blob/master/jwt/handler/api.go#L6

**Describe alternatives you've considered**
NA
**Additional context**

**Comment by ReneWerner87** [comment]
please check https://github.com/gofiber/recipes/blob/master/unit-test/main_test.go#L50-L61
and
https://docs.gofiber.io/api/app#test
