### ISSUE TITLE
Is fiber 100% 0 memory allocated?

### ISSUE THREAD

**Issue by superdolt** [gofiber/fiber#1445]
Is fiber 100% 0 memory allocated?

totally no memory allocated?

**Comment by ReneWerner87** [comment]
No, sometimes it is necessary to allocate memory for actions.
But in Fiber core we try to reduce it everywhere.
in some middlewares we have to try again and reduce the number, but overall it looks quite good.

you can see the resulting speeds in the benchmarks in techempower.

**Comment by hiqsociety** [comment]
is it possible to have 100% 0 memory allocation for fiber?

**Comment by ReneWerner87** [comment]
We are almost everywhere completely allocation free. If you find allocations in the core you are welcome to open a pull request and support us with it.
