### ISSUE TITLE
Can c.Params("name") convert "%20" to normal empty string?

### ISSUE THREAD

**Issue by buffalus** [gofiber/fiber#1450]
**Question description**

It seems c.Params("value") cannot convert "%20" to normal empty string?

For example, GET http://localhost:8080/hello%20world

With c.Params("name"), I expect to get "hello world", but in fact, I still get "hello%20world".

Can anyone help?

**Comment by IGLOU-EU** [comment]
Hi,
you can use `url.QueryUnescape` in `net/url` golang lib :)

**Comment by buffalus** [comment]
> Hi,
> you can use `url.QueryUnescape` in `net/url` golang lib :)
> https://pkg.go.dev/net/url#QueryUnescape

Using url.QueryUnescape is a good solution. Thank you !

But when using c.Query("name"), I can get "hello world" as expected. Is it possible c.Params("name") do the same way?

Thanks!

**Comment by IGLOU-EU** [comment]
Not sure, but, `c.Query` is for URL query every time in URL encoded format, so he has an implicit decode. While `c.Params` is used for routing only, may be URL path can be sending unencoded :thinking: 

@Fenny can probably tell why

**Comment by ReneWerner87** [comment]
yes we could, but we currently use the string of the original route in the Params method

**Comment by buffalus** [comment]
Noted and thanks !
