### ISSUE TITLE
🐛 The escape of special characters in route path does not work properly

### ISSUE THREAD

**Issue by decker502** [gofiber/fiber#1454]
**Fiber version**
v2.15.0

**Issue description**

The escape of special characters in route path does not work properly

**Code snippet**

```go
package routes

import (
	"fmt"
	"io/ioutil"
	"net/http/httptest"
	"testing"

	"github.com/gofiber/fiber/v2"
)

func TestEscaped(t *testing.T) {
	// Define Fiber config.
	config := fiber.Config{}

	// Define a new Fiber app with config.
	app := fiber.New(config)
	// Create route with GET method for test:
	app.Get("/v1/some/resource/name\\:customVerb", func(c *fiber.Ctx) error {
		return c.SendString("hello, customVerb!")
	})
	// http.Request
	req := httptest.NewRequest("GET", "/v1/some/resource/name:customVerb", nil)

	// http.Response
	resp, err := app.Test(req)
	if err != nil {
		t.Error(err)

	}

	// Do something with results:
	if resp.StatusCode == 200 {
		body, _ := ioutil.ReadAll(resp.Body)
		fmt.Println(string(body)) // => hello, customVerb!
	}
	if resp.StatusCode != 200 {
		t.Error(resp.StatusCode)

	}
}

```

**Comment by IGLOU-EU** [comment]
Hi,
url encoded `%5C` ?

**Comment by decker502** [comment]
> Hi,
> url encoded `%3A` ?

It's same

**Comment by ReneWerner87** [comment]
thanks for the error report, you are right, had forgotten a part at that time

we have in addition to the complex routing parsing with the parameters, also a simple matching via string comparison if no parameter is in this route, this part does not work yet with the escape stuff

**Comment by ReneWerner87** [comment]
this should be the fix
![image](https://user-images.githubusercontent.com/7063188/127335008-23b58acd-c364-4c4d-a19a-82d18afa1375.png)


but i have to test it carefully

**Comment by decker502** [comment]
nice, thanks so much
