### ISSUE TITLE
🐛 context.Query function alway change string value unexpected

### ISSUE THREAD

**Issue by loveuer** [gofiber/fiber#1455]
**Fiber version**
v2.15.0
**Issue description**
with context.Query function, the string value will change
**Code snippet**

```go
package main

import (
	"got/common/tool"
	"log"
	"sync"
	"github.com/gofiber/fiber/v2"
	"github.com/gin-gonic/gin"
)

type UMap struct {
	sync.Mutex
	Map map[string]string
}

func (um *UMap) Get(key string) string {
	val, ok := um.Map[key]
	if !ok {
		return ""
	}

	return val
}

func (um *UMap) Set(key, val string) {
	um.Lock()
	defer um.Unlock()

	um.Map[key] = val
}

var (
	umap = &UMap{Map: make(map[string]string)}
)

func main() {
	f()
}

func f() {
	app := fiber.New()

	app.Get("/demo", func(c *fiber.Ctx) error {
		token := c.Query("token")
		if token != "" {
			cookie := tool.RandStr(32)
			umap.Set(cookie, token)
			log.Printf("now map: %+v", umap.Map)
			return c.JSON(umap.Map)
		}

		log.Printf("then map: %+v", umap.Map)
		return c.JSON(umap.Map)
	})

	app.Listen(":8080")
}

func g() {
	app := gin.Default()

	app.GET("/demo", func(c *gin.Context) {
		token := c.Query("token")
		if token != "" {
			cookie := tool.RandStr(32)
			umap.Set(cookie, token)
			log.Printf("now map: %+v", umap.Map)
			c.JSON(200, umap.Map)
			return
		}

		log.Printf("then map: %+v", umap.Map)
		c.JSON(200, umap.Map)
	})

	app.Run(":8080")
}

```
- with the first req: http://localhost:8080/demo?token=nice, the logger with print the map: 
```go
map[c1h1gGp869GYLYGsZF8eAkqEo9qJj0CI:nice]
```
- and then second req: http://localhost:8080/demo?stuff=true, the logger with print: 
```go
map[c1h1gGp869GYLYGsZF8eAkqEo9qJj0CI:true]
```
- this almost 100% happens
- as you can see in the snippet, I also tried with gin, but this not happened with gin

**Comment by iCyberon** [comment]
@loveuer from the docs:

> Returned value is only valid within the handler. Do not store any references. Make copies or use the Immutable setting instead.

Instead of storing the token directly, make a copy using `utils.ImmutableString` and set the copied value.

```
app.Get("/demo", func(c *fiber.Ctx) error {
    token := c.Query("token")
    if token != "" {
        cookie := tool.RandStr(32)
        umap.Set(cookie, utils.ImmutableString(token))
        log.Printf("now map: %+v", umap.Map)
        return c.JSON(umap.Map)
    }

    log.Printf("then map: %+v", umap.Map)
    return c.JSON(umap.Map)
})
```

**Comment by ReneWerner87** [comment]
exactly, since we want to keep the allocations as small as possible, we use the allocation of the string with the unsafe feature

so you have to copy the value with the immutable string function

this behavior is expected and tolerated, because this way you can achieve enormous speed

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/127336276-90f9340e-391c-4c2e-ac0d-10919436e6bb.png)
https://docs.gofiber.io/#zero-allocation

**Comment by loveuer** [comment]
@ReneWerner87 thanks a lot ☺
