### ISSUE TITLE
Setting app.Server().MaxConnsPerIP🐛 

### ISSUE THREAD

**Issue by NathanBarta** [gofiber/fiber#1456]
**Fiber version**
v2.15.0
**Issue description**
Setting app.Server().MaxConnsPerIP() = x
either causes the server to use http instead of https/tls, or it causes c.Secure() and c.Protocol() to give false information.
This could also simply be by design. If so, it should be made less transparent to users. 
**Code snippet**

```go
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/gofiber/fiber/v2"
)

func main() {
	rootDir, err := filepath.Abs(filepath.Dir(os.Args[0]))
	if err != nil {
		panic("rootdir not found")
	}

	app := fiber.New(fiber.Config{
		EnableTrustedProxyCheck: true,
		Network:                 "tcp4", //Observation: specifing tcp makes the listener on https://[::]:443, and tcp4 makes 127.0.0.1:443
		Prefork:                 false,
	})

	// app.Server().MaxConnsPerIP = 4

	app.Get("/", func(c *fiber.Ctx) error {
		//openssl s_client -connect localhost:443
		//c.Protocol gives http, even though it looks like https on wireshark, however I lack the testing abilities to know.
		//The bug could be either that the traffic is not using tls, or that the following functions are giving the wrong info.
		fmt.Println(c.Secure())
		return c.SendString(c.Protocol())
	})

	CA_certPath := filepath.Join(rootDir, "cert", "cert.pem")
	CA_keyPath := filepath.Join(rootDir, "cert", "key.pem")

	app.ListenTLS(":443", CA_certPath, CA_keyPath)
}
```

**Comment by tysg** [comment]
Is anyone working on this? If not, may I work on it? I'm investigating on the issue, and it could be an upstream error in `fasthttp`

**Comment by ReneWerner87** [comment]
I don't think anyone is working on this yet, you are welcome to do it.

**Comment by tysg** [comment]
Looks like it's an upstream issue in `fasthttp`. I've submitted an issue at https://github.com/valyala/fasthttp/issues/1062

**Comment by tysg** [comment]
The issue has since been fixed. Let's upgrade the `fasthttp` version when they make the next release :)

**Comment by ReneWerner87** [comment]
ok thx for the hint

**Comment by NathanBarta** [comment]
https://github.com/valyala/fasthttp/releases/tag/v1.29.0 new release has been made

Thank you @tysg for your investigation and solution!
