### ISSUE TITLE
🐛 AllowOrigins empty for custom URL(s) 

### ISSUE THREAD

**Issue by saiumesh-apty** [gofiber/fiber#1466]
v2.16.0

AllowOrigins (Access-Control-Allow-Origin) header is empty when using with custom URL but works fine when using with *

**Code snippet**

```go
func main() {

	app := fiber.New()

	app.Use(cors.New(cors.Config{
		AllowOrigins: "https://gofiber.io, https://gofiber.net, http://localhost:8084",
		AllowHeaders: "Origin, Content-Type, Accept",
	}))

	app.Get("/health", func(c *fiber.Ctx) error {
		return c.SendStatus(200)
	})

	launchError := app.Listen(helpers.GetStaticServerPort())
	if launchError != nil {
		log.Fatal(launchError.Error())
	}

}
```

![image](https://user-images.githubusercontent.com/35692863/127904645-2305e71d-c23b-47b1-aecf-1c087643b9de.png)

**Comment by ReneWerner87** [comment]
Can you please share all request header, have a hunch if my guess is right I would solve it tomorrow

**Comment by saiumesh-apty** [comment]
Hello, @ReneWerner87 Here's the Request Headers. Let me know if you need more info. Thanks. 

```cmd
GET /health HTTP/1.1
Host: localhost:8084
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Cookie: ajs_anonymous_id=%22f2b0c22e-8fd5-42dc-99d7-561bb632b41e%22
Upgrade-Insecure-Requests: 1
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Pragma: no-cache
Cache-Control: no-cache
```

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/127967379-80472968-6aff-4c91-9fe2-b6dc4fc12602.png)
Behavior is as expected, the browser does not send an Origin header when the request goes to the same domain, so no content is displayed there.

but if the origin header is sent, it will be displayed in the header if it is matched.

**Comment by ReneWerner87** [comment]
different domains:
![image](https://user-images.githubusercontent.com/7063188/127967621-57245b3e-bea8-4e46-9770-40736597ba2f.png)

same domain:
![image](https://user-images.githubusercontent.com/7063188/127967660-08c2e8f9-653b-4918-928d-540c6d9fe903.png)

**Comment by saiumesh-apty** [comment]
Hello, @ReneWerner87  That absolutely makes sense. Thanks for the response. I feel a bit dumb 😀
