### ISSUE TITLE
🚀 I want to use color in the custom logger middleware

### ISSUE THREAD

**Issue by FlameMida** [gofiber/fiber#1467]
**Is your feature request related to a problem?**
no
**Describe the solution you'd like**
make it export in config

**Comment by ReneWerner87** [comment]
just use the color tags
![image](https://user-images.githubusercontent.com/7063188/127966024-5ef2d15d-288e-4294-81d6-d96ad1bac6ac.png)

**Comment by FlameMida** [comment]
alright ~but i want to make my status code and method fields switch color automatically

**Comment by amalshaji** [comment]
The current configuration only enables colors if the format is not provided.

```go
if cfg.Format == "" && cfg.Output == nil {
        cfg.enableColors = true
}
```
replace the empty check by checking for variables that require color. 
```go
func validCustomFormat(format string) bool {
	var validTemplates = []string{"${status}", "${method}"}
	if format == "" {
		return true
	}
	for _, template := range validTemplates {
		if !strings.Contains(format, template) {
			return false
		}
	}
	return true
}

if validCustomFormat(cfg.Format) && cfg.Output == nil {
        cfg.enableColors = true
}
```

thoughts?

**Comment by ReneWerner87** [comment]
create a pull request and check the output in the unittest and as long as it's just cost of initialization and not on the normal performance of the requests, we can take care of it

**Comment by ReneWerner87** [comment]
will you create a pull request ? then i will assign the issue to you

**Comment by amalshaji** [comment]
yes
