### ISSUE TITLE
Parsing .png-files from the request body

### ISSUE THREAD

**Issue by StillRosi** [gofiber/fiber#1468]
Hey everybody,
I currently work on an API that, among other features, is able to receive and save images (which are sent by a POST request), to my local disk but I am facing problems with Fiber's `BodyParser`.

This is what the block looks like in my `create`-route.
```go
var postImages models.PostImages

err = ctx.BodyParser(&postImages)
if err != nil {
	log.Println(err)
	return ctx.Status(fiber.StatusBadRequest).JSON(&fiber.Map{
		"success": false,
		"message": fmt.Sprint(err),
	})
}
```
Whenever this is run however, `postImages` is empty `{()}` and there are no errors thrown whatsoever.

This is what `PostImages` looks like:
```go
type PostImages struct {
	Images []string `json:"images" bson:"images"`
}
```
I send the request using Postman and add the .png-files via a form-data field like so:

![image](https://user-images.githubusercontent.com/53474113/128222878-109eb9ef-e687-4935-8bd9-299589b07ff8.png)

Sadly, I was not able to find anything regarding my issue elsewhere, which is why I'd figure asking here.

Thanks in advance for any help!

**Comment by ReneWerner87** [comment]
Please check https://docs.gofiber.io/api/ctx#savefile or https://docs.gofiber.io/api/ctx#multipartform or https://docs.gofiber.io/api/ctx#formfile instead of bodyParser.

**Comment by StillRosi** [comment]
> Please check https://docs.gofiber.io/api/ctx#savefile or https://docs.gofiber.io/api/ctx#multipartform or https://docs.gofiber.io/api/ctx#formfile instead of bodyParser.

Thank you so much, works like a charm now!
