### ISSUE TITLE
Misrouting API request

### ISSUE THREAD

**Issue by alihanyalcin** [gofiber/fiber#1469]
**Question description**

When I send api request for both endpoints, Fiber always routes to first endpoint `/v1/:id`. 
```
$ curl -X GET "localhost:3000/v1/1
/:id -> 1
$ curl -X GET "localhost:3000/v1/test/?id=1"
/:id -> test
```
If I register the `/v1/test` endpoint above `/v1/:id`, the problem is gone.

What is the reason of this? 
How does work Fiber's router? 
Is this a bug or design decision?

**Code snippet** 
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	v1 := app.Group("/v1")

	v1.Get("/:id", func(ctx *fiber.Ctx) error {
		id := ctx.Params("id")
		return ctx.SendString("/:id -> " + id)
	})

	v1.Get("/test", func(ctx *fiber.Ctx) error {
		id := ctx.Query("id")
		return ctx.SendString("/test -> " + id)
	})

	log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
No error, this is an expected behavior, as with express routing we get the order of the registered routes and check them in the same order, i.e. a clear recommendation is to prioritize the specific ones over the less specific ones.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/1090#issuecomment-751335790

https://github.com/gofiber/fiber/issues/1088#issuecomment-750476089
