### ISSUE TITLE
Session & Store Middleware return error 🐛 

### ISSUE THREAD

**Issue by whoiscarlo** [gofiber/fiber#1473]
Going through the documentation and when I tried to set **sessionName** I receive this error:  `unknown field sessionName in struct literalcompilerMissingLitField`

There are multiple places where sessionName is being using and I don't understand how.
Store Test
https://github.com/gofiber/fiber/blob/9a7b08ee238331e1cfa743bff6bca6f168448ce2/middleware/session/store_test.go

Session Test
https://github.com/gofiber/fiber/blob/master/middleware/session/session_test.go

And on a separate note the documentation and this [GitBook](https://docs.gofiber.io/api/middleware/session) aren't always consistent.

**Comment by ReneWerner87** [comment]
@whoiscarlo can you give us an example ?

**Comment by melvinodsa** [comment]
@whoiscarlo `sessionName` is an unexported field in the same package. That is why it is accessible inside the package, but not outside. You can use `Get`, `Set` receiver functions of Store to store values in sessions
