### ISSUE TITLE
Conflicting documentation

### ISSUE THREAD

**Issue by onthegit** [gofiber/fiber#1476]
Hello,

first of all thanks for the project.

https://docs.gofiber.io/api/ctx

For SendFile it says:
Method use gzipping by default, set it to true to disable.

and then in the example below it says:
// Disable compression
  return c.SendFile("./static/index.html", false);

So which one is true?

Does sendfile use io.Copy? Because I need it for large files.

**Comment by ReneWerner87** [comment]
thx for the hint
https://github.com/gofiber/fiber/blob/master/ctx.go#L1029


i will change the wording

**Comment by ReneWerner87** [comment]
is https://github.com/gofiber/docs/commit/59491de085f6243babe330645e7d2da1a025f248 okay ?
