### ISSUE TITLE
🤗 How to set a custom HTTP proxy while using Proxy middleware?

### ISSUE THREAD

**Issue by jj0e** [gofiber/fiber#1479]
**Question description**
The word "proxy" is being used a lot here so it's a bit confusing, but I am using the [proxy middleware](https://github.com/gofiber/fiber/tree/master/middleware/proxy) in my API. My goal is to proxy the client request, but update the IP address that it's being sent from by setting a custom HTTP proxy. Is this possible via updating the `fiber.Ctx` or by using the middleware?

Or do I need to have the client set a proxy before sending the request?

My purpose for this is to prevent my server IP from being used in the request which could result in `429 Too Many Request Errors`

**Comment by WLun001** [comment]
Hi @jj0e m not exactly get what you mean

Here is the approach that you can use `proxy` in handler, more details example on [proxy middleware](https://github.com/gofiber/fiber/tree/master/middleware/proxy#examples)

```go

import (
   "github.com/gofiber/fiber/v2"
   "github.com/gofiber/fiber/v2/middleware/proxy"
)

app.Get("/", func (c *fiber.Ctx) error {
    return proxy.Do(c, "https://example.com")
 })
```
`curl localhost:3000` would gives you content from `example.com`

**Comment by jj0e** [comment]
> Hi @jj0e m not exactly get what you mean
> 
> Here is the approach that you can use `proxy` in handler, more details example on [proxy middleware](https://github.com/gofiber/fiber/tree/master/middleware/proxy#examples)
> 
> ```go
> import (
>    "github.com/gofiber/fiber/v2"
>    "github.com/gofiber/fiber/v2/middleware/proxy"
> )
> 
> app.Get("/", func (c *fiber.Ctx) error {
>     return proxy.Do(c, "https://example.com")
>  })
> ```
> 
> `curl localhost:3000` would gives you content from `example.com`

Hi yes I completely understand how the proxy middleware works. What I’m asking is whether or not it’s possible to set a custom HTTP proxy for this request. What does this mean?

Example.com will receive the request from my server, but what will the IP be? Will the IP be my server IP or the client who is accessing localhost:3000’s IP? Either or, is it possible to set an HTTP proxy to spoof the IP address that example.com receives?

**Comment by jj0e** [comment]
After further inspection, I realize this is not directly implemented but it is possible. I would be willing to create a PR for this. Is it necessary to convert this issue to a feature?

**Comment by jj0e** [comment]
#1480
