### ISSUE TITLE
🤗 Message Flashing with Gofiber 

### ISSUE THREAD

**Issue by vividsystem** [gofiber/fiber#1481]
I wanted to ask if there is a way(using Fiber) to flash messages for success alerts etc. Some example frameworks for that would be Bufalo(https://gobuffalo.io/en/docs/flash-messages) or Flask(Python). If thats not possible, I would like  to know how you could update the page content without reloading the page

**Comment by sujit-baniya** [comment]
@vividsystem  You can try this for flash message: https://github.com/sujit-baniya/flash

**Comment by vividsystem** [comment]
Ok, thank you @sujit-baniya. I'll try it out.
