### ISSUE TITLE
Gofiber.io site is blocked

### ISSUE THREAD

**Issue by harishdurga** [gofiber/fiber#1483]
**Why is Gofiber.io site is blocked in India**
![screenshot-nimbus-capture-2021 08 12-12_36_41](https://user-images.githubusercontent.com/10380630/129153239-7ad5ad07-e456-4f62-99fe-6c17d9584c07.png)

**Comment by ReneWerner87** [comment]
thank you for the advice

we have checked it and also had other colleagues test it, unfortunately we cannot reproduce it and if there really is a problem, we cannot fix it either.
