### ISSUE TITLE
🐛 Try create a middleware

### ISSUE THREAD

**Issue by marioidival** [gofiber/fiber#1484]
**Fiber version**
2.14.0
**Issue description**
What's problem with this code and why the fiber don't accept
 go run main.go server
panic: use: invalid handler func() func(*fiber.Ctx) error
**Code snippet**

```go
	fb.Use(func() fb.Handler {
		return func(c *fb.Ctx) error {
			userKey := c.Get("X-API-KEY")
			if userKey != APIKEY {
				return c.SendStatus(fb.StatusUnauthorized)
			}
			return c.Next()
		}
	})


```

**Comment by ReneWerner87** [comment]
Because the handler you pass to the use function does not have the right structure

I guess the function is supposed to be a builder function which builds a fiber handler, i.e. you have to execute the build by writing the brackets for a call after the last curly bracket

**Comment by TianLiangZhou** [comment]
```golang
	fb.Use(func() fb.Handler {
		return func(c *fb.Ctx) error {
			userKey := c.Get("X-API-KEY")
			if userKey != APIKEY {
				return c.SendStatus(fb.StatusUnauthorized)
			}
			return c.Next()
		}
	}())
```

**Comment by ReneWerner87** [comment]
@marioidival is it working, can i close you report ?

**Comment by marioidival** [comment]
@ReneWerner87 yep, maybe we need create a better docs regarding this way.

**Comment by ReneWerner87** [comment]
You are welcome to prepare a pull request for our documentation to make this case more understandable.
