### ISSUE TITLE
🐛 Static path with trailing slashes doesn't work!

### ISSUE THREAD

**Issue by imraan-go** [gofiber/fiber#1490]
**Fiber version**
v2.17.0
**Issue description**
Static path with trailing slashes does not work! When path ends with slash like /docs/ or docs/  , the path is not found!
**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
app.Static("/docs", "./docs/slate/build/") // -> http://localhost:3000/docs  Works.
app.Static("/docs/", "./docs/slate/build/") // -> http://localhost:3000/docs/ Doesn't work! 404 Not found



  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by IGLOU-EU** [comment]
Even if you try to force `StrictRouting` to false in Config struct ?
https://pkg.go.dev/github.com/gofiber/fiber/v2#Config

**Comment by imraan-go** [comment]
> Even if you try to force `StrictRouting` to false in Config struct ?
> https://pkg.go.dev/github.com/gofiber/fiber/v2#Config

`StrictRouting ` is false by default! This has nothing to do with strict routing. The problem is with Static method.  `app.Get("/products/", SearchProducts)` This works perfectly fine with default settings.I can browse http://localhost/products/ But `app.Static("/docs/", "./docs/slate/build/")`  shows 404 Not found.

**Comment by ReneWerner87** [comment]
could be that the error lies there

https://github.com/valyala/fasthttp/blob/master/fs.go#L978

**Comment by imraan-go** [comment]
This is not related to fasthttp. I just tried debugging it, looks like the handler does not get called at all in `registerStatic` handler varible. So seems like fiber is unable to set the router properly when static path ends with slashes.

**Comment by fufuok** [comment]
May be fixed by #1538

**Comment by fufuok** [comment]
![image](https://user-images.githubusercontent.com/4979407/135624471-ffcf15c1-8c88-40d9-8d0a-b5177af5954c.png)

![image](https://user-images.githubusercontent.com/4979407/135624511-eb4bf1a9-a6fd-45e1-8a8e-75b8c7d035b0.png)

![image](https://user-images.githubusercontent.com/4979407/135624547-cd06b451-f3b7-40ba-9131-b51a5a859d3d.png)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	app.Static("/web", "./web")
	app.Listen(":3000")
}
```

**go.mod**
```go
module tmp_static_web

go 1.15

require github.com/gofiber/fiber/v2 v2.19.1-0.20211001105148-b94870d8865b
```

[tmp_static_web.211001.zip](https://github.com/gofiber/fiber/files/7267360/tmp_static_web.211001.zip)

**Comment by fufuok** [comment]
If you want to use trailing slash to register static file routing, then you may need such modification.

@ReneWerner87 if necessary, I can PR.

![image](https://user-images.githubusercontent.com/4979407/135636776-9a55200e-9337-4468-b3b2-5a3cf0aee188.png)

**demo**

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	app.Static("/static", "./public", fiber.Static{
		Browse: true,
	})
	app.Static("/test_static/", "./public", fiber.Static{
		Browse: true,
	})
	app.Static("/web", "./public/web")
	app.Static("/test_web/", "./public/web")
	app.Listen(":3000")
}
```

**go.mod**

```go
module tmp_static_trailing_slash

go 1.15

require github.com/gofiber/fiber/v2 v2.19.0

replace github.com/gofiber/fiber/v2 v2.19.0 => github.com/fufuok/fiber/v2 v2.19.1-0.20211001150354-c126d46683c1
```

You can visit the following URL:
- http://127.0.0.1:3000/static
- http://127.0.0.1:3000/static/
- http://127.0.0.1:3000/test_static
- http://127.0.0.1:3000/test_static/
- http://127.0.0.1:3000/web
- http://127.0.0.1:3000/web/
- http://127.0.0.1:3000/test_web
- http://127.0.0.1:3000/test_web/


**demo code**

[tmp_static_trailing_slash_fixed.211001.zip](https://github.com/gofiber/fiber/files/7268235/tmp_static_trailing_slash_fixed.211001.zip)
