### ISSUE TITLE
🚀 Serialize response data based on `Accept` header

### ISSUE THREAD

**Issue by Hexiro** [gofiber/fiber#1494]
**Is your feature request related to a problem?**

In my experience, modern APIs usually return JSON data, but sometimes the end-user will want to use a different data type,
whether that's because of their language of choice or just personal preference.

**Describe the solution you'd like**

A method added to `fiber.Context` that serializes a `struct` / `map` based on the accept header from the client.
(similarly to `c.JSON()`)

**Describe alternatives you've considered**
 -  a middleware, which I don't believe is possible due to the chained nature of fiber middleware.
 -  a utility function, which would get very annoying, tedious, and potentially make the code harder to read.

**Additional context**
:)

**Comment by ReneWerner87** [comment]
what about the https://docs.gofiber.io/api/ctx#format method ?

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/master/ctx.go#L439-L454

**Comment by Hexiro** [comment]
oh cool! that looks like what i was looking for. is it possible to enable / disable certain types or add custom ones?

**Comment by ReneWerner87** [comment]
no not yet, maybe you can help us and make this possible, for now we have only provided the 4 most common methods

**Comment by ReneWerner87** [comment]
check also http://expressjs.com/en/api.html#res.format

**Comment by ReneWerner87** [comment]
whereby the variant of express does not really bring the benefit, because you can then also directly use a switch and accomplish the same thing

**Comment by Hexiro** [comment]
alright interesting. I'll keep that in mind. Thanks for the help!
