### ISSUE TITLE
Question: Middleware is being applied outside the applied group and scope

### ISSUE THREAD

**Issue by nikandlv** [gofiber/fiber#1495]
**Fiber version**
 Fiber v2.17.0  

**Issue description**
When using jwt middleware and attempting to have 2 groups 1 for public and 1 for protected routes it applies the middleware to the public group which is defined separately 

`/works` returns 200
`/` returns 400

**expected behavior**
`/works` should return 200
`/` should return 200

**Code snippet**

```go
package main


import (
	jwtware "github.com/gofiber/jwt/v2"

	"github.com/gofiber/fiber/v2"
)

func main() {
  app := fiber.New()

  public := app.Group("")
  protected := app.Group("")

  public.Get("/works", func(c *fiber.Ctx) error {
    return c.SendString("it works!")
  })

  protected.Use(jwtware.New(jwtware.Config{
    SigningKey: []byte("secret"),
  }))

  public.Get("/", func(c *fiber.Ctx) error {
    return c.SendString("it does not work!")
  })

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
Yes, because you have only defined an empty route, in the end it is important on which logical route the handler is executed.

Express behaves the same way

**Comment by nikandlv** [comment]
> Yes, because you have only defined an empty route, in the end it is important on which logical route the handler is executed.
> 
> Express behaves the same way

Ah, well
Coming from `Echo` of labstack background the same code works.
Using a non empty route for groups `/app` for both groups also behaves the same.
Does this mean that if the prefix of the groups are the same then the groups their selves are the same or at least middle wares   treat them as same?

**Comment by ReneWerner87** [comment]
Yes exactly, groups in express are actually only virtual, at the end everything is in a flat list, where the route for matching is the key and the handlers are as a list under this key (if you leave out the further level of the request methods).

This list is traversed in the order in which it was defined when the request arrives at the server.

**Comment by nikandlv** [comment]
@ReneWerner87 I see thanks for the clarification
