### ISSUE TITLE
🤗 Are structs binded with BodyParser() safe to store outside handlers ?

### ISSUE THREAD

**Issue by sub-mersion** [gofiber/fiber#1498]
Methods that return unsafe values are marked in the docs, such as [`Ctx.Params()`](https://docs.gofiber.io/api/ctx#params).
`Ctx.BodyParser()` is not marked as such. So, is it safe to write the following ? :

```go
type Foo struct {...}

// ...

mem := make(map[string]Foo)

app.Post("/", func(c *fiber.Ctx) error {
	var foo Foo
	c.BodyParser(&foo)
        mem[newID()]=foo
	return c.SendStatus(fiber.StatusCreated)
})
```

If not, how can one store safely a struct parsed from request body in the memory?

I have encountered rewriting of string fields in a more complex case using BodyParser, but cannot reproduce it with a minimal example. I am wondering wether BodyParser() is unsafe "under the hood", or if my issue is more intricate.

**Comment by ReneWerner87** [comment]
would say it is not safe, inside we use a buffer which is reused, so you should make a copy if you want to put the data in memory

**Comment by sub-mersion** [comment]
Thanks for your response.
I suggest adding the warning note about mutability to the documentation of `Ctx.BodyParser()`, see gofiber/docs#194.

**Comment by ReneWerner87** [comment]
Thx for the PR
