### ISSUE TITLE
🐛 `c.OriginalURL()` changed after `SendFile`

### ISSUE THREAD

**Issue by Trim21** [gofiber/fiber#1499]
**Fiber version**

github.com/gofiber/fiber/v2 v2.17.0

**Issue description**

## `c.OriginalURL()` changed after `c.SendFile`

**Code snippet**

```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	// Steps to reproduce
	app.Get("/index", func(c *fiber.Ctx) error {
		fmt.Println("original", c.OriginalURL()) // "/index?page=1"
		err := c.SendFile(fmt.Sprintf("files/thread/%s.html", c.Query("page", "1")))
		fmt.Println(c.OriginalURL()) // "$CWD/files/thread/1.html"
		return err
	})

	log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/master/ctx.go#L1053-L1075

right , we change the original url so we can use the fasthttp internal functionality

probably we should change this back

maybe you can support us with a pull request and a unittest for it

**Comment by Trim21** [comment]
I found that there is an extra bug here, even default config `KeyGenerator: func(c *fiber.Ctx) string {	return c.Path() }` will make cache confused.

**Comment by Trim21** [comment]
this should be separated into 2 issues maybe.

**Comment by ReneWerner87** [comment]
feel free to create a pull request with the solution for both things

**Comment by Trim21** [comment]
I'm not sure what kind of fix do you expected for this cache issues.

Is it ok to make a copy string of generated key as real cache key?

**Comment by geet** [comment]
@ReneWerner87  I think we need to reopen this issue. If I try  the code snippet mentioned in the [comment](https://github.com/gofiber/fiber/issues/1499#issue-975160251) , I can still reproduce the bug. Try hitting the `/index` endpoint twice.
i gave a fix for this in the [PR](https://github.com/gofiber/fiber/pull/1788)
