### ISSUE TITLE
🐛 ipv6 loopback

### ISSUE THREAD

**Issue by hotrungnhan** [gofiber/fiber#1500]
**Fiber version**
v2.17.0
**Issue description**
i findout a little UI isuee with ipv6, that the console not giving me rightaway loopback ip. It must be [::1]:port not [::]
 ┌───────────────────────────────────────────────────┐
 │                     trueIPV6                      │
 │                   Fiber v2.17.0                   │
 │                 http://[::]:8000                  │
 │                                                   │
 │ Handlers ............. 2  Processes ........... 1 │
 │ Prefork ....... Disabled  PID .............. 9972 │
 └───────────────────────────────────────────────────┘
**Code snippet**
```go
package main

import "github.com/gofiber/fiber/v2"

func main() {

  var set = fiber.Config{
	  Network:                 fiber.NetworkTCP6,
  }
  app := fiber.New(set)

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by techytoes** [comment]
@ReneWerner87 can I work on this issue? Thanks!

**Comment by ReneWerner87** [comment]
Sure

**Comment by techytoes** [comment]
@ReneWerner87 can you please help me with documentation for testing locally? 🙇🏼

**Comment by hi019** [comment]
@techytoes I can help. What issue are you facing?

**Comment by techytoes** [comment]
@hi019 I have made the changes. Just wanted to test these locally. Couldn't find any supporting documentation. Can you please help me with this?

**Comment by hi019** [comment]
@techytoes you should be able to just run `go test`
