### ISSUE TITLE
🐛 Possible issue with BodyParser's MIME type determination logic

### ISSUE THREAD

**Issue by shirshendubhowmick** [gofiber/fiber#1505]
**Fiber version**: 2.17.0

**Issue description**: As per current logic in `BodyParser` it checks if content type is starting with `application/json` to parse JSON accordingly. The problem is when client sends a content type of `application/vnd.api+json; version=1` it fails and returns an error `Unprocessable Entity` even though the content type is valid of type `application/json`

**Code snippet**

```go
err := ctx.BodyParser(requestBody);
```

**Comment by shirshendubhowmick** [comment]
@ReneWerner87 Can I work on this and send PR ?

**Comment by ReneWerner87** [comment]
Sure

**Comment by shirshendubhowmick** [comment]
@ReneWerner87 Raised #1506 for this fix

**Comment by shirshendubhowmick** [comment]
@ReneWerner87 Any ETA when this new version will be released ?

**Comment by ReneWerner87** [comment]
Until the end of this week at the most, I want to collect more pull-requests first and then the release will come (we actually release every 14 days at the most).

**Comment by ReneWerner87** [comment]
As long as you could test the commit from the master in your go mod

https://golang.org/ref/mod#pseudo-versions
