### ISSUE TITLE
🤔 Does Fiber support Hot reload ?

### ISSUE THREAD

**Issue by chocovish** [gofiber/fiber#151]
Just tried fiber. and the very first thing i feel missing was the hot reload.
I'm coming from a python background where Flask has a feature like **development=True** parameter to enable hot reload (reflect result in server instantly after changing the code).

**Comment by Fenny** [comment]
We were planning to add this to `Fiber`, we are just not sure about the name yet.
Do you have any suggestions, and why we should name it `x`. 
`app.Settings.HotReload = true`
`app.Settings.AutoRefresh = true`
`app.Settings.RestartOnChange = true`
`app.Settings.AutoReload = true`
`app.Settings.AutoRefresh = true`

**Comment by cheft** [comment]
```javascript
import (
	"github.com/gofiber/fiber"
	"github.com/qinains/fastergoding"
)

func main() {
	fastergoding.Run() // hot reload
	app := fiber.New()
        ...
```

**Comment by sebastianbuechler** [comment]
> ```js
> import (
> 	"github.com/gofiber/fiber"
> 	"github.com/qinains/fastergoding"
> )
> 
> func main() {
> 	fastergoding.Run() // hot reload
> 	app := fiber.New()
>         ...
> ```

This does not work for me since the server always restarts after adding fastergroding:
```
/src/main.go:21 +0x57
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x88c00f]
goroutine 1 [running]:
github.com/qinains/fastergoding.watch.func2(0xc000182e40, 0xc, 0x0, 0x0, 0xa15020, 0xc0001004b0, 0x0, 0x0)
/go/pkg/mod/github.com/qinains/fastergoding@v0.0.2/fastergoding.go:135 +0x2f
path/filepath.walk(0xc000182cf0, 0xa, 0xa1eea0, 0xc0008db6c0, 0xc000093d10, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:380 +0x213
path/filepath.walk(0xc0001829d0, 0x7, 0xa1eea0, 0xc0008da820, 0xc000093d10, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:384 +0x2fe
path/filepath.walk(0xc000182676, 0x5, 0xa1eea0, 0xc0008da750, 0xc000093d10, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:384 +0x2fe
path/filepath.walk(0xc8b518, 0x1, 0xa1eea0, 0xc00068a270, 0xc000093d10, 0x0, 0xc000093cd8)
/usr/local/go/src/path/filepath/path.go:384 +0x2fe
path/filepath.Walk(0xc8b518, 0x1, 0xc000093d10, 0xc8b518, 0x1)
/usr/local/go/src/path/filepath/path.go:406 +0x105
github.com/qinains/fastergoding.watch(0xc8b518, 0x1, 0x0, 0x0, 0x0)
/go/pkg/mod/github.com/qinains/fastergoding@v0.0.2/fastergoding.go:134 +0x12e
github.com/qinains/fastergoding.Run(0x0, 0x0, 0x0)
/go/pkg/mod/github.com/qinains/fastergoding@v0.0.2/fastergoding.go:156 +0xa5
main.main()
/src/main.go:21 +0x57
```

**Comment by sivailangos** [comment]
@sebastianbuechler Check https://github.com/gofiber/recipes/tree/master/air to enable hot reload. It works!

**Comment by sagadsalem** [comment]
Does fiber has it's own Hot reload @Fenny

**Comment by efectn** [comment]
> Does fiber has it's own Hot reload @Fenny

Yes, https://github.com/gofiber/cli

**Comment by sagadsalem** [comment]
@efectn fiber hot reload is not working properly with Goland 
I think it's because the AutoSave in Goland
when I use sublime text everything works properly
