### ISSUE TITLE
Feature Request 🚀: Skip successful requests option for ratelimit middleware

### ISSUE THREAD

**Issue by pateljoel** [gofiber/fiber#1512]
It would be nice if it is possible for an option to skip successful requests much like the express rate limit library for node:

[express-rate-limit#skipsuccessfulrequests](https://github.com/nfriedly/express-rate-limit#skipsuccessfulrequests)

Thanks.

**Comment by ReneWerner87** [comment]
Please check https://docs.gofiber.io/api/middleware/limiter

And we are working also on https://github.com/gofiber/fiber/pull/1247

**Comment by ReneWerner87** [comment]
feel free to create a pull request containing the new option at the limiter middleware
