### ISSUE TITLE
Fiber performance vs gRPC performance ?

### ISSUE THREAD

**Issue by MagnifiGo** [gofiber/fiber#1514]
Has anybody performed any Fiber vs gRPC benchmarking? I am curious if Fiber outperforms gRPC or the other way around.

**Comment by ReneWerner87** [comment]
No, but you are welcome to create a benchmark and share your findings with us here

**Comment by ReneWerner87** [comment]
closed since we currently have no benchmark, if someone has a benchmark with results, he can deposit it here with pleasure
