### ISSUE TITLE
🚀 feature to disable logging for certain route

### ISSUE THREAD

**Issue by jeremy-chua** [gofiber/fiber#1519]
I'm using both the monitor and logger middleware.

The monitor refreshes every second, hence the log file will be fill up fast. Moreover, most file the log entry will belong to monitor which is not useful inho
Will be great to have a feature in logger to disable certain route from logging

Thanks

**Comment by hi019** [comment]
You should be able to use the Next config entry. Something like this (untested, let me know if it wrosk):

```go
app.Use(logger.New(&fiber.Config{
    Next: func (c *fiber.Ctx) {
        return c.Path() == "monitor"
    },
})
```

**Comment by jeremy-chua** [comment]
Thanks got it!!!
