### ISSUE TITLE
feature to support Server Side Event (SSE) and client EventSource

### ISSUE THREAD

**Issue by jeremy-chua** [gofiber/fiber#1520]
I'm working on a project to stream and subscribe to eventssource on client.

https://en.wikipedia.org/wiki/Server-sent_events

Will be great to have this supported.
Thanks
:)

**Comment by alanhe** [comment]
I want SSE too.

**Comment by efectn** [comment]
Look at here https://github.com/gofiber/recipes/pull/151.
