### ISSUE TITLE
🔥 Add a shortcut for map like gin.H

### ISSUE THREAD

**Issue by hyingreborn** [gofiber/fiber#153]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**

```go

c.JSON(fiber.H{
    "field1": someStructData1,
    "field2": someStructData2,
})
```

```go
// H is a shortcut for map[string]interface{}
type H map[string]interface{}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by Fenny** [comment]
This can be added in v2, what about naming it `Map` ?
```go
type Map map[string]interface{}

c.JSON(fiber.Map{
    "field1": someStructData1,
    "field2": someStructData2,
})
```

**Comment by hyingreborn** [comment]
that's well

**Comment by toannguyen3105** [comment]
> This can be added in v2, what about naming it `Map` ?
> 
> ```go
> type Map map[string]interface{}
> 
> c.JSON(fiber.Map{
>     "field1": someStructData1,
>     "field2": someStructData2,
> })
> ```

Thank you
