### ISSUE TITLE
Ctx.Render FuncMap templating

### ISSUE THREAD

**Issue by challmand** [gofiber/fiber#1533]
**Question description**
Is it possible to pass template functions with the Ctx.Render?

I am currently using html/template to pass a template.FuncMap to the template I am using, but want to convert to gofiber.

Thank you.

**Comment by ReneWerner87** [comment]
Please check https://github.com/gofiber/template/tree/master/html

**Comment by challmand** [comment]
> Please check https://github.com/gofiber/template/tree/master/html

thank you, that is exactly what i was looking for, didnt see it  initially on gofiber.io docs
