### ISSUE TITLE
Seperating routes into different files 🤗 

### ISSUE THREAD

**Issue by challmand** [gofiber/fiber#1534]
**Question description**
Currently i have a main.go file with my app.Get routes, but how could I separate my routes into different files and the main.go file will include them all?

Essentially would like to have multiple files with app.Get and app.Post and my main.go would have something like app.Routes which would be able to get the other routes from the files.

Or does it not matter and I can have in my main simply app.Listen and as long as I have a global app variable it will work as expected? 

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

var App *fiber.App

func main() {
  App = fiber.New()
  //multiple different files with app routes not in main.go

  App.Listen(":3000")

}
```

**Comment by shytikov** [comment]
You may not even need to declare it as a Global (with first capital letter), as a file in the same folder treated as part of the same module, that will work.

However... it could be achieved by creating a function that will accept the reference to the app and perform configuration. 

I guess.

**Comment by hi019** [comment]
There is an example of that here: https://github.com/gofiber/recipes/tree/master/clean-architecture%2Fapi
