### ISSUE TITLE
HOT Reload🚀 

### ISSUE THREAD

**Issue by AAlvarez90** [gofiber/fiber#1535]
**Is your feature request related to a problem?**
No, but I think it could be a great improvement.

**Describe the solution you'd like**
I would love, and I think many would love this feature if the app watched for changes in the source code and hot-reloaded itself. They got it done in this go framework: https://go-zepto.com/ 

**Describe alternatives you've considered**
The only alternative is to constantly kill the server and then run again `go run main.go`.

**Additional context**
This framework has it, maybe the functionality can be ported over? https://go-zepto.com/

After creating this issue I came across an article in which I learned that using nodemon it is possible to achieve the same result: `nodemon --exec go run main.go --signal SIGTERM`.
Here is the article: https://techinscribed.com/5-ways-to-live-reloading-go-applications/
I wonder if this could be adopted by the framework..

**Comment by ReneWerner87** [comment]
please check https://github.com/gofiber/recipes/tree/master/air

for hot load we recommend air
https://github.com/cosmtrek/air
