### ISSUE TITLE
🚀 Add Bind method to fiber.Ctx for adding var map for binding to template engine

### ISSUE THREAD

**Issue by aztecrabbit** [gofiber/fiber#1536]
**Is your feature request related to a problem?**
Yes, I want add var map for template engine from middleware.

**Describe the solution you'd like**
```go
app.Use(func(c *fiber.Ctx) error {
  c.Bind(fiber.Map{
    "DEBUG": true,
    "title": "App",
  })
  return c.Next()
})
app.Use(func(c *fiber.Ctx) error {
  c.Bind(fiber.Map{
    "PATH": c.Path(),
  })
  return c.Next()
})
app.Get("/", func(c *fiber.Ctx) error {
  return c.Render("index", fiber.Map{
    "title": "Home",
  })
})
```
```
DEBUG: true
 PATH: /
title: Home
```
Optional
```go
app.Use(func(c *fiber.Ctx) error {
  c.PutBind("SITE_NAME", "App Name")
  c.PutBind("IP", c.IP())
  return c.Next()
})
app.Get("/", func(c *fiber.Ctx) error {
  fmt.Println(c.GetBind("IP"))
  return c.Render("index", fiber.Map{
    "title": "Home",
  })
})
```
```
SITE_NAME: App Name
       IP: 127.0.0.1
    title: Home
```

**Comment by gitMitos** [comment]
c.Context().SetUserValue("IP",  c.IP() ) in middleware
then 
app.Get("/", func(c *fiber.Ctx) error {
  val:=c.Context().Value("IP") // plus maybe some wrap functions if needed
  return c.Render("index", fiber.Map{
    "IP": val,
  })
})

these are not droids you're looking for? or you want better "sugar" with specifically "PutBind" and "GetBind"?

**Comment by aztecrabbit** [comment]
No. `c.Context().SetUserValue` and `c.Context().Value` is same like `c.Locals` do. https://docs.gofiber.io/api/ctx#locals.

**Comment by ReneWerner87** [comment]
Exactly, please use the locals to populate a map and then when rendering you use the values set via the locals

**Comment by aztecrabbit** [comment]
Like this?
```go
app.Get("/", func(c *fiber.Ctx) error {
  return c.Render("index", fiber.Map{
    "DEBUG": c.Locals("DEBUG"),
    "SITE_NAME": c.Locals("SITE_NAME"),
    "PATH": c.Path(),
  })
})
```
Or maybe like this
```go
app.Use(func(c *fiber.Ctx) error {
  c.Locals("APP", fiber.Map{
    "DEBUG": true,
    "SITE_NAME": "App Name",
    "PATH": c.Path(),
  })
  return c.Next()
})
app.Use(func(c *fiber.Ctx) error {
  mapApp := c.Locals("APP").(fiber.Map)
  mapApp["IP"] = c.IP()
  c.Locals("APP", mapApp)
  return c.Next()
})
app.Get("/", func(c *fiber.Ctx) error {
  return c.Render("index", fiber.Map{
    "APP": c.Locals("APP"),
  })
})
app.Get("/and-in-every-route", func(c *fiber.Ctx) error {
  return c.Render("and", fiber.Map{
    "APP": c.Locals("APP"),
  })
})
```
Why should i do that? I believe this is not [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself)

**Comment by ReneWerner87** [comment]
yes this
```go
app.Get("/", func(c *fiber.Ctx) error {
  return c.Render("index", fiber.Map{
    "DEBUG": c.Locals("DEBUG"),
    "SITE_NAME": c.Locals("SITE_NAME"),
    "PATH": c.Path(),
  })
})
```
or like this
```go
app.Use(func(c *fiber.Ctx) error {
  c.Locals("APP", fiber.Map{
    "DEBUG": true,
    "SITE_NAME": "App Name",
    "PATH": c.Path(),
  })
  return c.Next()
})
app.Get("/", func(c *fiber.Ctx) error {
  mapApp := c.Locals("APP").(fiber.Map)
  return c.Render("index", mapApp)
})
app.Get("/and-in-every-route", func(c *fiber.Ctx) error {
  mapApp := c.Locals("APP").(fiber.Map)
  return c.Render("and", mapApp)
})
```

**Comment by aztecrabbit** [comment]
Okay. Let say some guy building debugtoolbarpanel middleware. Which mean they sould be bind html for that panel. How they sould bind that panel? Store html panel in `c.Locals`? And everytime i need to show that panel, i need to call `c.Locals` in every route? Thats not DRY at all.

Like in csrf milddeware. Why `ContextKey` stored in `c.Locals`? I think the best option is to store that in `c.Bind` and accessible in every template you render. No need to register it in `c.Render`.

**Comment by ReneWerner87** [comment]
possible, feel free to create a pull request in the template repository and make it possible in any engine
