### ISSUE TITLE
🚀 HTTP/2 Support 

### ISSUE THREAD

**Issue by efectn** [gofiber/fiber#1541]
**Is your feature request related to a problem?**
No.
**Describe the solution you'd like**
@dgrr says https://github.com/dgrr/http2 is production-ready. I think you should add initial support for HTTP/2 with config. I know we can add HTTP/2 after fiber.New() but default support would not come amiss.

**Comment by gitMitos** [comment]
is there any performance\rps data about http1/fasthttp vs dgrr/http2/fasthttp?

**Comment by dgrr** [comment]
I just made a small benchmark:
```
### Running HTTP/1.1

$ wrk -H 'Host: 127.0.0.1' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' -d 20 -c 128 http://127.0.0.1:8080/plaintext
Running 20s test @ http://127.0.0.1:8080/plaintext
  128 goroutine(s) running concurrently
1658386 requests in 18.445626985s, 205.60MB read
Requests/sec:		89906.73
Transfer/sec:		11.15MB
Avg Req Time:		1.423697ms
Fastest Request:	38.316µs
Slowest Request:	183.427525ms
Number of Errors:	0


### Running HTTP/2

$ wrk -H 'Host: 127.0.0.1' -H 'Accept: text/plain,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7' -H 'Connection: keep-alive' -d 20 -c 128 -no-vr https://localhost:8443/plaintext
Running 20s test @ https://localhost:8443/plaintext
  128 goroutine(s) running concurrently
1817519 requests in 18.778669885s, 228.80MB read
Requests/sec:		96786.35
Transfer/sec:		12.18MB
Avg Req Time:		1.3225ms
Fastest Request:	40.686µs
Slowest Request:	83.733169ms
Number of Errors:	0
```

But that means nothing, tbh. The main difference is latency. Instead of having to setup a single connection for N requests, with HTTP/2 you can just setup one connection and do all the requests you want. The connection can be kept alive as long as you want.

**Comment by gitMitos** [comment]
Thank you. I was worried it may cause some big (noticeable) drop in single requests (like if you add csrf middleware to fiber). Happy to see that all good in that front.

**Comment by dgrr** [comment]
[Here](https://http2.gofiber.io/) I have a testing site for http2 and websocket. (Don't click on the HTTP/1.1 because it doesn't work yet).

**Comment by efectn** [comment]
> [Here](https://http2.gofiber.io/) I have a testing site for http2 and websocket. (Don't click on the HTTP/1.1 because it doesn't work yet).

Does websocket middleware have support for HTTP/2 clients?

**Comment by G2G2G2G** [comment]
>Does websocket middleware have support for HTTP/2 clients?

What do you mean? Web socket is a.. socket it's entirely different from http a different connection method.

**Comment by dgrr** [comment]
> > [Here](https://http2.gofiber.io/) I have a testing site for http2 and websocket. (Don't click on the HTTP/1.1 because it doesn't work yet).
> 
> Does websocket middleware have support for HTTP/2 clients?

So... The HTTP/2 library does not support [fasthttp's Hijack](https://pkg.go.dev/github.com/valyala/fasthttp#RequestCtx.Hijack), that means, if an HTTP/2 request tries to upgrade to the WebSocket protocol, it won't be able. Normally, WebSocket connections use HTTP/1.1 to upgrade. But who knows, maybe chrome decides to upgrade over HTTP/2 too. I'll see.

Short answer: No, it doesn't support WebSocket upgrades.
