### ISSUE TITLE
🐛 template/html layout

### ISSUE THREAD

**Issue by bengarrett** [gofiber/fiber#1543]
**Fiber version**
v2.19 on Go 1.71.

**Issue description**
Hi, I am new to Fiber but I cannot seem to get the basic HTML layouts working as expected.

A copy and paste of the [HTML Basic example](https://github.com/gofiber/template/tree/master/html#basic-example) fails to produce a layout for the index. I don't know if this is a bug or simply a documentation error?

http://localhost:3000/ results in the following response.
```html
<h2>Header</h2>
<h1>Hello, World!</h1>
<h2>Footer</h2>
```

http://localhost:3000/layout results in the layout and index being rendered?
```html
<!DOCTYPE html>
<html>

<head>
  <title>Main</title>
</head>

<body>
  <h2>Header</h2>
<h1>Hello, World!</h1>
<h2>Footer</h2>
</body>

</html>
```

**Code snippet**

```go
package main

import (
	"log"
	
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/html"
)

func main() {
	// Create a new engine
	engine := html.New("./views", ".html")

  // Or from an embedded system
  // See github.com/gofiber/embed for examples
  // engine := html.NewFileSystem(http.Dir("./views", ".html"))

	// Pass the engine to the Views
	app := fiber.New(fiber.Config{
		Views: engine,
	})

	app.Get("/", func(c *fiber.Ctx) error {
		// Render index
		return c.Render("index", fiber.Map{
			"Title": "Hello, World!",
		})
	})

	app.Get("/layout", func(c *fiber.Ctx) error {
		// Render index within layouts/main
		return c.Render("index", fiber.Map{
			"Title": "Hello, World!",
		}, "layouts/main")
	})

	log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
next time please open an issue report in the template repository

the output is expected

the first route does not use a layout, so it only outputs the content of the file with the title variable

the 2nd route uses the layout and puts the content of the file to be rendered into the layout file where the {{embed}} tag is located

any other questions ?

**Comment by bengarrett** [comment]
That is great, thanks for the clarification René and sorry about the misplacement of the issue.

For a suggestion, it might be clearer if the "Render index" example comment is updated to state `// Render index with no layout`?

Having the ./views/layouts/main.html layout documentation, where the first example is root, but it doesn't render with the layout is a bit confusing. I thought I was doing something wrong.
