### ISSUE TITLE
🤗 Cannot get routes created in separate functions

### ISSUE THREAD

**Issue by lerichardson** [gofiber/fiber#1544]
**Question description**
I'm trying to clean up my code a bit by placing my routes in external go files. It seems, however, that fiber cannot create routes sent in other functions? When I try the code below, it results in a "Cannot GET /demo". What's going on?
**Code snippet**
```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
)

func main() {
	app := fiber.New()
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowHeaders: "*",
	}))
	DemoPage()
	app.Listen(":3000")
}

func DemoPage() {
	app := fiber.New()
	app.Get("/demo", func(c *fiber.Ctx) error {
		return c.SendFile("./public/demo.html")
	})
	return
}

```

**Comment by hi019** [comment]
Fiber instances created with fiber.New do not contain the routes of other instances. Try passing `app` from `main` into `DemoPage`:

```go
func DemoPage(app *fiber.App) {
	app.Get("/demo", func(c *fiber.Ctx) error {
		return c.SendFile("./public/demo.html")
	})
	return
}
```

Or you can just make DemoPage a Fiber handler and do `app.Get("/demo", DemoPage)` in main
