### ISSUE TITLE
🚀 Can someone provide the configuration of nginx equivalent for fiber for wordpress?

### ISSUE THREAD

**Issue by superdolt** [gofiber/fiber#1548]
"reverse proxy" script for things similar as the below for reference?

https://github.com/deliciousbrains/wordpress-nginx/blob/develop/sites-available/multisite-subdomain.com

**Comment by ReneWerner87** [comment]
for some things you should use nginx, there it does not offer to switch to fiber

**Comment by superdolt** [comment]
i dont want to route using nginx and then fiber then php etc. just use fiber to replace nginx. possible to provide the instructions? it's almost what everyone wants.

**Comment by G2G2G2G** [comment]
yes as eisen said, fiber isn't for that. 

Normally in your case superdolt you are going to run nginx in front of both wordpress AND fiber, and it'll reverse proxy to both of them
