### ISSUE TITLE
🐛 body parser wont parse json tag of struct in x-www-urlencoded , or formdata

### ISSUE THREAD

**Issue by hotrungnhan** [gofiber/fiber#1561]
**Fiber version**
v.2.19
**GO VERSION** 1.17.1
**Issue description**
Bodyparser cant unmashal json tag , throw err.
But it can work when post with property name as key ( still throw error but  you can skip), althought i already tag .
**Code snippet**

```go
// request should send with urlencode body as {type_type :"blabla" ....} 
// but it work with {type:"blabla",...}
package test

import (
	"encoding/json"
	"testing"

	"github.com/gofiber/fiber/v2"
)

type Container struct {
	Type string          `json:"type_type"`
}

func handler(c *fiber.Ctx) error {
	p := Container{}
	var err = c.BodyParser(&p)
        if err != nil {
        return err
        }
	return c.JSON(fiber.Map{
		"p":   p,
	})
}
func TestDSKDS(t *testing.T) {

	//Create the Json string
	app := fiber.New()
	app.Post("/test", handler)
	app.Listen(":3001")

}


```

**Comment by shahriar350** [comment]
```
func handler(c *fiber.Ctx) error {
    p := new(Container)
    var err = c.BodyParser(p)
    if err != nil {
     return err
}
.....
}
```
Try it

**Comment by hotrungnhan** [comment]
im sorry,  there was a bit mistake when i forgot check nill of err.
but after fix that now i findout that when you post with raw json > work ! , but the other form  url encode or formdata isn't reconize  type_type tag

**Comment by hotrungnhan** [comment]
oh no, i did't read document carefully for form data, url encode , use "form" tag instead "json"
