### ISSUE TITLE
Wildcards preferred over static path 

### ISSUE THREAD

**Issue by sokryptk** [gofiber/fiber#1588]
Hi, I have such a config on my webserver. Whenever I try to request to /info/112/download, the /info/:id/:chapter endpoint is the one that's getting matched. I have tried reordering them and I have failed to do it successfully. Is this by design and if so, how would I overcome this rather than changing the endpoint path.

```func main() {
	router := fiber.New()

	router.Use(cors.New(
		cors.Config{
			AllowOrigins: "*",
		}),
	)

	
	router.Post("/info/:id/:chapter", cornerstone.Retrieve)
	router.Post("/info/:id/download", cornerstone.Download)
	router.Get("/info/:id", cornerstone.Info)

	if err := router.Listen(getPort()); err != nil {
		log.Println(err)
	}
}
```

**Comment by krypticallusion** [comment]
Oh, okay. Thanks for the help!
