### ISSUE TITLE
How to access headers and cookies 🤗 

### ISSUE THREAD

**Issue by ManojKumarChauhan** [gofiber/fiber#1591]
**Question description**
How to access headers and cookies from fiber's request and response.
**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  // ..
}
```

I have following function where fiber context is passed
func handle(c *fiber.Ctx) {
}

I can access request headers using following code
req := c.Request()
headerString := req.Header.GetHeaders()

But I didn't find the code to access response header.

Also I didn't find any code to print all the cookies from fiber's request/response.

Can someone suggest?

**Comment by chalukyaj** [comment]
Not sure who this might help, but a simpler method to just get one header is 
`ctx.Fasthttp.Request.Header.Peek("header-name")`

**Comment by yangqingrong** [comment]
`token := c.GetReqHeaders()["Token"]`

it don't support UTF-8 chars

eg:
```
curl -X 'POST' \
  'http://127.0.0.1:8080/api/test/token' \
  -H 'accept: application/json' \
  -H 'Token: testUtf-8中文' \
  -d ''
```
output:
 
Undocumented | TypeError: Failed to execute 'fetch' on 'Window': Failed to read the 'headers' property from 'RequestInit': String contains non ISO-8859-1 code point.
