### ISSUE TITLE
🚀 Run multiple auth functions by relation

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#1608]
I have an idea for middleware relation. I have thought like that 

```go
api.Get("/",
        middlewares.CheckAuth(),
        relation.New(relation.Or, middlewares.CheckIsAdmin, middlewares.CheckIsModerator),
        controllers.GetMe,
    )
```

If user is not admin but if user is moderator, GetMe handler is going to work.

**Comment by balcieren** [comment]
Hi again, I made that's idea.
[fiber-relation](https://github.com/balcieren/fiber-relation)

**Comment by ReneWerner87** [comment]
Ok thx, you can add yourself to the list https://github.com/gofiber/fiber#-third-party-middlewares

**Comment by balcieren** [comment]
@ReneWerner87 [Fastify Auth](https://github.com/fastify/fastify-auth) this package ispired to me. But I can not do like that. I have tried but i didn't get positive result from [fiber-relation](https://github.com/balcieren/fiber-relation). I hope , your team will do that idea.

**Comment by ReneWerner87** [comment]
@balcieren can you add your package to the list ?

**Comment by balcieren** [comment]
> Reference

I have tried something but i didn't take good results so i have removed package.

**Comment by balcieren** [comment]
> @balcieren can you add your package to the list ?

I have tried something but i didn't take good results so i have removed package.
