### ISSUE TITLE
Rendering text/plain templates 

### ISSUE THREAD

**Issue by withernet** [gofiber/fiber#1615]
What is the proper way to render `text/plain` templates? I haven't been able to find out how to override such functionality with the code below.

```go
		//c.Set("Content-type", "text/plain") // Doesnt work
		//c.Type("text/plain", "utf8") // Doesnt work
                //c.Append("Content-Type", "text/plain") // Doesnt work

		return c.Render("robots.txt", fiber.Map{
			...
		})
```

**Comment by withernet** [comment]
Looks like I was able to do this like so:

```go
		c.Render("robots.txt", fiber.Map{
			...
		})

		c.Set("Content-type", "text/plain")

		return nil
```

While this does work, it doesn't seem correct?

**Comment by ReneWerner87** [comment]
the solution is okay and I would have suggested it too

you can also use the shortcut method 
https://docs.gofiber.io/api/ctx#type

c.Type("text")

**Comment by withernet** [comment]
`c.Type("text")` doesn't work, it changes the type to `Content-Type: application/octet-stream`. `c.Set("Content-type", "text/plain")` does work however.

**Comment by ReneWerner87** [comment]
Yes you are right

https://github.com/gofiber/fiber/blob/master/utils/http.go#L149

Should be c.Type("txt") without the "e"

**Comment by withernet** [comment]
Ah, there's the list, thanks :)
