### ISSUE TITLE
🤗  Question: what is a greedy parameter

### ISSUE THREAD

**Issue by idc77** [gofiber/fiber#1619]
If you invent new language, describe what this new language means.

What is a "greedy parameter"?

**Comment by idc77** [comment]
Your stupid discord bot doesn't recognize reactions

**Comment by ReneWerner87** [comment]
greedy parameters are
![image](https://user-images.githubusercontent.com/7063188/141092190-958963d2-2f56-4a38-9be7-a84c50b3b963.png)
https://docs.gofiber.io/guide/routing#parameters

we have taken this wording out of the world of regular expressions and actually thought it should be clear from the examples and this understanding how the behavior is
https://developpaper.com/the-greedy-and-non-greedy-modes-of-regular-expressions/

we can also provide further documentation describing this behavior better or you can also make a pull request for the documentation to be improved.

now that you have the 2 articles, do you understand what a greedy parameter is, so we can find a suitable wording for the documentation or should I explain it in another way?

**Comment by ReneWerner87** [comment]
> Your stupid discord bot doesn't recognize reactions

Btw what is your discord name? (maybe i can help you there)
