### ISSUE TITLE
🤗 How to extend fiber Router

### ISSUE THREAD

**Issue by xushuhui** [gofiber/fiber#1624]
**Question description**
Hi，I want add feature in route，But it must return interface fiber.Router

**Code snippet** 
I implement like this,But it not work 
```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  r := app.Group("test")
  r.Set(parmater1,parmater2).Get("/user",User)
...
}
```
In a word, I cant handle custom route，because  fiber.Router interface limit 
How can I do ?
Thank your work

**Comment by liaohongxing** [comment]
this example :

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  r := app.Group("test")
  r.Use(func(c *fiber.Ctx) error {
      c.Set("hello", "john")
      return c.Next()
  })
  r.Get("/user",User)
  ...
}
```

**Comment by xushuhui** [comment]
@liaohongxing   I  use middleware and   work it ,thanks
