### ISSUE TITLE
🐛 logger custom formatting is ignored

### ISSUE THREAD

**Issue by husanu** [gofiber/fiber#1625]
**Fiber version**
github.com/gofiber/fiber/v2 v2.22.0

**Issue description**

because of https://github.com/gofiber/fiber/blob/master/middleware/logger/config.go#L85 if Output == nil and Format contains `${status}` and `${method}"` then cfg.enableColors is set to true, which will force the code for no custom format to run:
```go
// https://github.com/gofiber/fiber/blob/master/middleware/logger/logger.go#L177
  // Default output when no custom Format or io.Writer is given
  if cfg.enableColors {}
```

**Code snippet**

```go
package main

import (
  "github.com/gofiber/fiber/v2"
  "github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
  app := fiber.New()

  // Steps to reproduce
  app.Use(logger.New(logger.Config{
    Format: ">>> [${time}] ${ip} ${host} ${status} - ${latency} ${method} ${path} ${url}\n",
    // DEFAULT Format: "[${time}] ${status} - ${latency} ${method} ${path}\n",
  }))

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/1609

**Comment by husanu** [comment]
> #1609

same buggy code... different side effect :)
