### ISSUE TITLE
🤗 Why is the return type of each handler is error?

### ISSUE THREAD

**Issue by jinhongguo** [gofiber/fiber#1630]
**Question description**

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

// look here
// Why is the return type of each handler is error, and what is the benefit of doing so?
func Foo(ctx *fiber.Ctx) error {
	return ctx.Send([]byte("hello fiber"))
}

func main() {
  app := fiber.New()
  app.Get("/",Foo)
  // ..
}
```

**Comment by ReneWerner87** [comment]
https://go.dev/blog/error-handling-and-go
https://go.dev/doc/tutorial/handle-errors

@jinhongguo this is a standard concept in golang 

the benefit is that we can abort the chain of middlewares if the return value is an error and not nil
