### ISSUE TITLE
🐛 Request Header Fields Too Large when running CSRF and encrypt cookie middleware

### ISSUE THREAD

**Issue by sevaho** [gofiber/fiber#1631]
**Fiber version** 2

**Issue description**

When running following script in a browser you will notice that the cookie value is growing by continuous encrypting the value. The browser will respond with `Request Header Fields Too Large` when cookie is too big.

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"
import "github.com/gofiber/fiber/v2/middleware/csrf"
import "github.com/gofiber/fiber/v2/middleware/encryptcookie"

func main() {
	app := fiber.New()

	app.Use(csrf.New())

    // cookie value generated by running `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
	app.Use(encryptcookie.New(encryptcookie.Config{
		Key: "VWY9XBVap74Zpd0ckbT1reTl0NM6pz7R"}))

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World 👋!")
	})

	app.Listen(":3000")
}
```

**Comment by fearofcode** [comment]
I can reproduce this on the latest fiber release.

If you run the above code and keep refreshing, the `_csrf` cookie value eventually becomes too large.

**Comment by vinay03** [comment]
For time being, changing the order of registering middlewares seems to be avoiding the issue.

```
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/csrf"
	"github.com/gofiber/fiber/v2/middleware/encryptcookie"
)

func main() {
	app := fiber.New()

	// cookie value generated by running `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
	app.Use(encryptcookie.New(encryptcookie.Config{
		Key: "VWY9XBVap74Zpd0ckbT1reTl0NM6pz7R"}))

	app.Use(csrf.New())

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})

	app.Listen(":3000")
}
```

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/pull/1343
@amir9480 can you help us with this problem

**Comment by silviucm** [comment]
To what @vinay03 mentioned, I would like to add that technically, the encryptcookie middleware already supports skipping cookies by name via the **Except** field at config time. So for csrf, one could just skip it, since it has its own generation ops (assuming below that the codebase keeps the default csrf cookie name as **csrf_** )

```
	// cookie value generated by running `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1`
	app.Use(encryptcookie.New(encryptcookie.Config{
		Key: "VWY9XBVap74Zpd0ckbT1reTl0NM6pz7R", Except: []string{"csrf_"}}))
```
With that added, you can use csrf independently positioned

**Comment by sevaho** [comment]
Thanks @silviucm I'll close the issue, as it not an issue anymore but a small bug.

**Comment by amir9480** [comment]
@ReneWerner87 
Sorry for the late response, I made a PR to fix this issue
