### ISSUE TITLE
🤗 can I add custom tcp listener or handler ?

### ISSUE THREAD

**Issue by Macrow** [gofiber/fiber#1635]
**How can I add custom tcp connection listener or handler?**

1. If I could add custom tcp connection listener or handler, how can I do ?

2. If not, I added a tcp listener in another port
```go
func setupTcpServer() {
	tcpServer, err := net.Listen("tcp", "0.0.0.0:4001")
	if err != nil {
		log.Fatal("start tcp server error")
	}
	go func() {
		for {
			conn, err := tcpServer.Accept()
			if err != nil {
				log.Printf("accept tcp connection error", err)
				continue
			}
                        // handle tcp connection
			go handleTpcConnection(conn)
		}
	}()
}
```
Everything works fine if prefork mode is ```false```.

if prefork mode is ```true```, it failed with ```bind: address already in use```

What is the right solution for handling tcp connection?

Start my custom tcp server in ```!fiber.IsChild()```?

**Comment by bigflood** [comment]
You can use custom listener.
```go
app := fiber.New()

// GET /api/register
app.Get("/api/*", func(c *fiber.Ctx) error {
    msg := fmt.Sprintf("✋ %s", c.Params("*"))
    return c.SendString(msg) // => ✋ register
})

customListener, err := net.Listen("tcp", ":3000")
if err != nil {
    panic(err)
}

//log.Fatal(app.Listen(":3000"))
log.Fatal(app.Listener(customListener))
```

**Comment by ReneWerner87** [comment]
@Macrow did the comment help you ? can we close the issue ?

**Comment by Macrow** [comment]
@bigflood @ReneWerner87 Thanks for your response.

Sorry for my unclear description.

I'v build a IM server handling websocket connection, at the same time, I want to handle raw tcp connection for tcp connection clients.

**My question: Can I setup raw tcp connection handler on same port which used by the normal http(websocket) handler ?**

For now, I used two different ports for http and raw tcp connections.

**Comment by Macrow** [comment]
@bigflood thanks for that, It helps a lot!
