### ISSUE TITLE
🐛 error(middleware/csrf): CookieSameSite default should be "Lax"

### ISSUE THREAD

**Issue by sixcolors** [gofiber/fiber#1639]
Default is "Strict", it should be "Lax"

Browser defaults are Lax. Fiber using a default of "Strict" is unadvisable as it will cause unexpected behavior. Strict requires HTTP first-party context and disregards requests initiated by third parties. So after navigating to the site from a third party site the safe HTTP methods (GET, HEAD, or OPTIONS) will not set the cookie. For example, a login page would not work by default when navigating to it from google or any other non-first party link.

"With Strict, the cookie is only sent to the site where it originated. Lax is similar, except that cookies are sent when the user navigates to the cookie's origin site. For example, by following a link from an external site. None specifies that cookies are sent on both originating and cross-site requests, but only in secure contexts (i.e., if SameSite=None then the Secure attribute must also be set). If no SameSite attribute is set, the cookie is treated as Lax."

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#samesite_attribute

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

The behaviour the team likely sought to prevent is SameSite=None, which blocks cookie set on cross-origin requests.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/825

it was lax before and was changed here to strict

**Comment by sixcolors** [comment]
> #825
> 
> it was lax before and was changed here to strict

Ack prior; argument still applies. Further default for other mw using CookieSameSite, session, which is Lax.
