### ISSUE TITLE
🤔 always get empty JSON response

### ISSUE THREAD

**Issue by washanhanzi** [gofiber/fiber#164]
**Question description**

- I always got empty `{}` from JSON response.
- no error is returned from the `c.JSON()` method.
- I tested in Postman, the response is always an empty object like `{}`. with `JSONP` method, the response is always `callback{}`.
- I don't know what happened or how to dig into this problem. 
- version: 1.7.0

**Code snippet (optional)**

```go
type status struct {
	code    int32
	message string
}

...
       data := status{
		code:    2,
		message: "hello wolrd",
	}
	if err := c.JSON(data); err != nil {
		log.Printf("error in response %v", err)
	}
```

**Comment by Fenny** [comment]
@washanhanzi, could you try the latest version 2?

**Comment by Fenny** [comment]
Make sure that your property keys are exported and accessible from the JSON parser:
```go
package main

import (
	"github.com/gofiber/fiber"
)

func main() {
	app := fiber.New()

	type status struct {
		Code    int32
		Message string
	}

	app.Get("/", func(c *fiber.Ctx) {
		// {"Code":200,"Message":"Hello, World"}
		if err := c.JSON(status{200, "Hello, World"}); err != nil {
			c.Status(500).Send("JSONParse error: ", err)
		}
	})

	type statusLwr struct {
		Code    int32  `json:"code"`
		Message string `json:"message"`
	}

	// {"code":200,"message":"Hello, World"}
	app.Get("/", func(c *fiber.Ctx) {
		if err := c.JSON(statusLwr{200, "Hello, World"}); err != nil {
			c.Status(500).Send("JSONParse error: ", err)
		}
	})

	// {"code":200,"message":"Hello, World"}
	app.Get("/", func(c *fiber.Ctx) {
		if err := c.JSON(fiber.Map{"code": 200, "message": "Hello, World"}); err != nil {
			c.Status(500).Send("JSONParse error: ", err)
		}
	})

	app.Listen(3000)
}

```

**Comment by washanhanzi** [comment]
I hate to ask this, but I am really new to golang. Fiber is my first framework to try out.

How to get v2.0.0?

I use:
```
import (
	"github.com/gofiber/fiber/v2"
)
```
the go mod report:
```
cannot load github.com/gofiber/fiber/v2: module github.com/gofiber/fiber@latest found (v1.7.0), but does not contain package github.com/gofiber/fiber/v2
```

I also tried the `github.com/gofiber/fiber@2.0.0`, but when I run `go get -u`, the import package automatic truncated the version.

I read in the [blog](https://blog.golang.org/publishing-go-modules), the pre-release version must contain a hyphen ?

**Comment by washanhanzi** [comment]
> Make sure that your struct keys are exported using capitalization so the JSON parser can access it.
> 
> ```go
> package main
> 
> import (
>   "github.com/gofiber/fiber"
> )
> 
> func main() {
>   app := fiber.New()
> 
>   type status struct {
>     Code    int32
>     Message string
>   }
> 
>    // {"Code":200,"Message":"Hello, World"}
>   app.Get("/", func(c *fiber.Ctx) {
>     if err := c.JSON(status{200, "Hello, World"}); err != nil {
>       c.Status(500).Send(err)
>     }
>   })
> 
>   type statusLwr struct {
>     Code    int32  `json:"code"`
>     Message string `json:"message"`
>   }
> 
>   // {"code":200,"message":"Hello, World"}
>   app.Get("/", func(c *fiber.Ctx) {
>     if err := c.JSON(statusLwr{200, "Hello, World"}); err != nil {
>       c.Status(500).Send(err)
>     }
>   })
> 
>   // {"code":200,"message":"Hello, World"}
>   app.Get("/", func(c *fiber.Ctx) {
>     if err := c.JSON(fiber.Map{"code": 200, "message": "Hello, World"}); err != nil {
>       c.Status(500).Send(err)
>     }
>   })
> 
>   app.Listen(3000)
> }
> ```

It worked after I change to Uppercase. Thank you for the reply.

**Comment by Fenny** [comment]
@washanhanzi, try to run `go get -u github.com/gofiber/fiber`
To see what version you are using, try to print:
```go
fmt.Println(fiber.Version)
```

If this doesn't work, delete the fiber folder `~/go/src/github.com/gofiber/fiber` and run:
`go get -u github.com/gofiber/fiber` again

**Comment by washanhanzi** [comment]
In the `go.mod` file, it says  `v1.7.0`, but the `fiber.Version` command and the logo output in the console both say `v1.6.1`. 

T_T

Also got `v1.7.0` in the go mod cache file,  `$GOPATH/pkg/mod/github.com/gofiber/fiber@v1.7.0`.

**Comment by washanhanzi** [comment]
I found the `Version` in 33th line in `application.go` maybe inconsistent with the `1.7.0` release version.

**Comment by washanhanzi** [comment]
I'm closing the issue. 

I will try to figure out the go mod. T_T

Thank you for the great framework.
