### ISSUE TITLE
How to set Nginx‘s location to proxy fiber service?

### ISSUE THREAD

**Issue by fengnex** [gofiber/fiber#1641]
**Question description**
Nginx cannot work when there are paramters in the url, and how to fix it?

**Code snippet** _Optional_

```go
Let's say we need to make Nginx as a proxy of a fiber service when request parameters are in the url:
http://hostname/api/trend/parameter
http://hostname/api/trms/parameter
http://hostname/api/real/parameter1/parameter2

A typical Nginx location seems like the following one:
location /api/ {
            proxy_pass http://ip:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header REMOTE-HOST $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

In such a case, we can only successfully access http://hostname/api/trend; and http://hostname/api/trend/parameter cannot be accessed. 
How to send the request or the whole URL to the backend fiber service?
```

**Comment by ReneWerner87** [comment]
please check our recipes:
https://github.com/gofiber/recipes/blob/master/docker-nginx-loadbalancer/nginx/nginx.conf#L14
https://github.com/gofiber/recipes/blob/master/docker-nginx-loadbalancer/api/api.go#L28-L36

or check 
https://www.nginx.com/blog/deploying-nginx-plus-as-an-api-gateway-part-1/

furthermore the question is what is the error

would recommend to look at the url which arrives in the microservice itself for debugging
```go
    app.Use(func(ctx *fiber.Ctx) error {
        return ctx.SendString(ctx.Path())
    })
```
with this snippet in the microservice you can see for each request the complete route that arrives in the service and on which the routing is based

all urls are allowed

**Comment by fengnex** [comment]
Thanks a lot for so quick response!
Your kind tips are definitely appreciated@ReneWerner87
I'm just curious why Nginx cannot pass parameters in the url to fiber service and will check it tomorrow.

**Comment by fengnex** [comment]
Thank you @ReneWerner87! Your reply was very helpful and I finally figured out one way for the problem.
Thank you very much again!
