### ISSUE TITLE
🚀 Middleware logger change stream

### ISSUE THREAD

**Issue by MichailVestnik** [gofiber/fiber#1642]
Hi! 

I write logs to files and use this command:
`go run app.go >> logs/messages.log 2>> logs/errors.log`

As we know 0 is stdin, 1 is stdout and 2 is stderr.
https://en.wikipedia.org/wiki/Standard_streams

2>> means that only errors will be written to this file.  

But all logs from the logger end up in the stderr stream. 
Maybe it is correct to send logs to stdout?

Спасибо!

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/master/middleware/logger/config.go#L56

yes right
