### ISSUE TITLE
🐛 ctx.Logger().Printf(...) is not working

### ISSUE THREAD

**Issue by cnp96** [gofiber/fiber#1651]
**Fiber version**
github.com/gofiber/fiber/v2 v2.23.0

**Issue description**
Request logger is not printing any messages

**Code snippet**

```go
package main

import (
  "github.com/gofiber/fiber/v2"
  "github.com/gofiber/fiber/v2/middleware/logger"
  "errors"
  "log"
)

func main() {
  app := fiber.New()

  app.Use(logger.New()) // This works 💯

  app.Use(func(c *fiber.Ctx) error {
    logger := c.Logger()
    
    // None of the below works 😕
    err := errors.New("test error")
    logger.Printf("error: %s", err)
    logger.Printf("Trying to print this message to console!")

    return c.Next()
  })

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
There is no method with the name
Logger() in the context.

Do not mix, the logging middleware is a middleware for logging the request and the response. 

For any logging operation you can use any other packet or even the standard logger.

**Comment by ReneWerner87** [comment]
https://pkg.go.dev/log
