### ISSUE TITLE
Absolute route should be prefered over route with parameter.

### ISSUE THREAD

**Issue by bokunodev** [gofiber/fiber#1654]
**Fiber version**
 Fiber v2.23.0

**Issue description**
I have code below, if route `/docs` comes after `/:name`, route `/docs` can not be accesed, because `/:name` always catch it.
But, since `/docs` is explecitly defined and does not have any parameter, it ***must*** be prefered.
and route order **must** not matter.

**Code snippet**

```Go
const ADDRESS = "localhost:8001"

func main() {
	app := config.NewFiber()

	app.Get("/:name", func(c *fiber.Ctx) error {
		return c.SendString(c.Params("name"))
	})

        // never reached
	app.Get("/docs", docs(app))

	app.Listen(ADDRESS)
}
```

**Comment by ReneWerner87** [comment]
Yes, this behavior is expected and the same as in expressjs, because the order of the routes is respected.

**Comment by hi019** [comment]
More info on how Express does it: https://stackoverflow.com/questions/32603818/order-of-router-precedence-in-express-js

And gorilla/mux does it in a similar way, too: http://jijeshmohan.github.io/post/gorilla-mux/

**Comment by bokunodev** [comment]
so its workig as intended and i can use third party router on top of fiber anyway.
