### ISSUE TITLE
🐛 `ctx.JSON()` Panic with Go 1.18 beta1

### ISSUE THREAD

**Issue by iredmail** [gofiber/fiber#1658]
**Fiber version**
2.23.0
**Issue description**
Same code running fine with Go 1.17.x, but panic with Go 1.18 beta1.

I don't have a working code snippet to reproduce the issue yet, sorry.
Program panic when it calls `ctx.Next()`, and the final line is:
https://github.com/gofiber/fiber/blob/master/ctx.go#L744

**Comment by renanbastos93** [comment]
Can you to put on here more details?

**Comment by iredmail** [comment]
How to reproduce the panic:

- Create an empty directory and save code below to `main.go` under the directory.
- Run commands below:

```
go mod init mymod
go mod tidy
go run main.go
```
- Visit the app from another terminal with `curl` command or a GUI web browser:
```
curl http://localhost:3000/
```

Code to reproduce the panic:

```
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

type dataset struct {
	Label           string
	BackgroundColor string
	Data            []uint64
}

func main() {
	m := map[string]interface{}{
		"_success": true,
		"labels":   []string{"11:00", "12:00"},
		"datasets": []dataset{{
			Label:           "rejected",
			BackgroundColor: "yellow",
			Data:            []uint64{0, 0},
		}},
	}

	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		return c.JSON(m)
	})

	log.Fatal(app.Listen(":3000"))
}
```

**Comment by iredmail** [comment]
Seems it's caused by the underlying json package: https://github.com/goccy/go-json
I created an issue there too: goccy/go-json#308

**Comment by iredmail** [comment]
This issue should be fixed by upstream, but i don't have time to verify it yet:
https://github.com/goccy/go-json/pull/310

By the way, any plan to rely on https://github.com/goccy/go-json package directly (add it in `go.mod`) instead of `internal/go-json/`?

**Comment by efectn** [comment]
> This issue should be fixed by upstream, but i don't have time to verify it yet: [goccy/go-json#310](https://github.com/goccy/go-json/pull/310)
> 
> By the way, any plan to rely on https://github.com/goccy/go-json package directly (add it in `go.mod`) instead of `internal/go-json/`?

I'll check it
