### ISSUE TITLE
🐛  panic: interface conversion: interface {} is *websocket.Conn, not *websocket.Conn (types from different packages)

### ISSUE THREAD

**Issue by EmreSURK** [gofiber/fiber#1661]
Fiber version: 2.23.0

I am building a backend, that except socket connection and send message to them by triggering with a get request. Apparently I have type conflict.

I added two different imports with alias but that didn't solve the problem. Please see the minimal working example and error message below.

I am using a global sync.Map variable to store connections.

```go
package main

import (
	"fmt"
	"sync"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/websocket/v2"
)

func main() {

	app := fiber.New()

	ListenSocket(app)
	app.Get("/socket/send", SendMessageController )
	app.Listen(":3000")

}
const websocketHeaderKey = "Sec-Websocket-Key"

var ConnectedIDSockets sync.Map 

func SendMessageController( c *fiber.Ctx ) error {
	ConnectedIDSockets.Range(func(key, value interface{}) bool {
		c := value.(* websocket.Conn)

		if c == nil {
			// that line is not printed, c is not nil.
			fmt.Println("c is nil.")
			return true
		}

		// we have crash at that line, even we read the err.
		err := c.WriteMessage(websocket.TextMessage, []byte("message"))

		// program does not runs to here since it crashed.
		println("err:", err)
		return true
	})
	return nil
}

func ListenSocket(app *fiber.App) {
	app.Use("/ws", func(c *fiber.Ctx) error {
		if websocket.IsWebSocketUpgrade(c) {
			c.Locals("allowed", true)
			c.Locals(websocketHeaderKey, string(c.Request().Header.Peek(websocketHeaderKey)))
			return c.Next()
		}
		return fiber.ErrUpgradeRequired
	})

	app.Get("/ws/:projectKEY", websocket.New(func(c *websocket.Conn) {

		socketID := c.Locals(websocketHeaderKey).(string)

		ConnectedIDSockets.Store(socketID, c.Conn)


		conn, _ := ConnectedIDSockets.Load(socketID)
		socketmap := conn.(*websocket.Conn) // line 65 is here.
		socketmap.WriteMessage(1, []byte(socketID))

	}))
}
```

```
panic: interface conversion: interface {} is *websocket.Conn, not *websocket.Conn (types from different packages)

goroutine 8 [running]:
main.ListenSocket.func2(0xc000181ef0)
        /Users/emre/Documents/Free/SocketServer/goExample/main.go:62 +0x112
github.com/gofiber/websocket/v2.New.func2.4(0xc000098000)
        /Users/emre/go/pkg/mod/github.com/gofiber/websocket/v2@v2.0.14/websocket.go:109 +0x75
github.com/fasthttp/websocket.(*FastHTTPUpgrader).Upgrade.func1({0x13eeec8, 0xc000098000})
        /Users/emre/go/pkg/mod/github.com/fasthttp/websocket@v1.4.3-rc.10/server_fasthttp.go:201 +0x1ad
github.com/valyala/fasthttp.hijackConnHandler({0x13e5b20, 0xc00018e4e0}, {0x13eefd0, 0xc000102008}, 0xc0002e6000, 0xc000076500)
        /Users/emre/go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/server.go:2426 +0x75
created by github.com/valyala/fasthttp.(*Server).serveConn
        /Users/emre/go/pkg/mod/github.com/valyala/fasthttp@v1.31.0/server.go:2380 +0x1cb5
exit status 2
```

**Comment by renanbastos93** [comment]
You need to treat these 2 lines 
```go
conn, _ := ConnectedIDSockets.Load(socketID)
socketmap := conn.(*websocket.Conn) // line 65 is here.
```
In golang is very important you treatment all errors.

you can try it
```go
conn, err := ConnectedIDSockets.Load(socketID)
if err != nil {
	panic(err)
}
socketmap, ok := conn.(*websocket.Conn) // line 65 is here.
if !ok {
	panic("cannot casting conn to *websocket.Conn")
}
```

**Comment by EmreSURK** [comment]
@renanbastos93 Your advise is correct but does not solves the problem, only hides it.

**Comment by renanbastos93** [comment]
I change your code with all validates.
```go
package main

import (
	"fmt"
	"reflect"
	"sync"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/websocket/v2"
)

func main() {

	app := fiber.New()

	ListenSocket(app)
	app.Get("/socket/send", SendMessageController)
	app.Listen(":3000")

}

const websocketHeaderKey = "Sec-Websocket-Key"

var ConnectedIDSockets = &sync.Map{}

func SendMessageController(c *fiber.Ctx) error {
	ConnectedIDSockets.Range(func(key, value interface{}) bool {
		c, ok := value.(*websocket.Conn)
		if !ok {
			// that line is not printed, c is not nil.
			fmt.Println("cannot casting c to *websocket.Conn")
			return true
		}

		// we have crash at that line, even we read the err.
		err := c.WriteMessage(websocket.TextMessage, []byte("message"))
		if err != nil {
			// program does not runs to here since it crashed.
			fmt.Println("cannot writemessage in Sockets Range")
			return false
		}

		return true
	})
	return nil
}

func ListenSocket(app *fiber.App) {
	app.Use("/ws", func(c *fiber.Ctx) error {
		if websocket.IsWebSocketUpgrade(c) {
			c.Locals("allowed", true)
			c.Locals(websocketHeaderKey, string(c.Request().Header.Peek(websocketHeaderKey)))
			return c.Next()
		}
		return fiber.ErrUpgradeRequired
	})

	app.Get("/ws/:projectKEY", websocket.New(func(c *websocket.Conn) {
		socketID, ok := c.Locals(websocketHeaderKey).(string)
		if !ok {
			fmt.Println("cannot casting Locals websocketHeaderKey to string")
			return
		}

		ConnectedIDSockets.Store(socketID, c.Conn)

		conn, ok := ConnectedIDSockets.Load(socketID)
		if !ok {
			fmt.Println("cannot load socksets id:", socketID)
			return
		}

		socketmap, ok := conn.(*websocket.Conn) // line 65 is here.
		if !ok {
			fmt.Println("cannot casting conn to *websocket.Conn:", reflect.TypeOf(conn))
			return
		}

		if err := socketmap.WriteMessage(1, []byte(socketID)); err != nil {
			fmt.Println("cannot write message:", err.Error())
		}

	}))
}
```

Now it not break again, but I'm trying understand with break line 65.

**Comment by renanbastos93** [comment]
Can you try another implements it?

**Comment by ReneWerner87** [comment]
@EmreSURK next time please use this space for the issue
https://github.com/gofiber/websocket/issues
proper assignment of problems is extremely important to maintain focus, channel and prioritize work on them


@EmreSURK wich golang version do you use ?
https://go-review.googlesource.com/c/go/+/123395/

do you also use go modules right ? and not gopath

could be a mixture of the packages from the go modules (vendor folder) and the go path

**Comment by EmreSURK** [comment]
> I change your code with all validates.
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"reflect"
> 	"sync"
> 
> 	"github.com/gofiber/fiber/v2"
> 	"github.com/gofiber/websocket/v2"
> )
> 
> func main() {
> 
> 	app := fiber.New()
> 
> 	ListenSocket(app)
> 	app.Get("/socket/send", SendMessageController)
> 	app.Listen(":3000")
> 
> }
> 
> const websocketHeaderKey = "Sec-Websocket-Key"
> 
> var ConnectedIDSockets = &sync.Map{}
> 
> func SendMessageController(c *fiber.Ctx) error {
> 	ConnectedIDSockets.Range(func(key, value interface{}) bool {
> 		c, ok := value.(*websocket.Conn)
> 		if !ok {
> 			// that line is not printed, c is not nil.
> 			fmt.Println("cannot casting c to *websocket.Conn")
> 			return true
> 		}
> 
> 		// we have crash at that line, even we read the err.
> 		err := c.WriteMessage(websocket.TextMessage, []byte("message"))
> 		if err != nil {
> 			// program does not runs to here since it crashed.
> 			fmt.Println("cannot writemessage in Sockets Range")
> 			return false
> 		}
> 
> 		return true
> 	})
> 	return nil
> }
> 
> func ListenSocket(app *fiber.App) {
> 	app.Use("/ws", func(c *fiber.Ctx) error {
> 		if websocket.IsWebSocketUpgrade(c) {
> 			c.Locals("allowed", true)
> 			c.Locals(websocketHeaderKey, string(c.Request().Header.Peek(websocketHeaderKey)))
> 			return c.Next()
> 		}
> 		return fiber.ErrUpgradeRequired
> 	})
> 
> 	app.Get("/ws/:projectKEY", websocket.New(func(c *websocket.Conn) {
> 		socketID, ok := c.Locals(websocketHeaderKey).(string)
> 		if !ok {
> 			fmt.Println("cannot casting Locals websocketHeaderKey to string")
> 			return
> 		}
> 
> 		ConnectedIDSockets.Store(socketID, c.Conn)
> 
> 		conn, ok := ConnectedIDSockets.Load(socketID)
> 		if !ok {
> 			fmt.Println("cannot load socksets id:", socketID)
> 			return
> 		}
> 
> 		socketmap, ok := conn.(*websocket.Conn) // line 65 is here.
> 		if !ok {
> 			fmt.Println("cannot casting conn to *websocket.Conn:", reflect.TypeOf(conn))
> 			return
> 		}
> 
> 		if err := socketmap.WriteMessage(1, []byte(socketID)); err != nil {
> 			fmt.Println("cannot write message:", err.Error())
> 		}
> 
> 	}))
> }
> ```
> 
> Now it not break again, but I'm trying understand with break line 65.

Hi, it is not crashing because it does not do anything :) It just skips the code.

**Comment by EmreSURK** [comment]
> @EmreSURK next time please use this space for the issue https://github.com/gofiber/websocket/issues proper assignment of problems is extremely important to maintain focus, channel and prioritize work on them
> 
> @EmreSURK wich golang version do you use ? https://go-review.googlesource.com/c/go/+/123395/
> 
> do you also use go modules right ? and not gopath
> 
> could be a mixture of the packages from the go modules (vendor folder) and the go path


So, you are considering that is not a bug, right? 
That issue does not contain anything except code example on README. 

Yes, I am using go modules. I downloaded the official golang container from docker.com to be sure.

**Comment by EmreSURK** [comment]
To be sure about using the same package around the code I changed the alias of the library: 




```
package main

import (
	"fmt"
	"sync"

	fiberLibrary "github.com/gofiber/fiber/v2"
	fiberWebsocketLibrary "github.com/gofiber/websocket/v2"
)

func main() {

	app := fiberLibrary.New()

	ListenSocket(app)
	app.Get("/socket/send", SendMessageController)
	app.Listen(":3000")

}

const websocketHeaderKey = "Sec-Websocket-Key"

var ConnectedIDSockets sync.Map

func SendMessageController(c *fiberLibrary.Ctx) error {
	ConnectedIDSockets.Range(func(key, value interface{}) bool {
		c := value.(*fiberWebsocketLibrary.Conn)

		if c == nil {
			// that line is not printed, c is not nil.
			fmt.Println("c is nil.")
			return true
		}

		// we have crash at that line, even we read the err.
		err := c.WriteMessage(fiberWebsocketLibrary.TextMessage, []byte("message"))

		// program does not runs to here since it crashed.
		println("err:", err)
		return true
	})
	return nil
}

func ListenSocket(app *fiberLibrary.App) {
	app.Use("/ws", func(c *fiberLibrary.Ctx) error {
		if fiberWebsocketLibrary.IsWebSocketUpgrade(c) {
			c.Locals("allowed", true)
			c.Locals(websocketHeaderKey, string(c.Request().Header.Peek(websocketHeaderKey)))
			return c.Next()
		}
		return fiberLibrary.ErrUpgradeRequired
	})

	app.Get("/ws/:projectKEY", fiberWebsocketLibrary.New(func(c *fiberWebsocketLibrary.Conn) {

		socketID := c.Locals(websocketHeaderKey).(string)

		ConnectedIDSockets.Store(socketID, c.Conn)

		conn, _ := ConnectedIDSockets.Load(socketID)
		socketmap := conn.(*fiberWebsocketLibrary.Conn) // line 65 is here.
		socketmap.WriteMessage(1, []byte(socketID))

	}))
}
```

**Comment by ReneWerner87** [comment]
Instead of
```go
ConnectedIDSockets.Store(socketID, c.Conn)
```
use 
```go
ConnectedIDSockets.Store(socketID, c)
``` 

Otherwise you save the connection of the connection and this is from the fasthttp websocket packet, so it reports a mismatch

Because the conn from the fasthttp/websocket packet is not the same as the conn from the fiber/websocket packet. (unfortunately the packet names and struct names are the same in this case, so it's hard to notice.

**Comment by EmreSURK** [comment]
@ReneWerner87 Thank you but I already tried it, the same thing happens.

**Comment by ReneWerner87** [comment]
with you origin code:
![image](https://user-images.githubusercontent.com/7063188/149491290-939692c5-a864-4c76-99d6-f3d736aba0a9.png)


with the adjustment i had suggested:
![image](https://user-images.githubusercontent.com/7063188/149491502-edcfda4f-6f31-4b07-983f-e85b5cb1e4fa.png)


@EmreSURK to me it looks like you are simply storing away the wrong part of the connection inside

if you need the other part from the gorilla websocket (conn.conn) repository you can do that too, then you just have to make an import above and direct the type casting to the code of the import

**Comment by najamsk** [comment]
Basically problem is fiber is using another type of web socket connection(type and packages) while gorilla is using websocket that is compatible with golang websocket package. 

now if someone has full api written in go fiber and they love the promise of fiber that is good. Problem arise if you are using something ike json rpc which rely on standard websocket connection  (implementing readwritecloser interface). 

if somehow we can swap underlaying websocket lib while booting up go giber that would be great in terms of people can have default and choice to replacee that default.
