### ISSUE TITLE
🚀 Split app.Listen() into separated Listen() & Serve() methods for better error handling

### ISSUE THREAD

**Issue by GalvinGao** [gofiber/fiber#1663]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Separate effects that has currently bundled with `app.Listen()` into separated `Listen()` and `Serve()` methods for better error handling, since `app.Listen()` will simply block if there's no error, and return one if there's one. This is not quite easy for handling the error for strict lifecycle handling applications, e.g. the ones built with https://github.com/uber-go/fx. To mitigate this issue, simply separating would be feasible.

**Describe alternatives you've considered**
- Maybe stay with the same convention from `net/http` where a `ListenAndServe()` will be used instead for the current `Listen()` behavior? But this *might* introduce backward compatibility issues so maybe consider involve it in the next major release?
- Trying to spin up the fiber server from the user's perspective *manually* is not really doable, since the required methods are all private ones.

**Additional context**
I'm using https://github.com/uber-go/fx for dependency injection here with fiber (it works great!), except that when the server launches I have to manually specify a timeout for spinning the fiber server up in order to both catch the error and also let fx know, in a meaningful amount of time, that the fiber server is actually started. If the one is interested [here's my implementation on it](https://github.com/penguin-statistics/backend-next/blob/12ae1a44255755aa67ad453e566f1f870322c01b/cmd/service/run.go?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L17-L31).

**Comment by ReneWerner87** [comment]
@GalvinGao you are welcome to prepare a pull request, but please try to stay as downward compatible as possible

**Comment by DarthBenro008** [comment]
@GalvinGao, there is already an function for that, and you can find the below snippet for your usecase

```go
func main() {
	app := fiber.New()
	app.Get("/hello", func(c *fiber.Ctx) error {
		return c.SendString("Testing")
	})
	ln, err := net.Listen("tcp", ":8080")
	if err != nil {
		// handle your error
	}
	err = app.Listener(ln)
	if err != nil {
		log.Fatal("App crashed")
	}
}
```
The relevant codebase is present here: 
https://github.com/gofiber/fiber/blob/5766feef29be223835cb8bb31ea6ad497afd47cd/app.go#L745-L764

With this we do not have to split `Listen()` and `Serve()`, you can create your own listener and pass that later onto `App`

**Comment by GalvinGao** [comment]
> @GalvinGao, there is already an function for that, and you can find the below snippet for your usecase
> 
> ```go
> func main() {
> 	app := fiber.New()
> 	app.Get("/hello", func(c *fiber.Ctx) error {
> 		return c.SendString("Testing")
> 	})
> 	ln, err := net.Listen("tcp", ":8080")
> 	if err != nil {
> 		// handle your error
> 	}
> 	err = app.Listener(ln)
> 	if err != nil {
> 		log.Fatal("App crashed")
> 	}
> }
> ```
> 
> The relevant codebase is present here:
> 
> https://github.com/gofiber/fiber/blob/5766feef29be223835cb8bb31ea6ad497afd47cd/app.go#L745-L764
> 
> With this we do not have to split `Listen()` and `Serve()`, you can create your own listener and pass that later onto `App`

Ohhh I see. That's very helpful then and I sure think it suits my needs. Thanks for posting this comment!

Closing issue as this is already resolved :D
