### ISSUE TITLE
🐛 websocket close fail

### ISSUE THREAD

**Issue by luyouxin84** [gofiber/fiber#1668]
**Fiber version**
        "github.com/gofiber/fiber/v2"
	"github.com/gofiber/websocket/v2"

**Issue description**
   c := *websocket.Conn
   c.Close() do not close connect and has not error return

**Code snippet**
```go
app.Get("/ws", websocket.New(func(c *websocket.Conn) {
		// When the function returns, unregister the client and close the connection
		defer func() {
			unregister <- c
			c.Close()
		}()
		register <- c
		for {
			messageType, message, err := c.ReadMessage()
			if err != nil {
				if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway, websocket.CloseAbnormalClosure) {
					log.Println("read error:", err)
				}

				return // Calls the deferred function, i.e. closes the connection on error
			}

			if messageType == websocket.TextMessage {
				// Broadcast the received message
				broadcast <- string(message)
			} else {
				log.Println("websocket message received of type", messageType)
			}
		}
	}))

```
    

this is code from your example: https://github.com/gofiber/recipes/blob/master/websocket-chat/main.go..
u can call c.Close() immediately but websocket still alive

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/147571955-b6b362a4-dd82-486c-a8db-487c705b3db2.png)

but i think you are right, there is one more line missing in the example in the part where we do the close
```go
connection.WriteMessage(websocket.CloseMessage, []byte{})
```
the connection must receive the message that it is closed

the net.connection probably does not do that

maybe this is also something for the fasthttp packet

**Comment by ReneWerner87** [comment]
can you ask in https://github.com/fasthttp/websocket for the right behaviour

**Comment by luyouxin84** [comment]
> can you ask in https://github.com/fasthttp/websocket for the right behaviour

ok
