### ISSUE TITLE
🤗 No required module provides package github.com/gofiber/fiber/v2/middleware/crsf

### ISSUE THREAD

**Issue by jzyzxx** [gofiber/fiber#1669]
**Question description**
`No required module provides package github.com/gofiber/fiber/v2/middleware/crsf`
**Code snippet** _Optional_

`package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/limiter"
	"github.com/gofiber/fiber/v2/middleware/compress"
	"github.com/gofiber/fiber/v2/middleware/crsf"
	// "gorm.io/gorm"
	"gowork/goadmin/services/controllers/user"
	// "gowork/goadmin/services/orm"
	// "time"
)

func main() {
	app := fiber.New()
	app.Use(limiter.New())
	app.Use(compress.New())
	app.Use(csrf.New()) // Default config
	app.Get(user.Path, func(c *fiber.Ctx) error {
		fmt.Println(user.Login(c))
		return c.SendString(user.Login(c))
	})
	app.Listen(":9999")
	// db := orm.GetDb()
	// type User struct {
	// 	gorm.Model
	// 	Name     string    `gorm:"type:char(30);comment:'姓名'"`
	// 	Age      int       `gorm:"age"`
	// 	Birthday time.Time `gorm:"birthday"`
	// }
	// db.Migrator().CreateTable(&User{})
	// user := User{Name: "Jinzhu", Age: 18, Birthday: time.Now()}
	// result := db.Create(&user) // 通过数据的指针来创建
	// fmt.Println(result)
}`

**Comment by hi019** [comment]
It should be "github.com/gofiber/fiber/v2/middleware/csrf"

**Comment by ReneWerner87** [comment]
Thx @hi019 , he is right, there is a typo in the import
