### ISSUE TITLE
Problem in BodyParser call when running in test mode 

### ISSUE THREAD

**Issue by fraviofii** [gofiber/fiber#1670]
**Question description**

I am trying to implement an integration test for my backend using gofiber framework. I'm using VSCode and debug tools, so I could stop where the problem is happening.

**Test procedure** _Optional_

```go
form := map[string]string{"data": "1234"}
var body io.Reader
var ct string
ct, body, err = createForm(form)
assert.Equalf(t, nil, err, "Preparing auth form request")
var req *http.Request
req, err = http.NewRequest("POST", "/test_call", body)
assert.Equalf(t, nil, err, "Preparing auth request")
req.Header.Add("Content-Type", ct)
resp, err := app.Test(req, 10)
assert.Equalf(t, nil, err, "Problem running the test: %v\n", err)
assert.Equal(t, 200, resp.StatusCode)
```

The `app` is initialized in TestMain() function, together with the router setup. In the handler call, I have the following:

**Handler code** _Optional_

```go
type DataInput struct {
	Data    string `json:"data" validate:"required"`
}

func Handler(c *fiber.Ctx) error {
	input := new(DataInput)
	if err := c.BodyParser(input); err != nil {
		return c.SendStatus(fiber.StatusUnauthorized)
	}
        return c.SendStatus(fiber.StatusOk)
}
```

When I run `go test`, I have the following output:

```
Messages:       Problem running the test: test: timeout error 1000ms
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x10323e734]
```

Using debug mode from VSCode, I can see that `decodePool` is not initialized. I don't know if it is correct, and I can't find any place where this call is initialized.

When running the final application, everything works correctly. Maybe the call `app.Listen` let everything set correctly, instead of `app.Test`. Or the function `BodyParser` should not me used.

Can somebody give me some advice?

**Comment by ReneWerner87** [comment]
Default timeout of the test method is 1 second, as if you are debugging you should set this to -1 to disable the timeout.

Decoder is setup in a sync pool
https://github.com/gofiber/fiber/blob/master/ctx.go#L289

https://github.com/gofiber/fiber/blob/master/ctx.go#L322

And reused between several requests.

**Comment by ReneWerner87** [comment]
Here some examples https://github.com/gofiber/recipes/blob/master/unit-test/main_test.go

https://github.com/gofiber/fiber/blob/7b7dcf29f79f185416325b62fad8cedf0b800b07/ctx_test.go#L848

https://github.com/gofiber/fiber/blob/7b7dcf29f79f185416325b62fad8cedf0b800b07/ctx_test.go#L823

**Comment by fraviofii** [comment]
Thank you @ReneWerner87 .

In this case, I replaced the timeout to -1 and everything started to work.
