### ISSUE TITLE
🚀 List all routes when server starts

### ISSUE THREAD

**Issue by vecpeng** [gofiber/fiber#1675]
**Is your feature request related to a problem?**
Is there any way to list all routes when server starts, like this:
![image](https://user-images.githubusercontent.com/56476336/147659983-661cc80e-34d5-4252-8afd-92f12797f6a3.png)
**Describe the solution you'd like**
**Describe alternatives you've considered**
**Additional context**
I think it is useful and maybe I can give a pull request for it if maintainers agree.

**Comment by ReneWerner87** [comment]
Can you provide this in the form of a middleware or features flag in config so that it is optimal

**Comment by vecpeng** [comment]
Ok, I will add a flag in config.
