### ISSUE TITLE
🤗 How to execute the middleware only once？

### ISSUE THREAD

**Issue by solo-xwz** [gofiber/fiber#1676]
**Question description**
I want to set up a jwt middleware, but when the check succeeds and returns c.NEXT(), the middleware will be executed again after the response. How to avoid it?

**Comment by ReneWerner87** [comment]
The middleware should be executed only once per request if you have registered it once

**Comment by solo-xwz** [comment]
When I use it in app.Use, it will only be executed once ,but executed after response:
`app.Use(middlewares.CheckAccessToken())

func CheckAccessToken() func(*fiber.Ctx) error {
	return jwtware.New(jwtware.Config{
		SigningKey:    pubKey,
		SigningMethod: "HS256",
		ContextKey:    "token",
		ErrorHandler:  jwtError,
		SuccessHandler: func(c *fiber.Ctx) error {
			token := c.Locals("token").(*jwt.Token)
			jwtClaims := token.Claims.(jwt.MapClaims)
			userid := jwtClaims["id"]
	
			if userid == nil || userid == "" {
				return errors.New("jwt payload error")
			}
			return c.Next()
		},
	})
}
`

when I use it in the group, it will be executed twice:
`app.Group("/account",middlewares.CheckAccessToken())`

**Comment by ReneWerner87** [comment]
So you register it in the group and with app.use? Or was that an either or?

**Comment by solo-xwz** [comment]
> So you register it in the group and with app.use? Or was that an either or?

These are two situations, and two results were got

**Comment by ReneWerner87** [comment]
Ok, have you tested this behavior with a self written dummy middleware? Is it the same?

**Comment by solo-xwz** [comment]
> Ok, have you tested this behavior with a self written dummy middleware? Is it the same?

yes, it's the same

**Comment by ReneWerner87** [comment]
Ok interesting, can you post a complete example for me (single main.go with everything)

**Comment by solo-xwz** [comment]
> Ok interesting, can you post a complete example for me (single main.go with everything)

I found the problem. 
Because I registered the middleware after initializing the route, it was normal after adjusting the order.
Thanks!
