### ISSUE TITLE
🚀 Early Access For HTTP2

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#1683]
Example :
```go
   app := fiber.New(fiber.Config{
        EnableHTTP2: true,
    })
```
 HTTP2 should be openable for early access. This feature probably will improve process. 
PR : #1688

**Comment by efectn** [comment]
@ReneWerner87 If you're OK, i can send PR. Also should we add dgrr/http2 to go.mod or internal dir?

**Comment by ReneWerner87** [comment]
Yes, iam ok with a PR

Add it to the go.mod

**Comment by ReneWerner87** [comment]
@balcieren and @efectn
You both worked on a pull request at the same time, would be cool if you could coordinate (maybe via discord) and both work on it together.

**Comment by balcieren** [comment]
> @balcieren and @efectn
> You both worked on a pull request at the same time, would be cool if you could coordinate (maybe via discord) and both work on it together.

Ok @ReneWerner87  . We are going to work together. Also we are going to work on same pull request.

**Comment by vecpeng** [comment]
Maybe there should be a new branch for this feature.

**Comment by itzikiusa** [comment]
Hi,
Will this prevent server failures when using http client to send requests via http 2?

**Comment by balcieren** [comment]
> Hi,
> Will this prevent server failures when using http client to send requests via http 2?
> 

We need to http2 transport for http client.

**Comment by balcieren** [comment]
> Example :
> 
> ```go
>    app := fiber.New(fiber.Config{
>         HTTP2: true,
>     })
> ```
> 
> HTTP2 should be openable for early access. This feature probably will improve process. #1688

#1688

**Comment by efectn** [comment]
closed by https://github.com/gofiber/fiber/pull/1688#issuecomment-1013701045
