### ISSUE TITLE
fiber.NewError()'s message should be interface{}

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#1695]
If I want to return multiple validation errors in array, it is not possible with fiber.NewError(). Because NewError() only support string type.

We should be able to do

Example:

```go
fiber.NewError(
	fiber.StatusBadRequest,
        []string{"validation error 1", "validation error 2"},
)
```

**Comment by ReneWerner87** [comment]
maybe a function that is called "fiber.NewError**s**("
