### ISSUE TITLE
🤗 Prefork question when using mysql pool

### ISSUE THREAD

**Issue by skadiD** [gofiber/fiber#1696]
**Question description**
I'm trying to use gorm mysql pool while `prefork ` is active , then i find `fiber.isChild()` and write my init code in master process. But it doesn't work
What should i do next ?
**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
	app := fiber.New(fiber.Config{
		Prefork:       true,
		CaseSensitive: true,
		StrictRouting: true,
	})
	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		MaxAge:       10000,
	}))
	if !fiber.IsChild() { // db init and assign to global val
		globals.DB = db.Init()
		globals.Redis = db.RedisInit()
	}
	// router register...
	log.Fatal(app.Listen(globals.Setting.Server.Port))
}
```

**Comment by ReneWerner87** [comment]
what do you want to achieve and what do you expect?

don't think you need the check, all child processes also need a database connection if they are to process data.

**Comment by skadiD** [comment]
yep,i move child check and it works right
