### ISSUE TITLE
🐛  UUID in a struct being returned in wrong format

### ISSUE THREAD

**Issue by Akaike** [gofiber/fiber#1697]
**Fiber version**
v2.24.0
**Issue description**
When returning an object which has an ID with type uuid.UUID (google/uuid), ctx.JSON returns the ID completely wrong.

![image](https://user-images.githubusercontent.com/2933354/148660682-78455cfd-882f-4871-876c-47ce30d84a05.png)

As you can see it should return 09b9aa47-3f7d-4f07-a3ee-c2ebc0aeca80 but instead it is just something else.

If I convert the UUID into a string before returning, it works. Is this intended or am I doing here something wrong?
log.Print returns the object correctly with the correct ID. When I do return ctx.JSON(project.ID) it works too.

**Code snippet**

Snippet of the controller/handler: 
```go
project, err := c.service.Get(ctx.Params("id"), user.ID)
	if err != nil {
		return ctx.Status(fiber.ErrInternalServerError.Code).JSON(util.Message(fiber.ErrInternalServerError.Code, err.Error()))
	}

	return ctx.Status(fiber.StatusOK).JSON(project)
```

project struct:
```go
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
```

Try it to reproduce with:
```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
)

type config struct {
	// debug enable a debug logging.
	debug bool
	// log used for logging on debug mode.
	log func(...interface{})
}

type res struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time   `json:"updated_at,omitempty"`
	Edges     interface{} `json:"edges,omitempty"`
}

func main() {
	app := fiber.New()
	app.Get("/", h)
	log.Fatal(app.Listen(":3001"))
}

func h(c *fiber.Ctx) error {
	u := uuid.New()

	test := res{
		ID:   u,
		Name: "test",
	}

	fmt.Println(test.ID) // not same as response
	return c.Status(fiber.StatusOK).JSON(test)
}
```

**Comment by hi019** [comment]
Hey. I'm not able to reproduce this:

```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
)

var app = fiber.New()

type res struct {
	ID uuid.UUID `json:"id"`
}

func main() {
	app.Get("/", h)

	log.Fatal(app.Listen(":3001"))
}

func h(c *fiber.Ctx) error {
	u := uuid.New()
	fmt.Println(u.String()) // same as response

	return c.JSON(res{u})
}
```

**Comment by Akaike** [comment]
@hi019 ,
Hm, yeah. I can't reproduce it too with your code. It must have something to do with entgo then. I will close the ticket then for now until I figure out what is exactly the issue.

Thank you

**Comment by Akaike** [comment]
@hi019 
Can you try to reproduce the error with this code, I think I found the problem. It is entgo, it creates entity structs with some  extra properties, but I could imagine that someone could also create something similar without entgo:
```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
)

type config struct {
	// debug enable a debug logging.
	debug bool
	// log used for logging on debug mode.
	log func(...interface{})
}

type res struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time   `json:"updated_at,omitempty"`
	Edges     interface{} `json:"edges,omitempty"`
}

func main() {
	app := fiber.New()
	app.Get("/", h)
	log.Fatal(app.Listen(":3001"))
}

func h(c *fiber.Ctx) error {
	u := uuid.New()

	test := res{
		ID:   u,
		Name: "test",
	}

	fmt.Println(test.ID) // not same as response
	return c.Status(fiber.StatusOK).JSON(test)
}
```

**Comment by hi019** [comment]
Looks like an issue with our upstream JSON marshaller. I've filed https://github.com/goccy/go-json/issues/318

**Comment by hi019** [comment]
In the meantime, you can set `JSONEncoder` in fiber.Config to `json.Marshal` from `encoding/json`

**Comment by Akaike** [comment]
> In the meantime, you can set `JSONEncoder` in fiber.Config to `json.Marshal` from `encoding/json`. Decoding will be a lot slower, so you could also use a faster json marshaller like https://github.com/segmentio/encoding

Thank you a lot! :)

**Comment by vecpeng** [comment]
> @hi019 Can you try to reproduce the error with this code, I think I found the problem. It is entgo, it creates entity structs with some extra properties, but I could imagine that someone could also create something similar without entgo:
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"log"
> 	"time"
> 
> 	"github.com/gofiber/fiber/v2"
> 	"github.com/google/uuid"
> )
> 
> type config struct {
> 	// debug enable a debug logging.
> 	debug bool
> 	// log used for logging on debug mode.
> 	log func(...interface{})
> }
> 
> type res struct {
> 	config `json:"-"`
> 	// ID of the ent.
> 	ID uuid.UUID `json:"id,omitempty"`
> 	// Name holds the value of the "name" field.
> 	Name string `json:"name,omitempty"`
> 	// Description holds the value of the "description" field.
> 	Description string `json:"description,omitempty"`
> 	// CreatedAt holds the value of the "created_at" field.
> 	CreatedAt time.Time `json:"created_at,omitempty"`
> 	// UpdatedAt holds the value of the "updated_at" field.
> 	UpdatedAt time.Time   `json:"updated_at,omitempty"`
> 	Edges     interface{} `json:"edges,omitempty"`
> }
> 
> func main() {
> 	app := fiber.New()
> 	app.Get("/", h)
> 	log.Fatal(app.Listen(":3001"))
> }
> 
> func h(c *fiber.Ctx) error {
> 	u := uuid.New()
> 
> 	test := res{
> 		ID:   u,
> 		Name: "test",
> 	}
> 
> 	fmt.Println(test.ID) // not same as response
> 	return c.Status(fiber.StatusOK).JSON(test)
> }
> ```
> 
> The response from fiber will be: 00000000-0000-0000-0000-000000000000
> 
> When you remove the config from the struct, it works again.

Add omitempty in the config `json: -` seems works.
