### ISSUE TITLE
🤗 Error loading template in official example (Template Engines)

### ISSUE THREAD

**Issue by goofcc** [gofiber/fiber#1699]
**Question description**
error: cannot use engine (variable of type *"github.com/gofiber/template/html".Engine) as fiber.Views value in struct literal: missing method LoadcompilerInvalidIfaceAssign

**Code snippet** _Optional_

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/html"
)

func main() {
	engine := html.New("./templattes", ".html")
        app := fiber.New(fiber.Config{
            Views: engine,// the error occurred here...
        })

	app.Get("/", func(c *fiber.Ctx) error {
		return c.Render("index", fiber.Map{
			"Title": "Hello, World!",
		})
	})

	log.Fatal(app.Listen(":3000"))
}


```

**Comment by ReneWerner87** [comment]
@goofcc 
![image](https://user-images.githubusercontent.com/7063188/148744609-6dab3b16-9afc-4be2-9a06-87d021c58f2c.png)
its working on my machine

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/148744801-68fb1f71-34ab-42ed-88e7-d9603bb6dcb8.png)

**Comment by ReneWerner87** [comment]
please try 

`go clean --modcache`

and 
`go mod vendor && go mod download && go mod tidy`
on your shell

**Comment by goofcc** [comment]
@ReneWerner87 Hello, thank you very much for your help, it is true that my library is relatively old, and it can run correctly after the update, thank you.
