### ISSUE TITLE
🐞 go get not resolve package

### ISSUE THREAD

**Issue by renanbastos93** [gofiber/fiber#170]
Well, I were to try using a new version this lib but when executing `go get github.com/gofiber/fiber` it goes to get the old beta version but I need the latest version ~~`v1.0.0`~~ `v1.7.1`

**Comment by hyingreborn** [comment]
Change 1.7.0 to 1.0.1 in go.mod file，then...
```bash
go clean -modcache
go mod tidy
go mod download
```

**Comment by Fenny** [comment]
```
go clean --modcache
go get -u github.com/gofiber/fiber
```

**Comment by renanbastos93** [comment]
this approach doesn't work, I test all suggest from you
I made go get -u github.com/gofiber/fiber@v1.0.1 and was success
