### ISSUE TITLE
🚀 404 should be handled by ErrorHandler

### ISSUE THREAD

**Issue by fanybook** [gofiber/fiber#1704]
**Is your feature request related to a problem?**
```go
	// If c.Next() does not match, return 404
	_ = c.SendStatus(StatusNotFound)
	_ = c.SendString("Cannot " + c.method + " " + c.pathOriginal)

	// If no match, scan stack again if other methods match the request
	// Moved from app.handler because middleware may break the route chain
	if !c.matched && methodExist(c) {
		err = ErrMethodNotAllowed
	}
```
**Describe the solution you'd like**
```go
	// If no match, scan stack again if other methods match the request
	// Moved from app.handler because middleware may break the route chain
	if !c.matched && methodExist(c) {
		err = ErrMethodNotAllowed
	} 

        // If c.Next() does not match, return 404
        err = ErrNotFound
        err.Message = "Cannot " + c.method + " " + c.pathOriginal
```

**Describe alternatives you've considered**

**Additional context**

**Comment by hi019** [comment]
Hi. Does this help? https://github.com/gofiber/fiber/issues/748#issuecomment-687521205

**Comment by fanybook** [comment]
@hi019 

I've seen [#748 (comment)](https://github.com/gofiber/fiber/issues/748), it means `404 Not Found is not an error according to the RFC`

but, how to custom 404 handler when undefined a uri in route


gin has a "NoRoute" func

```go
	// 处理 404
	app.NoRoute(func(c *gin.Context) {
		c.JSON(http.StatusNotFound, gin.H{
			"message": "Not Found",
		})
	})
```

**Comment by fanybook** [comment]
@hi019 

like this, use a custom 404 handler at router tail
```go
    app.Use(func(ctx *fiber.Ctx) error {
        ctx.Status(404).JSON(fiber.Map{
            "code":    404,
            "message": "Resource Not Found",
        })

        return nil
    })
```

**Comment by hi019** [comment]
Yes that should work, did you try it?

**Comment by fanybook** [comment]
@hi019  i tried it, it can work

but, 405 is a err,  404 isn't a err, is that reasonable?

if use a custom 404 handler  at router tail, there are other hanlders behind it?

**Comment by WLun001** [comment]
40x should not consider as error. it should place at the last, below all other functions

> Does this work? [#748 (comment)](https://github.com/gofiber/fiber/issues/748#issuecomment-687503079) (we should probably add this to the docs too)

We have it on the docs https://docs.gofiber.io/extra/faq#how-do-i-handle-custom-404-responses
