### ISSUE TITLE
🐛 Can't retrieve underscore/snakecase json key in bodyParser

### ISSUE THREAD

**Issue by fncolon** [gofiber/fiber#1705]
I was not able to use `password_confirmation` as one of multipart form body using snake_case.

```go
type request struct {
  Fullname             string `json:"fullname" validate:"required"`
  Email                string `json:"email" validate:"required,email"`
  Password             string `json:"password" validate:"required"`
  PasswordConfirmation string `json:"password_confirmation" validate:"required"`
}

var body request

if err := c.BodyParser(&body); err != nil {
   return err
}
```

**Comment by ReneWerner87** [comment]
for
> multipart form body

please use the annotation "form"

type request struct {
  Fullname             string `json:"fullname" form:"fullname" validate:"required"`
  Email                string `json:"email" form:"email" validate:"required,email"`
  Password             string `json:"password" form:"password" validate:"required"`
  PasswordConfirmation string `json:"password_confirmation" form:"password_confirmation" validate:"required"`
}

**Comment by fncolon** [comment]
> for
> 
> > multipart form body
> 
> please use the annotation "form"
> 
> ```go
> type request struct {
>   Fullname             string `json:"fullname" form:"fullname" validate:"required"`
>   Email                string `json:"email" form:"email" validate:"required,email"`
>   Password             string `json:"password" form:"password" validate:"required"`
>   PasswordConfirmation string `json:"password_confirmation" form:"password_confirmation" validate:"required"`
> }
> ```

Email, fullname and password is working without `form` but this answer solve my problem, big thanks!

**Comment by ReneWerner87** [comment]
content-type: application/json
-> annotation alias: json

content-type: application/x-www-form-urlencoded
-> annotation alias: form

content-type: multipart/form-data
-> annotation alias: form

content-type: text/xml || application/xml
-> annotation alias: xml
