### ISSUE TITLE
🐞 App instance haven't Recover() method

### ISSUE THREAD

**Issue by hyingreborn** [gofiber/fiber#171]
**Fiber version/commit**
v1.0.1

**Issue description**

**Expected behavior**

**Steps to reproduce**

**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  app.Recover(func(c *fiber.Ctx){
    // ...
  })
}
```

**Comment by Fenny** [comment]
@hyingreborn, nice catch. It got lost in v0.7.0.
I added Recover on both App & Group in `v1.0.0` +
