### ISSUE TITLE
🚀 c.Scheme() and c.Protocol() 

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#1712]
### Feature 1
```go
	app.Get("/", func(c *Ctx) error {
		return c.JSON(c.Scheme()) // return "http" or "https"
	})
```
`c.Scheme()` is going to return fasthttp request uri's scheme.

---
### Feature 2 (Actually Update)
```go
	app.Get("/", func(c *Ctx) error {
		return c.JSON(c.Protocol()) // return "HTTP/1.1" or "HTTP/2.0"
	})
```
`c.Protocol()` return `http` or `https` normally. I think, c.Protocol should return `HTTP/1.1` or `HTTP/2.0`. Because fasthttp request header's protocol return `HTTP/1.1.` or `HTTP/2.0`. 

If you think like me, I can help for PR.

**Comment by abhi12299** [comment]
If no one is assigned to this, I can take this up.

**Comment by abhi12299** [comment]
@ReneWerner87 just to reconfirm, the `Protocol` method currently returns http/https and changing it for a differently named method `Scheme` will be a major change in the public API. Is that what is expected from this PR?

**Comment by balcieren** [comment]
> @ReneWerner87 just to reconfirm, the `Protocol` method currently returns http/https and changing it for a differently named method `Scheme` will be a major change in the public API. Is that what is expected from this PR?

I think this should wait to v3

**Comment by ReneWerner87** [comment]
can also inform in the next release version, think so many do not use these methods

**Comment by abhi12299** [comment]
@ReneWerner87 I made a PR. Can you review it?
