### ISSUE TITLE
Support text/plain MIME-type for GLSL shaders

### ISSUE THREAD

**Issue by MichailVestnik** [gofiber/fiber#1716]
Hi ! 

# Issue
Some JS libraries and WebGL use GLSL shaders. Most often they are imported as a module. 

```js
import three from './libs/three.js' // js
import fragment from './shaders/fragment.glsl' // shader
```

The Fiber doesn't understand shaders MIME-type!

спасибо!

**Comment by hi019** [comment]
Hi, can't you just set the content type to text/plain? `ctx.Set(fiber.HeaderContentType, fiber.MIMETextPlain)`

**Comment by MichailVestnik** [comment]
> 

Hi. GLSL shaders are static content, like CSS, so I don't know how to make the right mime-type...
This code returns an html page that contains js working with WebGL shaders.

```go
func Index(context *fiber.Ctx) error {
	return context.Render("index", fiber.Map{
		"example": "Example string",
	})
}
```

I think that support in Fiber correct processing of shaders still does not hurt!

**Comment by ReneWerner87** [comment]
> > 
> 
> Hi. GLSL shaders are static content, like CSS, so I don't know how to make the right mime-type... This code returns an html page that contains js working with WebGL shaders.
> 
> ```go
> func Index(context *fiber.Ctx) error {
> 	return context.Render("index", fiber.Map{
> 		"example": "Example string",
> 	})
> }
> ```
> 
> I think that support in Fiber correct processing of shaders still does not hurt!

the type should be text or ? have you tried something like this ? @MichailVestnik 
```go
    app.Get("/test", func(context *fiber.Ctx) error {
        err := context.Render("index", fiber.Map{
            "example": "Example string",
        })
        if err != nil {
            return err
        }
        context.Type("txt") // or context.Set(fiber.HeaderContentType, fiber.MIMETextPlain)
        return nil
    })
  ```

**Comment by MichailVestnik** [comment]
I'll try to explain in steps:

## 1: handler
```go
app.Get("/test", func(context *fiber.Ctx) error {
        return context.Render("index", fiber.Map{
            "example": "Example string",
        })
    })
```

 ## 2: HTML. 
On line 16 I load JavaScript with the type of module.

![Снимок экрана от 2022-01-22 14-36-35](https://user-images.githubusercontent.com/87961969/150626450-3ca4f3d5-1e24-4e1e-b376-099e4e2d09f2.png)

## 3: JS
![Снимок экрана от 2022-01-22 14-37-47](https://user-images.githubusercontent.com/87961969/150626534-91c77985-6328-4d10-8748-3bc0ae729f73.png)

## 4: Start and Result
![Снимок экрана от 2022-01-22 14-34-14](https://user-images.githubusercontent.com/87961969/150626572-cf863054-5350-4c27-82cf-eec56dc34a73.png)

"Module download was blocked due to unresolved MIME-type(text/plain)". 

Some frameworks load rare types correctly, (wasm, glsl...), some have a problem. 
 In fact, the problem is solved simply by storing the shader file in a single JS variable using interpolation. 

```js
const fragment = `attribute vec2 a_position;

void main() {
    gl_Position = vec4( a_position, 0, 1 );
}`
```

But if you work a lot with graphics, it's not convenient.

**Comment by ReneWerner87** [comment]
okay, beginning to understand the problem

until now you only sent us the snippet for the rendering of the html file, where you then included the main.js

can you please send us the snippet where you deliver the static files ? probably with app.Static, but there are several possibilities

probably the problem is in the core, because we use the fs.handler for static files from fasthttp
-> but i have a fix outside in mind
-> to enable a long term fix we would have to open an issue in the fasthttp project

can you also attach a mini example with "glsl" file ? so we can recreate this locally ?

what content type should your glsl file have ?

how do you bundle your javascript and the other files ? (webpack, esbuild, rollup ...)

**Comment by MichailVestnik** [comment]
@ReneWerner87 
I create repository with simple example (fake 3D with GLSL shaders). 
https://github.com/MichailVestnik/GLSL-with-Fiber-Example

There are two files in the js folder - main.js and fiber.js
Only main.js is included in HTML because it includes shaders as constants.
To work properly, you can include shaders as js modules, as shown in fiber.js

**Comment by ReneWerner87** [comment]
thank you

of course "text/plain" is the current content type, but what is the expected one ? which content type should be played after the fix ?(unfortunately i am not an expert in connection with glsl, therefore the question)

**Comment by MichailVestnik** [comment]
I researched this topic and it turns out that mime-types for shaders have the status of experimental. 
The only correct method at the moment is to embed shaders as strings directly in JS.
I apologize for taking up your time
