### ISSUE TITLE
🤗 How Can I Get Origin?

### ISSUE THREAD

**Issue by fncolon** [gofiber/fiber#1720]
**Question description**

<img width="220" alt="Capture" src="https://user-images.githubusercontent.com/50759463/149913435-b9c74031-3f6e-4ff7-a0eb-e7fb8965cdaa.PNG">

How can i get origin in fiber?

**Comment by ReneWerner87** [comment]
just use https://docs.gofiber.io/api/ctx#get

```go
ctx.Get("Origin")
```

**Comment by ReneWerner87** [comment]
@fncolon  can also ask such simple questions in our "discord" chat
https://gofiber.io/discord

**Comment by fncolon** [comment]
> just use https://docs.gofiber.io/api/ctx#get
> 
> ```go
> ctx.Get("Origin")
> ```

I forgot about `express-like` 😄

**Comment by fncolon** [comment]
> @fncolon can also ask such simple questions in our "discord" chat https://gofiber.io/discord

Aaaa okay I'm discord guy

**Comment by fncolon** [comment]
Thanks!
