### ISSUE TITLE
🤗 Usage Example using Session within multiple handler files

### ISSUE THREAD

**Issue by Anthonyhawkins** [gofiber/fiber#1722]
**Question description**
The documentation isn't too clear on how to set up the `store` variable when dealing with handlers within multiple files.  Given the following structure 
```
 - main.go
  - router/router.go
  - controllers/foo.go
  - controllers/bar.go 
``` 
```go
//main.go
func main() {
	app := fiber.New()
	router.SetupRoutes(app)
	log.Fatal(app.Listen(":3000"))
}
```
```go
//router.go
func SetupRoutes(app *fiber.App) {
	app.Get("/foos", foo.Index)
	app.Get("/foos/new", foo.New)
        ...
	app.Get("/bars", bar.Index)
	app.Get("/bars/new", bar.New)
}
```
Where should store be declared?
How would I make the store available to all handles regardless of the file? 

The example shows a very basic all-in-one approach but I'm curious how to manage the session in a more complex scenario. 

Thanks.

**Comment by ReneWerner87** [comment]
here we have an example, just search for the variable sessionStore, maybe this will help you to understand the whole thing
https://github.com/gofiber/recipes/blob/master/csrf/routes/mainServer.go#L31

**Comment by Anthonyhawkins** [comment]
That doesn't quite help me.  That's another example of the session and handlers being in the same file.  My question if what if my handlers are in different packages/files than main.go where the app is created and started.  

Going back to my example, if session is declared in `main.go` how would my handlers defined within `controllers/foo.go` `controllers/bar.go` get access to it?

**Comment by Anthonyhawkins** [comment]
I ended up solving this by doing the following.  Open to other ideas as well, otherwise I'll close this tomorrow.


```go
//main.go
var store = session.New()
app.Use(func(c *fiber.Ctx) error {
    c.Locals("sessions", store)
    return c.Next()
})
```	
```go
//foo.go
func New(c *fiber.Ctx) error {
	store := c.Locals("sessions").(*session.Store)
        ...
}        	
```

```go
//bar.go
func New(c *fiber.Ctx) error {
	store := c.Locals("sessions").(*session.Store)
        ...
}        	
```

**Comment by hi019** [comment]
Hey. This situation isn't really unique to the session middleware -- it applies to any variable you want to share with all handlers. One common pattern is to have all the handlers be methods on a struct, and then put the variables inside the struct. See [here](https://drstearns.github.io/tutorials/gohandlerctx/#sechttphandlerimplementations)
