### ISSUE TITLE
🐛 Cors plugin dit not work for the post crossOrigin request

### ISSUE THREAD

**Issue by jzyzxx** [gofiber/fiber#1723]
**Fiber version**
v2.23.0
**Issue description**
Cors plugin dit not work for the post crossOrigin request,no 'Access-Control-Allow-Origin: *' shows on the chrome devtool panel
**Code snippet**

```go
package main

import (
	"encoding/base64"
	"fmt"
	"gowork/goadmin/services/controllers/captcha"
	"gowork/goadmin/services/controllers/crypto"
	// "gowork/goadmin/services/email"
	// "sync"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/compress"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/csrf"
	"github.com/gofiber/fiber/v2/middleware/limiter"
	// "gorm.io/gorm"
	// "gowork/goadmin/services/controllers/user"
	// "gowork/goadmin/services/orm"
	// "time"
)

func handleNoLogin(c *fiber.Ctx) error { //中间件
	id := c.FormValue("id")
	fmt.Println(id)
	// if id == "" {
	// 	return c.SendString("id不能为空")
	// }else{
	return c.Next()
	// }
}
func handlerLogin(c *fiber.Ctx) error { //登录中间件
	str := c.Get("Authorization")
	bytestr, err := base64.StdEncoding.DecodeString(str)
	if err != nil {
		return err
	}
	token := string(crypto.RSADecrypt([]byte(bytestr)))
	fmt.Println(token)
	return c.Next()
}
func main() {
	app := fiber.New()
	app.Use(limiter.New())
	app.Use(compress.New())
	app.Use(csrf.New()) // Default config
	app.Use(cors.New())
	v1 := app.Group("/v1", handleNoLogin)      //不需登录
	v2 := app.Group("/v2", handlerLogin) //需登录
	v1.Get("/captcha", func(c *fiber.Ctx) error {
		return captcha.Captcha(c)
		// return c.Download("./go.mod")
	})
	v1.Get("/captchaImage/:captchaId", func(c *fiber.Ctx) error {
		return captcha.CaptchaImage(c)
		// return c.Download("./go.mod")
	})

	v2.Get("/user/login", func(c *fiber.Ctx) error {
		return c.SendString("ok")
	})
	v2.Post("/file/upload", func(c *fiber.Ctx) error {
		fmt.Println("files")
		// form, err := c.MultipartForm()
		// if err != nil {
		// 	return err
		// }
		// files := form.File
		// fmt.Println(files)
		return c.SendString("ok")
	})
	app.Listen(":9999")

}

![1](https://user-images.githubusercontent.com/24405119/150301857-cf82d137-7247-4b0e-8111-f6d4f427e28f.jpg)

```

**Comment by jzyzxx** [comment]
The cors plugin had worked for the get cosssorigin request,but dit not work for the post cosssorigin  request,

**Comment by ReneWerner87** [comment]
Cannot reproduce
![image](https://user-images.githubusercontent.com/7063188/150304827-be975688-16cb-42ad-bc47-6e9e02b667e5.png)

**Comment by ReneWerner87** [comment]
@jzyzxx

**Comment by jzyzxx** [comment]
> @jzyzxx

I

> Cannot reproduce ![image](https://user-images.githubusercontent.com/7063188/150304827-be975688-16cb-42ad-bc47-6e9e02b667e5.png)

maybe it is related about my js code:
```let form = new FormData();
      if (fileList &&fileList.length) {
        fileList.forEach((item) => {
          form.append(item.name, item.originFileObj);
        });
      }
      let res = axios.post(
        "/v2/file/upload",
        { files: form },
        {
          "Content-Type": "multipart/form-data",
        }
      );```

**Comment by ReneWerner87** [comment]
@jzyzxx can you tell what headers your javascript framework sends? 

the origin header is important

https://github.com/gofiber/fiber/blob/master/middleware/cors/cors.go#L111

**Comment by ReneWerner87** [comment]
see no error in the fiber, so I close the issue, so as not to unsettle other users

feel free to send me a [direct discord message](https://gofiber.io/discord) with the header or other findings

**Comment by jzyzxx** [comment]
> see no error in the fiber, so I close the issue, so as not to unsettle other users
> 
> feel free to send me a [direct discord message](https://gofiber.io/discord) with the header or other findings

I have upload my test demo to gitee,the responsitory address  is [https://gitee.com/git.oschinajzy.net/gowork.git]

**Comment by ReneWerner87** [comment]
@jzyzxx please try 
axios.defaults.withCredentials = true

found many issues for axios
https://github.com/axios/axios/issues/853
https://github.com/axios/axios/issues/191

**Comment by jzyzxx** [comment]
> @jzyzxx please try axios.defaults.withCredentials = true
> 
> found many issues for axios [axios/axios#853](https://github.com/axios/axios/issues/853) [axios/axios#191](https://github.com/axios/axios/issues/191)

Maybe cors isn 't the real problem here, the cors middleware works fine, a problem cause 500 error,but chrome thinks it is cors

**Comment by jzyzxx** [comment]
> @jzyzxx please try axios.defaults.withCredentials = true
> 
> found many issues for axios [axios/axios#853](https://github.com/axios/axios/issues/853) [axios/axios#191](https://github.com/axios/axios/issues/191)

When i shield the csrf plugin,the code runs well
