### ISSUE TITLE
🚀 Mention BodyParser error again ⚡️

### ISSUE THREAD

**Issue by OneSeven** [gofiber/fiber#1738]
**Is your feature request related to a problem?**
Yes
**Describe the solution you'd like**
Would like to be able to implement the UnmarshalTypeError struct from the standard library
**Describe alternatives you've considered**
no
**Additional context**
I need to know where the parsed fit error is in that field, and the value of the information
I'm turning from echo, I might give up on fiber because of this problem, I don't think fiber should give up on excellent and convenient solutions！

**Comment by ReneWerner87** [comment]
thanks for the report @OneSeven 

above i can see that you have probably mentioned this before, can you link the pre-report here as well.

if not already present in the pre-report, can you create an example with the specific case ?

in my test i can see the field that led to the problem
![image](https://user-images.githubusercontent.com/7063188/151766249-fb273b90-4fdd-4e6d-9fe2-2aecb00fcb1b.png)

would appreciate more information about the feature/problem solution

in issue #1375 #1387 we have already released the error messages for external comparison, maybe this will help you. 
https://github.com/gofiber/fiber/blob/master/error.go#L5-L14

**Comment by OneSeven** [comment]
@ReneWerner87 

For details, see this issue https://github.com/gofiber/fiber/issues/1010

**Comment by ReneWerner87** [comment]
am curious how the pull request looks like, feel free to prepare something

pull requests are always welcome

**Comment by OneSeven** [comment]
> am curious how the pull request looks like, feel free to prepare something
> 
> pull requests are always welcome

I'm very sorry, my level is not enough, I hope the official can achieve

**Comment by ReneWerner87** [comment]
ok, let's see if a contributor will take care of that, otherwise we will tackle that, but there is quite a lot on the table at the moment and few people are available

**Comment by OneSeven** [comment]
> ok, let's see if a contributor will take care of that, otherwise we will tackle that, but there is quite a lot on the table at the moment and few people are available

The implementation is suitable, can it be like echo and put its error inside
https://github.com/labstack/echo/blob/master/echo.go#L107

**Comment by OneSeven** [comment]
> > ok, let's see if a contributor will take care of that, otherwise we will tackle that, but there is quite a lot on the table at the moment and few people are available
> 
> The implementation is suitable, can it be like echo and put its error inside https://github.com/labstack/echo/blob/master/echo.go#L107

For formData, XML's error hope is the same, not limited to json

**Comment by ReneWerner87** [comment]
Please check it after rhe next release again( #1755)

**Comment by tomaswarynyca** [comment]
@OneSeven v2.27.0 solved this problem?
