### ISSUE TITLE
🤗 How to prevent cache in remote storage for non matching routes (404)

### ISSUE THREAD

**Issue by khrome83** [gofiber/fiber#1740]
**Question description**

How to prevent cache in remote storage for nonmatching routes (404)?

**Code snippet** _Optional_

```go
	app.Use(cache.New(cache.Config{
		Next: func(c *fiber.Ctx) bool {
			return c.Query("refresh") == "true"
		},
		Expiration:   24 * time.Hour,
		CacheControl: true,
		Storage:      store, // redis
	}))
```

I am seeing a lot of things added to my cache in redis that would be better left out. In other words, how can I prevent caching 404 responses or non-matched routes. Basically, the generic sniffers that look for php-my-admin and wp nonsense cause my redis to bloat. 

On this test I only have two routes `/` and `/admin` , and anything else is serving a 404, but sadly still caching.

**Comment by ReneWerner87** [comment]
use the skip middleware or the next method to skip unwanted actions.

https://docs.gofiber.io/api/middleware/skip


![image](https://user-images.githubusercontent.com/7063188/151998042-4cbfbc4d-8452-42ee-94fb-c2fe28ecc539.png)
https://docs.gofiber.io/api/middleware/cache#config

**Comment by khrome83** [comment]
@ReneWerner87 my first thought was using the next middleware. I guess I am confused on the lifecycle. 

I assume the middleware is handled before it gets to a route handler/matcher. So how would I know within `Next` function that downstream it would result in a 404, non matched route. 

Or does the cache process post route handler. If so how can I read the status in the context to see its a missed route?

**Comment by ReneWerner87** [comment]
yes good point, how to know beforehand that nothing matched

https://github.com/gofiber/fiber/blob/5766feef29be223835cb8bb31ea6ad497afd47cd/middleware/cache/cache.go#L117
it looks like the next method is executed afterwards, so you might actually know if it matched or not

you could e.g. set locals which contain "cache" true, if this is set and other conditions like your query parameters apply 
https://docs.gofiber.io/api/ctx#locals
will then be cached

with the skip middleware you would check before executing your handler
https://github.com/gofiber/fiber/blob/5766feef29be223835cb8bb31ea6ad497afd47cd/middleware/skip/skip.go#L12-L17

**Comment by khrome83** [comment]
@ReneWerner87 that worked wonderful. 

I used this - 
```
	app.Use(cache.New(cache.Config{
		Next: func(c *fiber.Ctx) bool {
			if c.Query("refresh") == "true" {
				return true
			}

			if c.Locals("use-cache") != true {
				return true
			}

			return false
		},
		Expiration:   24 * time.Hour,
		CacheControl: true,
		Storage:      store,
	}))
```

In the handlers that should be cached I added `c.Locals("use-cache", true)`
