### ISSUE TITLE
🚀 support explicit allowed paths in basic auth config middleware

### ISSUE THREAD

**Issue by mstrYoda** [gofiber/fiber#1745]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
I know that there is already Next function in basicauth.Config but it would be nice to support basicauth.Allowed to disable basic auth for certain paths.

Current Next function will grow if we have different skip conditions. We can reduce it by writing a boiler plate Allowed/Skip paths in basic auth config.

**Describe alternatives you've considered**

**Additional context**
I thought that it would be nice to have AllowedPaths config as a convention.

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/middleware/skip

why don't you just use the skip middleware ?

**Comment by ReneWerner87** [comment]
@mstrYoda

**Comment by mstrYoda** [comment]
> https://docs.gofiber.io/api/middleware/skip
> 
> why don't you just use the skip middleware ?

Is not that would be nicer to write this:

```
app.use(basicauth.New(basicauth.Config{
  Users: map[string]string{
    basicAuthUser: basicAuthPassword,
  },
  AllowedPaths: []string{"/somepath", "/anotherpath"}
}))
```

instead of this:

```
app.Use(basicauth.New(basicauth.Config{
	Users: map[string]string{
		basicAuthUser: basicAuthPassword,
	},
	Next: func(c *fiber.Ctx) bool {
		return string(c.Request().RequestURI()) == "/somepath" || 
                        string(c.Request().RequestURI()) == "/anotherpath"
	},
}))
```

or this:

```
app.Use(skip.New(basicauth.New(basicauth.Config{
	Users: map[string]string{
		basicAuthUser: basicAuthPassword,
	}}), func(c *fiber.Ctx) bool {
	    return string(c.Request().RequestURI()) == "/somepath" || 
                        string(c.Request().RequestURI()) == "/anotherpath"
}))
```

**Comment by ReneWerner87** [comment]
this feature looks to me more like it is interesting for all middlewares and you can actually cover it already

therefore I would advise against this feature

below some other possibilities

the question is also, why you use a middleware on all paths, which is not needed there at all
-> we have so many possibilities with the router to structure these middlewares, that a whitelist is not needed there then

```go
    allowedPaths := map[string]bool{
        "/somepath": true,
        "/anotherpath": true,
    }
    app.Use(basicauth.New(basicauth.Config{
        Users: map[string]string{
            basicAuthUser: basicAuthPassword,
        },
        Next: func(c *fiber.Ctx) bool {
            return allowedPaths[utils.UnsafeString(c.Request().RequestURI())]
        },
    }))
 ```
 
 ```go
     auth := basicauth.New(basicauth.Config{
        Users: map[string]string{
            basicAuthUser: basicAuthPassword,
        },
    })
    app.Use("/somepath", auth)
    app.Use("/anotherpath", auth)
 ```
 
 ```go
     auth := basicauth.New(basicauth.Config{
        Users: map[string]string{
            basicAuthUser: basicAuthPassword,
        },
    })
    app.Get("/somepath", auth, myHandler)
    app.Get("/anotherpath", auth, myHandler)
 ```
 
 
 ```go
     allowedPaths := map[string]bool{
        "/somepath": true,
        "/anotherpath": true,
    }

    app.Use(skip.New(
        basicauth.New(basicauth.Config{Users: map[string]string{basicAuthUser: basicAuthPassword}}),
        func(c *fiber.Ctx) bool {
            return allowedPaths[utils.UnsafeString(c.Request().RequestURI())]
        }),
    )
 ```

**Comment by mstrYoda** [comment]
> this feature looks to me more like it is interesting for all middlewares and you can actually cover it already
> 
> therefore I would advise against this feature
> 
> below some other possibilities
> 
> the question is also, why you use a middleware on all paths, which is not needed there at all -> we have so many possibilities with the router to structure these middlewares, that a whitelist is not needed there then
> 
> ```go
>     allowedPaths := map[string]bool{
>         "/somepath": true,
>         "/anotherpath": true,
>     }
>     app.Use(basicauth.New(basicauth.Config{
>         Users: map[string]string{
>             basicAuthUser: basicAuthPassword,
>         },
>         Next: func(c *fiber.Ctx) bool { // skip with true
>             return false === allowedPaths[utils.UnsafeString(c.Request().RequestURI())]
>         },
>     }))
> ```
> 
> ```go
>    auth := basicauth.New(basicauth.Config{Users: map[string]string{basicAuthUser: basicAuthPassword}})
>    app.Use("/somepath", auth)
>    app.Use("/anotherpath", auth)
> ```
> 
> ```go
>    auth := basicauth.New(basicauth.Config{Users: map[string]string{basicAuthUser: basicAuthPassword}})
>    app.Get("/somepath", auth, myHandler)
>    app.Get("/anotherpath", auth, myHandler)
> ```
> 
> ```go
>     allowedPaths := map[string]bool{
>        "/somepath": true,
>        "/anotherpath": true,
>    }
> 
>    app.Use(skip.New(
>        basicauth.New(basicauth.Config{Users: map[string]string{basicAuthUser: basicAuthPassword}}),
>        func(c *fiber.Ctx) bool { // skip with true
>            return false === allowedPaths[utils.UnsafeString(c.Request().RequestURI())]
>        }),
>    )
> ```

All of them are good examples, thank you for the discussion.
