### ISSUE TITLE
🐛 Unable to parse JSON Decoder Error

### ISSUE THREAD

**Issue by kivox** [gofiber/fiber#1751]
**Fiber version**
Fiber v2.25.0

**Issue description**
Usually, you can unmarshal the error returned by a function into the struct it was declared as. Now the issue here is this struct is set as an internal property of the Fiber library, therefore, making it inaccessible to the project where Fiber is used in.

Location of the decoder's Error struct: `github.com/gofiber/fiber/v2/internal/go-json/errors`

**Code snippet**
```go
func ParseBody(ctx *fiber.Ctx, body interface{}) *fiber.Error {
	// parse request to struct
	if err := ctx.BodyParser(body); err != nil {
		// This should parse the error's string into a struct of the error
		if jsonErr, ok := err.(*errors.UnmarshalTypeError); ok {
			// use jsonErr to get values from error
		} else {
			// The error is not an UnmarshalTypeError
			return fiber.ErrBadRequest
		}
	}

	return nil
}
```

**Comment by ReneWerner87** [comment]
Should be fixed by #1755
