### ISSUE TITLE
🤗 Conflict router and context.Render

### ISSUE THREAD

**Issue by MichailVestnik** [gofiber/fiber#1753]
Hi!

### I had a case like this:

```go
app.Get("/articles/:id", func(ctx *fiber.Ctx) error {
	id := ctx.Params("id")
	article := fmt.Sprint("web/articles/", id, ".html")
	return ctx.SendFile(article)
})
```

In this example, I take a query parameter and give it to the HTML page.

Suppose there are three files in the articles folder - 1.html, 2.html and 3.html. If I add another 4.html file to this folder in running server mode, everything works correctly. I will see the page at mysite.com/articles/4.

### A case of the problem:

```go
app.Get("/articles/:id", func(ctx *fiber.Ctx) error {
	id := ctx.Params("id")
	article := fmt.Sprint("articles/", id)
	return ctx.Render(article, fiber.Map{
		"Test": "Hello, Fiber",
	})
})
```

If I add 4.html in this case, I won't get the page. Fiber freezes all template folders and files. 
How can I do folder status tracking in the case of a renderer?

Спасибо

**Comment by ReneWerner87** [comment]
For that you would have to re-read the templates with the load function.

**Comment by MichailVestnik** [comment]
OK! Thanks!
