### ISSUE TITLE
🤗 dynamically changing routes?

### ISSUE THREAD

**Issue by lonnietc** [gofiber/fiber#1757]
Hello,

I have a few web games in a subdirectory 

/games/game1
/games/game2
.
.
/games/gameN

I need to be able to read the "games" directory and choose a random game path which I can do.

My questions is to how Fiber can dynamically set that path as needed since each time a user comes to the website, I want a randomly chosen game to be registered for that user which will change on the next browser visit.

you have a static page listing as:

app.Static("/", "./public")
    // => http://localhost:3000/js/script.js
    // => http://localhost:3000/css/style.css

I want to randomly create a path string that might be "games/game6" = pathName for example and then 

I will have 2 routes:

app.Static("/dashboard", "./dashboard")

app.Static("/game", pathName)
    // => http://localhost:3000/js/script.js
    // => http://localhost:3000/css/style.css

Then when the user comes to the page then each time, the pathName will generate an new random path to one of the games in the games subdirectory then that will be set as static path for that instance.

How can I accomplish this?
Thanks in advance

**Comment by ReneWerner87** [comment]
@lonnietc There are many ways
The games are also delivered with app.static or? Would create an index html in each directory and define the base href in it and load your general static files(css and js) relative from the root.

The redirection, can happen via javascript(location.href = "...") in the main directory on the index html, you only need to load the information via ajax, which games or folders exist + random choose of a game.

Or you create a rest route which reads the folders via golang and redirects randomly to the game folder via redirect(301).
