### ISSUE TITLE
🚀 Feature Request: Hooks Support

### ISSUE THREAD

**Issue by efectn** [gofiber/fiber#1758]
I think hook support would be great and useful for Fiber. Example we can use hooks to define auto-swagger middleware etc.

**Simple Proposal Example:**
```
app.RegisterHook("onRoute", func(c *fiber.Ctx) error {
	...
})
```

Example Hooks:
- onRoute
- onShutdown
- onReady
- onRequest
- onResponse

Reference: https://www.fastify.io/docs/latest/Reference/Hooks

**->** _If you are OK, i can create PR in the next days._

**Comment by ReneWerner87** [comment]
We need a good document for the hooks

"When they are executed?"
Furthermore, they should have meaningful names

Maybe post and pre prefixes and some examples.
