### ISSUE TITLE
🤔 Limiter headers not working as expected

### ISSUE THREAD

**Issue by PringlePot** [gofiber/fiber#1759]
**Fiber version**
Latest version

**Issue description**
When using multiple instances of limiter, the headers might not show the correct headers.

![image](https://user-images.githubusercontent.com/80323633/152874867-cc662f95-667d-4ec3-b3cc-1798a62f292d.png)

**Code snippet**
https://gist.github.com/PringlePot/e28d90dab317c11736738e7f89af1480

**Comment by ReneWerner87** [comment]
In your example 2 limiter middlewares are used at the same time

By mounting the sub app that has the limiter middleware in the root on the path

Please try to reproduce it without mounting or with only one limiter middleware in a simple example

**Comment by PringlePot** [comment]
Can't you check if the headers are already set, and dont overwrite them then?

**Comment by ReneWerner87** [comment]
No, using this middleware 2 times on the same route is just wrong

if i would do this in this middleware, you would have to do this in every other middleware (cors, etag, compress, csrf, .....)

**Comment by PringlePot** [comment]
Okay, I will just add the middleware seperately for the routes then
