### ISSUE TITLE
🤗 How can I DO reverseproxy http(other server) to https(gofiber)?

### ISSUE THREAD

**Issue by koreaidi0t** [gofiber/fiber#1762]
**Question description**
 How can DO reverseproxy?

```go
package main

import (
	"crypto/tls"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/proxy"
)


func main() {
	cer, err := tls.LoadX509KeyPair("certs/fullchain.crt", "certs/privkey.pem")
	if err != nil {
		panic(err)
	}
	config := &tls.Config{Certificates: []tls.Certificate{cer}}

	app := fiber.New()
	g := app.Group("/test")
	{
		g.All("/*", func(c *fiber.Ctx) error {
			url := "http://192.168.10.144:80"+c.Path()
			err := proxy.Do(c, url)
			if err != nil{
				panic(err)
			}
			return nil
		})
	}
	ln, err := tls.Listen("tcp", ":443", config)
	if err != nil {
		panic(err)
	}
	app.Listener(ln)
}
```

When running this code, I got following error.
`panic: tls: first record does not look like a TLS handshake`

Thanks for reading.

**Comment by ReneWerner87** [comment]
@koreaidi0t  
have you tested the server and the tls configuration without the proxy middleware ? do you get the same error ?

**Comment by koreaidi0t** [comment]
> @koreaidi0t
> have you tested the server and the tls configuration without the proxy middleware ? do you get the same error ?

**Comment by ReneWerner87** [comment]
ok, you(@koreaidi0t ) opened it again ? 
anything else I can help ?

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/153443685-e9b90582-e767-4534-94ad-9211f267cadd.png)
https://github.com/gofiber/fiber/tree/master/middleware/proxy

have you tried this from the readme ?

**Comment by bigflood** [comment]
My guess is that the proxy middleware is doing https to the http target.

**Comment by koreaidi0t** [comment]
@bigflood 
Thanks.
I found that if I change the scheme to 'http', it overwrited to 'https' due to isTls variable in req is set true.
What can I do?

**Comment by bigflood** [comment]
It doesn't seem possible.

**Comment by koreaidi0t** [comment]
@bigflood 
It seems hard to change isTls var in req though. 😢 

BTW thanks for your comments!

**Comment by bigflood** [comment]
@ReneWerner87 
May I work on this issue?

**Comment by ReneWerner87** [comment]
Sure
