### ISSUE TITLE
🐛Backwards Incompatible Change to fiber.Error

### ISSUE THREAD

**Issue by golangaddict** [gofiber/fiber#1767]
**Fiber version**
2.26.0

**Issue description**
The change referenced here [CLICK HERE](https://github.com/gofiber/fiber/commit/7cf1886df5f6041449ca082701c05bb5eb13100e#r66439045) in #1728 which was applied to a MINOR update is backwards incompatible. This change will break underlying structures that reference fiber.Error.Message using the concrete type "string".

One cannot simply imply that although the string can now be accessed via `fiber.Message.Error()` that this is a backwards-compatible change. The fact that code modification is needed by consumers in order to recorrect this issue is the exact representation of incompatibility.

This is not an argument of the effort required to fix or resolve this issue. It is merely a statement that semantic versioning is not being followed by this project if decisions/actions like this are being supported by the maintaining contributors.

Symantic versioning implies that both MINOR & PATCH updates must be done in a backwards compatible manner. This change is not backwards compatible in a typical scenario.

Changing the concrete type of publicly exposed API struct fields is bad practice for anything other than MAJOR backwards incompatible updates.

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func ErrorHandler(c *fiber.Ctx, err error) error {
	var status int
	var message string

	switch e := err.(type) {
	case *fiber.Error:
		status = e.Code
		message = e.Message // This now throws an error because the concrete type of `Message` is no longer `string`
	default:
		status = http.StatusInternalServerError
		message = err.Error()
	}

	return c.Status(status).JSON(fiber.Map{"message": message})
}
```

**Comment by balcieren** [comment]
> **Fiber version** 2.26.0
> 
> **Issue description** The change referenced here [CLICK HERE](https://github.com/gofiber/fiber/commit/7cf1886df5f6041449ca082701c05bb5eb13100e#r66439045) in #1728 which was applied to a MINOR update is backwards incompatible. This change will break underlying structures that reference fiber.Error.Message using the concrete type "string".
> 
> One cannot simply imply that although the string can now be accessed via `fiber.Message.Error()` that this is a backwards-compatible change. The fact that code modification is needed by consumers in order to recorrect this issue is the exact representation of incompatibility.
> 
> This is not an argument of the effort required to fix or resolve this issue. It is merely a statement that semantic versioning is not being followed by this project if decisions/actions like this are being supported by the maintaining contributors.
> 
> Symantic versioning implies that both MINOR & PATCH updates must be done in a backwards compatible manner. This change is not backwards compatible in a typical scenario.
> 
> Changing the concrete type of publicly exposed API struct fields is bad practice for anything other than MAJOR backwards incompatible updates.
> 
> **Code snippet**
> 
> ```go
> package main
> 
> import "github.com/gofiber/fiber/v2"
> 
> func ErrorHandler(c *fiber.Ctx, err error) error {
> 	var status int
> 	var message string
> 
> 	switch e := err.(type) {
> 	case *fiber.Error:
> 		status = e.Code
> 		message = e.Message // This now throws an error because the concrete type of `Message` is no longer `string`
> 	default:
> 		status = http.StatusInternalServerError
> 		message = err.Error()
> 	}
> 
> 	return c.Status(status).JSON(fiber.Map{"message": message})
> }
> ```

thanks for issue, I have thought. Message is going to be string and I will add new property for Error struct. It is going to be interface so you can use if you want string or interface.

**Comment by golangaddict** [comment]
> > **Fiber version** 2.26.0
> > **Issue description** The change referenced here [CLICK HERE](https://github.com/gofiber/fiber/commit/7cf1886df5f6041449ca082701c05bb5eb13100e#r66439045) in #1728 which was applied to a MINOR update is backwards incompatible. This change will break underlying structures that reference fiber.Error.Message using the concrete type "string".
> > One cannot simply imply that although the string can now be accessed via `fiber.Message.Error()` that this is a backwards-compatible change. The fact that code modification is needed by consumers in order to recorrect this issue is the exact representation of incompatibility.
> > This is not an argument of the effort required to fix or resolve this issue. It is merely a statement that semantic versioning is not being followed by this project if decisions/actions like this are being supported by the maintaining contributors.
> > Symantic versioning implies that both MINOR & PATCH updates must be done in a backwards compatible manner. This change is not backwards compatible in a typical scenario.
> > Changing the concrete type of publicly exposed API struct fields is bad practice for anything other than MAJOR backwards incompatible updates.
> > **Code snippet**
> > ```go
> > package main
> > 
> > import "github.com/gofiber/fiber/v2"
> > 
> > func ErrorHandler(c *fiber.Ctx, err error) error {
> > 	var status int
> > 	var message string
> > 
> > 	switch e := err.(type) {
> > 	case *fiber.Error:
> > 		status = e.Code
> > 		message = e.Message // This now throws an error because the concrete type of `Message` is no longer `string`
> > 	default:
> > 		status = http.StatusInternalServerError
> > 		message = err.Error()
> > 	}
> > 
> > 	return c.Status(status).JSON(fiber.Map{"message": message})
> > }
> > ```
> 
> thanks for issue, I have thought. Message is going to be string and I will add new property for Error struct. It is going to be interface so you can use if you want string or interface.

That sounds like a much better approach, thank you.

**Comment by balcieren** [comment]
@golangaddict https://github.com/gofiber/fiber/pull/1768
