### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Martyhacker** [gofiber/fiber#1783]
**Question description**
Hello. I can't get fiber/v2. My go version is 1.16.4. Error is x509: certificate signed by unknown authority.
This is output when I entered <code>go get github.com/gofiber/fiber/v2</code> command on cmd.

github.com/gofiber/fiber/v2 imports
        github.com/valyala/fasthttp imports
        github.com/klauspost/compress/flate: github.com/klauspost/compress@v1.14.1: Get "https://storage.googleapis.com/proxy-golang-org-prod/f3457dc5db2353fd-github.com:klauspost:compress-v1.14.1.zip?Expires=1645101696&GoogleAccessId=gcs-urlsigner-prod%40golang-modproxy.iam.gserviceaccount.com&Signature=n%2BApZ954U9dpu16XgDPfLG6xnJwTabCpHCqNa57vzA1d5v6hwx9SAE6iGJDXcGLyH6FlhDimQUSKmZfqda2EZ1ZvndMB0aWb0i1nfOnXYvTlwUFLf%2BVaPnJeujJIxiDvVMcNf41jJ7wEIkS2WZWVDlNgPqPXq7x5UzBy4sNAFey%2FfdgxTuf%2BFVxgbsmBGUEgpPly41QdMxRNcq8uq37MTJAMd42bDFXK2dXjscWDmHOf9boJtF1KkXeGp4375hIb1Tt7087w%2FfQhLk70vodaRYTc8MLr%2FWv0fM8l7%2F5oQXIQzMI7LO4hJS%2BOkVA%2Bs0dTnBQQIGENEQ%2BTaSq0GyN3WQ%3D%3D": x509: certificate signed by unknown authority
github.com/gofiber/fiber/v2 imports
        github.com/valyala/fasthttp imports
        github.com/klauspost/compress/gzip: github.com/klauspost/compress@v1.14.1: Get "https://storage.googleapis.com/proxy-golang-org-prod/f3457dc5db2353fd-github.com:klauspost:compress-v1.14.1.zip?Expires=1645101696&GoogleAccessId=gcs-urlsigner-prod%40golang-modproxy.iam.gserviceaccount.com&Signature=n%2BApZ954U9dpu16XgDPfLG6xnJwTabCpHCqNa57vzA1d5v6hwx9SAE6iGJDXcGLyH6FlhDimQUSKmZfqda2EZ1ZvndMB0aWb0i1nfOnXYvTlwUFLf%2BVaPnJeujJIxiDvVMcNf41jJ7wEIkS2WZWVDlNgPqPXq7x5UzBy4sNAFey%2FfdgxTuf%2BFVxgbsmBGUEgpPly41QdMxRNcq8uq37MTJAMd42bDFXK2dXjscWDmHOf9boJtF1KkXeGp4375hIb1Tt7087w%2FfQhLk70vodaRYTc8MLr%2FWv0fM8l7%2F5oQXIQzMI7LO4hJS%2BOkVA%2Bs0dTnBQQIGENEQ%2BTaSq0GyN3WQ%3D%3D": x509: certificate signed by unknown authority
github.com/gofiber/fiber/v2 imports
        github.com/valyala/fasthttp imports
        github.com/klauspost/compress/zlib: github.com/klauspost/compress@v1.14.1: Get "https://storage.googleapis.com/proxy-golang-org-prod/f3457dc5db2353fd-github.com:klauspost:compress-v1.14.1.zip?Expires=1645101696&GoogleAccessId=gcs-urlsigner-prod%40golang-modproxy.iam.gserviceaccount.com&Signature=n%2BApZ954U9dpu16XgDPfLG6xnJwTabCpHCqNa57vzA1d5v6hwx9SAE6iGJDXcGLyH6FlhDimQUSKmZfqda2EZ1ZvndMB0aWb0i1nfOnXYvTlwUFLf%2BVaPnJeujJIxiDvVMcNf41jJ7wEIkS2WZWVDlNgPqPXq7x5UzBy4sNAFey%2FfdgxTuf%2BFVxgbsmBGUEgpPly41QdMxRNcq8uq37MTJAMd42bDFXK2dXjscWDmHOf9boJtF1KkXeGp4375hIb1Tt7087w%2FfQhLk70vodaRYTc8MLr%2FWv0fM8l7%2F5oQXIQzMI7LO4hJS%2BOkVA%2Bs0dTnBQQIGENEQ%2BTaSq0GyN3WQ%3D%3D": x509: certificate signed by unknown authority

**Comment by ReneWerner87** [comment]
do you have the same problems with "go mod" which you should use ?

https://go.dev/blog/using-go-modules

**Comment by Martyhacker** [comment]
> do you have the same problems with "go mod" which you should use ?
> 
> https://go.dev/blog/using-go-modules

I don't understand to go modules very well. But before getting fiber I just typed these commands
<code>go mod init backend-sample</code>
