### ISSUE TITLE
🚀 A custom setting for the CacheDuration in SendFile()?

### ISSUE THREAD

**Issue by hakoptak** [gofiber/fiber#1785]
**Is your feature request related to a problem?**
I have a use case where I have to peform some actions before sending out a static html file:

```go
app.Get("/home", func(c *fiber.Ctx) error {

	logInfo("GET /home")

	// Some actions

	return c.SendFile("home.html", true)

})
```
Currently, the `SendFile()` method accepts a compress flag and internally the `CacheDuration` is set to a fixed 10 seconds. But since the `home.html` is static by nature, I would like to define a `CacheDuration` beyond 10 seconds (like in `Static()`).

**Describe the solution you'd like**
Could we
1. Extend the SendFile method to `SendFile(file string, compress ...bool, duration ...time.Duration)`?
2. Or, more generally, define a new method `SendStaticFile(file string, config ...Static)`?
3. Or, which breaks the API, redefine `SendFile(file string, config ...Static)`?

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ReneWerner87** [comment]
@hi019 @efectn what do you mean ?
I prefer the 2nd method

1st method is not possible, because 2 times rest parameters can not come after each other

the 3rd method breaks the api

**Comment by efectn** [comment]
> @hi019 @efectn what do you mean ? I prefer the 2nd method
> 
> 1st method is not possible, because 2 times rest parameters can not come after each other
> 
> the 3rd method breaks the api

Me too. I think we can do 3. one on v3.

**Comment by hi019** [comment]
Yeah we can do 2, Or `SendFileWithDuration`

**Comment by hi019** [comment]
2 sounds good

**Comment by ReneWerner87** [comment]
@hakoptak

**Comment by hakoptak** [comment]
Hi @ReneWerner87, I am looking into it. I guess that solution 2 has its troubles: the `static` struct contains fields that do not apply to the send function (as far as I understand it). It concerns `ByteRange, Browse, Download, Index, Next()`

As always: the devil is in the details...

To be honest: I misunderstood the meaning of `CacheDuration` (thought it was the duration of the cached file, but it turns out that it is the duration of the request caching). So this makes my use case less strong.
