### ISSUE TITLE
🐛 Console output unreadable

### ISSUE THREAD

**Issue by dhruvkb** [gofiber/fiber#1791]
**Fiber version**

v2.27.0

**Issue description**

When the server starts, the output is unreadable on the console. This happens when using the Solarized Dark color theme.
<img width="512" alt="Screenshot 2022-02-22 at 9 12 29 AM" src="https://user-images.githubusercontent.com/16580576/155067213-9cee3296-7e7c-4513-a73e-a46c819f43db.png">

The text is still being rendered, as it becomes readable upon selection.
<img width="512" alt="Screenshot 2022-02-22 at 9 13 06 AM" src="https://user-images.githubusercontent.com/16580576/155067283-6d80b3f8-36fa-4075-8836-1f89ffc356fc.png">

It's just some ANSI controls are writing text with the same color as the background. Piping the output through
```
| sed 's/\x1b\[[0-9;]*m//g'
```
which strips all ANSI controls fixes this.

**Comment by hi019** [comment]
As a temporary fix, you could use add `DisableStartupMessage` to your config and print out the statistics manually

**Comment by dhruvkb** [comment]
The `sed` command in the issue is the current temporary fix I'm using. It just strips out the colors and makes the output readable.

**Comment by dhruvkb** [comment]
It seems this is an issue with Solarized Dark (https://github.com/altercation/solarized/issues/220) and not Fiber so I'm going to close this issue. Sorry for the trouble it might have caused.
