### ISSUE TITLE
fasthttp v1.33.0 panic when closing context🐛 

### ISSUE THREAD

**Issue by itzikiusa** [gofiber/fiber#1792]
**Fiber version**
v2.27.0
**Issue description**
every few minutes due to race condition panic occurs and program exists, issue is caused by fasthttp library, v1.33.0

this is more a warning then a bug, as a PR exists on fasthttp, but fiber also affected by this issue

**Comment by ReneWerner87** [comment]
@itzikiusa could you link this PR ?

**Comment by ReneWerner87** [comment]
you mean ?
https://github.com/valyala/fasthttp/issues/1205
https://github.com/valyala/fasthttp/pull/1206

**Comment by hi019** [comment]
There is some activity on a new PR: https://github.com/valyala/fasthttp/pull/1234

**Comment by itzikiusa** [comment]
@ReneWerner87 
seems like new version has been release for fasthttp v1.34.0

**Comment by ReneWerner87** [comment]
Dependabot is working https://github.com/gofiber/fiber/pull/1811

**Comment by FlandiaYingman** [comment]
Could we release a patch version to fix this?

**Comment by ReneWerner87** [comment]
sure give me some minutes

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/releases

**Comment by itzikiusa** [comment]
thanks!
