### ISSUE TITLE
🤗 Does gofiber runs asynchronously?

### ISSUE THREAD

**Issue by rushkii** [gofiber/fiber#1797]
I'm new using Go, it''s kinda hard to learn goroutine, is there an example using gofiber asynchronously?

**Comment by ReneWerner87** [comment]
https://medium.com/@gauravsingharoy/asynchronous-programming-with-go-546b96cd50c1

https://gobyexample.com/goroutines
https://gobyexample.com/channels
https://gobyexample.com/waitgroups

**Comment by ReneWerner87** [comment]
@rushkii  does my comment help you ?
