### ISSUE TITLE
Please tell me how to get a 302 redirect link 🤗. 

### ISSUE THREAD

**Issue by faryoo** [gofiber/fiber#1805]
**Question description**

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  // ..
}
```

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/ctx#redirect

Please always read the documentation first before opening an issue

The description and headline please always in English, otherwise we can not help you

You can also use translators
https://www.deepl.com/translator
