### ISSUE TITLE
🔥 Support GZip / Deflate

### ISSUE THREAD

**Issue by hyingreborn** [gofiber/fiber#181]
**Is your feature request related to a problem?**
Now, the gzip is built in Static()，so I can't customize which paths to open gzip and which file sizes to open gzip

**Describe the solution you'd like**
In my project，i need open gzip for staticfiles，at the same time, i want open gzip for restful api module(when the response is bigger than 4kb)

**Describe alternatives you've considered**
gzip be removed from Static() and exist as a official middleware

**Additional context**

**Comment by Fenny** [comment]
@hyingreborn, we have to option to enable gzipping for the `Static` files and `c.SendFile` method. If I'm correct you would like to have an option to enable gzipping for any kind of response besides files?

**Comment by hyingreborn** [comment]
I want gzip to work in my custom path，not only static files，for example
```go
// gzip work in static path
app.Static("/app/", "./public/")
app.Use("/app", gzip())

// gzip work in api module
app := app.Group("/api", gzip())
//...
```

**Comment by koddr** [comment]
@hyingreborn after Fiber `v1.7.0`, we can use multiple middlewares at `app.Method` and `app.Group`. You can write your own midware func and use it. 

@Fenny good idea to exclude `gzip` feature to `github.com/gofiber/middlewares` for easy use on everywhere in app code.

**Comment by hyingreborn** [comment]
I will use these two middleware when developing with gin, hoping to provide you with inspiration
github.com/gin-contrib/static
github.com/nanmu42/gzip

**Comment by Fenny** [comment]
Thanks @hyingreborn for your suggestion, we will release a middleware folder soon and I will take a look if a gzipping middleware is possible with fasthttp!

**Comment by renanbastos93** [comment]
Hi guys

Can I help you? I wish this challenge.

For context about it.
`Do we you wishing implement GZIP in all routes don't just files, right?`
Using according to example

```go
app.Static("/app/", "./public/")
app.Use("/app", fiber.gzip())
app := app.Group("/api", fiber.gzip())
```


See ya

**Comment by renanbastos93** [comment]
I saw now and FastHTTP have a compress gzip
https://github.com/valyala/fasthttp/blob/32793db72d04141d333eb04ce60170db6e79e6d2/compress.go

So, we should use `Content-Encoding` how gzip.
example:
```go
func Gzip(c *fiber.Ctx) {
	c.Set("Content-Encoding", "gzip")
	c.Next()
}
app.Group("/api", gzip)
```

Well, I believe that is possible using gzip on Fiber then I liked this approach to create a package for our middlewares. 

Can we create a todo list to implement these middlewares?

I can't test this approach now, when possible I'll test.

see ya

**Comment by Fenny** [comment]
I'm working on implementing Compression, It's really simple and I got a working version.
I created an context method called `Compress()` that will gzip / deflate the response at the end.
My proposition is to use the `ctx.Compress()` to enable compression per route.
And 'app.Settings.Compression = true'  for all routes, let me know what you think.

```go
// Compress a specific route
app.Get("/", func(c *fiber.Ctx) {
  c.Send("Hello, World!")
  c.Compress()
})
```
```go
// Compress middleware
func Gzip(c *fiber.Ctx) {
	c.Compress()
	c.Next()
}
app.Get("/", Gzip, func(c *fiber.Ctx) {
  c.Send("Hello, World!")
})
```
```go
// Enable compression for all routes
app := fiber.New(&fiber.Settings{
  Compression: true,
})
app.Get("/", func(c *fiber.Ctx) {
  c.Send("Hello, World!")
})
```

**Comment by Fenny** [comment]
Added in `v1.8.1`
