### ISSUE TITLE
🤗 Html layouts and views, having difficulties and I need help 

### ISSUE THREAD

**Issue by gregg-cbs** [gofiber/fiber#1810]
**Question description**
Can I please have an example of how views and layouts are supposed to interact with each other in Fiber?

At the moment i have set up layouts and views but if I use the layout in more than one view it seems to bug out.

**I have initialised views like so**
_In  my html folder is both my views and layouts_
```go
fApp := fiber.New(fiber.Config{
  Views: html.New("./app/html", ".html"),
})
```

**I made a base layout and in it i define base (as per some example from the internet):**
```go
{{define "base"}}
   <..some html>
  {{template "main" .}}
{{end}}
```

**I use the base template in a view by defining it**
```go
{{template "base" .}}
  {{define "main"}}
     <..some html>
  {{end}}
```

^ this works, but if I used the template again in another view then it shows this view as if something is cross pollinating.

The fiber [docs](https://docs.gofiber.io/guide/templates) on this matter were no help.

**Comment by ReneWerner87** [comment]
Hi, please move this report in our template repository
