### ISSUE TITLE
🐛 Limiter middleware works improperly with any database

### ISSUE THREAD

**Issue by qracer** [gofiber/fiber#1812]
Limiter middleware works fine with default in-memory storage. The same for db storage but only if `SkipSuccessfulRequests` and `SkipFailedRequests` set to `false`. 

If, for example, `SkipSuccessfulRequests` set to `true`, the middleware will still ban a user for specified amount of requests even if they have status codes less than 400.

The bug caused by the `set` method in [manager.go](https://github.com/gofiber/fiber/blob/master/middleware/limiter/manager.go):
```go
func (m *manager) set(key string, it *item, exp time.Duration) {
	if m.storage != nil {
		if raw, err := it.MarshalMsg(nil); err == nil {
			_ = m.storage.Set(key, raw, exp)
		}
		// we can release data because it's serialized to database
		m.release(it)
	} else {
		m.memory.Set(key, it, exp)
	}
}
```
If any database is used, `m.release(it)` to be executed what will set all fields of `it` structure to 0.

In its turn, [limiter_fixed.go](https://github.com/gofiber/fiber/blob/master/middleware/limiter/limiter_fixed.go) has code to check for successful requests:
```go
if (cfg.SkipSuccessfulRequests && c.Response().StatusCode() < fiber.StatusBadRequest) ||
			(cfg.SkipFailedRequests && c.Response().StatusCode() >= fiber.StatusBadRequest) {
			mux.Lock()
			e.currHits--
			remaining++
			mux.Unlock()
		}
```
Unfortunately, this actions do not have any sense, because `manager.get()` is called before:
```go
manager.set(key, e, cfg.Expiration)
``` 
Thereby, all fields values of `e` equals to 0 and checking for successful requests is meaningless.

The simplest and straightforward way to fix the bug is to remove `m.release(it)` from `manager.go`.

**Comment by ReneWerner87** [comment]
We will check this, thx for the hint
