### ISSUE TITLE
How can I get all param variables?

### ISSUE THREAD

**Issue by cw-20020752** [gofiber/fiber#1816]
For example, if my url is /test/:param1/test2/:param2
Isn't there a function that returns all path variables including param1 and param2 in middleware? 
(like url.Query())

What I expect is this.
--> 
url : test/1/test2/2
function returns: param1:1, param2:2

**Comment by ReneWerner87** [comment]
we do not have such a method, since we assumed that if the route itself is defined, you know the parameters

you can still get the route from the context and there is a parameters node which contains all parameters in a slice

**Comment by ReneWerner87** [comment]
@cw-20020752

**Comment by long2ice** [comment]
Current I do like this:
```go
params := make(map[string][]string)
for _, param := range c.Route().Params {
	params[param] = append(params[param], c.Params(param))
}
```

**Comment by ReneWerner87** [comment]
@long2ice perhaps a new method in context worth ?

**Comment by cw-20020752** [comment]
Thanks for your kind replies!
