### ISSUE TITLE
🤗 How about this FIber picture as my head picture?

### ISSUE THREAD

**Issue by AmyYummy** [gofiber/fiber#1817]
Hi friends!
I found an amazing [fiber](https://www.baudcom.cn) picture from the net? How about use it as my headpicture ?
![image](https://user-images.githubusercontent.com/97929262/157363422-ec1c752d-59a5-4155-a3bd-d286e7e99841.png)

**Comment by hi019** [comment]
Headpicture?

**Comment by ClaudiaChan1996** [comment]
Look my headpicture, If you use it, we will be the same, kkkkk
