### ISSUE TITLE
🤔 How do I register partials for handlebars?

### ISSUE THREAD

**Issue by Terisback** [gofiber/fiber#182]
**Question description**
How do I can register partials like {{> myPartial}} through fiber?

**Comment by Fenny** [comment]
@Terisback, thanks for trying out Fiber!

Our `Render` function is currently designed to perform basic templating, you can see how it works here: https://fiber.wiki/context#render
We would love to improve our render function to register partials or add custom functions.

If you have suggestions or ideas on how we should implement that in the Fiber API, feel free to let us know. There is always room for improvement :+1:

**Comment by Terisback** [comment]
Thank you, I am a beginner programmer, and for the first time I am writing a web application, but I find this package the most convenient of all.
I will do my best to make this package better.  I will try, despite my level of knowledge ☺️
