### ISSUE TITLE
🚀 v3 Request: Detailed Binding for Query, Form, Headers, Params...

### ISSUE THREAD

**Issue by efectn** [gofiber/fiber#1821]
Fiber already has QueryParser, BodyParser and ReqHeadersParser but they're really limited and not extendable. Also i think we don't need gorilla/schema. 

I think creating binding sub-directory will solve this problem. https://github.com/gin-gonic/gin/tree/master/binding. It'll provide more more detailed binding specs. (without default validator, maybe custom validator function can be added, https://github.com/gofiber/fiber/pull/1766).

Also adding all methods to ctx would be make ctx really mess and big. So we should add these binding methods by sub-method.
```
Bind().URI()
Bind().Form()
Bind().Params()
Bind().Headers()
```

Look These:
- https://github.com/gin-gonic/gin#model-binding-and-validation
- https://echo.labstack.com/guide/binding/
- https://github.com/gin-gonic/gin/tree/master/binding
- https://github.com/labstack/echo/blob/master/bind.go
- https://github.com/labstack/echo/blob/master/binder.go

**Comment by efectn** [comment]
> can we change validator function by passing another implemen?

Yes

**Comment by hotrungnhan** [comment]
hope it release soon

**Comment by efectn** [comment]
> hope it release soon

Hi. I'll start implementing this after closing some PRs for v3. https://github.com/orgs/gofiber/projects/1
