### ISSUE TITLE
🚀 v3 Request: fiber.Ctx type of interface

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#1824]
If fiber.Ctx will be interface , we can customize it.

Example

```go
type CustomCtx struct {
	fiber.Ctx
}

func (c *CustomCtx) Foo() {
	println("foo")
}

func (c *CustomCtx) Bar() {
	println("bar")
}

app.Get("/", func(c CustomCtx) error {
	c.Foo()
	c.Bar()
	return c.JSON("")
})
```

**Comment by efectn** [comment]
Similar to: 
- https://github.com/labstack/echo/blob/master/context.go#L19  
-  https://echo.labstack.com/guide/context/

**Comment by Trim21** [comment]
I have a question about this, what stop users doing the same thing if `Ctx` is a struct?

```golang
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
)

type CustomCtx struct {
	*fiber.Ctx
}

func (cc CustomCtx) Foo() {
	fmt.Println("foo")
}

func (cc CustomCtx) Boo() {
	fmt.Println("bar")
}

func main() {
	app := fiber.New(fiber.Config{})

	app.Get("/", func(c *fiber.Ctx) error {
		cc := CustomCtx{c}

		cc.Foo()
		cc.Boo()

		return cc.JSON("")
	})
}
```

**Comment by efectn** [comment]
> ```go
> package main
> 
> import (
> 	"fmt"
> 
> 	"github.com/gofiber/fiber/v2"
> )
> 
> type CustomCtx struct {
> 	*fiber.Ctx
> }
> 
> func (cc CustomCtx) Foo() {
> 	fmt.Println("foo")
> }
> 
> func (cc CustomCtx) Boo() {
> 	fmt.Println("bar")
> }
> 
> func main() {
> 	app := fiber.New(fiber.Config{})
> 
> 	app.Get("/", func(c *fiber.Ctx) error {
> 		cc := CustomCtx{c}
> 
> 		cc.Foo()
> 		cc.Boo()
> 
> 		return cc.JSON("")
> 	})
> }
> ```

Yes it works. However, interfaces give us more extendable and readability. I support using interface as Ctx type because of its.

**Comment by Trim21** [comment]
It doesn't have any difference with your example in PR, is there something I missed?

**Comment by efectn** [comment]
> It doesn't have any difference with your example, did I miss something?
> 
> Is there a more complex example?

If context is an interface, we can use type casting:
```go
cc := c.(*CustomCtx)
```

But usages like `return cc.SendString("")` gives an segmentation error. I should find a solution for this problem
