### ISSUE TITLE
🚀 v3 Request: fiber.Error's message type of interface{}

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#1825]
If fiber.Error's message's type will be interface{}, we can return multiple error messages etc.

Example 

```go
fiber.NewError(fiber.StatusBadRequest, fiber.Map{
  "type": "validation",
  "message": "email is invalid",
})
```

**Comment by efectn** [comment]
Same as https://github.com/gofiber/fiber/pull/1728

**Comment by pwtitle** [comment]
i want this: fiber.NewError(fiber.StatusBadRequest, "validation", "email is invalid", "other message")
