### ISSUE TITLE
🚀 v3 Request: Remove Listener, ListenTLS, ListenMutualTLS

### ISSUE THREAD

**Issue by efectn** [gofiber/fiber#1826]
```go
func (app *App) Listen(addr string, config ...ListenConfig) error

type ListenConfig struct {
	ListenerNetwork string
        CertFile string
        KeyFile string
        ClientCertFile string
	DisableStartupMessage bool
        EnablePrefork bool
	GracefulContext context.Context
	GracefulTimeout time.Duration
	TLSConfigFunc func(tlsConfig *tls.Config)
	ListenerAddrFunc func(addr net.Addr)
}
```

I think this way is more useful than creating more methods.

Reference: https://github.com/labstack/echo/blob/v5_alpha/server.go

**Comment by kstieger** [comment]
Hi,
I know this is maybe an additional FRQ, but an option for Listener on a unix socket (/var/run/example.sock) as alternative to the IP/TCP socket would be fine. Or is this already possible?
