### ISSUE TITLE
🚀 v3 Request: Optional PCRE Support for Routing

### ISSUE THREAD

**Issue by efectn** [gofiber/fiber#1827]
Regex would be really useful and powerful for Fiber routing. But Go's native regex library is really slow and not compatible with PCRE %100. 

So; what about adding pcre library with cgo? Also we can enable it by custom build tag. Users need regex can enable it easily. 

Library: https://github.com/scorpionknifes/go-pcre

**Comment by liaohongxing** [comment]
It is not recommended to use cgo, it seems better to make a community package

**Comment by efectn** [comment]
> 

But it will be slow if we don't build it with C.

**Comment by efectn** [comment]
With https://github.com/gofiber/fiber/issues/1903, we won't need this feature.
We can add custom MatchString into the config like https://github.com/gofiber/fiber/blob/master/app.go#L327. It's more easy and cleaner than this way. So i close the issue.
