### ISSUE TITLE
🤗 How can I resolve a named route with params to an actual url.

### ISSUE THREAD

**Issue by oeaniz** [gofiber/fiber#1830]
** resolving named route with params.**

Given the snippet below, In my view, I want to create a link to some user 'foo" in my view. I can't seem to find a way to do that.
I know how to redirect using a route and paramers, but it uses an internal method ```Ctx.getLocationFromRoute``` that's not available otherwise.
Is there something I'm missing, or should I make a feature request to make the getLocationFromRoute function public?

**Code snippet**

```go
func main() {
	app := fiber.New()
	
	app.Get("/users/:user", func(ctx *fiber.Ctx) error {
		return ctx.SendString(fmt.Sprintf("hello, %v.", ctx.Params("user")))
	}).Name("users")
	
	app.Get("/redirect/:username", func(ctx *fiber.Ctx) error {
		return ctx.RedirectToRoute("users", fiber.Map{"user": ctx.Params("username")})
	})

	theuser := app.GetRoute("users")
	fmt.Println(theuser.Path) // => /users/:user
}
```

**Comment by efectn** [comment]
Do you want to change params of route? Like Laravel's route() method.

**Comment by oeaniz** [comment]
I have never used Laravel. But yes, from the looks of it, this snippet from the laravel docs (https://laravel.com/docs/9.x/routing#generating-urls-to-named-routes) is exaclty what i'm looking for in fiber:

```
Route::get('/user/{id}/profile', function ($id) {
    //
})->name('profile');
 
$url = route('profile', ['id' => 1]);
```

**Comment by efectn** [comment]
> I have never used Laravel. But yes, from the looks of it, this snippet from the laravel docs (https://laravel.com/docs/9.x/routing#generating-urls-to-named-routes) is exaclty what i'm looking for in fiber:
> 
> ```
> Route::get('/user/{id}/profile', function ($id) {
>     //
> })->name('profile');
>  
> $url = route('profile', ['id' => 1]);
> ```

Yeah, it would be nice feature. What do you think @ReneWerner87

**Comment by ReneWerner87** [comment]
Jo sounds good

**Comment by sujit-baniya** [comment]
Just FYI, there's already a function doing this stuff. https://github.com/gofiber/fiber/blob/master/ctx.go#L1083

Just need to give it a name and export
