### ISSUE TITLE
🤗  Requests from newly created pods get timeout from Fiber server

### ISSUE THREAD

**Issue by hakangs** [gofiber/fiber#1837]
**Question description**
We have a server with Fiber, that is serving requests from a service. 
When this service make deployment in Kubernetes, newly created pods are getting timeout for a small amount of time.
All server side Fiber configs are default and not set with custom values, etc.

What can be the possible problem with this newly created pods timeout? What is the best ways & points to debug?

**Comment by ReneWerner87** [comment]
we also have fiber services in kubernetes 

do you use the live and readiness probe ?

**Comment by ReneWerner87** [comment]
you should have a health endpoint
![image](https://user-images.githubusercontent.com/7063188/159921204-64acc285-7672-41cc-8c0a-4221ef98b06a.png)


and a liveness and readiness probe on your deployment
![image](https://user-images.githubusercontent.com/7063188/159921335-1c9bd40b-275b-4021-97a4-44b0bc540c73.png)


and i would recommend the rollingUpdate stragtegy
![image](https://user-images.githubusercontent.com/7063188/159921447-863a571a-cba9-4bcc-b7a5-4380e063cf14.png)


for zero downtime

**Comment by hakangs** [comment]
@ReneWerner87 thanks for answer. Yes we have both RollingUpdate and live/readiness probes for Fiber server app.
But the timeouts are happening when client app is making a new deployment.

**Comment by ReneWerner87** [comment]
> But the timeouts are happening when client app is making a new deployment.

i can't really relate, as it is almost impossible for the fiber server not to be ready when it comes into distribution

since the health endpoint has been called beforehand to confirm that everything is ready

**Comment by ReneWerner87** [comment]
need more information to help you with this

a setup where i can understand what the problem is

did I understand correctly that it is about the timeouts of the clients to the fiber server ?

**Comment by ReneWerner87** [comment]
perhaps there are problems because the other service which is shut down is no longer responding properly 

i think we also had such a problem, so we added a 5 second delay on stop

![image](https://user-images.githubusercontent.com/7063188/159923612-a3df0472-1c4c-44d2-b867-19194232e391.png)
this should help the old service to shut down properly

**Comment by ReneWerner87** [comment]
also think there was a problem with the rollingUpdate, that didn't work 100% yet -> that's why we added the sleep at podStop

would try it in your place, maybe it fixes the cause, until kubernetes fixes the internal error

**Comment by hakangs** [comment]
thanks for the suggestions, but timeouts are coming from newly created pods (not from stopping ones). I do not know if it can be related with preStop, will try, thanks.

**Comment by ReneWerner87** [comment]
please try, there was a problem in the rolling update feature from kubernetes

**Comment by ReneWerner87** [comment]
any news ?
