### ISSUE TITLE
🐛 Sub fiber's error handlers not working

### ISSUE THREAD

**Issue by h4ckedneko** [gofiber/fiber#1839]
**Fiber version**
v2.30.0

**Issue description**
In v2.24.0, custom error handler in fiber sub apps is captured by the main fiber app when you mounted them (#1560). But this doesn't work anymore with the recent version.

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

// Custom error handler.
func apiErrorHandler = func(c *fiber.Ctx, err error) error {
    // Custom error handling logic here.
    // ...

    // Return from handler
    return nil
}

func main() {
  app := fiber.New()

  // Steps to reproduce  
  api := fiber.New(fiber.Config{
    ErrorHandler: apiErrorHandler,
  })
  
  app.Mount("/api", api)

  log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
)

// Custom error handler.
func apiErrorHandler(c *fiber.Ctx, err error) error {
	// Custom error handling logic here.
	// ...
	fmt.Println("apiErrorHandler", err)
	// Return from handler
	return fiber.DefaultErrorHandler(c, err)
}

func main() {
	app := fiber.New()

	// Steps to reproduce
	api := fiber.New(fiber.Config{
		ErrorHandler: apiErrorHandler,
	})

	api.Get("/test", func(ctx *fiber.Ctx) error {
		return fiber.ErrBadRequest
	})

	app.Mount("/api", api)

	log.Fatal(app.Listen(":3000"))
}
```

```sh
curl -i http://localhost:3000/api/test
```


can not reproduce, need more information on this

for me it works as seen in the screenshot
![image](https://user-images.githubusercontent.com/7063188/160660673-e4d15f31-df39-4851-b6c1-e2bf21da1b9e.png)

can you refine your example or describe the error in more detail ?

**Comment by h4ckedneko** [comment]
Hello, I created a git repo to reproduce this bug:
https://github.com/h4ckedneko/fiber-bug

**Comment by h4ckedneko** [comment]
Both v2.25.0 and v2.31.0 have the same fiber setup. But if you run them, the recent version doesn't print "custom error handler called" meaning the custom error handler is not being registered.

**Comment by h4ckedneko** [comment]
![image](https://user-images.githubusercontent.com/25201563/161476118-3a7457e9-712b-47df-88a1-fcf63c79441d.png)
![image](https://user-images.githubusercontent.com/25201563/161476175-7a522758-1ec6-418a-b5af-f822fa312838.png)

**Comment by ReneWerner87** [comment]
okay found the error, it only occurs when you root mounted apps from other fiber instances

we will fix it, thanks for the info

related to the refactoring from :
https://github.com/gofiber/fiber/pull/1749/files

**Comment by h4ckedneko** [comment]
Thanks Fiber team! 🥳
