### ISSUE TITLE
🚀  v3 Request: Retry Mechanism

### ISSUE THREAD

**Issue by gozeloglu** [gofiber/fiber#1840]
**Is your feature request related to a problem?**

**Describe the solution you'd like**
I am planning to add the exponential backoff algorithm. It is a widely used retry policy. Basically, there will be 2 different functions. One is `Retry()` (or `Do()` ) method and `NextBackoff()`(or `NextTime()`) methods. Of course, there will be some helper methods like `NewBackoff()`, `Reset()`. This feature will be flexible. The users can be used `Retry()` method and everything will be handled by the package. They won't consider details. They will just call the method like this:

```go
backoff.Retry(func() error{
    // Do whatever you want    
    return err
})
```
Or, maybe some users want to handle the retry part themselves. In this case, we provide all functionalities other than `Retry()` method like `Reset()`, `NextTime()`, `Sleep()`. They use the package and call the methods like this:

```go
for i := 0; i < n; i++ {
    ...
    next := backoff.NextTime()
    backoff.Sleep(next)
}
...
backoff.Reset()
```
Also, we can add two options to check the retry count/time with `Context` and `retryCount`. In `Context` usage, we set timeout to `context` and retry goes until timeout expires. For `retryCount` usage, we set number of retry step like 10, and the method retries 10 times. 

**Describe alternatives you've considered**
[**Regular Interval**](https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults#:~:text=Regular%20intervals.%20The%20application%20waits%20for%20the%20same%20period%20of%20time%20between%20each%20attempt.%20For%20example%2C%20it%20may%20retry%20the%20operation%20every%203%20seconds.): Waits in regular period of time.
[**Incremental Intervals**](https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults#:~:text=Incremental%20intervals.%20The%20application%20waits%20a%20short%20time%20before%20the%20first%20retry%2C%20and%20then%20incrementally%20increasing%20time%20between%20each%20subsequent%20retry.%20For%20example%2C%20it%20may%20retry%20the%20operation%20after%203%20seconds%2C%207%20seconds%2C%2013%20seconds%2C%20and%20so%20on.): Waiting time is increasing incrementally. 
**Additional context**
* [cenkalti/backoff](https://github.com/cenkalti/backoff)
* https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/ 
* https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/
* https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults
* [Other Go packages](https://github.com/search?q=backoff+language%3Ago)

**Comment by vishjain** [comment]
Can I contribute to this issue? Thanks!

**Comment by ReneWerner87** [comment]
Sure

**Comment by gozeloglu** [comment]
I was expecting to implement this. I mentioned that wanted to implemenet it in discussion section and proposed above solutions. As I remember @ReneWerner87 told me that v3 implementations hasn't been started yet when I asked it.

**Comment by ReneWerner87** [comment]
there is the https://github.com/gofiber/fiber/tree/v3-beta branch 
you can fork another branch from it and create a pull request for it on the beta branch

Sorry @vishjain  gozeloglu has the prerogative and if he has time and desire he should start with it
