### ISSUE TITLE
🐛 Mount sub fiber app on "/"

### ISSUE THREAD

**Issue by lotryas** [gofiber/fiber#1842]
**Fiber version**
2.31.0

**Issue description**
I can access http://localhost:3000/hello but I can't access http://localhost:3000/ for some reason. I get a 404 response from the last handler

**Code snippet**

```go
package main

import (
    "log"

    "github.com/gofiber/fiber/v2"
)

func main() {
    app := fiber.New()

    api := fiber.New()
    api.Get("/", func(c *fiber.Ctx) error { return c.SendString("api") })

    web := fiber.New()
    web.Get("/", func(c *fiber.Ctx) error { return c.SendString("home") })
    web.Get("/hello", func(c *fiber.Ctx) error { return c.SendString("hello") })
    web.Use(func(c *fiber.Ctx) error {
        return fiber.NewError(fiber.StatusNotFound)
    })

    app.Mount("/api", api)
    app.Mount("/", web)

    log.Fatal(app.Listen(":3000"))
}
```

```
curl -i http://localhost:3000//
curl -i http://localhost:3000/hello
curl -i http://localhost:3000/
```

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/161695478-dddcc58e-236a-4d11-a40c-06dc4fdb0442.png)


its fixed with the last commit
require github.com/gofiber/fiber/v2 v2.31.1-0.20220405064022-a8f9d4acfb2c


https://github.com/gofiber/fiber/commit/a8f9d4acfb2ccd533a458415ac0cffec62af0fda

**Comment by ReneWerner87** [comment]
Reason for the bugs:
problem was solved by optimizing the mounting
there the functionality for the root path was broken, because there a trimRight with "/" was used
https://github.com/gofiber/fiber/pull/1749/files
