### ISSUE TITLE
HCaptcha Implementation in Fiber?🤗 

### ISSUE THREAD

**Issue by alphonso06** [gofiber/fiber#1843]
**Question description**
I'm trying to figure out how to properly implement server-side validation with hCaptcha. The only package I could find in Go that does hCaptcha validation is [this one.](https://github.com/kataras/hcaptcha)

`hcaptcha.Get()` is unfortunately looking for a type of `*http.Request`, which I believe requires `net/http`. My app is already quite large and I was tasked to add a new hCaptcha validation.

**Code snippet** _Optional_

```go
func VerifyCaptcha(c *fiber.Ctx) error {
    type CaptchaInput struct {
      Response string `form:"response" validate:"required"`
      Sitekey  string `form:"sitekey" validate:"required"`
    }
    
    var ci CaptchaInput
    v := validator.New()
    
    if err := c.BodyParser(&ci); err != nil {
      fmt.Println(err)
      return c.Status(400).SendString("captcha error")
    }
    
    if err := v.Struct(&ci); err != nil {
      return c.Status(400).SendString(err.Error())
    }
    
    hcaptcha.New(config.Env("HCAPTCHA_SECRET"))
    hcaptchaResp, ok := hcaptcha.Get(ci) //--> needs a type of *http.Request
    
    if !ok {
      return c.Status(401).SendString("Are you a robot?")
    }
    
    return c.Status(200).JSON(fiber.Map{
      "message":  "Captcha success",
      "response": hcaptchaResp,
    })
}
```

**Comment by sujit-baniya** [comment]
@alphonso06 I've created hcaptcha middleware https://github.com/sujit-baniya/hcaptcha. Check the example https://github.com/sujit-baniya/hcaptcha/blob/master/examples/main.go
