### ISSUE TITLE
🐛 JSON parsing exception contains an array at the end

### ISSUE THREAD

**Issue by qmdx** [gofiber/fiber#1844]
**Fiber version**

v2.31.0

**Issue description**

JSON parsing exception .  `Skus` Unrecognized

**Code snippet**

```go
var purchaseOrderParams storeReq.PurchaseOrderParams
_ = c.BodyParser(&purchaseOrderParams)

type PurchaseOrderParams struct {
	store.PurchaseOrder
	Skus []*store.PurchaseSku `json:"skus,omitempty"`
}
```

Normal   JSON

````
{
    "skus": [
        {
            "spuId": 12,
            "spuNum": "123"
        }
    ],
    "warehouseId": 14,
    "supplierId": 4
}
````

Unrecognized  JSON

````
{
    "warehouseId": 14,
    "supplierId": 4,
    "skus": [
        {
            "spuId": 12,
            "spuNum": "123"
        }
    ]
}
````

**Comment by ReneWerner87** [comment]
Can you please provide all structs so we can analyze this behavior?

**Comment by ReneWerner87** [comment]
Without having made the first analysis, I think the problem is struct inheritance

What is not processed by the schema parser as you think

Your warehouse id should be under

root.PurchaseOrder.warehouseId

Please test the whole thing without inherited structs

**Comment by ReneWerner87** [comment]
@qmdx
