### ISSUE TITLE
🚀  Append queries to RedirectToRoute

### ISSUE THREAD

**Issue by laeo** [gofiber/fiber#1850]
**Is your feature request related to a problem?**

I would like to call `c.RedirectToRoute("login", fiber.Map{"code": state})`, `code` is not a route parameter, i want it will be passed as an GET query parameter.

**Describe the solution you'd like**

Let the second param is passed as queries to redirection.

**Describe alternatives you've considered**

Use `c.Redirect()` and create direction URL with additional queries manually.

**Additional context**

**Comment by laeo** [comment]
Wow its a really good news to me, but this impl isn't looks very well. The `queries` field uses `url.Values` may better than `map`, it gives more compatibility to other libs.

And, in my other frameworks' exp, `RedirectToRoute` is better to handle all params which not defined as path param to be normal queries in URL, and this action may not break backward-compatibility if we give users a option to enable it.

**Comment by efectn** [comment]
> Wow its a really good news to me, but this impl isn't looks very well. The `queries` field uses `url.Values` may better than `map`, it gives more compatibility to other libs.
> 
> And, in my other frameworks' exp, `RedirectToRoute` is better to handle all params which not defined as path param to be normal queries in URL, and this action may not break backward-compatibility if we give users a option to enable it.

It makes really much allocs.
