### ISSUE TITLE
🐛 When i use proxy middleware and the target url is begin with https, I got an error.

### ISSUE THREAD

**Issue by Hevienz** [gofiber/fiber#1855]
**Fiber version**
v2.31.0

**Issue description**
When i use proxy middleware and the target url is begin with https, I got "HostClient can't follow redirects to a different protocol, please use Client instead".

**Code snippet**

```go
        adminApiAddress := fmt.Sprintf("https://127.0.0.1:%d", apiAddress.Port)

	config := &tls.Config{InsecureSkipVerify: true}

	app.Use("/stat", proxy.Balancer(proxy.Config{
		Servers: []string{
			adminApiAddress,
		},
		TlsConfig: config,
	}))
```

**Comment by bigflood** [comment]
@Hevienz  
Currently, `proxy.Balancer` works only for `http -> http`.   
(you can work around the error by using `proxy.Do` or `Proxy.Forward` instead of `proxy.Balancer`)

@ReneWerner87  
May I work on this issue?

**Comment by Hevienz** [comment]
@bigflood 
I have tried proxy.Forward, just like below.
```go
        adminApiAddress := fmt.Sprintf("https://127.0.0.1:%d", apiAddress.Port)

	app.Use("/stat", proxy.Forward(adminApiAddress))
```
I got this error, "x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs".

So I try to skip verify, just like below.

```go
	adminApiAddress := fmt.Sprintf("https://127.0.0.1:%d", apiAddress.Port)

	proxy.WithTlsConfig(&tls.Config{
		InsecureSkipVerify: true,
	})

	app.Use("/stat", proxy.Forward(adminApiAddress))
```
This time I got 404.

Do you have any suggestions?

**Comment by bigflood** [comment]
@Hevienz  
LGTM

there is also test code:
https://github.com/gofiber/fiber/blob/728e9231deef7cd3c8365575f6a35726c33506e4/middleware/proxy/proxy_test.go#L203

it is possible that the admin API server responding with 404

**Comment by Hevienz** [comment]
@bigflood 
Yeah, you are right! The backend return 404.
