### ISSUE TITLE
middleware monitor question.

### ISSUE THREAD

**Issue by sman-cn** [gofiber/fiber#1856]
**Question description**
On my first fiber site,
I added client-side cache headers for every get request, and the monitor middleware didn't work properly. It seems to be cached.
Maybe it's better to use post request? .
Thank you!
**Code snippet**
```go
app.Use(func(c *fiber.Ctx) error {
		if c.Method() == "GET" and 	 {
			c.Append("Cache-Control", "max-age=1800")
		}
}
```

**Comment by efectn** [comment]
You can skip monitor middleware by using `c.Path()` @sman-cn

**Comment by sman-cn** [comment]
Thank you, I didn't use c.Path(), it seems better code like this？
```go
app.Get("/xxxxx", monitor.New(monitor.Config{
	Next: func(c *fiber.Ctx) bool {
		c.Append("Cache-Control", "")
		return false
	},
}))
```
So it looks better if this middleware changed to POST method?😃

**Comment by efectn** [comment]
> Thank you, I didn't use c.Path(), it seems better code like this？
> 
> ```go
> app.Get("/xxxxx", monitor.New(monitor.Config{
> 	Next: func(c *fiber.Ctx) bool {
> 		c.Append("Cache-Control", "")
> 		return false
> 	},
> }))
> ```
> 
> So it looks better if this middleware changed to POST method?😃

Yeah it would be better if we use API section of middleware as POST but it can be breaking-change🤔🤔

https://github.com/gofiber/fiber/blob/master/middleware/monitor/monitor.go#L84

**Comment by darkweak** [comment]
The monitor middleware could return a `Cache-Control: no-store, no-cache` HTTP header directive to fix that.

**Comment by sman-cn** [comment]
> 监视器中间件可以返回一个`Cache-Control: no-store, no-cache`HTTP 标头指令来解决这个问题。

好主意！👍
