### ISSUE TITLE
Different status codes in logger middleware compared to Chrome dev tools

### ISSUE THREAD

**Issue by AntonFridlund** [gofiber/fiber#1857]
**Question description**
Hello.  
I am using the etag and logger middleware.  
My goal is to create a client side cache for my web application.  
Chrome seems to like the solution and responds with a `304` status code. But the logger middleware responds with a `200` status code.  
Is this normal? The behavior in other servers such as Expressjs shows the `304` status code in the logger middleware.

Here are two images describing what I see in Chrome vs what the logger spits out:  

![image](https://user-images.githubusercontent.com/31419272/163277639-a837df5d-2eaa-47cf-b255-8e311a7f28d9.png)
![image](https://user-images.githubusercontent.com/31419272/163277453-45f5eb32-e389-4a67-aa0b-995231c36d95.png)

What I was expecting was something like this (taken from an Express server using morgan logger middleware):  
![image](https://user-images.githubusercontent.com/31419272/163278757-9db3935e-cee0-4a50-b1ea-7c9e64389b08.png)

### Code used for this example:

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/etag"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
	app := fiber.New()

	app.Use(etag.New())
	app.Use(logger.New())
	
	app.Get("/", func(ctx *fiber.Ctx) error {
		return ctx.SendString("OK")
	})

	app.Listen(":8080")
}
```

I'm not very well versed in the Go programming language but I have some experience working with Express servers.  
Appreciate any help in solving this 🙂

**Comment by ReneWerner87** [comment]
Should be due to the order of the declarations, the etag middleware wants to start after the business run with the logic of the middleware and the logging for the response works similarly

Probably the logging is executed first and then the process of the etag middleware for changing the status code is executed

Please try to swap the logging middleware and the position of the etag middleware and

**Comment by AntonFridlund** [comment]
Swapping the logging middleware and the etag middleware worked!  
I now get the `304` status code in the logger.  
👍 Now I can continue working on my awesome application.  

Thank you for the help!
