### ISSUE TITLE
🌐 Translate Fiber (i18n)

### ISSUE THREAD

**Issue by koddr** [gofiber/fiber#186]
## 💡 Translation status

**Fiber** [README](https://github.com/gofiber/fiber/blob/master/.github/README.md) is already translated into **9** languages:

- [x] 🇷🇺 Russian (RU)
- [x] 🇪🇸 Spanish (ES)
- [x] 🇨🇳 Chinese (ZH_CH)
- [x] 🇯🇵 Japanese (JA)
- [x] 🇵🇹 Portuguese (PT)
- [x] 🇩🇪 German (DE) 
- [x] 🇰🇷 South Korean (KO)
- [x] 🇫🇷 French (FR)
- [x] 🇹🇷 Turkish (TR)

**Fiber** [official documentation](https://fiber.wiki) is already translated into **4** languages:

> ❗️ This translations **on hold**. We're preparing to re-write English docs after release **Fiber** v1.8.

- [x] 🇷🇺 Russian (RU)
- [ ] 🇪🇸 Spanish (ES)
- [x] 🇨🇳 Chinese (ZH_CH)
- [ ] 🇯🇵 Japanese (JA)
- [ ] 🇵🇹 Portuguese (PT)
- [ ] 🇩🇪 German (DE) 
- [x] 🇰🇷 South Korean (KO)
- [x] 🇫🇷 French (FR)
- [ ] 🇹🇷 Turkish (TR)

## ✨ Add new translation

Anyone, who wants to add a new translation for **Fiber**, must follow these simple rules:

1. The translation must fully follow the narrative, structure and style of presentation as in the main `README.md` file.
2. To be added to the `master` branch, the translation must be completely finished and double-checked.
3. IT-specific phrases and comments in code snippets may not be translated.

Recommendations for PR description:

- Add link to flag for your language or country (we use [`flag-icon-css`](https://github.com/lipis/flag-icon-css) with 4x3 format, for example, [EN](https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.4.6/flags/4x3/gb.svg) lang flag).
- Add some words about tools, which you used to validate translation (like _Google Translator_, _GitLocalize_ or _DeepL_).

## ✏️ Update translation, when new features are shipped

For current **Fiber** translators: please read the release notes of new official versions to update **Fiber** docs and `README.md` file for your language!

## 💭 Improve/fix translation

If you find a translation error or want to improve translation, please make a fork of this repository, edit the corresponding `README` file in `.github` folder and send PR.

## ✍️ Translators list

<details>
<summary>Click to see translators list</summary>

### 🇷🇺 Russian

- [Docs](https://fiber.wki): 
  - @koddr 
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_ru.md):
  - @koddr 

### 🇪🇸 Spanish

- [Docs](https://fiber.wki): 
  - Auto translate
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_es.md):
  - Auto translate

### 🇨🇳 Chinese

- [Docs](https://fiber.wki): 
  - @keob 
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_zh-CH.md):
  - @keob 

### 🇯🇵 Japanese

- [Docs](https://fiber.wki): 
  - Auto translate
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_ja.md):
  - @nasjp 

### 🇵🇹 Portuguese

- [Docs](https://fiber.wki): 
  - Auto translate
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_pt.md):
  - @matAlmeida 

### 🇩🇪 German

- [Docs](https://fiber.wki): 
  - Auto translate
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_de.md):
  - Auto translate

### 🇰🇷 South Korean

- [Docs](https://fiber.wki): 
  - @yhg8423 
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_ko.md):
  - @korJAEYOUNGYUN
  - @yhg8423 

### 🇫🇷 French

- [Docs](https://fiber.wki): 
  - @Ynniss 
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_fr.md):
  - @Ynniss 

### 🇹🇷 Turkish

- [Docs](https://fiber.wki): 
  - Auto translate
- [README](https://github.com/gofiber/fiber/blob/master/.github/README_tr.md):
  - @mkacmaz 

</details>

> This list will be update by **Fiber** authors, after merge your PR to `master` branch.

## ⚠️ Warnings about liability

- All translations are done by volunteers, who are not indifferent to **Fiber**. 
- **Fiber** authors are not responsible for these translations, other than English, because they simply does not speak all these languages.

**Comment by hyingreborn** [comment]
official documentation can't see any language for a few days，only english as default

**Comment by keob** [comment]
ok

**Comment by koddr** [comment]
> @hyingreborn: official documentation can't see any language for a few days，only english as default

Yes, it's because we're preparing to re-write English docs after release Fiber `v1.8`. This section of translations on hold and hidden now.

**Comment by keob** [comment]
I translate chinese docs  now😊

**Comment by keob** [comment]
Many places in the document are not the same

**Comment by Ynniss** [comment]
ok, i'm gonna wait for the "new" english docs, to then translate it to french

**Comment by Fenny** [comment]
@keob, please wait for new documentation before you translate.
The English docs will be updated upon the next Fiber release.

**Comment by keob** [comment]
@Fenny ok😊😊
