### ISSUE TITLE
🤗 socket.io + Fiber compatibility

### ISSUE THREAD

**Issue by JuzioMiecio520** [gofiber/fiber#1864]
**Question description**
Hi,
I have a question regarding Fibers compatibility with socket.io. I've seen #1126, but it's from a year ago, so I'd like to know if there's been any development towards resolving that issue. If not, is there any simillar custom protocol like socket.io?

Thanks in advance!

**Comment by efectn** [comment]
Maybe this middleware can be helpful for you. https://github.com/antoniodipinto/ikisocket

It was inspired by Socket.io

**Comment by JuzioMiecio520** [comment]
Oh, that's awesome, thanks. It doesn't seem to support rooms, like socket.io did (only send to lists of UUIDs), but that's great anyways, thanks!

**Comment by doquangtan** [comment]
Socket.io for gofiber https://github.com/doquangtan/gofiber-socket.io
