### ISSUE TITLE
🐛 Cookie not setting for correct date

### ISSUE THREAD

**Issue by MaxTCodes** [gofiber/fiber#1865]
**Fiber version**
Fiber v2.31.0
**Issue description**
Cookie not setting for more than a year.
**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  app.Get("/", func(c *fiber.Ctx) error {
      cookie := fiber.Cookie{
			Name:    "Example Cookie",
			Value:   "data here",
			Expires: time.Now().Add(time.Second * 31560000),
		}
      c.Cookie(&cookie)
     return c.SendString("Set Cookie")
   })
  /* 
  Steps to reproduce:
  1. Start the server
  2. Go to localhost:3000
  3. Once there, open up developer tools
  4. Check the set cookies, and look at expiration.
  */
  log.Fatal(app.Listen(":3000"))
}
```

**Comment by renanbastos93** [comment]
I tested here and it worked

I added two years to expire. `expires=Thu, 18 Apr 2024 16:25:34 GMT;`
```
curl "http://127.0.0.1:3000/" -svk -o /dev/null
*   Trying 127.0.0.1:3000...
* Connected to 127.0.0.1 (127.0.0.1) port 3000 (#0)
> GET / HTTP/1.1
> Host: 127.0.0.1:3000
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Tue, 19 Apr 2022 16:25:34 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 10
< Set-Cookie: Example Cookie=data here; expires=Thu, 18 Apr 2024 16:25:34 GMT; path=/; SameSite=Lax
< 
{ [10 bytes data]
* Connection #0 to host 127.0.0.1 left intact```

**Comment by MaxTCodes** [comment]
Hi,

In my usage of gofiber, it seems that it doesn't set for 2 years, it's expiration gets set to 2022-04-20. 
![image](https://user-images.githubusercontent.com/25856189/164056096-8421110c-d141-4191-aefb-7a334e44f58e.png)

**Comment by ReneWerner87** [comment]
Can you please print out which system time in golang is the current one

Maybe we can find the cause

**Comment by MaxTCodes** [comment]
> Can you please print out which system time in golang is the current one
> 
> Maybe we can find the cause

The system time according to golang is `2023-04-19 20:13:02.6663192 -0400 EDT m=+31560000.005763401`, is that what you were looking for? Or are you looking for something else?

**Comment by ReneWerner87** [comment]
Yeah just time.Now()

**Comment by MaxTCodes** [comment]
Oh it's, `2022-04-19 13:46:57.1392545 -0400 EDT m=+0.005657601`

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/164207079-2f89ac92-5a80-48a2-97c6-017b06f18a57.png)
can also not detect any error, with me it runs

as long as we do not get a reproducible case, we can not help unfortunately

**Comment by MaxTCodes** [comment]
Okay!
