### ISSUE TITLE
🐛 ctx.Body not working in middleware

### ISSUE THREAD

**Issue by PringlePot** [gofiber/fiber#1866]
**Fiber version**
Latest
**Issue description**
When I was working I found out that ctx.Body() doesn't work when the request is using ctx.JSON(). Which means you have to use ctx.Context.Response.Body() instead

**Code snippet**

```go
if err := c.Next(); err != nil {
			return err
}

ctx.Body() // null
ctx.Context().Response.Body() // the body of the handler that's next

```

**Comment by renanbastos93** [comment]
@PringlePot Does it just not work? Or throw an error?

**Comment by PringlePot** [comment]
it just returns null while I do send a response

**Comment by PringlePot** [comment]
hi let me show you what I mean

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		// Get the response from the next request
		if err := c.Next(); err != nil {
			return err
		}


		return c.Body() // returns null while it shouldn't be, replacing it with fasthttp's body works c.Context().Response.Body()
	})

	app.Get("/", func(c *fiber.Ctx) error {
		return c.JSON(map[string]string{"data": "my data is little"})
	})

	app.Listen(":3000")
}
```

**Comment by renanbastos93** [comment]
of course, this behavior is right because `c.Body()` returns a `[]byte` then contract middleware Fiber is returning an error.

here not compile:
```cmd/main.go:22:10: cannot use c.Body() (value of type []byte) as type error in return statement:
        []byte does not implement error (missing Error method)```

**Comment by PringlePot** [comment]
That's not the point, if you print out both, the ctx.body will be null

**Comment by PringlePot** [comment]
🤦‍♂️I just noticed, sorry for wasting your time

**Comment by renanbastos93** [comment]
> 🤦‍♂️I just noticed, sorry for wasting your time

relax man. Thanks a lot for talking with us.
