### ISSUE TITLE
🤗 How to correctly configure custom ExpirationGenerator in cache middleware

### ISSUE THREAD

**Issue by breakbuidl** [gofiber/fiber#1869]
**Question description**
How to correctly configure custom ExpirationGenerator in cache middleware? My config is show below. (I am using Redis for storage with package `github.com/gofiber/storage/redis`

**Code snippet**

```
app.Use(cache.New(cache.Config{
    Next: func(c *fiber.Ctx) bool {
        return c.Query("refresh") == "true"
    },
    ExpirationGenerator: func(c *fiber.Ctx, cfg *cache.Config) time.Duration {
        newCacheTime, _ := strconv.Atoi(c.GetRespHeader("Cache-Time", "0"))
        return time.Second * time.Duration(newCacheTime)
    },
    KeyGenerator: func(c *fiber.Ctx) string {
        return c.OriginalURL()
    },
    Storage: database.Redis,
}))
```
I have not done anything fancy here, its the exact same `ExpirationGenerator` func mentioned in the docs. But, for some reason, key's expiration is always set to the default i.e `Expiration: 1 * time.Minute`. 

I have tried printing the value of `newCacheTime` and it's correct i.e whatever I send using `c.Response().Header.Add("Cache-Time", "30")`
```
 ExpirationGenerator: func(c *fiber.Ctx, cfg *cache.Config) time.Duration {
        newCacheTime, _ := strconv.Atoi(c.GetRespHeader("Cache-Time", "0"))
        fmt.Println(newCacheTime)
        return time.Second * time.Duration(newCacheTime)
    },
```
This is something so trivial but can't figure it out. It's driving me crazy.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/901492a78485b9c3e8378b8039f9e2b23a42bce6/middleware/cache/cache.go#L183

we have found that we use the expiration generator to write the expiration time to the item we are storing, but not if for the parameter which is to be set directly in the cache.

also better tests should be generated for the case

**Comment by ReneWerner87** [comment]
we could fix
https://github.com/gofiber/fiber/blob/901492a78485b9c3e8378b8039f9e2b23a42bce6/middleware/cache/cache.go#L170-L188
with 
```go
                // default cache expiration
		expiration := cfg.Expiration
		// Calculate expiration by response header or other setting
		if cfg.ExpirationGenerator != nil {
			expiration = cfg.ExpirationGenerator(c, &cfg)
		}
		e.exp = ts + uint64(expiration.Seconds())

		// For external Storage we store raw body separated
		if cfg.Storage != nil {
			manager.setRaw(key+"_body", e.body, expiration)
			// avoid body msgp encoding
			e.body = nil
			manager.set(key, e, expiration)
			manager.release(e)
		} else {
			// Store entry in memory
			manager.set(key, e, expiration)
		}
```

**Comment by breakbuidl** [comment]
I would like to take this up.

**Comment by ReneWerner87** [comment]
jo sure
