### ISSUE TITLE
🚀 Human readable BodyLimit

### ISSUE THREAD

**Issue by webdevium** [gofiber/fiber#1874]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**

What about make ability to set body size limit as human readable string?
Say we have environment variable `BODY_SIZE=42MB`
Then we read and set it to the fiber configuration.

Lets imagine **BodyLimitString** property in the fiber.Config
```
app := fiber.New(fiber.Config{
	BodyLimitString: os.Getenv("BODY_SIZE"),
})
```
And this property automatic parsed into bytes size

**Comment by ReneWerner87** [comment]
would treat the outside

integer numbers are perfect for config, everything else must be converted from outside

i.e. best you build a function that parses this or we could provide something in the utils, but in the config i wouldn't anchor it additionally

**Comment by webdevium** [comment]
@ReneWerner87  Fine. Maybe we can provide some function into Config, like ParseBodyLimit() as utility?

Sorry for my persistence. I'm just starting my journey into golang development.
I want to get it right :)

**Comment by webdevium** [comment]
Or you mean utils package?

**Comment by ReneWerner87** [comment]
converting does not really have anything to do with the bodylimit

we could provide a function in the utils called "ConvertToBits".
```go 
func ConvertToBits(humanReadbleBytes string) int
```

maybe here https://github.com/gofiber/fiber/blob/master/utils/common.go

**Comment by webdevium** [comment]
Sounds good!
Can I try to make this function?

**Comment by ReneWerner87** [comment]
```go
utils.ConvertToByte("42MB") // 4194304
utils.ConvertToByte("42MegaByte") // 4194304
utils.ConvertToByte("42MByte") // 4194304
```

**Comment by ReneWerner87** [comment]
> Sounds good! Can I try to make this function?

sure, but don´t forget 
unittests, documentation, benchmark method

**Comment by ReneWerner87** [comment]
Looks good, will merge it soon

**Comment by webdevium** [comment]
Tnx! 

Maybe I will be a good golang developer :)

**Comment by gaby** [comment]
@VanoDevium How do you use this function? There's no documentation about it. I tried: 

```
ConvertToBytes("20MB")
utils.ConvertToBytes("20MB")
fiber.ConvertToBytes("20MB")
common.ConvertToBytes("20MB")
```

They all return function is "undefined"

**Comment by ReneWerner87** [comment]
It's not released yet

But it's coming in the next days.

**Comment by gaby** [comment]
Thank you! 👍🏻
