### ISSUE TITLE
🐛 ctx.SendFile returns 404 not found if hash sign is in filename

### ISSUE THREAD

**Issue by FlandiaYingman** [gofiber/fiber#1876]
**Fiber version**
`github.com/gofiber/fiber/v2 v2.24.0`

**Issue description**
If a hash sign is in the filename, `ctx.SendFile` returns 404.

**Code snippet**

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	// Steps to reproduce
	app.Get("/0", func(ctx *fiber.Ctx) error {
		return ctx.SendFile("ascii_txt.txt")
	})
	app.Get("/1", func(ctx *fiber.Ctx) error {
		return ctx.SendFile("dollar_sign_$.txt")
	})
	app.Get("/2", func(ctx *fiber.Ctx) error {
		return ctx.SendFile("hash_sign_#.txt")
	})

	log.Fatal(app.Listen(":3000"))
}
```

**Comment by FlandiaYingman** [comment]
The problem happened here, `ctx.go:1382`:

```
// Set new URI for fileHandler
c.fasthttp.Request.SetRequestURI(file))
```

The variable `file` wasn't escaped before it got passed into `SetRequestURI`. So `file` got parsed into several part - part after `#`  was omitted. 

Because we can ensure when someone calls `ctx.SendFile`, they definitely don't want the path to contain a URI fragment (the part after hash sign) or a query string (after question mark, though most of the file system doesn't support containing question mark in filename). The way to solve this problem is to escape `file`, like: 

```
// Set new URI for fileHandler
c.fasthttp.Request.SetRequestURI(url.PathEscape(file))
```

**Comment by FlandiaYingman** [comment]
If you are happy with this solution, then I'll be glad to create a PR for this. XD

**Comment by ReneWerner87** [comment]
> If you are happy with this solution, then I'll be glad to create a PR for this. XD

normally i am in favor of such a customization, but unfortunately this makes the function slower for everyone else who does not have such characters in their file, so i would like to check other solutions

what happens if you use this function outside and then just use the escaped string in the sendFile method ? we could put a hint in the comment of the function if this works

**Comment by FlandiaYingman** [comment]
@ReneWerner87 

Good idea! I didn't even think of passing escaped string directly to `ctx.SendFile`. I tried and it worked.

Just add a hint in comment to let everyone know that the filepath would get parsed as URL.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/docs/commit/c0318bfe1ce3cecc348b4b48f8c5d2ee24f7dbf0

https://docs.gofiber.io/api/ctx#sendfile
