### ISSUE TITLE
Should the Context.Hostname reflect the port?

### ISSUE THREAD

**Issue by alexohneander** [gofiber/fiber#1878]
I am trying to check the hostname with my database via middleware. For testing purposes, I have directed a few domains to `127.0.0.1` via `/etc/hosts`.

The test is running on port **8080**.
But shouldn't the function only reflect the hostname?

**Code snippet**
```go
func (h *SiteHandler) checkIfSiteExistsMiddleware(c *fiber.Ctx) error {
	// Create a new customized context.
	customContext, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Fetch parameter.
	domain := c.Hostname()
	fmt.Println("Domain:", domain)

        ...
}
```

```bash
Domain: physio.test:8080
15:59:30 | 500 |    43ms |       127.0.0.1 | GET     | /
```

**Comment by hi019** [comment]
`ctx.Hostname()` just returns the `Host` request header (or the `X-Forwarded-Host` if you're using a proxy in the Fiber config).

`Host` may include a port number:

>  The Host request header specifies the host and port number of the server to which the request is being sent. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/host
