### ISSUE TITLE
🔥 add an interface for serving a custom net.Listener

### ISSUE THREAD

**Issue by cyolosec** [gofiber/fiber#188]
**Is your feature request related to a problem?**
no
**Describe the solution you'd like**
something along the lines of
```go
app := fiber.New()
ln, err := net.Listen("unix", "/tmp/sock.d")
app.Serve(ln)
```
**Describe alternatives you've considered**
editing the source code to add this functionality directly
**Additional context**

**Comment by Fenny** [comment]
@cyolosec, thanks for your first feature request!
Could you tell us a use-case example on why this could be a good feature for Fiber?

**Comment by Fenny** [comment]
@cyolosec, i'm closing this issue. Feel free to re-open :+1:

**Comment by TroyDota** [comment]
using unix sockets rather than open ports to increase performance.
