### ISSUE TITLE
🐛 The text color is too dark on linux terminal.

### ISSUE THREAD

**Issue by kuchaguangjie** [gofiber/fiber#1890]
**Fiber version**
v2.32.0

**Issue description**
The text color is too dark on linux terminal.
![c](https://user-images.githubusercontent.com/4230959/166142254-a8e601e2-49a5-40b5-a0bf-c06d61d80719.jpg)

It's almost unreadable when there is a white background:
![a](https://user-images.githubusercontent.com/4230959/166142280-b57642ff-d907-433a-b9f4-f14d0fe1d2aa.jpg)

**Comment by ReneWerner87** [comment]
unfortunately we can not prevent this

depending on what you have configured it can always lead to problems

maybe we should allow different themes for this
https://github.com/gofiber/fiber/blob/master/app.go#L1140-L1149

same with this
https://github.com/gofiber/fiber/blob/master/app.go#L1348-L1358

@hi019 @efectn what do you think ?

**Comment by efectn** [comment]
I think it's related of your color scheme. What's your color scheme?

**Comment by kuchaguangjie** [comment]
Mint mate 20, which is based on ubuntu. I didn't change the color scheme.

**Comment by efectn** [comment]
> unfortunately we can not prevent this
> 
> depending on what you have configured it can always lead to problems
> 
> maybe we should allow different themes for this https://github.com/gofiber/fiber/blob/master/app.go#L1140-L1149
> 
> same with this https://github.com/gofiber/fiber/blob/master/app.go#L1348-L1358
> 
> @hi019 @efectn what do you think ?

Allowing different themes looks like the best solution.

**Comment by kuchaguangjie** [comment]
I think make the text white (or similar) is safe for most terminals.
