### ISSUE TITLE
🤗 Can I use value from c.Locals in a go-routine after handler returns?

### ISSUE THREAD

**Issue by bofeng** [gofiber/fiber#1895]
From the documentation:

> Because fiber is optimized for high-performance, values returned from fiber.Ctx are not immutable by default and will be re-used across requests. As a rule of thumb, you must only use context values within the handler, and you must not keep any references

I understand that if I have a value from like `c.FormValue` or `c.Query`, I can't use that value directly (unless make a copy) into another go routine after the handler ends, but I am not sure how fiber handle values from c.Locals that I saved in a middleware.

For example, if I have a middleware that read some data from database, then save that data to `c.Locals("username", username)`, then in the handler, can I fetch that data and use it in another go routine?

```golang
func middleware(c *fiber.Ctx) error {
    username := readFromDB()
    c.Locals("username", username)
    return c.Next()
}

func handler(c *fiber.Ctx) error {
    name, ok := c.Locals("username").(string)
    go func() {
        // do something with the variable name, like sending email
       sendEmailWithName(name)
        // ...
    }()

    return c.SendStatus(fiber.StatusOK)
}
```

In the above example, I have the variable `name` fetched from `c.Locals`, since the handler returned first, is it safe to use the `name` in the sendEmail go routine? My guess is in this case it is safe, since the `username`'s memory is allocated by user's code (read from database), not managed by fiber, fiber won't reuse or clean it, but want to see if my understanding is correct.

Thank you!

**Comment by ReneWerner87** [comment]
Not sure, but I think fasthttp takes the object for the locals after the end of the request response and puts it back into a synpool so that the next request can use it without generating allocations.

If in doubt I would rather copy the values

**Comment by ivankprod** [comment]
I have the following:
```go
auth, err := service.IsAuthenticated(c.Cookies("session"), c.Get("user-agent"))
```
And below I run a goroutine and sometimes auth was nil, then I make a copy:
```go
go func(s services.UserService, id uint64) {
	_, _ = s.UpdateLastAccessTime(id)
}(service, auth.ID)
```

**Comment by bofeng** [comment]
> I have the following in middleware:
> 
> ```go
> auth, err := service.IsAuthenticated(c.Cookies("session"), c.Get("user-agent"))
> ```
> 
> And below I run a goroutine and sometimes auth was nil, then I make a copy:
> 
> ```go
> go func(s services.UserService, id uint64) {
> 	_, _ = s.UpdateLastAccessTime(id)
> }(service, auth.ID)
> ```
> 
> And it works well :)

Thank you for the example. Can you also share the `service.IsAuthenticated` code? also, are you putting the `auth` object in the `c.Locals`, then fetch it before the goroutine?

**Comment by ivankprod** [comment]
@bofeng Shure, you'll find the server code at:
https://github.com/ivankprod/ivankprod.ru/tree/main/src/server/internal
Code in previous comment is in the auth package :)

**Comment by ivankprod** [comment]
@bofeng In this middleware I put the `auth` into the `c.locals`, and then in the handlers I don't pass it into the goroutines, but if I would like to pass it to some goroutine, I would make a copy for confidence :)

**Comment by bofeng** [comment]
@ivankprod thank you for sharing the code! In your last comment you mentioned that:
> And below I run a goroutine and sometimes auth was nil, then I make a copy:

So in this middleware function, https://github.com/ivankprod/ivankprod.ru/blob/main/src/server/internal/auth/middleware.go#L32 
It seems the `auth` variable is read from database, but I didn't see anywhere in that function you made a copy of the `auth`. You do have the a copy of `auth.ID` by passing it as parameter to the go-routine, but not sure I understand what you mean by "sometimes auth was nil, then I make a copy", am I missing something here? sorry if I misunderstood your code.

**Comment by ivankprod** [comment]
@bofeng I just make a copy of the `auth.ID` instead of entire `auth` struct, because I need only `ID` field. So don't passing entire `auth` object to goroutine, and passing only the needed fields is much better for memory optimization (the `auth` struct is small, but still).
If I didn't the copy, the `s.UpdateLastAccessTime(id)` long-running function couldn't take `auth.ID` sometimes, because after executing this middleware (or all handlers/middlewares in chain, I don't know) the `auth` object will be `nil`.

**Comment by bofeng** [comment]
@ivankprod got it, thank you again for the example, appreciate your explanation!
