### ISSUE TITLE
🔥 Support/Integrate quicktemplate

### ISSUE THREAD

**Issue by s0kil** [gofiber/fiber#190]
Could you provide an example on how to integrate with [quicktemplate](https://github.com/valyala/quicktemplate) ?

**Comment by Fenny** [comment]
Hi @s0kil, quicktemplate needs to be compiled and therefor is hard to integrate with a web framework.
I use this library myself for some web apps, the way I make it work with fiber is straightforward:

```
go get -u github.com/valyala/quicktemplate
go get -u github.com/valyala/quicktemplate/qtc
```

**./templates/hello.qtpl**
```
{% func Hello(name string) %}
	Hello, {%s name %}!
{% endfunc %}
```

**Generate templates**
```
go generate
```

**./server.go**
```go
package main

import (
  "./templates"
  "github.com/gofiber/fiber"
)

func main() {
  app := fiber.New()
  app.Get("/", func(c *fiber.Ctx) {
    c.Set("Content-Type", "text/html")
    c.SendString(templates.Hello("Hello, World!"))
  })
  app.Listen(3000)
}
```

**Comment by s0kil** [comment]
Thank You @Fenny . Do you plan to document this?

**Comment by Fenny** [comment]
@s0kil, I have no plans to document this because it's not a part of our framework.
But since there is an example in this issue, it should be no problem to find for other users.

I'm closing this issue, feel free to re-open if you have questions/suggestions!

**Comment by frederikhors** [comment]
@s0kil are you still using Fiber and quicktemplate? Can I ask you how?

**Comment by ReneWerner87** [comment]
@s0kil https://github.com/gofiber/fiber/issues/190#issuecomment-591759866 here is the instruction from fenny

**Comment by s0kil** [comment]
@frederikhors Will try to find the project I got it working in.
