### ISSUE TITLE
🤗 How can I access context from Authorizer function in BasicAuth middleware?

### ISSUE THREAD

**Issue by alextr98** [gofiber/fiber#1901]
**Question description**
I am using basicAuth, need to access context from Login function
**Code snippet** _Optional_
func Login(user, password string bool {
 //  how to access context here?
}

**Comment by ReneWerner87** [comment]
Why do you want to access the context from this function?
https://github.com/gofiber/fiber/blob/master/middleware/basicauth/basicauth.go

It is not possible and also not intended to make this possible.

**Comment by alextr98** [comment]
I need extra parameter for Login - user name and password is not enough for authentication. 
I wish to have signature like this: func Login(user,password,domain string) bool {
}

> Why do you want to access the context from this function? https://github.com/gofiber/fiber/blob/master/middleware/basicauth/basicauth.go
> 
> It is not possible and also not intended to make this possible.

**Comment by ReneWerner87** [comment]
is it solved on your side ?
otherwise just copy this short middleware code 
https://github.com/gofiber/fiber/blob/master/middleware/basicauth/basicauth.go
and change it to your need.

**Comment by alextr98** [comment]
> is it solved on your side ?
> otherwise just copy this short middleware code
> https://github.com/gofiber/fiber/blob/master/middleware/basicauth/basicauth.go
> and change it to your need.

I resolved it this way - made user name Windows-style - "DOMAIN\USER", then in authenticator split it into domain and user. 
Not 100% good, but works for me ok.
I appreciate your suggestion, I will consider it.
Thanks a lot!
Alex
