### ISSUE TITLE
 🚀 Request: Route Constraints 

### ISSUE THREAD

**Issue by CerealKiller97** [gofiber/fiber#1903]
Route constraints execute when a match has occurred to the incoming URL and the URL path is tokenized into route values. I found this very useful when defining routes. ASP NET Core was inspiration for this feature.

# Example

```go
  app.Get("/users/{id:int}", func (ctx *fiber.Ctx) {
      // will come here if id is int
     // otherwise return 404
  })
```

Proposed constraints:

| Constraint  | Example           | Example matches              |
| ----------- | --------------  | ------------------------- |
| int                          |  {id:int}             | 123456789, -123456789 |
| bool                      |  {active:bool}   | true,false                            |
| datetime              | {dob:datetime} | 2016-12-31, 2016-12-31 7:32pm |
| guid                      | {id:guid}                        | CD2C1638-1638-72D5-1638-DEADBEEF1638|
| float                      | {weight:float}               | 1.234, -1,001.01e8 |
| minlength(value) | {username:minlength(4)} | Test (must be at least 4 characters) |
| maxlength(value) | {filename:maxlength(8)} | MyFile (must be no more than 8 characters |
| length(length) | {filename:length(12)} | somefile.txt (exactly 12 characters) |
| min(value) | {age:min(18)} | 19 (Integer value must be at least 18) |
| max(value) | {age:max(120)} | 91 (Integer value must be no more than 120) |
| range(min,max) | {age:range(18,120)} | 91 (Integer value must be at least 18 but no more than 120) |
| alpha | {name:alpha} | Rick (String must consist of one or more alphabetical characters, a-z and case-insensitive) |
| regex(expression) | {ssn:regex(^\\d{{3}}-\\d{{2}}-\\d{{4}}$)} | 123-45-6789 (Must match regular expression) |

More details: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-6.0#route-constraints

**Comment by MohabMohamed** [comment]
hello @CerealKiller97, are you working on this feature?
if not, can you or @efectn assign it to me, I would love to work on it

**Comment by efectn** [comment]
> hello @CerealKiller97, are you working on this feature? if not, can you or @efectn assign it to me, I would love to work on it

Assigned. If @CerealKiller97 isn't working on this, you can start working 🚀🚀

**Comment by balcieren** [comment]
It is looking good. This feature can open from fiber.Config for v2.
Example:
```go
fiber.New(fiber.Config{
  EnableRouteConstraints: true,
})
``` 
What do you think about it ?

**Comment by efectn** [comment]
> It is looking good. This feature can open from fiber.Config for v2. Example:
> 
> ```go
> fiber.New(fiber.Config{
>   EnableRouteConstraints: true,
> })
> ```
> 
> What do you think about it ?

I think something like this can be done too instead of adding extra config var:

```go
app.Get("/users/:id:int", func (ctx *fiber.Ctx) {
      // will come here if id is int
     // otherwise return 404
  })
```

**Comment by balcieren** [comment]
> I think something like this can be done too instead of adding extra config var:

I think it is not understandable.

**Comment by ReneWerner87** [comment]
My thought was to do it also without config switches and really use the same syntax as in the table, as alternative

Important is the speed, there should be hardly any time added when analyzing the route (so string based detection, except for the part with regexes)

**Comment by MohabMohamed** [comment]
> Hello @MohabMohamed you can work on this. Sorry for waiting for my reply.

Thank you @CerealKiller97 
> I think something like this can be done too instead of adding extra config var:
I think we can do something like this to differentiate between the param name and its type, and without changing unconstrained params:

 ```go
 app.Get("/users/:id<int>", func (ctx *fiber.Ctx) {
       // will come here if id is int
      // otherwise return 404
   })

 app.Get("/posts/:id", func (ctx *fiber.Ctx) {
       // will come here if id is int
      // otherwise return 404
   })
 ```

what do you think?

**Comment by ReneWerner87** [comment]
would also be possible

**Comment by ReneWerner87** [comment]
but it would be good if we use patterns that are already used in other frameworks/languages

maybe someone can do some research 

the goal is to provide people with familiar structures that they have already been exposed to in order to promote acceptance and knowledge sharing

**Comment by efectn** [comment]
> > Hello @MohabMohamed you can work on this. Sorry for waiting for my reply.
> 
> Thank you @CerealKiller97
> 
> > I think something like this can be done too instead of adding extra config var:
> > I think we can do something like this to differentiate between the param name and its type, and without changing unconstrained params:
> 
> ```go
> app.Get("/users/:id<int>", func (ctx *fiber.Ctx) {
>       // will come here if id is int
>      // otherwise return 404
>   })
> 
> app.Get("/posts/:id", func (ctx *fiber.Ctx) {
> 
>   })
> ```
> 
> what do you think?

I think this is the best way because of fiber router doesn't have adding parameters by {}

**Comment by ReneWerner87** [comment]
> I think this is the best way because of fiber router doesn't have adding parameters by {}

well, that would not be too complex to provide this possibility as an alternative syntax

because this "{" is a fixed character you can use it as a delimiter and mark it in the segments of the routes

which has to happen anyway for the contrains

**Comment by efectn** [comment]
> > I think this is the best way because of fiber router doesn't have adding parameters by {}
> 
> well, that would not be too complex to provide this possibility as an alternative syntax
> 
> because this "{" is a fixed character you can use it as a delimiter and mark it in the segments of the routes
> 
> which has to happen anyway for the contrains

Yes but Fiber is Express inspired framework. Wouldn't adding {}, make Fiber more complex?

**Comment by MohabMohamed** [comment]
I think if we want to add it with { } we could do this in V3 and change the params without constraints to follow this pattern too,
but we can't do this with the already in use version,and I think the constrained parameters should be derived from the regular params

and the only constrained params shape I know is flask it like this:

`/users/<int:id>`

**Comment by ReneWerner87** [comment]
maybe but since express does not offer this feature we have to choose a structure

would ask for research
a small list of frameworks/languages that offer this feature and their structure, i think this can only be beneficial and we might find some more additional constrains

**Comment by ReneWerner87** [comment]
> I think if we want to add it with { } we could do this in V3 and change the params without constraints to follow this pattern too,
but we can't do this with the already in use version,and I think the constrained parameters should be derived from the regular params

think we can do this in version 2 as well since we still support the old notation we don't change anything just add functionality

**Comment by ReneWerner87** [comment]
https://laravel.com/docs/9.x/routing#parameters-regular-expression-constraints
![image](https://user-images.githubusercontent.com/7063188/167611169-7db4e28f-ebd8-461f-9dc5-8e2ef6b1b7d2.png)

https://www.c-sharpcorner.com/blogs/asp-net-core-route-constraints

![image](https://user-images.githubusercontent.com/7063188/167611107-bd437ce4-e5b7-4c6c-b579-072ece5c1b7a.png)

... maybe some more research

**Comment by ReneWerner87** [comment]
we could also leave this declaration completely out of the url and provide a method in the context which receives and validates an object with the constrains for a possible validation

**Comment by efectn** [comment]
> we could also leave this declaration completely out of the url and provide a method in the context which receives an object with the constrains and validates it
> 
> ```go
> // instead of "/users/:id<int>"
> app.Get("/users/:id", func (ctx *fiber.Ctx) {
>       err := ctx.CheckRouteParams(fiber.Map{
>           id: "int",
>       })
>   })
> ```
> 
> ```go
> // instead of "/users/:id<int>"
> app.Get("/users/:id", func (ctx *fiber.Ctx) {
>     err := ctx.RouteConstrains().whereNumber("id")(....more...checks....).check();
> })
> ```

We can also do it by using latestRoute var of App struct -similar to usage of Name()-

```go
app.Get("/users/:id", func (ctx *fiber.Ctx) {
    ...
}).WhereNumber("id")
```

However, `id<int>` way sounds better.

**Comment by ReneWerner87** [comment]
The route syntax is okay for me.

**Comment by ReneWerner87** [comment]
Just know that later there will be questions or feature requests if the error messages we generate due to a mismatch are customizable.

So we should create formatted strings for this, which are customizable from outside (please not via config -> already quite a lot of settings)

**Comment by ReneWerner87** [comment]
Or ask if we can customize the structure (json, xml, html) and the status code

If a mismatch is detected, we should pass the error message which is composed of the type and the parameter name as a string into a generator function, which then generates the response.

so that we can make it overloadable and give the user all possibilities

**Comment by MohabMohamed** [comment]
I think we should just return 404 as not matching the type of the param should be the same behavior as not matching any route.
 and if the user wants to create a custom response when matching, he could use `:id` notation after the specific type one. so fiber while skipping the constrained routes and then match the generic one and the user can do what ever he wants in this route.

or do you have another idea?

**Comment by ReneWerner87** [comment]
yes would go, but would not be quite optimal

users will think that there is already a detection of which parameters do not match and expect this information to be returned to the consumer of the api with the exact instructions about the error

don't think users will be happy if a route constrains feature exists and because they want to customize the response in case it doesn't match, they have to rebuild the entire detection feature and generate their own response

we should provide in the case the possibility to customize the response

**Comment by MohabMohamed** [comment]
if a mismatch happened we can include this data in the `ctx` and we can implement a standard middleware to return these errors and run it after the route. so the user can use it if he wants or implement his own. I think that would be a clean solution.

**Comment by daison12006013** [comment]
Does adding too much option makes fiber more complex in terms of developer's perspective? or compilation time? Silly question, why can't we just use regex?

In gorilla/mux we do it this way `/users/{id:[0-9]+}` it means we want to disregard `/users/whatever` in the routing and only accept int/numeric value.

This is standard in laravel/expressjs too, this is even notable part of expressjs where there are insane regex registration that we can apply, such as:

```
// from: https://expressjs.com/en/guide/routing.html

/user/:userId(\d+)
```

If performance is really the problem then maybe adding that fiber config should disregard regex checking

**Comment by MohabMohamed** [comment]
@efectn sorry I was busy  the last period but working on it currently

**Comment by efectn** [comment]
Hi @MohabMohamed. if you didn't start working for this feature, i can look at the feature if you're OK.

**Comment by MohabMohamed** [comment]
Hello @efectn. I already did the segmentation and determined which constraint type parts. but I'm a little lost in the code base so I would love some support, so do you mind if I can ask you on discord?

and really sorry for being late

**Comment by efectn** [comment]
> Hello @efectn. I already did the segmentation and determined which constraint type parts. but I'm a little lost in the code base so I would love some support, so do you mind if I can ask you on discord?
> 
> and really sorry for being late

My discord is EfeCTN#8109, you can send a message.
