### ISSUE TITLE
🚀 v3 Request: Refactor Client

### ISSUE THREAD

**Issue by efectn** [gofiber/fiber#1906]
I think current client Implementation is very complex and limited. I think we should do these tasks to solve it:
- Move client.go to `client/`. Project structure will be more tidy by splitting the client.
- Re-create client by inspiring by [go-resty/resty](https://github.com/go-resty/resty)

**Comment by balcieren** [comment]
What do you think about node.js axios ? It's looking pretty for client.

**Comment by efectn** [comment]
> What do you think about node.js axios ? It's looking pretty for client.

I don't have any experience with Node.js but it looks like nice. [Guzzle](https://docs.guzzlephp.org/en/stable/) is also good and clean client.

**Comment by YuilTripathee** [comment]
Axios is a good one!

**Comment by wangjq4214** [comment]
I think `axios` has good UX. And maybe I can work for this feature, which branch should I start my work?

**Comment by efectn** [comment]
> I think `axios` has good UX. And maybe I can work for this feature, which branch should I start my work?

You can fork Fiber and work on `v3-beta` branch. I assign you to this issue.
