### ISSUE TITLE
🤗 Case sensitivity for parameters in GetRouteURL

### ISSUE THREAD

**Issue by martinwang2002** [gofiber/fiber#1907]
**Question description**

When using capitalized letters in `fiber.Map{}` with `GetRouteURL`, the case sensitivity of the keys is ignored.

**Code snippet** 

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
        app := fiber.New()

	// app := fiber.New(fiber.Config{
	// 	CaseSensitive: true,
	// })

	app.Get("/", func(c *fiber.Ctx) error {

		idUrl, err := c.GetRouteURL("id", fiber.Map{
			"testid": "ABC",
			"testId": "DEF",
		})

		if err != nil {
			panic(err)
		}

		return c.SendString(idUrl)
	})

	app.Get("/:testid/:testId/other_paths", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!\ntestid: " + c.Params("testid") + "\ntestId: " + c.Params("testId"))
	}).Name("id")

	app.Listen(":3001")
}

```
For example, GET `/`, you will receive `/ABC/ABC/other_paths`. The case sensitivity for GetRouteURL is ignored

On the other hand, c.Params can tell the difference between `testid` and `testId`.

I think that `Params` and `GetRouteURL` should behave the same behavior on case sensitivity.

---

Meanwhile, enabling `CaseSensitive` in the config will receive `/ABC/DEF/other_paths`

**Comment by ReneWerner87** [comment]
code is developed by sujit-baniya -> https://github.com/gofiber/fiber/pull/1831
@sujit-baniya can you check this

**Comment by martinwang2002** [comment]
I agree with you.

Could you also please check this part?
```
app.Get("/:testid/:testId/other_paths", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!\ntestid: " + c.Params("testid") + "\ntestId: " + c.Params("testId"))
}).Name("id")
```
with url: http://127.0.0.1:3001/first/second/other_paths

In this part of code, you will find that `testid` and `testId` are different.

---

That's why I have this confustion. We can get parameters with case sensitivity, but we cannot set proper keys via GetRouteURL with `CaseSensitive = false`. Is this expected?

**Comment by ReneWerner87** [comment]
But please still take a look at the performance after these changes

i expect only a slight increase if the value could not be found by the first check


https://github.com/gofiber/fiber/blob/aa229287cfeeb2002534cb6145b50f7798f76b3e/utils/strings.go#L65
or maybe a check with equalFolds, as this is even faster than converting to lowercase 

ToLower -> 50ns
EqualFold -> 32ns
