### ISSUE TITLE
🐛  Early in the middleware chain `ctx.Route().Path` is empty

### ISSUE THREAD

**Issue by ryan-yalo** [gofiber/fiber#1910]
**Fiber version**

`v2.33.0`

**Issue description**

When trying to author a middleware that needs access to the routed path, `ctx.Route().Path` is empty until `ctx.Next()` has completed. I first noticed this bug when I realized the path label for all prometheus metrics generated by [fiberprometheus](https://github.com/ansrivas/fiberprometheus) was `/`, regardless of the route that requests were coming in on. In the case of prometheus metrics, if we were to use `ctx.Path()` instead (being careful to deep copy the string because `fasthttp` will reuse the underlying byte array), the metrics endpoint would contain a separate listing for every call to `GET /id/123`, `GET /id/234`, etc. and that's definitely not what we want. The correct behavior is to show metrics with the path variables pre-interpolated but unfortunately I'm struggling to figure out how to do so reliably. At first I thought this was a bug in [fiberprometheus](https://github.com/ansrivas/fiberprometheus) and started digging in to try to fix the issue there. Then, I realized it's most likely because the path gets build up incrementally in [`app.next`](https://github.com/gofiber/fiber/blob/master/router.go#L132) and isn't complete the first time middleware gets called. Is there any way to access the complete route path early on in the middleware chain?

**Code snippet**

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New(fiber.Config{DisableStartupMessage: true})
	app.Use(
		func(ctx *fiber.Ctx) error {
			fmt.Println(ctx.Route().Path)
			err := ctx.Next()
			fmt.Println(ctx.Route().Path)
			return err
		},
	)
	app.Get("/path/:path", func(ctx *fiber.Ctx) error {
		switch ctx.Params("path") {
		case "ok":
			return nil
		default:
			return fiber.ErrInternalServerError
		}
	})
	err := app.Listen(":3000")
	if err != nil {
		panic(err)
	}
}
```

In the code snippet above, I'd expect to see `/path/:path` logged twice for each request. Instead I see the output below:

```
/
/path/:path
```

**Comment by ReneWerner87** [comment]
hi thanks for the report

ctx.Route().Path gives you the current path for the currently active route

this is in case of app.Use() the empty path or route path

after next is called, the next handler middleware is made with the second declared route and set as current route

as described here
https://docs.gofiber.io/api/ctx#route

please tell me again exactly what you need, so i can help you best possible

maybe we add a new hook for this which will be triggered when a route match happens
https://github.com/gofiber/fiber/blob/0fdd7df0f92c48508cc8193b1cfae3bbe5dbad08/router.go#L123-L128

**Comment by ryan-yalo** [comment]
What I was specifically hoping to get working for the project I'm working on currently is to fix the bug in [fiberprometheus](https://github.com/ansrivas/fiberprometheus) where the path in reported metrics is always `/` but after reading the documentation at the link you shared, I don't believe that's going to be possible unfortunately. The behavior on the fiber side is correct. The issue is just that [`fiberprometheus` collects the path too early](https://github.com/ansrivas/fiberprometheus/blob/master/middleware.go#L158). I will submit an issue on their side and try to PR up the fix from my fork. Thanks very much for your help!
