### ISSUE TITLE
Go fiber client example 

### ISSUE THREAD

**Issue by sheldondz** [gofiber/fiber#1916]
**Fiber Client example**

Is there an example on how to use the fiber ```*Client``` ``` *Agent``` to make an external https api call?

**Comment by ReneWerner87** [comment]
yes in the documentation 
https://docs.gofiber.io/api/client

**Comment by sheldondz** [comment]
got this working for was confused between ``` *Client ``` and ``` *Agent ``` actually ``` *Agent ``` does all the work.
i get this message "[Warning] client is still in beta, API might change in the future!" is this safe to use in production?

**Comment by ReaperMaga** [comment]
I think its not recommended to use it in production, since the API might change. You can use it in small projects.

I also actually wanted to know is it possible to disable this warning?

**Comment by ReneWerner87** [comment]
unfortunately the client was not developed further 

you can also check how much work is needed to stabilize it or add an option to turn off the warning

but i prefer stabilization with more unittests and stresstests

**Comment by sheldondz** [comment]
Thanks for the info, will stick to using the default  go ```net/http``` library for calling external api's for now.
