### ISSUE TITLE
🚀 Optional mTLS

### ISSUE THREAD

**Issue by 01epa** [gofiber/fiber#1918]
**Is your feature request related to a problem?**
It is not possible to configure fiber app with optional mTLS. Sometime clients may have no its own certificates, sometimes they may have certificates. Fiber allow to have either TLS or mTLS. I would like to have mTLS as optional. Golnag has a special constants for that - [common.go](https://github.com/golang/go/blob/master/src/crypto/tls/common.go#L293)
But fiber set mTLS as mandatory for all clients - see [app.go](https://github.com/gofiber/fiber/blob/master/app.go#L871)

**Describe the solution you'd like**
I would like to pass a `ClientAuth`  to a `ListenMutualTLS` method

**Describe alternatives you've considered**

**Additional context**

**Comment by efectn** [comment]
I think you can use Listener instead of adding new param or method @01epa

**Comment by efectn** [comment]
> Yes, that's what I did. But that's a huge copy-past
> 
> ```
> 		cert, err := tls.LoadX509KeyPair(certFile, keyFile)
> 		if err != nil {
> 			logger.Panic("Cannot load TLS key pair from certFile=%s and keyFile=%s: %+v", certFile, keyFile, err)
> 		}
> 
> 		clientCACert, err := ioutil.ReadFile(filepath.Clean(clientCertFile))
> 		if err != nil {
> 			logger.Panic("Cannot read ca cert file=%s, error=%+v", clientCertFile, err)
> 		}
> 		clientCertPool := x509.NewCertPool()
> 		clientCertPool.AppendCertsFromPEM(clientCACert)
> 
> 		tlsConfig := &tls.Config{
> 			MinVersion: tls.VersionTLS12,
> 			ClientAuth: tls.VerifyClientCertIfGiven,
> 			ClientCAs:  clientCertPool,
> 			Certificates: []tls.Certificate{
> 				cert,
> 			},
> 		}
> 		ln, err := tls.Listen(fiberConfig.Network, listenAddress, tlsConfig)
> 		if err != nil {
> 			logger.Panic("Cannot create listener on address=%s, error=%+v", listenAddress, err)
> 		}
> 		if err := app.Listener(ln); err != nil {
> 			logger.Panic("Cannot start tls listener on address=%s, error=%+v", listenAddress, err)
> 		}
> ```
> 
> instead of
> 
> ```
> 		if err := app.ListenMutualTLS(listenAddress, certFile , keyFile , clientCertFile ); err != nil {
> 			logger.Panic("Cannot start listener on address=%s, error=%+v", listenAddress, err)
> 		}
> ```

It may be more shortened by https://github.com/gofiber/fiber/issues/1826 on v3

**Comment by ReneWerner87** [comment]
sounds good
big improvement for v3
