### ISSUE TITLE
🐛 Unexpected GetRouteURL with param "*"

### ISSUE THREAD

**Issue by martinwang2002** [gofiber/fiber#1921]
**Fiber version**
v2.34.0

**Issue description**
Unexpected other parameters in the result when using `*` in one of the parameters.

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
 	app := fiber.New()

	// app := fiber.New(fiber.Config{
	// 	CaseSensitive: true,
	// })

	app.Get("/", func(c *fiber.Ctx) error {

		idUrl, err := c.GetRouteURL("id", fiber.Map{
			"testid": "ABC",
			"*": "def/hij/klm",
		})

		if err != nil {
			panic(err)
		}

		return c.SendString(idUrl)
	})

	app.Get("/:testid/*", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!\ntestid: " + c.Params("testid") + "\n*:" + c.Params("*"))
	}).Name("id")

	app.Listen(":3000")
}
```

In this example, when getting `/`, the expected result should be `/ABC/def/hij/klm`, while fiber returns `/ABC/ABCdef/hij/klm` or `/ABC/def/hij/klmABC`.  Fiber may prepend or append **all** other parameters when using `"*"` as one of the parameters in GetRouteURL.

**Comment by ReneWerner87** [comment]
@sujit-baniya can you check this

**Comment by sujit-baniya** [comment]
@ReneWerner87 Checking
