### ISSUE TITLE
🤗 Is 3% cpu usage normal for a gofiber tls-app?

### ISSUE THREAD

**Issue by hakoptak** [gofiber/fiber#1926]
Hi all,

I am running my gofiber app (ListenTLS) with no handlers and it still consumes about 3% cpu. I ran the app on my Macbook and on an Alpine Linux server and get similar results when using `top`. Is this normal behaviour? And where is the 3% cpu spent?

For comparison: I am also running a c++ https-server and it uses 0.01 % cpu at most.

Thanks for thinking along!

**Comment by hakoptak** [comment]
@ReneWerner87 Thanks for the link.

Strangely enough I have exactly the opposite situation: relatively low memory footprint (around 6 mb), high cpu usage (3%)

**Comment by ReneWerner87** [comment]
i think its normal
fasthttp is doing the magic behind this request and response flow

maybe you can test the behaviour with plain fasthttp code ?
