### ISSUE TITLE
🚀 v3 Request: tls.ClientHelloInfo in handlers

### ISSUE THREAD

**Issue by abusessender** [gofiber/fiber#1927]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
I need tls.ClientHelloInfo in route handlers, can it be made in fiber v3?

**Comment by efectn** [comment]
Can you give an example about this feature? @abusessender

**Comment by abusessender** [comment]
> Can you give an example about this feature? @abusessender

It does not released in other libraries, it will be good, if you release it first :D

**Comment by thomasdseao** [comment]
Hi @efectn , Can I work on this ?

**Comment by efectn** [comment]
> Hi @efectn , Can I work on this ?

Of course

**Comment by thomasdseao** [comment]
Cool!
I will be back from my holiday on the 15 august. So if it can wait until the 15, that's perfect for me.
If not don't hesitate to assign it to someone else 🙂

**Comment by thomasdseao** [comment]
Hi @efectn 

I made the small changes to get ClientHelloInfo in handlers in this PR : https://github.com/gofiber/fiber/pull/2011
Let me know if you want me to change some things or maybe where the code is located. (This is my first PR on fiber)
