### ISSUE TITLE
🔥 Query params

### ISSUE THREAD

**Issue by Ivan-Feofanov** [gofiber/fiber#193]
I can't find any normal way to get a query string params without using raw fasthttp queryString
Something like that can be very useful:
```golang
app.Get("/", func(c *fiber.Ctx) {
  queryValue := c.Query().Get("param_key")
})
```
Thanx!

**Comment by koddr** [comment]
@Ivan-Feofanov hi!

Do you use `Query()` method? https://fiber.wiki/context#query

**Comment by Fenny** [comment]
@Ivan-Feofanov, did this solve your problem? Feel free to re-open this issue :+1:
