### ISSUE TITLE
🤗 get prams from header 

### ISSUE THREAD

**Issue by RabeeaAli** [gofiber/fiber#1932]
I stored the id of the user in header and tried to get it to throw GET but I got nothing even the user_id is existed in the header ( checked it from postman)
my code:
```
fmt.Println("Content-Type is: " + c.Get("Content-Type"))
fmt.Println("id is: " + c.Get("user_id"))
return nil
```

the output is :
```
Content-Type is: 
id is: 
01:27:36 | 200 |     1ms |       127.0.0.1 | GET     | /api/test   
```

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/173503917-d01c33b4-0054-45f6-bb8c-d56acf73fc4a.png)
```go
package main

import (
    "fmt"
    "log"

    "github.com/gofiber/fiber/v2"
)

func main() {
    app := fiber.New()

    app.Get("/", func(c *fiber.Ctx) error {
        fmt.Println("Content-Type is: " + c.Get("Content-Type"))
        fmt.Println("id is: " + c.Get("user_id"))

        return c.SendString("index")
    })
    log.Fatal(app.Listen(":3000"))
}

```

curl --location --request GET 'localhost:3000/' \
--header 'User_id: testABC' \
--header 'Content-Type: application/json'


Hi, its working for me

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/ctx#append)](https://docs.gofiber.io/api/ctx#append

"append" adds the value to the response headers?

as you also see in postman

ctx.Get works only with the request headers, as noted in the documentation
https://docs.gofiber.io/api/ctx#get

you should use ctx.Locals if you want to exchange data between middlewares
https://docs.gofiber.io/api/ctx#locals

**Comment by RabeeaAli** [comment]
@ReneWerner87 So, How can I get the use_id by using `ctx.Locals`?

in middleware now :

```
func IsAuthenticated(c *fiber.Ctx) error {
	......
	c.Append("user_id", id)
	return c.Next()
}
```

**Comment by RabeeaAli** [comment]
@ReneWerner87 

I got `Invalid operation: "id is: " + c.Locals("user_id") (mismatched types string and interface{})`

**Comment by RabeeaAli** [comment]
@ReneWerner87  Thanks

**Comment by RabeeaAli** [comment]
@ReneWerner87  Hello

I have a question: How can I get `user_id` from anywhere I need it in the project?

I'm using Gorm with fiber and in the Post model, I'm using `BeforeCreate` like this:

```go
// in Post.go model

func (post *Post) BeforeCreate(*gorm.DB) error {
	post.UserId = utils.GetUserID()
	return nil
}

```

In helpers.go I have `GetUserID()` function

```
func GetUserID(c *fiber.Ctx) int {
	idString := c.Params("user_id")
	idInt, _ := strconv.Atoi(idString)
	return idInt
}
```
