### ISSUE TITLE
🤗 Using *fiber.Ctx in another function

### ISSUE THREAD

**Issue by Itshardtopickanusername** [gofiber/fiber#1934]
**Question description**
Is it okay to pass around *fiber.Ctx to other functions that are called from handlers?
without keeping any references. does this affect anything? I'm guessing not, but just want to confirm, since the docs state:

> As a rule of thumb, you must only use context values within the handler, and you must not keep any references

**Code snippet** _Optional_

```go
package main

import ( 
    "github.com/gofiber/fiber/v2"
    "fmt"
)

func main() {
  app := fiber.New()
  app.Get("/", MyHandler)
  fmt.Println(app.Listen("0.0.0.0:6060"))
}

func GetCtxVal(c *fiber.Ctx) string {
    ctx := c.UserContext()
    m, ok := ctx.Value("myctxkey").(string)
    if !ok {
        return ""
    }
    return m
}

func MyHandler(c *fiber.Ctx) error {
    myVal := GetCtxVal(c)

    return c.JSON(fiber.Map{"message": "myVal"})
}

```

**Comment by ReneWerner87** [comment]
That's okay.
