### ISSUE TITLE
🚀 Monitor middleware doesn't work in offline environments, requires CDN-hosted resources

### ISSUE THREAD

**Issue by hi019** [gofiber/fiber#1936]
**Is your feature request related to a problem?**
The monitor middleware can't be used on offline hosts, because it relies on external CDN's: https://github.com/gofiber/fiber/blob/master/middleware/monitor/index.go#L35-L36

**Describe the solution you'd like**
Monitor resources should be served by Fiber

**Comment by gaby** [comment]
👍🏻 Thanks for reporting this. We ran into this small issue today while deploying a Fiber powered service in an offline environment.
