### ISSUE TITLE
🤗 Is it possible to read streaming response body using fiber?

### ISSUE THREAD

**Issue by MHM98** [gofiber/fiber#1944]
**Question description**
Is it possible to read streaming response body using fiber?
**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  
app.Post("/", func(c *fiber.Ctx) error {
	        // real-time reading streamed data in c.body() and send it to fiber websocket
		return c.SendStatus(200)

}
```
Hello,

I have a streaming server(ffmpeg) that send data through HTTP.
I sent the stream to my fiber backend but I only have access to c.body  when the stream server(ffmpeg) is terminated.
Is there any way to capture streamed data in real-time in fiber?
Any help will be much appreciated.

**Comment by gaby** [comment]
@MHM98 Have you tried using `StreamRequestBody` ?

Example here: https://github.com/gofiber/recipes/blob/master/stream-request-body/main.go

**Comment by gaby** [comment]
@ReneWerner87 I think this can be closed.

**Comment by loganvo** [comment]
The question is Streaming the response body, not the request body.
