### ISSUE TITLE
🤗 How to delete file after ctx.Sendfile  success ?

### ISSUE THREAD

**Issue by jsdkarn** [gofiber/fiber#1946]
I try to remove the file after sending the file but I can't.

this is an error return.

`remove./tmp/\Temp-1111-2022-05.xlsx: The process cannot access the file because it is being used by another process.`

```go
time.AfterFunc(time.Second*10, func() {
		err = os.Remove(fmt.Sprintf("./tmp/%s.xlsx", tmpFilename))
		if err != nil {
			log.Println(err)
		}
	})

return c.Status(fiber.StatusOK).SendFile(fmt.Sprintf("./tmp/%s.xlsx", tmpFilename), false)
```

**Comment by efectn** [comment]
Can you send full code?

**Comment by bigdududu** [comment]
are you fixed this issue, I met the same problem recently. Any way to work it out?

**Comment by bigdududu** [comment]
@jsdkarn 
face the same issue, did you work it out?
