### ISSUE TITLE
🚀  Static File Deploy Middleware for SPA , put files to public(wwwroot) directory

### ISSUE THREAD

**Issue by taheri24** [gofiber/fiber#1958]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**

Easily and instant sync the public(www-root) folder with FE output
- Put File via Blob ContentType
- It must be secure (with SECRET_KEY)
- Compress Extract Feature
- Patching Mechanism  

**Describe alternatives you've considered**
- Inspired by FTP
**Additional context**

Also, We need a CLI tool for using Frontend Developers

**Comment by taheri24** [comment]
Is there someone here?

**Comment by efectn** [comment]
@taheri24
