### ISSUE TITLE
🐛 Not Found Handler wih subgroup middleware

### ISSUE THREAD

**Issue by baldanca** [gofiber/fiber#1959]
**Fiber version**
v2.33.0

**Issue description**
We are having one situation that the Fiber isn't detecting the not found routes.
If a middleware is applied to a subgroup like a authentication middleware the not found handler is not called.

**Code snippet**

```go
package main

import (
	"errors"
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	apiGroup := app.Group("/api")
	apiGroup.Use(AuthMiddleware)

	apiGroup.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello World!")
	})

	log.Fatal(app.Listen(":3000"))
}

func AuthMiddleware(c *fiber.Ctx) error {
	// ...
	// Some logic to check if the user is authenticated
	c.Status(fiber.StatusUnauthorized)
	return errors.New("Not authenticated")
}
```

If we call a route not defined like `/api/foo` will return 401 - Not authenticated instead of 404 - Not found

**Comment by balcieren** [comment]
@ReneWerner87 it looks like bug

**Comment by ReneWerner87** [comment]
@baldanca 
but you have added your auth middleware with ".Use" for the complete group "/api 

clear that this then catches the route which is under api

**Comment by ReneWerner87** [comment]
> @ReneWerner87 it looks like bug

for me its expected behaviour

**Comment by baldanca** [comment]
> > @ReneWerner87 it looks like bug
> 
> for me its expected behavior

But why run a middleware to a not found route? Not makes sense to me.
The expected for me it's verify if the route exist and after run the stack.

**Comment by ReneWerner87** [comment]
Let me put it another way, the middleware error has more prio than the error of the not found mechanism.

**Comment by baldanca** [comment]
In this way if I use a middleware auth in a group and call a not found route will return 401. But I think that need to return 404 but not makes sense verify the authorization.

**Comment by ReneWerner87** [comment]
Authentication without a real route doesn't make sense either, why don't you put it directly as middleware to the routes that exist?

**Comment by baldanca** [comment]
Because I have several routes in this group and all needs authentication. Don't make sense to me apply this middleware in one by one. It's more simple if I apply the middleware in the group.

**Comment by ReneWerner87** [comment]
Due to the limitation that we process the routes just like express in a row and we handle the middleware for "Use" or "Group" and the rest of the request methods middlewares identically and additionally the logic of the error handling works like this, the usecase with the defined handler on the group so that the not found error comes is unfortunately not possible.

Can only try to build you later a solution that I have in mind with the hooks, which then when adding the routes your middleware automatically added if it has the prefix of the group

**Comment by wangjq4214** [comment]
Again, I think a 404 error should be returned instead of a 401 error, and a more convenient API is needed.

Perhaps we could provide an API as follows, `Apply` will add a middleware for each endpoint that actually exists:

```go
package main

import (
	"errors"
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	apiGroup := app.Group("/api")
	apiGroup.Apply(AuthMiddleware)

	apiGroup.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello World!")
	})

	log.Fatal(app.Listen(":3000"))
}

func AuthMiddleware(c *fiber.Ctx) error {
	// ...
	// Some logic to check if the user is authenticated
	c.Status(fiber.StatusUnauthorized)
	return errors.New("Not authenticated")
}
```

Maybe I can work for it after I finish the client refactor.

**Comment by charlie-smma** [comment]
> ```go
> Apply
> ```

Hope can use this solution soon.

**Comment by efectn** [comment]
You can use Error handler to catch 404 errors i think
