### ISSUE TITLE
🚀 Ability to set request attributes on context

### ISSUE THREAD

**Issue by SharkFourSix** [gofiber/fiber#1963]
**Is your feature request related to a problem?**
Sort of. It would be nice to be able to set request attributes to the context. i.e

```go
type Foo struct {
    KeyId string `form: "keyId"`
    Bar string `form: "bar"`
    This int
}

app.Use(fooParser);

app.Get("/path", func(c* fiber.Ctx) error {
    var foo* = c.getAttribute("app.foo")
    // ... business logic
    return s.SendString("some string")
})

function fooResolver(c* fiber.Ctx) error {
    var foo = Foo{}
    _ := c.BodyParser(&foo)
    // ... maybe go to database and return some stuff
    foo.This = db.GetThat()
    c.setAttribute("app.foo", &foo) 
    return c.Next()
}
```

**Describe the solution you'd like**
Add method to allow adding objects to requests to the context.

**Describe alternatives you've considered**
Using the session middleware

**Additional context**

**Comment by efectn** [comment]
Doesn't `Locals` do the same thing? 
https://github.com/gofiber/fiber/blob/master/ctx.go#L759

**Comment by SharkFourSix** [comment]
> Doesn't `Locals` do the same thing? https://github.com/gofiber/fiber/blob/master/ctx.go#L759

Ahh. Yes. Thank you very much 😄 . I had actually missed this. https://docs.gofiber.io/api/ctx#locals

I was looking for the language "attribute".
