### ISSUE TITLE
🤗 [Question]: How do you configer the recover middleware not to display panic error messages to the client?

### ISSUE THREAD

**Issue by SharkFourSix** [gofiber/fiber#1965]
### Question Description

When using the recover, it returns the error message back to the client, which is a very very bad idea because it can reveal sensitive information, and in my case it's messing up my data structure.

How do I disable this behavior so that instead it only returns a 500 back to the client?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question
  app.Use(recover.New())

  app.Get("/dangerous", func(c* fiber.Ctx)error{ panic("ouch") })

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by liaohongxing** [comment]
recover returns an error to global error handling

you only need to handle errors global

https://docs.gofiber.io/guide/error-handling#custom-error-handler

**Comment by ReneWerner87** [comment]
@SharkFourSix
