### ISSUE TITLE
🚀 [Feature]: Resumable uploads

### ISSUE THREAD

**Issue by SoftExpert** [gofiber/fiber#1969]
### Feature Description

Hello,

Could (and should) a resumable upload protocol be implemented as a middleware?
I found the following [protocol](https://github.com/tus/tus-resumable-upload-protocol) that has a reference [implementation](https://github.com/tus/tusd).
Is there a need for it ?

Cheers!

### Additional Context (optional)

https://github.com/tus/tus-resumable-upload-protocol
https://github.com/tus/tusd

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by efectn** [comment]
Looks like Tus just supports net/http https://github.com/tus/tusd/blob/master/pkg/handler/handler.go. 
If you port it into the Fasthttp you can send a PR for https://github.com/gofiber/contrib. 

**Note:** You can also try to use it with [adaptor](https://github.com/gofiber/adaptor) but pure implementation is always better and faster. Feel free to contribute :smiley_cat: :smiley_cat: :smiley_cat:
