### ISSUE TITLE
🤗 [Question]: Why does the New function expect the Config more than once?

### ISSUE THREAD

**Issue by aligoren** [gofiber/fiber#1970]
### Question Description

I was looking for the source code of Fiber to understand how it works. I found `New` function and saw it expects Config as a parameter more than once. I don't know why. Is there any reason?

Because even If there are Config params, this function always uses only the first one.

### Code Snippet (optional)

```go
// Function expects params more than once. But only using the first one
func New(config ...Config) *App {


	// I wonder about this part
	if len(config) > 0 {
		app.config = config[0]
	}

	// some codes was here

	return app
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by efectn** [comment]
Because of Go doesn't have optional parameter feature, we're using variadic parameters to make behavior like optional on Fiber codebase. User-defined config is not necessary to start app. If config not given, we pass default variables as config.

**Comment by aligoren** [comment]
Oh thanks ^^
