### ISSUE TITLE
🤗 [Question]: Gofiber Streaming with Proxy Middleware

### ISSUE THREAD

**Issue by dominicfollett** [gofiber/fiber#1971]
### Question Description

I'd like to ask if it is at all possible to support streaming with Gofiber middleware, and additionally read that stream and make changes to it before passing on to the client?

I've included a snippet of what I'm kind of hoping to do, although I acknowledge I may be hopelessly off course.

### Code Snippet (optional)

```go
func StreamingHandler(c *fiber.Ctx) error {
	url := buildURL(viper.GetString("proxy.forward.app"), c.Path())

	if err := proxy.Do(c, url); err != nil {
		return err
	}
        
        rd := bufio.Reader{}
	reader := bufio.NewReader(&rd)
	c.Response().Read(reader)
	
        // make adjustments to the stream contents

        // set the outgoing stream contents ?
	c.Response().SetBodyStream(?)
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by Trim21** [comment]
Did a little digging, it's not possible currently.

https://github.com/valyala/fasthttp/issues/99

`fasthttp.Client` will read the whole body.

So, to stream response, you will need create a new fasthttp Response and pass it to `fasthttp.Client` in in the `proxy` middleware and pipe new reponse's body to fiber.Ctx's response (`newResponse.BodyWriteTo(*fiber.Ctx)`).

But currently, proxy middleware only use the response of fiber.Ctx, so with proxy middleware, you can neigher do stream proxy, not modify it.

You will have to use you own `http.Client` of `fasthttp.Client`.
