### ISSUE TITLE
🤗 [Question]: How to change limiter's Max value dynamically?

### ISSUE THREAD

**Issue by ssharish** [gofiber/fiber#1988]
### Question Description

I have a situation where in I need to change the limiter's Max value dynamically.  This needs to happen during runtime.  Is there a way to accomplish that.  From the code what I understood so far is, once, the App is created pretty much the configs for middleware remain immutable.  This is because `handlers` are stored as a list instead of hash, so they don't get replaced.

### Code Snippet (optional)

```go
ws := fiber.New()

if ws != nil {
      ws.Use(
          limiter.New(limiter.Config{
              Max:          RateLimit,
              Expiration:   LimitWindow,
              LimitReached: func(c *fiber.Ctx) error {
                 return c.SendStatus(fiber.StatusTooManyRequests)
              },
              SkipFailedRequests:     false,
              SkipSuccessfulRequests: false,
              LimiterMiddleware:      limiter.SlidingWindow{},
          }),
       )
}

// after a while RateLimit value (if) changes, then, I need that to be enforced
// repeating the same piece of code doesn't help!
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
its not possible with our core middleware

if you want that you have to create a custom variant of it

**Comment by ssharish** [comment]
Thank you very much for the quick reply
