### ISSUE TITLE
🚀 [Feature]: Change middleware config dynamically

### ISSUE THREAD

**Issue by ssharish** [gofiber/fiber#1989]
### Feature Description

There are situations where one needs to change the middleware's configuration values dynamically.  For e.g. a limiter's Max value can be ballooned dynamically based on other driving factors (metering).  Currently there is no mechanism to do that, which automatically enforces admin to restart the webserver.  Restart of webserver comes with a cost associated during production deployments (traffic rerouting, draining the queue, inflated infrastructure costs etc).  

Requesting for a feature to allow the replacement of values dynamically.

### Additional Context (optional)

Out of ignorance (of complete code base) I'm proposing two ways to accomplish it.

- Multiple call to .Use() with same middleware should replace the config
- Keep the config outside to that it can be modified.  No local copy of config maintained

### Code Snippet (optional)

```go
ws := fiber.New()

if ws != nil {
      ws.Use(
          limiter.New(limiter.Config{
              Max:          10,
              Expiration:   1 * time.Minute,
              LimitReached: func(c *fiber.Ctx) error {
                 return c.SendStatus(fiber.StatusTooManyRequests)
              },
              SkipFailedRequests:     false,
              SkipSuccessfulRequests: false,
              LimiterMiddleware:      limiter.SlidingWindow{},
          }),
       )
}

// after a while execute the following elsewhere in the code 
ws.Use(
    limiter.New(limiter.Config{
	Max:          30,
	Expiration:   1 * time.Minute,
	LimitReached: func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusTooManyRequests)
	},
	SkipFailedRequests:     false,
	SkipSuccessfulRequests: false,
	LimiterMiddleware:      limiter.SlidingWindow{},
    }),
)

// Now the webserver accepts 30 req/min
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
in your description there is not really a configuration change, you want to replace the whole middleware after you initialize the server

would advise against this for performance reasons

please adjust the example how it should look like later in case the config should be changed dynamically or the handler of the route should be changed

**Comment by ssharish** [comment]
Hi Rene,

Thanks for your explanation.  Yes it would be replacement of the entire middleware itself.  I realise there is a performance implication to this, however, this is a rare event and performance penalty offsets the benefits in the production.  Since I don't have the in-depth understanding the middleware code I'm presenting a simpler way to change the values. 

I don't think I'm qualified enough to suggest a correct way here (as I'm still reading the middleware code to understand it better).  One thing that might help is to store app.stack as map and offer an API to replace a particular handler (indirectly the config associated too).

I'm unsure why git is asking me to close with a comment, I would like to keep this as open.  In case if this can be done is someway.

**Comment by Trim21** [comment]
you can just wrap your config with `sync.RWMutex` and add a router (or in the middleware ) to update it.

**Comment by ssharish** [comment]
Hi Trim,

Thanks for your reply, could you please elaborate a little bit on "use another way to update it".  Most methods I have tried didn't work as values are copied by the middleware.

**Comment by Trim21** [comment]
```golang
package main

import (
	"net/http"
	"strconv"
	"sync"

	"github.com/gofiber/fiber/v2"
)

type Config struct {
	m sync.RWMutex

	allowed bool
}

func (c *Config) Middleware(ctx *fiber.Ctx) error {
	c.m.RLock()

	if !c.allowed {
		c.m.RUnlock()
		return ctx.Status(http.StatusForbidden).SendString("request forbidden by middleware")
	}

	c.m.RUnlock()
	return ctx.Next()
}

func (c *Config) Updater(ctx *fiber.Ctx) error {
	v, err := strconv.ParseBool(ctx.Query("allow"))
	if err != nil {
		return err
	}

	c.m.Lock()
	c.allowed = v
	c.m.Unlock()

	return nil
}

func main() {
	var config = &Config{allowed: true}

	app := fiber.New()
	app.Use(config.Middleware)

	app.Get("/config-middleware", config.Updater)

	app.Listen("127.0.0.1:7999")
}
```

**Comment by Trim21** [comment]
use a pointer receiver

**Comment by Trim21** [comment]
And you can also use "sync/atomic" to avoid the `sync.RWMutex`, I'm not sure which one has the better performance.

**Comment by ssharish** [comment]
Hi Trim,

Thanks a ton the code, this makes it easy.

**Comment by Trim21** [comment]
I guess this issue can be closed now?
