### ISSUE TITLE
How to remove an item from the cache?

### ISSUE THREAD

**Issue by smalloff** [gofiber/fiber#1991]
### Question Description

How to remove an item from the cache or update item? 
[From fiber cache middleware](https://github.com/gofiber/fiber/tree/master/middleware/cache)

This function does not allow getting into the cache. If the element is already in the cache, then it doesn't work.

```go
			Next: func(c *fiber.Ctx) bool {
				return c.Query("refresh") == "true"
			},
```

**Comment by smalloff** [comment]
The solution I found. Maybe someone will come in handy.

```go
import (
	"github.com/gofiber/fiber/v2/middleware/cache"
	"github.com/gofiber/storage/memory"
)

var (
	MemStore *memory.Storage
)

func main() {
	app.Use(
		cache.New(cache.Config{
			Storage:    MemStore,
			KeyGenerator: func(c *fiber.Ctx) string {
				return c.Path()
			},
		}),
	)

api := app.Group("/api")
api.Get("/cache/refresh/", Refresh)
}

func Refresh(c *fiber.Ctx) (err error) {
	key := c.Query("url")
	if key != "" {
		if err = MemStore.Delete(key + "_GET"); err == nil {
			if err = MemStore.Delete(key + "_GET_body"); err == nil {
				c.SendString("ok")
				return
			}
		}
	}
	return errors.New("key not found")
}

```

usage - 127.0.0.1:3000/api/cache/refresh/?url=my_url.html

**Comment by ReneWerner87** [comment]
Use the skip middleware https://docs.gofiber.io/api/middleware/skip

**Comment by smalloff** [comment]
> Use the skip middleware https://docs.gofiber.io/api/middleware/skip

Thanks, great!
