### ISSUE TITLE
🤗 [Question]: how to set release mode like gin in fiber?

### ISSUE THREAD

**Issue by wejectchen** [gofiber/fiber#1992]
### Question Description

my question is how to set release mode like gin in fiber?

like be:
```golang
gin.SetMode("release")
```

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](../CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by efectn** [comment]
Fiber doesn't have builtin logger and mode options.
