### ISSUE TITLE
🤗 [Question]: `app.Test` may hang infinitely with handler calling `runtime.Goexit`

### ISSUE THREAD

**Issue by Trim21** [gofiber/fiber#1996]
### Question Description

I'm using `github.com/stretchr/testify/mock` to create a mock, and this library may call `t.FailNow()` if caller try to do a unexpected method call.

But `(*testing.T).FailNow()` will only call `runtime.Goexit` but not `panic`.

Therefore, the handler can't panic if the test fail. and I can only get a timeout error instead of panic error.

and, if `app.Test` is called without timeout, this test will hang **infinitely** .

I want to know is there a way to handle this problem?

### Code Snippet (optional)

```go
package main_test

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gofiber/fiber/v2"
)

func TestFailNow(t *testing.T) {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		t.FailNow() // or runtime.Goexit()
		return nil
	})

	req := httptest.NewRequest(http.MethodGet, "/", http.NoBody)

	res, err := app.Test(req, -1)
	if err != nil {
		t.Error(err)
		t.FailNow()
	}

	if res.StatusCode != 502 {
		t.FailNow()
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by Trim21** [comment]
There is a workaround, add a test-only middleware to handle this:

```golang
			app.Use(func(c *fiber.Ctx) error {
				var returned bool
				defer func() {
					if !returned {
						panic("t.FailNow() called in handler")
					}
				}()

				err := c.Next()
				returned = true
				return err
			})
```

`runtime.Goexit()` will call all `defer`, so in this way fiber can get the control flow.

**Comment by wangjq4214** [comment]
`runtime.Goexit()` will call all `unexecuted defer` functions and **exit the current goroutine**, causing the error channel in Test function to not receive any messages.

And I think it's important to check the parameters at the controller level and make sure that the mock covers these test cases, rather than making the mock function call t.FailNow.

Changing app.Test will introduce unnecessary complexity.

**Comment by Trim21** [comment]
this is more a developer experience question.

Mocks may call `t.FailNow` when it can't find matched called, usually happens when writing tests and mock are not properly set. `t.FailNow` is not a expected behavior.

**Comment by Trim21** [comment]
And after read source of `app.Test`, I think it's not too complex to handle this, just add a defer in the goroutine
```golang
	go func() {
		channel <- app.server.ServeConn(conn)
	}()
```


```golang
	go func() {

				var returned bool
				defer func() {
					if !returned {
						panic("runtime.Goexit() called in handler")
					}
				}()

		r := app.server.ServeConn(conn)
				returned = true
channel <- r
	}()
```

**Comment by wangjq4214** [comment]
> this is more a developer experience question.
> 
> Mocks may call `t.FailNow` when it can't find matched called, usually happens when writing tests and mock are not properly set. `t.FailNow` is not a expected behavior.
> 
> if a test disable `app.Test` timeout, this may cause a test hang very long time until go.test reach default go test timeout and kill all test

I get your mean, the long hang-up is indeed unexpected behavior.
