### ISSUE TITLE
How to return xml to some endpoint and json to others.

### ISSUE THREAD

**Issue by rngallen** [gofiber/fiber#1999]
### Question Description

I want some routers to return json( used internally)
Other routers to return xml ( to be used by external app)

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by efectn** [comment]
You can use JSON() context method to return JSON body.
To return XML body, you can set content type and send xml body

**Comment by rngallen** [comment]
Do you mean something like this?

```
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question
   type Foor struct {
	ID int `xml:"id"`
	Name string `xml:"Name"`
	Amount float64 `xml:"Amount"`
  }


   app.Get("/", func(c *fiber.Ctx) error {

	data := Foor{12, "Foor", 2341}
	
	result, _ := xml.MarshalIndent(&data, "", " ")
	return c.Send(result) 
  })
  log.Fatal(app.Listen(":3000"))
}
```

**Comment by efectn** [comment]
> Do you mean something like this?
> 
> ```
> package main
> 
> import "github.com/gofiber/fiber/v2"
> import "log"
> 
> func main() {
>   app := fiber.New()
> 
>   // An example to describe the question
>    type Foor struct {
> 	ID int `xml:"id"`
> 	Name string `xml:"Name"`
> 	Amount float64 `xml:"Amount"`
>   }
> 
> 
>    app.Get("/", func(c *fiber.Ctx) error {
> 
> 	data := Foor{12, "Foor", 2341}
> 	
> 	result, _ := xml.MarshalIndent(&data, "", " ")
> 	return c.Send(result) 
>   })
>   log.Fatal(app.Listen(":3000"))
> }
> ```

Yes
