### ISSUE TITLE
[1.0.0-pre-release]c.Attachment download file is 0 byte

### ISSUE THREAD

**Issue by cheft** [gofiber/fiber#2]
Use `c.Attachment("./test.txt")`, the download file is 0 bytes.

The source file has content, but the download does not

```go
app.Get("/files/test", func(c *fiber.Ctx) {
  c.Attachment("./test.txt")
})
```

**Comment by Fenny** [comment]
Hi @cheft 

[Attachment](https://gofiber.github.io/fiber/#/context?id=attachment) only sets the `Content-Disposition` header.

I think you are after [SendFile](https://gofiber.github.io/fiber/#/context?id=sendfile)
```go
app.Get("/fiber/test", func(c *fiber.Ctx) {
		c.SendFile("./test.txt")
	})
```

**Comment by cheft** [comment]
sorry, I understand wrong. thx!
