### ISSUE TITLE
🚀 [Feature]: `ctx.Error()` helper function to quickly return an error with a response string 

### ISSUE THREAD

**Issue by ShivanshVij** [gofiber/fiber#2007]
### Feature Description

The `fasthttp.RequestCtx` object contains an `Error()` helper function that allows you to quickly specify the status code and error reason by calling `ctx.Error("reason", statusCode)`. 

Having this method available in fiber should be straight forward to do and it would make error responses much easier to send. 

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by Trim21** [comment]
you can use fiber.NewError, default error handler will convert it to a HTTP error response
