### ISSUE TITLE
🤗 [Question]: How to skip a handler function if the auth middleware fails and directly skip to response handler?

### ISSUE THREAD

**Issue by balanikaran** [gofiber/fiber#2008]
### Question Description

I'm having the code structure like this below:
```
someRouter.Use(auth.SomeAuthMiddleware)

someRouter.Post(
	"/someEndpoint",
	controller.SomeEndpointHandler,
	genericResponseHandler.GenericJSONResponseHandler,
)
```

What I want is, if my Auth Middleware fails for some reason, my `SomeEndpointHandler` should not run, and it should directly skip to the `GenericJSONResponseHandler` with the set status code.

Is that even possible? Or is my approach of code design is correct or not?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
fail with "panic" or error? 

if you want your handlers to continue, you would have to catch these errors, react to them and ignore them in the flow and put some information in the locals that you can use later for skipping

**Comment by balanikaran** [comment]
Yeah, I'm just setting the relevant `status_code` in the locals and then skipping the handlers by checking in the very beginning of the following handlers. I just wanted to know if there is any short-circuiting kind of pattern available.

**Comment by ReneWerner87** [comment]
> I just wanted to know if there is any short-circuiting kind of pattern available.
no i think not
@efectn @Trim21  any other ideas ?

**Comment by Trim21** [comment]
So if I understand correctly, you want `GenericJSONResponseHandler` to be executed
but not `SomeEndpointHandler` when `SomeAuthMiddleware` failed to authorized current request.

Common case for this is to just response (or return a error) in the `SomeAuthMiddleware`
and don't' call `c.Next()`, so the middleware and handler after this middleware won't be executed by nature.

Guessing from your handler name, the `GenericJSONResponseHandler` is used to create final response,
and if you need `GenericJSONResponseHandler` to create response,
you can use a middleware before auth middleware, use a customized error,
return it in your auth middleware and use `errors.As` to check it's expected error type.

**Comment by balanikaran** [comment]
Hey, thanks for the solution here, let me evaluate if we can use it in our code.

This was really helpful. :)

**Comment by efectn** [comment]
If you have some questions more, feel free to reopen the issue.
