### ISSUE TITLE
🤗 [Question]: Can not pass query params in group prefix

### ISSUE THREAD

**Issue by wavemoroc001** [gofiber/fiber#2009]
### Question Description

Hi there, I try to pass query params in nested url prefix like this 

`http://localhost:8585/classroom-service/account/submit-otp-link?test=testMessage` 

 **Router**

```go
func (h *Handler) Register(r *fiber.App) {
	v1 := r.Group("classroom-service")
	account := v1.Group("/account")
	account.Get("/submit-otp-link", h.handlePassQuery)
}
```

**Handler**
```go 
func (h *Handler) handlePassQuery(c *fiber.Ctx) error {
	param := c.Query("test", "Noting Here")
	return c.Status(fiber.StatusOK).JSON(fiber.Map{
		"Message": param,
	})
}

```

But it throw this  **Response**
```json
{
    "Reason": "strconv.ParseUint: parsing \"submit-otp-link\": invalid syntax",
    "Status": 400,
    "Timestamp": "2022-08-09 14:42:17.836431 TZ+07"
}
```

Cloud you advice how to fix this errors ? 

Fiber version : `2.36.0`

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func handlePassQuery(c *fiber.Ctx) error {
	param := c.Query("test", "Noting Here")
	return c.Status(fiber.StatusOK).JSON(fiber.Map{
		"Message": param,
	})
}

func main() {
	app := fiber.New()

	v1 := app.Group("classroom-service")
	account := v1.Group("/account")
	account.Get("/submit-otp-link", handlePassQuery)

	log.Fatal(app.Listen(":8585"))
}

```

![image](https://user-images.githubusercontent.com/7063188/183611021-88c67dfd-85f7-4b5c-b36b-e4522ee08818.png)
![image](https://user-images.githubusercontent.com/7063188/183611114-ac0393f8-cbd6-4e7d-9bfb-131c4b9ee21d.png)

@wavemoroc001 i cannot reproduce ? 
can't find "strconv.ParseUint" anywhere in our code, so must be the processes you didn't specify in the example

**Comment by wavemoroc001** [comment]
@ReneWerner87  Thank you for you kindness 
I found root cause, I think that might match  route to getAccountByID that i use `strconv` before go to `submit-otp-link` endpoint


``` go
	account.Get("/:ID", h.GetAccountByID)
	account.Get("/submit-otp-link", h.handlePassQuery)
```

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/183623622-4d56c53a-2649-449f-96d0-650bd906e79a.png)
https://docs.gofiber.io/guide/routing

yes please swap the route with the variable part with the route with the fixed part, otherwise the variable part will always be used before the other route, because with us the order plays a role just like with express

**Comment by wavemoroc001** [comment]
Thank you so much !
