### ISSUE TITLE
🤗 [Question]: Filesystem middleware: Handle when file name has spaces 

### ISSUE THREAD

**Issue by DhivakarK-git** [gofiber/fiber#2012]
### Question Description

We are trying to serve video files on a local server(intranet). FileNames with spaces in them with URLs being delimited using(%20). What's the solution for the same? 

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [x] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Can you give an example?
You know the app.Static function?
https://docs.gofiber.io/api/app#static

**Comment by ReneWerner87** [comment]
You have found a solution?
