### ISSUE TITLE
🐛 [Bug]: `IP()` function does not return client IP reliably

### ISSUE THREAD

**Issue by gbolo** [gofiber/fiber#2016]
### Bug Description

According to documentation for `func (c *Ctx) IP() string`: 

> IP returns the remote IP address of the request.

However, the logic in this function is too basic and cannot be trusted. Here are some issues for example:

- when setting `ProxyHeader: "X-Forwarded-For"` (or any other value), if this header is missing or empty then fiber will return an empty value for `c.IP()`. I think it would be better if the value defaulted to `fasthttp.RemoteIP().String()` when the value of this header is missing/empty
- no validation or modifications are done on the return value of `c.Get(c.app.config.ProxyHeader)`. This means that it's possible to return any string that does not even represent an IP

### How to Reproduce

Example App
```
package main

import (
	"github.com/gofiber/fiber/v2"
	"log"
)

func main() {
	app := fiber.New(fiber.Config{ProxyHeader: "X-Forwarded-For"})
	app.Get("/ip", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"ip": c.IP()})
	})
	log.Fatal(app.Listen(":19876"))
}
```

Testing
```
# Empty when proxy header is missing
❯ curl http://127.0.0.1:19876/ip
{"ip":""}

# Populated when proxy header has a value
❯ curl -H "X-Forwarded-For: 1.1.1.1" http://127.0.0.1:19876/ip
{"ip":"1.1.1.1"}

# The value is not checked, just simply passed through
❯ curl -H "X-Forwarded-For: whatever" http://127.0.0.1:19876/ip
{"ip":"whatever"}

❯ curl -H "X-Forwarded-For: 1.1.1.1, 2.2.2.2" http://127.0.0.1:19876/ip
{"ip":"1.1.1.1, 2.2.2.2"}
```

### Expected Behavior

```
# default to TCP IP address that you received the request from
❯ curl http://127.0.0.1:19876/ip
{"ip":"127.0.0.1"}

# same default if the proxy header does not make sense
❯ curl -H "X-Forwarded-For: whatever" http://127.0.0.1:19876/ip
{"ip":"127.0.0.1"}

# attempt to interpret what the IP of the actual client is
❯ curl -H "X-Forwarded-For: 1.1.1.1, 2.2.2.2" http://127.0.0.1:19876/ip
{"ip":"1.1.1.1"}
```

### Fiber Version

v2.36.0

### Code Snippet (optional)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"log"
)

func main() {
	app := fiber.New(fiber.Config{ProxyHeader: "X-Forwarded-For"})
	app.Get("/ip", func(c *fiber.Ctx) error {
		return c.JSON(fiber.Map{"ip": c.IP()})
	})
	log.Fatal(app.Listen(":19876"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
okay what would be your recommended change without causing a breaking change ?

**Comment by gbolo** [comment]
> okay what would be your recommended change without causing a breaking change ?

what do you mean by breaking? I think this is already broken right? I recommend that we do our best to match the function description. I don't see any value in keeping the function as-is.

Lets take a look at how some other web servers and reverse http proxies handle determining client IP:

- gin: https://github.com/gin-gonic/gin/blob/v1.8.1/gin.go#L454
- echo: https://github.com/labstack/echo/blob/v4.8.0/ip.go#L241
- fabio: https://github.com/fabiolb/fabio/blob/v1.6.1/proxy/http_headers.go#L37

I can work on a PR this week, if you agree that we need want this fixed

**Comment by gbolo** [comment]
@ReneWerner87 please review PR #2020

**Comment by ReneWerner87** [comment]
Sure, in the next days

**Comment by gbolo** [comment]
> Sure, in the next days

Thanks, no rush
