### ISSUE TITLE
🐛 [Bug]: Monitor middleware ignores custom settings if default title is used.

### ISSUE THREAD

**Issue by gaby** [gofiber/fiber#2019]
### Bug Description

When using the monitor middleware I noticed that if I don't change the title or refresh rate the other custom settings don't get applied. 

The bug is on this line: https://github.com/gofiber/fiber/blob/master/middleware/monitor/config.go#L99

Where if title or refresh rate are the `Default Values` everything else gets ignored in the `else`.

### How to Reproduce

Run code

### Expected Behavior

Custom settings should be applied regardless of title/refresh rate.

### Fiber Version

v2.36.0

### Code Snippet (optional) (Bug, Font/Chart URLs are ignored)

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/monitor"
)

func main() {
	app := fiber.New()

	app.Get("/metrics", monitor.New(monitor.Config{
	    FontURL: "blah/blah.css",
	    ChartJsURL: "blah/blah.js",
    }))

	log.Fatal(app.Listen(":3000"))
}
```

### Code Snippet (Working, Font/Chart URLs get applied)

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/monitor"
)

func main() {
	app := fiber.New()

	app.Get("/metrics", monitor.New(monitor.Config{
	    Title: "MyService Metrics Page",
	    FontURL: "blah/blah.css",
	    ChartJsURL: "blah/blah.js",
    }))

	log.Fatal(app.Listen(":3000"))
}
```

This bug doesn't show up in monitor_test.go, because the test is changing the `Title` to "New + DefaultTitle".

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
@jfcg can you support here
initial code is comming from https://github.com/gofiber/fiber/pull/1898

**Comment by jfcg** [comment]
I was just coding a cleaner solution to this :D

**Comment by gaby** [comment]
> I was just coding a cleaner solution to this :D

One thing I wish it supported is passing files paths instead of urls.

Right now I have copies of the js/css files in my container and I expose them via app.Static('/static', './static'). 

Ideally the monitor config supported file based resources and used those in the html imports.
