### ISSUE TITLE
🤗 [Problem]: tls.Config in ListenTLS

### ISSUE THREAD

**Issue by wireguard-dev** [gofiber/fiber#2025]
### Question Description

Can do you, please, set NextProto: []string{"h2"} in tls.Config of ListenTLS?
Without that I can't use dgrr/http2 :( 

Fiber version is v2.37.0-rc.1

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  http2.ConfigureServer(app.Server(), http2.ServerConfig{})

  log.Fatal(app.ListenTLS(":3000", ...))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by efectn** [comment]
I think we don't need it because of Fiber doesn't have default HTTP/2 support. You can use Listener to pass custom TLS config.

**Comment by wireguard-dev** [comment]
> I think we don't need it because of Fiber doesn't have default HTTP/2 support. You can use Listener to pass custom TLS config.

In my opinion, this might kill the ClientHelloInfo feature, because I don't have access to the non-exported fields in fiber.

**Comment by efectn** [comment]
> Author

Right. We may need to get TLS from https://github.com/gofiber/fiber/blob/master/listen.go#L31 and pass it to CHI to resolve this.
