### ISSUE TITLE
🚀 v3 Request: Revamp Startup Message

### ISSUE THREAD

**Issue by efectn** [gofiber/fiber#2032]
### Feature Description

I think we should revamp Fiber's startup message in v3 with more beautiful one. If you have some ideas please share them :smile:  :smile:  :smile: 

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the feature

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gozeloglu** [comment]
Hi @efectn. I checked the current startup message and it seems that it is a normal informative text. 

![Screen Shot 2022-08-24 at 00 25 29](https://user-images.githubusercontent.com/33967642/186269206-91e73ae6-c5aa-44eb-87fd-a7d24125231b.png)

I am OK with this informative text, but I think we can add fancy text like the one below. It is widely used in CLI messages. What do you think? 

```
    _______ __             
   / ____(_) /_  ___  _____
  / /_  / / __ \/ _ \/ ___/
 / __/ / / /_/ /  __/ /    
/_/   /_/_.___/\___/_/     
```

Also, we can add a welcome message. I can do these changes.

**Comment by efectn** [comment]
> Hi @efectn. I checked the current startup message and it seems that it is a normal informative text.
> 
> ![Screen Shot 2022-08-24 at 00 25 29](https://user-images.githubusercontent.com/33967642/186269206-91e73ae6-c5aa-44eb-87fd-a7d24125231b.png)
> 
> I am OK with this informative text, but I think we can add fancy text like the one below. It is widely used in CLI messages. What do you think?
> 
> ```
>     _______ __             
>    / ____(_) /_  ___  _____
>   / /_  / / __ \/ _ \/ ___/
>  / __/ / / /_/ /  __/ /    
> /_/   /_/_.___/\___/_/     
> ```
> 
> Also, we can add a welcome message. I can do these changes.

I agree. We can add informations to near/under the ASCII art. It would be more beautiful than making it table.

**Comment by gozeloglu** [comment]
Should I create the PR from the master branch?

**Comment by ReneWerner87** [comment]
no, from v3-beta branch

**Comment by gozeloglu** [comment]
Should I replace the table with something different? Like the plain text?
