### ISSUE TITLE
🚀 v3 Request: use https://github.com/stretchr/testify for testing

### ISSUE THREAD

**Issue by Trim21** [gofiber/fiber#2035]
### Feature Description

remove current `utils.AssertEqual` and use https://github.com/stretchr/testify for testing assertion

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by wangjq4214** [comment]
Good idea! Probably needs large work, if it's not a simple replacement.

**Comment by Trim21** [comment]
> Good idea! Probably needs large work, if it's not a simple replacement.

just use `gofmt -r` and `goimports`

**Comment by wangjq4214** [comment]
> > Good idea! Probably needs large work, if it's not a simple replacement.
> 
> just use `gofmt -r` and `goimports`

What I mean is to use different assertions for different judgments.

**Comment by Trim21** [comment]
```shell
gofmt -r "AssertEqual(t,a,b) => require.Equal(t,a,b)"
gofmt -r "AssertEqual(t,a,b) -> require.Equal(t,a,b)" ./
gofmt -r "AssertEqual(t,a,b) -> require.Equal(t,a,b)" -w ./...
gofmt -r "AssertEqual(t,a,b) -> require.Equal(t,a,b)" -w ./
gofmt -r "AssertEqual(t,a,b) -> require.Equal(t,a,b)" -w ./
gofmt -r "utils.AssertEqual(t,a,b) -> require.Equal(t,a,b)" -w ./
gofmt -r "utils.AssertEqual(t,a,b,c) -> require.Equal(t,a,b,c)" -w ./
gofmt -r "utils.AssertEqual(t,nil,a) -> require.Nil(t,a)" -w ./
gofmt -r "require.Equal(t,nil,a) -> require.Nil(t,a)" -w ./
gofmt -r "require.Equal(t,nil,a,b) -> require.Nil(t,a,b)" -w ./
gofmt -r "require.Nil(t,err) -> require.NoError(t,err)" -w ./
gofmt -r "require.Nil(t,err,a) -> require.NoError(t,err,a)" -w ./
gofmt -r "require.Equal(t,true,a) -> require.True(t,a)" -w ./
gofmt -r "require.Equal(t,true,a,b) -> require.True(t,a,b)" -w ./
gofmt -r "require.Equal(t,false,a,b) -> require.False(t,a,b)" -w ./
gofmt -r "require.Equal(t,false,a) -> require.False(t,a)" -w ./
gofmt -r "require.Equal(t,err,nil) -> require.NoError(t,err)" -w ./
gofmt -r "require.Equal(t,err,nil,a) -> require.NoError(t,err,a)" -w ./
```

😀

**Comment by efectn** [comment]
> ```shell
> gofmt -r "AssertEqual(t,a,b) -> require.Equal(t,a,b)" -w ./
> gofmt -r "utils.AssertEqual(t,a,b) -> require.Equal(t,a,b)" -w ./
> gofmt -r "utils.AssertEqual(t,a,b,c) -> require.Equal(t,a,b,c)" -w ./
> gofmt -r "utils.AssertEqual(t,nil,a) -> require.Nil(t,a)" -w ./
> gofmt -r "require.Equal(t,nil,a) -> require.Nil(t,a)" -w ./
> gofmt -r "require.Equal(t,nil,a,b) -> require.Nil(t,a,b)" -w ./
> gofmt -r "require.Nil(t,err) -> require.NoError(t,err)" -w ./
> gofmt -r "require.Nil(t,err,a) -> require.NoError(t,err,a)" -w ./
> gofmt -r "require.Equal(t,true,a) -> require.True(t,a)" -w ./
> gofmt -r "require.Equal(t,true,a,b) -> require.True(t,a,b)" -w ./
> gofmt -r "require.Equal(t,false,a,b) -> require.False(t,a,b)" -w ./
> gofmt -r "require.Equal(t,false,a) -> require.False(t,a)" -w ./
> gofmt -r "require.Equal(t,err,nil) -> require.NoError(t,err)" -w ./
> gofmt -r "require.Equal(t,err,nil,a) -> require.NoError(t,err,a)" -w ./
> ```
> 
> grinning

gofmt is really epic tool :D

**Comment by wangjq4214** [comment]
> ```shell
> gofmt -r "require.Nil(t,err) -> require.NoError(t,err)" -w ./
> ```

cool
