### ISSUE TITLE
🚀 v3 Request: Add Throttle and Timeout with retry in client

### ISSUE THREAD

**Issue by sujit-baniya** [gofiber/fiber#2038]
### Feature Description

While making requests with client, it might be essential to throttle the request based on the API Server bandwidth. So adding throttle Per Host.

Also API Server might take more time for request to complete. So timeout is required in this case. Since Retry is already implemented, timeout can be used with Retry

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the feature

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by wangjq4214** [comment]
I have some other work to do this week, and I will finish these features next week.
