### ISSUE TITLE
🤔logger is not logging route that is registered later than logger

### ISSUE THREAD

**Issue by soonoo** [gofiber/fiber#204]
Hi there.

```go
app.Get("/this-route-is-not-logged", ...)
app.Use(Logger())
app.Get("/this-route-is-logged", ...)
```
Is this intended to selectively applying middlewares?

**Comment by Fenny** [comment]
Hi @soonoo, **all routes** are appended to the so called `route []stack` that are executed (if matched) in order. So if you want to log all matching routes, make sure you place it at the top, I hope this explains how our routing mechanism works.

**Comment by soonoo** [comment]
@Fenny routers, middlewares, same stack. Thank you for your reply!
