### ISSUE TITLE
🐛 [Bug]: Group route `/` isn't handled properly in StrictRouting mode

### ISSUE THREAD

**Issue by jney** [gofiber/fiber#2044]
### Bug Description

route `/` isn't handled properly with `StrictRouting` option

### How to Reproduce

```
package main

import (
	"github.com/gofiber/fiber/v2"
)

func main() {

	app := fiber.New(fiber.Config{
		StrictRouting: true,
	})

	g := app.Group("/test")

	g.Get("/", func(c *fiber.Ctx) error {
		return c.SendString(c.Path())
	})

	g.Get("/1", func(c *fiber.Ctx) error {
		return c.SendString(c.Path())
	})

	app.Listen(":8888")
}
```

then request it:

```sh
$ curl 0.0.0.0:8888/test/1
/test/1
$ curl 0.0.0.0:8888/test/1/
Cannot GET /test/1/
$ curl 0.0.0.0:8888/test/
Cannot GET /test/
$ curl 0.0.0.0:8888/test
/test
```

### Expected Behavior

```
g.Get("/", func(c *fiber.Ctx) error {
	return c.SendString(c.Path())
})
```

should respond to `0.0.0.0:8888/test/`

### Fiber Version

v2.36.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
yes think you found a bug, we need more tests with the strict mode

https://github.com/gofiber/fiber/blob/b86f79eca4325c90aded51ec220e8e551420491d/helpers.go#L225-L227

probably it would be enough to remove the second part of the conditional, then it should go into the lower return branch and it should work

**Comment by wangjq4214** [comment]
> yes think you found a bug, we need more tests with the strict mode
> 
> https://github.com/gofiber/fiber/blob/b86f79eca4325c90aded51ec220e8e551420491d/helpers.go#L225-L227
> 
> probably it would be enough to remove the second part of the conditional, then it should go into the lower return branch and it should work

I also think this is the problem and there is very little testing about strictmode. Can I add the relevant content to router_test.go please?
