### ISSUE TITLE
🐛 [Bug]: Strange CSRF middleware behavior with header KeyLookup configuration

### ISSUE THREAD

**Issue by demget** [gofiber/fiber#2045]
### Bug Description

> Discord [discussion](https://discord.com/channels/704680098577514527/704682020990746624/1011604136111898664)

The middleware randomly starts responding with **403 Forbidden** if it's configured to look up for `header:X-Csrf-Token`. I found that the storage's map keys are messing up with random header values, so possibly this has something to do with unsafe magic.

One moment you have a map entry with a valid key which is actually a recently added CSRF token, a couple of requests ago you check this map and you see a random header value that replaced the first characters of the key, it can't be found by the middleware which results in returning the Forbidden response.

![image](https://user-images.githubusercontent.com/30910794/186612425-d163085d-de44-4610-8bfe-e17984096dc0.png)

### How to Reproduce

1. Use a default CSRF middleware for all your endpoints
2. Obtain your token with the GET request
3. Keep making POST requests and eventually you'll get **403 Forbidden**

### Expected Behavior

Technically, storage's map keys shouldn't mess up with random header values. CSRF middleware working correctly.

### Fiber Version

v2.34.1

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by demget** [comment]
René in our Discord [discussion](https://discord.com/channels/704680098577514527/704682020990746624/1011972988083634246) advised to:

> yes we should make a copy here
here https://github.com/gofiber/fiber/blob/master/middleware/csrf/csrf.go#L42 and here https://github.com/gofiber/fiber/blob/master/middleware/csrf/csrf.go#L37

**Comment by ReneWerner87** [comment]
we will look at this and develop a fix in a timely manner

**Comment by ReneWerner87** [comment]
does anyone have any idea how i can reproduce the case in the test? can't get the reused headers to have effect on memory
https://github.com/gofiber/fiber/blob/466d6b199575f4487b06762a4a3f9fef86631f47/middleware/csrf/csrf_test.go#L346-L394
@demget @efectn @GalvinGao 

![image](https://user-images.githubusercontent.com/7063188/187208014-b41d1efe-682b-4f2d-a6a5-0b04e1d330d8.png)

would like to produce this first before I fix it

**Comment by GalvinGao** [comment]
> does anyone have any idea how i can reproduce the case in the test? can't get the reused headers to have effect on memory
> 
> https://github.com/gofiber/fiber/blob/466d6b199575f4487b06762a4a3f9fef86631f47/middleware/csrf/csrf_test.go#L346-L394
> 
> @demget @efectn @GalvinGao 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/7063188/187208014-b41d1efe-682b-4f2d-a6a5-0b04e1d330d8.png)
> 
> 
> 
> would like to produce this first before I fix it
> 
> 

I think sequentially call `app.Test` won't trigger this as I suspect such issue would only occur in race conditions specifically, if I correctly understand the mechanism of `fasthttp`.

**Comment by ReneWerner87** [comment]
not really, it's just about putting the request and response objects back into the pool and reusing them later on.

but due to the unsafe there is still a link to the header value of the previous process

thought you can reproduce it like this

**Comment by demget** [comment]
I remember I couldn't reproduce this through go tests and postman, only together with the frontend part, which uses my API. I don't understand why is it working like so, but anyway I'm going to prepare a JS code snippet for you guys to produce this bug.

**Comment by ReneWerner87** [comment]
yes that would be good

try to fix it this time not test driven and hopefully will make that reproducible with your snippet then later in a test
