### ISSUE TITLE
🤗 [Question]: How to start fiber in another port with grpc

### ISSUE THREAD

**Issue by mpv945** [gofiber/fiber#2046]
### Question Description

I want to start the grpc service in the fiber service at the same time, and the ports will be occupied at the same time.

I specified grpc port as 9000 and http port as 9001. After starting the 9000 port of the grpc service, the http port will also use the 9000 port to start? I don't know how I need to adjust the two ports to start at the same time as a service?

### Code Snippet (optional)

```go
func main() {

	flag.Parse()
	gs := grpc.NewServer()
	pb.RegisterSimpleServer(gs, &grpcServer{})
	//lis, err := net.Listen("tcp", fmt.Sprintf(":%d", 9000))
	// Serve gRPC Server
	grpcLis, err := net.Listen("tcp", fmt.Sprintf(":%d", *port))
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	log.Println("Serving gRPC on 0.0.0.0" + fmt.Sprintf(":%d", *port))
	if err := gs.Serve(grpcLis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}

	serverPort := fmt.Sprintf(":%d", 9001)
	println("serverPort=", serverPort)

	app.Listen(serverPort)

}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by balcieren** [comment]
@mpv945 You should use `app.Listen` inside of `go func(){}`

**Comment by mpv945** [comment]
> 

不行，无法启动http端口
