### ISSUE TITLE
🤔 Use Context in websocket Conn?

### ISSUE THREAD

**Issue by hyingreborn** [gofiber/fiber#205]
**Question description**

**Code snippet (optional)**
main.go
```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  // JWTAuth is custom middleware, will use c.Local("claims") to store token claims in context
  app.Use(JWTAuth())
  app.Websocket("/ws", WSHandler)
}
```
wsHandler
```go
func WSHandler(c *fiber.Conn) {
	for {
		mt, msg, err := c.ReadMessage()
		if err != nil {
			log.Println("read:", err)
			break
		}
		log.Printf("recv: %s", msg)
		// if this is a normal handler
		claims := c.Locals("claims").(*middleware.JwtClaims)
		msg = fmt.Sprintf("Hello! Your ID is: %s", claims.UserID)
		err = c.WriteMessage(mt, msg)
		if err != nil {
			log.Println("write:", err)
			break
		}
	}
}
```

**Comment by Fenny** [comment]
This is something that was on my mind, we might move the Conn inside the Ctx. I will do some testing this weekend. I will keep you updated :+1:

**Comment by hyingreborn** [comment]
@Fenny Thanks a lot!

**Comment by Fenny** [comment]
Locals will be added to the `Conn` struct in `v1.8.3`

**Comment by coderbuzz** [comment]
Just landed here, so Fiber has websockets support already? What ws lib is used? Most performed Gobwas/ws?

**Comment by koddr** [comment]
@coderbuzz hi!

Fiber use [Fasthttp Websocket](https://github.com/fasthttp/websocket) lib via middleware https://github.com/gofiber/websocket

**Comment by coderbuzz** [comment]
@koddr hi,

Comes from NodeJS, in Node there is uWebSockets library which very perform.

[http benchmark](https://github.com/uNetworking/uWebSockets/blob/master/misc/bigshot_lineup.png)

[WS](https://github.com/uNetworking/uWebSockets/blob/master/misc/websocket_lineup.png)

Sadly the author won't make the library available in Go. Based on benchmark above; Gobwas/ws seems most performed.

Curious any benchmark result for Fasthttp Websocket vs Gobwas/ws?

**Comment by Fenny** [comment]
@coderbuzz, In my opinion uWebSockets is currently only useful for route levels. When we talk about proper concurrency inside the request handler, the benchmarks don't lie:
```
wrk -t1 -c400 -d10s http://127.0.0.1:8080/
```
**uWebsocketjs**
```js
// Thread Stats   Avg      Stdev     Max   +/- Stdev
// Latency     9.36ms    3.30ms  48.12ms   67.27%
// Req/Sec    43.02k     2.47k   47.12k    74.00%
const crypto = require('crypto');
const uws = require('uWebSockets.js');

var app = uws.App()
app.get('/*', (res, req) => {
  for (let i = 0; i < 10; i++) {
    const h = crypto.createHash('md5').update('foobar').digest('hex');
    if (h !== '3858f62230ac3c915f300c664312c63f') {
      throw h;
    }
  }
  res.end('Hello World!');
})
app.listen(8080, () => {});
```

**Fiber**
```go
// Thread Stats   Avg      Stdev     Max   +/- Stdev
// Latency     2.82ms  363.98us   6.02ms   84.98%
// Req/Sec   140.72k     5.03k  148.43k    75.00%
package main

import (
	"crypto/md5"
	"encoding/hex"

	"github.com/gofiber/fiber"
)

func main() {
        app := fiber.New()
        app.Get("/", func(c *fiber.Ctx) {
		for i := 0; i < 10; i++ {
			b := md5.Sum([]byte("foobar"))
			h := hex.EncodeToString(b[:])
			if h != "3858f62230ac3c915f300c664312c63f" {
				panic(h)
			}
		}
		c.SendString("Hello, World!")
        })
}
```

**Comment by Fenny** [comment]
@hyingreborn `Locals` are fixed in https://github.com/gofiber/fiber/pull/224 using https://github.com/gofiber/websocket

**Comment by kuchaguangjie** [comment]
So, what's the solution now ?

**Comment by kuchaguangjie** [comment]
Seems just use conn.Locals().
