### ISSUE TITLE
🐛 [Bug]: config DisableHeaderNormalizing not seem to be work with fiber Test()

### ISSUE THREAD

**Issue by bimbimprasetyoafif** [gofiber/fiber#2062]
### Bug Description

I found that configuration DisableHeaderNormalizing didn't work on unit testing.

### How to Reproduce

1. Create fiber instance with config `DisableHeaderNormalizing: true`
2. Register the route and handler with header checking. Let say: 
```go
       headers := c.GetReqHeaders()
	headerVal := headers["key"]    //No Title uppercase
	if headerVal == "" {
		// handling not found
	}
```
4. Create `req := httptest.NewRequest(...` and register header to it with `req.Header.Set("key", "value")`
5. run Test() function on fiber instance with `.Test(req)`

### Expected Behavior

The process will pass the handling not found because `key` was provided

### Fiber Version

v2.26.0

### Code Snippet (optional)

```go
func TestHeader(t *testing.T) {
  app := fiber.New(fiber.Config{DisableHeaderNormalizing: true})

	app.Get("/hello", func(c *fiber.Ctx) error {

		headers := c.GetReqHeaders()
		val := headers["key"]
		if val == "" {
			return c.SendStatus(400)
		}

		return c.SendStatus(200)
	})

	req := httptest.NewRequest("GET", "/hello", nil)
	req.Header.Set("key", "val")

	resp, _ := app.Test(req)
	assert.Equal(t, fiber.StatusOK, resp.StatusCode)
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by bimbimprasetyoafif** [comment]
It suddenly work on my snippet, maybe i will reopen this issue if this bug occure

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/187368933-c55119b9-e9db-47b3-9d9b-1f00dd93697d.png)
httptest changes the header

in fasthttp the option is processed correctly, just checked

**Comment by ReneWerner87** [comment]
the headers generated via httptest in the request cannot be lower case, so you have to look for a solution there

**Comment by ReneWerner87** [comment]
try this 
```go
	req := httptest.NewRequest("GET", "/hello", nil)
	req.Header["key"] = []string{"val"}
```
