### ISSUE TITLE
🤔 Middleware seems to run earlier than wildcard routing

### ISSUE THREAD

**Issue by hyingreborn** [gofiber/fiber#207]
**Question description**
Middleware seems to run earlier than wildcard routing，I use a custom middleware in router.Group，finally register a Not found route。

when i visit the "http://127.0.0.1:8080/api/v1/anyPathNotExist"，server still exec the JWTAuth() first，But my expectation is that the return route doesn't exist

**Code snippet (optional)**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  // General routing and using middleware in the group
	apiRouter := app.Group("/api")
	{
		authRouter := apiRouter.Group("/auth")
		{
			authRouter.Post("/login", auth.Login)
			authRouter.Get("/tokenRefresh", middleware.JWTAuth(), auth.TokenRefresh)
		}
		v1Router := apiRouter.Group("/v1", middleware.JWTAuth())
		{
			v1Router.WebSocket("/ws", websocket.WS)
			myRouter := v1Router.Group("/my")
			{
				myRouter.Get("/assets", my.Assets)
				myRouter.Get("/changePassword", my.ChangePassword)
			}
		}
	}

	// Not found route finally
	app.All("", func(c *fiber.Ctx) {
		c.Status(404).JSON("not found")
	})
}
```

**Comment by Fenny** [comment]
```go
app.Group("/api", Handler)
// equals
app.Use("/api", Handler)
```
This means that every route starting with `/api` will execute that handler.

If I'm correct, you only want to execute the middleware handler if the child route exists?

**Comment by hyingreborn** [comment]
@Fenny Yes ! Since child route doesn't exist, my expectation is not to execute any middleware, but to use a generic route to return 404 directly。
Although I registered the "/api" route group, it was not explicit to register a nonexistent child route such as "/api/notexist"

**Comment by Fenny** [comment]
Our routing logic is based on the express framework, you will get the same results using express.
```
GET /api/example
// "middleware!"
// 404 "Not Found"
```
```go
const express = require('express')
const app = new express()

app.use('/api', (req, res, next) => {
    console.log('middleware!')
    next()
})
app.use('*', (req, res) => {
    res.sendStatus(404);
})

app.listen(3001)
```

If you really want to execute the middleware only when a route is found, I suggest attaching the middleware to the route directly.

```go
authRouter.Post("/login", JWTAuth(), auth.Login())
```

**Comment by hyingreborn** [comment]
Thanks! It seems to be a feature rather than a problem
