### ISSUE TITLE
🚀v3 Request: shorter hooks naming and remove unnecessary returned error types

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#2072]
### Feature Description

1. I think `app.Hooks().OnName` is long naming. Actually `On` keyword refers to the event. So I think `app.OnName` is gonna be better.
2. Hooks return error but what will we do this error ? Where will we use this ? I think we should use `panic` in there. 

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by jonatan5524** [comment]
I'm new to this repo, I would like to work on this issue.

**Comment by jonatan5524** [comment]
By that logic we should change all the access to hooks methods as follow:
```app.Hooks().OnRoute``` to ```app.OnRoute```
```app.Hooks().OnFork``` to ```app.OnFork``` and so on...

**Comment by balcieren** [comment]
> By that logic we should change all the access to hooks methods as follow: `app.Hooks().OnRoute` to `app.OnRoute` `app.Hooks().OnFork` to `app.OnFork` and so on... Am I right?

it's just possible on v3

**Comment by jonatan5524** [comment]
> > By that logic we should change all the access to hooks methods as follow: `app.Hooks().OnRoute` to `app.OnRoute` `app.Hooks().OnFork` to `app.OnFork` and so on... Am I right?
> 
> it's just possible on v3

I am new to open source, this is mean that I can't yet work on this issue? I saw there are PRs on v3 to v3-beta branch.

**Comment by ReneWerner87** [comment]
am not really convinced of the change

the encapsulation under hooks i find better because then it is clear that they are hooks, they are better separated in the golang and gitbook docs and hopefully easier found and understood

**Comment by ReneWerner87** [comment]
feature is not wanted for the time being and is therefore temporarily closed until another decision is made.
