### ISSUE TITLE
🤗 [Question]: Don't have fuc get value param in post request with Content-Type: application/json

### ISSUE THREAD

**Issue by Nghiait123456** [gofiber/fiber#2078]
### Question Description

i have reques to server:
```bash
curl --location --request POST 'http://localhost:3000' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name":"json",
    "pass1": "111111"
}'
```

I want get value of name, pass, i don't find any function support. If in fast http, it's is same PostArgs().Peek()
in Fiber, i only one way:
```go
type User struct {
	Name interface{} `json:"name" xml:"name" form:"name"`
	Pass interface{} `json:"pass" xml:"pass" form:"pass"`
}

user  := User{}
if err := c.BodyParser(&persons); err != nil {
	fmt.Println(fmt.Sprintf("have error %s", err.Error()))
} else {
	fmt.Printf("success %v %v %v \n", persons, reflect.TypeOf(persons.Name), reflect.TypeOf(persons.Pass))
	return c.JSON(persons)
}
```

please help me this problem?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
```go
package main

import (
	"fmt"
	"log"
	"reflect"

	"github.com/gofiber/fiber/v2"
)

type User struct {
	Name interface{} `json:"name" xml:"name" form:"name"`
	Pass interface{} `json:"pass" xml:"pass" form:"pass"`
}

func main() {
	app := fiber.New()

	app.Post("/", func(ctx *fiber.Ctx) error {

		fmt.Println("form-param: pass", ctx.FormValue("pass")) // <- it prefer queryParam over formParam is queryparam
		fmt.Println("query-param: pass", ctx.Query("pass"))

		fmt.Println("form-param: name", ctx.FormValue("name")) // internal it is using PostArgs().Peek() -> but this is only working with content-type  application/x-www-form-urlencoded
		user := User{}
		if err := ctx.BodyParser(&user); err != nil {
			fmt.Println(fmt.Sprintf("have error %s", err.Error()))
			return err
		}

		fmt.Printf("success %v %v %v \n", user, reflect.TypeOf(user.Name), reflect.TypeOf(user.Pass))
		return ctx.JSON(user)
	})

	log.Fatal(app.Listen(":3000"))
}

```


lets check my code

**Comment by Nghiait123456** [comment]
@ReneWerner87  oh, it run success, but it's not way i want

I want only get "pass" or "name",  i don't want create struct. In fastHttp, this fc is : "PostArgs().Peek()"

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/012a2b16a5a391f76701431027224d69897e7fb2/ctx.go#L549 
-> 
https://github.com/valyala/fasthttp/blob/2f1e949d91d0ba1817afd80d7c981fafe7154774/server.go#L1097-L1114

**Comment by Nghiait123456** [comment]
oh, some thing went wrong, this code not run succes with application json:
try 
```
curl --location --request POST 'http://localhost:3000' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name":"json",
    "pass": "3333333333333333"
}'
```
package main

import (
	"fmt"
	"log"
	"reflect"

	"github.com/gofiber/fiber/v2"
)

type User struct {
	Name interface{} `json:"name" xml:"name" form:"name"`
	Pass interface{} `json:"pass" xml:"pass" form:"pass"`
}

func main() {
	app := fiber.New()

	app.Post("/", func(ctx *fiber.Ctx) error {

                //  it prefer queryParam over formParam
		fmt.Println("form-param: pass", ctx.FormValue("pass"))
		fmt.Println("query-param: pass", ctx.Query("pass"))
                // internal it is using PostArgs().Peek() -> but this is only working with content-type  application/x-www-form-urlencoded
		fmt.Println("form-param: name", ctx.FormValue("name")) 
		user := User{}
		if err := ctx.BodyParser(&user); err != nil {
			fmt.Println(fmt.Sprintf("have error %s", err.Error()))
			return err
		}

		fmt.Printf("success %v %v %v \n", user, reflect.TypeOf(user.Name), reflect.TypeOf(user.Pass))
		return ctx.JSON(user)
	})

	log.Fatal(app.Listen(":3000"))
}

it not work with code of you
```

```

**Comment by ReneWerner87** [comment]
It's only working with
application/x-www-form-urlencoded

**Comment by ReneWerner87** [comment]
PostArgs().Peek() and formValue will not work with json form data

**Comment by Nghiait123456** [comment]
@ReneWerner87  it's my problem in first Q/A
i don't find fc work on application - json 

i don't want create new struct and pass to body ctx.BodyParser(), i only want get one param 
please suggest me ?

**Comment by ReneWerner87** [comment]
unfortunately not possible without parsing the json you can not get the individual values for this structure

**Comment by Nghiait123456** [comment]
thank you @ReneWerner87
