### ISSUE TITLE
🤗 [Question]: How to get the RAW body?

### ISSUE THREAD

**Issue by alanhe** [gofiber/fiber#2085]
### Question Description

I want to support multi- `Content-Encoding`.

I find the method `Body()` that is supposed to give me the **raw** body. But when I check the source code, it seems to decompress some encodings by default.

For example, when it is `gzip`, I can call `Body()` to get the decompressed body, while it is `snappy`, I will have to handle the decompression logic myself.

Could you teach me if there's a better way to handle decompression?

https://github.com/gofiber/fiber/blob/8ec62a64cc8367372cd9eb1fc48eba380ee01bdf/ctx.go#L281-L311

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
just use `c.fasthttp.Request.Body() ` like we do

**Comment by alanhe** [comment]
Thank you very much for the tip! `c.Request().Body()`
