### ISSUE TITLE
🐛 [Bug]: No 413 response sent to firefox

### ISSUE THREAD

**Issue by mybigman** [gofiber/fiber#2086]
### Bug Description

Fiber doesnt send 413 response to firefox, however under chrome or safari it does.

Firefox inspector - v104.0.2
<img width="491" alt="image" src="https://user-images.githubusercontent.com/1289916/190134601-bc66d508-c4df-4a1f-8bb9-6866e3f1d823.png">

Chrome inspector
<img width="701" alt="image" src="https://user-images.githubusercontent.com/1289916/190134870-a90c99e2-a582-40be-abd5-0d01040b8eb7.png">

### How to Reproduce

1. create post endpoint as per code below
2. use firefox to upload file > 5MB

Firefox returns

The connection was reset
The connection to the server was reset while the page was loading.

### Expected Behavior

To return 413 response. Without this cant use custom error handler.

### Fiber Version

Fiber v2.37.1

### Code Snippet (optional)

```go
func PostUpload(c *fiber.Ctx) error {
	file, err := c.FormFile("attachment")
	if err != nil {
		log.Println(err)
	}
	log.Println(file.Filename)
	log.Println(file.Size)

	return nil
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
Probably same as https://github.com/gofiber/fiber/issues/1940. Will check it as soon as possible

**Comment by ReneWerner87** [comment]
yes it is exactly this problem 
https://github.com/valyala/fasthttp/issues/1348#issuecomment-1200122542

**Comment by efectn** [comment]
Closing this due to duplication. You can follow the issue from https://github.com/gofiber/fiber/issues/1940
