### ISSUE TITLE
🔥 Serve assets files from embedded resources

### ISSUE THREAD

**Issue by Shareed2k** [gofiber/fiber#209]
**Is your feature request related to a problem?**
there is no options to create one binary file with all assets

**Describe the solution you'd like**
i want to use something like http.FileServer, to use libs like [go.rice, pkger...]

**Comment by koddr** [comment]
@Shareed2k hi!

Try to use https://github.com/markbates/pkger by Mark Bates

**Comment by Shareed2k** [comment]
I know this is cool lib, can you show example how to use with fiber ?

**Comment by Shareed2k** [comment]
ok i found some agly way to work with pkger and fiber...

```golang
handler := fasthttpadaptor.NewFastHTTPHandler(http.StripPrefix("/console", http.FileServer(pkger.Dir("/ui/dist"))))

// for index.html
s.Get("/console", func(c *fiber.Ctx) {
	handler(c.Fasthttp)
})

// for assets
s.Get("/console/*", func(c *fiber.Ctx) {
	handler(c.Fasthttp)
})
```

**Comment by Fenny** [comment]
We could create a middleware for pkger, I will take a closer look next week.

**Comment by Fenny** [comment]
@Shareed2k https://github.com/gofiber/embed

Special thanks to @arsmn
