### ISSUE TITLE
🤗 [Question]: How can use named routes in the template

### ISSUE THREAD

**Issue by mybigman** [gofiber/fiber#2093]
### Question Description

All my `GET` endpoints use named routes. How I can I utilize this inside HTML templates?

I would like not having to hardcode these if possible?

### Code Snippet (optional)

```go
// endpoint
route.Get("/upload", controllers.ShowUpload).Name("upload")

// template eg:
<a href="{{ to('upload') }}">action</a>
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
inject the router (the app or group) in the template system and use this method https://docs.gofiber.io/api/app#getroute

**Comment by mybigman** [comment]
@ReneWerner87 thanks, however I am not seeing how since the `AddFunc` has to come before the `app`

I dont really want to have to inject the `app` on every endpoint.

```go
engine := html.New("./views", ".html")

engine.AddFunc("test", func(r string) string {
    // need app here
    return app.GetRoute(r).Name
})

app := fiber.New(fiber.Config{
    Views:             engine,
    ViewsLayout:       "layouts/base",
    BodyLimit:         20 * 1024 * 1024, // 20MB limit
})
```

**Comment by ReneWerner87** [comment]
Can try to provide an example later

**Comment by ReneWerner87** [comment]
Solution 1:
```go
func main() {
	engine := html.New("./assets", ".html")
	engine.AddFunc("getRoute", func(a *fiber.App, r string) string {
		return a.GetRoute(r).Path
	})

	app := fiber.New(fiber.Config{
		Views:     engine,
		BodyLimit: 20 * 1024 * 1024, // 20MB limit
	})
	// register the app for the view engine
	app.Use(func(ctx *fiber.Ctx) error {
		ctx.Bind(fiber.Map{"app": app})
		return ctx.Next()
	})

	app.Get("/test", func(ctx *fiber.Ctx) error {
		return ctx.Render("test", fiber.Map{
			"Title": "Hello, <b>World</b>!",
		})
	}).Name("testRoute")
}

```
```html
    <h1>{{.Title}}</h1>
    <div>{{ getRoute .app "testRoute" }}</div>
```

maybe we should do the initialization of the template system only when listing
just before we issue the start message to allow for better addition of the app

we will consider this for version 3

**Comment by mybigman** [comment]
@ReneWerner87 thanks mate much appreciated... I will work on that tonight. I like the sound of your proposed solution.

**Comment by foreverlz1111** [comment]
> 
Yes,template could be initiated on first load,then we“Render”some new data to update the page.
On V2: 
> app.Get("/", responder.InitDir)
> app.Post("/u", responder.UpdateDir)
If my template in "/" and I want to get new DirList after refresh the web,but the update was always overwrited by the first Get.

***
> Solution 1:
> 
> ```go
> func main() {
> 	engine := html.New("./assets", ".html")
> 	engine.AddFunc("getRoute", func(a *fiber.App, r string) string {
> 		return a.GetRoute(r).Path
> 	})
> 
> 	app := fiber.New(fiber.Config{
> 		Views:     engine,
> 		BodyLimit: 20 * 1024 * 1024, // 20MB limit
> 	})
> 	// register the app for the view engine
> 	app.Use(func(ctx *fiber.Ctx) error {
> 		ctx.Bind(fiber.Map{"app": app})
> 		return ctx.Next()
> 	})
> 
> 	app.Get("/test", func(ctx *fiber.Ctx) error {
> 		return ctx.Render("test", fiber.Map{
> 			"Title": "Hello, <b>World</b>!",
> 		})
> 	}).Name("testRoute")
> }
> ```
> 
> ```
>     <h1>{{.Title}}</h1>
>     <div>{{ getRoute .app "testRoute" }}</div>
> ```
> 
> maybe we should do the initialization of the template system only when listing just before we issue the start message to allow for better addition of the app
> 
> we will consider this for version 3
