### ISSUE TITLE
🤗 [Question]: Logging to Custom File on GoFiber

### ISSUE THREAD

**Issue by Koredeoluwafemi** [gofiber/fiber#2094]
### Question Description

I will like to log to a custom file using the golang package log library.

I am currently using this code below, but its not working on a gofiber app

	// open log file
	logFile, err := os.OpenFile("/assets/log.txt", os.O_APPEND|os.O_RDWR|os.O_CREATE, 0644)
	if err != nil {
		log.Panic(err)
	}
	defer logFile.Close()

	
	log.SetOutput(logFile)
	

	
	log.Println("Custom File Log")

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
Hello @Koredeoluwafemi  Is it possible to use https://github.com/gofiber/fiber/tree/master/middleware/logger ? It can set the [OutPut](https://github.com/gofiber/fiber/blob/master/middleware/logger/config.go#L42)

**Comment by ReneWerner87** [comment]
its working on my machine 
```go
package main

import (
	"log"
	"os"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	logFile, err := os.OpenFile("./assets/log.txt", os.O_APPEND|os.O_RDWR|os.O_CREATE, 0644)
	if err != nil {
		log.Panic(err)
	}
	defer logFile.Close()
	log.SetOutput(logFile)

	app.Get("/test", func(ctx *fiber.Ctx) error {
		log.Println("In GET handler")

		return ctx.SendStatus(200)
	})
	log.Println("After app init")

	log.Fatal(app.Listen(":3000"))
}
```

![image](https://user-images.githubusercontent.com/7063188/190572648-78092012-93d3-4f1f-8129-230cbb1b1ff3.png)

**Comment by ReneWerner87** [comment]
pls check your permissions and the path
maybe you miss the relative part in your path

**Comment by Koredeoluwafemi** [comment]
Thanks @ReneWerner87 for the example, it works now.
