### ISSUE TITLE
🐛 [Bug]: panic: add: invalid http method LOAD

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2096]
### Bug Description

I want to create a handler with a custom http method called "LOAD".

```
app.Add("LOAD", "/hello", func(c *fiber.Ctx) error {
	return c.SendString("Hello, World 👋!")
})
```

It crashes the application:

`panic: add: invalid http method LOAD`

### How to Reproduce

app.Add("LOAD", "/hello", func(c *fiber.Ctx) error {
	return c.SendString("Hello, World 👋!")
})

### Expected Behavior

It should allow for custom http methods

### Fiber Version

 Fiber v2.37.1

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Not really a bug, until now our methodic does not allow custom methods

**Comment by ReneWerner87** [comment]
Maybe we can provide a method where you can register the custom request methods

**Comment by rafimuhammad01** [comment]
hi @ReneWerner87 my first approach for this issue is to make a new function called `AddMethod` that adding new method to the list of registered method

```go
var registeredMethods []string


func (app *App) AddMethod(method string) error {
	registeredMethods = append(registeredMethods, strings.ToUpper(method)
	return nil
}
```

Then add new validation on `app.register(...)` method, such that:

```go
func (app *App) register(method, pathRaw string, handlers ...Handler) Router {
	// Uppercase HTTP methods
	method = utils.ToUpper(method)
	// Check if the HTTP method is valid unless it's USE
	if method != methodUse && methodInt(method) == -1 && !slices.Contains(registeredMethods, method) {
		panic(fmt.Sprintf("add: invalid http method %s\n", method))
	}
       .....
```

With this implementation we can add new method but I'm kinda confuse since this implementation doesn't have any functionality except to passed the validation. Let me know what do you think about this @ReneWerner87 ? 

Thank you! 🍺

**Comment by efectn** [comment]
> hi @ReneWerner87 my first approach for this issue is to make a new function called `AddMethod` that adding new method to the list of registered method
> 
> ```go
> var registeredMethods []string
> 
> 
> func (app *App) AddMethod(method string) error {
> 	registeredMethods = append(registeredMethods, strings.ToUpper(method)
> 	return nil
> }
> ```
> 
> Then add new validation on `app.register(...)` method, such that:
> 
> ```go
> func (app *App) register(method, pathRaw string, handlers ...Handler) Router {
> 	// Uppercase HTTP methods
> 	method = utils.ToUpper(method)
> 	// Check if the HTTP method is valid unless it's USE
> 	if method != methodUse && methodInt(method) == -1 && !slices.Contains(registeredMethods, method) {
> 		panic(fmt.Sprintf("add: invalid http method %s\n", method))
> 	}
>        ...
> ```
> 
> With this implementation we can add new method but I'm kinda confuse since this implementation doesn't have any functionality except to passed the validation. Let me know what do you think about this @ReneWerner87 ?
> 
> Thank you! 🍺

I think it's good idea to add custom method registration method to app. Maybe it would be more efficent with improving method int for custom methods. We use it in most places

**Comment by rafimuhammad01** [comment]
Well I think we can use `map[string]int` for registeredMethods instead of `[]string`. So, in method int we can check the if the new method is exist and return the int value.

But I think we need a validation on this function to check if the number assigned to the new method won’t be duplicated with existing method. 

What do you think about this? @efectn

**Comment by efectn** [comment]
> Well I think we can use `map[string]int` for `registeredMethods` instead of `[]string`. So, in method int we can check if the new method is exist and return the int value.
> 
> But I think we need a validation on this function to check if the number assigned to the new method won’t be duplicated with existing method.
> 
> What do you think about this? @efectn

Agree. We should check duplications

**Comment by rafimuhammad01** [comment]
@efectn I submitted PR for this issue, please kindly review it. Thank you 🍺
