### ISSUE TITLE
🤗 [Question]: func (app *App) Patch(path string, handlers ...Handler) Router

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2097]
### Question Description

I understand why `Router` is returned by `.Group(...)` and `.Use()`.

Why does `*App.Get` etc return `Router`? What is the use-case? Am I doing something wrong.

No example in the docs ever uses the return value.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
This should be `Method Chaining`.

such as 
```
package main

import "github.com/gofiber/fiber/v2"

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World 👋!")
	}).Get("/ping", func(ctx *fiber.Ctx) error {
		return ctx.SendString("Hello, Ping 👋!")
	})

	app.Listen(":3000")
}
```

**Comment by ReneWerner87** [comment]
Yes exactly we want to support the concept of method chaining https://en.wikipedia.org/wiki/Method_chaining#%3A%7E%3Atext%3DMethod_chaining%2C_also_known_as%2Cto_store_the_intermediate_results.?wprov=sfla1

**Comment by pjebs** [comment]
@li-jin-gou I don't understand what your example code is trying to achieve in a real-world scenario?

**Comment by li-jin-gou** [comment]
> Yes exactly we want to support the concept of method chaining https://en.wikipedia.org/wiki/Method_chaining#%3A%7E%3Atext%3DMethod_chaining%2C_also_known_as%2Cto_store_the_intermediate_results.?wprov=sfla1

:sob: refer to :point_up_2:

**Comment by ReneWerner87** [comment]
Since no error or other important return value is needed in this logic, we decided to return the router instead of a void value that nobody can use.
whereby the concept of method chaining can be used

some developers don't like this and just use the app or group instance from before other developers like this concept

in the examples we tried to explain as simple as possible, so we don't show this concept concretely
