### ISSUE TITLE
🤗 [Question]: Documentation should address this:

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2098]
### Question Description

Is there a difference in these 2 approaches in the documentation:

```
app.Get("/*", func(c *fiber.Ctx) error {
    return c.SendString(c.Params("*"))
})

```

vs 

```
app.Use("/", func(c *fiber.Ctx) error {
    // Edit: There seems to be no equivalent of c.Params("*") using this approach I noticed.
})

(**assuming** I don't want to make it in middleware. Say it's just a standard endpoint handler)
```

What are the advantages and disadvantages of either approach?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
The first handler matched only GET request methods.

The second matched all request methods.

The advantages or disadvantages are the same as with the other rest frameworks or expressjs.

In the case the route detections behave the same nothing more.
