### ISSUE TITLE
Unable to test POST request using app.Test

### ISSUE THREAD

**Issue by ekaputra07** [gofiber/fiber#210]
**Question description**
I tried to test my POST request handler, if I didn't specify the request body its just fine but when I set the body it returns an error, and I need to test my handler for a different data in body.

The error message though is not coming from **Fiber** but from **fasthttp**. Not sure if I missed something when using the `app.Test(req)` or its a bug.

**Code snippet (optional)**

```go
package main

import (
  "fmt"
  "strings"
  "net/http"
  "github.com/gofiber/fiber"
)

func main() {
  app := fiber.New()
  app.Post("/", func(c *fiber.Ctx){
    c.Send("testing")
  })

  req, _ := http.NewRequest("POST", "/", strings.NewReader(`{"data": "123"}`))
  _, err := app.Test(req)
  fmt.Println(err)    
  // Error message: error when reading request headers: EOF. Buffer size=13, contents: "{\"data\": 123}"
}
```
**Error message: error when reading request headers: EOF. Buffer size=13, contents: "{\"data\": 123}"**

The strange thing is, I did nothing with headers, only sending request body but I got error related to headers.

Thanks

**Comment by Fenny** [comment]
Hi @ekaputra07, when you make a post request you need add the `Content-Length` header.

```go
package main

import (
	"io/ioutil"
	"log"
	"net/http"
	"strconv"
	"strings"

	"github.com/gofiber/fiber"
)

func main() {
	app := fiber.New()
	app.Post("/", func(c *fiber.Ctx) {
		c.Send("testing")
	})

	data := `{"data": "123"}`
	req, _ := http.NewRequest("POST", "/", strings.NewReader(data))
	req.Header.Add("Content-Length", strconv.Itoa(len(data)))
	resp, err := app.Test(req)
	if err != nil {
		log.Fatal(err)
	}
	if body, err := ioutil.ReadAll(resp.Body); err == nil {
		log.Println(string(body)) // "testing"
	}
}
```

**Comment by ekaputra07** [comment]
@Fenny great! thanks so much. Will close this issue.
