### ISSUE TITLE
🐛 [Bug]: unstable behaviour of ReqHeaderParser/QueryParser methods

### ISSUE THREAD

**Issue by N1cOs** [gofiber/fiber#2100]
### Bug Description

Recently we started to use fiber in our new service. After a while we encountered a problem in production that `ReqHeaderParser` didn't parse some headers of client identifiers. This behaviour starts at arbitrary point of time and if it happens, then all future requests face that problem. For now only restarting the application fix it.

I added log wrapper to inspect incoming requests on errors. This wrapper just logs required headers through method `ctx.Get`. When it happened last time `ctx.Get` returned non-empty string, although `ReqHeaderParser` set empty value into request struct.

I assume that we faced some sort of race, but on first glance I couldn't spot it. 

### How to Reproduce

As it'a an unstable behaviour it hard to reproduce it in sandbox. I suppose code snippet will be more useful in our situation.  Anyway, formal steps for handler:
1. Parse headers by using `ReqHeaderParser`
2. Parse query parameters by using `QueryParser`
3. Get value of client identifier, which is sent in headers
4. See empty value

### Expected Behavior

Request struct has non-empty client identifier

### Fiber Version

v2.29.0

### Code Snippet (optional)

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

type TestRequest struct {
	ClientID1 *string `json:"x-client-id1,omitempty" reqHeader:"x-client-id1"`

	ClientID2 *string `json:"x-client-id2,omitempty" reqHeader:"x-client-id2"`

	Param1 *string `json:"param1,omitempty" query:"param1"`

	Param2 *string `json:"param2,omitempty" query:"param2"`

	AppName string `json:"x-app-name" reqHeader:"x-app-name"`
}

func handler(c *fiber.Ctx) error {
	// Test request: curl 'http://localhost:3000/test?param1=param1' -H 'x-client-id1: client1' -H 'x-app-name: web'
	var req TestRequest
	if err := c.ReqHeaderParser(&req); err != nil {
		return fiber.ErrBadRequest
	}
	if err := c.QueryParser(&req); err != nil {
		return fiber.ErrBadRequest
	}

	// At some point we start to exit from handler here.
	// Although wrapper log handler indicates that request
	// has one of the client identifier (i.e. method c.Get("x-client-id1") returns non-empty string).
	if req.ClientID1 == nil && req.ClientID2 == nil {
		return fiber.ErrNotFound
	}
	return c.JSON(&req)
}

func main() {
	app := fiber.New()
	app.Get("/test", handler)
	log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by N1cOs** [comment]
Also during development we encountered a problem with order of calling methods `QueryParser` and `ReqHeaderParser`. I didn't find comments about it in docs, but if we change order in above snippet, then we return error on each request:
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

type TestRequest struct {
	ClientID1 *string `json:"x-client-id1,omitempty" reqHeader:"x-client-id1"`

	ClientID2 *string `json:"x-client-id2,omitempty" reqHeader:"x-client-id2"`

	Param1 *string `json:"param1,omitempty" query:"param1"`

	Param2 *string `json:"param2,omitempty" query:"param2"`

	AppName string `json:"x-app-name" reqHeader:"x-app-name"`
}

func handler(c *fiber.Ctx) error {
	// Test request: curl 'http://localhost:3000/test?param1=param1' -H 'x-client-id1: client1' -H 'x-app-name: web'
	// Change order of calling parsers.
	var req TestRequest
	if err := c.QueryParser(&req); err != nil {
		return fiber.ErrBadRequest
	}
	if err := c.ReqHeaderParser(&req); err != nil {
		return fiber.ErrBadRequest
	}

	if c.Get("x-client-id1") == "" {
		panic("empty clientID1")
	}

	if req.ClientID1 == nil && req.ClientID2 == nil {
		return fiber.ErrNotFound
	}
	return c.JSON(&req)
}

func main() {
	app := fiber.New()
	app.Get("/test", handler)
	log.Fatal(app.Listen(":3000"))
}
```

**Comment by ReneWerner87** [comment]
yes you are right, there is something strange

this error occurs in any case because you use the same struct, which we have not tested yet

i also did some troubleshooting and it seems like the gorilla schema parser cache is messing something up

**Comment by li-jin-gou** [comment]
> yes you are right, there is something strange
> 
> this error occurs in any case because you use the same struct, which we have not tested yet
> 
> i also did some troubleshooting and it seems like the gorilla schema parser cache is messing something up

in this case, filed cache key equal to Variable Name，causes judgment failure

**Comment by N1cOs** [comment]
@li-jin-gou thanks for PR! However, does #2101 fix unstable behaviour of `ReqHeaderParser`? From changes in PR, for me, it seems that it only fixes problem with parsing query/header/body params into single struct

**Comment by N1cOs** [comment]
@ReneWerner87 up above question) Today we faced the problem again. If you think, that PR fix initial problem with unstable behaviour, then we can update version and monitor situation.

> i also did some troubleshooting and it seems like the gorilla schema parser cache is messing something up

And what did you mean in that message? Were you able to reproduce the problem in your environment?

**Comment by ReneWerner87** [comment]
Yes, i was able and the PR was fixing the problem which i described before(with the caching)

Can you try the master version in your go.mod file?

May plan is to release the stuff on the weekend.

**Comment by ReneWerner87** [comment]
https://stackoverflow.com/questions/53682247/how-to-point-go-module-dependency-in-go-mod-to-a-latest-commit-in-a-repo/53682399#53682399

**Comment by li-jin-gou** [comment]
> https://stackoverflow.com/questions/53682247/how-to-point-go-module-dependency-in-go-mod-to-a-latest-commit-in-a-repo/53682399#53682399

you are so thoughtful :stuck_out_tongue:

**Comment by N1cOs** [comment]
Thanks guys! I updated module to master version. If encounter problem again, I'll write :)
