### ISSUE TITLE
🤗 [Question]: Is it possible to get a current list of all of the routes?

### ISSUE THREAD

**Issue by acidjazz** [gofiber/fiber#2111]
### Question Description

for dev purposes I like to have an endpoint showing a nice HTML table of my routes - I need a way to get a list of them for this

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
Maybe add an `App.GetRoutes`

**Comment by li-jin-gou** [comment]
I see that `App.Stack()` can also get all the routers, but It can modify the app's route information.

**Comment by acidjazz** [comment]
thank you @li-jin-gou - i was able to use that to get my list going:

```go
func List(c *fiber.Ctx) error {

	type RouteInfo struct {
		Method   string
		Name     string
		Path     string
		Handlers string
	}

	routes := []RouteInfo{}

	for _, routeStack := range c.App().Stack() {
		for _, route := range routeStack {
			var handlers string
			for _, handler := range route.Handlers {
				handlers += runtime.FuncForPC(reflect.ValueOf(handler).Pointer()).Name() + " "
			}
			routes = append(routes, RouteInfo{
				Method:   route.Method,
				Name:     route.Name,
				Path:     route.Path,
				Handlers: handlers,
			})
		}
	}

	return render.Render(c, routes)
}
```

I wonder if an easier methodology is worth adding as a feature? maybe `c.App().RouteList()` ?

I can attempt a PR but I'm still somewhat new with Go
