### ISSUE TITLE
🐛 [Bug]: Custom Middleware creating routes

### ISSUE THREAD

**Issue by acidjazz** [gofiber/fiber#2113]
### Bug Description

I wrote a simple middleware to see benchmarks of my endpoints:

```go
func Benchmark(c *fiber.Ctx) error {
	c.Locals("tonicBenchmark", time.Now().UnixMicro())
	return c.Next()
}
```
I use it like this:

```go
app.Use(route.Benchmark)
```

Since I've added this - I'm noticing tons of new routes when i enable `EnablePrintRoutes` ->

```
method  | path                | name | handlers
------  | ----                | ---- | --------
POST    | /                   |      | github.com/fumeapp/tonic/route.Benchmark github.com/gofiber/fiber/v2/middleware/cors.New.func1 
GET     | /                   |      | github.com/fumeapp/tonic/route.Benchmark 
```

I also see a ton of new routes using the CORS middleware - is this ok? it's really hard to filter these vs my real routes.

### How to Reproduce

try my middleware out

### Expected Behavior

Only see the routes I've defined

### Fiber Version

v2

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Hi
there is no difference between the middlewares and the routes

each handler is a middleware for us and is defined for a certain type of route

the print route feature should show all routes as described in the description without any restriction

>  is this ok?

yes

**Comment by li-jin-gou** [comment]
refer to https://github.com/gofiber/fiber/pull/2112
