### ISSUE TITLE
🚀 [Feature]: Add ability to configure client for proxy.Do

### ISSUE THREAD

**Issue by Vovcharaa** [gofiber/fiber#2116]
### Feature Description

Add ability to provide custom client configuration to client that used inside proxy.Do, or make client from proxy package public.

### Additional Context (optional)

Right now i faced issue where i was out of free connections (ErrNoFreeConns) and couldn`t provide custom number of connection per host or wait for connection timeout and was forced to copy-paste proxy implementation to my code to provide custom client settings.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by li-jin-gou** [comment]
Referring to the proxy usage scenario of the `Hertz` , I found it useful to set the client.
