### ISSUE TITLE
🤗 [Question]: When got 2 fields of the same name (and type) via embedding, neither will receive the param?

### ISSUE THREAD

**Issue by kuchaguangjie** [gofiber/fiber#2121]
### Question Description

```
struct A {
	ID        uint64    `form:"id" json:"id"`
}
struct B {
	ID        uint64    `form:"id" json:"id"`
}
struct C {
        A
        B
}
```

Try to receive param `id = 1`:
```
c := &Ｃ{}
ctx.QueryParser(c)
```

Then c's id is zero value `0`, removing one of the id from A or B, then could receive id as `1`.

I did this by mistake in the first place, but wondering is it golang's feature or fiber's feature that: when got 2 fields of the same name (and type), neither will receive the param, and there is no error at all?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
Hello @kuchaguangjie you can refer to https://github.com/golang/go/issues/19194

**Comment by kuchaguangjie** [comment]
Ok

> Otherwise there are multiple fields, and all are ignored; no error occurs
