### ISSUE TITLE
🐛 [Bug]: csrf cookie middleware encryption

### ISSUE THREAD

**Issue by mybigman** [gofiber/fiber#2125]
### Bug Description

When using the csrf middleware without changing the cookie name the cookie value is in plain text.

When you change the cookie name the value becomes encrypted.

<img width="731" alt="image" src="https://user-images.githubusercontent.com/1289916/192527998-92d14508-ece8-44d1-89aa-ea76c50c0ee0.png">

### How to Reproduce

see code below...

### Expected Behavior

I expect to see it encrypted no matter what since I am using `encryptcookie` middleware.

Everything still works just very odd behavior.

### Fiber Version

Fiber v2.38.1 

### Code Snippet (optional)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/csrf"
	"github.com/gofiber/fiber/v2/middleware/encryptcookie"
)

func main() {
	app := fiber.New()

	app.Use(encryptcookie.New(encryptcookie.Config{
		Key: "blah blah",
	}))

	app.Use(csrf.New(csrf.Config{
		KeyLookup:      "form:pid",
		CookieName:     "csrf_1", // set encrypts - unset plain text
		CookieHTTPOnly: true,
	}))

	app.Listen(":8081")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
we skip some of the cookies in the encryption https://github.com/gofiber/fiber/blob/master/middleware/encryptcookie/config.go#L37
otherwise it is hard to know if the cookie value in the crsf middleware is encrypted or not

implemented in https://github.com/gofiber/fiber/commit/bff8843abd95b2fad8eb0fc421f0612da582db52
@amir9480 can you help here with some explaintions

**Comment by amir9480** [comment]
@mybigman
Encrypting the csrf cookie value can cause issues for your app. You should add your csrf key (csrf_1) in encryptcookie `Except`  configuration.
```go
app.Use(encryptcookie.New(encryptcookie.Config{
    Key: "blah blah",
	Except: []string{"csrf_1"},
}))
```
Please check #1631.
