### ISSUE TITLE
🤗 [Question]: How can I clear the Cache ?

### ISSUE THREAD

**Issue by levniko** [gofiber/fiber#2129]
### Question Description

I'm using the Cache middleware for some endpoints. This is my config for cache:
```
// ConfigDefault is the default config
var ConfigDefault = cache.Config{
    Next: func(c *fiber.Ctx) bool {
        return c.Query("refresh") == "true"
    },
    Expiration:           1 * time.Minute,
    CacheControl:         true,
    StoreResponseHeaders: false,
    Storage:              nil,
}
```
And this is my endpoint:
```
cacheGroup := group.Use(cache.New(ConfigDefault))
cacheGroup.Get("/products", productHandler.Get)
```
My question is that how can I clear the cache when products table updated ?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
Default cache Storage is a  memory store. You can use redis cache store  to instead of it and when products table updated, you also update redis cache. refer to https://github.com/gofiber/storage

**Comment by ReneWerner87** [comment]
think that is currently not easily possible

you could inject a storage and then empty it
![image](https://user-images.githubusercontent.com/7063188/192955059-2053450b-2f26-4f8e-9941-302bd392b565.png)

**Comment by levniko** [comment]
thank you so much @ReneWerner87 @li-jin-gou
