### ISSUE TITLE
🚀 [Feature]: Export matching function

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2138]
### Feature Description

Let say I have a route path like this: `"/user/:name/books/:title"`.

I need **_the_** function used by fiber's router to check if a url matches that path.

Perhaps: 

```go
app.Use(func(c *fiber.Ctx) error {
	path := `/user/:name/books/:title`
	reqURL := string(c.Request().URI().Path())
	if Match(path, reqURL) {
		// Do something
	}
	return c.Next()
})

```

I believe the matching is done here: https://github.com/gofiber/fiber/blob/master/router.go#L64 (unexported)

### Additional Context (optional)

Currently I am doing it like this as a workaround:

```go
s.All(`/user/:name/books/:title`, func(c *fiber.Ctx) error {
	// Do something
	return c.Next()
})
```

This approach makes the path and **all** the methods end up in `app.Stack()`.
Since I am essentially building middleware, I don't want it to appear as route(s).

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
we can make
I also had the thought

but is not so simple
and also not only the match function

before you can match this route you have to create a route first

for this there is an analysis function which is not really optimized because it was only used for the declaration of the routes so far

we would have to optimize this and then provide both functionalities and document how this can be used

**Comment by pjebs** [comment]
I'm only interested in simpler functionality than what you envision.

**Comment by ReneWerner87** [comment]
> This approach makes the path and all the methods end up in app.Stack().
Since I am essentially building middleware, I don't want it to appear as route(s).

sorry had overlooked the sentence

so you just don't want them to show up in stack ?

why not solve it differently by making this functionality filterable or overwriteable ?

**Comment by pjebs** [comment]
I can't tell which paths are actual routes and which are from the "middleware" (`app.All()`). They both end up in the stack are indistinguishable. They are also provided from outside my package.

**Comment by ReneWerner87** [comment]
ok

**Comment by pjebs** [comment]
Let me know what you think of this PR

**Comment by pjebs** [comment]
This is now complete.

**Comment by leonklingele** [comment]
> NOTE: The reason I'm asking for "obscure" functionality in my many feature requests is because I am making a package that combines fiber and sveltekit super-super tightly (tighter than it's ever been done before) and I need to interact with sveltekit's own rounting system.
> 
> I will open-source my package and demo it to everyone soon.

Sorry for abusing this issue to message you. Have you made any progress on this sveltekit-fiber package? I'm very interested!

**Comment by pjebs** [comment]
@leonklingele I've made a lot of progress. I am looking for some help though. I can give a demo. We can meet up on zoom.

**Comment by leonklingele** [comment]
@pjebs sent you an email, hope it's the correct address I used.

**Comment by pjebs** [comment]
@leonklingele which email address? I didn't receive. Try planepjs@hotmail.com

**Comment by pjebs** [comment]
Oops: @leonklingele planetpjs@hotmail.com
