### ISSUE TITLE
🚀 [Feature]: missing session SessionOnly (cookie)

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2145]
### Feature Description

See: https://pkg.go.dev/github.com/gofiber/fiber/v2@v2.38.1/middleware/session#Config

There seems to be no option to set SessionOnly.

See: https://pkg.go.dev/github.com/gofiber/fiber/v2#Cookie

SessionOnly deletes the cookies when the user closes the browser window.

If you set Expiration to 0, it deletes it immediately.

There is also ambiguity: Does `Expiration` refer to how long the data is stored in the session data or how long the cookie lasts for?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by li-jin-gou** [comment]
Refer to https://stackoverflow.com/questions/14196671/session-only-cookies-with-javascript

**Comment by pjebs** [comment]
No, it can be done via backend.
You have to omit expiry value. Prob is you can't omit because a value of 0 ( the "zero value") means something else i.e. Delete session immediately.

**Comment by li-jin-gou** [comment]
![image](https://user-images.githubusercontent.com/97824201/194757621-2902bfbc-9225-454e-8f9d-e2b0361d8943.png)
It also seems to be fine without setting.

**Comment by pjebs** [comment]
You can't unset it. A value of zero is not the same

**Comment by efectn** [comment]
> Hello can I jump in and help?

Sure. You can create a PR
