### ISSUE TITLE
🐛 [Bug]: Potential memory leak in Data map in session middleware

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2149]
### Bug Description

The session middleware contains a Data struct which contains a map.

I suspect it may leak according to this article: https://teivah.medium.com/maps-and-memory-leaks-in-go-a85ebe6e7e69

### How to Reproduce

Just a suspicion

### Expected Behavior

Just a suspicion

### Fiber Version

All

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by pjebs** [comment]
```go
func (d *data) Reset() {
	d.Lock()
	for key := range d.Data {
		delete(d.Data, key)
	}
	d.Unlock()
}
```

Perhaps the better solution is just to replace the map rather than delete each key.

**Comment by li-jin-gou** [comment]
refer to https://github.com/golang/go/issues/20135
