### ISSUE TITLE
🤗 [Question]: delete the file, but shows me The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by bigdududu** [gofiber/fiber#2165]
### Question Description

First, thanks very much to the fiber team. It's really an awesome framework. 
I'm trying to move my personal project to fiber, but I met an issue, when I'm trying to delete the files, got 
_**The process cannot access the file because it is being used by another process**_
here is my code:

```
func DeleteApiImageDelete(c *fiber.Ctx) error {
	var image *models.Image
	if err := c.BodyParser(&image); err != nil {
		return err
	}
	if err := os.Remove(fmt.Sprintf(".%v", image.Src)); err != nil {
		fmt.Println(err)
	}
	sqlite.DB.Unscoped().Delete(&image)
	return c.SendStatus(http.StatusOK)
}
```

but it works in my current web framework, is there anything I did wrong with it?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
do you also have a stacktrace ? who throws this error ?

**Comment by bigdududu** [comment]
I‘m not familiar with the trace, but it shows me something like this. something wrong I did?  I really want to solve this problem, and move my project to fiber.
 
`
error(*io/fs.PathError) *{Op: "remove", Path: "./sources/media/18007 LS3872W.jpg", Err: error(syscall.Errno) golang.org/x/sys/windows.ERROR_SHARING_VIOLATION (32)}
`

**Comment by ReneWerner87** [comment]
well the error says in any case that the file is still open somewhere

i.e. you should see if you edit it in the other places we don't see here now, but don't create it closed

another assumption is that you deliver the file by static middleware and it is still open by fasthttp, but this is unlikely

if the 2 assumptions were checked and you couldn't find anything then please find all places where you use the file or folder and push the code here 

or try to reduce the code to the minimum, so that we have a reproducible example, which we can also run

**Comment by bigdududu** [comment]
Thanks very much, I'll check all your mentioned and see if I can solve this issue, Thanks again

> well the error says in any case that the file is still open somewhere
> 
> i.e. you should see if you edit it in the other places we don't see here now, but don't create it closed
> 
> another assumption is that you deliver the file by static middleware and it is still open by fasthttp, but this is unlikely
> 
> if the 2 assumptions were checked and you couldn't find anything then please find all places where you use the file or folder and push the code here
> 
> or try to reduce the code to the minimum, so that we have a reproducible example, which we can also run

Thanks very much, I'll check all your mentioned and see if I can work it out. Thanks again

**Comment by ReneWerner87** [comment]
@bigdududu any progress on the topic?

**Comment by bigdududu** [comment]
still not,  this is my first module, no middleware, so there are no other places to use it. 
but I use this to serve my uploaded images， is this the problem with the media file?
`
app.Static("/", "./public")
`
and I'm trying to see if fasthttp uses it when deleting the image, whatever, I will find it, and move my project to fiber, I love this framework very much. There are lots of modules I could use for my projects.

Thanks again.

**Comment by bigdududu** [comment]
> @bigdududu any progress on the topic?

Hi, 

I'm trying to work it out by myself, but it seems I can't. attach all my code below: it still shows me  _**The process cannot access the file because it is being used by another process.**_, when trying to remove the image. but a similar code can run in my current framework, but I want to move to fiber. This issue confuse me for many days, could you please help me see if is there something wrong I did? Thanks very much.

```
func main() {
	settings.Init()

	sqlite.Init()

	engine := html.New(".", ".html")
	engine.Delims("[[", "]]")
	app := fiber.New(fiber.Config{
		Views: engine,
	})
	app.Use(compress.New(compress.Config{
		Level: compress.LevelBestSpeed,
	}))
	app.Static("/static", "./static")
	app.Static("/src", "./src")
	app.Static("/sources", "./sources")
	app.Get("/admin/image", func(c *fiber.Ctx) error {
		return c.Render("templates/image/image", fiber.Map{
			"meta_title": "Image",
		})
	})
	app.Post("/api/image/upload", func(c *fiber.Ctx) error {
		form, err := c.MultipartForm()
		if err != nil {
			return err
		}
		files := form.File["files"]
		for _, file := range files {
			sqlite.DB.FirstOrCreate(&models.Image{}, &models.Image{Name: file.Filename, Src: fmt.Sprintf("/sources/media/%v", file.Filename)})

			if err := c.SaveFile(file, fmt.Sprintf("./sources/media/%v", file.Filename)); err != nil {
				return err
			}
		}
		return c.SendStatus(http.StatusOK)
	})

	app.Get("/api/image/list", func(c *fiber.Ctx) error {
		var images []*models.Image
		var imageTotal int64

		page, err := strconv.Atoi(c.Query("page"))
		if err != nil {
			fmt.Println(err)
		}

		rowsPerPage, err := strconv.Atoi(c.Query("rowsPerPage"))
		if err != nil {
			fmt.Println(err)
		}
		filter := c.Query("filter")
		sqlite.DB.Model(&models.Image{}).Where("name LIKE ?", "%%"+filter+"%%").Count(&imageTotal).Limit(rowsPerPage).Offset((page - 1) * rowsPerPage).Order("id desc").Find(&images)
		data := make(map[string]interface{}, 2)
		data["images"] = images
		data["imageTotal"] = imageTotal
		return c.JSON(data)
	})

	app.Delete("/api/image/delete", func(c *fiber.Ctx) error {
		var image *models.Image
		if err := c.BodyParser(&image); err != nil {
			return err
		}
		if err := os.Remove(fmt.Sprintf(".%v", image.Src)); err != nil {
			// fmt.Println(err)
			fmt.Println(err)
		}
		sqlite.DB.Unscoped().Delete(&image)

		return c.SendStatus(http.StatusOK)
	})

	app.Listen(fmt.Sprintf("%s:%d", settings.Conf.Server.Host, settings.Conf.Server.Port))
}
```

**Comment by bigdududu** [comment]
> 

still can't delete the files. is it possible that caused by static cache_duration? I tried to change it into a negative, but still the same, is there anyone facing the same problem?

**Comment by liaohongxing** [comment]
https://github.com/gofiber/fiber/issues/1338

please refer to this issue @bigdududu

**Comment by bigdududu** [comment]
Thanks, @liaohongxing . It works well, after setting the static duration. Anyway, I'll move all my projects to fiber. Thanks again
