### ISSUE TITLE
🤗 [Question]: use vs group

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2166]
### Question Description

Is there any practical difference between `app.Use(prefix, MW1).Get(...)` and `app.Group(prefix, MW1).Get(...)`?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Yes, group returns an instance containing the prefix for all routes bound to that instance
