### ISSUE TITLE
🤗 [Question]: route get parameter

### ISSUE THREAD

**Issue by devbrisk** [gofiber/fiber#2170]
### Question Description

Is there a way to include the get parameter with type and optional character?
this way does not work
`:offset<int>?`

### Code Snippet (optional)

```go
User.Get("/favorites/:offset<int>?", user.Favorites)
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
think the combination of optional parameters and contrains is currently not covered

@efectn can you confirm this ? can we add the functionality ?
