### ISSUE TITLE
🐛 [Bug]: ctx.BodyParser isnt' working as expected

### ISSUE THREAD

**Issue by axrav** [gofiber/fiber#2174]
### Bug Description

According to docs, Ctx.BodyParser binds the request body to a struct,the behavior is not upto the mark when it is used,

- When the request body does'nt has the specific data, which is a member of struct
- When the request body has unknown members
in both above cases the expected behavior of BodyParser should be throwing an error, but it works normally without errors
![image](https://user-images.githubusercontent.com/77937681/198285352-1e9921b7-a321-4e21-9c0e-3db9282b2ec5.png)

### How to Reproduce

Trying with a simple post Request will work, I have provided the code snippet below, the issue can be reproduced with that,

Moreover to test with a post request,
`curl -X POST -H "Content-Type: application/json" --data "{\"name\":\"john\",\"pass\":\"doe\"}" localhost:3000`

### Expected Behavior

This should return an error as the struct should not be parsed because unknown members are there in request body, but it works without any error

### Fiber Version

 v2.39.0

### Code Snippet (optional)

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	app.Post("/", Testfxn)
	app.Listen(":3000")

}

type Resp struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

func Testfxn(c *fiber.Ctx) error {
	resp := new(Resp)
	if err := c.BodyParser(&resp); err != nil {
		panic(err)
	}
	fmt.Println("mail", resp.Email)
	fmt.Println("pass", resp.Password)
	return c.JSON(resp)

}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
where does it say that the body parser does validation ? 

the default configuration for our parser is that it reads empty records and ignores unknown keys and maps only the known ones
https://github.com/gofiber/fiber/blob/ff4602980a2a88b4a543641714716e7a348b3007/ctx.go#L59-L60


you are welcome to change the behavior by changing the parser options
https://docs.gofiber.io/api/ctx#setparserdecoder


if you want to validate your request data and make sure it throws an error when data is empty or does not match a format you are welcome to follow the validation guide
https://docs.gofiber.io/guide/validation

**Comment by axrav** [comment]
Even on changing behavior of parser, the outcome is same, it doesnt throws an error, 

Here's my main function,
according to it, sending unknown keys should throw an error

`func main() {
	app := fiber.New()
	fiber.SetParserDecoder(
		fiber.ParserConfig{
			IgnoreUnknownKeys: false,
			ZeroEmpty:         true,
		},
	)
	app.Post("/", Testfxn)
	app.Listen(":3000")

}`

**Comment by ReneWerner87** [comment]
ok

only now seen that you use json
this feature for setting is only for our parser which is used for form and multiform data

with json there is no configuration possibility

there is only the validation to use

**Comment by ReneWerner87** [comment]
it is not planned
pull requests with suggestions are of course welcome, as long as they are interesting for the whole community and fit the framework idea.
