### ISSUE TITLE
🤗 [Question]: Expose Fiber on the Internet

### ISSUE THREAD

**Issue by gandaldf** [gofiber/fiber#2177]
### Question Description

Regarding this old article by Filippo Valsorda: https://blog.cloudflare.com/exposing-go-on-the-internet/ I wonder if there is a way to apply these tips and settings to Fiber and if they make sense for it.
Sometimes I am asked to expose small / medium services directly on the internet so I wondered what were the best precautions to take.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
the clear recommendation is to expose the services via nginx or cloudflare, there are many examples for this in articles and the recipes

exposing the service would of course also work, but then you can't use the advantages of the http2/3 protocol, because fasthttp is not ready for them

**Comment by gandaldf** [comment]
Thank you, I am aware of the examples and the best practises but sometimes a company with small or no infrastructures at all asks you to put your software on their public server (with all due respect to http2/3).
So I'm asking if I can do something for this specific edge case.

**Comment by li-jin-gou** [comment]
Consider mainly what you would lose without the nginx proxy.😁
