### ISSUE TITLE
🐛 [Bug]: unsafeString2Bytes may not be future proof

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2180]
### Bug Description

https://github.com/gofiber/fiber/blob/master/utils/convert.go#L24
https://github.com/gofiber/fiber/blob/master/internal/fasttemplate/unsafe.go#L15

See: https://stackoverflow.com/questions/59209493/how-to-use-unsafe-get-a-byte-slice-from-a-string-without-memory-copy

The current implementations may not be as future proof as it could be according to the discussion in the link above.

They propose:
```go
func unsafeGetBytes(s string) []byte {
    if s == "" {
        return nil // or []byte{}
    }
    return (*[0x7fff0000]byte)(unsafe.Pointer(
        (*reflect.StringHeader)(unsafe.Pointer(&s)).Data),
    )[:len(s):len(s)]
}
```

### How to Reproduce

N/A

### Expected Behavior

N/A

### Fiber Version

N/A 

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
Agree with you. I think we should use recommend solution.

**Comment by ReneWerner87** [comment]
The initial functions were copies of the fasthttp functions, we should open a topic there too

Furthermore we should comment the line with the magic limit and determine this number outside on a constant one
