### ISSUE TITLE
🚀 [Feature]: Add custom tags to logger middleware

### ISSUE THREAD

**Issue by Skyenought** [gofiber/fiber#2187]
### Feature Description

I want to replace `switch` matching `tag` with `map[string]func()` matching `tag` before processing. This adds custom `tag` functionality.

This allows us to add custom tags,  but it is not thread-safe.

### Additional Context (optional)

[Source code](https://github.com/gofiber/fiber/blob/master/middleware/logger/logger.go#L196)

Pseudocode:
```go
type LogFunc func(buf *bytebufferpool.ByteBuffer, c *fiber.Ctx, w io.Writer, tag string) (int, error)

// TagMap use to storage how to log content when parse Tag.
var TagMap = map[string]LogFunc{
    TagReferer: func(buf *bytebufferpool.ByteBuffer, c *fiber.Ctx, w io.Writer, tag string) (int, error) {
		return buf.WriteString(c.Get(fiber.HeaderReferer))
    },
}

TagMap[TagTime] = func(buf *bytebufferpool.ByteBuffer, c *fiber.Ctx, w io.Writer, tag string) (int, error) {
	return buf.WriteString(timestamp.Load().(string))
}

// Loop over template tags to replace it with the correct value
_, err = tmpl.ExecuteFunc(buf, func(w io.Writer, tag string) (int, error) {
/* switch tag {
       case TagTime:
           return buf.WriteString(timestamp.Load().(string))
       case TagReferer:
	   return buf.WriteString(c.Get(fiber.HeaderReferer))
        ...
*/
  if logFunc, ok := TagMap[tag]; ok {
      return logFunc(buf, c, w, tag)
  } else {
       switch {
	   case strings.HasPrefix(tag, TagReqHeader):
	      return buf.WriteString(c.Get(tag[10:]))
	   // ...						
        }
   }
   return 0, nil
})
// ...
```

### Code Snippet (optional)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/internal/bytebufferpool"
	"github.com/gofiber/fiber/v2/middleware/logger"

	"io"
)

func main() {
	app := fiber.New()
	logger.TagMap["custom_tag"] = func(buf *bytebufferpool.ByteBuffer, c *fiber.Ctx, w io.Writer, tag string) (int, error) {
		return buf.WriteString("it is a custom tag")
	}
	buf := bytebufferpool.Get()
	defer bytebufferpool.Put(buf)
	app.Use(logger.New(logger.Config{
		Format: "${custom_tag}",
		Output: buf,
	}))
	app.Get("/", func(ctx *fiber.Ctx) error {
		return ctx.JSON(map[string]string{
			"message": "hello world",
		})
	})
	app.Listen(":3000")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
Okay, good idea
then please make it configurable in the configuration 

thread safe it will be if we allow it only at initialization or add other mechanisms

**Comment by Skyenought** [comment]
> Okay, good idea then please make it configurable in the configuration
> 
> thread safe it will be if we allow it only at initialization or add other mechanisms

ok, I will submit the code shortly, hopefully you can help me check for potential problems.
