### ISSUE TITLE
🤗 [Question]: in prefork mode, can i remove all mutexes for memory access?

### ISSUE THREAD

**Issue by ultperf** [gofiber/fiber#2189]
### Question Description

just curious, and to confirm. for prefork mode it is in single thread per process, so mutex is totally unnecessary right since memory cannot be shared.

is there any circumstances that i'm not foreseeing that mutex will be needed in prefork mode ( in regards with memory access and nothing over database etc )

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by efectn** [comment]
closed due to https://github.com/valyala/fasthttp/issues/1413#issuecomment-1302591027
