### ISSUE TITLE
🤔 Implement golang-security-action (action running gosec)

### ISSUE THREAD

**Issue by Ynniss** [gofiber/fiber#219]
**Is your feature request related to a problem?**
nope

**Describe the solution you'd like**
I'm actually working on a tiny github action named [golang-security-action](https://github.com/marketplace/actions/golang-security-action), which is basically running gosec.

I know that you already have a workflow file that use gosec, but i think using my "external" action is easier and more maintainable, since you'll just have to deal with the inputs you pass to the action, and the version of the action.

The action is still very young, i made several pre-release yesterday , and i'm close to the first stable release 0.1.0 .

What do you think about it ?

(btw i'm beginner on github actions, i'd love to have any feedbacks ! )

**Describe alternatives you've considered**

**Additional context**

**Comment by renanbastos93** [comment]
hey dude, already we have an action to run GoSec
https://github.com/gofiber/fiber/blob/master/.github/workflows/security.yml

**Comment by Ynniss** [comment]
Hi !

**Comment by renanbastos93** [comment]
Hi, my English is so so

Well, I think interesting about your approach. But I don't see gain with your approach to me are will the same benefits.

I believe that we should set a badge in readme.md info about workflow.

**Comment by Ynniss** [comment]
Indeed, the purpose is the same. For me, benefits are more on the "practical", "easy to use", "more maintainable" sides.

I'm not really familiar with badges, but i assume it indicates that the action succeeded ?

**Comment by renanbastos93** [comment]
Yes, the badges are to indicate the status of the action. Ok, it is "easy to use" I believe you but who maintenance from this [golang-security-action](https://github.com/marketplace/actions/golang-security-action) this action is very recent and it worries me a little. I prefer we maintenance will be made for community with contributors and members of fiber. 

So, I believe you made a good work I will be test your action.

**Comment by Ynniss** [comment]
Ok, i see.
That's true it's recent and i can understand your worries :) 

Thanks. Btw I made some stable releases during the last hour, you should be able to use the action without any problem.  Also feel free to contribute :+1:  .

**Comment by renanbastos93** [comment]
How nice, sorry but what is btw?

**Comment by Ynniss** [comment]
btw mean By the way :)

**Comment by Fenny** [comment]
Hi @Ynniss, it looks promising. But I think it needs a bit more testing and time before we will use it in production. Sounds good?

**Comment by Ynniss** [comment]
Hi ! Thanks for your feedback.

Yeah, i might re-open it, in the future ;)
