### ISSUE TITLE
🚀 [v3 Request]: v3 Router ideas

### ISSUE THREAD

**Issue by acidjazz** [gofiber/fiber#2190]
### Feature Description

Here are some code samples from discord to keep track of our ideas for the new router:

* Chained separated Middleware with routes

```go

Router.Get("/gated", controllers.Gated).Middleware(auth.Middleware)

Router.Middleware(auth.Middleware, func (router *fiber.Router) {
  router.Get("/me", AuthControllers.me)
  router.Get("/user", controllers.UserIndex)
  router.Match([]{"Put", "Patch"}, "/user/:user", controllers.UserUpdate)
}).Name("Authenticated Routes")
```
 
* Multiple methods in a single call
 
```go
Router.Match([]{"Put", "Patch"}, "/user/:user", controllers.UserUpdate)
Router.Any("/catchall", controllers.CatchAll)
```

* Grouping makes more sense as Prefix - since that is reuqired https://docs.gofiber.io/guide/grouping

```go
const v1 = Router.Prefix("/v1")
```

* Maybe a group can be a callback

```go
Router.Middleware(middlewares.V1Middleware).Prefix("/v1", func (router *fiber.Router) {
  router.Get("/endpoint", v1conrtollers.Endpoint)
})
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
Can you provide examples with expressjs code showing this feature there
so that we can match the naming accordingly

important for me is not to deviate far from the wordings and structure of express in the router, so that we are still close to the expressjs code and thus make it easier to get started for everyone

**Comment by ReneWerner87** [comment]
we have created another concept #2202 as an idea with which this is possible in a contribution package 

so i will close this issue
