### ISSUE TITLE
🐛 [Bug]: When multiple files use the same layout and define the same template, the last file is rendered on any request (Go templates)

### ISSUE THREAD

**Issue by Baldomo** [gofiber/fiber#2191]
### Bug Description

I have to say this is a weird one. When using Go's template engine, only the last file in `views/` get rendered. The file structure is as follows:

```
.
├── views
│   ├── layouts
│   │   └── main.html
│   ├── index.html
│   └── z.html
└── main.go
```

where `main.html` contains the following (note that the bug arises even when not using `{{ embed }}`, but including the layout template with `{{ template "views/layouts/main" }}` in the index template):

```html
<!DOCTYPE html>
<html>

<head>
  <title>Main</title>
</head>

<body>
  {{ embed }}

  {{ template "content" . }}
</body>

</html>
```

while `index.html` and `z.html` are simply

```html
{{ define "content" }}
<div>This is index.html</div>
{{ end }}
```

and

```html
{{ define "content" }}
<div>This is z.html</div>
{{ end }}
```

Running `go run main.go` results in the following:

![image](https://user-images.githubusercontent.com/17025402/199741122-4aade7e9-e077-4be8-a156-aabe35a2dd97.png)

Removing `z.html` or renaming it to something like `a.html` (so that `index.html` comes last in the file list) fixes the problem but that's not a solution. Fiber should render the requested template, not `z.html` (which should never even be served since it's never even mentioned in the handler).

I think something like this... bug? or whatever it is can be a security problem in some circumstances since it basically leaks template data.

### How to Reproduce

1. Run `main.go`
2. Open browser
3. Profit? Only the last template in the `views/` folder is rendered.

### Expected Behavior

Fiber should render the correct template instead of the last file in the folder.

### Fiber Version

v2.39.0

### Code Snippet (optional)

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/template/html"
)

func main() {
	engine := html.New("./views", ".html")

	app := fiber.New(fiber.Config{
		Views: engine,
	})

	app.Get("/", func(c *fiber.Ctx) error {
		return c.Render("index", nil, "layouts/main")
	})

	log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
This is known and an expected behavior

For performance reasons we parse all templates in the folder which would be specified in the view engine

So you should avoid creating definitions with the same names and use the embed tag

**Comment by Baldomo** [comment]
Thanks for the quick response! If it's for performance then I suppose I get it, but it should be documented because it's a project-specific decision and can generate a lot of confusion, not to add that it makes templates quite redundant because of the "same name renders the last one" thing. Thank you for your time anyways.
