### ISSUE TITLE
🚀 [Feature]: cluster aware / enabled / resilient HA web servers

### ISSUE THREAD

**Issue by hiqsociety** [gofiber/fiber#2193]
### Feature Description

is there a cluster aware / enabled, resilient HA web server example?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the feature

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
@hiqsociety can you please link more media on the topic and also give examples from other frameworks to increase the understanding of the question/feature

**Comment by ReneWerner87** [comment]
closed due to lack of information

if this information is provided, we can reopen the feature request
