### ISSUE TITLE
🐛 [Bug]: config [DisableStartupMessage] was merged by wrong code

### ISSUE THREAD

**Issue by DaoshunShi** [gofiber/fiber#2198]
### Bug Description

The PR changes DisableStartupMessage #425, but the commit was covered by commit 3470e8d.

Now, version 2.39.0,  the DisableStartupMessage will not print out the «Fiber» ASCII art and listening address.

### How to Reproduce

1. Set DisableStartupMessage to **true**

### Expected Behavior

**«Fiber» ASCII art and listening address not print**, while it was supposed to **not print out the «Fiber» ASCII art**

### Fiber Version

v.2.39.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
or should the ascii graphic and the output of the address be separated?

Believe one has decided to output nothing in the case

**Comment by efectn** [comment]
Fiber v2 doesn't have ASCII art on startup message. I've not used v1 before but it seems v1 has ASCII art https://github.com/gofiber/fiber/blob/v1/app.go#L660

**Comment by DaoshunShi** [comment]
In 1.10.1, it would print **Started listening on**, ignore **DisableStartupMessage**.

Now, if i set DisableStartupMessageto true, then there is no message for what port the server is listening on.

**Comment by ReneWerner87** [comment]
correct, because this output belongs to the startup message and has been deactivated

if you want to have the port which you set yourself before, you should just output it yourself

the current behavior is intentional for most users

**Comment by DaoshunShi** [comment]
Thanks for explaining.
