### ISSUE TITLE
🚀 [v3 Feature Request]: Grouping - altered middleware behavior

### ISSUE THREAD

**Issue by acidjazz** [gofiber/fiber#2200]
### Feature Description

* V2 Grouping should be renamed Prefixing - and solely the ability to define a prefix, not actual grouping
* Grouping should work somewhat how V2 Grouping works, but does not require a prefix

ex: defining a group

```go
authRoutes := app.Group(middleware.Auth)
authRoutes.Get("/me", controllers.AuthMe)
```

ex: defining a group with a prefix
```go
authRoutes := app.Group(middleware.Auth).Prefix("/auth")
authRoutes.Get("/me", controllers.AuthMe)
```

* CHANGE: Grouped middleware should be given the context of each individual route, not the groups route 

```go
package middleware

func Auth(c *fiber.Ctx) {
  c.Route() // should be /auth/me - NOT /auth (currently in v2)
}
```

### Other Notes

* v2 grouping currently adds routes, a GET for each group - this is not neccessary
* All middleware in groups should only executed w/ the exact context of the routes defined w/in the group

### other ideas of grouping

```go
app.Prefix("/auth").Group(middleware.Auth, func(app *fiber.App) {
  app.Get("/me", controllers.AuthMe)
})
```

> I like the 1st example more - just more ideas

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by splashsky** [comment]
+1, the current grouping behavior is current a major roadblock in my own project at the moment. Being able to simply group routes with a middleware without prefix collision would be an immediate fix to my problems.

**Comment by ReneWerner87** [comment]
we have created another concept #2107 2202 as an idea with which this is possible in a contribution package

so i will close this issue
