### ISSUE TITLE
🤔 [Question]: Why are some external packages copied into the internal package here?

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2208]
### Question Description

For example `internal/bytebufferpool` is a copy of https://github.com/valyala/bytebufferpool. Why not just import the external package instead of tracking its source? This'd make it so much easier to update dependencies through go mod.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by leonklingele** [comment]
I see that this has improved as part of the v3 migration. A copy of the [`schema` package](https://github.com/gorilla/schema) however still seems to reside here: https://github.com/gofiber/fiber/tree/v3-beta/internal/schema

**Comment by leonklingele** [comment]
Also, https://github.com/gofiber/fiber/tree/24fd1656606a2554b8416ac4bffb66324b0dc743/internal/storage/memory seems to be a copy of https://github.com/gofiber/storage/tree/a1556f322a7b86fd875a83a5368281ba93449a6d/memory.

**Comment by efectn** [comment]
> I see that this has improved as part of the v3 migration. A copy of the [`schema` package](https://github.com/gorilla/schema) however still seems to reside here: https://github.com/gofiber/fiber/tree/v3-beta/internal/schema

Upstream schema repo has some bugs we've solved in Fiber and it's not under active maintenance. https://github.com/gofiber/fiber/pull/1424

Btw we plan to remove it in v3. We will prefer more performant binding way https://github.com/gofiber/fiber/pull/2006

**Comment by ReneWerner87** [comment]
accurate 

is that enough for you to explain, can I close the issue?

**Comment by leonklingele** [comment]
Yeah, thank you.
