### ISSUE TITLE
🐛 [Bug]: dictpool is deprecated

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2209]
### Bug Description

https://github.com/savsgio/dictpool was deprecated a couple of weeks ago. A copy of it is tracked here: https://github.com/gofiber/fiber/tree/e388e0edb3c6d4bdbfa41e8d533e1f4bd734404d/internal/dictpool

### How to Reproduce

-

### Expected Behavior

-

### Fiber Version

latest

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
Closed by https://github.com/gofiber/fiber/commit/73b43cc93e21dd8bff2af2cd6ce98af422b4e877

**Comment by leonklingele** [comment]
Can this be backported to v2 as well?

**Comment by efectn** [comment]
> Can this be backported to v2 as well?

Sounds OK to me
