### ISSUE TITLE
🤔 [v3 Question]: Why are some middlewares of the gofiber org not part of v3?

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2212]
### Question Description

Some of the unarchived middlewares found here (https://github.com/orgs/gofiber/repositories) are not part of v3, e.g. `websocket`. Why is that?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by efectn** [comment]
It has extra dependencies

**Comment by leonklingele** [comment]
I see, makes sense.
