### ISSUE TITLE
🐛 [Bug]: Recover middleware doesn't catch Panic

### ISSUE THREAD

**Issue by gandaldf** [gofiber/fiber#2230]
### Bug Description

I was using a third-party package (github.com/go-ping/ping) to ping an IP address; I mistakenly set Timeout parameter to 0 and it crashed the Ticker inside the package.
I thought that Recover middleware would have keep my app running but it didn't.

### How to Reproduce

Try this example to reproduce the behavior:

```
package main

import (
	"fmt"
	"runtime"

	"github.com/go-ping/ping"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/recover"
)

func main() {
	app := fiber.New()

	// Default middleware config
	app.Use(recover.New())

	app.Get("/", func(c *fiber.Ctx) error {
		pinger, err := ping.NewPinger("127.0.0.1")
		if err != nil {
			return err
		}

		if runtime.GOOS == "windows" {
			pinger.SetPrivileged(true)
		}

		//pinger.Timeout = 5 * time.Second // this is right
		pinger.Timeout = 0 // this is bad and crash app
		pinger.Count = 5
		pinger.Run()

		stats := pinger.Statistics()
		msg := fmt.Sprintf("ping: %d sent, %d received, %.1f%% loss", stats.PacketsSent, stats.PacketsRecv, stats.PacketLoss)

		return c.SendString(msg)
	})

	app.Listen(":3000")
}

```

### Expected Behavior

Recover middleware should catch the Panic e keep app running.

### Fiber Version

v2.40

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by li-jin-gou** [comment]
because panic occurs in other goroutines.

**Comment by li-jin-gou** [comment]
> Uhm ok... I suspected it was somenthing like that. So the only way to fully recover an app is using an OS service or suprevisor?

Yes or ping caught this panic.
