### ISSUE TITLE
🐛 [Bug]: Logger bytesSent incompatible with SSE

### ISSUE THREAD

**Issue by Khez** [gofiber/fiber#2232]
### Bug Description

After activating `bytesSent` on the logger, all SSE endpoints stop streaming.

It most likely caused by the logger attempting to read the full body length, consuming data before it is sent the client.

https://github.com/gofiber/fiber/blob/master/middleware/logger/tags.go#L91

### How to Reproduce

1. Follow the instructions on https://github.com/gofiber/recipes/tree/master/sse
2. Check SSE route, confirm it streams
2. Add logger middleware https://docs.gofiber.io/api/middleware/logger
3. Add sure the format contains `${bytesSent}` as shown under https://docs.gofiber.io/api/middleware/logger#constants
4. Check SSE route again, confirm it stops streaming

### Expected Behavior

SSE Should continue streaming.

### Fiber Version

2.40.1

### Code Snippet (optional)

```go
// @see https://github.com/gofiber/recipes/tree/master/sse
// @see https://docs.gofiber.io/api/middleware/logger#constants
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by li-jin-gou** [comment]
I think it can be used .

Similar to
```
	TagBytesSent: func(ctx context.Context, c *app.RequestContext, buf *bytebufferpool.ByteBuffer) (int, error) {
		return appendInt(buf, c.Response.Header.ContentLength())
	},
```

**Comment by Khez** [comment]
When streaming you are using `Transfer-Encoding: chunked`, which makes `Content-Length: -1`.

https://github.com/valyala/fasthttp/blob/master/header.go#L236

**Comment by li-jin-gou** [comment]
> When streaming you are using `Transfer-Encoding: chunked`, which makes `Content-Length: -1`.
> 
> https://github.com/valyala/fasthttp/blob/master/header.go#L236

yes

**Comment by li-jin-gou** [comment]
I found that contentlenth is set after the handler, so that the middleware cannot get it from the header without using len(body).😩

**Comment by li-jin-gou** [comment]
Is it possible to set the length directly to 0 when it is determined to be streaming? I think it's OK.
