### ISSUE TITLE
🐛 [Bug]: Mounted subapps don't work correctly if parent app attached additional middlewares after mounting (v2.40.1 bug)

### ISSUE THREAD

**Issue by defshift** [gofiber/fiber#2233]
### Bug Description

If fiber app is mounting some subapps, routes from these subapps are not matching if the parent app added middlewares after mounting.
See the code snippet above to reproduce the problem. `GET /world` always returns `404`. **v2.39.0** handled this case correctly.

### How to Reproduce

1. Run the code snippet
2. Request `GET /world` 
3. Get 404

### Expected Behavior

`GET /world` should return 200 'Hello'

### Fiber Version

v2.40.1

### Code Snippet (optional)

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Get("/hello", hello)

	// subApp routes never matched if '404 handler' midlleware exists
	subApp := fiber.New()
	subApp.Get("/world", func(c *fiber.Ctx) error {
		return c.SendString("World!")
	})

	app.Mount("/", subApp)

	// !!! This handler breaks the /world route now
	// 404 Handler
	app.Use(func(c *fiber.Ctx) error {
		return c.SendStatus(404) // => 404 "Not Found"
	})

	log.Fatal(app.Listen(":3000"))
}

// Handler
func hello(c *fiber.Ctx) error {
	return c.SendString("Hello!")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
Fiber v2.32.0 and up support adding 404 handling by customizing the error handler. You can take a look https://docs.gofiber.io/extra/faq#how-do-i-handle-custom-404-responses

I'll also think how to fix the problem.

**Comment by ReneWerner87** [comment]
unfortunately you are right and we have to do some rebuilding

the problem is that the routing tree has wrong positions in our routing tree because we don't remember at what time the mount command was executed

because we wanted to allow routes to be added later, we moved the merge to the start of the app, but currently we don't know where the mount command was executed

we already have some ideas and will try to fix this in the next release

**Comment by andersryanc** [comment]
A similar but slightly different use case which is also effected by this issue. In this use case, I'm trying to add authentication to groups of routes.

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func findUser() map[string]interface{} {
	// actually lookup the user
	return nil
}

func requireAuth(c *fiber.Ctx) error {
	u := findUser()

	if u == nil {
		return c.SendStatus(fiber.StatusForbidden)
	}

	c.Locals("user", u)
	return c.Next()
}

func main() {
	app := fiber.New()

	lists := fiber.New()
	lists.Get("/", func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusOK)
	})

	users := fiber.New()
	users.Get("/", func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusOK)
	})

	api := app.Group("/api")

	api.Get("/foo", func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusOK)
	})

	api.Mount("/lists", lists)

	authorized := api.Group("/", requireAuth)

	authorized.Get("/bar", func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusOK)
	})

	authorized.Mount("/users", users)

	api.Get("/baz", func(c *fiber.Ctx) error {
		return c.SendStatus(fiber.StatusOK)
	})

	log.Fatal(app.Listen(":3000"))
}
```

I found that this used to work up until v2.40.0 was released. Here is a list of the endpoints and responses:

```
# what I would have expected to happen from reading the code
GET /api/foo -> 200
GET /api/lists -> 200
GET /api/bar -> 403
GET /api/users -> 403
GET /api/baz -> 200

# actual behavior v2.39.0 and below
GET /api/foo -> 200
GET /api/lists -> 200
GET /api/bar -> 403
GET /api/users -> 403
GET /api/baz -> 403

# actual behavior v2.40.0 and above
GET /api/foo -> 200
GET /api/lists -> 403
GET /api/bar -> 403
GET /api/users -> 403
GET /api/baz -> 403
```

Is there a different way this is meant to be done? Or an actual bug with the way I'm trying to use `.Group()` and `.Mount()`?
