### ISSUE TITLE
🤗 [Question]: I already follow the code in the docs about SetParserDecoder but doesn't work

### ISSUE THREAD

**Issue by hs-dev-web** [gofiber/fiber#2234]
### Question Description

How to use SetParserDecoder()?

when should I declare fiber.SetParserDecoder()?

before or after `app := fiber.New()`?

why is it still can't parse the date and throw an error instead, something like this:

> "parsing time \"\\\"2022-11-10\\\"\" as \"\\\"2006-01-02T15:04:05Z07:00\\\"\": cannot parse \"\\\"\" as \"T\""

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  customtypes.RegisterFiberCustomParser()

  app := fiber.New()

  log.Fatal(app.Listen(":3000"))
}

========================================================

package customtypes

import (
	"fmt"
	"time"
	"reflect"

	"database/sql"
	"database/sql/driver"
	"github.com/gofiber/fiber/v2"
)

type Date time.Time

func (date *Date) Scan(value interface{}) (err error) {
	nullTime := &sql.NullTime{}
	err = nullTime.Scan(value)
	*date = Date(nullTime.Time)
	return
}

func (date Date) Value() (driver.Value, error) {
	y, m, d := time.Time(date).Date()
	return time.Date(y, m, d, 0, 0, 0, 0, time.Time(date).Location()), nil
}

// GormDataType gorm common data type
func (date Date) GormDataType() string {
	return "date"
}

func (date Date) GobEncode() ([]byte, error) {
	return time.Time(date).GobEncode()
}

func (date *Date) GobDecode(b []byte) error {
	return (*time.Time)(date).GobDecode(b)
}

func (date Date) MarshalJSON() ([]byte, error) {
	return time.Time(date).MarshalJSON()
}

func (date *Date) UnmarshalJSON(b []byte) error {
	return (*time.Time)(date).UnmarshalJSON(b)
}

// String() returns the time in string
func (date *Date) String() string {
	t := time.Time(*date).String()
	return t
}

func RegisterFiberCustomParser() {
	// Register the converter for Date type format as 2006-01-02
	var timeConverter = func(value string) reflect.Value {
		fmt.Println("timeConverter", value)
		if v, err := time.Parse("2006-01-02", value); err == nil {
			return reflect.ValueOf(v)
		}
		return reflect.Value{}
	}

	customDate := fiber.ParserType{
		Customtype: Date{},
		Converter:  timeConverter,
	}

	// Add setting to the Decoder
	fiber.SetParserDecoder(fiber.ParserConfig{
		IgnoreUnknownKeys: true,
		ParserType:        []fiber.ParserType{customDate},
		ZeroEmpty:         true,
	})
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
refer to https://docs.gofiber.io/api/ctx#setparserdecoder

**Comment by ReneWerner87** [comment]
> This works for form posts only. What about json posts?

![image](https://user-images.githubusercontent.com/7063188/226451730-87abe82a-e1ff-4069-85f7-a93a11de5bad.png)
https://docs.gofiber.io/api/ctx#bodyparser

should also work with json, maybe you have to add the annotation for json in your struct

**Comment by SharkFourSix** [comment]
I do have the json annotation. I put a breakpoint on my parser/converter and it's never. Hit.

But I also noticed this:

![image](https://user-images.githubusercontent.com/18681730/226454181-c99266e5-6e5d-461c-84ce-27310e02e536.png)

There is no ```json``` in the list of tags
