### ISSUE TITLE
🤗 [Question]:  I want to create new storage, but i have one question about tests

### ISSUE THREAD

**Issue by 0xdeface** [gofiber/fiber#2235]
### Question Description

I want to create nats jetstream storage. In my project we are using nats as bus and as kv. nats is modern cloud opensource software. I studied another storage and i saw than they use some unclear hosts and ports without testcontainers or same software.  Can i use testcontainers in my test or what host and port i should use?

### Code Snippet (optional)

```go
// for example 
// ConfigDefault is the default config for redis
var ConfigDefault = Config{
	Host:      "127.0.0.1",
	Port:      6379,
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
Yes and you can refer to https://github.com/gofiber/storage/tree/main/.github/workflows

**Comment by mdelapenya** [comment]
Sorry to comment on a closed ticket, but I found this randomly today. Yes, you can use testcontainers-go in the storage layers, please see https://github.com/gofiber/storage/issues/1507
