### ISSUE TITLE
🐛 [Bug]: Static file net::ERR_CONTENT_LENGTH_MISMATCH after update fasthttp

### ISSUE THREAD

**Issue by smalloff** [gofiber/fiber#2244]
### Bug Description

My CSS file is truncated. Therefore, an error will occur - net::ERR_CONTENT_LENGTH_MISMATCH.
File size 5 kb.
If the file is small (~ 1kb), then there is no problem.

The error occurs only when downloading files with the CSS extension!

OS: Ubuntu 18, Windows 10
Fiber version: v2.40.1

**This bug is reproduced on fasthttp version - github.com/valyala/fasthttp v1.42.0**
On version v1.41.0 , there are no problems.

### How to Reproduce

1) Create a fiber project and launch **go get -u**

app := fiber.New()
app.Static("/", "./public")
app.Listen(":3000")

2) Make sure go.mod contains the required version of fasthttp - v1.42.0
3) Place a large css file in the public folder and launch server.
4) Try to open the file in a browser
5) See console or network tab.

### Expected Behavior

Give the browser the entire file.

### Fiber Version

2.40.1

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by MindMayhem** [comment]
Agree,

`Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH` on random static files (css/js/img)

**Comment by lne-io** [comment]
I am having this issue with WEBP images. Before upgrading to gofiber v2.40.1 there was no issue. Request shows that transferred content is less than `Content-length`

**Comment by MindMayhem** [comment]
@lne-io problem was in multi-range support in **fasthttp**, currently it reverted commits in last version, just update **fasthttp** in your **go.mod** to v1.43.0

**Comment by smalloff** [comment]
@lne-io, Yes. Indeed, the problem was on all files. I made a mistake when looking for a bug and made the wrong conclusion. Now everything is fixed. Just update fasthttp.

**Comment by byene0923** [comment]
@smalloff @lne-io  hello, i'm the coder of multi-range support in fasthttp, sorry to produce the bug. i check that file length in (4096, 8192) will cause this bug. is that any other cases will cause this bug?
