### ISSUE TITLE
🤗 [Question]: Can't receive bigger body than ~64KB

### ISSUE THREAD

**Issue by Kibergx** [gofiber/fiber#2248]
### Question Description

I am aware there is a BodyLimit option in the API, the default is 4MB, I also set this 4MB to myself, not helped.

When I am sending to my Fiber server a bigger body than 64KB the receive fails. If this happens even my app.Post function is not called.

Javascript only saying Failed to fetch, in the Chrome devtools network tab I see there is no response from the server (no headers, nothing). The biggest data I could receive is around 63.9KB, so I am gussing the limit is 64KB for some reason.

From my javascript I am sending binary data (content-type: application/octet-stream).

How can I solve this problem?
Thank you!

### Code Snippet (optional)

```go
func main() {
	fmt.Println("Hello, World!")

	app := fiber.New(fiber.Config{
		BodyLimit: 4 * 1024 * 1024, // this is the default limit of 4MB
	})

	//**** HTTP
	app.Static("/", "../AnyShape")
	app.Post("/api", func(c *fiber.Ctx) error {
          fmt.Println("I can't see this if the Body bigger than 64KB :(")
        }
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Can you please prepare a curl request and share and the output you get when executing the curl request against the server endpoint with the data

**Comment by Kibergx** [comment]
WIth curl it worked. I check my javascript code again, I set the keepalive false from true in the fetch function. Now it is working. I don't understand why keepalive causing a problem.. Thank you for your suggestion to try with curl.
