### ISSUE TITLE
V3 🚀 Feature: Drop "XHR" func from Ctx interface

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2250]
### Feature Description

The new Ctx interface requires a [`XHR() bool`](https://github.com/gofiber/fiber/blob/77d14848b805ce3e27c3034f2a353ea66d597dc4/ctx_interface.go#L318) func.
This is a simple header lookup which I suppose is barely even used. As the interface is already quite overloaded, we should try to make it easier to satisfy by removing such simple functions.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
Not sure about this

I think expressjs is also providing this kind of function

**Comment by ReneWerner87** [comment]
https://expressjs.com/en/5x/api.html#req.xhr 
since we want to be close to the express api and this method is available there i would leave the removal for now

because it offers an added value by supporting the builder of the api
