### ISSUE TITLE
🐛 [Bug]: Fiber route path definition with regex which contains comma will make regex invalid

### ISSUE THREAD

**Issue by benz9527** [gofiber/fiber#2251]
### Bug Description

I try to build a route path with regex like below:
```go
var app *fiber.App
// skip some initialize codes...
app.Group(`/xxx/:csName<regex(^[a-z0-9]([a-z0-9-]{1,61}[a-z0-9])?$)>`, func(ctx *fiber.Ctx) error {
  return ctx.Next()
})
```

When I debugged into fiber path source code, I found that the regex constraint data was splitted by comma into 2 elements of array.
![image](https://user-images.githubusercontent.com/109717800/205207124-ab203551-0e22-456f-bb2e-42d90399bfb7.png)

![lQLPJx-Y5NpxjL7NAXHNBZmwY5HbWrX5U5UDhdDh78CMAA_1433_369](https://user-images.githubusercontent.com/109717800/205207368-148b0afb-7ad8-4534-a54f-8099c8b51eda.png)

Then the go built-in regex package must compile with only the first element.
![lQLPJxyppsmYOk7Mkc0Ej7BoJK1tCHWCiAOFz1RTwIIA_1167_145](https://user-images.githubusercontent.com/109717800/205207276-cd4636e6-3876-40a0-8b1e-73c7ad647343.png)

### How to Reproduce

1.  Please follow below code example to define a route path with regex:
```go
var app *fiber.App
// skip some initialize codes...
app.Group(`/xxx/:csName<regex(^[a-z0-9]([a-z0-9-]{1\,61}[a-z0-9])?$)>`, func(ctx *fiber.Ctx) error {
  return ctx.Next()
})
```

### Expected Behavior

I wish the regex compile with correct pattern string which I have defined before like `^[a-z0-9]([a-z0-9-]{1,61}[a-z0-9])?$` instead of a part of it  as `^[a-z0-9]([a-z0-9-]{1`.

### Fiber Version

v2.40.1

### Code Snippet (optional)

```go
func main() {
  var app *fiber.App
// skip some initialize codes...
app.Group(`/xxx/:csName<regex(^[a-z0-9]([a-z0-9-]{1,61}[a-z0-9])?$)>`, func(ctx *fiber.Ctx) error {
  return ctx.Next()
})
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
Can you try to put `\\` before comma

**Comment by benz9527** [comment]
> Can you try to put `\\` before comma

![lQLPJxkHPRANag7NA0nNBRuwunFUyyrymk4Dhg0qvkBVAA_1307_841](https://user-images.githubusercontent.com/109717800/205239378-821283bb-07eb-44c1-951f-570ebc16f4bc.png)

![lQLPJxgkxkNAfo7M2c0D5LDFp2B1sGffnwOGDUlIgEcA_996_217](https://user-images.githubusercontent.com/109717800/205239394-fe2e6c41-6854-4f3e-8b2d-c4183d6cb9b6.png)

It is not a real workable regular expression for me.
```
^[a-z0-9]([a-z0-9-]{0\\,61}[a-z0-9])?$
```
![image](https://user-images.githubusercontent.com/109717800/205239864-7913bf43-6960-41dc-983b-06bd95d8ec92.png)

**Comment by efectn** [comment]
> > Can you try to put `\\` before comma
> 
> ![lQLPJxkHPRANag7NA0nNBRuwunFUyyrymk4Dhg0qvkBVAA_1307_841](https://user-images.githubusercontent.com/109717800/205239378-821283bb-07eb-44c1-951f-570ebc16f4bc.png)
> 
> ![lQLPJxgkxkNAfo7M2c0D5LDFp2B1sGffnwOGDUlIgEcA_996_217](https://user-images.githubusercontent.com/109717800/205239394-fe2e6c41-6854-4f3e-8b2d-c4183d6cb9b6.png)
> 
> It is not a real workable regular expression for me.
> 
> ```
> ^[a-z0-9]([a-z0-9-]{0\\,61}[a-z0-9])?$
> ```
> 
> ![image](https://user-images.githubusercontent.com/109717800/205239864-7913bf43-6960-41dc-983b-06bd95d8ec92.png)

Will check it. You can also send a PR if you have an idea to fix it
