### ISSUE TITLE
🚀 Feature: Move all tests to *_test package

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2252]
### Feature Description

In order for tests to only test exported functionality, all tests should be moved to a `_test` package.

E.g. tests with a package of `package fiber` should move to `package fiber_test` so they can no longer access private, unexported internals of the `fiber` package.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by li-jin-gou** [comment]
refer to https://stackoverflow.com/questions/19200235/golang-tests-in-sub-directory

**Comment by leonklingele** [comment]
@li-jin-gou what do you mean?

**Comment by li-jin-gou** [comment]
> @li-jin-gou what do you mean?

Paste a similar discussion

**Comment by ReneWerner87** [comment]
Sorry but I lay the current way of testing and could not yet see any negative aspects of this procedure

**Comment by leonklingele** [comment]
Would you accept a PR moving the package definition of all `_test.go` files to their respective `_test` version?

The benefit of doing this is that we do not fiddle around with any internals on accident in the test files.

**Comment by ReneWerner87** [comment]
i know that sometimes we also test internal functionalities to test deep units, which otherwise could be tested with much too much effort via the public method.

don't know if this is such a good idea, we could start with it, but should not limit ourselves completely

sometimes it can make sense to have more possibilities in testing
