### ISSUE TITLE
🚀 Feature: Make all tests run using "t.Parallel()"

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2254]
### Feature Description

In order to speed up test execution, all test funcs should make a call to `t.Parallel()`. This should be safe to implement as I have seen no tests where this might result in a data race so far.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by gaby** [comment]
Excellent idea, I can work on this one.
