### ISSUE TITLE
🐛 [Bug]: Status Code returns 405 (Method not allowed) instead of 404

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2266]
### Bug Description

1. I have some defined PATCH routes
2. When I make a request to an undefined route, I get a response back of 405 (Method Not allowed)
3. It should return a 404 back by default. 405 doesn't seem to make sense.

### How to Reproduce

Create some PATCH routes.
Make a request for an undefined route.

### Expected Behavior

Return 404 (not found). That seems more appropriate.

### Fiber Version

Latest

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by li-jin-gou** [comment]
this is example:
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Patch("/ping", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})

	log.Fatal(app.Listen(":3000"))
}

```

- it will returns 404 when using curl http://127.0.0.1:3000/demo and meets expectations.
- it will return  405  when using curl http://127.0.0.1:3000/ping with use http get method and  meets expectations.

**Comment by pjebs** [comment]
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Patch("/ping", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})

	app.Get("/*", func(c *fiber.Ctx) error {
		return c.SendString("Got here")
	})

	log.Fatal(app.Listen(":3000"))
}
```

When I make request for `PATCH: http://127.0.0.1:3000/xxxx`, I get status of 405.

I understand your logic. But I don't see **explicit** guidance in https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405

I wonder what other frameworks do including express.js.

**Comment by li-jin-gou** [comment]
Because the use of /* matches all routes starting with /.

**Comment by pjebs** [comment]
```

const express = require('express')
const app = express()
const port = 3000

app.patch('/ping', (req, res) => {
  res.send('Hello World!')
})

app.get('/*', (req, res) => {
  res.send('Got here')
})

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
})
```

Express produces 404 for `PATCH: http://127.0.0.1:3000/xxxx`

**Comment by li-jin-gou** [comment]
The same problem occurs with express.js and refer to https://github.com/expressjs/express/issues/1895,
