### ISSUE TITLE
🐞 static files with uppercase letters in filename are not served

### ISSUE THREAD

**Issue by y21** [gofiber/fiber#227]
**Fiber version/commit**
v1.8.31

**Issue description**
Files that have an uppercase letter in their filename are not served. My file structure:
```
- [project root]
    - main.go
    - public
        - js
            - A.js
```
![image](https://user-images.githubusercontent.com/30553356/76685809-d8c00d00-6616-11ea-85cd-563fa9678718.png)

**Expected behavior**
The file should be sent to the client

**Steps to reproduce**
1.) Create a file with an uppercase letter in its filename
2.) Run the code below
3.) Send request to `/js/<filename>.js`

**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  app.Static("/js", "./public/js")
  app.Listen(3000)
}
```

**Comment by Fenny** [comment]
This should be fixed in `v1.8.32` https://github.com/gofiber/fiber/releases/tag/v1.8.32
Feel free to re-open this issue if you still have problems regarding this issue.
