### ISSUE TITLE
🤗 [Question]: After the timeout middleware is used, the recover middleware becomes invalid

### ISSUE THREAD

**Issue by Tristin-C** [gofiber/fiber#2272]
### Question Description

Before using timeout middleware, recover can capture panic normally, but after I add timeout middleware, obviously panic will not be captured or prompted, but will wait until timeout

![image](https://user-images.githubusercontent.com/82650741/208067900-4d474f32-284e-4cab-a559-c7248c00b1b0.png)

### Code Snippet (optional)

```go
package main

import (
	"testing"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/timeout"
)

func TestXxx(t *testing.T) {
	app := fiber.New()
	api := app.Group("/v1.0")
	api.Use(recover.New(recover.Config{
		EnableStackTrace: true,
	}))

	api.Post("", timeout.New(func(c *fiber.Ctx) error {
		panic("this is a panic")
	}, time.Millisecond*1000))
	app.Listen(":8080")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@fufuok @hakankutluay can you support here

**Comment by hakankutluay** [comment]
Could you please check if your fiber version is greater than [v2.38.1](https://github.com/gofiber/fiber/releases/tag/v2.38.1)

Curl:
```shell
curl --location --request POST 'http://localhost:8080/v1' -i

HTTP/1.1 500 Internal Server Error
Date: Fri, 16 Dec 2022 11:04:00 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 15

this is a panic%


```

Test code:

```go
package main

import (
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"github.com/gofiber/fiber/v2/middleware/timeout"
)

func main() {
	app := fiber.New()
	api := app.Group("/v1")
	api.Use(recover.New(recover.Config{
		EnableStackTrace: true,
	}))

	api.Post("", timeout.New(func(c *fiber.Ctx) error {
		panic("this is a panic")
	}, time.Millisecond*10000))

	app.Listen(":8080")
}

```

**Comment by Tristin-C** [comment]
@hakankutluay 
Thank you very much. My version is v2.37.0. It solved my problem
