### ISSUE TITLE
🐛 [Bug]: Cache middleware not working

### ISSUE THREAD

**Issue by smalloff** [gofiber/fiber#2274]
### Bug Description

Hi! I noticed that the cache does not work. I check with timestamp. I include it in the server response. As a result, every time I get a new time.

### How to Reproduce

Use my source code to build the fiber.

### Expected Behavior

The timestamp should not change.

### Fiber Version

v2.40.1

### Code Snippet (optional)

```go
package main

import (
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cache"
)

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World 👋!" + time.Now().Format(time.RFC850))
	})

	app.Use(cache.New(cache.Config{
		Expiration:   30 * time.Minute,
		CacheControl: true,
	}))

	app.Listen(":3000")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
You should add cache middleware before handlers that will be cached.
