### ISSUE TITLE
🤗 [Question]:  Disable default logging

### ISSUE THREAD

**Issue by marcoscaco** [gofiber/fiber#2275]
There any way of doing this?
I have a '/' GET method for AWS NLB health checking, and my cloud watch logs are getting messy with the default logging of Fiber

**Comment by leonklingele** [comment]
@marcoscaco there is no default logging except the startup message in fiber.

The startup message can be disabled as follows:

```sh
app := fiber.New(fiber.Config{
	DisableStartupMessage: true,
})
```

**Comment by antter** [comment]
> @marcoscaco there is no default logging except the startup message in fiber.
> 
> The startup message can be disabled as follows:
> 
> ```shell
> app := fiber.New(fiber.Config{
> 	DisableStartupMessage: true,
> })
> ```

"there is no default logging" This is not the behavior I was seeing. Not sure if something has changed but we had a minimal fiber app and it logged info about every request by default, including the full payload of the response. [The docs here](https://docs.gofiber.io/api/log#set-level) say `LevelTrace` is the default logging level. We disabled all these logs just by changing the log level to `LevelInfo` or higher.

Just commenting incase someone else stumbles upon this.

**Comment by KunMoe** [comment]
Seems like `DisableStartupMessage` was removed in the `fiber/v3`, how could I remove this log info?

<img width="961" height="179" alt="Image" src="https://github.com/user-attachments/assets/ffa98754-ea2c-467a-abe9-7fe856d564f4" />

<img width="1219" height="301" alt="Image" src="https://github.com/user-attachments/assets/a525ca30-bd2b-4e53-8de6-bbdbc314d9ec" />

**Comment by gaby** [comment]
@KUN1007 The configs were consolidated, its on the docs. https://docs.gofiber.io/next/api/fiber#server-listening
