### ISSUE TITLE
🐛 [Bug]: A group with blank prefix ("") spills the associated middleware to all the routes added after the group.

### ISSUE THREAD

**Issue by yaameen** [gofiber/fiber#2276]
### Bug Description

When the app has a group defined with a blank prefix like so
```go
group := app.Group("", Middleware)
```
Any route defined after the group has the `Middleware` applied regardless. Even the wildcard ones.

### How to Reproduce

1. Run the code snippet
2. Request curl localhost:3001/test1
3. Return the output from the `Middleware` and **NOT** the expected out come which `Test1!`

### Expected Behavior

localhost:3001/test1 should return `Test1!`

### Fiber Version

v2.40.1

### Code Snippet (optional)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func Middleware(c *fiber.Ctx) error {
	return c.SendString("Middleware!")
}

func main() {
	app := fiber.New()
	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})

	group := app.Group("", Middleware)
	
	group.Get("/test", func(c *fiber.Ctx) error {
		return c.SendString("Test!")
	})

	app.Get("/test1", func(c *fiber.Ctx) error {
		return c.SendString("Test1!")
	})

	app.Use("*", func(c *fiber.Ctx) error {
		return c.SendString("Fallback!")
	})

	app.Listen(":3001")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
This is the normal expected behavior, the middleware is defined for the given route prefix and match everything with this starting route

**Comment by yaameen** [comment]
Can middleware be applied to a set of routes that share a common path or prefix, such as an API with several endpoints under the same prefix (e.g. v1)? 
For instance, if I want to use authentication middleware for routes requiring user authentication and different middleware for the rest of the routes, is it possible to do this without individually specifying the middleware for each route?

**Comment by li-jin-gou** [comment]
Of course and refer to https://docs.gofiber.io/guide/routing#middleware

**Comment by yaameen** [comment]
I think I could not explain the issue here. Let me elaborate more 

```go
func main() {
  app := fiber.New()

  api := app.Group("/api", middleware) // /api

  v1 := api.Group("/v1", middleware)   // /api/v1
  v1.Get("/list", handler)             // /api/v1/list
  v1.Get("/user", handler)             // /api/v1/user
  v1.Get("/profile", handler)             // /api/v1/profile
  v1.Get("/notifications", handler)             // /api/v1/notifications

  v2 := api.Group("/v2", middleware)   // /api/v2
  v2.Get("/list", handler)             // /api/v2/list
  v2.Get("/user", handler)             // /api/v2/user

  log.Fatal(app.Listen(":3000"))
}
```
Note I have added a couple of routes to v1 group. Given I have a middleware that checks user authenticated `auth`, do I have to add the middleware to each route individually like so?
```go
  // I don't want to add the `auth` middleware to this route
  v1.Get("/list", handler)             // /api/v1/list
  // I need the rest however to have the `auth` middleware 
  v1.Get("/user", auth, handler)             // /api/v1/user
  v1.Get("/profile", auth, handler)             // /api/v1/profile
  v1.Get("/notifications", auth, handler)             // /api/v1/notifications
```
I am trying to use a middleware on a specific subgroup of routes that belong to the "v1" group. However, I don't want to add a prefix to the routes in order to differentiate the ones that use the middleware from the ones that don't. 

I am wondering if it is possible to use the middleware on a subgroup of routes without adding a prefix. Is there another way to apply the middleware to a subgroup of routes without adding a prefix? Or am I missing something here?

**Comment by ReneWerner87** [comment]
applying middleware to a group that does not have the same route parts in it is unfortunately not possible

possible would be to apply the middleware to "v1", wrap it and inside check the route with a list for allowed or not allowed and skip or execute the middleware content in each case

probably this is not as readable as the concept you used in the last example where you apply the middleware directly where it should be used
