### ISSUE TITLE
gin vs go fiber?

### ISSUE THREAD

**Issue by anonranger** [gofiber/fiber#2278]
### Question Description

We are planning a project and internally discussing gin vs go fiber?

Since the project relies on fast http, that is different than net/https

1. Will i run into problems with Go framework upgrades?
2. Any issues will i run into (edge cases) hosting in AWS?
3. What if fasthttp maintenance stops?

There are many risks.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
- The difference between fasthttp and net/http can be found in https://github.com/valyala/fasthttp#switching-from-nethttp-to-fasthttp
- I think gin and fiber ‘s server are both Go HTTP services, and fiber will not encounter any particular problems with AWS deployments.
- I don't think fasthttp will stop maintaining.
