### ISSUE TITLE
🤗 [Question]: How do I send a multipart/form-data response?

### ISSUE THREAD

**Issue by bumberboy** [gofiber/fiber#2284]
### Question Description

Hello there! 

I'm trying to send large files as a response but I can't figure out how to send a multipart/form-data response with fiber. Can someone point me to a code snippet?

I'm looking for something compatible with `multipart.Writer`.

`ctx.SendStream(...)` will not cut it because it writes to the body only.

`ctx.SendFile(...)` does not seem to slice files that are big into multiple parts.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
refer to https://docs.gofiber.io/api/client#filedata

**Comment by li-jin-gou** [comment]
sry and you can use https://docs.gofiber.io/api/ctx#write to set response  body content and content-type.
