### ISSUE TITLE
Golang fiber c.Render layout not execute with multi templates

### ISSUE THREAD

**Issue by alwismt** [gofiber/fiber#2287]
### Question Description

I'm trying to use one layout with different templates,
```
├── Main Folder
   ├── cmd
        └── main.go
   ├── controllers
   ├── models
   ├── views
        └── partials
            └── layout.html
        └── index.html
        └── dashboard.html
        └── login.html
   └── public
        └── sample.png
```

In my `layout.html`, I have

```html
<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>
    <h1>Loaded from Layout</h1>

// this way didn't worked
  {{ template . }}

// so i tried this way also
    {{ $templateName := .Template }}
    {{ template $templateName }}

// both way won't work


</body>
</html>
```

In my `dashboard.html`
```html
{{ define "dashboard" }}
    <h1>Dashboard</h1>
{{ end }}
```

In my `login.html`
```html
{{ define "login" }}
    <h1>Login</h1>
{{ end }}
```

When I'm render dashboard through controller its only load login.html, its take last html file always
```go
// controller

func Dashboard(c *fiber.Ctx) error {
	return c.Render("dashboard", fiber.Map{
		"title": "Login | Selectify Admin",
                "Template": "dashboard",
	}, "partials/layout")
}

```

In main file I have told where to find views
```go
//main.go

// create a new HTML engine
	template_engine := html.New(
		"./views",
		".html",
	)

	// create a new Fiber app
	app := fiber.New(fiber.Config{
		Views: template_engine, // set the views engine

		ErrorHandler: func(c *fiber.Ctx, err error) error {
			return utils.HandleError(c, err)
		},
	})
```

it's giving an error
"template: "partials/layout" is an incomplete or empty template"

How can I send or render correct html file using one layout??

Go version 1.19
fiver version 2
"github.com/gofiber/template/html"

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/template/tree/master/html
![image](https://user-images.githubusercontent.com/7063188/210963657-c1772a9d-cf24-4a47-b058-1422d906e21a.png)

is there a reason why you don't use the templating concept we prepared? by using the `{{embed}}` tag and specifying the layout template ?

**Comment by ReneWerner87** [comment]
@alwismt ? any progress here ?

**Comment by alwismt** [comment]
Thanks, some how i changed embed to template and i check all over google for an answer. My bad!!

**Comment by alwismt** [comment]
Also I do have an other question, when we use session in fiber is it use memory or file driver??

```
        store := session.New()
	sess, err := store.Get(c)
	if err != nil {
		log.Println(err)
	}
	sess.Set("user_id", user.ID)
```

If it is use memory as default how can I change to file driver, I so documentation about how to change it to sqlite. I wanna use session using file based for save auth data in mvc architecture

**Comment by ReneWerner87** [comment]
the memory storage should not be used there, rather another file storage or database

**Comment by alwismt** [comment]
Yeah I know we should not use memory for that kinda works. Thats why i'm trying to change it to file driver, I can't find working documentation for it. Do happened to know the documentation where I can found instruction? please

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/211322907-304bec9c-7211-41a0-b698-e36c4ac37b79.png)
https://docs.gofiber.io/api/middleware/session


all the existing storages:
https://github.com/gofiber/storage
(with the same interface)


mini example:
https://github.com/gofiber/recipes/blob/master/sessions-sqlite3/main.go#L54-L65

**Comment by alwismt** [comment]
Thanks
