### ISSUE TITLE
How to inject object/pointers to route handlers please? 🤗 [Question]: 

### ISSUE THREAD

**Issue by phyokyaw** [gofiber/fiber#2289]
### Question Description

I am new to golang and fiber.

Question please.

When declaring a handler for a particular route I would like to pass in dependency to function. Please see snippet below.

`
service = getProductService()
`

Instead of getting the above from inside the hander callback, I would like to pass 

```
service *ProductService
```
to the handler.

I tried to see if I can set the service reference in *fiber.App and get it from c.App() but I can't seem to find a way.

The reason I would like to inject is for testability and easy to change implementation of the product service interface. Product is an example.

Many thanks in advance. fiber looks great.

### Code Snippet (optional)

```go
func setUpRoutes(webApp *fiber.App, service *ProductService) {
	product := webApp.Group("/product")
        product.Get("/", listProducts)
}

func listProducts(c *fiber.Ctx) error {
        service := getProductService() # returns *ProductService
        products := service.GetProducts()
        return c.Status(fiber.StatusOK).JSON(&products)
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by phyokyaw** [comment]
May be what I would like to achieve is more like a design issue than fiber issue. May be it is possible if we change to
`
type Hander[T any] func(*fiber.Ctx, ...T)
`

If no other suggestions I'll close this.

**Comment by li-jin-gou** [comment]
refer to https://github.com/google/wire
