### ISSUE TITLE
Logo license?

### ISSUE THREAD

**Issue by m1212e** [gofiber/fiber#2290]
### Question Description

Hi,
under what license is the fiber logo/trademark? I'd like to mention that I worked with fiber in my resume, including the logo? Is that allowed?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by li-jin-gou** [comment]
refer to https://github.com/gofiber/fiber/blob/master/LICENSE
