### ISSUE TITLE
🐛 [Bug]: Cross compile to Darwin fails for internal/gopsutil/mem

### ISSUE THREAD

**Issue by ping-localhost** [gofiber/fiber#2293]
### Bug Description

Cross compiling to Darwin on Alpine Linux & Windows fails with:

```
# github.com/gofiber/fiber/v2/internal/gopsutil/mem
.go/pkg/mod/github.com/gofiber/fiber/v2@v2.41.0/internal/gopsutil/mem/mem_darwin_nocgo.go:21:14: undefined: invoke
```

### How to Reproduce

1. Run `GOOS=darwin GOARCH=amd64 go build -o app` on Windows/Alpine Linux.

### Expected Behavior

It should compile successfully but fails.

### Fiber Version

v2.41.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce
  app.Get("/metrics", monitor.New(monitor.Config{Title: "app"}))
  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by li-jin-gou** [comment]
I didn't reproduce it using mac, I'll try linux later.

**Comment by ping-localhost** [comment]
> I didn't reproduce it using mac, I'll try linux later.

Yes, it works fine when I compile it on my Mac/Darwin. It fails when I try to cross compiling to Darwin on Alpine Linux and Windows.

**Comment by ReneWerner87** [comment]
what do you mean by cross compiling

either you compile the binary for linux and use it there or mac and use it there

in my opinion you can't compile it for mac and use it on linux or windows ?

**Comment by ping-localhost** [comment]
> what do you mean by cross compiling
> 
> either you compile the binary for linux and use it there or mac and use it there
> 
> in my opinion you can't compile it for mac and use it on linux or windows ?

Since Go 1.16 (?) you can cross compile by specifying GOOS/GOARCH, for example:
- `GOOS="linux" GOARCH="arm64" go build ...` will compile for Linux ARM64
- `GOOS="linux" GOARCH="amd64" go build ...` will compile for Linux AMD64
- etc

There are some decent articles about that in the wild:
- https://freshman.tech/snippets/go/cross-compile-go-programs/
- https://www.digitalocean.com/community/tutorials/building-go-applications-for-different-operating-systems-and-architectures

---

A bug like this has been reported before: https://github.com/gofiber/fiber/issues/1984 (and resolved in https://github.com/gofiber/fiber/pull/1995). In fact, you were the one that closed the issue @ReneWerner87 😛

**Comment by ReneWerner87** [comment]
ok thx for the info^^

**Comment by ping-localhost** [comment]
Can confirm that it has been resolved by using the current commit in `master` (via `go get github.com/gofiber/fiber/v2@8a605c67d1313ad10a8dd22f9ab8c661c352645a`). 

Thank you!
