### ISSUE TITLE
How to profile Go Fiber App 

### ISSUE THREAD

**Issue by Koredeoluwafemi** [gofiber/fiber#2305]
### Question Description

How do I access the pprof data on the app. 

go tool pprof http://127.0.0.1:3000/debug/pprof/heap throws a 404 error

Fetching profile over HTTP from http://127.0.0.1:3000/debug/pprof/heap
http://127.0.0.1:3000/debug/pprof/heap: server response: 404 Not Found
failed to fetch any source profiles

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "github.com/gofiber/fiber/v2/middleware/pprof"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question
  app.Use(pprof.New())
  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by Koredeoluwafemi** [comment]
@li-jin-gou

**Comment by ReneWerner87** [comment]
@Koredeoluwafemi for me its working
![image](https://user-images.githubusercontent.com/7063188/213480168-def4a100-8698-4174-8d9a-9e34fa47a69f.png)

**Comment by Koredeoluwafemi** [comment]
I keep getting this error

go tool pprof http://127.0.0.1:3000/debug/pprof/heap
Fetching profile over HTTP from http://127.0.0.1:3000/debug/pprof/heap
http://127.0.0.1:3000/debug/pprof/heap: server response: 404 Not Found
failed to fetch any source profiles
@ReneWerner87

**Comment by ReneWerner87** [comment]
Then we need to know more
Golang version, fiber version, os system + version

**Comment by ReneWerner87** [comment]
Is it running nativ on your machine or in a docker container?
Have you tested :
Localhost and 0.0.0.0 as domain instead of 127.0.0.1

**Comment by Koredeoluwafemi** [comment]
just tried it again and it works. Am not sure of what change I made.

Golang version: 1.19.3
Fiber version: 2.41.0
Machine: local(macOS)

**Comment by Koredeoluwafemi** [comment]
I just confirmed what made the code to work.

It works only when I serve the app with this command

log.Println(http.ListenAndServe("localhost"+port, nil))

@ReneWerner87

**Comment by Koredeoluwafemi** [comment]
@ReneWerner87 is it possible to run my app on two different ports and install pprof using the working command

**Comment by ReneWerner87** [comment]
sure should be
just listen in a go function

**Comment by Koredeoluwafemi** [comment]
Thanks, works for me @ReneWerner87
