### ISSUE TITLE
🤔 Static files and Router interference bug

### ISSUE THREAD

**Issue by anton7r** [gofiber/fiber#231]
## Description
On 1.8.2 `app.Static(...)` used to work before `app.Get(...)` routes. But now doing it this way you cannot get the page from `Get("/")`. And `Get("/other")` shows the page normally but will send status 404 to the client.

**Expected behavior**
`Get("/")` - should show the page and not show `Directory index is forbidden`
`Get("/other")` - should show the page normally and not send status 404.

## How to reproduce

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  app.Static("/", "./public")

  app.Get("/", handlerFunc)
  app.Get("/other", handlerFunc2)
}
```

## And this is how i fixed the issue

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  app.Get("/", handlerFunc)
  app.Get("/other", handlerFunc2)

  app.Static("/", "./public")
}
```

**Comment by Fenny** [comment]
Hi @anton7r this has to do because an `index.html` is served before hitting your second `/` route.

A simple fix would be to disable the default `index.html` being served by passing the `Index` setting.

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  app.Static("/", "./static", fiber.Static{
    Index: "",
  })

  app.Get("/", func(c *fiber.Ctx) {
    c.Send("Hello /")
  })
  app.Get("/other", func(c *fiber.Ctx) {
    c.Send("Hello /other")
  })

  app.Listen(3000)
}
```

**Comment by anton7r** [comment]
ok, thanks!
