### ISSUE TITLE
🤔 Cors middleware error

### ISSUE THREAD

**Issue by EdneyMesquita** [gofiber/fiber#232]
Basic exemple that I found in documentation always throws that error. When I remove cors it works, but if I enable cors, it breaks.

![Captura de Tela 2020-03-18 às 10 45 58](https://user-images.githubusercontent.com/13970098/76967315-069e9d80-6906-11ea-96e1-cc730cc18c49.png)

**Comment by Fenny** [comment]
@EdneyMesquita, make sure you use the release version.
```go get -u github.com/gofiber/cors```

**Comment by EdneyMesquita** [comment]
I'm already using the latest version of this package. I updated the packages version today

**Comment by EdneyMesquita** [comment]
Problem solved! Thank you.

**Comment by renanbastos93** [comment]
> Problem solved! Thank you.

Share with us, how to solve this problem?
