### ISSUE TITLE
🐛 [Bug]: build with darwin-nocgo fail

### ISSUE THREAD

**Issue by Luoxin** [gofiber/fiber#2320]
### Bug Description

I can't compile 'darwin-nocgo'

### How to Reproduce

I get the following error
`/github.com/gofiber/fiber/v2@v2.41.0/internal/gopsutil/mem/mem_darwin_nocgo.go:21:14: undefined: invoke`

### Expected Behavior

It is expected to compile correctly.

### Fiber Version

2.41.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by li-jin-gou** [comment]
same to https://github.com/gofiber/fiber/issues/2293
