### ISSUE TITLE
🐛 [Bug]: Coloring on logs does not works as documentation while using custom format string

### ISSUE THREAD

**Issue by parvezmrobin** [gofiber/fiber#2321]
### Bug Description

When the `logger` middleware is used under default config like `app.Use(logger.New())`, coloring works just fine. However, when I use my own `loger.Config` to specify a format string, the output (e.g. method, status code) is not colored anymore. This is counter-intuitive the [source code comments](https://github.com/gofiber/fiber/blob/master/middleware/logger/config.go#L138) that states.
> // Enable colors if no custom ... output is given

This happens because, when I pass a custom `config` containing no `Output` stream, then it is automatically set to `ConfigDefault.Output` which is  `io.Writer`.
Therefore, even if I do not pass any custom `Output` stream, coloring gets disabled. 
As a hack, I am currently setting `logger.ConfigDefault.Output = nil` before calling `logger.New(config)`. Using this, coloring seems to work fine with a custom format string.

Still and all, it would be great it coloring works directly with a custom format string.

### How to Reproduce

1. Go to the file that defines the `*fiber.App` (e.g., `main.go`)
2. Add the following lines
   ```go
   app.Use(logger.New(logger.Config{
       Format: "${time} |${status}| ${latency} |${method}\n",
   }))
   ```
3. Run the app
4. See that the logs does not contain any coloring

### Expected Behavior

`method` and `status` values from the logs should be colored

### Fiber Version

v2.41.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  app.Use(logger.New(logger.Config{
    Format: "${time} |${status}| ${latency} |${method}\n",
  }))

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by efectn** [comment]
Resolved by https://github.com/gofiber/fiber/pull/2296. Will be included in the next release.
