### ISSUE TITLE
🤔 Wondering if "SameSite" is supported

### ISSUE THREAD

**Issue by Lol3rrr** [gofiber/fiber#233]
**Question description**
As far as I can see the Cookie-Struct does not have a "SameSite" field or something similiar and now I'm wondering if I just missed something in the documentation or if there is nothing for it.

If there is nothing to support this, are there any plans to add it?

This seems kind of important, especially as Chrome and other browser are now moving over to forcing Cookies to use these security related settings.

**Comment by Fenny** [comment]
This will be available in the next patch `v1.8.34` 👍

**Comment by Fenny** [comment]
Closing issue, `v1.8.4` now supports `SameSite` https://fiber.wiki/context#cookie
