### ISSUE TITLE
🐛 [Bug]: unauthrized request (basic auth middleware) not logged

### ISSUE THREAD

**Issue by msaf1980** [gofiber/fiber#2334]
### Bug Description

Unauthrized request (with basic auth middleware) not logged.

### How to Reproduce

1. Go to https://github.com/gofiber/fiber/blob/master/middleware/basicauth/basicauth_test.go#L41
2. Insert
```
	app.Use(logger.New(logger.Config{
		Format: "[${ip}]:${port} ${status} - ${method} ${path}\n",
	}))
```
4. Execute `go test -run ^Test_Middleware_BasicAuth$ github.com/gofiber/fiber/v2/middleware/basicauth -v`
5. No log for 401 (Unauthorized) 
```
=== RUN   Test_Middleware_BasicAuth
=== PAUSE Test_Middleware_BasicAuth
=== CONT  Test_Middleware_BasicAuth
[0.0.0.0]:0  200  -  GET      /testauth
[0.0.0.0]:0  200  -  GET      /testauth
--- PASS: Test_Middleware_BasicAuth (0.00s)
PASS
```

### Expected Behavior

Any way to log failed midleware ?

### Fiber Version

Current muster

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Thanks for the report, we will test it

My first guess is that the order is not correct, the logger middleware must be registered before the base auth middleware and not after (line 25 would be too late).

**Comment by msaf1980** [comment]
> Thanks for the report, we will test it
> 
> My first guess is that the order is not correct, the logger middleware must be registered before the base auth middleware and not after.
> 
> line 25 would be too late Insert in between 19 and 20 should work
> 
> @msaf1980 can you test it before we start the investigation process

Yes, insert use of logging middleware first after create app solve a problem.

May be update documentation, if not too easy fix them ?

**Comment by ReneWerner87** [comment]
you think we should describe this in the documentation?
we can do that, if you want you can also create a pull request for our documentation repository.
https://docs.gofiber.io/api/middleware/logger
-> https://github.com/gofiber/docs/edit/master/docs/api/middleware/logger.md

**Comment by msaf1980** [comment]
> you think we should describe this in the documentation? we can do that, if you want you can also create a pull request for our documentation repository. https://docs.gofiber.io/api/middleware/logger -> https://github.com/gofiber/docs/edit/master/docs/api/middleware/logger.md

https://github.com/gofiber/docs/pull/316
