### ISSUE TITLE
Breaking change to mounting caused by PR #2120

### ISSUE THREAD

**Issue by joshua-auchincloss** [gofiber/fiber#2335]
### Bug Description

When mounting a separate application, routes are skipped with valid prefixing and return invalid request URL. Appears in versions > 2.40.0, and seems to be caused by #2120

Specifically, the bug is caused when creating an app out of the main initialization of the (main) fiver application, and sub-mounting to a path (non-prefixed and prefixed, eg below)

### How to Reproduce

1. Define a function to create a *fiber.App 
```go
func CreatesApp() *fiber.App {
    app := fiber.New
    app.Get(“sub”, func(c *fiber.Ctx) error {
          log.Print(“called”)
          return c.JSON(“ok”)
}

    return app
}
```

2. Mount in main app: 

```go

func main(){
   mainApp := fiber.New()
   subApp := submodule.CreatesApp()
   mainApp.Mount(“/path”, subApp)
   ….
}
```

3. Try a request to ‘path/sub’, it will fail

### Expected Behavior

Pre 2.40.0, no issues & sub-paths route as expected. Fixes by rolling back to 2.39.0

### Fiber Version

2.40.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func CreatesApp() *fiber.App {
    app := fiber.New()

    app.Get(‘bar’, func(c *fiber.Ctx) error {
    return c.JSON(‘ok’)
}

    return app
}

func main() {
  app := fiber.New()
  sub := CreatesApp()
  app.Mount(
   “foo”, sub
  )
  log.Print(sub.MountPath()) // prints “foo”
  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Thanks for the report
Its a duplicate https://github.com/gofiber/fiber/issues/2233

We try to fix it in https://github.com/gofiber/fiber/pull/2331

**Comment by joshua-auchincloss** [comment]
> Thanks for the report
> 
> Its a duplicate https://github.com/gofiber/fiber/issues/2233
> 
> 
> 
> We try to fix it with https://github.com/gofiber/fiber/pull/2331 

Gotcha, thanks anyways for the fast reply!
