### ISSUE TITLE
🐛 [Bug]: Unable to use struct pointer in bodyparser()

### ISSUE THREAD

**Issue by JetLua** [gofiber/fiber#2336]
### Bug Description

```go
type Bar struct {
	Name    string    `json:"name"`
	Message *Message `json:"message"` // *Message: Don't work
}

type Message struct {
	Content string `json:"content"`
}
```
```bash
curl -X POST -H "Content-Type: application/json" 127.0.0.1:7777/bar --data "{\"name\": \"fiber\", \"message\": {\"content\": \"ok\"}}"
```

```
&Bar{Name:"fiber", Status:"", Message:(*Message)(0x1400029c590)}
```

when i don't use the pointer:

```go
type Bar struct {
	Name    string    `json:"name"`
	Message Message `json:"message"` // Message: work
}
```

```
&Bar{Name:"fiber", Message:Message{Content:"ok"}}
```

### How to Reproduce

```go
bar := &Bar{Message: &Message{}}
c.BodyParser(bar)
```

### Expected Behavior

&Bar{Name:"fiber", Message:Message{Content:"ok"}}

### Fiber Version

v2.24.0
go: v1.20.1

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by JetLua** [comment]
sorry

**Comment by ReneWerner87** [comment]
> sorry

What was the solution to the problem?

**Comment by JetLua** [comment]
> > sorry
> 
> What was the solution to the problem?

It's not a bug, it's my own problem.
The address printed when pointers are nested, I thought the parsing failed.
