### ISSUE TITLE
🤗 [Question]: Transfer data between handles

### ISSUE THREAD

**Issue by JobberRT** [gofiber/fiber#2337]
### Question Description

Maybe this is a simple question but I couldn't find a andswer. Tried search the issues with `transfer data`/`store data`/`store data in ctx` etc and official document website's `Ctx` section, but got nothing.

Here's what I need to achieve:
I can use some method to transfer data between handlers. For example, in `labstack/echo`, I can simple use `echo.Context.Set(key, val)` to save data to context, then when I need to use it, I could call `echo.Context.Get(key)` to get data that I need.

### Code Snippet(`Code Snippet` block doesn't highlight synatx, so I just write it here)
```go

// These just example that helps me to explain, may not working

func main() {
  app := fiber.New()
  app.Use(filterMiddleware)
  app.Get("/", processData)
  app.Listen(":80")
}

func filterMiddleware(c *fiber.Ctx) error {
  rawData := c.Query("data")
  // In real life, the filtering process is much more complex
  filteredData := strings.Split(rawData, ",")
  // This is my imagination funciton to save a data in *fiber.Ctx, doesn't exist
  c.SaveData("filteredData", filteredData)
  return c.Next()
}

func processdata(c *fiber.Ctx) error {
  // This is my imagination funciton to get a data from *fiber.Ctx, doesn't exist
  filtered := c.GetData("filteredData")
  fmt.Println(filtered)
  return c.Next()
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Pls check https://docs.gofiber.io/api/ctx#locals

**Comment by ReneWerner87** [comment]
@JobberRT  have you looked at the feature ? 
it should not even be created a new allocation, because we only shift the value
