### ISSUE TITLE
🤔 Does fiber have support for live reload, like Gin?

### ISSUE THREAD

**Issue by Frankcarvajal** [gofiber/fiber#234]
**Question description**
I'm a newer gopher coming from the JS ecosystem. I'm used to nodemon for live reload of the server on code changes, I think this exists in the gin web framework, but does Fiber have this? or what would be recommended?

**Comment by renanbastos93** [comment]
Hello man,

I using this lib to use live reload -> github.com/githubnemo/CompileDaemon

see ya

**Comment by kokizzu** [comment]
Also graceful restart, previously i used https://github.com/jpillora/overseer

**Comment by renanbastos93** [comment]
Should we implement a live reload on Fiber?
> I believe that it's unnecessary.

**Comment by Frankcarvajal** [comment]
Using nodemon when developing Node/Express applications is super useful. But, it's not in express itself. But, that's because installing the nodemon dependency & using it appears far easier to set up & quickly use than CompileDaemon or overseer, from what I can see.

**Comment by Fenny** [comment]
I love nodemon when I work with node, the big difference is that Go is not a scripting language. I'm not sure if we should implement this in Fiber, the best option would be to find a good live reload package and promote it in our docs.

Does anyone has an example on how to use one, so I could pin it?

**Comment by WLun001** [comment]
Haven't tried modd, but air works good to me

https://github.com/cosmtrek/air

**Comment by Fenny** [comment]
I'm closing this issue because there are no plans to implement this directly in Fiber, this issue should have enough keywords to be found for other users asking the same thing.

Thank you all for thinking out loud and providing sources 👍

**Comment by WLun001** [comment]
@Fenny Should we add to the docs and provide example?

**Comment by jeyraj** [comment]
The following is my solution, which I am currently using.

[](https://medium.com/@jeyraj/live-reload-for-go-afef9c25420a)

**Comment by chrisbirster** [comment]
@jeyraj FYI it appears that link is to an invalid url on git. But after copy and paste into browser I'm able to see the article.

**Comment by jeyraj** [comment]
> @jeyraj FYI it appears that link is to an invalid url on git. But after copy and paste into browser I'm able to see the article.

Sorry for the inconvenience. I am not able share the Medium article directly. There is no option available.

**Comment by chrisbirster** [comment]
> > @jeyraj FYI it appears that link is to an invalid url on git. But after copy and paste into browser I'm able to see the article.
> 
> Sorry for the inconvenience. I am not able share the Medium article directly. There is no option available.

Oh nevermind then. I didn't know that was restricted.

**Comment by ameenpv** [comment]
> @Fenny Should we add to the docs and provide example?

Second that. I spend sometime on docs and an hour outside looking for the common practice. Hope it will be helpful for someone who's new to go and coming from node background.
