### ISSUE TITLE
🤗 [Question]: Does the log  support cutting by file size?

### ISSUE THREAD

**Issue by feng99** [gofiber/fiber#2342]
### Question Description

Does the log  support cutting by file size?

if yes,  give me a sample, thank you。
if no, hope to add this feature。

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
No, log rotation is not supported.

**Comment by feng99** [comment]
> No, log rotation is not supported.

I need it.   What should I do to achieve this feature?

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/middleware/logger#config

![image](https://user-images.githubusercontent.com/7063188/221119069-e46b2528-f09c-41b9-924f-fa70033b9fb7.png)
i think this can easily be made possible with additional packages

Our logger middleware takes the output writer which is stored in the config and here you can take any writer, e.g. also a writer which supports log rotation.

https://github.com/natefinch/lumberjack

https://github.com/natefinch/lumberjack#func-logger-write
![image](https://user-images.githubusercontent.com/7063188/221119156-8f098ae1-3f39-4454-a289-1a98464afcc9.png)

**Comment by ReneWerner87** [comment]
https://pkg.go.dev/github.com/yieldr/go-log/log/logrotate#Logrotate.Write
![image](https://user-images.githubusercontent.com/7063188/221119619-b51a7686-abe4-40e1-b80e-0886043bf29a.png)


just search in google for golang and log rotation 
almost every package provides implements the io.Writer interface

**Comment by feng99** [comment]
thanks.    I get it.
