### ISSUE TITLE
🤗 [Question]:  Why i can't get cookie that i've set?

### ISSUE THREAD

**Issue by adimasmudi** [gofiber/fiber#2345]
### Question Description

I'm trying to save my user email in cookie and i want to get it from auth middleware,

I am trying to console the cookie i've set immediately and showed in the console, but when i tried to get it my auth middleware it showed [nothing]

 the code like this : 

### Code Snippet (optional)

```go
// set the cookie

// Create cookie
cookie := new(fiber.Cookie)
cookie.Name = "user"
cookie.Value = user.Email
cookie.Expires = time.Now().Add(24 * time.Hour)

fmt.Println(cookie)
// it showed -> &{user myemail@gmail.com   0 2023-02-26 09:27:02.4858237 +0700 +07 m=+86423.322795001 false false  false}
  
// Set cookie
c.Cookie(cookie)


// get cookie
cookie := c.Cookies("user","empty") // set default to empty

fmt.Println("cookie",string(cookie))
// it showed -> cookie empty
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by adimasmudi** [comment]
It solved when i trying to set from another controller, i think the reason why the cookie can't be get because from the code i gave above, i loged in from browser so the cookie set in the browser but my second controller is using API based login so the cookie showed in console when i tried to print.

**Comment by YairLevi** [comment]
> It solved when i trying to set from another controller, i think the reason why the cookie can't be get because from the code i gave above, i loged in from browser so the cookie set in the browser but my second controller is using API based login so the cookie showed in console when i tried to print.

Hi, having the same issue now, and I didn't quite understand your solution. Mind explaining a bit?
