### ISSUE TITLE
🤗 [Question]: I need to implement a function based on udp protocol. Is there any relevant class library or code？

### ISSUE THREAD

**Issue by feng99** [gofiber/fiber#2346]
### Question Description

I need to implement a function based on udp protocol. Is there any relevant class library or code？

The hardware device reports data to the go service.

thanks.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
udp is unfortunately not possible with fiber

but you can use fasthttp

```go
package main

import (
	"fmt"
	"log"
	"net"
	"time"

	"github.com/valyala/fasthttp"
)

func main() {
	// Erstelle den UDP-Listener.
	listener, err := NewUDPPacketListener(":8080")
	if err != nil {
		log.Fatalf("Fehler beim Erstellen des Listeners: %v", err)
	}
	defer listener.Close()

	// Erstelle den Fasthttp-Request-Handler.
	requestHandler := func(ctx *fasthttp.RequestCtx) {
		fmt.Fprintf(ctx, "Hello, world!")
	}

	// Starte den Server mit der ServeConn-Funktion von Fasthttp.
	if err := fasthttp.ServeConn(listener, requestHandler); err != nil {
		log.Fatalf("Fehler beim Starten des Servers: %v", err)
	}
}

 ```

**Comment by feng99** [comment]
thanks,   but,   func  NewUDPPacketListener  not found.

**Comment by ReneWerner87** [comment]
https://www.golinuxcloud.com/golang-udp-server-client/
yes that's right, just follow the methods in the article

**Comment by feng99** [comment]
Oh, I thought wrong, udp protocol and fastttp, fiber is not necessarily related, embarrassing
