### ISSUE TITLE
🚀 [Feature]: middleware/requestid: don't call "Generator" func on existing request ID header

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2350]
### Feature Description

The `Generator()` func is called even if the request ID header was found:

https://github.com/gofiber/fiber/blob/a70b8612b180de0cd0187673833998d3983c20fc/middleware/requestid/requestid.go#L19

For performance reasons, the func should only be called if the request ID header was not found or is empty.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by efectn** [comment]
Agree with you. defaultString doesn't seem performant for that case. `utils.UUID` makes 1 alloc.

**Comment by ReneWerner87** [comment]
yes confirm, there we can optimize

**Comment by ReneWerner87** [comment]
@leonklingele can you support us with a PR

**Comment by Rorke76753** [comment]
@ReneWerner87 can i help with this issue?

**Comment by ReneWerner87** [comment]
sure
