### ISSUE TITLE
🐛 [Bug]: requestId middleware still only accepts `string` for `ContextKey` config value, should be `any` like `c.Locals`.

### ISSUE THREAD

**Issue by benjajaja** [gofiber/fiber#2356]
### Bug Description

#2143 allows to use `any` as key for `c.Locals(key, v)`. The RequestID middleware should be consistent with that.
This allows to use a custom type for context keys, like for other keys. The RequestID is likely read back somewhere else along other context keys.

### How to Reproduce

See https://docs.gofiber.io/api/middleware/requestid#config

### Expected Behavior

https://docs.gofiber.io/api/middleware/requestid#config should have `ContextKey interface{}`

### Fiber Version

v2.42.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
@benjajaja can you help us with a pull request?

**Comment by benjajaja** [comment]
yea I can find some time
