### ISSUE TITLE
🔥 disable time limit in app.Test

### ISSUE THREAD

**Issue by Trim21** [gofiber/fiber#236]
**Is your feature request related to a problem?**

No

**Describe the solution you'd like**

A options to disable time limit in `app.Test`

**Describe alternatives you've considered**

Supply another alternate function to check execution time.

**Additional context**

I'm writing a handler may be slow.
When I'm testing it, I always got a `errors.errorString{s:"timeout"}`.
I found that there is a time limit in `app.Test`. 
But I really don't care about its performance in this router, and I found there is no way to disable it.

**Comment by Fenny** [comment]
We could add an ms timeout `Test(request *http.Request, msTimeout ...int)` for `v1.8.4`?

**Comment by Trim21** [comment]
Great!
So could I use 0 er -1 to disabled it then it ?

**Comment by Fenny** [comment]
Correct!
