### ISSUE TITLE
🐛 [Bug]: memory: protect field access with lock to avoid possible data race

### ISSUE THREAD

**Issue by UtopiaGitHub** [gofiber/fiber#2360]
### Bug Description

Fixed inconsistency and also potential data race in memory/memory.go:
s.db is read/written 8 times in memory/memory.go; 7 out of 8 times it is protected by s.mux.RLock()/Lock(); 1 out of 8 times it is read without a Lock, which is in func Conn() on L142.
A data race may happen when Conn() and other func like Set() are called in parallel.
The fix is to protect the access to s.db and save the result to a local variable.

### How to Reproduce

Nil

### Expected Behavior

Data Race

### Fiber Version

v2.42.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by UtopiaGitHub** [comment]
您好，邮件我已收到，我会及时给您回复，祝好！

**Comment by ReneWerner87** [comment]
@UtopiaGitHub can you help us with a pull request and also do the fix in the storage repository

**Comment by UtopiaGitHub** [comment]
Yes. I commit the pull request to fix the bug. Thanking for your condition.

**Comment by gaby** [comment]
@ReneWerner87 @UtopiaGitHub I made the comment in the PR too. But I think Conn() is suppose to return a pointer to the memory field. The other storage providers return a pointer.
