### ISSUE TITLE
🤗 [Question]:  how to get Route().Path in Group Handler before c.next() ?

### ISSUE THREAD

**Issue by yellowmarlboro** [gofiber/fiber#2362]
### Question Description

I want to obtain the specific `Route Path` in the handler of Group and put it into `UserContext` for the use of interfaces within the group, for example, printing /abc/:id here. However, I found that the complete `Route Path` is only available after c.Next(), which means that interfaces within the group cannot obtain the path (if c.Next() is not included in the interfaces). Is there any way to write the specific interface's `Route Path` into the context using only the Group Handler without modifying the interfaces within the group?
```Go
func main() {
    r := fiber.New()
    router := r.Group("/", func(c *fiber.Ctx) error {
        path := c.Route().Path
        fmt.Println("Route Path:", path)
        return c.Next()
    })
    router.Get("/abc/:id", func(c *fiber.Ctx) error {
        c.Status(http.StatusOK)
        return c.SendString("OK")
    })
    req, _ := http.NewRequest("GET", "/abc/123", nil)
    r.Test(req)
    defer r.Shutdown()
}
```

### Checklist:

- [x] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by muhfaris** [comment]
hi @yellowmarlboro I have same issue.
how to solve that?
