### ISSUE TITLE
🤗 [Question]: CSRF reporting "Forbidden" after POST

### ISSUE THREAD

**Issue by oso95** [gofiber/fiber#2363]
### Question Description

Hi, 

I am new to go and having issue to implement CSRF protection. I have CSRF token generated successfully but I wasn't able to verify it and the page just display "Forbidden"

How do I verify the CSRF token in my HandleLogin()?

### Code Snippet (optional)
This is my server.go
```go


csrfConfig := csrf.Config{
  KeyLookup:      "header:X-CSRF-Token",
  KeyGenerator:  utils.UUIDv4,
  CookieName:     "_csrf",
  CookieSameSite: "Strict",
  CookieSecure:   true,
  CookieHTTPOnly: true,
}	

NoAuthPost := app.Group("/auth")
NoAuthPost.Use(csrf.New(csrfConfig), limiter.New(limiterConfig))

// This is Post request routes for user without authentication
NoAuthPost.Post("/login", controller.HandleLogin)
```

login.go
```go

func LoadLoginPage(c *fiber.Ctx) error {
	// Get the CSRF token from the context
	csrfToken := c.Cookies("_csrf")
	log.Print(csrfToken)

	// Add the CSRF token to the template data
	data := fiber.Map{
		"csrf": csrfToken,
	}

	// Render login.html template with CSRF token included
	return c.Render("login", data)
}

// HandleLogin handles user login requests
func HandleLogin(c *fiber.Ctx) error {

  csrfToken := c.FormValue("_csrf")
  trueCsrfToken := c.Cookies("_csrf")
  if csrfToken != trueCsrfToken {
    return c.Render("login", fiber.Map{"ErrorMessage": "Invalid CSRF token"})
  }
  email := c.FormValue("email")
  password := c.FormValue("password")

  //more codes here to verify user's input

  // The email and password are correct, log the user in
  return c.Render("dashboard", fiber.Map{
	"csrf": trueCsrfToken,
  })
```
login.html
```html
  <body>
    <h1>User Login</h1>
    <form method="POST" action="/auth/login">
      <input type="hidden" name="_csrf" value="{{ .csrf }}">
      <span style="color: black"> {{.SuccessfullyRegistered}}</span>
      <br>
      <label for="email"> Email </label>
      <br>
      <input type="email" name="email">
      <br>
      <label for="password"> Password </label>
      <br>
      <input type="password" name="password">
      <br>
      <span style="color: red">{{.ErrorMessage}}</span>
      <br>
      <input type="submit" value="Log in">
      <br>
      <a href="/auth/SelectUniversity" style="color: blue"> Create Account </a>
    </form>

```

dashboard.html
```html
<body>
    <input type="hidden" name="_csrf" value="{{ .csrf }}">
    <div class="profile-container">
      <img src="{{.ProfilePicture}}" alt="User profile photo" width="50" , height="50">
      <h3 style="margin-top: 20px;"> {{.UserName}} </h3>
      <h4 style="margin-top: 20px;"> {{.UserUniversity}} </h4>
      <h5 style="margin-top: 20px;"> {{.ProfileLink}} </h5>
    </div>
    <div class="button-container">
      <a href="/user/profilePage" class="button">Profile Page</a>
      <a href="/user/manageTag" class="button">Manage Tag</a>
      <a href="/user/requesTag" class="button">Request Tage</a>
      <a href="/user/setting" class="button">Setting</a>
      <form action="/user/logout" method="post">
        <input type="submit" value="Logout">
      </form>
    </div>
  </body>
  ```
### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
there are several ways to transfer the token, you said in your configuration that you want the key in the headers

```go
csrfConfig := csrf.Config{
  KeyLookup:      "header:X-CSRF-Token",
...
}
```

https://docs.gofiber.io/api/middleware/csrf#config
![image](https://user-images.githubusercontent.com/7063188/224533680-1676b2ec-bd6c-47f9-96fe-6d1064965617.png)

but in the example you try to get it from the wrong resources

example:
https://github.com/gofiber/recipes/blob/master/csrf/routes/mainServer.go#L47

**Comment by oso95** [comment]
> there are several ways to transfer the token, you said in your configuration that you want the key in the headers
> 
> ```go
> csrfConfig := csrf.Config{
>   KeyLookup:      "header:X-CSRF-Token",
> ...
> }
> ```
> 
> https://docs.gofiber.io/api/middleware/csrf#config ![image](https://user-images.githubusercontent.com/7063188/224533680-1676b2ec-bd6c-47f9-96fe-6d1064965617.png)
> 
> but in the example you try to get it from the wrong resources
> 
> example: https://github.com/gofiber/recipes/blob/master/csrf/routes/mainServer.go#L47

Thanks, didn't notice that! Problem fixed
