### ISSUE TITLE
🤗 [Question]: Timeout is not work in Fiber v2.42.0

### ISSUE THREAD

**Issue by codingkits** [gofiber/fiber#2364]
### Question Description

# Timeout is not work in Fiber v2.42.0
> For Example 
> In Code Snippet 
> It should return a "request timeout" , if the handler costs more than 1000 Millisecond
> But it does not work

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Like this , the timeout does not work
  app.Get("/abc", timeout.New(xxHandler, time.Millisecond*1000))

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@hakankutluay would like to restore the original functionality and provide a separate function for working with contexts as mentioned in the old pull request

**Comment by hakankutluay** [comment]
@ReneWerner87 sure, but the original functionality has race conditions and is not safe to use on production. 

The PR was for a new timeout functionality but we have decided to replace it after a [discussion](https://github.com/gofiber/fiber/pull/2090#issuecomment-1247154389).

**Comment by hakankutluay** [comment]
@ReneWerner87 we have a workaround to make it work with `time.Sleep`

```go

func main() {
	app := fiber.New()

	// Like this , the timeout does not work
	app.Get("/abc", timeout.New(func(ctx *fiber.Ctx) error {
		time.Sleep(2 * time.Second)
		return nil
	}, time.Millisecond*1000))

	log.Fatal(app.Listen(":3000"))
}
```
Sleep with context timeout
```go
func main() {
	app := fiber.New()

	// Like this , the timeout does not work
	app.Get("/abc", timeout.New(func(ctx *fiber.Ctx) error {
		if err := sleepWithContext(c.UserContext(), 2 * time.Second, ErrFooTimeOut); err != nil {
			return fmt.Errorf("%w: execution error", err)
		}
		return nil
	}, time.Millisecond*1000))

	log.Fatal(app.Listen(":3000"))
}

func sleepWithContext(ctx context.Context, d time.Duration, te error) error {
	timer := time.NewTimer(d)
	select {
	case <-ctx.Done():
		if !timer.Stop() {
			<-timer.C
		}
		return te
	case <-timer.C:
	}
	return nil
}
```

**Comment by ReneWerner87** [comment]
Can we provide something so that the old functionality behavior is restored without the consumers having to change anything (otherwise it is a breaking change if the behavior changes)?

**Comment by hakankutluay** [comment]
@ReneWerner87 I couldn't find a way to implement race condition-free timeout middleware that supports `time.Sleep`.

**Comment by ReneWerner87** [comment]
@hakankutluay can you create an example of the race conditions in code so i can recreate them

**Comment by hakankutluay** [comment]
sure,

**server**
use previous fiber versions that has original timeout middleware. like  `v2.37.1`

```go
func main() {
	app := fiber.New()

	app.Use(recover.New(recover.Config{
		EnableStackTrace: true,
	}))
	app.Use(logger.New())

	// Like this , the timeout does not work
	app.Get("/abc", timeout.New(func(ctx *fiber.Ctx) error {
		time.Sleep(time.Millisecond * 2000)
		return ctx.SendStatus(http.StatusNoContent)
	}, time.Millisecond*1000))

	log.Fatal(app.Listen(":3200"))
}
```

run with `-race` flag. [docs](https://go.dev/doc/articles/race_detector)
```shell
 go run -race ./main.go
``` 

**call in parallel**
```shell
seq 1 200 | xargs -n1 -P20  curl "http://localhost:3200/abc"
```

some of them will introduce race conditions

```
==================
WARNING: DATA RACE
Read at 0x00c0005a6018 by goroutine 30:
  github.com/valyala/fasthttp.(*Response).bodyBytes()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/http.go:362 +0x274
  github.com/valyala/fasthttp.(*Response).Body()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/http.go:352 +0x230
  github.com/gofiber/fiber/v2.(*Ctx).SendStatus()
      /Users/hakan.kutluay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.1/ctx.go:1527 +0x80
  main.main.func1()
      /Users/hakan.kutluay/Projects/go/fiber-middleware-test/original/main.go:25 +0x38
  github.com/gofiber/fiber/v2/middleware/timeout.New.func2.1()
      /Users/hakan.kutluay/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.1/middleware/timeout/timeout.go:31 +0x60

Previous write at 0x00c0005a6018 by goroutine 22:
  github.com/valyala/bytebufferpool.(*ByteBuffer).Reset()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/bytebufferpool@v1.0.0/bytebuffer.go:110 +0xb4
  github.com/valyala/fasthttp.(*Response).ResetBody()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/http.go:595 +0x94
  github.com/valyala/fasthttp.(*Response).resetSkipHeader()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/http.go:1073 +0xc0
  github.com/valyala/fasthttp.(*Response).Reset()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/http.go:1065 +0xb8
  github.com/valyala/fasthttp.(*RequestCtx).reset()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/server.go:795 +0x44
  github.com/valyala/fasthttp.(*Server).releaseCtx()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/server.go:2751 +0x44
  github.com/valyala/fasthttp.(*Server).serveConn()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/server.go:2449 +0x1e5c
  github.com/valyala/fasthttp.(*Server).serveConn-fm()
      <autogenerated>:1 +0x44
  github.com/valyala/fasthttp.(*workerPool).workerFunc()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/workerpool.go:224 +0x98
  github.com/valyala/fasthttp.(*workerPool).getCh.func1()
      /Users/hakan.kutluay/go/pkg/mod/github.com/valyala/fasthttp@v1.41.0/workerpool.go:196 +0x48
```

**Comment by ReneWerner87** [comment]
@hakankutluay 
https://github.com/valyala/fasthttp/blob/7846101dc65ee5e02cea672af4594e3a80048632/server.go#L455-L487

back then the timeout middleware was a copy of the timeout handler, maybe i had forgotten something in the adaption ? 

or is this timeouthandler in use also with race conditions ? can you check this

**Comment by ReneWerner87** [comment]
maybe the part with the check for the concurrency request count

**Comment by hakankutluay** [comment]
@ReneWerner87 I have checked `TimeoutHandler` on fasthttp, and it doesn't raise race conditions. 

I think `concurrencyCh` on the server limits concurrent requests, It may handle race condition issues. we couldn't access this channel since it's private.

**Comment by hakankutluay** [comment]
`fasthttp.TimeoutHandler` returns `fasthttp.RequestHandler` which we can't use on routing directly. It should be implemented on Fiber too, but as I mentioned before, it uses some `fasthttp` internal calls which we can't access.

By the way, the new implementation supports context cancelation, which is useful to cancel underlying operations like DB calls,  http calls etc. that are not supported directly on `fasthttp.TimeoutHandler`.  Only needs some workaround with direct usage of `time.Sleep`.

**Comment by ReneWerner87** [comment]
@hakankutluay Can you create a pull request in fasthttp which allows this?

**Comment by hakankutluay** [comment]
@ReneWerner87 not yet, I'll do whenever I have a time
