### ISSUE TITLE
🐛 [Bug]: Can't parse time values with positive timezone offsets

### ISSUE THREAD

**Issue by Sophie1142** [gofiber/fiber#2366]
### Bug Description

Hello!

Fiber `Query/BodyParser` is able to parse RFC 3339 datetime strings in UTC (`2022-01-01T00:00:00Z`) and with negative timezone offsets (`2022-01-01T00:00:00-05:00`), but it throws an error for a correctly formatted datetimes with a positive timezone offset (`2022-01-01T00:00:00+05:00`).

This is the error message I get when I make a request to my app via Postman:
<img width="732" alt="image" src="https://user-images.githubusercontent.com/43194894/224520737-59e3e3c3-68c2-4650-b0dd-fa13fc6d1c0c.png">

Thanks so much for your time and consideration on this issue!

### How to Reproduce

1. Define a handler that uses `c.Query/BodyParser` on a struct containing a `time.Time` field. 
2. Make a request to that handler with an RFC 3339 datetime with a _positive_ timezone offset, like `2022-01-01T00:00:00+05:00`. See the error that's raised.

### Expected Behavior

Expected behavior is that it should be able to parse datetimes with positive offsets.

### Fiber Version

v2.42.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
@Sophie1142 can you send us code examples for faster fixing

https://docs.gofiber.io/next/api/ctx#setparserdecoder 
have you already tested and set your own parser type ?


maybe its escaped in your request ?
https://github.com/gorilla/schema/issues/185#issuecomment-1073116792

**Comment by Sophie1142** [comment]
Ahhh yes, it does seem `+` is an escaped character in URL encoding. Apologies for taking up your time, and thanks for the speedy response!
