### ISSUE TITLE
🤗 [Question]: How to get specific value from session

### ISSUE THREAD

**Issue by fnoopv** [gofiber/fiber#2370]
### Question Description

I need to check if the user is already logged in to prevent duplicate logins, I use the following code to set the session:
```go
func Login(ctx *fiber.Ctx) error {
    sess, err := store.Get(ctx)
    if err != nil {
        panic(err)
    }
// I should check if this user is already logged in, how can I check if the user with id 1 is already logged in, I need to know if a value with id==1 exists
    sess.Set('id', 1)
}
```

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/middleware/session

sess.Get("id") is not working?

**Comment by fnoopv** [comment]
> https://docs.gofiber.io/api/middleware/session#signatures 
> 
> sess.Get("id") is not working? 

it's working，but sess.Get() is find by key，if current session exclude logged in session，example，same user，he first logged in success by webui，then he will login by curl, but the second login not include first logged in session, so, i need w function or other else, to check value is 1 of id column is exists, sess.Get() can't do this

**Comment by ReneWerner87** [comment]
I don't quite understand the second part of your description
