### ISSUE TITLE
🤗 [Question]: About proxy protocol v2 support when webapi behind haproxy using ssl passthrough

### ISSUE THREAD

**Issue by auxo86** [gofiber/fiber#2375]
### Question Description

Hi~ I'm a beginner of Fiber. I have written some web APIs using Fiber and placed them behind HAProxy. Because HAProxy has SSL passthrough enabled, my web APIs may need to support Proxy Protocol v2 to obtain the IP address of the HTTP request smoothly. Can I use Fiber to set up support for this protocol? Thank you very much!

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@auxo86 Have you tried running a simple Fiber server with TLS behind HAProxy to see how it behaves?

**Comment by auxo86** [comment]
Yes，when I send a request by Jmeter ，I got exception like this:
```
Response code:Non HTTP response code: javax.net.ssl.SSLHandshakeException
Response message:Non HTTP response message: Remote host terminated the handshake
```

**Comment by auxo86** [comment]
I write a prototype here:
```
package main

import (
	"crypto/tls"
	"github.com/gofiber/fiber/v2"
	"github.com/pires/go-proxyproto"
	"net"
	"time"
)

func main() {
	app := fiber.New()
	ln, _ := net.Listen("tcp", ":8081")

	proxyListener := &proxyproto.Listener{
		Listener:          ln,
		ReadHeaderTimeout: 10 * time.Second,
	}
	defer proxyListener.Close()

	cer, _ := tls.LoadX509KeyPair("./SSL/ForTest.crt", "./SSL/ForTest.key")

	ln = tls.NewListener(proxyListener, &tls.Config{Certificates: []tls.Certificate{cer}})

	app.Get("/ok", func(c *fiber.Ctx) error {
		return c.SendString("Your IP address is: " + c.IP() + "\n")
	})

	app.Listener(ln)
}
```
It works. However, It uses net.Listen() to create custom Listener.
I have do some loading test for it, and the best result is about 22000 rps.
I don't know if the efficiency bottleneck of this simple program that displays IP address is due to my use of the Go net package.

**Comment by gaby** [comment]
> I write a prototype here:
> 
> ```
> package main
> 
> import (
> 	"crypto/tls"
> 	"github.com/gofiber/fiber/v2"
> 	"github.com/pires/go-proxyproto"
> 	"net"
> 	"time"
> )
> 
> func main() {
> 	app := fiber.New()
> 	ln, _ := net.Listen("tcp", ":8081")
> 
> 	proxyListener := &proxyproto.Listener{
> 		Listener:          ln,
> 		ReadHeaderTimeout: 10 * time.Second,
> 	}
> 	defer proxyListener.Close()
> 
> 	cer, _ := tls.LoadX509KeyPair("./SSL/ForTest.crt", "./SSL/ForTest.key")
> 
> 	ln = tls.NewListener(proxyListener, &tls.Config{Certificates: []tls.Certificate{cer}})
> 
> 	app.Get("/ok", func(c *fiber.Ctx) error {
> 		return c.SendString("Your IP address is: " + c.IP() + "\n")
> 	})
> 
> 	app.Listener(ln)
> }
> ```
> 
> It works. However, It uses net.Listen() to create custom Listener. I have do some loading test for it, and the best result is about 22000 rps. I don't know if the efficiency bottleneck of this simple program that displays IP address is due to my use of the Go net package.

Yeah, using net is eliminating the benefits of using fiber/fasthttp.

I think this question is more related to fasthttp. Once they support proxy v2, it would be available for fiber.

**Comment by auxo86** [comment]
Thanks. I will forward this question to fasthttp and close this issue.
