### ISSUE TITLE
🐛 [Bug]:  BodyParser doesn't return error if the payload doesn't match the json structure

### ISSUE THREAD

**Issue by marcodd23** [gofiber/fiber#2378]
### Bug Description

I'm using the fiber v2.42.0, and maybe I'm doing something wrong, but when I parse the body , if it contains invalid fields it doesn't return an error, but just leave them default for the variable.

### How to Reproduce

Just a basic post handler

### Expected Behavior

When the body of the request is not valid, the parsing should fail

### Fiber Version

v2.42.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

type BaseController struct {
	config config.Config
	userService service.UserService
	logger logger.LoggerManager
}

type User struct {
	Username string `json:"username"`
	Password string `json:"password"`
	IsActive bool `json:"isActive"`
}

func (c BaseController) CreateUser(ctx *fiber.Ctx) error {	
	ctx.Type("json", "utf-8")
	user := new(model.User)
	errParser := ctx.BodyParser(user)
	if errParser != nil {
		return ctx.Status(fiber.StatusUnprocessableEntity).JSON(fiber.Map{
			"errors": errParser.Error(),
		  })
	}

	//c.logger.LogDebugf("Adding user: %s, %s, %s", ctx.Params("username"), ctx.Params("password"), ctx.Params("isActive"))
	errService := c.userService.CreateUser(user)
	if errService != nil {
		c.logger.LogError("error creating User: %s", errService)
		return ctx.Status(fiber.StatusInternalServerError).JSON("error creating User")
	}
	return ctx.Status(fiber.StatusCreated).JSON("User Created")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
what does your request look like ? 

the body parser only transfers the values of the body into the struct and does not do any validation
![image](https://user-images.githubusercontent.com/7063188/226452260-6961590e-e1da-4ea4-91dc-39e52c973995.png)

https://docs.gofiber.io/next/api/ctx#bodyparser


for validation you have to follow this concept
https://docs.gofiber.io/next/guide/validation

**Comment by ReneWerner87** [comment]
you can of course customize the parser a bit, so that it returns error messages if there are unknown keys etc.
https://docs.gofiber.io/next/api/ctx#setparserdecoder

**Comment by ReneWerner87** [comment]
@marcodd23 does it help you ?
