### ISSUE TITLE
🤔 Server settings like IdleTimeout, ReadTimeout, WriteTimeout

### ISSUE THREAD

**Issue by talgat-ruby** [gofiber/fiber#238]
**Question description**
Since was removed from settings the IdleTimeout, ReadTimeout, WriteTimeout params. How to set them now?

[v1.8.2 changelog](https://github.com/gofiber/fiber/issues/203)

**Comment by Fenny** [comment]
@talgat-ruby, thanks for submitting your first issue!
We removed most of the settings to keep it more in-lined with `expressjs` and keep it simple.
If you have a good use case for `IdleTimeout`, `ReadTimeout` or `WriteTimeout ` I would love to know and we could consider to re-add these in `v1.8.41`

```go
// ReadTimeout is the amount of time allowed to read
// the full request including body. The connection's read
// deadline is reset when the connection opens, or for
// keep-alive connections after the first byte has been read.
//
// By default request read timeout is unlimited.
ReadTimeout time.Duration

// WriteTimeout is the maximum duration before timing out
// writes of the response. It is reset after the request handler
// has returned.
//
// By default response write timeout is unlimited.
WriteTimeout time.Duration

// IdleTimeout is the maximum amount of time to wait for the
// next request when keep-alive is enabled. If IdleTimeout
// is zero, the value of ReadTimeout is used.
IdleTimeout time.Duration
```

**Comment by talgat-ruby** [comment]
@Fenny thanks.

I am newb in go and was learning through book [Let's Go](https://lets-go.alexedwards.net/). Where author sets up server and adds IdleTimeout, ReadTimeout, WriteTimeout. It just seems good idea to have flexibility, because both go's native http server and fasthttp have those options.

**Comment by Fenny** [comment]
Oh I wasn't aware that the native http server got these options too, I will add these back in `v1.8.41 today` 👍

**Comment by Fenny** [comment]
Closing this issue since `v1.8.41` got merged 🍾

**Comment by talgat-ruby** [comment]
@Fenny thanks. The fiber is awesome.
