### ISSUE TITLE
How embed a folder with a react app? 🤗 [Question]: 

### ISSUE THREAD

**Issue by thejus-r** [gofiber/fiber#2380]
### Question Description

I'm trying to create a project where Fiber acts a the backend and React as frontend, I used app.Static.. when build, it works when the exe file is in the same dir. But when I run the binary else where.. the react app is not showing. I'm thinking its the problem with embedding the folder into the binary itself

I saw solutions for fiber 1.x, using some middleware like packr .. 

How can I do this in fiber v2?

this is my folder structure

project
  -  go.mod
  - go.sum
  - main.go
  - ui/
      - dist/
      - src/
      - public/

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
either you specify an absolute path when using app.Static
or you use the exe in the root folder relative to your defined path 

delivering the data should work with app.Static

for v2 there are the same solutions
https://docs.gofiber.io/api/middleware/filesystem

**Comment by ReneWerner87** [comment]
@thejus-r does it help ? can we close this question?

**Comment by thejus-r** [comment]
yeah @ReneWerner87, it works.. thankyou!
