### ISSUE TITLE
🐛 [Bug]: ctx.Accepts("text", "json") with headerAccept, "text/*, application/json" fails on macOS 

### ISSUE THREAD

**Issue by sixcolors** [gofiber/fiber#2383]
### Bug Description

ctx.Accepts("text", "json") with headerAccept, "text/*, application/json" is not the same on macOS and linux

On macOS it returns "text"

On linux it returns "json"

### How to Reproduce

Run test on macOS and linux

### Expected Behavior

consistent return and tests pass

### Fiber Version

v2.43.0

### Code Snippet (optional)

```go
func Test_Ctx_Accepts(t *testing.T) {
	t.Parallel()
	app := New()
	c := app.AcquireCtx(&fasthttp.RequestCtx{})
	defer app.ReleaseCtx(c)

	c.Request().Header.Set(HeaderAccept, "text/*, application/json")
	utils.AssertEqual(t, "json", c.Accepts("json", "text"))
}

// called with above params DEBUG comments added
func (c *Ctx) Accepts(offers ...string) string {
	if len(offers) == 0 {
		return ""
	}
	header := c.Get(HeaderAccept)
	if header == "" {
		return offers[0]
	}

	spec, commaPos := "", 0
	for len(header) > 0 && commaPos != -1 {
		commaPos = strings.IndexByte(header, ',')
		if commaPos != -1 {
			spec = utils.Trim(header[:commaPos], ' ')
		} else {
			spec = utils.TrimLeft(header, ' ')
		}
		if factorSign := strings.IndexByte(spec, ';'); factorSign != -1 {
			spec = spec[:factorSign]
		}

		var mimetype string
		for _, offer := range offers { // DEBUG first loop "text"
			if len(offer) == 0 {
				continue
				// Accept: */*
			} else if spec == "*/*" {
				return offer
			}

			if strings.IndexByte(offer, '/') != -1 {
				mimetype = offer // MIME type
			} else {
				mimetype = utils.GetMIME(offer) // DEBUG on linux: "application/octet-stream", on macOS: "text/plain; charset=utf-8"
			}

			if spec == mimetype {
				// Accept: <MIME_type>/<MIME_subtype>
				return offer
			}

			s := strings.IndexByte(mimetype, '/')
			// Accept: <MIME_type>/*
			if strings.HasPrefix(spec, mimetype[:s]) && (spec[s:] == "/*" || mimetype[s:] == "/*") { // DEBUG first loop mimeType = "text/*"
				return offer // DEBUG on macOS text spec matches the string before / (text), on linux text does not match string before / (application)
			}
		}
		if commaPos != -1 {
			header = header[commaPos+1:]
		}
	}

	return ""
}
```

### Further context

Caused by: utils.GetMIME("text"), which calls mime.TypeByExtension("." + extension) on macOS returns "text/plain; charset=utf-8" while on linux it returns ""

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by sixcolors** [comment]
If we add "text" to http.go mime extensions

// - Add "text" as an alias for "text/plain" as recommended per https://datatracker.ietf.org/doc/html/rfc2046#section-4.1var mimeExtensions = map[string]string{
...
"text":    "text/plain",
"txt":     "text/plain",
...

**Comment by sixcolors** [comment]
The section of RFC 2046 that defines the "text" media type and its subtypes is Section 4.1. In this section, the RFC states:

The top-level media type "text" has a number of subtype values which
indicate human-readable text in one form or another. The primary
subtype, "plain", indicates plain (unformatted) text.

...

Other subtypes of "text" usefully include types that represent
formatted text containing controlled white space (e.g., "text/tab-
separated-values") and text representing markup languages (e.g.,
"text/html").

...

It is important to note that "text" cannot be assumed to be
anything other than a structured byte sequence whose precise
structure is not generally known to the recipient.

...

The recommended practice for the Internet is to label human-
readable content types as "text/plain" and most machine-readable
formats as "application/octet-stream".

This passage implies that "text" is a top-level media type that encompasses various subtypes, including "text/plain". Later in the same section, the RFC notes that "text/plain" is the recommended subtype for human-readable content types, suggesting that "text" can be used as an alias for "text/plain" in these contexts.

**Comment by ReneWerner87** [comment]
Its related to https://github.com/gofiber/fiber/pull/2340

**Comment by sixcolors** [comment]
> Its related to #2340

I think adding text to the mime map would be an acceptable solution to normalize the behavior.

But what about the specific scenario: if text is a mime type matching text/ in type inner loop should that return first? Or should it check type or subtype match?

If so the Accepts code needs to be updated. 

Thoughts?

**Comment by sixcolors** [comment]
And what about the q value? https://developer.mozilla.org/en-US/docs/Glossary/Quality_values

**Comment by ReneWerner87** [comment]
@derkan can you help here

**Comment by derkan** [comment]
@sixcolors, what is the go version?

I've tested with go1.19.7 and by adding a new test line to [`ctx_test.go`](https://github.com/gofiber/fiber/blob/master/ctx_test.go#L38) like this:

```go
...
c.Request().Header.Set(HeaderAccept, "text/*, application/json")
...
utils.AssertEqual(t, "json", c.Accepts("text", "json"))
```

Unfortunately I got same result: "json" on macOS for both go versions(and fiber master@latest). Am I missing something or this problem is because of go version?

**Comment by sixcolors** [comment]
> @sixcolors, what is the go version?
> 
> I've tested with go1.19.7 and by adding a new test line to [`ctx_test.go`](https://github.com/gofiber/fiber/blob/master/ctx_test.go#L38) like this:
> 
> ```go
> ...
> c.Request().Header.Set(HeaderAccept, "text/*, application/json")
> ...
> utils.AssertEqual(t, "json", c.Accepts("text", "json"))
> ```
> 
> Unfortunately I got same result: "json" on macOS for both go versions(and fiber master@latest). Am I missing something or this problem is because of go version?

1.20.2

**Comment by sixcolors** [comment]
> > @sixcolors, what is the go version?
> > I've tested with go1.19.7 and by adding a new test line to [`ctx_test.go`](https://github.com/gofiber/fiber/blob/master/ctx_test.go#L38) like this:
> > ```go
> > ...
> > c.Request().Header.Set(HeaderAccept, "text/*, application/json")
> > ...
> > utils.AssertEqual(t, "json", c.Accepts("text", "json"))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Unfortunately I got same result: "json" on macOS for both go versions(and fiber master@latest). Am I missing something or this problem is because of go version?
> 
> 1.20.2

However it probably has more to do with macOS install than go version looking at https://cs.opensource.google/go/go/+/refs/tags/go1.20.2:src/mime/type.go;l=102

I’ll check the files when I’m back on a computer (on phone right now)

**Comment by derkan** [comment]
I've also tested with following line added to [ctx_test.go](https://github.com/gofiber/fiber/blob/master/ctx_test.go#L38) on macOS and go1.20.2, no problem.

```go
c.Request().Header.Set(HeaderAccept, "text/*, application/json")
utils.AssertEqual(t, "json", c.Accepts("text", "json"))
```

**Comment by sixcolors** [comment]
I'm seeing .text registered with text edit. So that should be on basically every macOS install...

mdls -name kMDItemContentTypeTree example.text 
kMDItemContentTypeTree = (
    "public.plain-text",
    "public.text",
    "public.data",
    "public.item",
    "public.content"
)

duti -x text
TextEdit.app
/System/Applications/TextEdit.app
com.apple.TextEdit

let me write a sample app.

**Comment by sixcolors** [comment]
@derkan made a sample and test pass using CI GitHub action but fails locally. Checking a fresh install of macOS to make sure.

https://github.com/sixcolors/textmime/
https://github.com/sixcolors/textmime/actions/runs/4524905041

~/textmime (main) » go test -v ./...                                                                                                                     sixcolors@Jasons-MacBook-Pro
=== RUN   TestAccepts
    main_test.go:13: mimetype is text/plain; charset=utf-8, want application/json
--- FAIL: TestAccepts (0.00s)
FAIL
FAIL    github.com/sixcolors/textmime   0.596s
FAIL

**Comment by sixcolors** [comment]
@derkan yes it fails on multiple local macOS versions including a fresh install of the latest macOS

Please see the test project.

**Comment by sixcolors** [comment]
@ReneWerner87 and @derkan 

The other part is this:

```
...
c.Request().Header.Set(HeaderAccept, "text/*, application/json")
...
utils.AssertEqual(t, "json", c.Accepts("json", "txt"))
```

That should still pass, right? If so then the logic in Accepts is wrong.

**Comment by ReneWerner87** [comment]
I think the accepts method works wrong

instead of going through the arguments in the loop and comparing them one by one with the header values

the header values are split and compared with the passed arguments one after the other
