### ISSUE TITLE
🐛 [Bug]: BodyParsers not being able to parse correctly

### ISSUE THREAD

**Issue by gutrapp** [gofiber/fiber#2392]
### Bug Description

This is very weird, I've checked all the types, I dont believe I've made any typos, so I don't understand why it isn't being able to parse it. It keeps giving me the unprocessable entity error response. I really need some help it's my first time doing anything with Fiber and this is driving me insane

### How to Reproduce

server := fiber.New(fiber.Config{
		JSONEncoder: json.Marshal,
		JSONDecoder: json.Unmarshal,
	})

	store = session.New(session.Config{
		// CookieSecure: true, for https
		Expiration:     time.Hour * 5,
		CookieHTTPOnly: true,
		CookieSameSite: "none",
	})

	server.Use(Middleware(), cors.New(cors.Config{
		AllowCredentials: true,
		AllowOrigins:     "*",
		AllowHeaders:     "Access-Control-Allow-Origin, Content-Type, Origin, Accept",
	}))

Start a fiber server with that and some more routes so that you can actually make a call from the front-end, I'm using Vite.

### Expected Behavior

Parse body correctly and place the data into a variable.

### Fiber Version

Fiber v2.42.0

### Code Snippet (optional)

```go
type User struct {
	gorm.Model
	ID        uint   `gorm:"primaryKey:autoIncrement" json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Telephone string `json:"telephone"`
	Age       string `json:"age"`

	TestTaken           bool                `json:"testTaken"`
	Type                uint                `json:"type"`
	Admin               bool                `json:"admin"`
	ResultMBTI          ResultMBTI          `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	ResultLife          ResultLife          `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	ResultSelfKnowledge ResultSelfKnowledge `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	ResultLoveLanguage  ResultLoveLanguage  `gorm:"constraint:OnUpdate:CASCADE,OnDelete:CASCADE;"`
	Key                 string              `gorm:"unique" json:"key"`
	Password            string              `json:"password"`
}

func register(c *fiber.Ctx) error {
	c.Accepts("application/json")

	var user db.User

	err := c.BodyParser(&user)
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"message": "Error parsing body!" + err.Error(),
		})
	}

	password, bcErr := bcrypt.GenerateFromPassword([]byte(user.Password), 14)
	if bcErr != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"message": "Error encrypting password!" + bcErr.Error(),
		})
	}

	user = db.User{
		TestTaken: false,
		Admin:     false,
		Type:      user.Type,
		Key:       user.Key,
		Password:  string(password),
	}

	err = db.RegisterUser(&user)
	if err != nil {
		return c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"message": "Error registering user!" + err.Error(),
		})
	}

	return c.Status(fiber.StatusOK).JSON(fiber.Map{
		"message": "User registered!",
	})
}

Front-end Code:

await fetch("http://localhost:4000/admin", {
      method: "POST",
      body: JSON.stringify({
        name: "default",
        email: "default",
        telephone: "default",
        age: 999,
        testTaken: false,
        type: parseInt(form.type),
        admin: false,
        key: form.key,
        password: form.pass,
      }),
      credentials: "include",
    });
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Which fields are not mapped correctly? What are you trying to do with the c. Accepted method?
Which header is used to transfer the contents?

**Comment by ReneWerner87** [comment]
Are you using the standard decoder/encoder for json? If not please try this one first

**Comment by ReneWerner87** [comment]
![image](https://user-images.githubusercontent.com/7063188/229072791-cd4ab0ec-4b74-4eaf-bd37-15aab6905290.png)
![image](https://user-images.githubusercontent.com/7063188/229072847-0af0d6a0-5cb2-417b-905e-5395587e27ee.png)
looks like the fetch is misconfigured and not using the correct header
![image](https://user-images.githubusercontent.com/7063188/229073059-71e3bb6a-f411-4dd3-8111-25c1c5cac11d.png)

**Comment by ReneWerner87** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#uploading_json_data

```js
fetch("http://localhost:3000/test", {
  method: "POST",
    headers: {
    "Content-Type": "application/json",
  },
  body: JSON.stringify({
    name: "default",
    email: "default",
    telephone: "default",
    age: 999,
    testTaken: false,
    type: 10,
    admin: false,
    key: "foo",
    password: "testPW",
  }),
  credentials: "include",
}).then();
```
![image](https://user-images.githubusercontent.com/7063188/229073560-1c00c1b8-b1d3-4030-90bd-e5b7f3c47171.png)

![image](https://user-images.githubusercontent.com/7063188/229073543-21d90d9f-d578-4ff5-8cc2-e51e7fd70a9d.png)

![image](https://user-images.githubusercontent.com/7063188/229073701-e5609064-ce23-4226-a59f-bedf6a8e84b1.png)
you configured string, but in your frontend example you send integers



after this fix
![image](https://user-images.githubusercontent.com/7063188/229073954-264937a2-0fb8-4a38-974c-354e7997eb96.png)

![image](https://user-images.githubusercontent.com/7063188/229073985-c4ecc887-97b3-49eb-9da4-7f413c007f78.png)
@gutrapp from my point of view we can close the report, it was just a wrong usage in the frontend and error in your struct

**Comment by ReneWerner87** [comment]
the test setup code
```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

type User struct {
	ID        uint   `gorm:"primaryKey:autoIncrement" json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Telephone string `json:"telephone"`
	Age       uint   `json:"age"`

	TestTaken bool   `json:"testTaken"`
	Type      uint   `json:"type"`
	Admin     bool   `json:"admin"`
	Key       string `gorm:"unique" json:"key"`
	Password  string `json:"password"`
}

func register(c *fiber.Ctx) error {
	var user User

	err := c.BodyParser(&user)
	if err != nil {
		fmt.Println(err)
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"message": "Error parsing body!" + err.Error(),
		})
	}

	return c.Status(fiber.StatusOK).JSON(user)
}

func main() {
	app := fiber.New()
	app.Use(logger.New())

	// Example 1 - check whether the origin is any scheme or port on localhost
	app.Post("/test", register)

	log.Fatal(app.Listen(":3000"))
}

```

**Comment by gutrapp** [comment]
Oh man sorry this is what I get for being a hothead, thank you so much!

**Comment by gutrapp** [comment]
@ReneWerner87, when I add the Content-Type header to the fetch request, I get a CORS error, but when I remove it, it is normal and it just gives me the unprocessable entity error, can you help.

**Comment by ReneWerner87** [comment]
Share your cors configuration, i think you must allow the header

**Comment by gutrapp** [comment]
cors.New(cors.Config{
		AllowCredentials: true,
		AllowOrigins:     "http://127.0.0.1:5173",
		AllowHeaders:     "Access-Control-Allow-Origin, Content-Type, Origin, Accept",
		AllowMethods:     "GET, PUT, DELETE, POST, OPTIONS",
	}))

**Comment by gutrapp** [comment]
Also using middleware but I don't think it has anything to do with the problem.

func Middleware() fiber.Handler {
	return AuthMiddleware
}

func AuthMiddleware(c *fiber.Ctx) error {
	session, err := store.Get(c)

	if strings.Split(c.Path(), "/")[1] == "auth" {
		return c.Next()
	}
	if err != nil {
		return c.Status(fiber.StatusInternalServerError).JSON(fiber.Map{
			"message": "User is not authorized",
		})
	}

	if session.Get(AUTH_KEY) == nil {
		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
			"message": "User is not authorized",
		})
	}

	return c.Next()
}

Just a checker if the user authorized or noth

**Comment by ReneWerner87** [comment]
Pls share the cors error message

**Comment by gutrapp** [comment]
Access to fetch at 'http://localhost:4000/admin' from origin 'http://127.0.0.1:5173/' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ReneWerner87** [comment]
Remove the Access-Control-Allow-Origin header from the cors config

**Comment by gutrapp** [comment]
Same error man

**Comment by gutrapp** [comment]
```
adminRouter := server.Group("/admin")
	adminRouter.Post("/", register)

	authRouter := server.Group("/auth")
	authRouter.Post("/login", login)
	authRouter.Delete("/logout", logout)
	authRouter.Get("/", logged)
	authRouter.Get("/admin", isAdmin)

	userRouter := server.Group("/user")
	userRouter.Get("/", getUser)

	mbtiRouter := userRouter.Group("mbti")
	mbtiRouter.Post("/", saveResultMBTI)
	mbtiRouter.Get("/", getResultsMBTI)
	mbtiRouter.Get("/:id", getResultMBTI)

	lifeRouter := userRouter.Group("life")
	lifeRouter.Post("/", saveResultLife)
	lifeRouter.Get("/", getResultsLife)
	lifeRouter.Get("/:id", getResultLife)

	selfKnowledgeRouter := userRouter.Group("mbti")
	selfKnowledgeRouter.Post("/", saveResultSelfKnowledge)
	selfKnowledgeRouter.Get("/", getResultsSelfKnowledge)
	selfKnowledgeRouter.Get("/:id", getResultSelfKnowledge)

	loveLanguageRouter := userRouter.Group("life")
	loveLanguageRouter.Post("/", saveResultLoveLanguage)
	loveLanguageRouter.Get("/", getResultsLoveLanguage)
	loveLanguageRouter.Get("/:id", getResultLoveLanguage)
```

Here are my routes, only the ones in the /auth work, and the other ones do also work but not when I add the Content-Type header to my fetch request

**Comment by ReneWerner87** [comment]
Try the wildcard as origin configuration in your cors middleware

**Comment by gutrapp** [comment]
Still, not working

**Comment by gutrapp** [comment]
```
const res = await fetch("http://localhost:4000/auth/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify(data),
    });
```

For example, this call works even with the added header, but the other one don't

**Comment by gutrapp** [comment]
Btw, I'm using react-router-dom so my front-end has multiple routes. Maybe that's the problem somehow

**Comment by ReneWerner87** [comment]
> Still, not working

But this must work
Then there is another check in between

**Comment by gutrapp** [comment]
Exactly, that's what I'm thinking it SHOULD work, but it doesn't

**Comment by ReneWerner87** [comment]
Change mode of the fetch https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters

**Comment by gutrapp** [comment]
Switched to "no-cors" now I get a Internal Server Error (500) but with no error message just that? Even weirder

**Comment by gutrapp** [comment]
What I understand even less is why do my "/auth" routes all work, but all of my other ones don't

**Comment by ReneWerner87** [comment]
The order of the registered middlewares plays a role

Cors and logger should be at the beginning

**Comment by gutrapp** [comment]
WHAT, now it works? Why is it like that, just lost 3 days worth of work on a order error? lol

**Comment by gutrapp** [comment]
Thank you a lot for your time.

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/guide/routing#paths
![Screenshot_2023-04-01-15-25-35-89_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://user-images.githubusercontent.com/7063188/229291803-997e4da7-418f-4240-a75a-a8aeb18b29c4.jpg)
