### ISSUE TITLE
🚀 [Feature]: Split fiber.Storage to multiple interfaces

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2399]
### Feature Description

Go interfaces are meant to be small. The `fiber.Storage` should be split to multiple interfaces:

Instead of (as currently done):

```go
type Storage interface {
	Get(key string) ([]byte, error)
	Set(key string, val []byte, exp time.Duration) error
	Delete(key string) error
	Reset() error
	Close() error
}
```

we should do:

```go
type Storage interface {
	StorageGetter
	StorageSetter
	StorageDeleter
	StorageResetter
	StorageCloser
}

type StorageGetter interface {
	Get(key string) ([]byte, error)
}
type StorageSetter interface {
	Set(key string, val []byte, exp time.Duration) error
}
type StorageDeleter interface {
	Delete(key string) error
}
type StorageResetter interface {
	Reset() error
}
type StorageCloser interface {
	Close() error
}
```

This even is a backwards-compatible way for `v2`.

See also https://github.com/gofiber/fiber/pull/2253#pullrequestreview-1203444213

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
After a community vote, it was decided by majority vote that we do not need this feature after all.

Thanks for the effort
