### ISSUE TITLE
🚀 [Feature]: Consistent way of issuing fiber log messages / warnings / errors

### ISSUE THREAD

**Issue by leonklingele** [gofiber/fiber#2402]
### Feature Description

Currently, some fiber warnings & errors are done using `fmt.Print*`, some using `log.Print*`:

Examples:
- https://github.com/gofiber/fiber/blob/5a8bc44a1f55149d2f6b78ad128cb1d9c4c1c761/internal/template/html/html.go#L115
- https://github.com/gofiber/fiber/blob/5a8bc44a1f55149d2f6b78ad128cb1d9c4c1c761/app.go#L524

There should only be a single way of doing this.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
https://github.com/search?q=repo%3Agofiber%2Ffiber%20log.Printf(%22%5B&type=code

in every middleware with this pattern
"[MIDDLEWARENAME] - [LOG-LEVEL] text"

**Comment by efectn** [comment]
I'd prefer adding Logger interface instead of adding hardcoded `log.Print`

**Comment by kousikmitra** [comment]
I can pick it up if it's up for grab.

**Comment by leonklingele** [comment]
Go for it!! 🫨🥳🚀

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/pull/2444
