### ISSUE TITLE
🤗 [Question]:  Goroutine to the environment of the production quantity is high

### ISSUE THREAD

**Issue by Tristin-C** [gofiber/fiber#2403]
### Question Description

In the re-use of fiber v2.42.0 version, the number of goroutine will increase from time to time in the reproduction environment, so that the client cannot establish a connection. Check the figure through pprof profile, and help to answer whether it is related to the use of fiber framework itself. And with more instances, only one of them will have this problem, and the other will be normal

![image](https://user-images.githubusercontent.com/82650741/229396531-4aaf4dca-d16e-4189-be51-9efcf8e3eba5.png)

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
have you made the same observation with fasthttp?
can you find out what is the reason ?

**Comment by Tristin-C** [comment]
Not yet. We are limiting the number of Goroutines in the program through coroutpools to eliminate problems with the program itself.
Oddly enough, this problem occurs only one instance at a time

**Comment by Tristin-C** [comment]
Or is there anything you think I can do to identify the source of the problem

**Comment by leonklingele** [comment]
@Tristin-C can you tell in which release of fiber the issue was introduced?

**Comment by Tristin-C** [comment]
> @Tristin-C can you tell in which release of fiber the issue was introduced?

There was no problem when using v2.37, then upgraded to v2.40.1 because of timeout middleware, and then to v2.42.0 after a short time.
So if I have to say which version, I prefer the v2.40-v2.42 issue

**Comment by Tristin-C** [comment]
The possibility of coroutine leakage within the program has been ruled out

**Comment by Tristin-C** [comment]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/82650741/236717572-bea5553c-4ee3-4164-a735-f36ba041b478.png">

Could it be a problem with time-out middleware?

**Comment by Tristin-C** [comment]
@ReneWerner87 
https://github.com/valyala/fasthttp/pull/1435

**Comment by ReneWerner87** [comment]
> <img alt="image" width="907" src="https://user-images.githubusercontent.com/82650741/236717572-bea5553c-4ee3-4164-a735-f36ba041b478.png">
> 
> Could it be a problem with time-out middleware?

maybe, had you tried it without ?

problem with the timeout middleware is that we can't completely use the code we got from the fasthttp internal timeout handler solution, because there is some internal info missing here
https://github.com/valyala/fasthttp/blob/fa72f3cc3907a2ad8fd109db846ece8d0c03810f/server.go#L455
https://github.com/valyala/fasthttp/blob/fa72f3cc3907a2ad8fd109db846ece8d0c03810f/server.go#L461

can you try to recreate your problem with fasthttp directly and the timeout handler, if it is fixed there, we need to adjust our timeout middleware anyway

**Comment by Tristin-C** [comment]
Nothing to do with timeout middleware, this problem still occurs after use is turned off.

https://github.com/valyala/fasthttp/pull/1435

Doubt is the question, I will try to confirm my guess.

**Comment by ReneWerner87** [comment]
and if you equip your software with the fix to see if this would help

**Comment by Tristin-C** [comment]
ok, i will

**Comment by Tristin-C** [comment]
https://github.com/valyala/fasthttp/issues/1554

Added here is the status of some of the metrics related to pprof when the issue occurred after the upgrade to 2.45.0

**Comment by Tristin-C** [comment]
https://github.com/valyala/fasthttp/issues/1384

@ReneWerner87 

May I ask where this configuration is reflected

**Comment by ReneWerner87** [comment]
this setting is currently not reflected in the config 
if you want to use it , do this

![image](https://github.com/gofiber/fiber/assets/7063188/b2721756-76e4-4e95-b3be-58748ca9a544)

**Comment by Tristin-C** [comment]
ok, thanks
