### ISSUE TITLE
🤗 [Question]: .Get .Use declaration order

### ISSUE THREAD

**Issue by ferllings** [gofiber/fiber#2404]
### Question Description

Hello,

I understand the middlewares are executed in the declaration order, but
is it possible to declare .Use after .Get? Like in the following code?
It looks like if declared after .Get the .Use middleware is not executed.

### Code Snippet (optional)

```go
package main

import (
    "log"

    "github.com/gofiber/fiber/v2"
    "github.com/gofiber/websocket/v2"
)

func main() {
    app := fiber.New()

    // Route pour la méthode HTTP GET
    app.Get("/", func(c *fiber.Ctx) error {
        return c.SendString("Hello, World!")
    })

    // Route pour la connexion WebSocket
    app.Use("/", func(c *fiber.Ctx) error {
        if websocket.IsWebSocketUpgrade(c) {
            // Utilisez le middleware WebSocket pour la même route
            return websocket.New(func(ws *websocket.Conn) {
                for {
                    _, msg, err := ws.ReadMessage()
                    if err != nil {
                        log.Println(err)
                        return
                    }
                    log.Printf("Message reçu: %s", msg)

                    err = ws.WriteMessage(websocket.TextMessage, msg)
                    if err != nil {
                        log.Println(err)
                        return
                    }
                }
            })(c)
        }
        // Si la requête n'est pas une connexion WebSocket, renvoyez une erreur 404
        return fiber.ErrNotFound
    })

    app.Listen(":3000")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Yes it is possible
Consider that app.Use covers all requets methods and allows prefix matching

I.e. app.Get works only on example.de/
But app.Use works on everything after example.de/test

If the GET route is matched, however, this is preferred and since it does not contain ctx.Next in this case, the process ends there.

**Comment by ferllings** [comment]
Thanks for the clarification.
