### ISSUE TITLE
🐛 [Bug]: router treats group prefix of non-grouped routes as part of that group

### ISSUE THREAD

**Issue by acidjazz** [gofiber/fiber#2406]
### Bug Description

router treats group prefix of non-grouped routes as part of that group

### How to Reproduce

```go

// agent-related portal routes, and agent client routes
agent := app.Group("/agent", middleware.Auth)
agent.Get("/key", middleware.Agent, agentControllers.LinkingKey).Name("Get Linking Key")
app.Post("/agent/register", middleware.AppToken, agentControllers.Register).Name("Register an Agent")

```
if i fire a POST to /agent/register - the middleware.Auth fires=

### Expected Behavior

Since this is not part of the specified group/middleware it shouldn't use the middleware

One note: if i move the POST __above__ the group then it works:

```go

// agent-related portal routes, and agent client routes
app.Post("/agent/register", middleware.AppToken, agentControllers.Register).Name("Register an Agent")
agent := app.Group("/agent", middleware.Auth)
agent.Get("/key", middleware.Agent, agentControllers.LinkingKey).Name("Get Linking Key")
```

### Fiber Version

v2.42.0

### Code Snippet (optional)

```go
look above
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Not really a bug

You register a middleware on a prefix that you later use in your request which is then used

If you put the post in front of it
The order changes and this route will be triggered first.

The same way expressjs behaves
The groups are only for the better distribution in the code

At the end everything ends up in a flat list with a route, the information which request methods should match and if this is a prefix matching

**Comment by acidjazz** [comment]
Keep this open to update documentation?

**Comment by ReneWerner87** [comment]
Yes, i will provide a new part in the documentation

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/1495#issuecomment-901226189

**Comment by ReneWerner87** [comment]
Closed with
https://github.com/gofiber/fiber/commit/fcf708dfc2edb5dfcb5d8c527eff9f5b30755d89
https://github.com/gofiber/fiber/commit/c396d2aa45966dc4c0b249405aea9d2f69ac10a0
