### ISSUE TITLE
Cloudflare and reverse proxy support 

### ISSUE THREAD

**Issue by justevery** [gofiber/fiber#2419]
### Bug Description

A cloudflare and error issue.

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected Behavior

1) The reverse proxy thing if any attack comes expose the reverse proxy IP address and it shows everyone "dial connection brb brb ip". So your ip address gone, i look the reverse proxy, error handler documents but i don't see how i can made all errors to custom html page.

2) Ratelimit are need to have a cloudflare mode for get CF-Connecting-IP it so annoying because of i tried 5-6 way for get CF-Connecting-IP and the end i do.

3) The logging thing has same problem what i said on 2.

### Fiber Version

latest

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
no 2 and 3 are fixable with 

```go
app := fiber.New(fiber.Config{
	ProxyHeader: "CF-Connecting-IP",
})
```` 
or
````go
app := fiber.New(fiber.Config{
	ProxyHeader: fiber.HeaderXForwardedFor,
})
````
according to https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/ and
https://developers.cloudflare.com/fundamentals/get-started/reference/http-request-headers/#cf-connecting-ip

after that the ctx.IP method is using this header for the ip determination
https://docs.gofiber.io/api/ctx#ip

and the logger will log the right ip and the limiter middleware is also using the right one.
![image](https://user-images.githubusercontent.com/7063188/232280980-0485cdeb-522f-45fd-821e-56dc3b0ff657.png)
https://docs.gofiber.io/api/middleware/limiter#config

no 1 is solveable with the ModifiedResponse method
here a small example:
```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/proxy"
)

func main() {
	app := fiber.New()


	app.Use(
		proxy.Balancer(proxy.Config{
		        Servers:  []string{
		              "http://localhost:3001",
		              "http://localhost:3002",
	                },
			ModifyResponse: func(c *fiber.Ctx) error {
				if c.Response().StatusCode() == 502 { // Check if the response is a 502 (Bad Gateway) error
					c.Response().Reset() // Reset the response to clear the existing error message
					return c.Status(503).SendString("The requested service is currently unavailable. Please try again later."})
				}
				return nil
			},
		}),
	)

	err := app.Listen(":3000")
	if err != nil {
		fmt.Printf("Error starting server: %v", err)
	}
}

````

**Comment by justevery** [comment]
Well, the proxy.Balancer code has errors. I fixed it the syntax error if someone wants to use it.

`	app.Use(
		proxy.Balancer(proxy.Config{
		        Servers:  []string{
		              "http://localhost:3001",
		              "http://localhost:3002",
	                },
			ModifyResponse: func(c *fiber.Ctx) error {
				if c.Response().StatusCode() == 502 { // Check if the response is a 502 (Bad Gateway) error
					c.Response().Reset() // Reset the response to clear the existing error message
					return c.Status(503).SendString("The requested service is currently unavailable. Please try again later.")
				}
				return nil
			},
		}),
	)`

**Comment by justevery** [comment]
My problem isn't solved it still shows dial tcp errors..

**Comment by ReneWerner87** [comment]
@justevery Is it running? Can we mark the report as closed (answered)?

**Comment by ReneWerner87** [comment]
```go
package main

import (
	"errors"
	"log"
	"net"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/proxy"
	"github.com/gofiber/fiber/v2/utils"
)

func main() {
	app := fiber.New(fiber.Config{
		// Override default error handler
		ErrorHandler: func(ctx *fiber.Ctx, err error) error {
			code := fiber.StatusInternalServerError
			ctx.Set(fiber.HeaderContentType, fiber.MIMETextPlainCharsetUTF8)

			var netError *net.OpError
			if errors.As(err, &netError) {
				return ctx.Status(fiber.StatusBadGateway).SendString(utils.StatusMessage(fiber.StatusBadGateway))
			}
			var e *fiber.Error
			if errors.As(err, &e) {
				code = e.Code
			}

			return ctx.Status(code).SendString(err.Error())
		},
	})
	app.Use(proxy.Balancer(proxy.Config{
		Servers: []string{
			"http://139.144.180.160/",
		},
		ModifyRequest: func(ctx *fiber.Ctx) error {
			ctx.Request().Header.Add("CF-Connecting-IP", ctx.IP())
			return nil
		},
	}))

	log.Fatalln(app.Listen(":8080"))
}

```

**Comment by justevery** [comment]
René patiently solved my problem, I thank him ♥

**Comment by ReneWerner87** [comment]
@efectn @gaby @leonklingele @li-jin-gou 
should we add a part for the net.Error(s) in our default error handler
so that we do not pass on network information for security reasons ?

```go
app := fiber.New(fiber.Config{
		// Override default error handler
		ErrorHandler: func(ctx *fiber.Ctx, err error) error {
			code := fiber.StatusInternalServerError
			ctx.Set(fiber.HeaderContentType, fiber.MIMETextPlainCharsetUTF8)

			var netError net.Error
			if errors.As(err, &netError) {
                // 502 - Bad Gateway or 503 - ServiceUnavailable
				return ctx.Status(fiber.StatusBadGateway).SendString(utils.StatusMessage(fiber.StatusBadGateway))
			}
			var e *fiber.Error
			if errors.As(err, &e) {
				code = e.Code
			}

			return ctx.Status(code).SendString(err.Error())
		},
	})
```

**Comment by gaby** [comment]
@ReneWerner87 Yes, may be worth it.

**Comment by leonklingele** [comment]
Yes, definitely! All my apps using fiber additionally wrap the fiber errors for that specific reason, so only my own, well-known internal errors get exposed.

**Comment by ReneWerner87** [comment]
Then let us do this

**Comment by leonklingele** [comment]
Don’t forget to log the original error. It’ll be a pain (or even close to impossible) to debug.

**Comment by ReneWerner87** [comment]
> Don’t forget to log the original error. It’ll be a pain (or even close to impossible) to debug.

![Bildschirmfoto 2023-04-17 um 08 13 43](https://user-images.githubusercontent.com/7063188/232400146-df1fbb6c-4aa8-43ba-822c-a20e67cddbca.png)

not a problem, the logger is logging the error message

what should i take ? 502 or 503 ?
