### ISSUE TITLE
[1.8.33] Broken version

### ISSUE THREAD

**Issue by waghanza** [gofiber/fiber#242]
Hi @Fenny,

Our bot track `fiber` and show that **modules** defined for `1.8.33` is not well define

The version `1.0.0` of `template` does not exists in https://github.com/gofiber/fiber/blob/ed2db21172895fa67dab18131aeca9fd21812a04/go.mod#L7

Regards,

PS : If you can update `fiber` in https://github.com/the-benchmarker/web-frameworks in the same time it will be :heart:

**Comment by Fenny** [comment]
Thanks @waghanz, I created a PR https://github.com/the-benchmarker/web-frameworks/pull/2383/
