### ISSUE TITLE
🚀 [Feature]: Can you provide a case study of all aspects of mvc

### ISSUE THREAD

**Issue by qingshanshui** [gofiber/fiber#2420]
### Feature Description

Can you provide a case study of all aspects of mvc，
There are many functions that cannot be achieved using mvc

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the feature

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by li-jin-gou** [comment]
refer to https://github.com/gofiber/recipes
