### ISSUE TITLE
🐛 [Bug]: 

### ISSUE THREAD

**Issue by jney** [gofiber/fiber#2422]
### Bug Description

setting following cors config

```go
srv.Use(cors.New(cors.Config{
	AllowCredentials: true,
	AllowOriginsFunc: func(string) bool { return true },
}))
```

got the following error:

> Access to resource at 'https://foo.xyz/v1/events?ik=1681915937.ch0008e3f8kfks98mrl0&t=PA-34761163' from origin 'https://foo.click' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

### How to Reproduce

check

### Expected Behavior

`Access-Control-Allow-Origin` should be set to origin, not `*`

### Fiber Version

v2.44.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "github.com/gofiber/fiber/v2/middleware/cors"
import "log"

func main() {
  app := fiber.New()

  app.Use(cors.New(cors.Config{
    AllowCredentials: true,
    AllowOriginsFunc: func(string) bool { return true },
  }))

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
@Jamess-Lucass can you help here

**Comment by Jamess-Lucass** [comment]
> @Jamess-Lucass can you help here

Yeah sure, you may assign this issue to me.

Cause:

```go
if allowOrigin == "" && cfg.AllowOriginsFunc != nil {
    if cfg.AllowOriginsFunc(origin) {
        allowOrigin = origin
    }
}
```

`allowOrigin` is actually `*` as this is the default value set if nothing is defined.

Will fix this and add a test to cover this use case, mb.
