### ISSUE TITLE
🐛 [Bug]: use sync.Map maybe error

### ISSUE THREAD

**Issue by zing-dev** [gofiber/fiber#2425]
### Bug Description

```go
w.app.Use(favicon.New())
	a := sync.Map{}
	w.app.Get("/p/:p", func(ctx *fiber.Ctx) error {
		p := ctx.Params("p")
		a.Store(p, true)
		fmt.Println(p, p == "112233", ctx.Request().URI())
		return ctx.JSON(true)
	})
	w.app.Get("/g/:p", func(ctx *fiber.Ctx) error {
		p := ctx.Params("p")
		_, ok := a.Load(ctx.Params("p"))
		_, ok2 := a.Load(p)
		fmt.Println(ctx.Request().URI())
		a.Range(func(key, value any) bool {
			//  112233 vicon. false??
			fmt.Println("->", ctx.Params("p"), key.(string), p == key.(string))
			return true
		})
		return ctx.SendString(fmt.Sprintf("%v %v", ok, ok2))
	})
```

request /p/112233 response true
request /g/112233 response maybe true or false 
so print a ,sometimes print  112233 vicon. false ?? understand
but /*w.app.Use(favicon.New())*/ is ok

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected Behavior

request /p/112233 response true
request /g/112233 response maybe true or false 
so print a ,sometimes print  112233 vicon. false ?? understand
but /*w.app.Use(favicon.New())*/ is ok

### Fiber Version

2.43.0

### Code Snippet (optional)

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/favicon"
	"github.com/gofiber/fiber/v2/middleware/recover"
	"log-collector-server/helps"
	"log-collector-server/log"
	"net/http"
	"sync"
)

func init() {
	_ = helps.CreateDir(helps.DefaultLogPath)
}

type web struct {
	app *fiber.App
	//apiManager *api.Manager
}

func newWeb() *web {
	var w = &web{
		app: fiber.New(fiber.Config{
			AppName:   "日志数据收集服务器",
			BodyLimit: 100 * 1024 * 1024,
			ErrorHandler: func(c *fiber.Ctx, err error) error {
				log.L.Error(fmt.Sprintf("%s %s", c.IP(), err))
				_, _ = c.WriteString(fmt.Sprintf("oops: %s", err))
				c.Response().SetStatusCode(http.StatusBadRequest)
				return nil
			}}),
	}
	//w.apiManager = api.NewAPIManager(w.app)
	return w
}

func (w *web) run() {
	w.app.Use(recover.New())
	w.app.Use(favicon.New())
	a := sync.Map{}
	w.app.Get("/p/:p", func(ctx *fiber.Ctx) error {
		p := ctx.Params("p")
		a.Store(p, true)
		fmt.Println(p, p == "112233", ctx.Request().URI())
		return ctx.JSON(true)
	})
	w.app.Get("/g/:p", func(ctx *fiber.Ctx) error {
		p := ctx.Params("p")
		_, ok := a.Load(ctx.Params("p"))
		_, ok2 := a.Load(p)
		fmt.Println(ctx.Request().URI())
		a.Range(func(key, value any) bool {
			//  112233 vicon. false??
			fmt.Println("->", ctx.Params("p"), key.(string), p == key.(string))
			return true
		})
		return ctx.SendString(fmt.Sprintf("%v %v", ok, ok2))
	})
	//w.apiManager.RegisterRouter()
	log.L.Fatal(w.app.Listen(":7011"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by leonklingele** [comment]
Can you try

app := fiber.New(fiber.Config{
    Immutable: true,
})

Might be related to fiber‘s super dangerous non-immutable by default config.
Also see https://github.com/gofiber/fiber/issues/2242

**Comment by zing-dev** [comment]
thank you,I changed, it works,It seems like I need to read more documents now 😆

**Comment by ReneWerner87** [comment]
you can also use our copy function 
https://github.com/gofiber/fiber/blob/master/utils/convert.go#L40
then you don't have to set the whole application to immutable, because this creates allocations which are not always necessary and eat performance

default is that no allocations are created for them and references exist

this is enough in most cases, because you only use the parameters for searching or comparing and they are not needed after that

only if you want to use the data after sending the response, like you did in the example, it is necessary to make a copy of it

by the way this is valid for all data you can get via fiber and the internal core fasthttp
