### ISSUE TITLE
🚀 [Feature]: Support constraints for other method

### ISSUE THREAD

**Issue by 18183883296** [gofiber/fiber#2427]
### Feature Description

Constraints on path is wonderful, I think it would be nice to have it with other methord.

### Additional Context (optional)

Now, when add constraints on path, only GET and HEAD methods are allowed. Though I have other routes with other methods, they are rejected with response `Method Not Allowed`. I am not sure whether it's the proper behavior.
``` shell
Method Not Allowed
Allow: GET, HEAD
```

### Checklist:

- [x] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
Route constraints are working for all the methods
