### ISSUE TITLE
🤗 [Question]: How best to return JSON with different content-type?

### ISSUE THREAD

**Issue by sazzer** [gofiber/fiber#2428]
### Question Description

I'm playing with Fiber, and trying to get a clean solution for RFC-7807 Problem Detail responses. Which I've mostly done. The problem is the content types. These responses should have a `Content-Type` header of `application/problem+json` but Fibre is overriding this to just `application/json`.

What I've done is to write an `ErrorHandler` function that detects if my `error` is a `problem.Problem` type, and if so then handle it to return the correct response:

```go
package problem

import (
	"errors"

	"github.com/gofiber/fiber/v2"
)

func ErrorHandler(c *fiber.Ctx, err error) error {
	var problem Problem
	if errors.As(err, &problem) {
		c.Status(problem.statusCode)

		if len(problem.payload) > 0 {
			c.Set("content-type", "application/problem+json; charset=utf-8")

			return c.JSON(problem.payload)
		}

		return nil
	}

	return fiber.DefaultErrorHandler(c, err)
}
```

For the most part this works great. But the `c.JSON` call forcibly sets the `Content-Type` header, even if I've already set it.

Changing it to this does work, but feels just a bit wrong...
```go
		if len(problem.payload) > 0 {
			if err := c.JSON(problem.payload); err != nil {
				return err
			}

			c.Set("content-type", "application/problem+json; charset=utf-8")

			return nil
		}
```

Is there a better way to send a JSON response with an alternative content type? Or is this the best option?

Cheers

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
no currently, the content type is currently hard linked to the json encode functionality

https://github.com/gofiber/fiber/blob/0b5baf522d0af6a59ded5ef3ec9f536fef2c5907/ctx.go#L793-L801

but you can build your own helper method and execute your codeblock there

**Comment by sazzer** [comment]
Any interest in a PR for this? It would be very easy to have this method - and other ones - only set the content-type if it's not already set. 

Alternatively - but maybe of less interest - the `data` parameter could optionally implement an interface that defines the content-type, and if so then that's used in preference to the default.

**Comment by ReneWerner87** [comment]
for me it is too specific, so i would not like to include that
