### ISSUE TITLE
🤗 [Question]: i have an error while trying to use cors in my code 

### ISSUE THREAD

**Issue by mmalacarag** [gofiber/fiber#2431]
### Question Description

the following error is appearing in my code while trying to use cors and i dont know why, somebody know what is happenin ?

ERROR: panic: use: invalid handler func(*fiber.Ctx) error

MY MAIN CODE:
```go
  func main() {
  
	  database.Connect()
	  app := fiber.New()
  
	  app.Use(cors.New())
  
	  routes.SetupRoutes(app) // Cambiar a SetupRoutes
	  app.Listen(":50000")
  } 
```
MY CODE OF MY FUNCTIONS:
```go
package controllers

import (
	"paquetes/database"
	"paquetes/models"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

func AllUsers(c *fiber.Ctx) error {
	var users []models.User
	database.DB.Preload("Role").Find(&users)
	return c.JSON(users)
}

func CreateUser(c *fiber.Ctx) error {

	var user models.User

	if err := c.BodyParser(&user); err != nil {
		return err
	}

	user.SetPasswprd("1234")

	database.DB.Create(&user)

	return c.JSON(user)
}

func GetUser(c *fiber.Ctx) error {
	id, _ := strconv.Atoi(c.Params("id"))

	user := models.User{
		Id: uint(id),
	}

	database.DB.Preload("Role").Find(&user)

	return c.JSON(user)
}

func UpdateUser(c *fiber.Ctx) error {
	id, _ := strconv.Atoi(c.Params("id"))

	user := models.User{
		Id: uint(id),
	}

	if err := c.BodyParser(&user); err != nil {
		return err
	}

	database.DB.Model(&user).Updates(user)

	return c.JSON(user)
}

func DeleteUser(c *fiber.Ctx) error {
	id, _ := strconv.Atoi(c.Params("id"))

	user := models.User{
		Id: uint(id),
	}

	database.DB.Delete(&user)

	return nil
}
```

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by Rorke76753** [comment]
can you provide more code of `SetupRoutes`? i think the problem should be here

**Comment by mmalacarag** [comment]
thank you for answering, this is my SetupRoutes code: 

package routes

import (
	"paquetes/controllers"
	"paquetes/middleware"

	"github.com/gofiber/fiber/v2"
)

func SetupRoutes(app *fiber.App) {
	app.Post("/api/register", controllers.Register)
	app.Post("/api/login", controllers.Login)

	app.Use(middleware.IsAuthenticated)

	app.Get("/api/User", controllers.User)
	app.Post("/api/logout", controllers.Logout)

	app.Get("/api/users", controllers.AllUsers)
	app.Post("/api/users", controllers.CreateUser)
	app.Get("/api/users/:id", controllers.GetUser)
	app.Put("/api/users/:id", controllers.UpdateUser)
	app.Delete("/api/users/:id", controllers.DeleteUser)
}

**Comment by Rorke76753** [comment]
should be `middleware.IsAuthenticated` because i can only find your panic message in fiber `Use` and `Group` method(since you only use `Use` here 😄

**Comment by mmalacarag** [comment]
oh ok, here is my code of the function IsAuthenticated :)

package middleware

import (
	"paquetes/util"

	"github.com/gofiber/fiber/v2"
)

func IsAuthenticated(c *fiber.Ctx) error {
	cookie := c.Cookies("jwt")
	if _, err := util.ParseJwt(cookie); err != nil {
		c.Status(fiber.StatusUnauthorized)
		return c.JSON(fiber.Map{
			"message": "Unauthenticated",
		})
	}
	return c.Next()
}

**Comment by Rorke76753** [comment]
i am sorry 😢 these code seems to work fine to me . apologize for could not help you

**Comment by ReneWerner87** [comment]
please check the function declaration and the return values of your functions
the error says that you are not fetching somewhere at this declaration

**Comment by mmalacarag** [comment]
Thanks for answering, im gonna check the function declaration and the return values, i think the declaration are fine but i need to check the return values 

And yes, the error happens when building, im gonna comment part per part

**Comment by mmalacarag** [comment]
I think I have a problem with the library, within my project, I ran the following code and the same error continues to appear

`package main

import (

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
)

func main() {

	app := fiber.New()

	app.Use(cors.New())

	app.Listen(":50000")
}`
what could be causing the error?

**Comment by mmalacarag** [comment]
hey, I have already solved the problem, i created a new proyecto and try cors in a simple example as Rorke, then i run 'go mod vendor', and that proyect worked. Then i get back to my main proyect and i reinstalled fiber and i run 'go mod vendor' again.
That's the solution!

**Comment by mmalacarag** [comment]
Thank you all 😁😁
