### ISSUE TITLE
🚀 [Feature]: Add Logger interface

### ISSUE THREAD

**Issue by kousikmitra** [gofiber/fiber#2433]
### Feature Description

As pointed out by @efectn in https://github.com/gofiber/fiber/issues/2402 and https://github.com/gofiber/fiber/pull/2432#issuecomment-1519594752 xurrently we log everything using default logger like `log.Print*`, this makes it hard to replace the standard logger with any other logger like logrus, zap etc.

We can add a logger interface and give an option to replace the default logger via `fiber.Config`

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  // Enable fiber to use slog to log messages.
  app := fiber.New(fiber.Config{Logger: slog.New()})

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by jonatan5524** [comment]
Hi, I am new to this repo and would like to tackle this issue

**Comment by ReneWerner87** [comment]
Sure

**Comment by jonatan5524** [comment]
I am a bit overwhelmed on this issue, I might search for an easier issue in this repo.

**Comment by iDevoid** [comment]
Hi team, I'd like to work on this. 
which one do you prefer as the best approach?
1. create a logger interface on the root level, and use a var Logger public type, so we can use it inside the middleware
directory:
```
app.go
.
.
log.go
```
interface + holder:
```
var Logger Logger

type Logger interface{
    ...
}
```
2. create a package log that has a logger interface, and has private var to hold the logger interface
directory:
```
log/
    log.go
    ....
app.go
```
interface + holder:
```
var logger Logger

type Logger interface{
    ...
}

func (log *logger) Print(...)
```

**Comment by ReneWerner87** [comment]
approach 2

**Comment by ReneWerner87** [comment]
we only need something like this
https://github.com/gofiber/fiber/pull/2432#issuecomment-1530983962

its just for the internal logging
we should not build up a new dependency there

**Comment by iDevoid** [comment]
From the code snippet, you shared.
I found that we are trying to create a local logging system from the standard library.
Instead of the initial issue as described above:

> this makes it hard to **replace the standard logger** with any other logger like logrus, zap etc.
> We can add a logger interface and give an option to replace the default logger via fiber.Config

If it is the case, I'd like to know the meaning of internal logging.
does internal log mean for the user/client to use or for fiber's dev to use?

if it's only a minimal log that is not really impacting. I actually agree that we should use a built-in log library but with a customized format.

But, let me know which one I should proceed with because your suggestion is contradicting the issue's description above.
thank you

**Comment by Skyenought** [comment]
I think we could add a log package to the fiber, assuming it's called `fiberlog`

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/flog"
	"log"
)

func main() {
	app := fiber.New(fiber.Config{
		Logger: fiberzap.NewLogger(),
	})
	app.Get("/hello/world", func(c *fiber.Ctx) error {
		flog.Info("Hello World!")
		return c.SendString("Hello World 👋!")
	})
	app.Get("/:option/world", func(c *fiber.Ctx) error {
		return c.SendString(c.Params("option") + " World 👋!")
	})
	log.Fatal(app.Listen(":3000"))
}
```
We can adapt libraries such as `zap`, `zerolog`, etc. by implementing the interface provided by `fiberlog`.

```go
package fiberlog

type Logger interface {
	Trace(v ...interface{})
	Debug(v ...interface{})
	Info(v ...interface{})
	Notice(v ...interface{})
	Warn(v ...interface{})
	Error(v ...interface{})
	Fatal(v ...interface{})
	Panic(v ...interface{})
}

// Control provides methods to config a logger.
type Control interface {
	SetLevel(Level)
	SetOutput(io.Writer)
}

// ...

type FullLogger interface {
	Logger
	FormatLogger
	CtxLogger
	Control
}

package fiberzap

import (
	"context"
	"github.com/gofiber/fiber/v2/flog"
	"go.uber.org/zap"
	"io"
)

var _ flog.FullLogger = (*Logger)(nil)

type Logger struct {
	l *zap.SugaredLogger
}

func (l *Logger) Trace(v ...interface{}) {
	//TODO implement me
	panic("implement me")
}

func (l *Logger) Debug(v ...interface{}) {
	//TODO implement me
	panic("implement me")
}
```
If this option works, I will try to propose a PR to solve this issue

**Comment by ReneWerner87** [comment]
Please without external dependencies.

**Comment by Skyenought** [comment]
yes, i thi

> Please without external dependencies.

Of course, pls assign me, let me try

**Comment by ReneWerner87** [comment]
@kousikmitra @efectn @gaby @leonklingele 
everyone okay with the solution in https://github.com/gofiber/fiber/pull/2499 ?
