### ISSUE TITLE
🤗 [Question]: Could we use Fiber as API Gateway

### ISSUE THREAD

**Issue by ArkjuniorK** [gofiber/fiber#2435]
### Question Description

I would like to build an API Gateway using Fiber since it had better middleware/feature support. Based on middleware list, there are some missing middleware that usually used to build an API Gateway such as:
- Circuit Breaker
- Retry Mechanism

Could I implement those feature in Fiber's middleware and of course could I use Fiber to build my API Gateway?
Thank you in advice.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
should be possible, if you have enough experience you can use fiber and fasthttp for almost all things

but keep in mind that fiber/fasthttp, but does not provide http2/3 support

Regarding middlewares
new functionality that makes it easier for others to use is always appreciated, we just have to decide if it should be in the core or in the contrib package

you are welcome to create pull requests for them, but I would suggest one per middleware

**Comment by ArkjuniorK** [comment]
Basically I'm new to Golang and Fiber and microservice world but based on your answer that means those feature could be implement. Correct me if I'm wrong so the feature above could be implemented at Middleware?

**Comment by ReneWerner87** [comment]
Yes think so

**Comment by ArkjuniorK** [comment]
ok, thanks @ReneWerner87
