### ISSUE TITLE
🤗 [Question]: how to reload routes after listening ?

### ISSUE THREAD

**Issue by kimkit** [gofiber/fiber#2443]
### Question Description

rt

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
For live reload, you can use https://docs.gofiber.io/extra/faq#how-can-i-use-live-reload-

**Comment by kimkit** [comment]
> For live reload, you can use https://docs.gofiber.io/extra/faq#how-can-i-use-live-reload-

air is for development, my routes is in config file, I want to reload when routes changed.

**Comment by ReneWerner87** [comment]
@kimkit 
what do you mean ? the routes have to be declared before you start the app, because we don't support dynamic routes 
(already described several times in various issues)

i.e. if your configuration changes, you also have to restart the server -> therefore air

**Comment by kimkit** [comment]
@ReneWerner87 ok,thanks
