### ISSUE TITLE
🤗 [Question]: How to handle QueryParser

### ISSUE THREAD

**Issue by frkntplglu** [gofiber/fiber#2447]
### Question Description

I have an enum and a struct. I want to get query parameter based on this struct. When I go to http://localhost:8080/?something=furkan I'm expecting to get error because something does not exist in my struct. However, it does not return any error. What's my mistake? Can you help me out? Thanks.

### Code Snippet (optional)

```go
type ChDomain string

const (
    ChDomainCimri  ChDomain = "cimri"
    ChDomainMarket ChDomain = "market"
)

type MainCategoryInfoParams struct {
    Domain ChDomain `query:"domain"`
}

queryParam := models.MainCategoryInfoParams{}
        
    if err := c.QueryParser(&queryParam); err != nil {
        fmt.Println("error : ", err)
        return nil // temporarily return nil
    }
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by cmd777** [comment]
You can use [validation](https://docs.gofiber.io/next/guide/validation) for it

Somewhat like this:

```go
package main

import (
	"log"

	"github.com/go-playground/validator"
	"github.com/gofiber/fiber/v2"
)

type (
	ChDomain string

	MainCategoryInfoParams struct {
		Domain ChDomain `validate:"gt=0" query:"domain"`
	}
)

var validate = validator.New()

func main() {
	app := fiber.New()

	app.Get("/", func(ctx *fiber.Ctx) error {
		queryParam := new(MainCategoryInfoParams)

		if err := ctx.QueryParser(queryParam); err != nil {
			log.Println(err)
			return ctx.SendString("Error!")
		}

		if err := validate.Struct(queryParam); err != nil {
			log.Println(err)
			return ctx.SendString("Error!")
		}
		log.Println(queryParam.Domain)

		return ctx.SendString("OK")
	})

	log.Fatal(app.Listen(":8080"))
}

```

```
(http://localhost:8080/?domain=) => Key: 'MainCategoryInfoParams.Domain' Error:Field validation for 'Domain' failed on the 'gt' tag 

(http://localhost:8080/?domain=somethingsomething) => somethingsomething
```

**Comment by frkntplglu** [comment]
This solved my problem. Thanks a lot. You made my day!!
