### ISSUE TITLE
🐛 [Bug]: Concurrency issue?

### ISSUE THREAD

**Issue by apikee** [gofiber/fiber#2450]
### Bug Description

String in array gets "merged" in a weird way. I believe the code snippet is the best explanation of the problem. Or am I doing something wrong? I have tested the same scenario with both Gin and Echo and it worked perfectly fine

### How to Reproduce

1. Create a public folder with index.html, index.css, index.js, link the files in the index.html
2. Serve the public folder through app.Static
3. Create empty string array and mutex
4. Add middleware that appends the c.OriginalURL to the array (lock the array before appending)
5. Print the array from within the middleware
6. Visit the website several times
7. You'll see the routes merged in a weird way:

```
[/]
[/ /index.css]
[/ /index.jss /index.js]
[/ /favicon.i /favicon. /favicon.ico]
[/ /favicon.i /favicon. /favicon.ico /]
[/ /index.css /index.cs /index.cssco / /index.css]
[/ /index.jss /index.js /index.jssco / /index.jss /index.js]
[/ /favicon.i /favicon. /favicon.ico / /favicon.i /favicon. /favicon.ico]
[/ /favicon.i /favicon. /favicon.ico / /favicon.i /favicon. /favicon.ico /]
[/ /index.css /index.cs /index.cssco / /index.css /index.cs /index.cssco / /index.css]
[/ /index.jss /index.js /index.jssco / /index.jss /index.js /index.jssco / /index.jss /index.js]
[/ /favicon.i /favicon. /favicon.ico / /favicon.i /favicon. /favicon.ico / /favicon.i /favicon. /favicon.ico]
```

### Expected Behavior

The url strings does not get merged, meaning instead of ` /index.cssco` will be `/index.css` and `/favicon.ico`

### Fiber Version

v2.44.0

### Code Snippet (optional)

```go
package main

import (
	"fmt"
	"sync"

	"github.com/gofiber/fiber/v2"
)

var mu sync.Mutex
var arr = []string{}

func main() {
        // Create a public folder with index.html, index.css, index.js, link the files in the index.html

	app := fiber.New()

	app.Use(func(c *fiber.Ctx) error {
		mu.Lock()
		arr = append(arr, c.OriginalURL())
		mu.Unlock()

		fmt.Println(arr)

		return c.Next()
	})

	app.Static("/", "public")

	app.Listen(":8080")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by apikee** [comment]
Well, it seems the `utils.CopyString` resolved the issue.
```
		mu.Lock()
		arr = append(arr, utils.CopyString(c.OriginalURL()))
		mu.Unlock()
```

Closing the bug

**Comment by gaby** [comment]
@apikee This behavior is explained in the first page of the docs: https://docs.gofiber.io/#zero-allocation
