### ISSUE TITLE
🐛 [Bug]: Ctx cookie in Extractor of csrf not working.

### ISSUE THREAD

**Issue by armada45-pixel** [gofiber/fiber#2451]
### Bug Description

In middleware csrf function CsrfFromCookie c *fiber.Ctx `c.Cookies(param)` not working.

https://github.com/gofiber/fiber/blob/9abb24597fb2cd58a45241326f104ce915116d0e/middleware/csrf/extractors.go#L42

### How to Reproduce

Use cookie in KeyLookup option in csrf.Config
```go
csrf.Config{
  KeyLookup:    "cookie:csrf_",
}
```

Or Extractor option
```go
csrf.Config{
  Extractor:      csrf.CsrfFromCookie("csrf_"),
}
```

### Expected Behavior

using cookie instead of header or form

### Fiber Version

v2.44.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"
import "github.com/gofiber/fiber/v2/middleware/csrf"

func main() {
  app := fiber.New()

  app.Use(csrf.New(csrf.Config{
    KeyLookup: "cookie:csrf_",
  }))

  app.Get("/", func(c *fiber.Ctx) error {
    return c.SendString(c.Cookies("csrf_")) // but working here
  })

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
What exactly do you mean by the term "does not work"?
Can you add an example request and an expectation?

**Comment by armada45-pixel** [comment]
My bad.
