### ISSUE TITLE
🐛 [Bug]: Parsing ParamParser on the struct with same params tag and field (case insensitive) 

### ISSUE THREAD

**Issue by Xyedo** [gofiber/fiber#2455]
### Bug Description

if i use paramParser with same field by name or field by tag name (case insensitive) like the code below and parsing it to a paramParser, 
```go
var userStruct struct {
	UUID            uuid.UUID
	SomethingUnique uuid.UUID `params:"uuid"`
}
c.ParamParser(&userStruct)
//it parsing to field UUID instead of field with tag `params:"uuid"`
```

the json return on that is 
```json
{"UUID":"0f7f2d1c-b56c-4ffd-8006-24eb378915e5","SomethingUnique":"00000000-0000-0000-0000-000000000000"}
```

it should be 
```json
{"UUID":"00000000-0000-0000-0000-000000000000","SomethingUnique":"0f7f2d1c-b56c-4ffd-8006-24eb378915e5"}
```

### How to Reproduce

1. create a folder
2. put it to the main file 
```go 
func main() {
	app := fiber.New()
	app.Get("/:uuid", h)
	log.Fatal(app.Listen(":3001"))
}

func h(c *fiber.Ctx) error {
	var userStruct struct {
		UUID            uuid.UUID
		SomethingUnique uuid.UUID `params:"uuid"`
	}
	err := c.ParamsParser(&userStruct)
	if err != nil {
		panic(err)
	}

	return c.Status(http.StatusOK).JSON(userStruct)
}

```

3. on the terminal, write it like
```bash
curl http://localhost:3001/0f7f2d1c-b56c-4ffd-8006-24eb378915e5
```

### Expected Behavior

i think it should prioritize the param tag first or case sensitive first, and then search about case incentive

### Fiber Version

v2.45.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
the normal and expected

if you use 2 times the same id for the schema parser of your structs

internally for all struct properties without annotation it tries to use the name of the property

this is also not a real world example, no one should use the same internal name for 2 different property names

**Comment by Xyedo** [comment]
its actually a bug from production app that our services uses that mapped the db table, the UUID is the primery child key, and SomethingUnique was the foreign parent key, but totally understandable by that decision, thank you. we just have to change to more specific name
