### ISSUE TITLE
🐛 [Bug]: 

### ISSUE THREAD

**Issue by JSchmidt63** [gofiber/fiber#2458]
### Bug Description

- go 1.20
- fiber 2.45.0
- windows 10
- chrome Version 113.0.5672.93 (Offizieller Build) (64-Bit)

1. build a main.go with embed dirs and files
the last modifed time it buggy?
![image](https://github.com/gofiber/fiber/assets/25293774/e971860a-d18a-41f7-9ae5-f9c2c07ff93c)

### How to Reproduce

1. Go to http://127.0.0.1:4000/public/
2. see to the last modifed time and date in dirs and files: last modified 0001-01-01 00:00:00 +0000 UTC

### Expected Behavior

i want to see the correct time in dirs and files

### Fiber Version

2.45.0

### Code Snippet (optional)

```go
package main

import (
    "embed"
    //"io/fs"
    "log"
    "net/http"

    "github.com/gofiber/fiber/v2"
    "github.com/gofiber/fiber/v2/middleware/filesystem"
)

// Embed a directory
//go:embed public/*
var embedDirStatic embed.FS

func main() {
	// Fiber instance
	app := fiber.New()

    // Access file "image.png" under `static/` directory via URL: `http://<server>/static/image.png`.
    // Without `PathPrefix`, you have to access it via URL:
    // `http://<server>/static/static/image.png`.
    app.Use("/public", filesystem.New(filesystem.Config{
        Root: http.FS(embedDirStatic),
        PathPrefix: "public",
        Browse: true,
    }))

	if err := app.Listen(":4000"); err != nil {
		log.Panic(err)
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
not really related to fiber
https://github.com/golang/go/issues/44854
