### ISSUE TITLE
🐛 [Bug]: Wrong handlers execution order in some mount cases

### ISSUE THREAD

**Issue by sadfun** [gofiber/fiber#2460]
### Bug Description

In some rare cases, fiber can wrongly build `app.treeStack`, breaking the execution chain. For example, it can call a handler from a mounted app before it calls a middleware specified at the top level earlier.

### How to Reproduce

In attached code snippet, fiber thinks that middleware printing `"i'm ignored!"` should be executed after `/methods/test` handler.

I think there are many more cases when this happens, but for now I'm able to reproduce only this one.

### Expected Behavior

Handlers execute in correct order.

### Fiber Version

2.45.0

### Code Snippet (optional)

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v2"
	"net/http"
)

func getApi() *fiber.App {
	var API = fiber.New()

	methods := API.Group("/methods")

	methods.Get("/test", func(c *fiber.Ctx) error {
		if c.Locals("hello") != "world" {
			panic("hello is not world")
		}
		return c.SendStatus(http.StatusOK)
	})

	return API
}

func main() {
	app := fiber.New()

	app.Use(func(c *fiber.Ctx) error {
		return c.Next()
	})

	app.Mount("/ws", fiber.New())

	app.Use(func(c *fiber.Ctx) error {
		return c.Next()
	})

	app.Get("/status", func(c *fiber.Ctx) error {
		return c.SendString("ok")
	})

	app.Use(func(c *fiber.Ctx) error {
		fmt.Println("i'm ignored!")
		c.Locals("hello", "world")
		return c.Next()
	})

	app.Mount("", getApi())

	test(app)
}

func test(app *fiber.App) {
	req, _ := http.NewRequest("GET", fmt.Sprintf("/methods/test"), nil)

	app.Test(req)
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
@sadfun 
big thanks for the good example

it really seems to be a bug

i assume it is a problem when i replace the mounted app
https://github.com/gofiber/fiber/blob/c56b4e66a0e4c6fe8ce070e95f1ee39773d01a0c/mount.go#L214-L218

will fix it in the next days and release it on friday

**Comment by ReneWerner87** [comment]
the problem is the positions i created when replacing the mounted app
![image](https://github.com/gofiber/fiber/assets/7063188/99ccb32c-f1ef-419b-99dc-264cd77f1c7a)

and after that they are sorted
![image](https://github.com/gofiber/fiber/assets/7063188/caf9f60b-7f68-4277-8b65-1bcd38334647)
