### ISSUE TITLE
🐛 [Bug]: Naming for Middlewares

### ISSUE THREAD

**Issue by efectn** [gofiber/fiber#2467]
### Bug Description

Currently naming on middlewares just working for last element of RequestMethods slice (it's PATCH as default). That's not expected behavior and it needs to be fixed.

```
Path: /, Method: GET, Name: 
Path: /, Method: HEAD, Name: 
Path: /, Method: POST, Name: 
Path: /, Method: PUT, Name: 
Path: /, Method: DELETE, Name: 
Path: /, Method: CONNECT, Name: 
Path: /, Method: OPTIONS, Name: 
Path: /, Method: TRACE, Name: 
Path: /, Method: PATCH, Name: test
```

### How to Reproduce

1. Add middleware and name it.
2. Naming will only apply to PATCH method.

### Expected Behavior

All methods of middleware should have the name.

```
Path: /, Method: GET Name: test
Path: /, Method: HEAD, Name: test
Path: /, Method: POST, Name: test
Path: /, Method: PUT, Name: test
Path: /, Method: DELETE, Name: test
Path: /, Method: CONNECT, Name: test
Path: /, Method: OPTIONS, Name: test
Path: /, Method: TRACE, Name: test
Path: /, Method: PATCH, Name: test
```

### Fiber Version

After naming feature introduced

### Code Snippet (optional)

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Use(func(c *fiber.Ctx) error {
		return c.Next()
	}).Name("test")

	for _, route := range app.GetRoutes() {
		fmt.Printf("Path: %s, Method: %s, Name: %s\n", route.Path, route.Method, route.Name)
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ytsruh** [comment]
I've submitted a PR for this just now
