### ISSUE TITLE
🚀 [Feature]: Disabling startupMessage during system startup and using custom message output.

### ISSUE THREAD

**Issue by javerVip** [gofiber/fiber#2471]
### Feature Description

Hello everyone,

I would like to disable the startupMessage when the system starts up (I know this can be achieved by setting DisableStartupMessage: true in App.Config), but I also want to use my own startupMessage after disabling it. Is there any other way to do this besides adding my own method before app.Listen?

Best regards,

### Code Snippet (optional)

```go
// config fiber Config startupMessage
app := fiber.New(fiber.Config{
	BodyLimit:             constants.DefaultBodyLimit,
	DisableStartupMessage: true,
	CustomStartupMessage: func(addr string, tls bool, pids string) {
		schemaStr := "http"
		if tls {
			schemaStr = "https"
		}
		fmt.Printf("Startup complete, PID is {%s} access address: %s://%s\n", pids, schemaStr, addr)
	},
})
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
this is currently not planned
but there is the possibility to write a start message per hook
https://docs.gofiber.io/guide/hooks#onlisten
