### ISSUE TITLE
🤗 [Question]: is it possible to pass a base64 png image as a parameter of Render function ?

### ISSUE THREAD

**Issue by sgaunet** [gofiber/fiber#2478]
### Question Description

Hi,

I'm generating a base64 png image. I have tested the file and it's ok. I'm trying to pass it as a parameter of Render function:

```
return c.Render("register", fiber.Map{
		"ImgB64s": b64s,
	})
```

My template references it like this:

`<img src="{{ .ImgB64s }}" />`

And the generated result is not as expected:

`<img src="#ZgotmplZ">`

The string b64s contains more than 2k characters beginning with: data:image/png;base64,

What am I doing wrong ?

Thanks

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
It should forward the value like it is.
At the end its normal golang template/html behavior, nothing special.
Maybe you can test with the unescape function https://github.com/gofiber/template/tree/master/html#example-with-innerhtml

**Comment by sgaunet** [comment]
Not better, I don't understand for now. Thanks for your comment

**Comment by MarcusSanchez** [comment]
Try to wrap your item in one of html/templates' safe content defining functions. One of these should fix this:

return c.Render("register", fiber.Map{
	"ImgB64s":template.URL( b64s),
})
	
return c.Render("register", fiber.Map{
	"ImgB64s": template.Srcset(b64s),
})

and yes this is a funky html/templates behavior

**Comment by sgaunet** [comment]
Thank you very much Marcus. template.URL did the job :)
I've tested also template.Srcset but it doesn't work as expected.

**Comment by MarcusSanchez** [comment]
> Thank you very much Marcus. template.URL did the job :)
> 
> I've tested also template.Srcset but it doesn't work as expected.

No problem my friend. Hail from the USA. Good luck on your future Go-ings.
