### ISSUE TITLE
🤔 Set Content-Type charset

### ISSUE THREAD

**Issue by ekaputra07** [gofiber/fiber#248]
**Question description**

I'm using `c.JSON()` to return json response. But it only set response headers "Content-Type" to `application/json`. Is there a way I can set the charset as well?

I'm expecting the content-type would be: `application/json; charset=utf-8`. If its only `application/json` my client app rendering some strange chars, adding utf-8 charset fix it.

Thanks

**Comment by ekaputra07** [comment]
Of course I can just do this:
```
j, err := json.Marshal(items)
if err != nil {
// return err
}
c.Send(j)
```

but `c.JSON()` is much more convenient :)

**Comment by Fenny** [comment]
Hi @ekaputra07, we can set the default charset to `utf-8` for `JSON`, `JSONP` & `Render`.
I will make a PR for `v1.8.43` thanks!

**Comment by ekaputra07** [comment]
Thanks @Fenny, setting the header after the `c.JSON()` call did it. 👍 
Previously I set it before the JSON() and JSON() overrode it :)

**Comment by Fenny** [comment]
@ekaputra07 the best practise would be to utf8 encode the json instead, I might add a boolean parameter to JSON to utf8 encode input.

**Comment by ptflp** [comment]
im using like this, from @Fenny 
```go
func JSON(c *fiber.Ctx, response interface{}) error {
	err := c.JSON(response)
	c.Set("content-type", "application/json; charset=utf-8")
	return err
}

.....

return JSON(c, YetAnotherStruct)
```

**Comment by j-pel** [comment]
Not only older browsers: Flutter is also getting it as utf-7 by default. The response should conform to the "Accept" header if present on the request.
