### ISSUE TITLE
🤗 [Question]: How to edit Params in Middleware function.

### ISSUE THREAD

**Issue by MarcusSanchez** [gofiber/fiber#2480]
### Question Description

I have a rest API where I manually for each helper need to change the param from for example, "Miami-Heat" to "Miami Heat" so that I can query the db, however in attempt to create a middleware, it doesn't appear to have a way to change it before the handler utilizes it. This isn't a big issue because I can just do this manually for every function but the ability to do it in a middleware would be nice.

### Code Snippet (optional)

```go
func replaceHyphens(c *fiber.Ctx) error {
	if err := c.Next(); err != nil {
		fmt.Println("error: ", err)
                return err
	}
	for _, param := range c.Route().Params {
		value := c.Params(param)
		value = strings.ReplaceAll(value, "-", " ")
		// I don't know if something like this exists, so it's a question not a feature request...
		c.SetParam(param, value) // SetParam() doesn't exist
	}
	return nil
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [x] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
unfortunately, this is not possible without further ado, as each middleware has its own route and thus its own parameters

you could only try to use the hooks to change this before starting the application
https://docs.gofiber.io/guide/hooks
but i would not recommend this
i am also not 100% through the usecase yet

**Comment by MarcusSanchez** [comment]
> unfortunately, this is not possible without further ado, as each middleware has its own route and thus its own parameters
> 
> you could only try to use the hooks to change this before starting the application https://docs.gofiber.io/guide/hooks but i would not recommend this i am also not 100% through the usecase yet

No problem, I will close this and create a new feature request.
