### ISSUE TITLE
🤔 How to serve Single page application

### ISSUE THREAD

**Issue by WLun001** [gofiber/fiber#249]
**Question description**
How to serve javascript single app application?

**Code snippet (optional)**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  // ..
app.Static("/", "web/dist/web")
}
```

This only works for the client root routes. It won't work if the client has navigate to different route.
eg, /page1

**Comment by y21** [comment]
I had the same "problem" a while ago and ended up registering multiple static file handlers as it didn't work with just one handler, though I'm not sure if this is the optimal way to approach that and it seems rather annoying if you have a lot of directories.

```go
app.Static("/", "web/dist/web")
app.Static("/js/", "web/dist/web/js")
app.Static("/css/", "web/dist/web/css")
// ...
```

**Comment by WLun001** [comment]
@y21 yeah I know using web server will be better sense. I just wanted to run simple full stack app in one service.

**Comment by Fenny** [comment]
```go
package main

import (
	"github.com/gofiber/fiber"
)

func main() {
	app := fiber.New()

	app.Static("/", "./web")

	app.Use("*", func(c *fiber.Ctx) {
		c.SendFile("./web/index.html")
	})
	
	app.Listen(3000)
}

```

**Comment by WLun001** [comment]
@Fenny thanks! This is my final code, SPA serves under `web` because I still want to serve `api`

```go
func main() {
  app := fiber.New()
  app.Static("/web", "web/dist/web")
  app.Get("/web/*", func(ctx *fiber.Ctx) {
    ctx.SendFile("web/dist/web/index.html")
 })
  app.Listen(3000)
}
```

**Comment by Fenny** [comment]
I will add an example to https://github.com/gofiber/recipes
