### ISSUE TITLE
🤗 [Question]: After introducing static resources packaged by Vue through go embed, the sse request cannot be used and returns 404

### ISSUE THREAD

**Issue by CNZeroY** [gofiber/fiber#2490]
### Question Description

When my front-end requests the fiber's sse interface, it returns 404

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

//go:embed web/*
var frontendFiles embed.FS

func main() {
  app := fiber.New()

  app.Use("/", filesystem.New(filesystem.Config{
		Root:       http.FS(frontendFiles),
		PathPrefix: "web",
		Index:      "index.html",
		Browse:     false,
  }))

  app.Get("/sse", func(c *fiber.Ctx) error {
		c.Set(fiber.HeaderContentType, "text/event-stream")
		c.Set(fiber.HeaderCacheControl, "no-cache")
		c.Set(fiber.HeaderConnection, "keep-alive")

		c.Context().SetBodyStreamWriter(fasthttp.StreamWriter(func(w *bufio.Writer) {
			ticker := time.NewTicker(1 * time.Second)
			for range ticker.C {
				fmt.Fprintf(w, "data: %s\n\n", "hello")
				w.Flush()
			}
		}))

		return nil
  })

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by CNZeroY** [comment]
use `app. Static ("/", "web/")`  it work

**Comment by cmd777** [comment]
A bit late, but if you got a "Forbidden", you could try this:

```go
app.Use("/", filesystem.New(filesystem.Config{
	Root:   http.FS(frontendFiles),
	Index:  "web/index.html",
	Browse: false,
}))
```

If you want to do it with `filesystem` instead of `app.Static`

**Comment by CNZeroY** [comment]
> A bit late, but if you got a "Forbidden" or "Not found", you could try this:
> 
> ```go
> app.Use("/", filesystem.New(filesystem.Config{
> 	Root:   http.FS(frontendFiles),
> 	Index:  "web/index.html",
> 	Browse: false,
> }))
> ```
> 
> If you want to do it with `filesystem` instead of `app.Static`

When I try to register the root route under the sse route, it works
