### ISSUE TITLE
🚀 [Feature]:  Support HTTP2 version

### ISSUE THREAD

**Issue by nadir-pb** [gofiber/fiber#2492]
### Feature Description

Actually, all know that Fiber support fast HTTP but it does not support HTTP2 anymore. In any case, every language uses  [gRPC](https://grpc.io/) and it requires HTTP2 but fiber is not supported. Please consider this issue

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
duplicate https://github.com/gofiber/fiber/issues/2358 https://github.com/gofiber/fiber/issues/1541

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/2358#issuecomment-1461511087
