### ISSUE TITLE
🐛 [Bug]: Auth middleware is being executed for undefined paths [ 404 paths ] 

### ISSUE THREAD

**Issue by mari-muthu-k** [gofiber/fiber#2494]
### Bug Description

I have protected group and unprotected group. Protected group has auth middleware. But when I give 404 path request that doesn't belong to any group , the auth middleware keep executing and returning 401 instead of 404. 
Note : I've applied auth middleware to the group not to the individual protected group route.

### How to Reproduce

1.  Creat two route groups one with auth middleware
2.  Send 404 path request to the fiber app 

### Expected Behavior

It should return 404 instead of 401. 

### Fiber Version

v2.44.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce
    NoAuthAPI(app.Group("/"))
    AuthAPI(app.Group("/",Authenticate()))
  log.Fatal(app.Listen(":3000"))
}

func NoAuthAPI(app fiber.Router){
	app.Post("/login",func(c *fiber.Ctx) error {
        return c.JSON("Hello, World! from NoAuthAPI")
    })
}

func AuthAPI(app fiber.Router){
	app.Post("/home",func(c *fiber.Ctx) error {
        return c.JSON("Hello, World! from AuthAPI")
    })
}

func Authenticate() fiber.Handler {
	return func(c *fiber.Ctx) error {
                isAuth := false // dummy value to depict the auth function
		// Check if user is authenticated
		if isAuth {
			return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{
		"message":"unauthorized",
	     })
		}

		// Continue with next middleware
		return c.Next()
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Our grouping is only a golang capsule, so virtual.
Since the middleware was registered for the root path it works there too, expressjs behaves the same way

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/2406#issuecomment-1498075776

https://docs.gofiber.io/guide/grouping

![image](https://github.com/gofiber/fiber/assets/7063188/21bf449f-5cc2-48c8-919f-45ca70492d7b)
