### ISSUE TITLE
🤗 [Question]: Performance implication of using (*fiber.App) Mount vs Group

### ISSUE THREAD

**Issue by UbadahJ** [gofiber/fiber#2498]
### Question Description

Hi

I am using fiber to build a gateway for our server. In some routes, we need to provide multiple middlewares for a specific platform. For example,

```
/api/test-x
/api/android/test-y
/api/ios/test-y
```
Now here the two test-y routes have the same functionality, just different middleware. For this we have decided to create multiple fiber.App and register routes on both and then mount them.

My question is what are the performance implications of this approach, if this methodology is discouraged, and if it is, how can we use fiber.Group to do the same?

**Additional Context**

We are dividing the codebase into multiple packages so each component is completely independent of each others and we would like to continue using this if possible.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by taniko** [comment]
How about like this?
```go
func main() {
	app := fiber.New()
	apiMiddleware := func(c *fiber.Ctx) error {
		c.Locals("api", "ok")
		return c.Next()
	}
	a := func(c *fiber.Ctx) error {
		c.Locals("a", "ok")
		return c.Next()
	}
	b := func(c *fiber.Ctx) error {
		c.Locals("b", "ok")
		return c.Next()
	}
	h := func(c *fiber.Ctx) error {
		return c.Status(http.StatusOK).JSON(map[string]any{
			"api": c.Locals("api"),
			"a":   c.Locals("a"),
			"b":   c.Locals("b"),
		})
	}
	api := app.Group("/api", apiMiddleware)
	api.All("/test-x", h)
	api.All("/android/test-y", a, h)
	api.All("/ios/test-y", b, h)
	log.Fatal(app.Listen("localhost:3000"))
}
```

**Comment by UbadahJ** [comment]
Interesting and Thank you!

I will look into this and unless I face any issues, will close this issue by tomorrow. 

Still, can you share any metrics on using multiple fiber.App and mounting them vs using groups with handlers?

**Comment by UbadahJ** [comment]
Thanks for the info!

The handler method also works but since there is no difference in mounting and handlers, we will go with mounting since that is how we have already implemented it.

Closing the issue
