### ISSUE TITLE
🤗 [Question]: How BodyParser to parse unknown body params (to any json scheme)

### ISSUE THREAD

**Issue by SudoDios** [gofiber/fiber#2500]
### Question Description

Hi.
How to parse body to any scheme ?
(without creating a special struct)

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  app.Post("/", func(ctx *fiber.Ctx) error {
		var payload interface{} //parse any scheme
		if err := ctx.BodyParser(&payload); err != nil {
			return err
		}
		return ctx.JSON(payload)
	})

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by SudoDios** [comment]
I make this and work
```go
app.Post("/", func(ctx *fiber.Ctx) error {
		var test interface{}
		if err := json.Unmarshal(ctx.Body(), &test); err != nil {
			return err
		}
		return ctx.JSON(test)
	})
```
But is this the right way?

**Comment by cmd777** [comment]
> But is this the right way?

Yeah.
But you can also use either `map[string]interface{}`, or `json.RawMessage`, or `interface{}` as well, they all should work as well.

**Comment by SudoDios** [comment]
very nice
thanks
