### ISSUE TITLE
Data race issue🤗 [Question]: 

### ISSUE THREAD

**Issue by Krishnakumar-b** [gofiber/fiber#2507]
### Question Description

The application  running from the go-fiber-v2 version 2.44.0 throwing a warning as :
[Warning] - [TIMEOUT] timeout contains data race issues, not ready for production!
Can you please let me know if this will cause our application?

 

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by cmd777** [comment]
You're using `timeout.New()`, which is deprecated.

Both the [docs](https://docs.gofiber.io/api/middleware/timeout), and the [go comment docs](https://github.com/gofiber/fiber/blob/master/middleware/timeout/timeout.go#L17) recommend using `timeout.NewWithContext()` instead, which don't appear to have data races.

**Comment by Krishnakumar-b** [comment]
> You're using `timeout.New()`, which is deprecated.
> 
> Both the [docs](https://docs.gofiber.io/api/middleware/timeout), and the [go comment docs](https://github.com/gofiber/fiber/blob/master/middleware/timeout/timeout.go#L17) recommend using `timeout.NewWithContext()` instead, which don't appear to have data races.

**Comment by cmd777** [comment]
> Thank you @cmd777 , for concluding , **timeout.NewWithContext()** is the better version to use right?

Yeah
