### ISSUE TITLE
🐞 fiber.App is an exported type and should not be renamed in patch version bump

### ISSUE THREAD

**Issue by Trim21** [gofiber/fiber#251]
**Fiber version/commit**

v1.8.41 -> v1.8.43

**Issue description**

I upgrade my fiber version from `v1.8.41` to `v1.8.43`, and this is part of my code:

```golang
func rootRouter(app *fiber.App) {
// something
}
```

But I can't compile it any more because `fiber.App` become `undefined`

**Expected behavior**

`fiber.App` should still be available until a major version bump, it's a breaking change.

**Comment by Fenny** [comment]
@Trim21, `v1.8.43` caused this issue. I re-created this version with a fix. If you having cache problems, the latest version should also fix this issue `v1.8.431`.

**Comment by Trim21** [comment]
Version of fiber is very confusing.

1.8.431 should be considered newer than 1.8.5.

I got confused once when I upgrade form 1.8.32 to 1.8.4.
