### ISSUE TITLE
🚀 [Feature]: ctx.Cookie is missing "Priority" Option

### ISSUE THREAD

**Issue by MartinHotmann** [gofiber/fiber#2515]
### Feature Description

I am refering to Chromes (~65% browser market share) cookie setting `Priority` ([LINK](https://bugs.chromium.org/p/chromium/issues/detail?id=232693), [docs](https://developer.chrome.com/docs/devtools/application/cookies/)) which tells the browser which cookies are more important than others, for example login cookies and creates a priority of which cookies can be deleted first if the browser needs to.

I am currently missing this option [in the docs](https://docs.gofiber.io/api/ctx#cookie) and also could not add it in code - so I assume this is not implemented.

AFAIK this is a chromium only thing by now, so other browsers wil just ignore it - no downsides/sideeffects.

### Code Snippet (optional)

```go
// Set the token as a cookie
c.Cookie(&fiber.Cookie{
	Name:     "Cookie Name",
	Value:    "Cookie value",
	Path:     "/",
	Expires:  time.Now().UTC().Add(900 * time.Second),
	Secure:   true,
	HTTPOnly: true,
	SameSite: "Strict",
	//Priority: "High",
})
```

Options for `Priority` are: `Low`, `Medium` & `High`

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
does not seem to be currently supported by our core
https://github.com/valyala/fasthttp/blob/ffdf59d04ca2f02556308d60d37b8e77ea04484c/cookie.go#L67-L97

as soon as this happens we can include it

to speed this up, you can also create a report at fasthttp

**Comment by MartinHotmann** [comment]
Thanks for the quick reply, I appreciate it!

Will link them: https://github.com/valyala/fasthttp/issues/1580

**Comment by leonklingele** [comment]
I‘ve never heard of the Priority directive, and also MDN doesn’t list it: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
Are you sure it’s still supported?

**Comment by ReneWerner87** [comment]
had also looked there, am also not sure

**Comment by ReneWerner87** [comment]
https://github.com/valyala/fasthttp/issues/1580#issuecomment-1603908117 
erik means its deprecated 
so better to not support it

**Comment by ReneWerner87** [comment]
https://datatracker.ietf.org/doc/html/rfc6265#section-5.2

![image](https://github.com/gofiber/fiber/assets/7063188/e074f0bf-87dd-4d43-ade9-c4903f0dc89d)

since it is not part of the standard and is also marked as deprecated, we will not support this

**Comment by MartinHotmann** [comment]
I understand, it is not officially supported. But would not hurt/break anything.
Anyway I understand. Should have thecheck the IEFT before.

Thanks anyway!
