### ISSUE TITLE
🐛 [Bug]: c.params can not deal with chinese characters

### ISSUE THREAD

**Issue by g-mero** [gofiber/fiber#2519]
### Bug Description

fiber can not handle chinese characters in request url

work fine in browser， but failed when use ApiPost(an api testing software)

```
r.Get("/pic/*", GetImage)

func GetImage(c *fiber.Ctx) error {
      
	src := "data/pic/" + c.Params("*")
       
        // get http://127.0.0.1/1234/图片123.jpg
        // print data/pic/1234/%E5%9B%BE%E7%89%87
        // should be data/pic/1234/%E5%9B%BE%E7%89%87123.jpg
	fmt.Println(src)
	_, err := os.Stat(src)

	if os.IsNotExist(err) {
		return fiberResp.Error(c)
	}
	return c.SendFile(url.PathEscape(src))
}
```

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected Behavior

when I get http://127.0.0.1/1234/图片123.jpg
fiber return data/pic/1234/%E5%9B%BE%E7%89%87
should be data/pic/1234/%E5%9B%BE%E7%89%87123.jpg

### Fiber Version

v2.47.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Have you tried the UnescapePath setting? https://docs.gofiber.io/api/fiber#config

**Comment by g-mero** [comment]
> Have you tried the UnescapePath setting? https://docs.gofiber.io/api/fiber#config

Became 'data/pic/1234/图片', still can not get the full path

**Comment by cmd777** [comment]
Try using url.Queryunescape?
```go
result, _ := url.Queryunescape(c.Params("*"))
src := "data/pic/" + result
```
or double check the link/file again?
I cannot replicate this bug though, I tried both x32 & x64, and both Queryunescape and the UnescapePath config as well, but they both worked just fine

**Comment by g-mero** [comment]
> Try using url.Queryunescape?
> 
> ```go
> result, _ := url.Queryunescape(c.Params("*"))
> src := "data/pic/" + result
> ```
> 
> or double check the link/file again? I cannot replicate this bug though, I tried both x32 & x64, and both Queryunescape and the UnescapePath config as well, but they both worked just fine

Can not solve. 

But I find this only happened when I use api test app, worked fine in browser. Because browser send an encoded url to backend, but api test app send original url. 

And it is strange that when Chinese characters or a query are added to the request, the backend can receive the complete path correctly. For example, http://127.0.0.1/23123/图片123.jpg图 or http://127.0.0.1/23123/图片123.jpg?some=some or http://127.0.0.1/23123/图片123.jpg#, all of these can be received correctly.

**Comment by Skyenought** [comment]
@g-mero 

这是我的代码:

This is my test code:
```go
package main

import (
	"github.com/gofiber/fiber/v2"
	fiberlog "github.com/gofiber/fiber/v2/log"
	"net/url"
)

func main() {
	app := fiber.New(fiber.Config{
		UnescapePath: true,
	})
	app.Get("/pic/*", func(c *fiber.Ctx) error {
		src := "data/pic/" + c.Params("*")
		unescapeUrl, _ := url.PathUnescape(src)
		return c.JSON(fiber.Map{
			"unescapeUrl": unescapeUrl,
			"url":         src,
		})
	})

	fiberlog.Fatal(app.Listen(":4000"))
}
```
```shell
curl http://127.0.0.1:4000/pic/图片.png
```

结果:

result:

```json
{
    "unescapeUrl": "data/pic/图片.png",
    "url": "data/pic/图片.png"
}
```

没有遇见你的问题.
No lost suffixes were encountered

**Comment by gooddavvy** [comment]
I don't think it can handle Unicode characters. Any ideas?

**Comment by MartinHotmann** [comment]
Maybe related to https://github.com/gofiber/fiber/issues/2575 ?

**Comment by ReneWerner87** [comment]
@g-mero @gooddavvy can someone provide a reproducible example
with curl request so that we can test it
if other files are needed, i would suggest a github example

According to last stand we could not reproduce this

**Comment by g-mero** [comment]
@ReneWerner87, this issue occurs when the request path contains unescaped characters. It seems that some API testing software (e.g., apifox, apipost) cannot automatically encode unescaped characters (e.g., Chinese). It works fine in a browser or with curl.

**Comment by ReneWerner87** [comment]
Need a request for the reproduction, with curl this should also be possible because curl sends the request without change

Otherwise we can not help
