### ISSUE TITLE
 🤔 [Question]: how to setup the filesystem with embedded data

### ISSUE THREAD

**Issue by conero** [gofiber/fiber#2526]
### Bug Description

Refer to the page( https://docs.gofiber.io/api/middleware/filesystem#embed ) and write the embedded file system mode. When requesting a page, it returns 404, but can successfully return content such as js/css.

Can respond to pages normally in `app. Static` mode.

*The page request is as follows:*

![image](https://github.com/gofiber/fiber/assets/19564821/33569d0f-ee22-416e-8ae3-32ad5aed15b1)

### How to Reproduce

`git clone https://github.com/conero/fiber_bug_2526`  

Compile instance code and run it.

code: https://github.com/conero/fiber_bug_2526

### Expected Behavior

Correctly respond to requests in embedded mode instead of 404.

### Fiber Version

v2.47.0

### Code Snippet (optional)

```go
package main

import (
	"embed"
	"log"
	"net/http"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/filesystem"
)

// Embed a single file
//
//go:embed index.html
var f embed.FS

// Embed a directory
//
//go:embed assets/*
var embedDirStatic embed.FS

func main() {
	app := fiber.New()

	app.Use("/", filesystem.New(filesystem.Config{
		Root: http.FS(f),
	}))

	// Access file "image.png" under `assets/` directory via URL: `http://<server>/assets/image.png`.
	// Without `PathPrefix`, you have to access it via URL:
	// `http://<server>/assets/assets/image.png`.
	app.Use("/assets", filesystem.New(filesystem.Config{
		Root:       http.FS(embedDirStatic),
		PathPrefix: "assets",
		Browse:     true,
	}))

	log.Fatal(app.Listen(":3023"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
![image](https://github.com/gofiber/fiber/assets/7063188/b47c721e-23c0-4ba1-a86f-3667fe274aec)


https://docs.gofiber.io/next/guide/routing#paths
![image](https://github.com/gofiber/fiber/assets/7063188/e92fa63d-c4de-416a-8ab4-5341c17e1267)


the problem is the order of the routes

app.Use() is used to detect a prefix path and then the more specific route should come before the other one

**Comment by ReneWerner87** [comment]
btw little bit improved -> for security

```go
package main

import (
	"embed"
	"log"
	"net/http"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/filesystem"
)

// Embed a single file
//
//go:embed index.html
var f embed.FS

// Embed a directory
//
//go:embed assets/*
var embedDirStatic embed.FS

func main() {
	app := fiber.New()

	// Access file "image.png" under `assets/` directory via URL: `http://<server>/assets/image.png`.
	// Without `PathPrefix`, you have to access it via URL:
	// `http://<server>/assets/image.png`.
	app.Use("/assets", filesystem.New(filesystem.Config{
		Root:       http.FS(embedDirStatic),
		PathPrefix: "assets",
	}))

        // only expose the index.html
	app.Use("*", func(ctx *fiber.Ctx) error {
		return filesystem.SendFile(ctx, http.FS(f), "index.html")
	})

	log.Fatal(app.Listen(":3023"))
}

```
