### ISSUE TITLE
🤗 [Question]: How to wrap validation?

### ISSUE THREAD

**Issue by Behzad-Khokher** [gofiber/fiber#2527]
### Question Description

I'm trying to create a validation wrapper so I don't have to write the same code repeatedly.

This is what I want to be able to do:
```go
func ValidateModel(c *fiber.Ctx, model interface{}) error {
	// Create a new validator instance
	validate := validator.New()

	// Validate the model object
	if err := validate.Struct(model); err != nil {
		// Handle validation error
		response := fiber.Map{
			"Success": false,
			"Message": err.Error(),
		}
		return c.Status(400).JSON(response)
	}

	// No validation errors, return nil
	return nil
}
```

And handle it in controllers:
```go
// CreateChannel creates a new channel
// @desc      Create new channel
// @route     POST /api/v1/channels
// @access    Private
func CreateChannel(c *fiber.Ctx) error {
	// newChannel := models.Channel{ID: 1, Name: "New Channel", Description: "New Channel description", PostCount: 0}
	// return c.JSON(newChannel)

	var channel models.Channel

	if err := c.BodyParser(&channel); err != nil {
		return c.Status(400).JSON(err.Error())
	}

	// I want to remove these lines of code
	// validate := validator.New()
	// if err := validate.Struct(channel); err != nil {
	// 	// Handle validation error
	// 	return c.Status(400).JSON(fiber.Map{
	// 		"success": false,
	// 		"message": err.Error(),
	// 	})
	// }

        // Want to do something like this
	if err := ValidateModel(c, channel); err != nil {
		return err
	}

	database.Database.Db.Create(&channel)
	return c.Status(200).JSON(channel)
}
```

But it won't work, it doesn't validate. And on the wrong input, it still tried to create the record in the database.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
check this new documentation 
https://docs.gofiber.io/next/guide/validation
if this still helps @Z3NTL3  may help you

**Comment by Behzad-Khokher** [comment]
Just a follow up to my question. I was able to figure out a solution to what I wanted to implement.

This is how we would write the validate function:
```
func Validate(c *fiber.Ctx, data interface{}) error {
	validate := validator.New()
	if err := validate.Struct(data); err != nil {
		errArr := strings.Split(err.Error(), "\n")

		c.Status(fiber.StatusBadRequest).JSON(fiber.Map{
			"success": false,
			"error":   errArr,
		})
		return fiber.NewError(400, "Validator Failded: "+err.Error())
	}
	return nil
}
```

And this function will be used like this:
```
func ControllerFunction (...) error{
	var user User
	 if err := Validate(c, user); err != nil {
	     return nill 
         }
}
```

The main thing is to return nill to the fiber.Router. Returning err, will actually re-execute fiber's `c.fasthttp.Response.SetBodyRaw(raw)` where the raw data will be the error but it won't be formated in json.

@ReneWerner87 Please do look into this, if you have another recommendations do let me know.

**Comment by ReneWerner87** [comment]
why don't you return a mistake

you could return a specific validation error and handle it in the error handler, then you would have a termination of further functionality and the handling would be well partitioned
https://docs.gofiber.io/guide/validation
https://docs.gofiber.io/guide/error-handling#custom-error-handler

as we do for example with the internal server errors
https://github.com/gofiber/fiber/blob/f6446ab0b93d8ba508daa43bd253cfb0631d90aa/app.go#L1069-L1084
