### ISSUE TITLE
🤔 Need help with mp4 pseudo-streaming

### ISSUE THREAD

**Issue by xpopit** [gofiber/fiber#253]
**Question description**

**Code snippet (optional)**

```go
	app.Get("/mp4", func(c *fiber.Ctx) {
		_c := c.Fasthttp
		file, err := os.Open(mp)
		if err != nil {
			_c.SetStatusCode(500)
			return
		}
		defer file.Close()
		fi, err := file.Stat()
		if err != nil {
			_c.SetStatusCode(500)
			return
		}
		fileSize := int(fi.Size())
		// ctx.Request.Header.Peek()
		if len(_c.Request.Header.Peek("Range")) == 0 {
			contentLength := strconv.Itoa(fileSize)
			contentEnd := strconv.Itoa(fileSize - 1)
			_c.Response.SkipBody = true
			_c.Response.Header.Set("Content-Type", "video/mp4")
			_c.Response.Header.Set("Accept-Ranges", "bytes")
			_c.Response.Header.Set("Content-Length", contentLength)
			_c.Response.Header.Set("Content-Range", "bytes 0-"+contentEnd+"/"+contentLength)
			_c.SetStatusCode(200)
			_c.SetBodyStreamWriter(func(w *bufio.Writer) {
				buffer := make([]byte, BUFSIZE)
				for {
					n, err := file.Read(buffer)
					if n == 0 {
						break
					}
					if err != nil {
						break
					}
					data := buffer[:n]
					w.Write(data)
					w.Flush()
				}
			})
```

**Comment by xpopit** [comment]
not work 
curl --head http://localhost:8000/mp4
HTTP/1.1 200 OK
Date: Wed, 01 Apr 2020 11:30:13 GMT
Content-Type: video/mp4
Content-Length: 1303341816
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Range: bytes 0-1303341815/1303341816

**Comment by Fenny** [comment]
Does this solve your problem?
```go
app.Static("/mp4", "/movie.mp4", fiber.Static{
    ByteRange: true,
})
```

**Comment by xpopit** [comment]
OMG! ok thank 
  
![image](https://user-images.githubusercontent.com/17220015/78154104-0e158900-7466-11ea-8dfc-23ea312a9b79.png)

One more question? 
I will use dynamic Params

example
```go
func MP4(app *fiber.Fiber) {
app.Static("/mp4/:media", mp, fiber.Static{
 media := c.Params("media")
		ByteRange: true,}
)
}
```

**Comment by Fenny** [comment]
@xpopit, sorry I didn't had time to create an example.
You could create a normal `app.Get` handler with params and try to get the ranges using `c.Range(file.length)` and stream the specific range requested.

If I have some time left this weekend I will try to make a working example!

**Comment by RodsAlex** [comment]
Hi, 
Is it possible to have an example without using static file but using bytes array?
I need to get the file from s3 on http request, so i can't give the path of the file.
