### ISSUE TITLE
🚀 [Feature]: support app.Group return an app.RouterGroup achieving the goal of chain grouping.

### ISSUE THREAD

**Issue by Fly-Playgroud** [gofiber/fiber#2531]
### Feature Description

support `app.Group` return an `app.RouterGroup` achieving the goal of chain grouping. Like `gin.Group`

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()
  Router := fiber.New()
  Router.Use(middleware.LoggerMiddleware())
  crawlerRouter := router.RouterGroupApp.Crawler

  v1Group := Router.Group("/api/v1")

  {
        crawlerRouter.InitCrawlerRouter(v1Group)
   }

  func (r *CrawlerRouter) InitCrawlerRouter(Router *fiber.RouterGroup) {
	crawlerRouter := Router.Group("/crawlerTask")
	crawlerAPI := v1.APIGroupAPP.CrawlerApiGroup.CrawlerAPI
	{
		crawlerRouter.Get("/status/:id<int>", crawlerAPI.GetCrawlerTaskStatus)
		crawlerRouter.Post("/create", crawlerAPI.CreateCrawlerTask)
		crawlerRouter.Put("/stop/:id<int>", crawlerAPI.StopCrawlerTask)
		crawlerRouter.Delete("/delete/:id<int>", crawlerAPI.DeleteCrawlerTask)
	}
}

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
> support app.Group return an app.RouterGroup achieving the goal of chain grouping. Like gin.Group

@Fly-Playgroud 
what is the difference to the current state? 
the group function already returns a group which is from the router interface and this can be chained infinitely

**Comment by Fly-Playgroud** [comment]
> > support app.Group return an app.RouterGroup achieving the goal of chain grouping. Like gin.Group
> 
> @Fly-Playgroud what is the difference to the current state? the group function already returns a group which is from the router interface and this can be chained infinitely

group not return a group,instead return a router

**Comment by ReneWerner87** [comment]
yes right, the router interface, which offers almost the same functionalities as the real group

what are you missing with the return type ? 

you can take the return value and brew a new following group with the group function

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/453ccadadd09b80155cdde7cc9d1beae9ec91f21/router.go#L21-L45



endless chaining
https://github.com/gofiber/fiber/blob/453ccadadd09b80155cdde7cc9d1beae9ec91f21/router.go#L38C1-L38C1

**Comment by Fly-Playgroud** [comment]
> https://github.com/gofiber/fiber/blob/453ccadadd09b80155cdde7cc9d1beae9ec91f21/router.go#L21-L45
> 
> endless chaining https://github.com/gofiber/fiber/blob/453ccadadd09b80155cdde7cc9d1beae9ec91f21/router.go#L38C1-L38C1

ok. I understand it. thank you!
