### ISSUE TITLE
🐛 [Bug]: Documentation for route escape

### ISSUE THREAD

**Issue by pjebs** [gofiber/fiber#2534]
### Bug Description

See: https://docs.gofiber.io/guide/routing

> All special parameter characters can also be escaped with "\\" and lose their value, so you can use them in the route if you want, like in the custom methods of the [google api design guide](https://cloud.google.com/apis/design/custom_methods).

```go
func Test_RoutePatternMatch(t *testing.T) {
...
testCase("/v1/some/resource/name\\:customVerb", []testparams{
    {url: "/v1/some/resource/name:customVerb", match: true},
    {url: "/v1/some/resource/name:test", match: false},
})

```

The docs say escaping should be done with `\`. I _suspect_ escaping is actually done with `\` , but due to double-quote strings, you need 2 slashes.

Perhaps the documentation should use ``` (backticks) for all route pattern strings to make it clearer.
In go's regex documentation, they **always** use backticks to make sure it is unambiguous and the escape character doesn't interfere with regex patterns in an unexpected way.

Example for docs:

```go
app.Get(`/v1/some/resource/name\:customVerb`, func(c *fiber.Ctx) error {
    return c.SendString("Hello, Community")
})

instead of current:

app.Get("/v1/some/resource/name\\:customVerb", func(c *fiber.Ctx) error {
    return c.SendString("Hello, Community")
})


```

### How to Reproduce

N/A

### Expected Behavior

N/A

### Fiber Version

N/A

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by 11-aryan** [comment]
Hey, Can I take up this issue ?
