### ISSUE TITLE
🤗 [Question]: Problem with route index path

### ISSUE THREAD

**Issue by fachryansyah** [gofiber/fiber#2537]
### Question Description

i want to create group path index but i got this

```GO
func (a *Rest) Routes(r fiber.Router) {
	routes := r.Group("surah")
	routes.Get("", a.GetSurah) // => http://localhost:3000/surah
	routes.Get("/", a.GetSurah) // => http://localhost:3000/surah/
}
```
why i need write 2 route handler with same function ? how can i just wrote 1 handler and handle 2 different index url ?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by Behzad-Khokher** [comment]
Hi @fachryansyah, Maybe try adding a slash to your group.

`func (a *Rest) Routes(r fiber.Router) {
	routes := r.Group("/surah")
	routes.Get("/", a.GetSurah) // => http://localhost:3000/surah
`

I hope this helps. Do let me know if it doesn't work.

**Comment by ReneWerner87** [comment]
@fachryansyah 
```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	routes := app.Group("test")
	routes.Get("/", func(ctx *fiber.Ctx) error {
		return ctx.SendStatus(fiber.StatusOK)
	})

	log.Fatalln(app.Listen(":3000"))
}

```

result:
![image](https://github.com/gofiber/fiber/assets/7063188/4e7a9848-e2de-401b-b514-363f4517a872)
![image](https://github.com/gofiber/fiber/assets/7063188/f6a4e8d4-d839-4050-b905-c3205c259e3b)


btw there is no difference between 
```go
routes.Get("/", ..)
routes.Get("", ..)
```

if you want to have strict routing only for the route with slash, then you have to enable strict routing in config
https://docs.gofiber.io/api/fiber#config
![image](https://github.com/gofiber/fiber/assets/7063188/c48fa9dd-1a02-45f0-a24c-d914f96c2260)

**Comment by Behzad-Khokher** [comment]
@ReneWerner87 Oh thanks for pointing that out.
