### ISSUE TITLE
🤗 [Question]: hotreload fiber on windows

### ISSUE THREAD

**Issue by anliben** [gofiber/fiber#2539]
### Question Description

Is there a way to hotreload the fiber when I'm on windows because on linux I use air but on windows I can't configure the path to use air normally

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Have you checked https://github.com/gofiber/recipes/blob/master/air/.air.windows.conf

**Comment by Behzad-Khokher** [comment]
Hi @anliben, I recently had a similar issue. But I discovered I am able to use Nodemon for hot reloading my Go apps. I'm assuming you already have Nodejs and NPM setup.

Install nodemon:
`npm -g install nodemon`

Then run your file using this:
`nodemon --exec go run main.go --signal SIGTERM`

It works like a charm. Let me know if you need help with the setup.

**Comment by ReneWerner87** [comment]
@anliben have you tried the air example on windows? is it working?

**Comment by anliben** [comment]
> Hi @anliben, I recently had a similar issue. But I discovered I am able to use Nodemon for hot reloading my Go apps. I'm assuming you already have Nodejs and NPM setup.
> 
> Install nodemon: `npm -g install nodemon`
> 
> Then run your file using this: `nodemon --exec go run main.go --signal SIGTERM`
> 
> It works like a charm. Let me know if you need help with the setup.

Este serviço ele inicia porem acredito que o projeto seja tao grande que ele não atualize! eu testei removendo uma rota, porem ele continua após recarregar chamou a rota

**Comment by anliben** [comment]
> @anliben have you tried the air example on windows? is it working?

I can't configure air on my windows

**Comment by Behzad-Khokher** [comment]
@anliben I have used it and i have encountered the issue that your facing with nodemon. It dose not concern the size of the project.

Please try doing this:
`npm -g install nodemon@3.0.1`

Then do this:
`nodemon --watch './**/*.go' --signal SIGTERM --exec 'go' run main.go`

It should work.

**Comment by anliben** [comment]
Not working on my project!

I will avaliable other method

https://github.com/gofiber/fiber/assets/45929971/9096dc7f-72fb-490e-86a7-267012a2ea75

**Comment by Behzad-Khokher** [comment]
Thanks for the feedback. I didn't get that error. Are you also receiving an error for Air as well?

**Comment by anliben** [comment]
I cannot set air on my path windows, on  full path i run go run main.go init, but not working:

![image](https://github.com/gofiber/fiber/assets/45929971/097207b3-3193-4d2d-a5cc-019bf91ed788)

Exists tutor for configure air on windows?

**Comment by ReneWerner87** [comment]
> Have you checked https://github.com/gofiber/recipes/blob/master/air/.air.windows.conf

Yes, just check my example

**Comment by ReneWerner87** [comment]
https://dev.to/komfysach/go-live-reload-using-air-40ll

**Comment by anliben** [comment]
Yes, Yes, YYYYEEEESSSSSSSSSSSS

Thanks you Bro!
