### ISSUE TITLE
🤗 [Question]: 

### ISSUE THREAD

**Issue by TheLazyLemur** [gofiber/fiber#2541]
### Question Description

I have a very basic Fiber project.
It consists of two endpoints

POST /feature
Get /

All that I am doing is posting a form value and then storing it in a map, if the map contains the value I return an error.

The strange thing that is happening however is the whenever I post a value of "hello" and then another of "world" the error gets thrown. I know I sound crazy. But I have recreated it on two machines now and the same logic with Go Chi and I do not have this same issue

I am not sure if this is a bug, or somethign I am missing?

### Code Snippet (optional)

```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v2"
)

var (
	data = make(map[string]string)
)

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		html := `
	<!DOCTYPE html>
<html>
<head>
  <title>Feature Form</title>
</head>
<body>
  <form action="/feature" method="POST">
    <label for="featureName">Feature Name:</label>
    <input type="text" id="featureName" name="featureName" required>
    <br>
    <input type="submit" value="Submit">
  </form>
</body>
</html>
	
		`
		c.Context().SetContentType("text/html")
		return c.SendString(html)
	})

	app.Post("/feature", func(c *fiber.Ctx) error {
		v := c.FormValue("featureName")
		fmt.Println(v)
		_, ok := data[v]
		if ok {
			return c.SendString("Feature already exists")
		}

		data[v] = v

		return c.Redirect("/")
	})

	log.Fatal(app.Listen(":3000"))
	
	// Go Chi Version
	
	package main

import (
	"net/http"

	"github.com/go-chi/chi/v5"
)

var (
	data = make(map[string]string)
)

func main() {
	r := chi.NewRouter()

	r.Get("/", func(w http.ResponseWriter, r *http.Request) {

		html := `
	<!DOCTYPE html>
<html>
<head>
  <title>Feature Form</title>
</head>
<body>
  <form action="/feature" method="POST">
    <label for="featureName">Feature Name:</label>
    <input type="text" id="featureName" name="featureName" required>
    <br>
    <input type="submit" value="Submit">
  </form>
</body>
</html>
	
		`

		w.Write([]byte(html))
	})

	r.Post("/feature", func(w http.ResponseWriter, r *http.Request) {
		v := r.FormValue("featureName")
		_, ok := data[v]
		if ok {
			w.Write([]byte("Feature already exists"))
			return
		}

		data[v] = v
		http.Redirect(w, r, "/", 301)
	})

	http.ListenAndServe(":3000", r)
}

}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Pls make a copy of the value

We use references of the requests
https://docs.gofiber.io/#zero-allocation


https://docs.gofiber.io/api/ctx#formvalue
Check the hint box
![Uploading Screenshot_2023-07-15-20-19-27-71_40deb401b9ffe8e1df2f1cc5ba480b12.jpg …]()
