### ISSUE TITLE
🤗 [Question]: Middleware `logging` unconfigurable latency/request body formatting

### ISSUE THREAD

**Issue by torbendury** [gofiber/fiber#2543]
### Question Description

When using the fiber `logging` middleware, I stumbled upon something when trying to configure it to log JSON: The `${latency}` field is always formatted to use up 7 characters which looks bad in the log output and makes processing it harder. The respective code line can be found [here](https://github.com/gofiber/fiber/blob/08099b0635f4432e2ded1adda9e951a1144ea97a/middleware/logger/tags.go#L195).

Since I'm not a senior Go dev, my question would be if this is available to be patched by myself somehow or if it has to be changed upstream in `gofiber/fiber`.

I tried to hack together a minimum example which is an extraction from a code base of mine (not published yet, more of a learning project).

It produces the following lines:

```txt
{"time":23:35:42, "latency":"     0s", "method":"GET", "path":"/book/1", "ip":"127.0.0.1", "body":"", "useragent":"Thunder Client (https://www.thunderclient.com)", "status":404}
{"time":23:45:00, "latency":"997.7µs", "method":"POST", "path":"/book", "ip":"127.0.0.1", "body":"{
  "id": 1,
  "title": "you wouldn't believe",
  "description": "...that this actually worked!",
  "price": 13.37
}", "useragent":"Thunder Client (https://www.thunderclient.com)", "status":202}
{"time":23:45:04, "latency":"     0s", "method":"GET", "path":"/book/1", "ip":"127.0.0.1", "body":"", "useragent":"Thunder Client (https://www.thunderclient.com)", "status":200}
{"time":23:46:13, "latency":"     0s", "method":"GET", "path":"/book/1", "ip":"127.0.0.1", "body":"", "useragent":"Thunder Client (https://www.thunderclient.com)", "status":200}
```

PS: While debugging this, I found that also the `body` doesn't get `\n` stripped away. Is there any way to configure this?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"
import "github.com/gofiber/fiber/v2/middleware/logger"

func main() {
  app := fiber.New()

  // An example to describe the question
  app.Use(
    logger.New(logger.Config{
			Format:        "{\"time\":${time}, \"latency\":\"${latency}\", \"method\":\"${method}\", \"path\":\"${path}\", \"ip\":\"${ip}\", \"body\":\"${body}\", \"useragent\":\"${ua}\", \"status\":${status}}\n",
			DisableColors: true,
			Output:        os.Stdout,
		}),
  )

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
You can define your own logger tags https://docs.gofiber.io/api/middleware/logger#config

Check custom tags.
https://docs.gofiber.io/api/middleware/logger#examples

**Comment by Behzad-Khokher** [comment]
In continuation to the documentation provided by @ReneWerner87 . You would have to do something like this:

```
	app.Use(logger.New(logger.Config{
		CustomTags: map[string]logger.LogFunc{
			"cust_latency": func(output logger.Buffer, c *fiber.Ctx, data *logger.Data, extraParam string) (int, error) {
				latency := data.Stop.Sub(data.Start)
				return output.WriteString(fmt.Sprintf("%v", latency))
			},
		},
	}))
```

**Comment by torbendury** [comment]
Hello and thank you both so much for demystifying the custom tags! I totally overlooked that in the docs when digging through.

Have a great day both of you!
