### ISSUE TITLE
🐛 [Bug]: Cannot set header to 'text/event-stream' with ctx.Set

### ISSUE THREAD

**Issue by michealroberts** [gofiber/fiber#2546]
### Bug Description

As above, I had a middleware running on version 2.31.0 of Go finer, where I would utilise the following:

```go
import "github.com/gofiber/fiber/v2"

func SetServerSentEventsHeaders(c *fiber.Ctx) error {
	c.Set("Content-Type", "text/event-stream")
	c.Set("Cache-Control", "no-cache")
	c.Set("Connection", "keep-alive")
	c.Set("Transfer-Encoding", "chunked")
	return c.Next()
}
```

My associated test suite was passing on version 2.31.0 but on version 2.48.0 it seems to be failing, instead, the Content-Type header is still set to 'text/plain'

<img width="504" alt="Screenshot 2023-07-17 at 15 13 06" src="https://github.com/gofiber/fiber/assets/84131395/37c84a9d-6148-474f-b292-276d1faee3dd">

### How to Reproduce

As above.

### Expected Behavior

It should be able to set the Content-Type header to "text/event-stream".

### Fiber Version

2.48.0

### Code Snippet (optional)

```go
package sse

import "github.com/gofiber/fiber/v2"

func SetServerSentEventsHeaders(c *fiber.Ctx) error {
  c.Set("Content-Type", "text/event-stream")
  c.Set("Cache-Control", "no-cache")
  c.Set("Connection", "keep-alive")
  c.Set("Transfer-Encoding", "chunked")
  return c.Next()
}


func New() fiber.Handler {
  return func(c *fiber.Ctx) error {
    return SetServerSentEventsHeaders(c)
  }
}
```

Associated test (failing):

```go
package sse

import (
	"testing"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/utils"
	"github.com/valyala/fasthttp"
)

func TestSSEDefaults(t *testing.T) {
  app := fiber.New(fiber.Config{
    IdleTimeout: -1,
    ReadTimeout: 0,
  })

  app.Use(New())

  t.Helper()

  h := app.Handler()

  // Test default GET response headers
  ctx := &fasthttp.RequestCtx{}
  ctx.Request.Header.SetMethod(fiber.MethodGet)
  h(ctx)

  utils.AssertEqual(t, "text/event-stream", string(ctx.Response.Header.Peek(fiber.HeaderContentType)))
  utils.AssertEqual(t, "no-cache", string(ctx.Response.Header.Peek(fiber.HeaderCacheControl)))
  utils.AssertEqual(t, "keep-alive", string(ctx.Response.Header.Peek(fiber.HeaderConnection)))

  ctx.Response.Header.Set(fiber.HeaderConnection, "close")
  ctx.Response.ConnectionClose()

  app.Shutdown()
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
reason is this
https://github.com/gofiber/fiber/pull/1847

since the handler is a middleware and contains only one next you must have at least one handler with logic

```go

func TestSSEDefaults(t *testing.T) {
	app := fiber.New(fiber.Config{
		IdleTimeout: -1,
		ReadTimeout: 0,
	})

	app.Use(New())
	// needed
	app.Get("/", func(ctx *fiber.Ctx) error {
		return nil
	})

	t.Helper()

	h := app.Handler()

	// Test default GET response headers
	ctx := &fasthttp.RequestCtx{}
	ctx.Request.Header.SetMethod(fiber.MethodGet)
	h(ctx)

	utils.AssertEqual(t, "text/event-stream", string(ctx.Response.Header.Peek(fiber.HeaderContentType)))
	utils.AssertEqual(t, "no-cache", string(ctx.Response.Header.Peek(fiber.HeaderCacheControl)))
	utils.AssertEqual(t, "keep-alive", string(ctx.Response.Header.Peek(fiber.HeaderConnection)))

	ctx.Response.Header.Set(fiber.HeaderConnection, "close")
	ctx.Response.ConnectionClose()

	app.Shutdown()
}
```

**Comment by michealroberts** [comment]
@ReneWerner87 Ok the reason seems logical, but worth noting that this (i.e., my tests) were working on version 2.31.0 of Fiber ...

**Comment by ReneWerner87** [comment]
@michealroberts 

> reason is this
https://github.com/gofiber/fiber/pull/1847

yes as I said before
it is because of the feature that came in the next release


https://github.com/gofiber/fiber/releases/tag/v2.32.0
![image](https://github.com/gofiber/fiber/assets/7063188/26f6cf17-2678-413b-8acd-eb9f035a4e33)

**Comment by michealroberts** [comment]
@ReneWerner87 Totally understand. So you wouldn't consider that a breaking change?

**Comment by ReneWerner87** [comment]
yes is a kind of breaking change

for me this was more a bug, because a middleware without a real handler which processes the content and only forwards it to other middlewares is rather wrong

**Comment by michealroberts** [comment]
> yes is a kind of breaking change
> 
> for me this was more a bug, because a middleware without a real handler which processes the content and only forwards it to other middlewares is rather wrong

Yeh I also appreciate this. It's kind of a bug, but introduces a change that will break a lot of previous code. Could you update the release notes of 2.32.0 with a breaking change note please, this should really have been a v3 release RFC imho, but as it borders the line between bug and feature, it's a though one to partition.

**Comment by ReneWerner87** [comment]
yes I can do

**Comment by ReneWerner87** [comment]
![image](https://github.com/gofiber/fiber/assets/7063188/77e2a03a-1a60-485d-93eb-ca3d627ff1df)
