### ISSUE TITLE
🐛 [Bug]: BodyParser will fail to parse correctly into the slices of the struct if input data contains comma

### ISSUE THREAD

**Issue by rere61** [gofiber/fiber#2557]
### Bug Description

In an HTML form, if there are multiple input elements with same name and the user enters content containing **commas**(,), thenBodyParser() function will fail to parse correctly into the slices member of the struct

```html
<html>
      <head>
      </head>
      <body>
        <form method="post" action="/">
          <input name='todo'  type='text' value='a,b'>
          <input name='todo' type='text' value='c'>
          <input type='submit' value='submit'>
      </form>
      </body>
  </html>
```
```go
  
  func (c *Test) Test(ctx *fiber.Ctx) error {
	  type MyForm struct {
		  Todo []string `form:"todo"`
	  }
	  
	  var frm MyForm
	  ctx.BodyParser(&frm)
	  
          //incorrect member size 3
          // frm.Todo[0] = "a"      frm.Todo[1]="b"   frm.Todo[2]="c"
        
         // correct members should be:  frm.Todo[0]="a,b"      frm.Todo[1]="c"

	  fmt.Println(len(frm.Todo))
  }
```

### How to Reproduce

1. Go to '....'
3. Do '....'
4. See '....'

### Expected Behavior

The number of elements in the slice member parsed into the struct must be the same as the number of input elements in the HTML form, and their content must also match.

### Fiber Version

v2.48.0

### Code Snippet (optional)

```html
<html>
      <head>
      </head>
      <body>
        <form method="post" action="/">
          <input name='todo'  type='text' value='a,b'>
          <input name='todo' type='text' value='c'>
          <input type='submit' value='submit'>
      </form>
      </body>
  </html>
```

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce
	app.Post("/",func(ctx *fiber.Ctx) error {
		type MyForm struct {
			Todo []string `form:"todo"`
		}

		var frm MyForm
		ctx.BodyParser(&frm)

	    //incorrect member size 3
          // frm.Todo[0] = "a"      frm.Todo[1]="b"   frm.Todo[2]="c"
        
         // correct members should be:  frm.Todo[0]="a,b"      frm.Todo[1]="c"
		return nil
	})
  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
the usage is incorrect, you cannot use the same key for multiple elements in one form

regardless of the backend, the data is already overwritten during the transfer from the frontend and the last value with the same key should win

**Comment by rere61** [comment]
> the usage is incorrect, you cannot use the same key for multiple elements in one form
> 
> regardless of the backend, the data is already overwritten during the transfer from the frontend and the last value with the same key should win

Nope.
HTML Form elements with same names are allowed, you can use browser's dev tools to see how it send form data to server.
An example in requested body will be: todo=a%2Cb&todo=c

For root cause of this bug is in the following implementation of BodyParser:
```
if strings.HasPrefix(ctype, MIMEApplicationForm) {
		data := make(map[string][]string)
		var err error

		c.fasthttp.PostArgs().VisitAll(func(key, val []byte) {
			if err != nil {
				return
			}

			k := c.app.getString(key)
			v := c.app.getString(val)

			if strings.Contains(k, "[") {
				k, err = parseParamSquareBrackets(k)
			}

			if strings.Contains(v, ",") && equalFieldType(out, reflect.Slice, k) {
				**values := strings.Split(v, ",")**
				for i := 0; i < len(values); i++ {
					data[k] = append(data[k], values[i])
				}
			} else {
				data[k] = append(data[k], v)
			}
		})

		return c.parseToStruct(bodyTag, out, data)
	}
```

**Comment by ReneWerner87** [comment]
ok good to know
at that time there were several requests with the requirement to split the values which are list values directly

**Comment by ReneWerner87** [comment]
why don't you send the structure right away as you expect it?

```html
<html>
      <head>
      </head>
      <body>
        <form method="post" action="/">
          <input name='todo.0'  type='text' value='a,b'>
          <input name='todo.1' type='text' value='c'>
          <input type='submit' value='submit'>
      </form>
      </body>
  </html>
  ```

**Comment by rere61** [comment]
> why don't you send the structure right away as you expect it?
> 
> ```
> <html>
>       <head>
>       </head>
>       <body>
>         <form method="post" action="/">
>           <input name='todo.0'  type='text' value='a,b'>
>           <input name='todo.1' type='text' value='c'>
>           <input type='submit' value='submit'>
>       </form>
>       </body>
>   </html>
> ```

Dear sir:

Please see the following Go's standard net/http package for references.

```
// FormValue returns the first value for the named component of the query.
// POST and PUT body parameters take precedence over URL query string values.
// FormValue calls ParseMultipartForm and ParseForm if necessary and ignores
// any errors returned by these functions.
// If key is not present, FormValue returns the empty string.
// To access multiple values of the same key, call ParseForm and
// then inspect Request.Form directly.
func (r *Request) FormValue(key string) string {
	if r.Form == nil {
		r.ParseMultipartForm(defaultMaxMemory)
	}
	if vs := r.Form[key]; len(vs) > 0 {
		return vs[0]
	}
	return ""
}
```

**Comment by rere61** [comment]
> why don't you send the structure right away as you expect it?
> 
> ```
> <html>
>       <head>
>       </head>
>       <body>
>         <form method="post" action="/">
>           <input name='todo.0'  type='text' value='a,b'>
>           <input name='todo.1' type='text' value='c'>
>           <input type='submit' value='submit'>
>       </form>
>       </body>
>   </html>
> ```

> ```go
> import "github.com/gofiber/fiber/v2"
> ```

@ReneWerner87 
It does not help, the slice size is still 3 not 2, and the first element of slice is not "a,b".
In about example the slice size should be 2 **whatever the input value contains comma(",") or not.**

Could you please look at the implementation BodyParser() function.

And please look at my explanation about how standard net/http does this.

**Comment by ReneWerner87** [comment]
Release https://github.com/gofiber/fiber/releases/tag/v2.0.3
it was requested in https://github.com/gofiber/fiber/pull/817
and implemented in 
https://github.com/gofiber/fiber/pull/817 
for the QueryParser and we have adopted the logic for the other parsers as well

**Comment by rere61** [comment]
> Release https://github.com/gofiber/fiber/releases/tag/v2.0.3 it was requested in #782 and implemented in #817 for the QueryParser and we have adopted the logic for the other parsers as well

@ReneWerner87 
Please try to understand standard net/http and other web framworks do.
I think this behavior you just mentioned is total wrong.
Sometimes, users' requirements are not correct.

**Comment by rere61** [comment]
@ReneWerner87 
Supposed there are a form for users to input their teachers in school, like the following html,
please guest what will happen in GoFiber、net/http、Gin or other framework ?
what is the correct result in you expectation?

<html>
      <head>
      </head>
      <body>
        <form method="post" action="/">
          <input name='teacher'  type='text' value='Hemingway, Ernest Miller'>
          <input name='teacher' type='text' value='Laurence Kerr Olivier, Baron Olivier'>
<--- user can dynamically add input by javascript --->
    <input name='teacher'  type='text' value='.....'>
          <input type='submit' value='submit'>
      </form>
      </body>
  </html>

**Comment by ngocchien** [comment]
@rere61,
Has your problem been resolved? Could you share your solution to resolve this problem?
I am facing a problem the same way you are.

Thank you so much.
