### ISSUE TITLE
v3 🚀 [Feature]: brancheless as far as possible

### ISSUE THREAD

**Issue by MartinHotmann** [gofiber/fiber#2562]
### Feature Description

Fort better performance all code, that will result in branches in the decompiled assembly code will result in branches.
Would love to see this taken into consideration for v3 - as this boosts performance by quite a bit!

That would include all conditional statements, like:

- **`if`**
- **`if...else`**
- **`if...else if....else`**
- **`switch...case`**

but specially the ones that are nested.
A little YouTube Video, for the ones, that do not know what it is - this guy explains it quite good:
https://www.youtube.com/watch?v=bVJ-mWWL7cE

### Additional Context (optional)

When things are getting nested or more complex, it gets harder to make themn branchless, but it is always worth the effort.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
thanks for the idea, but i think the performance gain is not too big and the effort and readability is not in any relation to it

most of it should already be optimized by the golang compiler itself, but probably in other programming languages it is a big gain

**Comment by ReneWerner87** [comment]
Maybe I am also wrong
can you provide data inform of benchmarks, then we could decide again based on that
