### ISSUE TITLE
🤗 [Question]: How to set default values for custom type in Converter for QueryParser

### ISSUE THREAD

**Issue by resulshm** [gofiber/fiber#2573]
### Question Description

I want to use QueryParser of fiber to parse my custom types. And I want parser set default values if it couldn't parse query params.
The problem is when I send invalid limit in query (for example, limit=hello) QueryParser returns an error, but I need it to set default value 20. how to fix that? My converter function is not returning an error!!!! Here is my code sample:

### Code Snippet (optional)

```go
package main

import (
	"fmt"
	"strconv"

	"github.com/gofiber/fiber/v2"
)

type Limit uint

func LimitConverter(value string) reflect.Value {
	v, err := strconv.Atoi(value)
	if err != nil || v <= 0 {
		return reflect.ValueOf(Limit(20))
	}
	return reflect.ValueOf(Limit(v))
}

var LimitParser = fiber.ParserType{
	Customtype: 0,
	Converter:  LimitConverter,
}

func main() {
	app := fiber.New()
    
    fiber.SetParserDecoder(fiber.ParserConfig{
		IgnoreUnknownKeys: true,
		ParserType: []fiber.ParserType{
			LimitParser,
		},
		ZeroEmpty: true,
	})
	app.Get("/", func(c *fiber.Ctx) error {
		var filter struct {
			Limit Limit `form:"limit" query:"limit"`
		}

		err := c.QueryParser(&filter)
		if err != nil {
			// Handle the error and set the default value
		}

		return c.JSON(filter)
	})

	app.Listen(":3000")
}

```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by nickajacks1** [comment]
`Customtype: 0,`

Change this to `Customtype: Limit(0)`

**Comment by resulshm** [comment]
> `Customtype: 0,`
> 
> Change this to `Customtype: Limit(0)`

oh it worked! thank you very much :)
