### ISSUE TITLE
🚀 [Feature]: `app.Match` method to get which handlers a certain path will match

### ISSUE THREAD

**Issue by parvezmrobin** [gofiber/fiber#2574]
### Feature Description

I am proposing the following function
```go
type RegisteredHandler struct {
    Handler
    Path string
}
app.Match(path string) []RegisteredHandler 
```

It will return the list of `Handler`s that the specified `path` will match.

## Rationale
Currently, it is quite hard to reason why a certain response is returned in a large application. It is especially true in cases of routes that involve too many parameters. If we could log the list of `Handler`s a certain path will invoke, it would be much easier to fix bugs or redesign the route paths.

Consider the following oversimplified case.
```go
router.Post("/:purchaseId/finalize", func(ctx *fiber.Ctx) error {
	purchase, errNotFound := FinalizePurchase(ctx.Params("purchaseId"))
	if errNotFound != nil {
		return fiber.ErrNotFound
	}
	return ctx.SendStatus(fiber.StatusOK)
})

router.Post("/all/finalize", func(ctx *fiber.Ctx) error {
	...
	return ctx.SendStatus(fiber.StatusOK)
})
```

Now, hitting `POST /all/finalize` will return a `NotFoundError`, which is hard to reason about at first glance. If there was an easy way to know that it is actually invoking the parameterized handler, it would be much easier to debug.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // router and handler registration goes here

  log.Debug(app.Match("/quite/complicated/path"))

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by PR454D** [comment]
@parvezmrobin, I believe the functionality is already present in `path.go`. Look for the 
`func RoutePatternMatch(path, pattern string, cfg ...Config) bool`
