### ISSUE TITLE
🐛 [Bug]:  middlerware/limiter SlidingWindow is not working as expected

### ISSUE THREAD

**Issue by yellowmarlboro** [gofiber/fiber#2578]
### Bug Description

Setting the `LimiterMiddleware=SlidingWindow`, `Max=5` and `Expiration=10*time.Second`, then continuously sending one request per second to the server, all requests will return `status codes=429` after the 5th request.
I don't know if it is normal behavior ?
if it is normal, how could i drop the requests out of limiter.
if it is bug, should i pr ?

### How to Reproduce

1. config like this, then start the app.
```golang
	app.Use(limiter.New(limiter.Config{
		Max:                5,
		Expiration:         10 * time.Second,
		LimiterMiddleware:  limiter.SlidingWindow{},
		SkipFailedRequests: true,
	}))

	app.Get("/test", func(c *fiber.Ctx) error {
		fmt.Println("start")
		return c.SendString("OK")
	})
```
2. send request per second from other client. The first five are normal, but the rest after that don't work(429). 
In:
```python
for i in range(20):
    resp = requests.get("http://localhost:8080/test")
    print(i, resp.status_code)
    time.sleep(1)
```
Out:
```
0 200
1 200
2 200
3 200
4 200
5 429
6 429
7 429
8 429
9 429
10 429
11 429
12 429
13 429
14 429
15 429
16 429
17 429
18 429
19 429
```

### Expected Behavior

expected like this
```
0 200
1 200
2 200
3 200
4 200
5 429
6 429
7 429
8 429
9 429
10 200
11 200
12 200
13 200
14 200
15 429
16 429
17 429
18 429
19 429
```

### Fiber Version

v2.48.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
	app := fiber.New()

  // Steps to reproduce
	app.Use(limiter.New(limiter.Config{
		Max:                5,
		Expiration:         10 * time.Second,
		LimiterMiddleware:  limiter.SlidingWindow{},
		SkipFailedRequests: true,
	}))

	app.Get("/test", func(c *fiber.Ctx) error {
		fmt.Println("start")
		return c.SendString("OK")
	})
	log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
is your application behind a reverse proxy or api gateway? have you defined the proxy header? otherwise the ip method uses that of the reverse proxy and it has an effect on all requests

**Comment by yellowmarlboro** [comment]
My application is a internal application, only other internal app will send request, so there is no reverse proxy or api gateway behind that. and i want set `KeyGenerator ` to `para from request body`, the parameter has 10 possible enumeration values.
Now i know what you mean, i will try to set a reverse proxy or other way.
thank you so much

**Comment by ReneWerner87** [comment]
please close the issue when it is resolved
