### ISSUE TITLE
🔥 Boilerplate Project Example 

### ISSUE THREAD

**Issue by jeyraj** [gofiber/fiber#258]
**Is your feature request related to a problem?**
NO

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Excellent job team.. I love ExpressJS, Now the similar features on golang.. Simply WOW...
Many of here are from Nodejs. So to kick start the FIBER to production level, Please provide some expressjs style "**Boilerplate Project**".

Like : 
&nbsp;&nbsp;Config:
  &nbsp;&nbsp;&nbsp;&nbsp;config.go
&nbsp;&nbsp;db:
  &nbsp;&nbsp;&nbsp;&nbsp;mongo_connection.go
&nbsp;&nbsp;Models:
  &nbsp;&nbsp;&nbsp;&nbsp;models.go
&nbsp;&nbsp;Controllers:
  &nbsp;&nbsp;&nbsp;&nbsp;businessLogic.go
&nbsp;&nbsp;Routes:
  &nbsp;&nbsp;&nbsp;&nbsp;router.go
&nbsp;&nbsp;main.go

**Comment by Fenny** [comment]
@jeyraj, welcome! This is a great suggestion, I will create a `boilerplate` repo tomorrow!

**Comment by mehmetuken** [comment]
boilerplate can be gorm based.

**Comment by Fenny** [comment]
@mehmetuken PR's are welcome ofcourse. I'm closing this issue on this repo. You can open one at any time [boilerplate one](https://github.com/gofiber/boilerplate) repo.
