### ISSUE TITLE
🤗 [Question]: Set Body Request Limit on Group

### ISSUE THREAD

**Issue by confusionhill** [gofiber/fiber#2583]
### Question Description

Hello, i wanted to ask, are there a way to make a group have a body limit rather than setting it up on the config? because I have this case where different route have different limit

thank you

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
unfortunately not, we are bound to the core and it only allows limits for the whole server

**Comment by ReneWerner87** [comment]
@confusionhill i will close the report, if there are further questions, please report in the discord or reopen the issue
