### ISSUE TITLE
🐛 [Bug]: Routes added on a listening app aren't always immediately available

### ISSUE THREAD

**Issue by contrast-jproberts** [gofiber/fiber#2596]
### Bug Description

When registering a route on a listening `App`, initial requests to the new route may return 404 or 405 response codes. They usually pass through to the new route handler, but not always.

It's possible that a route added on a listening `App` isn't meant to be immediately available, but I didn't see that stated in the documentation so I'm filing this as a bug to start.

### How to Reproduce

I can reproduce the failure by running this unit test with a high count (`-count=200` on my machine).

```go
package fiber

import (
	"io"
	"net"
	"net/http"
	"testing"

	"github.com/gofiber/fiber/v2"
)

func TestFiberRouteRegistration(t *testing.T) {
	app := fiber.New(fiber.Config{
		DisableStartupMessage: true,
	})
	t.Cleanup(func() { app.Shutdown() })

	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatal(err)
	}
	go func() {
		if err := app.Listener(ln); err != nil {
			t.Error(err)
		}
	}()
	addr := ln.Addr().String()

	app.Get("/get", func(ctx *fiber.Ctx) error {
		ctx.WriteString("OK\n")
		return ctx.SendStatus(fiber.StatusOK)
	})

	res, err := http.Get("http://" + addr + "/get")
	if err != nil {
		t.Fatal(err)
	}
	if res.StatusCode != fiber.StatusOK {
		t.Fatal(res.Status)
	}
	if _, err := io.Copy(io.Discard, res.Body); err != nil {
		t.Fatal(err)
	}
}
```

```
go test -timeout 30s -run ^TestFiberRouteRegistration$ example.com/james/scratch/fiber -count=200
--- FAIL: TestFiberRouteRegistration (0.00s)
    fiber_test.go:39: 405 Method Not Allowed
--- FAIL: TestFiberRouteRegistration (0.00s)
    fiber_test.go:39: 404 Not Found
FAIL
FAIL    example.com/james/scratch/fiber 0.859s
FAIL
```

### Expected Behavior

The provided unit test passes with `-count=2000` (10x the count that failed, to be safe).

Or documentation that states that routes added after the app is listening might not be available when the call to `App.Add` returns.

### Fiber Version

v2.48.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
route registration must happen before the start of the server, we do not support routes added afterwards

**Comment by ReneWerner87** [comment]
check 
https://github.com/gofiber/fiber/issues/2443#issuecomment-1531335152 https://github.com/gofiber/fiber/issues/1174#issuecomment-781927952

**Comment by contrast-jproberts** [comment]
@ReneWerner87 That decision makes sense, but can it be added to the Go docs? Most frameworks don't expect users to read PR or issue tracker comments as authoritative docs.

**Comment by ReneWerner87** [comment]
yes you are right

will add it

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/next/guide/routing/#constraints-on-adding-routes-dynamically
