### ISSUE TITLE
🐛 [Bug]: Middleware Propagation

### ISSUE THREAD

**Issue by eos175** [gofiber/fiber#2598]
### Bug Description

I'm experiencing an unexpected behavior in Fiber version v2.48.0, where a middleware applied to one group is propagating to another group even though it's not explicitly applied to that group.

### How to Reproduce

1. Create two groups `/v1` and `/v1` using `app.Group()`.
2. Apply the `AuthenticationMiddleware` to the `apiAuth` group using `apiAuth.Use(middleware.AuthenticationMiddleware(tm))`.
3. Define a route `/with-auth` under `apiAuth` using `apiAuth.Get("/with-auth", ...)`.
4. Define a route `/without-auth` under `api` using `api.Get("/without-auth", ...)`.
5. Observe that the `AuthenticationMiddleware` intended for `apiAuth` also affects the `api` group, even though it's not explicitly applied there.

### Expected Behavior

The `AuthenticationMiddleware` applied to the `apiAuth` group should only affect routes within that group and not propagate to the `api` group.

### Fiber Version

v2.48.0

### Code Snippet (optional)

```go
api := app.Group("/v1")
apiAuth := app.Group("/v1")

apiAuth.Use(middleware.AuthenticationMiddleware(tm))

...

apiAuth.Get("/with-auth", func(c *fiber.Ctx) error {
    return c.SendString("a")
})

api.Get("/without-auth", func(c *fiber.Ctx) error {
    return c.SendString("b")
})
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/guide/grouping

The behavior is not unexpected, we have described it in the doku

Our routing works like expressjs

![Screenshot_2023-08-25-00-41-50-16_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/gofiber/fiber/assets/7063188/f473da6b-1e55-4018-89ff-19ab1088c4fe)
