### ISSUE TITLE
🤗 [Question]: Is fiber currently supports http 2.0 or if isn't when it will support?

### ISSUE THREAD

**Issue by Necoo33** [gofiber/fiber#2602]
### Question Description

Hello, as being a experienced express.js developer i want to use your framework on my projects and i want to know the current status about supporting http 2.0. If i need to use multiple goroutines in my app will it be a problem if isn't support http 2.0, if it will be a problem then is there any workaround for that?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by efectn** [comment]
It won't be supported unless fasthttp gets http2 support. And i can say fasthttp won't get proper http2 support in the near future.

https://github.com/valyala/fasthttp/issues/144#issuecomment-1668501217
https://github.com/valyala/fasthttp/issues/144#issuecomment-1668510072

**Comment by Necoo33** [comment]
> It won't be supported unless fasthttp gets http2 support. And i can say fasthttp won't get proper http2 support in the near future.
> 
> [valyala/fasthttp#144 (comment)](https://github.com/valyala/fasthttp/issues/144#issuecomment-1668501217) [valyala/fasthttp#144 (comment)](https://github.com/valyala/fasthttp/issues/144#issuecomment-1668510072)

thanks for answer. I find an implementation, in this link:

https://github.com/dgrr/http2

Do you consider adopt this? If i was experienced i'll do it myself but unfortunately i'm not.

**Comment by efectn** [comment]
> > It won't be supported unless fasthttp gets http2 support. And i can say fasthttp won't get proper http2 support in the near future.
> > [valyala/fasthttp#144 (comment)](https://github.com/valyala/fasthttp/issues/144#issuecomment-1668501217) [valyala/fasthttp#144 (comment)](https://github.com/valyala/fasthttp/issues/144#issuecomment-1668510072)
> 
> thanks for answer. I find an implementation, in this link:
> 
> https://github.com/dgrr/http2
> 
> Do you consider adopt this? If i was experienced i do it myself but unfortunately i'm not.

It's unmaintained and has some issues

**Comment by gaby** [comment]
@Necoo33 You don't need HTTP/2 to run goroutines within your Fiber app.

For most use cases you can have NGINX, Traefik, Caddy, or any other reverse proxy with HTTP/2 support in front of your Fiber app.
