### ISSUE TITLE
🐛 [Bug]: Logger Middleware: Enabling color changes padding for some fields

### ISSUE THREAD

**Issue by JShorthouse** [gofiber/fiber#2604]
The colourization code for `{method}` and `{status}` formats the value and adds extra padding either side. This padding is not added when colorization is disabled.

https://github.com/gofiber/fiber/blob/8ec7cec43522bc7fe2a035d42458d656e58b667f/middleware/logger/tags.go#L176-L189

This discrepency is immediately obvious when using a custom format that puts these values in brackets, e.g:

```
"${time} [${locals:requestid}: ${ip}] (${status}) [${method}] ${path}​\n"
```

With `DisableColours: false`:

![image](https://github.com/gofiber/fiber/assets/18244032/3f68b50b-b0e7-47db-b399-5950dadb03ef)

`DisableColours: true`:

![image](https://github.com/gofiber/fiber/assets/18244032/47f4fee2-dfd2-4362-a43d-758d42687b01)

**Comment by JShorthouse** [comment]
Personally I can live with the 7 character padding on the method type because it makes sense for "pretty printing" to ensure a constant width for all possible values.

But the single extra spaces on each side really threw me off. There's currently no way for me to remove that space and keep the colours on. I don't think having that spacing makes much sense, if people want an extra space either side they can just add it to their format string like: `( ${status} ) [ ${method} ]`

**Comment by AKARSHITJOSHI** [comment]
@JShorthouse are we looking to remove the extra spacing or add extra spaces on `DisableColours: false` also ??

**Comment by JShorthouse** [comment]
I think removing the spacing would make more sense
