### ISSUE TITLE
🤗 [Question]: Can I get limiter remaining from context?

### ISSUE THREAD

**Issue by LittleSheep2Code** [gofiber/fiber#2608]
### Question Description

I want get limiter remaining from the context, then I can render template with it.

But I tried read response header and it doesn't work. There's any way to get it without modify limiter middleware?

### Code Snippet (optional)

```go
package main

import (
	"log"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/limiter"
)

func main() {
	app := fiber.New()

	app.Use(limiter.New(limiter.Config{
		Max:               20,
		Expiration:        30 * time.Second,
		LimiterMiddleware: limiter.SlidingWindow{},
		LimitReached: func(c *fiber.Ctx) error {
			return c.SendStatus(fiber.StatusTooManyRequests)
		},
	}))

	app.Get("/", func(c *fiber.Ctx) error {
		return c.Render("index", fiber.Map{
			"Limit": c.Get("X-Ratelimit-Limit"), // This doesn't work
		})
	})

	log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@LittleSheep2Code 
c.Get("X-Ratelimit-Limit")
https://docs.gofiber.io/next/api/ctx#get
![image](https://github.com/gofiber/fiber/assets/7063188/bb6a5064-6026-4ba9-b62d-832994eec3ac)

> But I tried read response header ...

pls try
https://docs.gofiber.io/next/api/ctx#getrespheader
![image](https://github.com/gofiber/fiber/assets/7063188/a0d13e93-7ed4-4bb0-a7cf-31b2f7fffb58)

**Comment by LittleSheep2Code** [comment]
Okay, but it still cannot read the data.

```go
package main

import (
        "fmt"
	"log"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/limiter"
)

func main() {
	app := fiber.New()

	app.Use(limiter.New(limiter.Config{
		Max:               20,
		Expiration:        30 * time.Second,
		LimiterMiddleware: limiter.SlidingWindow{},
		LimitReached: func(c *fiber.Ctx) error {
			return c.SendStatus(fiber.StatusTooManyRequests)
		},
	}))

	app.Get("/", func(c *fiber.Ctx) error {
		fmt.Println(c.GetRespHeaders())
		return c.Render("index", fiber.Map{
			"Limit": c.GetRespHeader("X-Ratelimit-Limit"),
		})
	})

	log.Fatal(app.Listen(":3000"))
}
```

And it print:

```txt
map[Content-Type:text/plain; charset=utf-8]
```

**Comment by ReneWerner87** [comment]
I look at it directly

**Comment by ReneWerner87** [comment]
![image](https://github.com/gofiber/fiber/assets/7063188/194bb1f8-aab6-42d0-8c21-7e7ea909c4b0)
it does not run because your handler is executed first and these values are set at the end

**Comment by LittleSheep2Code** [comment]
So how can I get them? Do I need to create a new limiter middleware and change the call order?

**Comment by ReneWerner87** [comment]
it is not possible to change the call order

Max or "X-Ratelimit-Limit" is what you put in the config as "Max"

the order was chosen because the other values can only be determined after the buisness handler has been processed.

**Comment by LittleSheep2Code** [comment]
Why so say it impossible? I tried it and looks like everything is alright.

![image](https://github.com/gofiber/fiber/assets/56875315/d896de4f-ba09-4a10-9261-53525249b2f7)

![image](https://github.com/gofiber/fiber/assets/56875315/1a9c2812-a0c2-44be-9195-735969454afa)

![image](https://github.com/gofiber/fiber/assets/56875315/687c5768-e391-4483-8cb2-95b1874d9b03)

**Comment by ReneWerner87** [comment]
@LittleSheep2Code 
well look at the "if" for the feature skipSuccessfulRequests, skipFailedRequests
it is important that the business handler has already been worked through, because this feature is based on the response from them
and this also changes the remaining number so that it has to be set afterwards or it will be set multiple times, but then it is not consistent

**Comment by LittleSheep2Code** [comment]
Okay, got it.
