### ISSUE TITLE
🚀 [Feature]: allow users to disable caching of CORS-preflight responses

### ISSUE THREAD

**Issue by jub0bs** [gofiber/fiber#2609]
### Feature Description

Omitting the `Access-Control-Max-Age` header from a preflight response leads browsers to cache that response for [5 seconds](https://fetch.spec.whatwg.org/#http-access-control-max-age), whereas including

```http
Access-Control-Max-Age: 0
```

in a preflight response instructs browsers not to cache that preflight response.  However, Fiber CORS middleware ignores that distinction and takes a `MaxAge` value of `0` [as a cue to omit the `Access-Control-Max-Age` header](https://github.com/gofiber/fiber/blob/d44b03e60a68f8414f47e60127371267b8d60719/middleware/cors/cors.go#L188). Therefore, Fiber prevents its users from disabling caching of preflight responses.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
ok good point, then we would have to create the possibility to distinguish between the not set (no header) and the 0 value

**Comment by jub0bs** [comment]
@ReneWerner87 Indeed. If that's any comfort, Fiber's CORS middleware is not alone:

* https://github.com/labstack/echo/issues/2471
* https://github.com/rs/cors/issues/152

**Comment by jub0bs** [comment]
rs/cors recently [fixed this problem](https://github.com/rs/cors/commit/d3f0a2b9d89dc78f36ca65ffc4ff02f6391982d2) by instructing users to set the `MaxAge` field to a negative integer in order to disable preflight caching. I don't think this solution is ideal, but it works well enough. Perhaps something to consider for Fiber too.
