### ISSUE TITLE
🤗 [Question]: How can we call internal api endpoints within the fiber app？

### ISSUE THREAD

**Issue by k359792067** [gofiber/fiber#2621]
### Question Description

I'm trying to forward mqtt requests to http api endpoints in the same program,  is there any way to call it internally and with minimal performance cost.

### Code Snippet (optional)

```go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"

	mqtt "github.com/eclipse/paho.mqtt.golang"
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	app.Post("/hello", func(c *fiber.Ctx) error {
		return c.SendString("hello!")
	})

	var messageHandler mqtt.MessageHandler = func(client mqtt.Client, msg mqtt.Message) {
		payload := msg.Payload()
		go func() {
			jsonPayload, err := json.Marshal(payload)
			if err != nil {
				return
			}

			url := "http://localhost:8000/hello"
			resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonPayload))
			if err != nil {
				return
			}
			defer resp.Body.Close()

			respBody, err := ioutil.ReadAll(resp.Body)
			if err != nil {
				return
			}

			fmt.Println(string(respBody))
		}()
	}

	log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@k359792067 I don't think you need the `goroutine`, you can improve the client call to the server by using the fasthttp client or Fiber Client. 

Docs are here: https://docs.gofiber.io/api/client

**Comment by ReneWerner87** [comment]
@k359792067 is there anything else we can do to help? or can the report be closed?
