### ISSUE TITLE
How can i pass a variable to all templates

### ISSUE THREAD

**Issue by nickfthedev** [gofiber/fiber#2622]
### Question Description

Is it possible to pass for example a variable across all templates?  

For example the user data from a middlware to all templates? 

### Code Snippet (optional)

```go
// Main.go

        page := app.Group("/", middleware.IsLoggedIn) 
         htmx := app.Group("/") 
         // 
         // Routes which render sites 
         // 
         page.Get("/", func(c *fiber.Ctx) error { 
                 fmt.Println(c.Locals("id")) 
                 // Render index template 
                 return c.Render("index", fiber.Map{ 
                         "Title": "Hello, World!", 
                 }) 
         })

// middleware 

func IsLoggedIn(c *fiber.Ctx) error { 
         user, _ := CheckLogin(c) 
         if &user != nil {
// THIS IS REQUIRED IN ALL TEMPLATES
// PART OF THE MAIN MENU IN LAYOUT 
                 c.Locals("name", user.Name) 
                 c.Locals("id", user.ID) 
                 c.Locals("isLoggedIn", true) 
         } 

         c.Locals("message", "Hello, World!") 
         return c.Next() 
 }
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/fiber#config

Try the config setting `PassLocalsToViews`

**Comment by nickfthedev** [comment]
Thank you so much, I was looking 3 days for a solution to my problem!
