### ISSUE TITLE
🤗 [Question]: vendor/github.com/gofiber/fiber/path.go:175:15: undefined: utils.GetTrimmedParam

### ISSUE THREAD

**Issue by awaiter** [gofiber/fiber#2623]
### Question Description

how to solve it？

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
closed because the information is not filled according to our issue template
