### ISSUE TITLE
🐛 Website wrong middleware link

### ISSUE THREAD

**Issue by SahilDhingraa** [gofiber/fiber#2625]
### Bug Description

![image](https://github.com/gofiber/fiber/assets/92306979/ca2f8819-3eaf-4240-af99-3cb8c1f838cf)
this link is broken

### How to Reproduce

Go on gofiber.io and then scroll to **Flexible Middleware Support**

### Expected Behavior

It should be directing to a working url

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Thx for the report
New url is https://docs.gofiber.io/category/-middleware
But i will add a redirect url in our docs

**Comment by ReneWerner87** [comment]
fixed with https://github.com/gofiber/docs/commit/516124c7ff0ef7f939ace41c58b672785d87e8e0
