### ISSUE TITLE
🤗 [Question]: is there any fallback on middleware?

### ISSUE THREAD

**Issue by FrHaN23** [gofiber/fiber#2630]
### Question Description

i want to create 2 method auth using my own credential and using keycloak (gocloak: [link](https://github.com/Nerzal/gocloak)) and using fiber.use as middleware. is there any type of fallback if my own auth or keycloak fail and using another one vice versa?

Middleware:

```go
func Protected() fiber.Handler {
	keycloak.IntrospectToken()

	return jwtware.New(jwtware.Config{
		SigningKey:   []byte(config.Env("SECRET")),
		ErrorHandler: jwtError,
	})
}
```

Keycloak Retrospect
```go
func IntrospectToken() fiber.Handler {
	cloak := KeyCloak().gocloak

	return func(c *fiber.Ctx) error {
		context := c.Context()
		res, err := cloak.RetrospectToken(
			context,
			c.Get("authorization"),
			KeyCloak().clientId,
			KeyCloak().clientSecret,
			KeyCloak().realm,
		)
		if err != nil {
			return c.Status(fiber.StatusBadRequest).SendString("Missing or malformed JWT")
		}
		if !*res.Active {
			return c.Status(fiber.StatusForbidden).JSON(fiber.Map{"status": "error", "message": err.Error()})
		}
		return c.Next()
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
not really
if one of the two does not call the next anymore or returns an error the process is finished

**Comment by FrHaN23** [comment]
thanks for replay @ReneWerner87. i did find solution by compering is cloak function has return or not
here snippet:

```go
func Protected() fiber.Handler {
	cloak := keycloak.IntrospectToken()
	if cloak == nil {
		return jwtware.New(jwtware.Config{
			SigningKey:   []byte(config.Env("SECRET")),
			ErrorHandler: jwtError,
		})
	}

	return cloak
}
```
