### ISSUE TITLE
🤗 [Question]: Log errors in Nginx

### ISSUE THREAD

**Issue by BassamMasry** [gofiber/fiber#2631]
### Question Description

First I want to thank you for the great, super-fast web framework.

My question is, I am using Nginx as a web server with the fiber as a web framework, but the error logs are not working for some reason. I tried ```os.Stderr.WriteString```, ```os.Stdout.WriteString```, and ```log.Println```... All without use.

Tell me please, is there a way to log errors through Nginx?

I attached the ```CentralizedErrorHandler``` function, and the Nginx configuration file.

The log messages are being displayed in the console but not the error log file.

This is the content of my error.log:
```2023/09/11 13:46:38 [notice] 28460#28460: signal process started```

### Code Snippet (optional)

```go
var CenteralizedErrorHandler = func(c *fiber.Ctx, err error) error {
	// Status code defaults to 500
	code := fiber.StatusInternalServerError

	// Retrieve the custom status code if it's a *fiber.Error
	var e *fiber.Error
	if errors.As(err, &e) {
		code = e.Code
	}

	os.Stderr.WriteString("Error: ERRRRRRRORRRRR\n")
	os.Stdout.WriteString("Error: MIRRRRRORRRR\n")
	log.Println("Error:", err)
	return c.Status(code).SendString(err.Error())
}
```

### Nginx configuration:

```
server {
  listen 80;
  listen [::]:80;
  server_name localhost;

  error_log /var/log/nginx/error.log warn;

location /static {
  alias /home/bassam/git/Jobs/pogostu/static/;
}

location /favicon.ico {
  alias /home/bassam/git/Jobs/pogostu/static/favicons/favicon.ico;
}

location / {
  proxy_pass http://127.0.0.1:3000;
  }
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
Nginx is a reverse proxy, not a log collector.

**Comment by BassamMasry** [comment]
Yes, after a lot of researching, I found that there is no simple way to force Nginx to log the application-specific errors.
Sorry for the confusion.
