### ISSUE TITLE
🤗 [Question]: How to find html in docker by Fiber Template

### ISSUE THREAD

**Issue by hairgely** [gofiber/fiber#2633]
### Question Description

Html folder path is different in docker.    

FROM golang:alpine AS builder
ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
RUN apk add --no-cache tzdata
WORKDIR /build
COPY . ./
RUN go mod tidy
RUN go mod download
RUN go build -o main ./
WORKDIR /dist
RUN cp /build/main .

FROM scratch
COPY --from=builder /dist/main .
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo

ENTRYPOINT ["/main"]

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New(fiber.Config{
		Views: html.New("./views", ".html"),
})

app.Get("/queue/:app/:pid", func(c *fiber.Ctx) error {
return c.Render("queue", fiber.Map{})
})

  // An example to describe the question
// I get error message : [failed to render: render: template queue does not exist]
// In docker...    local is very well work in macbook

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@hairgely if your file structure in your docker image is different and you can't do anything to match it, you should create an enviroment variable and use it with different paths

**Comment by hairgely** [comment]
thank.  
I have solved the problem. Thanks to you
