### ISSUE TITLE
🤗 [Question]: is there a way to retrieve snake case parameters with QueryParser?

### ISSUE THREAD

**Issue by jianmaikj** [gofiber/fiber#2635]
### Question Description

```
type Item struct {
	ItemId     uint64 `validate:"required" json:"item_id"`
}

```
How can I parse the `item_id` in querystring to `ItemId` when using `QueryParser()`

Thanks!

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Sure, you can specify it in the annotation

Check the example https://docs.gofiber.io/next/api/ctx#queryparser

**Comment by jianmaikj** [comment]
> Sure, you can specify it in the annotation
> 
> Check the example https://docs.gofiber.io/next/api/ctx#queryparser

thank you!
