### ISSUE TITLE
🤗 [Question]: How to work with multipart.FileHeader and validation body parser?

### ISSUE THREAD

**Issue by hbinduni** [gofiber/fiber#2636]
### Question Description

```
type MyForm struct {
	File     *multipart.FileHeader `form:"file" validate:"required"`
}

app.Post("/upload-v1", func(c *fiber.Ctx) error {
		// Parse the request body into MyForm
		form := new(MyForm)
		if err := c.BodyParser(form); err != nil {
			msg := fmt.Sprintf("Failed to parse the request body: %s", err.Error())
			return c.Status(http.StatusBadRequest).JSON(&fiber.Map{"ok": false, "msg": msg})
		}

		log.Printf("form: %+v", form) // <= this return form.File null

		return c.Status(http.StatusOK).JSON(&fiber.Map{"ok": true})
	})
```

i call the upload with this curl:
```
curl -X POST -F "file=@/tmp/data/test-data.txt" \
  http://localhost:3000/upload-v1
```

it give me `form: &{File:<nil>}` on the console. 
and return error `Validation failed: Key: 'MyForm.File' Error:Field validation for 'File' failed on the 'required' tag`
what is the proper way to work wtih form data validation and body parser? does it support form data validation?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by efectn** [comment]
It will be implemented in v3 -> https://github.com/gofiber/fiber/issues/2002. https://github.com/gorilla/schema doesn't support -*multipart.FileHeader
