### ISSUE TITLE
🚀 [Feature]: CookieParser

### ISSUE THREAD

**Issue by balcieren** [gofiber/fiber#2639]
### Feature Description

I think it is a feature that can be added

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"

type Cookie struct {
	Name string `json:"name" cookie:"name"`
}

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		var cookies Cookie
		if err := c.CookieParser(&cookies); err != nil {
			return err
		}

		return c.SendString(cookies.Name)
	})

	app.Listen(":3000")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by joey1123455** [comment]
Is any one working on this at the moment, I'm available to work on it

**Comment by joey1123455** [comment]
Quick question, while parsing the cookie result would we need just the cookie value or also the value and its attributes, thinking about making it viable for both?

**Comment by balcieren** [comment]
@joey1123455  Actually working system is similar to QueryParser. What's more I tried to make cookie parser but I got panic error.

**Comment by joey1123455** [comment]
> @joey1123455  Actually working system is similar to QueryParser. What's more I tried to make cookie parser but I got panic error.

Aiit, I have implemented it, just writing the tests. What package where you working with when you the panic was raised and what we're you doing?
