### ISSUE TITLE
Does Fiber has a default project structure as same as the Expressjs provided?

### ISSUE THREAD

**Issue by wilsonwu** [gofiber/fiber#264]
I think it is better to has a default/common project structure, like Expressjs, we can use the command line to create a very clear and useful project structure, or Fiber could just provide a git repo for users.

**Comment by UJPrasad** [comment]
@wilsonwu I guess this is what you are looking for? https://github.com/gofiber/boilerplate

**Comment by Fenny** [comment]
Hey @wilsonwu, welcome!

We created a [boilerplate](https://github.com/gofiber/boilerplate) but is not finished yet, PR's are welcome!

**Comment by wilsonwu** [comment]
@UJPrasad @Fenny thanks for your answer, I will follow the project.
