### ISSUE TITLE
🤗 [Question]: Idempotency middleware does not init  feild Storage correctly

### ISSUE THREAD

**Issue by lcnap** [gofiber/fiber#2643]
### Question Description

Idempotency middleware does not init  feild `Storage` in `ConfigDefault` correctly。`app.Use(idempotency.New())` will cause nil pointer panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x71f15e]

goroutine 10 [running]:
github.com/gofiber/fiber/v2/middleware/idempotency.New.func1(0xc000004600, {0xc000022240?, 0x24?})
        /home/lcnap/go/pkg/mod/github.com/gofiber/fiber/v2@v2.49.2/middleware/idempotency/idempotency.go:38 +0x3e
github.com/gofiber/fiber/v2/middleware/idempotency.New.func2(0xc000004600)
        /home/lcnap/go/pkg/mod/github.com/gofiber/fiber/v2@v2.49.2/middleware/idempotency/idempotency.go:84 +0x145
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@leonklingele can you help here?

**Comment by leonklingele** [comment]
Will fix this asap.
