### ISSUE TITLE
🐛 [Bug]: Pass-locals-to-views not work if bind is nil

### ISSUE THREAD

**Issue by findridoy** [gofiber/fiber#2644]
### Bug Description

Let's say I am returning a simple view like this:

```go
protected.Get("/", func(c *fiber.Ctx) error {
		c.Locals("K", "v")
		return c.Render("views/index", nil)
	})
``` 

Now local 'K' will not be available on view. I have to set an empty map to have that local, like this:

```go
protected.Get("/", func(c *fiber.Ctx) error {
		c.Locals("K", "v")
		return c.Render("views/index", fiber.Map{})
	})
```

I don't know is this intentional or not but having binding optional is may be okay?

If it is intentional and we have to explicitly put empty map then please close this issue.

### How to Reproduce

1. Enable PassLocalToView to true
2. Set local to ctx
3. set bind to nil
4. local will not be available on view

### Expected Behavior

Binding is nill but locals are available on view

### Fiber Version

2.48

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
Thx for the report
