### ISSUE TITLE
🚀 [Feature]: Render should have optional content type

### ISSUE THREAD

**Issue by goliatone** [gofiber/fiber#2670]
### Feature Description

I want to be able to use the view engine to render non HTML content, e.g. JSON, and specify the right mime type of the response. Currently is hardcoded to `MIMETextHTMLCharsetUTF8`.

This could be as simple as exposing a new render function that takes options and the current `Render` implementation would call this new function with the HTML mime type

### Code Snippet (optional)

```go
func (c *Ctx) RenderOpts(name string, bind interface{}, mime string, layouts ...string) error { 
   ...
    // Set Content-Type to text/html
    c.fasthttp.Response.Header.SetContentType(mime)
    // Set rendered template to body
    c.fasthttp.Response.SetBody(buf.Bytes())

    return nil
}

func (c *Ctx) Render(name string, bind interface{}, layouts ...string) error { 
   return c.RenderOpts(name, bind, MIMETextHTMLCharsetUTF8, layouts...)
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by ReneWerner87** [comment]
Use the type(contentType) method after the render method.

**Comment by goliatone** [comment]
Ok, that was non-obvious to me, since the `Render` method returns an error I assumed it was final and admittedly I did not try what you suggested since other frameworks (like express) will throw an error if you try to modify the response after calling the body function. 
I had to go from:
```go
func handleRoute(c *fiber.Ctx) error {
...
    render c.Render(template, fiber.Map{
        "data": data,
    })
}
```

to this:

```go
func handleRoute(c *fiber.Ctx) error {
...
    render c.Render(template, fiber.Map{
        "data": data,
    })
    c.Type("json", "utf-8")
    return nil
}
```
