### ISSUE TITLE
🤗 [Question]: should we validate client ip in session middleware?

### ISSUE THREAD

**Issue by iredmail** [gofiber/fiber#2672]
### Question Description

Dear all,

Seems fiber session middleware doesn't verify client IP address, is it secure if client IP changed but sent http request with same cookie / session id?

I used Python web framework `web.py`, it offers an option `ignore_change_ip` to control this situation, default value is `false`. If client IP changed, session will be destroyed. With ignore_change_ip=true, it ignores client IP change.

FYI

https://github.com/webpy/webpy/blob/master/web/session.py#L138-L142

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
it is not insecure, but we could add it as a feature to increase security for critical applications

**Comment by sixcolors** [comment]
It’s generally a bad idea to bind tokens to IP addresses. Consider proxies, VPNs, Private Relay (macOS and iOS users), users moving between WiFI and cellular, etc.

Ref See: https://www.akamai.com/blog/developers/why-you-shouldn-t-tie-ip-addresses-to-tokens

https://security.stackexchange.com/questions/139952/why-arent-sessions-exclusive-to-an-ip-address#:~:text=First%2C%20linking%20a%20session%20to,%2C%20CDN%2C%20etc.
