### ISSUE TITLE
🤗 [Question]: need to modify request form in request body

### ISSUE THREAD

**Issue by Noraddeen** [gofiber/fiber#2674]
### Question Description

I need to modify request form add new field (key/value) and can't use ctx.Local it should be part of request for that sent
this is my middleware func trying to add new field which is url parameter in request body.

### Code Snippet (optional)

```go
func AddParamToBody(paramName string) fiber.Handler {
    return func(c *fiber.Ctx) error {
        paramValue := c.Params(paramName)
        var bodyMap map[string]interface{}
        json.Unmarshal(c.Body(), &bodyMap); 
        bodyMap[paramName] = paramValue
        newBody, err := json.Marshal(bodyMap)
        
        // this is caused error, no SetBody() function exist in fiber framework
        c.SetBody(newBody)        // error

        return c.Next()
    }
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@Noraddeen check this

```go
func AddParamToBody(paramName string) fiber.Handler {
    return func(c *fiber.Ctx) error {
        paramValue := c.Params(paramName)
        var bodyMap map[string]interface{}
        json.Unmarshal(c.Body(), &bodyMap);
        bodyMap[paramName] = paramValue
        newBody, err := json.Marshal(bodyMap)
        
        if err != nil {
            return err
        }

        c.Request().SetBody(newBody)

        return c.Next()
    }
}

```

**Comment by Noraddeen** [comment]
@ReneWerner87 
thanks a lot it worked

**Comment by Noraddeen** [comment]
I guess it will be nice if being add to documentation.
I mean the use of Request().SetBody(newbody)

**Comment by ReneWerner87** [comment]
we will do, if we are asked for it more often
