### ISSUE TITLE
🤗 [Question]: CORS middleware and errors

### ISSUE THREAD

**Issue by edwh** [gofiber/fiber#2680]
### Question Description

I'm seeing a CORS error which makes me think that if an error is returned, then the CORS middleware is not adding the usual headers.

Is there any way to make it do this?  

### Code Snippet (optional)

Enabling CORS:

```
	app.Use(cors.New(cors.Config{
		MaxAge: 86400,
	}))
```

Then later:

```
return fiber.NewError(fiber.StatusNotFound, "User not found")
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by sixcolors** [comment]
> ### Question Description
> I'm seeing a CORS error which makes me think that if an error is returned, then the CORS middleware is not adding the usual headers.
> 
> Is there any way to make it do this?
> 
> ### Code Snippet (optional)
> Enabling CORS:
> 
> ```
> 	app.Use(cors.New(cors.Config{
> 		MaxAge: 86400,
> 	}))
> ```
> 
> Then later:
> 
> ```
> return fiber.NewError(fiber.StatusNotFound, "User not found")
> ```
> 
> ### Checklist:
> * [x]  I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
> * [x]  I have checked for existing issues that describe my questions prior to opening this one.
> * [x]  I understand that improperly formatted questions may be closed without explanation.

Do you have an example app demonstrating this behavior you could share?

**Comment by edwh** [comment]
I don't have a minimal repro.  It felt like the kind of thing where someone would say "No, that won't work because X" or "Yes, that should work".  Obviously if it isn't that kind of thing then I should write one.

**Comment by sixcolors** [comment]
> I don't have a minimal repro. It felt like the kind of thing where someone would say "No, that won't work because X" or "Yes, that should work". Obviously if it isn't that kind of thing then I should write one.

I’ll take a look 👀 if you did a minimal repo already please share, but it’s easy enough for me to write one.

**Comment by edwh** [comment]
I made a minimal repro, and the headers were set correctly.  So this 
looks like it's a problem at my side which I've not diagnosed properly, 
or it needs a more complex repro.

Thanks for your offer to help - I'll update this issue when I get to the 
bottom of it.


------ Original Message ------
From "Jason McNeil" ***@***.***>
To "gofiber/fiber" ***@***.***>
Cc "Edward Hibbert" ***@***.***>; "Author" 
***@***.***>
Date 18/10/2023 03:10:27
Subject Re: [gofiber/fiber] 🤗 [Question]: CORS middleware and errors 
(Issue #2680)

**Comment by edwh** [comment]
Sure.


------ Original Message ------
From "RW" ***@***.***>
To "gofiber/fiber" ***@***.***>
Cc "Edward Hibbert" ***@***.***>; "Author" 
***@***.***>
Date 18/10/2023 13:15:08
Subject Re: [gofiber/fiber] 🤗 [Question]: CORS middleware and errors 
(Issue #2680)

**Comment by edwh** [comment]
No, I'm not using csrf.

**Comment by ReneWerner87** [comment]
can you share the reproducible example so we can help you ?

**Comment by edwh** [comment]
Aa far as I can tell, this is caused by Chrome wrongly caching CORS results after an error. I can't quite get a clear repo but I can see that it stops sending OPTIONS requests. If I restart Chrome then it works OK.

So I no longer think this is a fiber issue. Thank you for your attention.
