### ISSUE TITLE
🐛 [Bug]: CSRF middleware default ContextKey and PassLocalsToViews

### ISSUE THREAD

**Issue by ly020044** [gofiber/fiber#2682]
### Bug Description

I'm using csrf middleware with v2.49.2 is worked. But after upgrade to v2.50.0, Errors will occur when visit any page.

```failed to render: [Error (where: checkForValidIdentifiers)] context-key 'fiber.csrf.handler' (value: '&{config:0x14001198a00 sessionManager:<nil> storageManager:0x14000842e80}') is not a valid identifier```

If change csrf config `HandlerContextKey="csrf"`, is worked. Because `HandlerContextKey` is default value `fiber.csrf.handle`, So the default value contains the `.` character. `.xx` is usually used in templates to access properties or methods.

### How to Reproduce

1. Set fiber.Config `PassLocalsToViews: true`
1. Use `django` html engine.
2. Use CSRF middleware

### Expected Behavior

Can visit all pages.

### Fiber Version

v2.50.0

### Code Snippet (optional)

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/csrf"
	"github.com/gofiber/template/django/v3"
)

func main() {
	engine := django.New("./views", ".html")

	// Pass the engine to the Views
	app := fiber.New(fiber.Config{
		Views:             engine,
		PassLocalsToViews: true,
	})

	app.Use(csrf.New())

	app.Get("/", func(c *fiber.Ctx) error {
		// Render index
		return c.Render("index", fiber.Map{
			"Title": "Hello, World!",
		})
	})

	log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by sixcolors** [comment]
@ly020044 I am looking into this now. It doesn't cause errors with HTML.

**Comment by sixcolors** [comment]
gofiber/template/django/v3 will pass keys to Pongo2 that do not meet the regex in `checkForValidIdentifiers()`

The regex is:

```go
var reIdentifiers = regexp.MustCompile("^[a-zA-Z0-9_]+$")
```

I have created a PR that will exclude any KVP that has an "invalid identifier".
