### ISSUE TITLE
🤗 [Question]: How can i filter logs by regexp?

### ISSUE THREAD

**Issue by mv-yurchenko** [gofiber/fiber#2683]
### Question Description

I have service in k8s cluster and k8s checks

After each check I got a log message

How can I disable printing log for healtcheck route

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@mv-yurchenko there is a NEXT method in the configuration which is for skipping unwanted paths
https://docs.gofiber.io/api/middleware/logger#config

**Comment by ReneWerner87** [comment]
@mv-yurchenko do you have other questions? can i close the issue report?

**Comment by ReneWerner87** [comment]
if you have any questions, just reopen
