### ISSUE TITLE
🤗 [Question]: Next() in middleware not filtering requests. Am I doing something wrong?

### ISSUE THREAD

**Issue by visheshnayak** [gofiber/fiber#2691]
### Question Description

I am using `keyauth.New(keyauth.Config(...))` to set a value for `Next` which skips the middleware check. I have attached both the where I register the middleware and the function that I am using. 

I went through the code of what is being returned from `keyauth.New(...)` and it seems pretty straightforward. I don't understand what I am doing wrong there... Either `cfg.Next()` is `nil` which cannot be because I did assign the function or `cfg.Next()` is returning `false`, which is also not possible because I am sure that the function returns `true`.

Please do help. Thanks.

### Code Snippet (optional)

```go
// registering
	mw.app.Use(keyauth.New(keyauth.Config{
		Next:      mw.authFilter,
		KeyLookup: "cookie:USS_TOKEN",
		Validator: mw.validateAPIKey,
	}))

// authFilter
func (mw *MiddleWare) authFilter(c *fiber.Ctx) bool {
	originalURL := strings.ToLower(c.OriginalURL())
	originalMethod := c.Method()

	for _, exclude := range mw.excludeList {
		if strings.Contains(originalURL, exclude.path) && // I printed out the result, it is false && true = false
			exclude.method == originalMethod {
			return false
		}
	}
	return true
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by visheshnayak** [comment]
I apologise for not using discord as I do not have access to it from here. Please do overlook that.

**Comment by ReneWerner87** [comment]
Believe your return value is the wrong way around
If the method returns true, it will skip
If nil or false nothing will be skipped

Otherwise you can just print the conditions or debug it.
Except for the rotation of the return you are using it correctly and the internal code is also ok (just checked).

**Comment by ReneWerner87** [comment]
@visheshnayak does it work?

**Comment by visheshnayak** [comment]
> Believe your return value is the wrong way around If the method returns true, it will skip If nil or false nothing will be skipped
> 
> Otherwise you can just print the conditions or debug it. Except for the rotation of the return you are using it correctly and the internal code is also ok (just checked).

Hi, thank you for replying, yes, I did code it that way because I was testing all possibilities. I did figure that out when I went through the source code: 
```
// Filter request to skip middleware
if cfg.Next != nil && cfg.Next(c) {
    return c.Next()
}
```
I understood it from that part. I did figure it out though. Apparently, the issue was in my validator for APIkey. I was letting it go even if the condition failed. So, I guess, it was user error. Thanks a lot @ReneWerner . Cheers.
