### ISSUE TITLE
🤗 [Question]: BodyParser can't bind json data to struct

### ISSUE THREAD

**Issue by kalougata** [gofiber/fiber#2697]
### Question Description

I wrote a function "BindAndCheck" to bind and parse the JSON and validate the parameters, but it doesn't bind the JSON to the struct.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "github.com/gookit/validate"
import "log"

func BindAndCheck(c *fiber.Ctx, data any) error {
	if err := c.BodyParser(data); err != nil {
		return response.Build(c, e.ErrBadRequest().WithMsg(err.Error()), nil)
	}
	fmt.Println(data) // nil
        
        // this is validate library
	if v := validate.Struct(data); !v.Validate() {
		return response.Build(c, e.ErrInternalServer().WithErr(v.Errors), nil)
	}

	return nil
}

func main() {
  app := fiber.New()

  // An example to describe the question
  app.Post("/login", func(c *fiber.Ctx) error {
    data := &LoginReq{}
    if err := BindAndCheck(c, data);err!=nil {
       return err
    }
    
    return c.JSON(400, "invalid request body")
  })

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by nickajacks1** [comment]
Double check that your request has the `Content-Type` header set to `application/json`.  If it doesn't, it will not parse as JSON.
If you're using curl, the default Content-Type is `application/x-www-form-urlencoded`

**Comment by kalougata** [comment]
> Double check that your request has the `Content-Type` header set to `application/json`. If it doesn't, it will not parse as JSON. If you're using curl, the default Content-Type is `application/x-www-form-urlencoded`

Thanks for the reply I am using Postman and the request format is JSON

**Comment by ReneWerner87** [comment]
@kalougata can you please share a curl request and the definition of the struct so we can analyze the problem

**Comment by kalougata** [comment]
> @kalougata can you please share a curl request and the definition of the struct so we can analyze the problem

yes, of course

```go
type LoginReq struct {
	UserName  string `json:"user_name"`
	PassWord  string `json:"password"`
}
```

```
curl -XPOST -H "Content-type: application/json" -d '{
  "user_name": "John Doe",
  "password": "123456"
}' 'http://localhost:8000/api/v1/login'
```

**Comment by kalougata** [comment]
> @kalougata can you please share a curl request and the definition of the struct so we can analyze the problem

My question is, when I was developing the project, I wrote the BodyParser step in the BindAndCheck function resulting in the inability to parse the JSON and bind it to the struct

**Comment by kalougata** [comment]
> @kalougata can you please share a curl request and the definition of the struct so we can analyze the problem

I tried to
```go
func BindAndCheck(c *fiber.Ctx, data any) error {
	if err := c.BodyParser(data); err != nil {
		return response.Build(c, e.ErrBadRequest().WithMsg(err.Error()), nil)
	}
	fmt.Println(data) // nil
        
        // this is validate library
	if v := validate.Struct(data); !v.Validate() {
		return response.Build(c, e.ErrInternalServer().WithErr(v.Errors), nil)
	}

	return nil
}
```

**Comment by ReneWerner87** [comment]
@kalougata cannot reproduce with this data
<img width="1573" alt="image" src="https://github.com/gofiber/fiber/assets/7063188/68270417-3b52-45ce-a403-96d94d72efa8">

**Comment by kalougata** [comment]
> @kalougata cannot reproduce with this data <img alt="image" width="1573" src="https://user-images.githubusercontent.com/7063188/279704896-68270417-3b52-45ce-a403-96d94d72efa8.png">

I tried again and there were no more errors. It's mind-boggling 🤣
