### ISSUE TITLE
🤔 How can I structure my routes into seperate files?

### ISSUE THREAD

**Issue by monzarrugh** [gofiber/fiber#270]
Right now all of my routes are in the main function.

What is the correct way to structure my application so that I can separate routes into multiple files the same way as with express?

I want to handle the GET, POST etc. of each route in a separate file for that route

**Comment by renanbastos93** [comment]
Hey @monzarrugh 

If I understood you, I suggest you use a design pattern in your project, I am using currently `clean architecture` 

https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html

**Comment by mthli** [comment]
Structure routes into seperate files may caused routes conflict 🤔

**Comment by Fenny** [comment]
@monzarrugh, does this help https://github.com/gofiber/boilerplate?
Or are you looking to move whole groups into separate files?

**Comment by monzarrugh** [comment]
> Or are you looking to move whole groups into separate files?
Yes I'd like to handle a group requests in a separate file

**Comment by Fenny** [comment]
@monzarrugh you could pass `app` to a custom function to register routes from a separate file.
```go
// ./main.go
package main

import (
	"./routes"
	"github.com/gofiber/fiber"
)

func main() {
	app := fiber.New()

	routes.RegisterAPI(app)

	app.Listen(3000)
}
// ./routes/main.go
package routes

import (
	"github.com/gofiber/fiber"
)

func RegisterAPI(app *fiber.App) {
	app.Get("/admin", 		handlerAdmin)
	app.Post("/register", handlerRegister)
	app.Post("/login", 		handlerLogin)
}

```
