### ISSUE TITLE
🤗 [Question]: Fiber config WriteTimeout and ReadTimeout not working

### ISSUE THREAD

**Issue by fluoz** [gofiber/fiber#2702]
### Question Description

How WriteTimeout and ReadTimeout works and how i want to test it?

### Code Snippet (optional)

```go
package main

import (
	"log"
	"time"

	"github.com/gofiber/fiber/v2"
)

func main() {

	app := fiber.New(fiber.Config{
		ReadTimeout:  1 * time.Second,
		WriteTimeout: 1 * time.Second,
	})

	app.Get("/ping", func(c *fiber.Ctx) error {
		time.Sleep(2 * time.Second)
		return c.SendString("hello")
	})

	log.Fatal(app.Listen(":8081"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
https://docs.gofiber.io/api/fiber

Have you read the documentation?
These 2 settings have nothing to do with the timeout in your handler. 

The read timeout is the timeout that exists when the request is read and the write timeout is the timeout for writing the response. These settings are in the unittests of our package and or the underlying fasthttp framework.
You are probably looking for a way to give your handler a timeout for execution, for that look at this
https://docs.gofiber.io/api/middleware/timeout

**Comment by ReneWerner87** [comment]
@fluoz any other question to this?

**Comment by ReneWerner87** [comment]
if you have any questions, just reopen
