### ISSUE TITLE
🐛 [Bug]: Using Head Method Header ContentLength always set and is not zero

### ISSUE THREAD

**Issue by afifurrohman-id** [gofiber/fiber#2703]
### Bug Description

I don't know why fiber always Set Header `ContentLength` with non zero value, even using `HEAD` method

I have try using `ctx.Send(nil)` still same, even i set header manually `ctx.Set(fiber.HeaderContentLength, "")`  still didn't work

### How to Reproduce

1. Run test for code sample.
```sh
go test -v 
```

2. See..
```diff
=== RUN   TestHead
2023/11/04 05:35:45.740429 main_test.go:27: [Fatal] Expected Header ContentLength to zero, but got 18
exit status 1
FAIL    go-fiber-bug-head       0.641s
```

### Expected Behavior

PASS, Header `ContentLength` is not set OR zero value

### Fiber Version

v2.50.0

### Code Snippet (optional)

```go
package main

import (
        "testing"
        "net/http/httptest"
        "github.com/gofiber/fiber/v2"
        "github.com/gofiber/fiber/v2/log"
)

func TestHead(test *testing.T) {
        app := fiber.New()
        app.Head("/", func(ctx *fiber.Ctx) error {
                return ctx.SendStatus(fiber.StatusOK)
        })

        req := httptest.NewRequest(fiber.MethodGet, "/", nil)
        res, err := app.Test(req)
        if err != nil {
            log.Error(err)
        }


        contentLength :=  res.Header.Get(fiber.HeaderContentLength)
        if contentLength != "" {
                log.Fatalf("Expected Header ContentLength to zero, but got %s",contentLength)
        }

}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
It is an automatism, within our kernel, which sets this header automatically and is not a bug

This is intentional

**Comment by afifurrohman-id** [comment]
Ok so, how when i want to unset `ContentLength` header??

**Comment by ReneWerner87** [comment]
Why would you want to do that?

**Comment by ReneWerner87** [comment]
This is determined automatically based on the content.
I can send you an example later of how you can set it to 0, but not unset.

**Comment by ReneWerner87** [comment]
@afifurrohman-id 

![image](https://github.com/gofiber/fiber/assets/7063188/556a8c89-ee8f-4361-87e8-54ea6b0267c5)

```go
	app.Head("/", func(ctx *fiber.Ctx) error {
		return ctx.Status(fiber.StatusOK).Send(nil)
	})
```

![image](https://github.com/gofiber/fiber/assets/7063188/5ae05607-62f5-4797-aa8a-88a53a3b9c0e)
```go
	app.Head("/", func(ctx *fiber.Ctx) error {
		// manipulation of the content length
		ctx.Response().Header.SetContentLength(10000)
		return ctx.Status(fiber.StatusOK).Send(nil)
	})
```

**Comment by afifurrohman-id** [comment]
Okay cool, can you added to docs? May helpful for anyone with same question

**Comment by ReneWerner87** [comment]
if it comes up again, I'll add it
