### ISSUE TITLE
🚀 v3: Update Beta Branch with Changes from Master for v3 Preparation

### ISSUE THREAD

**Issue by ReneWerner87** [gofiber/fiber#2710]
### Description

The beta branch for version 3 needs to be updated with all the changes from the master branch, including bug fixes, features, and other improvements that have been made since the beta branch was last synchronized.

### Objectives:

- [ ] Incorporate all recent updates from the master branch into the beta branch without overwriting any new v3 features.
- [ ] Maintain the integrity and stability of the v3 beta branch by carefully managing merge conflicts.

### Steps for Implementation:

1. Pull the latest changes from the master branch.
2. Merge these changes into the beta branch, ensuring careful handling of any conflicts.
3. Test all merged features and fixes in the context of the beta branch to ensure compatibility.
4. Document any changes made during the merge to assist with any future troubleshooting and to inform the team of changes.

### Expected Outcome:
The beta branch for v3 will be up-to-date with the master branch, including all the latest bug fixes, features, and improvements, ensuring that the v3 beta is as current and stable as possible for further development and eventual release.

**Comment by efectn** [comment]
done https://github.com/gofiber/fiber/commit/6ea4d81331edb14052e278237e8e3b85c4f534d6
