### ISSUE TITLE
Uploading 500MB File

### ISSUE THREAD

**Issue by Jayden000** [gofiber/fiber#272]
**Question description**
When using the [upload-single file recipe](https://github.com/gofiber/recipes/blob/master/upload-file/single/main.go) I am trying to upload a 500MB file just to test Go's performance compared to node in a file upload sense and it says 413 Request Entity Too Large. I was wondering if this was a Fiber limitation and if I can change that somewhere

**Comment by Fenny** [comment]
Hi @Jayden000, did you try changing the [BodyLimit](https://fiber.wiki/application#settings)?

**Comment by Nv7-GitHub** [comment]
I am having this issue, how do you fix it? I can't find anything on `BodyLimit` in the supplied link

**Comment by doppelganger113** [comment]
Always check the library code, found it immediately:
```go
app := fiber.New(fiber.Config{
    BodyLimit: 4 * 1024 * 1024, // this is the default limit of 4MB
})
```

**Comment by pyxiscloud** [comment]
try 
app := fiber.New(fiber.Config{
		//BodyLimit: 400 * 1024 * 1024, // this is the default limit of 4MB
		DisablePreParseMultipartForm: true,
		StreamRequestBody:            true,
	})
