### ISSUE TITLE
🚀 [Feature]: Using Number as Valid Boolean Query Parameter

### ISSUE THREAD

**Issue by afifurrohman-id** [gofiber/fiber#2723]
### Feature Description

It would be better right if Query Parameter Number is Valid Boolean Value using `QueryBool()` method

The mechanism just like a **python** when casting type `int` to `bool`.
`0` is `false` otherwise is `true`

![image](https://github.com/gofiber/fiber/assets/118882411/f59fb6b1-f1d6-4b2e-aa7c-8c88dec5cdd0)

### Additional Context (optional)

```sh
curl https://example.com/?is_ok=1&is=0
```

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  app.Get("/", func (ctx *fiber.Ctx) {
     fmt.Println(ctx.QueryBool("is_ok")) // true
     fmt.Println(ctx.QueryBool("is")) // false

     return nil
  })

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my suggestion prior to opening this one.
- [X] I understand that improperly formatted feature requests may be closed without explanation.

**Comment by dozheiny** [comment]
The **QueryBool** function uses [strconv.ParseBool](https://pkg.go.dev/strconv#ParseBool) function for parsing boolean value types. And it supports 1 and 0 values.
But for a -1 or other value, it didn't support it and returned an error.
Should we add support for all integers not in the `strconv.ParseBool`?

**Comment by dozheiny** [comment]
Also, check this out: https://stackoverflow.com/questions/727196/boolean-true-positive-1-or-negative-1

**Comment by ReneWerner87** [comment]
The current behavior and internal usage is clear. What is your opinion to change the return value to `true` if the internal function returns an error because the values are not in the intersection.

**Comment by dozheiny** [comment]
I think returning a `false` value if it returns an error is better than returning a `false.`

**Comment by ReneWerner87** [comment]
I agree and would rather not take the python approach
But the approach where we use `false` as value if our value list for the boolean value detection is not matched (which corresponds to the underlying golang functionality)

To consider multiple opinions I would like to vote with thumbs up or thumbs down in the initial header comment or request comments as a response for decision making.
@gofiber/contributors @gofiber/maintainers

**Comment by dozheiny** [comment]
Isn't it good to open this in discussions?

**Comment by gaby** [comment]
Any non-zero value should return `True`. For example:

```
curl https://example.com/?is_ok=-1
```

Should return `True`.

**Comment by sixcolors** [comment]
As a proponent of developer autonomy, I believe query parameter handling should typically be managed by the application developer. Nonetheless, gofiber provides `Query*` functions for convenience. Therefore, I maintain that `QueryBool()` should default to the Zero Value, `false`, for bool when no default is provided:

- Consistency: Modifying `QueryBool()` could disrupt applications that depend on it for parsing query parameters as boolean values. Maintaining the current behavior ensures the gofiber framework remains consistent and predictable.

- Go Standards: Adapting `QueryBool()` to Python’s type casting would conflict with Go’s explicit type conversion conventions and the strings package’s `ParseBool()` function, which only recognizes specific string values, “1”, “t”, “T”, “true”, “TRUE”, “True”, as true. See https://go.dev/play/p/ula8bAP4iJw.
	
- Developer Control: gofiber’s QueryBool() supports an optional default value, allowing developers to specify what should happen when a query parameter is missing or invalid. For example, c.QueryBool("key", true) returns true when a parameter is absent or unparseable.

Preserving the current implementation of QueryBool() respects Go’s conventions and developers’ expectations, ensuring framework consistency and reliability.

**Comment by wangjq4214** [comment]
> As a proponent of developer autonomy, I believe query parameter handling should typically be managed by the application developer. Nonetheless, gofiber provides `Query*` functions for convenience. Therefore, I maintain that `QueryBool()` should default to the Zero Value, `false`, for bool when no default is provided:
> 
> * Consistency: Modifying `QueryBool()` could disrupt applications that depend on it for parsing query parameters as boolean values. Maintaining the current behavior ensures the gofiber framework remains consistent and predictable.
> * Go Standards: Adapting `QueryBool()` to Python’s type casting would conflict with Go’s explicit type conversion conventions and the strings package’s `ParseBool()` function, which only recognizes specific string values, “1”, “t”, “T”, “true”, “TRUE”, “True”, as true. See https://go.dev/ref/spec#The_zero_value, https://go.dev/ref/spec#Conversions, https://pkg.go.dev/strconv#ParseBool and https://go.dev/play/p/ula8bAP4iJw.
> * Developer Control: gofiber’s QueryBool() supports an optional default value, allowing developers to specify what should happen when a query parameter is missing or invalid. For example, c.QueryBool("key", true) returns true when a parameter is absent or unparseable.
> 
> Preserving the current implementation of QueryBool() respects Go’s conventions and developers’ expectations, ensuring framework consistency and reliability.

I agree.

**Comment by efectn** [comment]
As we want to have same behavior as Go's `strconv.ParseBool()`, closing the PR as not planned.
