### ISSUE TITLE
🤗 [Question]: Fiber App copies its mutex lock when passing as parameter

### ISSUE THREAD

**Issue by furknozg** [gofiber/fiber#2725]
### Question Description

When you pass the fiber.App reference into a function, it seemingly takes a copy of the mutex. Although the mutex is privately defined has anyone experienced any triggers of potential deadlocks, would this kind of implementation not be considered a best practice in that manner.

Apologies if the question is rather redundant or odd, I'm relatively new to go and this framework.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  SetupServer(*app)
}


func SetupServer(app fiber.App){
  //Actual code not this short but this is a sufficient example
  app.Get("/", func(c *fiber.Ctx) error {
	return c.SendString("Hello, this is a GET request!")
  })


}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@furknozg your function declaration is wrong

```go
func SetupServer(app *fiber.App){
```

https://gobyexample.com/pointers

thats the reason for the copy from golang
