### ISSUE TITLE
🐛 [Bug]: Logger middleware default Format isn't the format that's used

### ISSUE THREAD

**Issue by daenney** [gofiber/fiber#2729]
### Bug Description

> I'm filing this as a bug since I think the behaviour is counter-intuitive.

The logger middleware has a configuration with a default format: https://github.com/gofiber/fiber/blob/2374cad3cd109d3bf33f5863e6eb14c32de1882e/middleware/logger/config.go#L89

However, when the logger proceeds to print this, it ignores the actual format: https://github.com/gofiber/fiber/blob/2374cad3cd109d3bf33f5863e6eb14c32de1882e/middleware/logger/logger.go#L141-L174

Despite it checking for if it should use the default format, it then uses a different format string in the `fmt.Sprintf()` calls.

### How to Reproduce

* Add the logging middleware without overriding the `Format`
* Do a request and observe the log output

### Expected Behavior

Logged line should use the `ConfigDefault.Format` for output, as shown in the configuration: https://docs.gofiber.io/api/middleware/logger#default-config

### Fiber Version

v2.50.0

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by brunodmartins** [comment]
I want to work on this issue!

**Comment by brunodmartins** [comment]
@ReneWerner87 I opened a draft PR! I explained the problem and a proposed solution. Now I have a doubt. The tests for logging have broken due to the correct default format. 

- Should we change the tests or the default format to be like this one that has been used on the middleware?

**Comment by triadmoko** [comment]
i found the same bug
