### ISSUE TITLE
🤗 [Question]: Problem with CSRF after updating fiber to 2.51

### ISSUE THREAD

**Issue by FarsiScript** [gofiber/fiber#2733]
### Question Description

Hi there , guys i have some problem after updating fiber into 1.51
my middleware for CSRF stop working and all time I get 403 error

**Middleware Code :**
```go
App.Use(csrf.New(csrf.Config{
		KeyLookup:         "header:" + HeaderName,
		CookieName:        "csrf_",
		CookieSameSite:    "Lax",
		CookieSessionOnly: true,
		CookieHTTPOnly:    true,
		Expiration:        1 * time.Hour,
		KeyGenerator:      utils.UUIDv4,
		Extractor:         CsrfFromHeader(HeaderName),
		Session:           SessionStore,
		SessionKey:        "fiber.csrf.token",
		HandlerContextKey: "fiber.csrf.handler",
		ContextKey:        "csrfToken",
}))
```

**and the Routes :**
```go
Frontend.Post("/authentication", Controllers.AuthenticationController_Authentication)
Frontend.Get("/SignIn/:error?/:code?", Controllers.AuthenticationController_Signin)
Frontend.Get("/SignUp/:error?/:code?", Controllers.AuthenticationController_Signup)
Frontend.Get("/SignOut", Controllers.AuthenticationController_SignOut)
```

**and the AuthenticationController_Authentication handler :** 
```go
func AuthenticationController_Authentication(c *fiber.Ctx) error {

	email := c.FormValue("email")
	if pkg.IsValidEmail(email) {

		//MD5 The Password
		password := pkg.CryptoMd5Encode(c.FormValue("password") + os.Getenv("APP_SECRET"))

		//Make a object of user
		var users []Models.User

		//Query the db to find the user
		pkg.DB.Where("email = ? AND password = ?", email, password).Find(&users)

		// Handle the result
		if pkg.DB.Error != nil {
			return c.Redirect("/SignIn/error", fiber.StatusFound)
		} else {
			if len(users) > 0 {
				Session, _ := pkg.SessionStore.Get(c)
				Session.Set("isLogin", true)
				Session.Set("UserID", users[0].ID)
				Session.Set("First_name", users[0].First_name)
				Session.Set("Lirst_name", users[0].Last_name)
				Session.Save()

				// Update user's last login date and IP address
				users[0].Logindate = time.Now()
				users[0].Ip = c.IP()

				// Save the updated user record
				pkg.DB.Save(&users[0])

				//If user have right to login 2:enable 1:ban 0:disable
				if users[0].Status == 2 {
					return c.Redirect("/dashboard?", fiber.StatusFound)
				} else {
					return c.Redirect("/SignIn/error/2", fiber.StatusFound)
				}

			} else {
				return c.Redirect("/SignIn/error/1", fiber.StatusFound)
			}
		}
	} else {
		return c.Redirect("/Signin/error/1", fiber.StatusFound)
	}

}
```

**Network header for login page :** 
```
HTTP/1.1 200 OK
Date: Sat, 18 Nov 2023 17:10:58 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 2127
Vary: Cookie
Set-Cookie: session_id=709bd6f3-947a-4a2a-b2f2-edc951f4189e; max-age=86400; path=/; SameSite=Lax
Set-Cookie: csrf_=506115f0-90bb-4997-9b66-a23d02e74d76; path=/; HttpOnly; SameSite=Lax
```

**Network header for authentication post page :** 

```
POST /authentication HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Content-Length: 34
Content-Type: application/x-www-form-urlencoded
Cookie: session_id=709bd6f3-947a-4a2a-b2f2-edc951f4189e; csrf_=506115f0-90bb-4997-9b66-a23d02e74d76
DNT: 1
Host: localhost:3000
Origin: http://localhost:3000
Referer: http://localhost:3000/Signin
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
sec-ch-ua: "Microsoft Edge";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
```

**even when i used the default config i still get the error.**
```go
// Initialize default config
app.Use(csrf.New())
```

Please be advice 
Thanks

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@sixcolors can you help here

**Comment by FarsiScript** [comment]
i get this error if any help :
2023/11/18 23:56:24 CSRF validation error: CSRF token not found in the header

**Comment by sixcolors** [comment]
@FarsiScript I'm not seeing a header with a token in your POST request. Can you provide the HeaderName value and the front end code (html, js, etc) that is submitting the POST request?

**Comment by FarsiScript** [comment]
my login page html code generate by amber :
`main
    div.container
        div.row
            div.col-sm-9.col-md-7.col-lg-5.mx-auto
                div.card.border-0.shadow.rounded-3.my-5
                    div.card-body.p-4
                        h5.card-title.text-center.mb-5.fw-light.fs-5 Sign in
                        form#login[method="POST"][action="/authentication"][name="login"]
                            input[type="hidden"][name="_csrf"][value=CsrfToken]
                            if Error == 1
                                div.alert.alert-danger[role="alert"]
                                    |Sorry ,Invalid email or password.
                            else if Error == 2
                                div.alert.alert-danger[role="alert"]
                                    |Sorry ,Your account is banned.
                            div.form-floating.mb-3
                                input#floatingInput.form-control[type="email"][placeholder="name@example.com"][name="email"][required]
                                label[for="floatingInput"]
                                    |Email address
                                div.invalid-feedback
                                    |Please enter a valid email address.

                            div.form-floating.mb-3
                                input#floatingPassword.form-control[type="password"][placeholder="Password"][name="password"][required]
                                label[for="floatingPassword"]
                                    |Password
                            div.form-check.mb-3
                                input#rememberPasswordCheck.form-check-input[type="checkbox"][value="1"]
                                label.form-check-label[for="rememberPasswordCheck"]
                                    |Remember password
                            div.d-grid
                                button.btn.btn-primary.btn-login.text-uppercase.fw-bold[type="submit"]
                                    |Sign in
                            hr.my-4

`

the html source output is here (hidden input box has token) :
`<html>
<body>

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | 
  | <meta content="width=device-width, initial-scale=1" name="viewport" />
  | <link crossorigin="anonymous" href="/asset/css/bootstrap.min.css" rel="stylesheet" />
  | <link href="/asset/css/app.css" rel="stylesheet" />
  | <title>Sign in</title>
  | <script type="text/javascript" src="http://me.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=7ZiTCOyU77NwpcjbsdRlg50AySsNE_L5y9Dot4aGz1mnKak8L38HGs9J8NjACcp-" charset="UTF-8"></script></head>
  | <body>
  | <main>
  | <div class="container">
  | <div class="row">
  | <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
  | <div class="card border-0 shadow rounded-3 my-5">
  | <div class="card-body p-4">
  | <h5 class="card-title text-center mb-5 fw-light fs-5">Sign in</h5>
  | <form action="/authentication" id="login" method="POST" name="login">
  | <input name="_csrf" type="hidden" value="5255b550-b178-47b4-aefe-295558958c32" />
  | <div class="form-floating mb-3">
  | <input class="form-control" id="floatingInput" name="email" placeholder="name@example.com" required type="email" />
  | <label for="floatingInput">Email address</label>
  | <div class="invalid-feedback">Please enter a valid email address.</div>
  | </div>
  | <div class="form-floating mb-3">
  | <input class="form-control" id="floatingPassword" name="password" placeholder="Password" required type="password" />
  | <label for="floatingPassword">Password</label>
  | </div>
  | <div class="form-check mb-3">
  | <input class="form-check-input" id="rememberPasswordCheck" type="checkbox" value="1" />
  | <label class="form-check-label" for="rememberPasswordCheck">Remember password</label>
  | </div>
  | <div class="d-grid">
  | <button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">Sign in</button>
  | </div>
  | <hr class="my-4" />
  | </form>
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | </main>
  |  
  |  
  | <script src="/asset/js/Jquery.js"></script>
  |  
  | <script crossorigin="anonymous" src="/asset/js/bootstrap.bundle.min.js"></script>
  |  
  | <script src="/asset/js/app.js"></script>
  | </body>
  | </html>
  |  


</body>
</html><!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<meta content="width=device-width, initial-scale=1" name="viewport" />
		<link crossorigin="anonymous" href="[/asset/css/bootstrap.min.css](http://localhost:3000/asset/css/bootstrap.min.css)" rel="stylesheet" />
		<link href="[/asset/css/app.css](http://localhost:3000/asset/css/app.css)" rel="stylesheet" />
		<title>Sign in</title>
	<script type="text/javascript" src="http://me.kis.v2.scr.kaspersky-labs.com/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=7ZiTCOyU77NwpcjbsdRlg50AySsNE_L5y9Dot4aGz1mnKak8L38HGs9J8NjACcp-" charset="UTF-8"></script></head>
	<body>
		<main>
	<div class="container">
		<div class="row">
			<div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
				<div class="card border-0 shadow rounded-3 my-5">
					<div class="card-body p-4">
						<h5 class="card-title text-center mb-5 fw-light fs-5">Sign in</h5>
						<form action="/authentication" id="login" method="POST" name="login">
							<input name="_csrf" type="hidden" value="5255b550-b178-47b4-aefe-295558958c32" />
							<div class="form-floating mb-3">
								<input class="form-control" id="floatingInput" name="email" placeholder="name@example.com" required type="email" />
								<label for="floatingInput">Email address</label>
								<div class="invalid-feedback">Please enter a valid email address.</div>
							</div>
							<div class="form-floating mb-3">
								<input class="form-control" id="floatingPassword" name="password" placeholder="Password" required type="password" />
								<label for="floatingPassword">Password</label>
							</div>
							<div class="form-check mb-3">
								<input class="form-check-input" id="rememberPasswordCheck" type="checkbox" value="1" />
								<label class="form-check-label" for="rememberPasswordCheck">Remember password</label>
							</div>
							<div class="d-grid">
								<button class="btn btn-primary btn-login text-uppercase fw-bold" type="submit">Sign in</button>
							</div>
							<hr class="my-4" />
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</main>

		
		<script src="[/asset/js/Jquery.js](http://localhost:3000/asset/js/Jquery.js)"></script>
		
		<script crossorigin="anonymous" src="[/asset/js/bootstrap.bundle.min.js](http://localhost:3000/asset/js/bootstrap.bundle.min.js)"></script>
		
		<script src="[/asset/js/app.js](http://localhost:3000/asset/js/app.js)"></script>
	</body>
</html>`

**Comment by sixcolors** [comment]
Then you probably want:

```go
App.Use(csrf.New(csrf.Config{
		KeyLookup:         "form: _csrf",
		CookieName:        "csrf_",
		CookieSameSite:    "Lax",
		CookieSessionOnly: true,
		CookieHTTPOnly:    true,
		Expiration:        1 * time.Hour,
		Session:           SessionStore,
		SessionKey:        "fiber.csrf.token",
		HandlerContextKey: "fiber.csrf.handler",
		ContextKey:        "csrfToken",
}))
```

You don't need `Extractor` since you are setting `KeyLookup`, and `KeyGenerator` is `utils.UUIDv4` by default.

**Comment by sixcolors** [comment]
@FarsiScript see example: https://github.com/gofiber/recipes/blob/759fea63d37fa121c1e98f8e22352450c6a0de58/csrf-with-session/main.go#L124

**Comment by FarsiScript** [comment]
> @FarsiScript then you probably want:
> 
> ```go
> App.Use(csrf.New(csrf.Config{
> 		KeyLookup:         "form:_csrf",
> 		CookieName:        "csrf_",
> 		CookieSameSite:    "Lax",
> 		CookieSessionOnly: true,
> 		CookieHTTPOnly:    true,
> 		Expiration:        1 * time.Hour,
> 		Session:           SessionStore,
> 		SessionKey:        "fiber.csrf.token",
> 		HandlerContextKey: "fiber.csrf.handler",
> 		ContextKey:        "csrfToken",
> }))
> ```
> 
> You don't need `Extractor` since you are setting `KeyLookup`, and `KeyGenerator` is `utils.UUIDv4` by default.

can we use it with out putting it into form ?
i mean in cookie or session/ header / config ?

**Comment by sixcolors** [comment]
> can we use it with out putting it into form ? i mean in cookie or session/ header / config ?

Yes. You can use JS fetch/axios/ajax etc to submit POST the form with a header.

Here is an example html/js where you would use the template engine to add a meta tag with the csrf token.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="your_csrf_token">
    <title>Fetch Form Submit with CSRF</title>
</head>
<body>

    <form id="myForm">
        <!-- Your form fields go here -->
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>

        <button type="submit">Submit</button>
    </form>

    <script>
        document.getElementById('myForm').onsubmit = function(event) {
             // Disable the default form submission
            event.preventDefault();

            // Get form data
            const formData = new FormData(document.getElementById('myForm'));

            // Fetch options
            const fetchOptions = {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-Csrf-Token': getCSRFToken() // Include CSRF token in the headers
                },
                body: new URLSearchParams(formData)
            };

            // Fetch the endpoint
            fetch('your_api_endpoint', fetchOptions)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    // Handle the response data as needed
                    // Probably a redirect in the case of the above template...
                    // You may also want to adjust as this example expects a JSON response not a new page....
                    // You should redirect after a login to something that will be a 'safe' (eg GET) request to generate a new csrf token.
                    console.log(data);
                })
                .catch(error => {
                    console.error('There was a problem with the fetch operation:', error);
                });
        };

        function getCSRFToken() {
            // Retrieve CSRF token from the meta tag
            const metaTag = document.querySelector('meta[name="csrf-token"]');
            return metaTag ? metaTag.content : null;
        }
    </script>

</body>
</html>

```

You could also set `CookieHTTPOnly` to `false` and get the token from the cookie. I do this here: https://github.com/sixcolors/gofiber-react-session-csrf-example when I'm using a React front end.

**Comment by FarsiScript** [comment]
Thanks buddy , Your solution totally works.
