### ISSUE TITLE
🐛 [Bug]: utils.IsIPv4 and net.ParseIP have inconsistent results

### ISSUE THREAD

**Issue by itswcg** [gofiber/fiber#2735]
### Bug Description

if config EnableIPValidation set true, The correct IP is filtered.

cause:
utils.IsIPv4 and net.ParseIP have inconsistent results

utils.IsIPv4("123.117.56.255") // return fasle

ip := net.ParseIP("123.117.56.255")
ip.To4() != nil // return true

### How to Reproduce

IP address ending with .255, utils.IsIPv4 always returns false.

### Expected Behavior

utils.IsIPv4("123.117.56.255") return true

### Fiber Version

v2.49.2

### Code Snippet (optional)

```go
app := fiber.New(fiber.Config{
	EnableIPValidation: true,
})

ips = ctx.IPs()
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/blob/2374cad3cd109d3bf33f5863e6eb14c32de1882e/utils/ips.go#L9-L39

```go
func IsIPv4(s string) bool {
    for i := 0; i < net.IPv4len; i++ {
        if len(s) == 0 {
            return false
        }

        if i > 0 {
            if s[0] != '.' {
                return false
            }
            s = s[1:]
        }

        n, ci := 0, 0

        for ci = 0; ci < len(s) && '0' <= s[ci] && s[ci] <= '9'; ci++ {
            n = n*10 + int(s[ci]-'0')
            if n > 0xFF { // change
                return false
            }
        }

        if ci == 0 || (ci > 1 && s[0] == '0') {
            return false
        }

        s = s[ci:]
    }

    return len(s) == 0
}
```

could you test this ?

**Comment by ReneWerner87** [comment]
0xFF is 255

**Comment by itswcg** [comment]
> https://github.com/gofiber/fiber/blob/2374cad3cd109d3bf33f5863e6eb14c32de1882e/utils/ips.go#L9-L39
> 
> ```go
> func IsIPv4(s string) bool {
>     for i := 0; i < net.IPv4len; i++ {
>         if len(s) == 0 {
>             return false
>         }
> 
>         if i > 0 {
>             if s[0] != '.' {
>                 return false
>             }
>             s = s[1:]
>         }
> 
>         n, ci := 0, 0
> 
>         for ci = 0; ci < len(s) && '0' <= s[ci] && s[ci] <= '9'; ci++ {
>             n = n*10 + int(s[ci]-'0')
>             if n > 0xFF { // change
>                 return false
>             }
>         }
> 
>         if ci == 0 || (ci > 1 && s[0] == '0') {
>             return false
>         }
> 
>         s = s[ci:]
>     }
> 
>     return len(s) == 0
> }
> ```
> 
> could you test this ?

it was passed.

utils.IsIPv4("123.117.56.255")  // return true

**Comment by ReneWerner87** [comment]
ok, can you create a pull request that contains the fix and other unittest cases or should I do that?
