### ISSUE TITLE
🤗 [Question]: how to debug requests in Fiber within GoLand

### ISSUE THREAD

**Issue by 1294403205** [gofiber/fiber#2738]
### Question Description

Hello, I would like to ask how to debug requests in Fiber within GoLand. I've noticed that breakpoints in the request functions are not being hit.
![WeChat1eed56622f7d60bec525ca71c96cc997](https://github.com/gofiber/fiber/assets/48780388/64c70fd6-ea9c-4216-8fe9-3074922af589)
![WeChatfddfe106903723f1f92b603078e1e6db](https://github.com/gofiber/fiber/assets/48780388/e8aa4329-6102-44f8-82e5-11a3401b59df)

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
normally we only give info on fiber relevant topics, but i'll try to help here

I can debug at this point
but i would recommend you to set your debugging points not at variable declarations but at real executions maybe your goland version has errors there


# my setup

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"log"
)

func MyFunc(c *fiber.Ctx) error {
	var foo string
	foo = "bar"

	return c.SendString(foo)
}
func main() {
	app := fiber.New()

	app.Get("/test", MyFunc)

	log.Fatalln(app.Listen(":5555"))
}

```
![image](https://github.com/gofiber/fiber/assets/7063188/13d30abc-510c-41bf-9d2c-8b67f792c73e)

![image](https://github.com/gofiber/fiber/assets/7063188/f7df004e-3cef-40bb-9e80-384e11f99ec9)

How to debug:
1. run dlv
```sh
dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient debug main.go
```
2. attach debugger in golang
![image](https://github.com/gofiber/fiber/assets/7063188/e601181b-4d3e-4b22-b83f-1447403d8fd7)
3. open url in browser
```txt
http://localhost:5555/test
```
