### ISSUE TITLE
🐛 [Bug]: Csrf with Session store does not support secure cookie middleware

### ISSUE THREAD

**Issue by rngallen** [gofiber/fiber#2743]
### Bug Description

Store defined as 
```
Store = session.New(
		session.Config{
			Expiration: setups.SessionExpiration,
			KeyLookup:  "header:Session-Id",
			// Storage: ,// Redis on production/Memory on dev
			CookieDomain:   config.Conf.App.Domain,
			CookieSecure:   config.Conf.App.Secure, // True on HTTPS
			CookieHTTPOnly: true,
		},
	)
```
Csrf Configuration 
```
	app.Use(csrf.New(csrf.Config{
		CookieDomain:      config.Conf.App.Domain,
		CookieSecure:      config.Conf.App.Secure, // HTTPS True
		CookieHTTPOnly:    true,
		CookieSameSite:    "Strict",
		CookieSessionOnly: true, // Set True ignore expiration time
		Session:           Store,
		ErrorHandler:      defaultErrorHandler,
	}))
```
This works perfect but if i enable secure cookie middleware 
```
	 app.Use(encryptcookie.New(encryptcookie.Config{
	Key: encryptcookie.GenerateKey(),
	}))
```

csrf always returns forbidden 

### How to Reproduce

Enable secure cookie middleware when csrf storage uses session store

### Expected Behavior

I expect it should also work when secure cookie middleware is in use

### Fiber Version

2.51.0

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by sixcolors** [comment]
@rngallen, thank you for bringing up this issue. After reviewing the encryptcookie middleware in GoFiber, I have some insights to share.

The encryptcookie middleware encrypts incoming cookies and decrypts outgoing ones during its execution in the middleware chain. In GoFiber, middleware runs in the order it is applied. Consequently, any middleware applied before the encryptcookie middleware won't have incoming cookies decrypted, and any middleware applied after won't have its outgoing cookies encrypted.

The [current documentation](https://docs.gofiber.io/api/middleware/encryptcookie#usage-of-csrf-and-encryptcookie-middlewares-with-custom-cookie-names) recommends adding csrf cookies to the `Except` configuration and `csrf_` is part of the `ConfigDefault`. However, if you are using other middleware those cookies would also need to be added to the Except slice.

Given that the tokens used in the Fiber session and CSRF middleware, at least those derived using the default key generator, don't derive a security benefit from encryption, I recommend that you configure your encryptcookie middleware as follows:

```go
app.Use(encryptcookie.New(encryptcookie.Config{
    Key: "your-secret-here",
    Except: []string{
        "session_id",
        "csrf_",
    },
}))

### Further considerations

GoFiber middleware, by design, may not allow for a single secure cookie middleware that interoperates seamlessly with other middleware. It would require two middleware handlers: the first running before other middleware, decrypting incoming cookies, and a second running after other middleware, encrypting outgoing cookies.

The middleware provided by GoFiber does not seem to benefit from encrypting cookies due to its use of simple tokens, typically UUIDv4.

For non-GoFiber middleware, they are likely designed generically enough not to rely on the secure cookie middleware. If real-world examples indicate otherwise, I'd be happy to review and discuss.

### Recommendations

I am recommending that we update the secure cookie middleware documentation to include the session cookie and any a note about other middleware cookies as well.

**Comment by sixcolors** [comment]
@rngallen Here's a working example. Be aware that middleware order matters. Also, if you use `Key: encryptcookie.GenerateKey()` it will fail between app restarts.

Replace the key in the example with your secret key:

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/csrf"
	"github.com/gofiber/fiber/v2/middleware/encryptcookie"
	"github.com/gofiber/fiber/v2/middleware/session"
)

func main() {
	app := fiber.New()

	// Example: Encryptcookie middleware
	app.Use(encryptcookie.New(encryptcookie.Config{
		Key: "t+A2pNQ+GM117Uj7AhaHq/BwjWzZwBT9crgOSY6eWjA=",
	}))

	sessionStore := session.New(session.Config{})

	// Example: CSRF middleware
	app.Use(csrf.New(csrf.Config{
		KeyLookup:  "form:csrfToken",
		Session:    sessionStore,
		ContextKey: "csrfToken",
	}))

	// Route handler
	app.Get("/", func(c *fiber.Ctx) error {
		// html page with a form that posts to /test
		// inline javascript that reads the csrf token from the cookie and adds it to the form
		csrfToken := c.Locals("csrfToken")
		page := `
		<html>
			
			<body>
				<form action="/" method="POST">
					<input type="text" name="test" />
					<input type="submit" value="Submit" />
					<input type="hidden" name="csrfToken" value="` + csrfToken.(string) + `" />
					</form>
						</body>
						</html>
			`
		c.Type("html")
		return c.SendString(page)
	})

	app.Post("/", func(c *fiber.Ctx) error {
		csrfToken := c.Locals("csrfToken")
		page := `
		<html>
			
			<body>
				<p>You submitted: ` + c.FormValue("test") + `</p>
				<form action="/" method="POST">
					<input type="text" name="test" />
					<input type="submit" value="Submit" />
					<input type="hidden" name="csrfToken" value="` + csrfToken.(string) + `" />
					</form>
						</body>
						</html>
			`
		c.Type("html")
		return c.SendString(page)
	})

	// Listen on port 3000
	err := app.Listen(":3000")
	if err != nil {
		fmt.Println("Error:", err)
	}
}
```

**Comment by sixcolors** [comment]
@rngallen the encryptcookie middleware exempts the csrf token by default and that is necessary if reading the token from the cookie in the front end/client. If however you are using templates or otherwise including the csrf token in the html as above, then you can also encrypt the csrf cookie by using this config:

```go
	app.Use(encryptcookie.New(encryptcookie.Config{
		Key: "t+A2pNQ+GM117Uj7AhaHq/BwjWzZwBT9crgOSY6eWjA=",
		Except: []string{
		},
	}))
```

**Comment by rngallen** [comment]
Thanks but after working around I have discovered the followings 

1. I use `sess.Save()` on  my middleware 
```func AuthMiddleware(c *fiber.Ctx) error {
	sess, err := Store.Get(c)
	if err != nil {
		return c.Status(fiber.StatusUnauthorized).JSON(response.UnAuthorized(""))
	}
	if sess.Get(AUTH_KEY) == nil {
		return c.Status(fiber.StatusUnauthorized).JSON(response.UnAuthorized(""))
	}
	// Add user to the next handle
	c.Locals("userUid", sess.Get(USER_UID))
	c.Locals("superUser", sess.Get(SUPER_USER))
	c.Locals("sub", sess.Get(SUB))

	// Update user session expiration time
	// Uncomment this to enable coockie to be updated on each request
	// if err := sess.Save(); err != nil {
	// 	return err
	// }
	return c.Next()
}
```
  session was keep updating on every request. And because am using js(next js) on frontend I have to save this cookie(s) on every request, i think it's not a proper way. On top of that session max-age/expires keep extended on each request.
2.  Even if I comment `sess.Save()` but in csrf middleware Session uses Store instead of nil (default) it keep updating session id on every request.
3. if I set `Session:nil` on csrf middleware and comment `sess.Save()` session id will not updated on each request. But as per documentation csrf will be effective if it used with session(Store).

Is it the best practice to keep updating session on each request?
What are the drawbacks(security) if I use session but csrf will not use store? as per point3
