### ISSUE TITLE
The compiled package is too big, isn't it

### ISSUE THREAD

**Issue by iaping** [gofiber/fiber#2747]
### Question Description

The volume of the compiled package is also too large. Compared with gin, is the method wrong?

### Code Snippet (optional)

```go
go build -trimpath -ldflags '-w -s'
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by nickajacks1** [comment]
What kinds of sizes are you seeing? In a basic hello world application, I get a smaller size for fiber when compared to gin

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

// func main() {
// 	app := gin.Default()
// 	app.GET("/", func(ctx *gin.Context) {
// 		ctx.String(200, "Hello...")
// 	})
// 	app.Run(":3000")
// }

func main() {
	app := fiber.New()
	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello...")
	})
	app.Listen(":3000")
}
```

gin = 6.8 MB
fiber = 6.2 MB

**Comment by iaping** [comment]
I don't know what happened. Look at my dependency package, 50M after compilation
<img width="821" alt="tobig" src="https://github.com/gofiber/fiber/assets/15192203/dc19b9c3-0cda-4393-9f5f-a475ae60dfe0">
<img width="539" alt="tobig2" src="https://github.com/gofiber/fiber/assets/15192203/c9a3e85f-efb0-45b8-a0bf-8d25c426a363">

**Comment by iaping** [comment]
I see, if you don't use github.com/bytedance/sonic, compiled only 33 m, I have to check which packages

**Comment by ReneWerner87** [comment]
as already mentioned, it should be due to the many additional packages in your go mod file
if you can't identify any large packages there, i would suggest you delete the vendor folder and the go mod cache and fetch the dependencies again

if you have any further questions on the subject, simply reopen or continue posting
