### ISSUE TITLE
🐛 [Bug]: Middleware Rate Limiter Not Work as expected if Header Value Using IP

### ISSUE THREAD

**Issue by afifurrohman-id** [gofiber/fiber#2756]
### Bug Description

If i use ip value like `192.168.10.1` and using again `192.168.10.2` just different the rest octect it will fail, i also testing manually using two devices(Mobile, PC) with different Internet providers and still same.

But if i using other value like key1 and using key2 it work

### How to Reproduce

1. Create test project
```sh
mkdir fiber-test-limit
```
2. Go to project directory
```sh
cd fiber-test-limit
```
3. Initialize Go Module
```
go mod init fiber-test-limit
```
4. Create `main.go`
```go
// main.go
package main

import (
        "github.com/gofiber/fiber/v2"
        "github.com/gofiber/fiber/v2/log"
        "github.com/gofiber/fiber/v2/middleware/limiter"
)

const maxLimit = 2

func setupApp() *fiber.App {
        app := fiber.New()

        app.Get("/hello", limiter.New(limiter.Config{
                Max: maxLimit,
                KeyGenerator: func(ctx *fiber.Ctx) string {
                        if ctx.Get("Limit-Key") != "" {
                                log.Info(ctx.Get("Limit-Key"))
                                return ctx.Get("Limit-Key")
                        }

                        return ctx.IP()
                },
        }), func(ctx *fiber.Ctx) error {
                return nil
        })

        return app
}
```
5. Create `main_test.go`
```go
// main_test.go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/log"
	"net/http/httptest"
	"testing"
)

func TestLimit(test *testing.T) {
	app := setupApp()

	req := httptest.NewRequest(fiber.MethodGet, "/hello", nil)

	testsTable := []struct{
		Name string
		Value string
	} {
		{
			Name: "TestKey1",
			Value: "1.1.1.1",
		},
		{
			Name: "TestKey2",
			Value: "1.1.1.2",
		},
	}

	for _, tt := range testsTable {
		test.Run(tt.Name, func(test *testing.T) {
		req.Header.Set("Limit-Key", tt.Value)

		for i := 0; i <= maxLimit; i++ {
			res, err := app.Test(req, 1500*10)
			if err != nil {
				log.Error(err)
			}

			if i < maxLimit {

				if res.StatusCode != fiber.StatusOK {
					test.Fatalf("Unexpected Status Code want: %d, But Got: %d", fiber.StatusOK, res.StatusCode)
				}
			} else {
				if res.StatusCode != fiber.StatusTooManyRequests {
					test.Fatalf("Unexpected Status Code want: %d, But Got: %d", fiber.StatusTooManyRequests, res.StatusCode)
				}
			}

		}
	})

	}
}
```
6. Do Test
```sh
go test -v
```
8. See
```diff
=== RUN   TestLimit
=== RUN   TestLimit/TestKey1
2023/12/08 17:27:37.644043 main.go:18: [Info] 1.1.1.1
2023/12/08 17:27:37.644593 main.go:18: [Info] 1.1.1.1
2023/12/08 17:27:37.644593 main.go:18: [Info] 1.1.1.1
=== RUN   TestLimit/TestKey2
2023/12/08 17:27:37.645147 main.go:18: [Info] 1.1.1.2
    main_test.go:42: Unexpected Status Code want: 200, But Got: 429
--- FAIL: TestLimit (0.00s)
    --- PASS: TestLimit/TestKey1 (0.00s)
    --- FAIL: TestLimit/TestKey2 (0.00s)
FAIL
exit status 1
FAIL    fiber-rate-limit        0.577s
```

### Expected Behavior

Test Should be PASS, because value is different

### Fiber Version

2.51.0

### Code Snippet (optional)

```go
package main

import (
        "github.com/gofiber/fiber/v2"
        "github.com/gofiber/fiber/v2/log"
        "github.com/gofiber/fiber/v2/middleware/limiter"
)

const maxLimit = 2

func setupApp() *fiber.App {
        app := fiber.New()

        app.Get("/hello", limiter.New(limiter.Config{
                Max: maxLimit,
                KeyGenerator: func(ctx *fiber.Ctx) string {
                        if ctx.Get("Limit-Key") != "" {
                                log.Info(ctx.Get("Limit-Key"))
                                return ctx.Get("Limit-Key")
                        }

                        return ctx.IP()
                },
        }), func(ctx *fiber.Ctx) error {
                return nil
        })

        return app
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
don't forget to make a copy, otherwise in the memory storage, which is the default storage, there is a reference of the item to the other items coming from other requests
 

![image](https://github.com/gofiber/fiber/assets/7063188/25619072-c45e-49dc-ae50-e832695062ba)
![image](https://github.com/gofiber/fiber/assets/7063188/37c14dcf-a0f9-4987-9502-c6399e5e6731)
https://docs.gofiber.io/next/api/ctx#get

fixed with 
![image](https://github.com/gofiber/fiber/assets/7063188/f65c4424-ebcf-49e5-bd29-4ece0e8898fe)
![image](https://github.com/gofiber/fiber/assets/7063188/6f6ebed5-1a8d-40fb-b02a-33e3d82aef2c)

**Comment by afifurrohman-id** [comment]
> don't forget to make a copy, otherwise in the memory storage, which is the default storage, there is a reference of the item to the other items coming from other requests
> 
> ![image](https://private-user-images.githubusercontent.com/7063188/289049014-25619072-c45e-49dc-ae50-e832695062ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzQyOTksIm5iZiI6MTcwMjAzMzk5OSwicGF0aCI6Ii83MDYzMTg4LzI4OTA0OTAxNC0yNTYxOTA3Mi1jNDVlLTQ5ZGMtYWU1MC1lODMyNjk1MDYyYmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMTExMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDE1ZjQyYTVkZmU0MjVkMDIyY2M2OTZmZjM2MTgxMGI3MGNhNjU5MTUzNWUxZDgxODc3YWMwNTIwNjBmZjFiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GxDnU50DbVkSfOW660FJ0LEPMthLZG1kLg_ZnzYl-Gk) ![image](https://private-user-images.githubusercontent.com/7063188/289049444-37c14dcf-a0f9-4987-9502-c6399e5e6731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzQyOTksIm5iZiI6MTcwMjAzMzk5OSwicGF0aCI6Ii83MDYzMTg4LzI4OTA0OTQ0NC0zN2MxNGRjZi1hMGY5LTQ5ODctOTUwMi1jNjM5OWU1ZTY3MzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMTExMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZkMzRhNGY4MTc3MDA2ZjI2NTY1MGU0MDAzMzY3YTIzNTU5YWUxMDg4ZmY2MTEwMGRiNjA5YzhlYWE5NGY1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YUwPqydVqyhHBeWP4tGgKjzqaPzjAErdkdrk_FQvp-o) https://docs.gofiber.io/next/api/ctx#get
> 
> fixed with ![image](https://private-user-images.githubusercontent.com/7063188/289049296-f65c4424-ebcf-49e5-bd29-4ece0e8898fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzQyOTksIm5iZiI6MTcwMjAzMzk5OSwicGF0aCI6Ii83MDYzMTg4LzI4OTA0OTI5Ni1mNjVjNDQyNC1lYmNmLTQ5ZTUtYmQyOS00ZWNlMGU4ODk4ZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMTExMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODMwNDViNWIzMDVmODdhMzNkMmE4Y2FkNDhlYzdkNjRjYjA0MjkzZDc1ODcyODdmM2FjM2Q1YTZmMWJmNmE2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AHVtHFke2Jin4JiH9cxxjaSUcoCPqWYnYR53swCfiNg) ![image](https://private-user-images.githubusercontent.com/7063188/289049329-6f6ebed5-1a8d-40fb-b02a-33e3d82aef2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzQyOTksIm5iZiI6MTcwMjAzMzk5OSwicGF0aCI6Ii83MDYzMTg4LzI4OTA0OTMyOS02ZjZlYmVkNS0xYThkLTQwZmItYjAyYS0zM2UzZDgyYWVmMmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDhUMTExMzE5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE4MmQ3ZDcwYzZkZjk1MmYyZmExOWNmNWY3OWM4MGU4YWZmOWUyNWEzMGM0Nzc4M2JhYzY0NmY0NTUxNjUwMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3sUGVva5td9VV8mTKlhV1Y7nr-CrJkr_XLRkEvCOLSc)
> 
> btw `ctx.IP` is a copy by default

Thanks, now understand immutability as docs say.
