### ISSUE TITLE
🔥 Auto Swagger Api Documantion

### ISSUE THREAD

**Issue by mehmetuken** [gofiber/fiber#276]
**Describe the solution you'd like**
New middleware for auto generate swagger endpoint.

**Describe alternatives you've considered**
https://github.com/swaggo/swag
https://github.com/swaggo/echo-swagger
https://github.com/swaggo/gin-swagger

**Comment by Fenny** [comment]
Thanks for your suggestion @mehmetuken, personally I don't have experience with swagger. But I will ask around in our Telegram group if someone can take a look at it.

[Join Fiber on Telegram](https://t.me/gofiber)

**Comment by Fenny** [comment]
@mehmetuken @arsmn is working on it -> https://github.com/arsmn/fiber-swagger
