### ISSUE TITLE
🤗 [Question]: Can fiber support reverse url like django?

### ISSUE THREAD

**Issue by feeops** [gofiber/fiber#2768]
### Question Description

Can fiber support reverse url like django?

https://docs.djangoproject.com/en/5.0/ref/urlresolvers/

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by AlfredoRamos** [comment]
Is [`GetRouteURL()`](https://docs.gofiber.io/api/ctx#getrouteurl) what you are looking for?

**Comment by feeops** [comment]
> Thanks for opening your first issue here! 🎉 Be sure to follow the issue template! If you need help or want to chat with us, join us on Discord https://gofiber.io/discord

yes
