### ISSUE TITLE
💡 Template / View / Render enhancement

### ISSUE THREAD

**Issue by pharrisee** [gofiber/fiber#277]
Loving fiber so far, but I have one issue with the way that templating is done.  

The current templating functionality is passing the raw contents of the template. 

I generally use https://github.com/unrolled/render for template management, and it works really well in other Go web frameworks/routers.  However it requires the template name and not the contents to be passed to it.

I wrote a middleware to the templating interface (as the others already implemented do), but obviously it's not worked for the reason specified above.

Is there any way to get the templating engine to pass the name of the template rather than it's contents?

**Comment by Fenny** [comment]
Hey @pharrisee, our templating middleware was a `quick-fix` solution. You could play with the [template](https://github.com/gofiber/template) repo and submit a PR.

Or leave a code suggestion regarding our template middleware here.

**Comment by Fenny** [comment]
@pharrisee We are going to change the way we render templates in Fiber. I opened an discussion that relates to multiple issues including this one, if you have any ideas or feedback please post them here https://github.com/gofiber/fiber/issues/331
