### ISSUE TITLE
Why isn't c.Params(param) capturing the route parameter in a middle handler?

### ISSUE THREAD

**Issue by darienmiller88** [gofiber/fiber#2774]
### Question Description

I'm trying to read the value of a route parameter in a middleware, but the function to return that value return `""` instead of the value of route parameter. It works perfectly fine in the route handler, but not the middleware attached to it. Is there something I'm missing?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

func main() {
  app := fiber.New()

  app.Use(func(c *fiber.Ctx) error{
     fmt.Println("param:", c.Params("username")) // Returns ""
     return c.Next()
  }).Get("/:username", func(c *fiber.Ctx) error {
     fmt.Println("param:", c.Params("username")) // Returns value here

     return c.Send([]byte("Hello"))
  })

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Yes, that's right, that's how it should work
You can also define the parameter in the "Use", then you can use it
Otherwise, each route is separate from each other and cannot share information with the others

**Comment by darienmiller88** [comment]
How should I mount a middleware on a particular to parse the request params before it hit the handler?

**Comment by ReneWerner87** [comment]
```go
app.Use("/:param", middlewareCode)
```

**Comment by darienmiller88** [comment]
Okay, that works perfectly! I also realized that I can do it like this:

`app.Post("/", middlewareHandler,  handler)`

Is this also a fine way to use middlewares?

**Comment by ReneWerner87** [comment]
Yes sure
