### ISSUE TITLE
🤗 [Question]: best way to check if a path is registered in the app

### ISSUE THREAD

**Issue by lang-devbr** [gofiber/fiber#2775]
### Question Description

Is there a way to identify in middleware whether the request path is registered in the app? basically I want to identify if it is a 404 in my app within my middleware.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by nickajacks1** [comment]
If this is an option for you, you can try having your middleware survive the processing of routes:

```go
func main() {
	app := fiber.New()

	app.Use("/", func(c fiber.Ctx) error {
		// Run the main handlers...
		err := c.Next()
		if err != nil {

			//  your stuff here...

			return c.Status(404).SendString(err.Error())
		}
		return nil
	})
	app.Get("/stuff", func(c fiber.Ctx) error {
		return c.SendString("Hello!")
	})
	log.Fatal(app.Listen(":3000"))
}
```
It's also possible to prod around and look at the raw Route objects
https://docs.gofiber.io/api/app#getroutes
https://docs.gofiber.io/api/app#stack
But I'm not sure how reliable these would be when you have wildcards.

There might be other ways to do this as well that I'm not aware of, so I'll let others pitch in if neither of these work for you

**Comment by lang-devbr** [comment]
Nice, it was exactly what I needed! Thx @nickajacks1
