### ISSUE TITLE
🤗 [Question]: app.OnShutdown not printing to stdout

### ISSUE THREAD

**Issue by mhornbacher** [gofiber/fiber#2778]
### Question Description

I have a small service that hooks into OpenTelementary and a few other resources that need to be sent a shutdown signal once the app shutsdown. The `app.Hooks().OnShutdown()` hook looks right for this but I cannot seem to get it to trigger, either via Ctrl-C or via `app.Shutdown()`

The following is a minimal code sample to reproduce this issue. When closing the software via Ctrl-C (or any SIGINT) the OnShutdown hook does not output to stdout

What am I doing wrong here in terms of configuring on shutdown process.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"
import "fmt"
import "os"
import "os/signal"

func main() {
  app := fiber.New()

  // 🎣 hooks
  app.Hooks().OnShutdown(func() error {
    fmt.Println("🔭 Shutting down Open Telemetry")
    return nil
  })

  c := make(chan os.Signal, 1)
  signal.Notify(c, os.Interrupt)

  go func() {
    _ = <-c
    _ = app.Shutdown()
  }()
  
  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by nickajacks1** [comment]
There are two things that are likely happening.
1. The program is exiting before app.Shutdown() is finished.  You should make sure that the main goroutine waits for the shutdown to complete before exiting.  This can be done using a channel to notify the main goroutine or by moving the signal handling to the main goroutine itself.
2. log.Fatal is killing the program before the shutdown completes.  `app.Listen` will return when `app.Shutdown` is called, causing log.Fatal to trigger.  Changing this to `log.Println` might superficially resolve the situation, but please make sure you handle the cases where `app.Listen` exits unexpectedly (e.g. `bind: address already in use` type errors)!

Here is a modified version of the original code:

```go
package main

import (
	"fmt"
	"log"
	"os"
	"os/signal"

	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()

	// 🎣 hooks
	app.Hooks().OnShutdown(func() error {
		fmt.Println("🔭 Shutting down Open Telemetry")
		return nil
	})

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt)

	go func() { log.Println(app.Listen(":3000")) }()
	<-c
	err := app.Shutdown()
	if err != nil {
		log.Fatal(err)
	}
}
```
If you go with something like the above, please also be sure to add better error handling and cleanup for `app.Listen`!!

**Comment by mhornbacher** [comment]
Interesting, why would the `app.Listen` go inside of a go-routine?

I applied the code as you suggested (with some slightly increased error handling) and now the hook is running twice 😆😢

**Comment by nickajacks1** [comment]
You can keep app.listen in the main goroutine as long as you wait for the shutdown to finish.
You can make the shutdown happen just once using something like [sync.Once](https://pkg.go.dev/sync#Once), or if you're using go 1.21, [sync.OnceFunc](https://pkg.go.dev/sync#OnceFunc)

**Comment by gaby** [comment]
@mhornbacher There's multiple ways of doing it, but yes. It needs to run in a goroutine.

The biggest problem is having that `log.Fatal()` which will cause the program to panic. Try running your code without the fatal, does the output show?

**Comment by mhornbacher** [comment]
I think I get it. Thank you so much for clarifying and explaining.

Seems a bit unclear from the documentation that this is all required for `onShutdown` hooks to run but is simple enough to figure out.

And the reason it was running twice is because I was accidentally registering it twice 😞
