### ISSUE TITLE
🤗 [Question]: Dynamic Session ID Generation

### ISSUE THREAD

**Issue by gandaldf** [gofiber/fiber#2786]
### Question Description

Hello everyone, I have a question regarding the generation of IDs in session middleware.
I understand there's a function to customize the generator, `KeyGenerator func() string`, which is a predefined function during configuration and is particularly useful for generating completely random keys.
However, my requirement is to create an ID where the initial part varies based on the user logging in, such as `user_id:random_chars`, to enable later retrieval of all sessions assigned to that user.
Therefore, a method like `(s *Session) SetID(id string)` to be used before `session.Save()` would be very helpful.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by sixcolors** [comment]
Why store the information in the token itself instead of just keeping a reference in your database or cache?

**Comment by gandaldf** [comment]
Perhaps I didn't explain myself well, but yes, what I meant was indeed to store a server-side session reference in the form `user_id:random_chars`.
However, with the current `KeyGenerator function func() string`, I am unable to customize its operation for each new user login.

**Comment by sixcolors** [comment]
Currently this is not possible. But I was going to do v3 changes to session so I’ll keep this use case in mind. 

A solution for now could be to use a separate db or cache to store the session tokens with the users id as the key.

**Comment by gandaldf** [comment]
I think that to avoid modifying all the implementations of the gofiber/storage package by adding new functions, the only solution is to store session references under a key, possibly allowing the application to define it.
In this way, I could define keys like `sessions:user:userID` or `sessions:group:groupID` to store session IDs; this would also distribute the data across multiple keys without overloading a 'global' one.
Perhaps we could extend the session package by adding a 'Manager' type to integrate these features without causing breaking changes.
