### ISSUE TITLE
🤔 Possible for server streaming

### ISSUE THREAD

**Issue by WLun001** [gofiber/fiber#279]
**Question description**
Is it possible to perform Http/2 server streaming like the snippet below?
**Code snippet (optional)**
from Echo
```go
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo"
)

func request(c echo.Context) error {
	req := c.Request()
	format := "<pre><strong>Request Information</strong>\n\n<code>Protocol: %s\nHost: %s\nRemote Address: %s\nMethod: %s\nPath: %s\n</code></pre>"
	return c.HTML(http.StatusOK, fmt.Sprintf(format, req.Proto, req.Host, req.RemoteAddr, req.Method, req.URL.Path))
}

func stream(c echo.Context) error {
	res := c.Response()
	gone := res.CloseNotify()
	res.Header().Set(echo.HeaderContentType, echo.MIMETextHTMLCharsetUTF8)
	res.WriteHeader(http.StatusOK)
	ticker := time.NewTicker(1 * time.Second)
	defer ticker.Stop()

	fmt.Fprint(res, "<pre><strong>Clock Stream</strong>\n\n<code>")
	for {
		fmt.Fprintf(res, "%v\n", time.Now())
		res.Flush()
		select {
		case <-ticker.C:
		case <-gone:
			break
		}
	}
}

func main() {
	e := echo.New()
	e.GET("/request", request)
	e.GET("/stream", stream)
	e.Logger.Fatal(e.StartTLS(":1323", "cert.pem", "key.pem"))
}
```

**Comment by Fenny** [comment]
@WLun001 Fiber does not support http/2 see https://github.com/gofiber/fiber/issues/262#issuecomment-610353479

We run on fasthttp that waits for a handler to return before sending the response, something like `Flush()` is not possible.

**Comment by WLun001** [comment]
@Fenny actually what I wanted to achieve is realtime update on web. As far as I know currently only can do with websocket, (short/long) polling. Looking at http/2 streaming/server push solution

**Comment by thomasvvugt** [comment]
Hi @WLun001,
Thanks for your question. I would recommend implementing real-time updates on the web using Fiber's websocket middleware. See Fenny's comment on issue #262 about missing HTTP/2 support.
Thanks!
