### ISSUE TITLE
Feature request: Add docs for https://github.com/gofiber/fiber/pull/2796

### ISSUE THREAD

**Issue by Skyenought** [gofiber/fiber#2797]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Add docs for feat: https://github.com/gofiber/fiber/pull/2796

**Describe alternatives you've considered**

**Additional context**

Office docs repo: https://github.com/cloudwego/cloudwego.github.io

**Comment by gaby** [comment]
@Skyenought It's a golang change from 1.18 version. Given that Fiber v3 requires min 1.20 the change was done.

`any` is basically an alias for `interface{}`
