### ISSUE TITLE
🤔 Fiber object not found in versione 1.9.0

### ISSUE THREAD

**Issue by accyourate** [gofiber/fiber#281]
**Question description**

**Code snippet (optional)**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  // ..
}
```
I get a compile error "undefined: fiber.Fiber"

**Comment by koddr** [comment]
@accyourate hi! 

What's your Go version and OS?

**Comment by accyourate** [comment]
Go 1.14 with Mac OS Catalina.
I solved changing Fiber with App.
In version 1.8.x I was using *Fiber, but in 1.9.0 I need *App

**Comment by Fenny** [comment]
@accyourate this was a mistake in `v1.8.432` because of a missing test case that was up for several hours, this version has been removed and a test case has been added.
