### ISSUE TITLE
🧹 [Maintenance]: Update golangci-lint

### ISSUE THREAD

**Issue by nickajacks1** [gofiber/fiber#2816]
### Maintenance Task Description

As of writing, the latest version of golangci-lint is v1.55.2. This issue encompasses updating the github actions to use at least this version of golangci-lint along with updating the .golanci.yml config to enable or disable new rules and linters as agreed upon by the fiber team.

- [gosmopolitan](https://github.com/xen0n/gosmopolitan) checks for i18n usage, including time.Local
- [mirror](https://github.com/butuzov/mirror) checks for allocs in string/[]byte conversions
- [tagalign](https://github.com/4meepo/tagalign) checks for struct tag formatting
- [gochecksumtype](https://github.com/alecthomas/go-check-sumtype) checks for exhaustive type switches. Somewhat complex, check out the examples.
- [inamedparam](https://github.com/macabu/inamedparam) requires named params for interface functions (can exclude single param funcs)
- [perfsprint](https://github.com/catenacyber/perfsprint) checks faster alternatives to fmt.Sprintf
- [testifylint](https://github.com/Antonboom/testifylint) checks idiomatic testify usage
- [zerologlint](https://github.com/ykadowak/zerologlint) zerolog usage
- [sloglint](https://github.com/go-simpler/sloglint) slog usage
- [protogetter](https://github.com/ghostiam/protogetter) protobuf usage

In addition to the new linters, there are several new linter rules for existing linters, many of which raise errors in the current codebase. These will likely need to be inspected individually.

### Impact on the Project

Updating the linter benefits the project by keeping up with modern Go practices, maintaining code consistency, and reducing the probability of bugs and API issues.

### Checklist:

- [X] I have confirmed that this maintenance task is currently not being addressed.
- [X] I understand that this task will be evaluated by the maintainers and prioritized accordingly.
- [X] I am available to provide further information if needed.

**Comment by efectn** [comment]
We should add support for `fieldalignment` linter too.
