### ISSUE TITLE
🐛 [Bug]: `c.Bind.Query()` cannot parse data to struct correcttly with structTag.

### ISSUE THREAD

**Issue by qingchuwudi** [gofiber/fiber#2823]
### Bug Description

`c.Bind.Query()` cannot parse data to struct with `fiber/v3` when using structTag.

### How to Reproduce

server code:

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v3"
)

type Tt struct {
	K string `json:"k_1"`
	V string `json:"k_2"`
}

func queryBind(c fiber.Ctx) error {
	var _out Tt = Tt{}
	err := c.Bind().Query(&_out)
	if err != nil {
		return fmt.Errorf("paramBind error : %v", err)
	} else {
		fmt.Printf("paramBind : %v", _out)
	}
	return nil
}

func main() {
	appRoot := fiber.New()
	appRoot.Get("/", queryBind)
	appRoot.Listen(":9999")
}
```

parse failed:
```bash
curl --request GET \
  --url 'http://127.0.0.1:9999/?k_1=hello&k_2=world'
```

parse ok:
```bash
curl --request GET \
  --url 'http://127.0.0.1:9999/?k=hello&v=hello_world'
```

### Expected Behavior

Parsing data narmally when using structTag within http request.

### Fiber Version

v3.0.0-20240131065809-dde9da33e32a

### Code Snippet (optional)

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber/v3"
)

type Tt struct {
	K string `json:"k_1"`
	V string `json:"k_2"`
}

func queryBind(c fiber.Ctx) error {
	var _out Tt = Tt{}
	err := c.Bind().Query(&_out)
	if err != nil {
		return fmt.Errorf("paramBind error : %v", err)
	} else {
		fmt.Printf("paramBind : %v", _out)
	}
	return nil
}

func main() {
	appRoot := fiber.New()
	appRoot.Get("/", queryBind)
	appRoot.Listen(":9999")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by aliziyacevik** [comment]
Hey guys, I can offer my assistance with this one.

**Comment by Skyenought** [comment]
I don't think this is a bug, you should specify `query` tag
The search order of bind() is `query` -> var

```go
type Tt struct {
	K string `json:"k_1" query:"k_1"`
	V string `json:"k_2" query:"k_2"`
}
```
After that
```bash
curl --request GET \
  --url 'http://127.0.0.1:9999/?k_1=hello&k_2=hello_world'

    _______ __             
   / ____(_) /_  ___  _____
  / /_  / / __ \/ _ \/ ___/
 / __/ / / /_/ /  __/ /    
/_/   /_/_.___/\___/_/     v3.0.0-beta.1
--------------------------------------------------
INFO Server started on http://127.0.0.1:9999 (bound on host 0.0.0.0 and port 9999)
INFO Total handlers count: 1
INFO Prefork: Disabled
INFO PID: 82917
INFO Total process count: 1
paramBind : {hello hello_world}

```

**Comment by qingchuwudi** [comment]
> @qingchuwudi I don't think this is a bug, you should specify `query` tag. The search order of bind() is `query` -> var, The search order for bind() is `query` -> var, which is why `k=hello&v=hello_world` works.
> 
> ```go
> type Tt struct {
> 	K string `json:"k_1" query:"k_1"`
> 	V string `json:"k_2" query:"k_2"`
> }
> ```
> 
> After that
> 
> ```shell
> curl --request GET \
>   --url 'http://127.0.0.1:9999/?k_1=hello&k_2=hello_world'
> 
>     _______ __             
>    / ____(_) /_  ___  _____
>   / /_  / / __ \/ _ \/ ___/
>  / __/ / / /_/ /  __/ /    
> /_/   /_/_.___/\___/_/     v3.0.0-beta.1
> --------------------------------------------------
> INFO Server started on http://127.0.0.1:9999 (bound on host 0.0.0.0 and port 9999)
> INFO Total handlers count: 1
> INFO Prefork: Disabled
> INFO PID: 82917
> INFO Total process count: 1
> paramBind : {hello hello_world}
> ```

Thanks.
