### ISSUE TITLE
🤗 [Question]: How to add space at the end of header value

### ISSUE THREAD

**Issue by pitagoras530** [gofiber/fiber#2828]
### Question Description

"GET / HTTP/1.1"
"Host: 127.0.0.1"
"Test: testvalue     "

It seems that GoFiber is removing the spaces at the end of header values. Is there a way to disable the trimming of header values?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v3"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by nickajacks1** [comment]
Fasthttp, the underlying http library that fiber uses, is the one that's stripping the value.
RFC-9110 does not permit spaces at the end of a header value:
https://www.rfc-editor.org/rfc/rfc9110#name-field-values
Note that field-vchar is any visible US-ASCII character, meaning space is excluded.
One solution is to quote any value that ends in a space: `Test: "testvalue "`
Please feel free to reopen if you have further questions.

**Comment by pitagoras530** [comment]
> Fasthttp, the underlying http library that fiber uses, is the one that's stripping the value. RFC-9110 does not permit spaces at the end of a header value: https://www.rfc-editor.org/rfc/rfc9110#name-field-values Note that field-vchar is any visible US-ASCII character, meaning space is excluded. One solution is to quote any value that ends in a space: `Test: "testvalue "` Please feel free to reopen if you have further questions.

Hi, i have solved this issue by using ```ctx.Request().Header.RawHeaders()```
