### ISSUE TITLE
🤗 [Question]: Is there any way to use existing storage instead of creating a new one when app restarts?

### ISSUE THREAD

**Issue by VivekAlhat** [gofiber/fiber#2829]
### Question Description

Hi, Is there any way to reuse the existing storage in limiter middleware?
I have deployed my application on Fly.io and it has a setting to auto-stop machines when there are no requests and auto-restart when a new request is made to the server. 
I am using limiter middleware and bbolt db to store data but every time the machine is restarted it creates a new bbolt db storage. 
Due to this whenever I hit the rate limit and the machine goes idle, then when the machine auto restarts still I can make requests to the server as it creates a new storage.
Is there any way where we can use the existing storage?

### Code Snippet (optional)

```go
storage := bbolt.New() // use existing if available or create a new one

app.Use(limiter.New(limiter.Config {
    Max: 5,
    Expiration: 60 * time.Minute,
    LimiterMiddleware: limiter.SlidingWindow {},
    Storage: storage,
}))
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@VivekAlhat This is actually a Fly.io issue not a Fiber one. By default bbolt driver creates `fiber.db` in your current working directory. If this file exists, it will be reused with the last data on it.

By default Fly.io uses ephemeral deployments, so your data does not persist across deployments. More information here: https://fly.io/docs/database-storage-guides/#fly-volumes-disk-storage

To solve your issue you have to use a Fly Volume with your deployment, more info here https://fly.io/docs/apps/volume-storage/

**Comment by VivekAlhat** [comment]
Thank you for clarifying, I appreciate the explanation. I'll take a look at the documentation you shared regarding Fly Volumes and disk storage to address the problem. Thanks again for pointing me in the right direction!
