### ISSUE TITLE
🐛 [Bug]: Prefork Option removed from fiber.Config

### ISSUE THREAD

**Issue by darkness-a47** [gofiber/fiber#2834]
### Bug Description

today i tried to use fiber v3 and i noticed the Prefork option isn't available anymore in fiber.Config
the Option removed between commit 94acde8fe5dd2b793ab07924cd9d0ee728eb753c and 6ea4d81331edb14052e278237e8e3b85c4f534d6

i don't know it is intended behavior or not

### How to Reproduce

1. Create a new fiber v3 project
2. try to enable prefork option
3. prefork isn't available on fiber.Config

### Expected Behavior

be able to enable the prefork option in fiber.Config

### Fiber Version

v3-beta1

### Code Snippet (optional)

```go
package main

import (
	"github.com/gofiber/fiber/v3"
)

func main() {
    app := fiber.New(fiber.Config{
        Prefork: true,
    })

    app.Get("/", func(c *fiber.Ctx) error {
        return c.SendString("Hello!")
    })

    app.Listen(":3000")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
@efectn can you confirm this?

**Comment by ReneWerner87** [comment]
its now in the ListenConfig
https://github.com/gofiber/fiber/blob/9b0a99ba27fcae1b841ecd28139785b6e230c59b/listen.go#L95

when you use the Listen function

**Comment by ReneWerner87** [comment]
we will refresh the documentation soon
