### ISSUE TITLE
🤗 [Question]: Grouping by Middleware

### ISSUE THREAD

**Issue by adiwahyudi** [gofiber/fiber#2843]
### Question Description

Hello, I'm encountering an issue with route setup in Go using Fiber.
```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/basicauth"
)

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})
	basicAuth1 := basicauth.New(basicauth.Config{
		Users: map[string]string{
			"go": "123",
		},
		Unauthorized: func(ctx *fiber.Ctx) error {
			return fiber.NewError(fiber.StatusForbidden, "Error BasicAuth V1")
		},
	})
	basicAuth2 := basicauth.New(basicauth.Config{
		Users: map[string]string{
			"go": "321",
		},
		Unauthorized: func(ctx *fiber.Ctx) error {
			return fiber.NewError(fiber.StatusForbidden, "Error BasicAuth V2")
		},
	})
	base := app.Group("/api")
	v1 := base.Group("/", basicAuth1)
	v1.Get("/v1", func(ctx *fiber.Ctx) error {
		return ctx.SendString("a from v1")
	})

	v2 := base.Group("/", basicAuth2)
	v2.Get("/v2", func(ctx *fiber.Ctx) error {
		return ctx.SendString("a from v2")
	})

	app.Listen(":3000")
}

```

When I attempt to access the `api/v2` endpoint, I receive an error from the basicAuth1 middleware.
This middleware should only be applied to a different group and not affect `api/v2`.
I just want grouping path by middleware.

![api/v1 with right auth](https://github.com/gofiber/fiber/assets/24860132/ff26481c-1834-493b-9e89-8f9f71c8460b)

![api/v2 with right auth](https://github.com/gofiber/fiber/assets/24860132/62e23fd6-2cda-475d-a19d-942f390a442b)

### Code Snippet (optional)

```go
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/issues/2406#issuecomment-1498075776

https://docs.gofiber.io/guide/grouping

Pls check the info box
![Screenshot_2024-02-10-13-51-29-73_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/gofiber/fiber/assets/7063188/82894a7b-6a3f-462b-9f99-b92ea5a92898)

**Comment by adiwahyudi** [comment]
ah okay got it, thanks @ReneWerner87

**Comment by nexovec** [comment]
Is there really no way to only have group scoped middleware? This approach requires me to make the route longer for every nested group, which results in some pretty long route names. I'm sometimes just inlining the middlewares to avoid this, but that's really not good.
