### ISSUE TITLE
🤗 [Question]: How to handle multipart range request?

### ISSUE THREAD

**Issue by sergey-ust** [gofiber/fiber#2844]
### Question Description

I'm struggling with responding on such multipart range requests like in [mozila.org example]( https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests#multipart_ranges)

Maybe someone could give me a clue how to construct a response like that (mozila.org example):
```
HTTP/1.1 206 Partial Content
Content-Type: multipart/byteranges; boundary=3d6b6a416f9b5
Content-Length: 282

--3d6b6a416f9b5
Content-Type: text/html
Content-Range: bytes 0-50/1270

<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Example Do
--3d6b6a416f9b5
Content-Type: text/html
Content-Range: bytes 100-150/1270

eta http-equiv="Content-type" content="text/html; c
--3d6b6a416f9b5--
````

 
Thank you in advance

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
what do you want to achieve? do you want to send a file? 

https://docs.gofiber.io/api/middleware/filesystem#sendfile supports partial content transfer

**Comment by sergey-ust** [comment]
Firstly, @ReneWerner87 thanks a lot for your answer!

I want to return some file parts in the response and unfortunately I don't have a real file, only `io.Reader` interface. I can obtain such  `io.Reader` object from my storage by call something like: `payloadReader := storage.StartDownload(offset, bytesCnt)`. And I have found a way to fill the request body with interfaces and without additional copying:
```
	io.Copy(ctx.Response().BodyWriter(), payloadReader)
```

How can I see, it's possible to construct the multipart range response with manually adding into the response body the following parts:

1.  a boundary (=separator) 
2.  part headers
3.  data (copying with interfaces)

But maybe there are some corresponding methods, aren't they?

**Comment by ReneWerner87** [comment]
thats a little bit harder

you have to follow the following approach
https://github.com/valyala/fasthttp/blob/bce576699a322ab33b618773a4456a25e602682d/http_test.go#L1540C2-L1540C10

**Comment by sergey-ust** [comment]
thanks a lot!
