### ISSUE TITLE
🤗 [Question]: Validate request params

### ISSUE THREAD

**Issue by meldumm** [gofiber/fiber#2873]
### Question Description

Request:
```
{
    "tokens": [{
        "address": "test",
        "decimals": "1"
    }]
}
```

If a user sends a request with a string instead of an int for decimals, the following error will be returned:

```
runtime error: invalid memory address or nil pointer dereference
```

Is there a way to validate the request body and return a proper error message to the user?

### Code Snippet (optional)

```go
type Token struct {
	Address  string `json:"address"`
	Decimals int    `json:"decimals"`
}

type tokenAddRequestParams struct {
	Tokens        []Token `json:"tokens"`
}

func AddTokens(c *fiber.Ctx) error {
	var req tokenAddRequestParams
	if err := c.BodyParser(&req); err != nil {
		return nil, c.Status(fiber.StatusBadRequest).JSON(fiber.Map{"error": "Cannot parse JSON"})
	}
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by meldumm** [comment]
This is a question for V2

**Comment by sixcolors** [comment]
Can you provide a minimal runnable example?

**Comment by meldumm** [comment]
The issue was identified in a different section of the code. Thank you for your assistance
