### ISSUE TITLE
🧹 [v3 Maintenance]: Update docs to reflect fiber.Ctx struct to interface change

### ISSUE THREAD

**Issue by grivera64** [gofiber/fiber#2879]
### Maintenance Task Description

As v3 introduces a [new interface](https://github.com/gofiber/fiber/blob/main/ctx_interface.go#L20) for `fiber.Ctx` in preference over the [current struct](https://github.com/gofiber/fiber/blob/v2/ctx.go#L82) `*fiber.Ctx` in v2, the documentation should also reflect this change. Currently, some v3 docs still refer to `*fiber.Ctx`.

For example:
- [/docs/api/ctx.md](https://github.com/gofiber/fiber/blob/main/docs/api/ctx.md?plain=1#L20) in lines 20-23
- [/docs/api/app.md](https://github.com/gofiber/fiber/blob/main/docs/api/app.md?plain=1#L96) in line 96

This would involve replacing all uses of the `*fiber.Ctx` struct to instead use the `fiber.Ctx` interface in the `/docs/` folder.

### Impact on the Project

This update will help people in the v2 -> v3 migration process when the full release is ready. This also helps avoid confusion for early testers who are using the docs as a reference point.

There's a potential risk that we could be doing this too early, as there may be more complicated changes besides `*fiber.Ctx` -> `fiber.Ctx` in certain v3 components of Fiber. This could cause requiring double the work, when all of the changes can be made at once in a single PR.

### Additional Context (optional)

This serves as a smaller issue to split the progress of the following larger issues' goals:

#2712 
#2713 

### Checklist:

- [X] I have confirmed that this maintenance task is currently not being addressed.
- [X] I understand that this task will be evaluated by the maintainers and prioritized accordingly.
- [X] I am available to provide further information if needed.

**Comment by gaby** [comment]
Fxied via #2880
