### ISSUE TITLE
💡 Add Pull Request templates with code reviews

### ISSUE THREAD

**Issue by renanbastos93** [gofiber/fiber#289]
According to talk us in Telegram, we need to implement a new process to define one flow easily to merge new features/fixes etc on Fiber.

PR == `pull request`

Suggestion:
- Title in PR using prefix (fix, feat, refactor, chore)
- Description with details
- minimal 1 approve in members from the organization to merge PR

e.g.

PR1: (CHORE)
```
chore: Add workflow lint

Added a new workflow to validate linter.
```

PR2: (REFACTOR)

```
refactor: Rename file x to y

Renamed file X to Y because one definition xyz...
```

P3: (FEAT)

```
feat: Add parameter options in URLs

Added a new options to use in your endpoint to parameters optional
currently URL: /api/logs/:opt?
we can use it
 > /api/logs
 > /api/logs/error

etc...
```

PR4: (FIX)

```
fix: Not compliance rule x

Improved a business rule because it not compliace with RFC...
```

**Comment by Fenny** [comment]
@renanbastos93 we could start with adding PR's templates like we do with ISSUE's 
https://github.com/gofiber/fiber/tree/master/.github/ISSUE_TEMPLATE

Feature, Refactor, Fix

**Comment by thomasvvugt** [comment]
Also, here is a nice guideline with PR template examples.
https://github.com/stevemao/github-issue-templates

Keep in mind; We just need more emojis! 😎

Let me know if you need any help!

**Comment by thomasvvugt** [comment]
@Fenny , I'll leave this issue open for future work on improving our pull request templates.
