### ISSUE TITLE
🐛 [Bug]: Proxy middleware and Vite dev server on localhost, tcp4 127.0.0.1:5173: connect: connection refused

### ISSUE THREAD

**Issue by sixcolors** [gofiber/fiber#2890]
### Bug Description

When using the proxy middleware to `proxy.BalanceForward([]string{"http://localhost:5173"}))` to a Vite/react dev server running on port 5173 the connection is refused with the following output `Error: The HTTP request failed with error dial tcp4 127.0.0.1:5173: connect: connection refused`

### How to Reproduce

Clone https://github.com/sixcolors/FiberReactTest

```bash
cd frontend
npm install --include=dev && npm run dev
```

The proxy demonstrates this behaviour as can be seen in the main.go:

```go
if DevMode {
		app.Get("*", proxy.BalancerForward([]string{"http://localhost:5173"}))
```

However the issue has been isolated to the fasthttp client.

To verify run the following:

```go
package main

import (
	"io"
	"log"
	"net/http"

	"github.com/valyala/fasthttp"
)

func main() {
	// test connection to http://localhost:5173
	resp, err := http.Get("http://localhost:5173")
	if err != nil {
		log.Fatalf("Error: The HTTP request failed with error %s", err)
	} else {
		defer resp.Body.Close()
		data, err := io.ReadAll(resp.Body)
		if err != nil {
			log.Fatalf("Error reading body: %v", err)
		}
		log.Printf("HTTP Response Status: %d %s", resp.StatusCode, http.StatusText(resp.StatusCode))
		log.Printf("Response Body: %s", string(data))
	}

	statusCode, body, err := fasthttp.Get(nil, "http://localhost:5173")
	if err != nil {
		log.Fatalf("Error: The HTTP request failed with error %s", err)
	} else {
		log.Printf("HTTP Response Status: %d", statusCode)
		log.Printf("Response Body: %s", body)
	}
}
```

### Expected Behavior

fasthttp client should connect to http://localhost:5173 and the proxy should work.

### Actual Behavior 

fasthttp client will not try dialing IPv6 by default and only IPv4 is tried, resulting in a connection refused error. 

### Fiber Version

v2.52.2

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by sixcolors** [comment]
bug filed with valyala/fasthttp https://github.com/valyala/fasthttp/issues/1730

**Comment by sixcolors** [comment]
Erik Dubbelboer from upstream issue:

> This is because `vite` only listens on IPv6 and fasthttp doesn't try dialing IPv6 by default. If you change the code to this it works:
> 
> ```go
> 	client := fasthttp.Client{
> 		DialDualStack: true,
> 	}
> 	statusCode, body, err := client.Get(nil, "http://localhost:5173")
> ```

**Comment by sixcolors** [comment]
Further ref for Vite/node: https://github.com/vitejs/vite/issues/2032
https://nodejs.org/api/net.html#net_server_listen_options_callback

**Comment by sixcolors** [comment]
Should we support dual stack be default in the client for proxy middleware, or no?

**Comment by negrel** [comment]
I believe adding an option for DialDualStack won't hurt. As a fiber user, I'm forced to fork proxy middleware to enable it as my cloud provider only support IPv6 for internal networking.

**Comment by gaby** [comment]
@negrel Agree we should add an option to allow either ipv4, ipv6 or DialDual to the middleware. Sounds reasonable to me.
