### ISSUE TITLE
🤗 [Question]: When can the 3.0 version be applied to the production environment?

### ISSUE THREAD

**Issue by my-world-2022** [gofiber/fiber#2893]
### Question Description

When can the 3.0 version be applied to the production environment? Is there an approximate timeframe? I need to work on a project that will take about 2 months to complete, so I'm currently debating whether to use version 2.0 or 3.0.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Hi, pls use version 2
We try our best to release v3 in the next 2 months

**Comment by my-world-2022** [comment]
ok, thk

**Comment by my-world-2022** [comment]
ok, thk

**Comment by my-world-2022** [comment]
ok, thk
