### ISSUE TITLE
🤗 [Question]: Custom Listen Function

### ISSUE THREAD

**Issue by skadiD** [gofiber/fiber#2907]
### Question Description

Currently, `reuseport.Listen` is only used after `Prefork` is enabled. However, in my scenario, in order to achieve seamless restart updates on the server side, I want `app.Listen` to be able to choose between `reuseport.Listen` and `net.Listen` based on custom requirements. At the same time, how can I get the returned `net.Listener` `ln`?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by skadiD** [comment]
It seems that I can use `app.Listener` to custom listen function

**Comment by ReneWerner87** [comment]
@skadiD can we close this or are there still questions

**Comment by ReneWerner87** [comment]
I'll close this for now, if there is still a need we can open it again
