### ISSUE TITLE
CSRF Trusted Origins

### ISSUE THREAD

**Issue by sixcolors** [gofiber/fiber#2909]
A possible solution that maintains best practice for CSRF protection while addressing some users issue where they have multilple origins that they consider trusted, could be to mirror https://docs.djangoproject.com/en/5.0/ref/settings/#std-setting-CSRF_TRUSTED_ORIGINS

_Originally posted by @sixcolors in https://github.com/gofiber/fiber/pull/2904#pullrequestreview-1924895214_

**Comment by sixcolors** [comment]
@sebytza23 faced a challenge with hosting both the backend and client on the same server, with HTTPS enforced, using Apache2 and Virtualmin, presumable for the front end. The issue arose because he couldn't have the same port (443) for the Apache2 client and the backend. I suggested using Apache as a reverse proxy for the backend, providing specific Apache module configurations and ProxyPass directives. Additionally, I mentioned the ongoing addition of TrustedOrigins to the CSRF middleware in gofiber.

For reference for anyone else with a similar setup:

Enable Apache Modules:

```bash
sudo a2enmod proxy
sudo a2enmod proxy_http
```

Configure ProxyPass:

Edit your Apache configuration file. This could be the default configuration file located at /etc/apache2/sites-available/000-default.conf or a custom configuration file. Add the ProxyPass directive to forward requests to your API.

```apache
<VirtualHost *:443>
    ServerName your-domain.com

    # ... other configuration settings ...

    ProxyPass /api http://localhost:3000/
    ProxyPassReverse /api http://localhost:3000/
# Forward client's IP address
    RequestHeader set X-Forwarded-For %{REMOTE_ADDR}
    RequestHeader set X-Real-IP %{REMOTE_ADDR}
    RequestHeader set X-Forwarded-Proto "https"
</VirtualHost>
```

Restart Apache:

```bash
sudo systemctl restart apache2
```

**Comment by ReneWerner87** [comment]
solved by https://github.com/gofiber/fiber/pull/2910
