### ISSUE TITLE
🔥 OAuth Multi-Provider Authentication

### ISSUE THREAD

**Issue by Shareed2k** [gofiber/fiber#292]
**Question description**
Is wrapper for [goth library](https://github.com/markbates/goth) to use with fiber Framework, provides a simple, clean, and idiomatic way to write authentication packages for Go web applications.

`go get github.com/shareed2k/goth_fiber`

**Code snippet (optional)**

```go
package main

import (
	"log"
	"os"

	"github.com/gofiber/fiber"
	"github.com/markbates/goth"
	"github.com/markbates/goth/providers/google"

	"github.com/shareed2k/goth_fiber"
)

func main() {
	app := fiber.New()

	goth.UseProviders(
		google.New(os.Getenv("OAUTH_KEY"), os.Getenv("OAUTH_SECRET"), "http://127.0.0.1:8088/auth/callback"),
	)

	app.Get("/login", goth_fiber.BeginAuthHandler)
	app.Get("/auth/callback", func(ctx *fiber.Ctx) {
		user, err := goth_fiber.CompleteUserAuth(ctx)
		if err != nil {
			log.Fatal(err)
		}

		ctx.Send(user)

	})
	app.Get("/logout", func(ctx *fiber.Ctx) {
		if err := goth_fiber.Logout(ctx); err != nil {
			log.Fatal(err)
		}

		ctx.SendString("logout")
	})

	if err := app.Listen(8088); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by thomasvvugt** [comment]
Hi @Shareed2k !
Thanks for creating this issue. I think the Goth package is very usefull when one is willing to use a thrid-party authentication provider using OAuth2 for example.
It supports a lot of providers and to me it seems worth to be taking a look at!

@Fenny Maybe we can create an addition middleware package for third-party authentication providers along with the session provider update?

**Comment by Fenny** [comment]
@Shareed2k awesome work, we will keep this issue open until our session middleware is finished. Me and @thomasvvugt are currently working on it. Will keep you updated.

**Comment by Fenny** [comment]
Our session middleware is updated to `v1.0.0` I saw you also updated this in your mw. We will add your repo to our official third party middlewares.

**Comment by wurikiji** [comment]
@Fenny When will this be documented? Or where can I find other useful official middlewares in addition to [official site](docs.gofiber.io)?
