### ISSUE TITLE
🤗 [Question]: Rate limit per path

### ISSUE THREAD

**Issue by kirankumar-grootan** [gofiber/fiber#2924]
### Question Description

is it possible to add rate limiting functionality per path e.g. have different rate limiting logic for each path below?

app.Get("/auth", handler.RedirectHandler) - rate limit by 10 for 1 min
app.Get("/auth/", handler.RedirectHandler) - rate limit by 5 for 1 min
app.Get("/auth/realms", handler.RedirectHandler) - rate limit by 25 for 1 min

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by bigboiii300** [comment]
Is anyone know decision?

**Comment by sixcolors** [comment]
Yes. You can use a new rate limiter middleware handler for each route. 

Either set a route on `app.Use` with the middleware handler (works with groups too), or apply the handler in the `app.Get`

https://docs.gofiber.io/guide/routing#middleware

**Comment by sixcolors** [comment]
Here is an example with app.Use

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/limiter"
)

func main() {
	app := fiber.New()

	// …

	// Custom rate limits for specific paths
	app.Use("/auth", limiter.New(limiter.Config{
		Max:        10, // Requests per minute for /auth
		Expiration: 1 * time.Minute,
	}))

	app.Use("/auth/", limiter.New(limiter.Config{
		Max:        5, // Requests per minute for /auth/
		Expiration: 1 * time.Minute,
	}))

	app.Use("/auth/realms", limiter.New(limiter.Config{
		Max:        25, // Requests per minute for /auth/realms
		Expiration: 1 * time.Minute,
	}))

	// Add your routes here
	app.Get("/auth", handler.RedirectHandler)
	app.Get("/auth/", handler.RedirectHandler)
	app.Get("/auth/realms", handler.RedirectHandler)

	// …

	// Start the server
	app.Listen(":3000")
}
```

**Comment by kirankumar-grootan** [comment]
@sixcolors  thanks I did the same way and it works
