### ISSUE TITLE
💡 Functional settings for config of App

### ISSUE THREAD

**Issue by CommoDor64** [gofiber/fiber#293]
## Current state:
Setting default configurations and addition new ones is kinda clunky.
```go
func New(settings ...*Settings) *App {
	schemaDecoderForm.SetAliasTag("form")
	schemaDecoderQuery.SetAliasTag("query")
	// Create app
	app := new(App)
	// Create settings
	app.Settings = new(Settings)
	// Set default settings
	app.Settings.Prefork = isPrefork()
	app.Settings.BodyLimit = 4 * 1024 * 1024
	// If settings exist, set defaults
	if len(settings) > 0 {
		app.Settings = settings[0] // Set custom settings
		if !app.Settings.Prefork { // Default to -prefork flag if false
			app.Settings.Prefork = isPrefork()
		}
		if app.Settings.BodyLimit <= 0 { // Default MaxRequestBodySize
			app.Settings.BodyLimit = 4 * 1024 * 1024
		}
		if app.Settings.Concurrency <= 0 {
			app.Settings.Concurrency = 256 * 1024
		}
		if app.Settings.Immutable { // Replace unsafe conversion funcs
			getString = getStringImmutable
			getBytes = getBytesImmutable
		}
	}
	return app
}
```
## Proposal
I propose to follow the methodology of Dave Cheney  https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis
```go
type Option func(a *app)

// an example for Concurrency setting
func Concurrency(concurrency int) Option {
        return func(a *app) {
                a.settings.Concurrency = concurrency
        }
}
func New(options ...Option) *App {
	// Create app
	app := new(App)
	// Create settings
	app.settings = new(Settings)
	// Set default settings
	app.settings.Prefork = isPrefork()
	app.settings.BodyLimit = 4 * 1024 * 1024
	app.settings.Concurrency = 256 * 1024
	// more default settings here

        for _,option := range options {
                option(app)
        }

	return app
}
```

It allows extending and changing any settings related matters very easily, I personally think it is a fantastic way that should be used whenever possible. This is a classic case for this.

**Comment by CommoDor64** [comment]
In case you find it useful I will hop on to work on a PR

**Comment by Fenny** [comment]
Looks interesting, I will definitively take a look at the article

**Comment by Fenny** [comment]
@CommoDor64 could you show us an real-world example on how the api/syntax would look like for the end-user?

**Comment by CommoDor64** [comment]
Sure,
*main.go*
```go
const (
    defaultConcurrency = ...
    defaultBodyLimit = ...
)

func main(){
    fiber.New(
        fiber.PreFork(),
        fiber.BodyLimit(defaultBodyLimit),
        fiber.Concurrency(defaultConcurrency),
        fiber.Immutable(),
    )
}
```

#### The main sell-points for me are two things
1) No cumbersome conditionals when setting default values, such as in New() in app.go
2) You don't expose the Settings struct and "trust" the user to set it up correctly

**Comment by thomasvvugt** [comment]
I don't agree with the fact that trusting the user to set up a Fiber application correctly is a selling point. I like the way that the Settings struct provides an overview of all the settings for the application, however I am waiting response from the other maintainers as well.
Thanks for your comment on the syntax!

**Comment by CommoDor64** [comment]
I meant the other way around, you don't trust the user.
It creates a limited functional API to work upon.

If the user wants to see what options are available for the settings he can either take a look at the **public functional options** or take a look inside the package to examine the **not-longer-public settings struct**, the latter should not be needed unless the user wants to alter the fiber package

**Comment by Fenny** [comment]
Hi @CommoDor64, we appreciate your suggestion! I do understand where you're coming from, but I tend to agree with @thomasvvugt. All possible settings are exposed on purpose to give users the complete freedom and flexibility for their web app. 

Everything is well [documented](https://docs.gofiber.io/application#settings) including the default values. With the current setup it's easy to explore the settings because they are bundled under one namespace `Settings`, this makes it clear to understand that all properties are related to the `app settings` and not the `fiber framework`.

![](https://i.imgur.com/l0mVORc.png)

![](https://i.imgur.com/FTCfJmx.png)

![](https://i.imgur.com/har5Hib.png)

![](https://i.imgur.com/lo8FrKf.png)

Feedback is always welcome, but since this won't change anytime soon because of incompatibility I will close this issue.

❤️
