### ISSUE TITLE
📝  *** CLOSE - I see Context( ) returns this type .... *** - r4[Proposal]: Add RequestCtx in ctx that returns *fasthttp from DefaultCtx

### ISSUE THREAD

**Issue by rabarar** [gofiber/fiber#2942]
### Feature Proposal Description

Give the users access to the whole fasthttp request for more control (i.e. accessing client certs via ctx) by creating a method similar to `func (c *DefaultCtx) Request() *fasthttp.Request` in `ctx.go` but instead returns `*fasthttp`

### Alignment with Express API

unknown. don't use javascript

### HTTP RFC Standards Compliance

confirmed

### API Stability

this feature doesn't affect API Stability

### Feature Examples

```go
// RequestCtx return the *fasthttp object
// This allows you to use all fasthttp.RequestCtx methods
// https://godoc.org/github.com/valyala/fasthttp#RequestCtx
func (c *DefaultCtx) Request() *fasthttp.RequestCtx {
    return &c.fasthttp
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have searched for existing issues that describe my proposal before opening this one.
- [X] I understand that a proposal that does not meet these guidelines may be closed without explanation.

**Comment by ReneWerner87** [comment]
@rabarar
Have you checked the context method?
https://github.com/gofiber/fiber/blob/7ba02c14cf53c5a5f8171a0e4eb125ef4615f7c0/ctx.go#L305

**Comment by rabarar** [comment]
Yeah - I literally found it moments *AFTER* posting the Feature Request … lol

**Comment by ReneWerner87** [comment]
Can we close the feature request? Because its there?

**Comment by rabarar** [comment]
I think that’s prudent :) 
Thanks!
