### ISSUE TITLE
📝 [Proposal]: Allow disabling cache for ctx.SendFile()

### ISSUE THREAD

**Issue by bpatyi** [gofiber/fiber#2945]
### Question Description

hello. Is there any way to turn off the ctx.SendFile cache? In our project, we further distribute files to devices in chunks, which can change every second. If I understand the code correctly, it is currently fixed to cache for 10 seconds, which causes it to arrive incorrectly. Thanks for your help.

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@bpatyi This would need to be added as a feature in `v3`. The filesystem middleware problably needs the same feature.

**Comment by gaby** [comment]
While we are at it, there's no unit-tests for the `compress` param.

https://github.com/gofiber/fiber/blob/main/ctx_test.go
