### ISSUE TITLE
🤗 [Question]: How to use BodyParse in v3 ?

### ISSUE THREAD

**Issue by root9464** [gofiber/fiber#2964]
### Question Description

```go
package main

import (
	"log"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/logger"
)

func main() {
	app := fiber.New()
	app.Use(logger.New())
	app.Get("/", func(Ctx fiber.Ctx) error {
		Ctx.BodyParser(struct{}{})
		return Ctx.SendString("Hello, World!")
	})
	log.Fatal(app.Listen(":3000"))
}

```

Ctx.BodyParser undefined (type fiber.Ctx has no field or method BodyParser)compiler[MissingFieldOrMethod](https://pkg.go.dev/golang.org/x/tools/internal/typesinternal#MissingFieldOrMethod)

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v3"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by VolkerLieber** [comment]
It looks like it should be done via `Ctx.Bind().Body`.
Source documentation:

- `Bind`: You can bind body, cookie, headers etc. into the map, map slice, struct easily by using Binding method. It gives custom binding support, detailed binding options and more. **Replacement of: BodyParser**, ParamsParser, GetReqHeaders, GetRespHeaders, AllParams, QueryParser, ReqHeaderParser
- `Body`: .Body binds the request body into the struct, map[string]string and map[string][]string. It supports decoding the following content types based on the Content-Type header: application/json, application/xml, application/x-www-form-urlencoded, multipart/form-data If none of the content types above are matched, it'll take a look custom binders by checking the MIMETypes() method of custom binder. If there're no custom binder for mşme type of body, it will return a ErrUnprocessableEntity error.

**Comment by gaby** [comment]
@VolkerLieber That's correct, the updates to the documentation are "Work In Progress".

**Comment by gaby** [comment]
V3 Docs until released: https://github.com/gofiber/fiber/blob/main/docs/api/bind.md#body
