### ISSUE TITLE
🤗 [Question]: Why v3 has no option to DisableStartupMessage

### ISSUE THREAD

**Issue by umardev500** [gofiber/fiber#2968]
### Question Description

I just uses v3 as i can see that has no disable startup message optopm available

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@umardev500 The option still there, it was moved under ListenConfig

See here: https://github.com/gofiber/fiber/blob/main/listen.go#L90

**Comment by gaby** [comment]
@umardev500  Example:

```go
app := fiber.New()
app.Listen(":3000", ListenConfig{DisableStartupMessage: true})
```
