### ISSUE TITLE
🤗 [Question]:   upstream reply  with long time 

### ISSUE THREAD

**Issue by wade-liwei** [gofiber/fiber#2970]
### Question Description

I use go fiber as the API server; Api server calling another API server takes 3 minutes, 
I do benchmark 2 TPS, but after 5 minutes, the Go Fiber API can not be accessed.

Do you have parameters for this environment?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@wade-liwei Can you provide an example code where this happens?

**Comment by wade-liwei** [comment]
I got the the error log.

level=warn component=client host=172.31.12.187:3100 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'fake'"
level=warn component=client host=172.31.12.187:3100 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'fake'"
level=warn component=client host=172.31.12.187:3100 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'fake'"
level=warn component=client host=172.31.12.187:3100 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'fake'"
level=warn component=client host=172.31.12.187:3100 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'fake'"
level=warn component=client host=172.31.12.187:3100 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'fake'"
level=warn component=client host=172.31.12.187:3100 msg="error sending batch, will retry" status=429 error="server returned HTTP status 429 Too Many Requests (429): Maximum active stream limit exceeded, reduce the number of active streams (reduce labels or reduce label values), or contact your Loki administrator to see if the limit can be increased, user: 'fake'"

**Comment by wade-liwei** [comment]
I can not provide an example code.

there are many dependent.

**Comment by gaby** [comment]
@wade-liwei If you are getting 429's it means you are being rate-limited by the service upstream which i guess is Loki in this case.

You need to add logic to your code, if yoy get 429, backoff and sleep then try again.

**Comment by wade-liwei** [comment]
Thank you, I will try your suggestion.

**Comment by wade-liwei** [comment]
@gaby 

Thank you good man,
I have fix the problem.

**Comment by gaby** [comment]
@wade-liwei Awesome! 💪
