### ISSUE TITLE
🤗 [Question]: i get v3 docs are not exactly v3 docs

### ISSUE THREAD

**Issue by umardev500** [gofiber/fiber#2971]
### Question Description

Any one can explain why the docs are not exactly v3

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
Yeah, because we are working on the docs (https://github.com/gofiber/fiber/pull/2934)
