### ISSUE TITLE
🐛 [Bug]: Middleware Monitor "CPU Usage" is a "static value".

### ISSUE THREAD

**Issue by nyufeng** [gofiber/fiber#2978]
### Bug Description

When I use "Monitor", I found that the value of "CPU Usage" of the program does not change, but the CPU usage of the program has been changing dynamically by `top` or `htop`. The system "CPU" is also changing dynamically.
After reading the source code, I found that this value is the average value since the program started, and does not reflect the current load of the program in real time. I hope to improve it.

### How to Reproduce

```
monitor.New()
```

### Expected Behavior

Dynamically changing like `top`.

### Fiber Version

v2.52.4

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by nyufeng** [comment]
If you're wondering the same thing, here's how to fix it
https://github.com/nyufeng/fiber-monitor

**Comment by gaby** [comment]
@nyufeng Your fixes will be released in the next v2 release.

Fixed via #2984
