### ISSUE TITLE
🔥 Portuguese translating API docs

### ISSUE THREAD

**Issue by rafamttz** [gofiber/fiber#298]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
Translate the Fiber documentation to brazilian portuguese.

**Additional context**
The brazilian Go community is huge and Fiber is a great framework so I want bring knowledge about Fiber to people from Brazil.

**Comment by Fenny** [comment]
@rafamttz, our API documentation is almost ready for translations. I will keep everyone posted when translations are accepted. Should be within 10 days 👍

**Comment by rafamttz** [comment]
Okay @Fenny I'll be waiting for it!

**Comment by Fenny** [comment]
@rafamttz, translations are now possible!

Please visit -> https://crowdin.com/project/gofiber

**Comment by rafamttz** [comment]
Ok, I'll fork the project and then open PR...

**Comment by Fenny** [comment]
@rafamttz translations can be done via the crowdin interface.
![](https://i.imgur.com/cwMlpdP.png)

**Comment by thomasvvugt** [comment]
Please see the above comment for contributing translations.
