### ISSUE TITLE
🤗 [Question] Is Fiber going to be used for Rust?

### ISSUE THREAD

**Issue by omolayoabegunde** [gofiber/fiber#2995]
### Question Description

Good day! I want to ask, is there going to be a support for Rust in the future? I just enjoy usingn fiber.

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v3"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
No, there's nothing like this planned.

**Comment by omolayoabegunde** [comment]
> No, there's nothing like this planned.

Ok! Thanks
