### ISSUE TITLE
Add a default document names for the static method

### ISSUE THREAD

**Issue by hyingreborn** [gofiber/fiber#3]
Add a default document names for the static method plz : "index.html"、"index.htm"、"default.html"、"default.htm"

server.go
```
app.Static("./public/static", "/static")
```

when i visit http://127.0.0.1:8080/static，Instead of 404, the contents of index.html are displayed by default

**Comment by Fenny** [comment]
Hi @hyingreborn ,

I was planning to add some settings on the Static method so you can disable the default index.html or gzipping. If I understand you correctly, you would like to disable the default index.html route or rename it to "default.html" instead?

Thanks for your feedback btw :+1:

**Comment by hyingreborn** [comment]
@Fenny tks for your reply！
The static method is quite different from other frameworks，like gin or echo，The path rules for the files are not as expected，Can you refer to gin or echo?

**Comment by Fenny** [comment]
Hi @hyingreborn ,
I checked out the static method details from thr  echo documention and it's almost identical.
https://echo.labstack.com/guide/static-files

The only difference with the static method from fiber is that the `virtual path prefix` is optional. If you don't use a prefix, it defaults to `/`.

The following examples achieve the same results:
```go
app := fiber.New()
app.Static("/", "./my/static/files")
// => http://localhost:8080/gopher.png

app.Static("./my/static/files")
// => http://localhost:8080/gopher.png
```

**Comment by hyingreborn** [comment]
Hi @Fenny ，
I built a SPA using Vuejs，then try to add it to Fiber's project，directory structure like this: 
```
|-public
|--favicon.ico // for global path to visit
|--app // VueJS's SPA
|---index.html
|---js
|----js
|---css
|---...
```
I hope that through http://127.0.0.1:8080/app to access the directory/public/app, so I this configuration：
```js
app := fiber.New()
app.Static("/app", "./public/app")
```
The result is that i can only access index.html as the default document, and no other static files are not accessible，my vue's spa already config public path to "./"，It works in subdirectories under both gin and echo。
