### ISSUE TITLE
🐛 [Bug]: incorrect selection of the error handler if one of the sub apps is mounted on "/"

### ISSUE THREAD

**Issue by DaryaHom** [gofiber/fiber#3003]
### Bug Description

I create two sub apps with different error handlers and mount one of them on the “/” path and the other on the “/two” path. 

If an error occurs in handler, the (app *App)ErrorHandler method can incorrectly define the error handler for the second sub app. You can see this in the code snippet.

This happens because the paths “/” and “/two” return the same number of parts (2) from strings.Split(prefix, “/” ) , and the path “/two” is prefixed with “/”. For the method to work correctly, the path “/” must be defined as only 1 part:

```
func (app *App) ErrorHandler(ctx *Ctx, err error) error {
	...
	for prefix, subApp := range app.mountFields.appList {
		if prefix != "" && strings.HasPrefix(ctx.path, prefix) {
                        if prefix == "/" {
                                parts = 1
                        } else {
			parts := len(strings.Split(prefix, "/"))
			}
	...
```

### How to Reproduce

1. Run the code snippet (may take a few times).
2. Check the output in the stdout.

### Expected Behavior

The error handler for the sub app must be defined correctly. 
In my example, only the `twoErrorHandler` must be used for the sub app `two`.

### Fiber Version

v2.52.0

### Code Snippet (optional)

```go
package main

import (
	"errors"
	"fmt"
	"log"
	"net/http"

	"github.com/gofiber/fiber/v2"
)

// Custom error handlers.
func oneErrorHandler(c *fiber.Ctx, err error) error {
	// Custom error handling logic here.
	fmt.Println("ONE error handler")

	// Return from handler
	return fiber.DefaultErrorHandler(c, err)
}

func twoErrorHandler(c *fiber.Ctx, err error) error {
	// Custom error handling logic here.
	fmt.Println("TWO error handler")

	// Return from handler
	return fiber.DefaultErrorHandler(c, err)
}

func handler(c *fiber.Ctx) error {
	// Return error to call ErrorHandler
	return errors.New("some error")
}

func runFiberApps() {
	app := fiber.New()
	// Create first sub-app with custom error handler.
	one := fiber.New(fiber.Config{
		ErrorHandler: oneErrorHandler,
	})
	one.Get("/some-path", handler)
	app.Mount("/", one)

	// Create second sub-app with custom error handler.
	two := fiber.New(fiber.Config{
		ErrorHandler: twoErrorHandler,
	})
	two.Get("/some-path", handler)
	app.Mount("/two", two)

	log.Fatal(app.Listen(":3000"))
}

func main() {
	// Create one fiber.App with two sub apps and start listen on :3000.
	go runFiberApps()

	// Multiple calls to the handler "two"
	// to see a random error handler calls.
	for i := 0; i < 20; i++ {
		_, _ = http.Get("http://localhost:3000/two/some-path")

	}

	fmt.Println("the end")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
@DaryaHom  your expectations are not entirely correct


https://docs.gofiber.io/guide/grouping
![image](https://github.com/gofiber/fiber/assets/7063188/caf01ac6-0770-47db-b854-baf8df490972)

since only a flat list exists internally in fiber and your first app is registered on the "root" path, the error handler also works for this path

the problem in the example is that you want to achieve app separation for different paths, but the paths overlap in prefix matching

the registration works like a middleware "app.Use" and uses a prefix matching for all things that do not match exactly, such as the error handler
