### ISSUE TITLE
🤗 [Question]: gofiber v3 rc release date?

### ISSUE THREAD

**Issue by febelery** [gofiber/fiber#3004]
### Question Description

gofiber v3 official release plan, currently beta.2, I would like to guide the beta how many more versions, to rc how many more versions

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by liaohongxing** [comment]
I've been waiting for v3 since March

**Comment by ReneWerner87** [comment]
unfortunately we are not progressing as fast as expected and we want to add some more features before we create the new major version

it will probably take another 1-2 months before we release the stable version
