### ISSUE TITLE
🤗 [Question]: Is `fiber.Ctx` thread safe? If not, is that documented?

### ISSUE THREAD

**Issue by omaskery** [gofiber/fiber#3012]
### Question Description

The project I've recently joined uses fiber, and when running the test suite with `--race` I'm getting races detected. Several of them seem to stem from accessing `Ctx` in multiple goroutines. For example, when `Ctx.String()` is called by our test framework it internally asks `fasthttp` for `c.fasthttp.URI().FullURI()` which internally computes the full URI on each invocation and writes it to an internal variable.

I've tried searching online to see if other people have discussed this already, or had similar issues, but I've had no luck.

So my question is: is `fiber.Ctx` thread safe or is it not intended for sharing between goroutines?

If it is not thread safe: should this be documented somewhere, similar to how it is documented that `Ctx` is only valid for the duration of the request handler?

### Code Snippet (optional)

Edit: quickly added some pseudo code:

```go
func Handler(ctx *fiber.Ctx, ...) (..., error) {
  eg := errgroup.Group{}
  
  eg.Go(func() error {
    // use ctx
    return nil
  })
  
  eg.Go(func() error {
    // use ctx
    return nil
  })
  
  if err := eg.Wait(); err != nil {
    return err
  }
  
  return ..., nil
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@omaskery does it answer your question?

**Comment by omaskery** [comment]
Ah, so to me the wording of the documentation makes it clear that you should not keep references to Ctx that outlive the handler's execution, but it does not make clear to me that it isn't thread-safe _during_ the execution of a handler.

If I'm understanding you correctly that the `fiber.Ctx` is not thread-safe, even within the handler's duration, then I think you've answered my question, thank you.

I do feel that it might be worth explicitly stating in the documentation that this struct is not thread-safe. What do you think?

**Comment by ReneWerner87** [comment]
> I do feel that it might be worth explicitly stating in the documentation that this struct is not thread-safe. What do you think?

yes that would be good

can you provide this as a contribution to our current documentation ?

**Comment by omaskery** [comment]
Yeah I'm willing to give that a go :)

**Comment by umardev500** [comment]
I still never get it, hard to understand for me haha

**Comment by ReneWerner87** [comment]
> I still never get it, hard to understand for me haha

what do you not understand ? the context cannot be torn out of its process and simply be used in a parallel process
because it is reused after the request response process
and it is not designed to access the methods in parallel, there might be problems in some places
therefore you should extract the values beforehand and use them in the parallel run
