### ISSUE TITLE
🤗 [Question]: A new Redis key is created every time the url is accessed. Is this normal?

### ISSUE THREAD

**Issue by yusrenaltair** [gofiber/fiber#3013]
### Question Description

I copied and modified the code in the following recipe repo.
[https://github.com/gofiber/recipes/tree/master/csrf-with-session](https://github.com/gofiber/recipes/tree/master/csrf-with-session) 
I made some modifications, so this is the final code :
[https://github.com/yusrenaltair/fiber_example/tree/main](https://github.com/yusrenaltair/fiber_example/tree/main)
You can try it on your localhost. 
I setup TLS With nginx btw and I use Redis for Session storage.
What I want to ask is that every time I run main.go in the client directory, which calls the `/test-api` url in the server directory (already running), Redis always creates a new key. Occurs only when the Session position is LOGGED IN.
Does Fiber really work like that, Or did I make a mistake in writing the code?
Thanks in advance

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by sixcolors** [comment]
@yusrenaltair your client does not seem to be setting any cookies. So you would be creating a new session and CSRF token on that GET request.

**Comment by yusrenaltair** [comment]
Dear @sixcolors.
do you have a code snippet to provide guidance on how to solve this?
I still don't really understand this client server connection, but I really need it.
Thank you in advance.

**Comment by sixcolors** [comment]
> Dear @sixcolors. do you have a code snippet to provide guidance on how to solve this? I still don't really understand this client server connection, but I really need it. Thank you in advance.
> 
> edit: Or do I just follow the agent cookie guide on the following Fiber documentation page? https://docs.gofiber.io/api/client/#cookie

Depends on the use case. It appears that you have your own token/api key auth middleware. Why are you using Session and CSRF?

**Comment by yusrenaltair** [comment]
I'm working on a project. Create a simple custom SSO that will be used internally (Server and Client App on the same server).  The goal is that the Server session can be used together with the Client App. Every request received by the Client Backend will pass through middleware which will be connected to the SSO Server's session checking function. Sorry in advance, frankly I'm still a newbie about this.
