### ISSUE TITLE
📝 [Proposal]: Improving route matching and url parsing performance with Ada Url

### ISSUE THREAD

**Issue by meftunca** [gofiber/fiber#3019]
### Feature Proposal Description

Ada Url can parse url information really fast. Because it processes simd and data in parallel, which means doing multiple operations at once. By parsing url parsing information quickly, we can actually approach the speed of fasthttp.

After Ada Url started using nodejs, they got a really big performance boost. At least we should be able to enable this feature via fiber config.
https://github.com/ada-url/ada#ada-is-fast

### Alignment with Express API

It does not include any changes that will affect the interface of Express JS.

### HTTP RFC Standards Compliance

This feature only speeds up route matching and url fragmentation. It is not a feature that will break any existing structure.

### API Stability

This feature only speeds up route matching and url fragmentation. It is not a feature that will break any existing structure. As I mentioned above, nodejs has provided more than 4x performance increase thanks to this library. It also already uses this library.

### Feature Examples

```go
import (
   "github.com/ada-url/goada"
   "fmt"
)

url, err := goada.New("https://www.GOogle.com")
if err != nil {
    t.Error("Expected no error")
}
fmt.Println(url.Href()) // prints https://www.google.com/
url.SetProtocol("http:")
url.SetHash("goada")
fmt.Println(url.Hash()) // prints #goada
fmt.Println(url.Href()) // prints http://www.google.com/#goada
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have searched for existing issues that describe my proposal before opening this one.
- [X] I understand that a proposal that does not meet these guidelines may be closed without explanation.

**Comment by ReneWerner87** [comment]
thx for the idea

our current matching is already quite optimized and can keep up with that of aida
![image](https://github.com/gofiber/fiber/assets/7063188/33bcf2d3-af36-42bf-bcf3-cc3c347dbaf6)

but we are happy to test it

**Comment by meftunca** [comment]
Can you share the results of the comparison with us? @ReneWerner87 :)

**Comment by ReneWerner87** [comment]
my screenshot and the numbers from your article

ada average number
![image](https://github.com/gofiber/fiber/assets/7063188/0183a05f-9b1d-411e-990d-e1ea054a6289)

our route parsing numbers
![image](https://github.com/gofiber/fiber/assets/7063188/8936945e-c4e9-4c8d-88d9-e64b82c031f6)

**Comment by ReneWerner87** [comment]
perhaps a misunderstanding

we can test the package in fiber and then look at the results
just wanted to show that we already have very good results
but it varies depending on which cases are used, so you can't really say which is faster and test it in an integrated way

**Comment by meftunca** [comment]
Then I'll take the time to do some benchmarks over the weekend if you like, and we'll continue by adding the benchmarks here, along with the existing and island url.

**Comment by nickajacks1** [comment]
This requires cgo, which would be a real shame to force on users. If it's included in fiber, I think it should be an optional addon.

**Comment by gaby** [comment]
@ReneWerner87 I think we can close this since it requires CGO

**Comment by ReneWerner87** [comment]
Ok, thx
