### ISSUE TITLE
🤗 [Question]: v3 when ready for production

### ISSUE THREAD

**Issue by umardev500** [gofiber/fiber#3023]
### Question Description

Does v3 is ready for production, previously i have seen the latest docs is v3 then reversed into v2 again as default docs

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@umardev500 v3 is still in Beta as stated in the README https://github.com/gofiber/fiber?tab=readme-ov-file#%EF%B8%8F-attention

**Comment by gaby** [comment]
@umardev500 we are now production ready, https://github.com/gofiber/fiber/releases/tag/v3.0.0
