### ISSUE TITLE
🤗 [Question]: Cache Next is not called when KeyGenerator is Defined

### ISSUE THREAD

**Issue by hcancelik** [gofiber/fiber#3034]
### Question Description

Is it by design or a bug that the `Next` function is not called when the `KeyGenerator` config is defined?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "github.com/gofiber/fiber/v2/middleware/cache"
import "log"

func main() {
  app := fiber.New()

  app.Use(cache.New(cache.Config{
    Next: func(c *fiber.Ctx) bool {
      panic("not called")
      return c.Query("noCache") == "true"
    },
    KeyGenerator: func(c *fiber.Ctx) string {
      return fmt.Sprintf("report-%s", c.Query("startDate"))
    },
    Expiration: 30 * time.Minute,
    CacheControl: false,
  }))

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@hcancelik there is no dependency on the other function outside

but there are other dependencies, e.g. if the cache entry is not there and has to be created first, etc.

can you narrow down the problem more precisely?

https://github.com/gofiber/fiber/blob/6c9510df5a376c9a9dd2fbc7310f032e9137d24f/middleware/cache/cache.go#L174

**Comment by hcancelik** [comment]
@ReneWerner87, thanks for your response. 

I think I misunderstood what `Next` was doing. It looks like Next closure is not called if there is already a cache.

I was trying to skip the existing cache and generate a new one by passing query parameters with Next. I guess that's not doable with the current middleware. 

Skip middleware completely skips the cache so I cannot use that either.

**Comment by ReneWerner87** [comment]
@hcancelik good point, we are currently working on version 3

can you help and make the cache middleware capable of covering this case

i think we have had several requests like this from other users

maybe we should provide a `cacheInvalidation` function that gets the `context` and if it is `true`, the cache is invalidated and the caching is skipped

**Comment by hcancelik** [comment]
@ReneWerner87 I'm not good at Go, but I will try it and let you know.

**Comment by hcancelik** [comment]
@ReneWerner87 I just sent a PR for this https://github.com/gofiber/fiber/pull/3036
