### ISSUE TITLE
🐞 [Bug]:  v3 Flash Message with redirect is not working 

### ISSUE THREAD

**Issue by patelajay745** [gofiber/fiber#3038]
### Question Description

I am sending flash message using below code

return c.Redirect().With("status","added").To("/dashboard")

and try to retrieve it using below code 

message := c.Redirect().Message("status")

Not getting anything.

Is there anything wrong?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
thanks for the report we will have a look in the next hours/days

**Comment by ReneWerner87** [comment]
thx for the report 

example:
```go
package main

import (
	"fmt"
	"log"

	"github.com/gofiber/fiber/v3"
)

func main() {
	app := fiber.New()

	app.Get("/redirectWithRoute", func(c fiber.Ctx) error {
		return c.Redirect().With("status", "Logged in successfully").Route("base")
	})
	app.Get("/redirectWithTo", func(c fiber.Ctx) error {
		return c.Redirect().With("status", "Logged in successfully").To("/")
	})

	app.Get("/", func(c fiber.Ctx) error {
		fmt.Println("messages", c.Redirect().Messages())
		// => Logged in successfully
		return c.SendString(c.Redirect().Message("status"))
	}).Name("base")

	log.Fatalln(app.Listen(":3000"))
}
```
curl
http://localhost:3000/redirectWithTo
http://localhost:3000/redirectWithRoute


currently there is only the flash messages functionality in the `Route` method
https://github.com/gofiber/fiber/blob/ba6ea675ba4a1562e364cde0e2adf754b0d6feb4/redirect.go#L204-L233

but we will move this to the `To` function

because other methods(`Route`, `Back`) are using this internally 
https://github.com/gofiber/fiber/blob/main/redirect.go#L250-L253
https://github.com/gofiber/fiber/blob/main/redirect.go#L270

**Comment by keypeearr** [comment]
Hello, I have used the example usage above. I would like to verify if I am the only one getting this issue that the message isn't being retrieved.

> https://github.com/gofiber/fiber/issues/3038#issuecomment-2180722931

Here is the example code I used:

`
package main

import (
	"fmt"

	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/logger"
)

func main() {
	app := fiber.New(fiber.Config{
		AppName: "Go Test",
	})

	app.Use(logger.New(logger.ConfigDefault))

	app.Get("/redirectWithRoute", func(c fiber.Ctx) error {
		return c.Redirect().With("status", "Logged in successfully").Route("base")
	})
	app.Get("/redirectWithTo", func(c fiber.Ctx) error {
		return c.Redirect().With("status", "Logged in successfully").To("/")
	})

	app.Get("/", func(c fiber.Ctx) error {
		fmt.Println("messages", c.Redirect().Messages())
		// => Logged in successfully
		return c.JSON(c.Redirect().Message("status"))
	}).Name("base")

	if err := app.Listen(":3000"); err != nil {
		panic(err)
	}
}
`

Here is the screenshot of the output:
<img width="1182" alt="Image" src="https://github.com/user-attachments/assets/0bc19510-2300-4958-b1ff-1e0bd5695e00" />

<img width="716" alt="Image" src="https://github.com/user-attachments/assets/122aebd0-efef-4fd0-b722-59db2c07312b" />

NOTE: I have only made a single request for each endpoint and noticed that it keeps on logging multiple requests in the background. I am not sure if that's how it works or there's something I do not understand yet.

**Comment by zhukovra** [comment]
@keypeearr I opened new bug with detailed problem description https://github.com/gofiber/fiber/issues/3437
