### ISSUE TITLE
📝 [Proposal]: Upgrade fiber.NewError() for error handle

### ISSUE THREAD

**Issue by pwtitle** [gofiber/fiber#3040]
### Feature Proposal Description

i want use Custom ErrorHandler to handle my error, but now fiber.NewError() has missed my message params

 for example i want use fiber.NewError like this:

`return fiber.NewError(45001, "my error message", 401)`

on fiber.NewError() will missed my params : 401

<img width="437" alt="image" src="https://github.com/gofiber/fiber/assets/3120531/174b9a19-dd81-4f81-8c31-c9896d78aa35">

can you change the Error and NewError() like this:

<img width="411" alt="image" src="https://github.com/gofiber/fiber/assets/3120531/7ac99391-4b65-4f4e-8c42-6faad6f6bf3e">

i will handle the error in my Custom ErrorHandler:

<img width="717" alt="image" src="https://github.com/gofiber/fiber/assets/3120531/1a1995d4-c484-4c45-a5c5-8457c5d6109a">

### Alignment with Express API

nothing

### HTTP RFC Standards Compliance

nothing

### API Stability

nothing

### Feature Examples

```go
nothing
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have searched for existing issues that describe my proposal before opening this one.
- [X] I understand that a proposal that does not meet these guidelines may be closed without explanation.

**Comment by ReneWerner87** [comment]
@pwtitle hi, i think you have a very specific problem that does not match the requirements of other consumers

the fiber.Error struct is public and you can fill it without the NewError method

**Comment by luk3skyw4lker** [comment]
I'm not sure if this should be considered at all. this is fixable by creating a custom error implementing the error interface and returning it at every error occurrence if I'm not mistaken. The error handler doesn't exactly needs it to be a fiber.Error struct, it only needs the error to be compliant with the error interface.

I could be wrong about this, but from what I've gathered reading the ErrorHandler config parameters, this is what I could understand.

**Comment by ReneWerner87** [comment]
right, so I think this requirement is too specific for a special case and can already be handled well with custom errors
