### ISSUE TITLE
🤗 [Question]: FX with Fiber graceful shutdown Failed to stop cleanly: context deadline exceeded

### ISSUE THREAD

**Issue by conioX** [gofiber/fiber#3053]
### Question Description

Hello Guys

i always getting Failed to stop (cleanly: context deadline exceeded) after run the script and hit the endpoint /

[Fx] ERROR              Failed to stop cleanly: context deadline exceeded

i also try ShutdownWithTimeout and ShutdownWithTimeout no one working

```
package main

import (
	"fx-fiber/webserver"
	"context"
	"go.uber.org/fx"
	"log"
	"time"
)

func boostrap(
	lifeCycle fx.Lifecycle,
	webserver *webserver.Webserver,
) {
	lifeCycle.Append(fx.Hook{
		OnStart: func(_ context.Context) error {
			go func() {
				if err := webserver.StartServer(); err != nil {
					log.Fatalf("start server error : %v\n", err)
				}
			}()
			return nil
		},
		OnStop: func(ctx context.Context) error {
			log.Println("stopping server ...")
			time.Sleep(5 * time.Second)
			log.Println("stop server success")
			return webserver.ShutDownServer()
		},
	})
}

func main() {
	fx.New(
                user.module,
		webserver.Module,
		fx.Invoke(boostrap),
	).Run()
}
```

```
package webserver

import (
	"github.com/gofiber/fiber/v2"
)

type (
	Webserver struct {
		app *fiber.App
	}
	webserverInterface interface {
		StartServer() error
		ShutDownServer() error
	}
)

func NewWebServer() *Webserver {
	return &Webserver{app: fiber.New()}
}

func (webServer *Webserver) App() *fiber.App {
	return webServer.app
}

func (webServer *Webserver) StartServer() error {
	app := webServer.app

	return app.Listen(":3000")
}

func (webServer *Webserver) EchoRoute(ctx *fiber.Ctx) error {
	return ctx.SendString("Hello, World 👋!")
}

func (webServer *Webserver) ShutDownServer() error {
	return webServer.app.Shutdown()
}

```

```
package webserver

import "go.uber.org/fx"

var Module = fx.Options(
	fx.Provide(NewWebServer),
)

```

```
package users

import (
       "fx-fiber/webserver"
	"github.com/gofiber/fiber/v2"
	"go.uber.org/fx"
)

type UserController struct {
	fx.In
}

func (c *UserController) GetPosts(ctx *fiber.Ctx) error {
	return ctx.SendString("Hello, World 👋!")
}

func UseRegister(webserver *webserver.Webserver, endpoint UserController) {
	webserver.App().Get("/", endpoint.GetPosts)
}
```

```
package users

import (
	"go.uber.org/fx"
)

var Module = fx.Options(
	fx.Invoke(UseRegister),
)

```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@conioX You should be using `ShutdownWithContext()`.

```go
        OnStop: func(ctx context.Context) error {
			log.Println("stopping server ...")
			return webserver.ShutdownWithContext(ctx)
		},
```

**Comment by conioX** [comment]
hi @gaby 

i change my code 

```
func (webServer *Webserver) ShutDownServer(ctx context.Context) error {
	return webServer.app.ShutdownWithContext(ctx)
}
```

```
func boostrap(
	lifeCycle fx.Lifecycle,
	webserver *webserver.Webserver,
) {
	lifeCycle.Append(fx.Hook{
		OnStart: func(_ context.Context) error {
			go func() {
				if err := webserver.StartServer(); err != nil {
					log.Fatalf("start server error : %v\n", err)
				}
			}()
			return nil
		},
		OnStop: func(ctx context.Context) error {
			return webserver.ShutDownServer(ctx)
		},
	})
}
```


But still same i got this error : 

[Fx] INTERRUPT
[Fx] HOOK OnStop                main.boostrap.func2() executing (caller: main.boostrap)
[Fx] HOOK OnStop                main.boostrap.func2() called by main.boostrap failed in 15.0002333s: context deadline exceeded
[Fx] ERROR              Failed to stop cleanly: context deadline exceeded

**Comment by gaby** [comment]
Why is your server taking `+15secs` to `shutdown` ?

**Comment by conioX** [comment]
i dont know @gaby lol 

i just run the server with go run main.go and hit the endpoint localhost:3000 after that hit the ctrl + c to interupt the server ant then i got the context deadline exceeded

**Comment by gaby** [comment]
@gofiber/maintainers Any ideas?

**Comment by conioX** [comment]
extra information : 

if i interupt the server without open the endpoint localhost:3000 shutdown success 

[Fx] INTERRUPT
[Fx] HOOK OnStop                main.boostrap.func2() executing (caller: main.boostrap)
2024/06/30 22:27:15 stopping server ...
[Fx] HOOK OnStop                main.boostrap.func2() called by main.boostrap ran successfully in 5.9794ms


```
func boostrap(
	lifeCycle fx.Lifecycle,
	webserver *webserver.Webserver,
) {
	lifeCycle.Append(fx.Hook{
		OnStart: func(_ context.Context) error {
			go func() {
				if err := webserver.StartServer(); err != nil {
					log.Fatalf("start server error : %v\n", err)
				}
			}()
			return nil
		},
		OnStop: func(ctx context.Context) error {
			log.Println("stopping server ...")

			if err := webserver.ShutDownServer(ctx); err != nil {
				log.Fatalf("stop server error : %v\n", err)
			}

			return nil
		},
	})
}
```

and i change my lifecycle  above

**Comment by gaby** [comment]
@conioX This is probably because of `Keep-Alive`. Try opening the browser, and close it. Wait 5-10 seconds and try to shutdown the server.

**Comment by conioX** [comment]
@gaby it work

but should i disable the keep alive? is it  recommend?

**Comment by gaby** [comment]
@conioX Set your IdleTimeout to 10secs.

Docs here: https://docs.gofiber.io/api/fiber#idletimeout

**Comment by gaby** [comment]
```go
func NewWebServer() *Webserver {
	return &Webserver{app: fiber.New(fiber.Config{
		IdleTimeout: 5 * time.Seconds
	})}
}

```

**Comment by conioX** [comment]
not work @gaby 

already try 1s, 5s, 10s

[Fx] INTERRUPT
[Fx] HOOK OnStop                main.boostrap.func2() executing (caller: main.boostrap)
2024/07/01 08:22:50 stopping server ...
[Fx] ERROR              Failed to stop cleanly: context deadline exceeded
exit status 1

**Comment by gaby** [comment]
@conioX How about using ReadTimeout ?

```go
func NewWebServer() *Webserver {
	return &Webserver{app: fiber.New(fiber.Config{
		ReadTimeout : 5 * time.Second
	})}
}
```

**Comment by conioX** [comment]
@gaby 

ReadTimeout works

```
func NewWebServer(users *users.Users) *Webserver {
	app := fiber.New(fiber.Config{
		ReadTimeout:  30 * time.Second,
		WriteTimeout: 30 * time.Second,
	})

	app.Get("/users", users.FindUsers)

	return &Webserver{app: app}
}
```

and i change my main.go and increase the fx start and stop timeout

```
func main() {
	app := fx.New(
		fx.StartTimeout(120*time.Second),
		fx.StopTimeout(120*time.Second),
		webserver.Module,
		users.Module,
		fx.Invoke(boostrap),
	)
	app.Run()
}
```

**Comment by gaby** [comment]
@conioX Glad you found a solution!
