### ISSUE TITLE
🤗 [Question]: whats the session id injection issue in github report

### ISSUE THREAD

**Issue by MrAllenA** [gofiber/fiber#3057]
https://github.com/gofiber/fiber/security/advisories/GHSA-98j2-3j3p-fw2v

**Comment by sixcolors** [comment]
@MrAllenA advisory has a description of the vulnerability and is fixed in v2.52.5.

can you be more specific as to what you want to know?

**Comment by sixcolors** [comment]
No response from OP closing issue.
