### ISSUE TITLE
📝 [Proposal]: Add StartupProbe support to healthcheck Middleware

### ISSUE THREAD

**Issue by kirankumar-grootan** [gofiber/fiber#3068]
### Maintenance Task Description

Add StartupProbe support for the health check middleware, similar to the existing Liveness and Readiness Probes. Kubernetes supports three distinct probes, making it easier to read and maintain each probe separately.

### Checklist:

- [X] I have confirmed that this maintenance task is currently not being addressed.
- [X] I understand that this task will be evaluated by the maintainers and prioritized accordingly.
- [X] I am available to provide further information if needed.

**Comment by kirankumar-grootan** [comment]
It's seems pretty much straight forward. I can also contribute 🙂

**Comment by ReneWerner87** [comment]
yeah sounds good, you can extend the existing mw with this part

**Comment by kirankumar-grootan** [comment]
Hi @gaby 

I apologize for the confusion. I was referring to version 2. Sorry, I didn't realize that Fiber is now working on version 3 https://github.com/gofiber/fiber/blob/v2/middleware/healthcheck/config.go#L8.

After reviewing the version 3 documentation, I see that we can add as many probe routes as we want no changes required. https://docs.gofiber.io/next/middleware/healthcheck. I can add `DefaultStartupEndpoint = "/startupz"` and raise PR.

**Comment by ReneWerner87** [comment]
@kirankumar-grootan
i see the healthcheck mw is better in v3 https://docs.gofiber.io/next/middleware/healthcheck

can you still add the default path for the startup probe and documentation so that people don't wonder why we didn't include them

**Comment by luk3skyw4lker** [comment]
@ReneWerner87 I thought that the readiness probe already did the work that the startup probe is mentioning here. It is supposed to only return true when the app is totally ready to serve requests, we can't check it inside the middleware because the requirements for each application are different, but when you set a custom function for it, it should check for all the requirements for the app to serve the requests and then return true if so.

**Comment by kirankumar-grootan** [comment]
https://github.com/gofiber/fiber/pull/3069 merged with startup probe change and doc for v3.
