### ISSUE TITLE
🐛 [Bug]: Can't debug in Goland in Routes

### ISSUE THREAD

**Issue by vruzin** [gofiber/fiber#3071]
### Bug Description

Checking in Intellij Goland (dlv)

### How to Reproduce

Checking in Intellij Goland (dlv)

### Expected Behavior

Debug )))

### Fiber Version

v2.52.5

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v3"
import "log"

func main() {
  app := fiber.New()
  fmt.Println("In main") // Breakpoint  working

  app.Post("/", Home).Name("Home")
  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}

func Home(c *fiber.Ctx) error {
	fmt.Println("Home") // Breakpoint not working
	return c.SendString(fmt.Sprintf("Home: Ok\n%v", rand.Intn(100))) // Breakpoint  not working
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
its working in my goland
![image](https://github.com/user-attachments/assets/8da6ac0c-c186-45d5-918a-3123b2cf94d3)

my steps:
1. start the server via dlv on the shell
```sh
 dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient debug main.go 
 ```
 
2. start the debug listener
![image](https://github.com/user-attachments/assets/f9a4ab8b-5393-4bf8-b93a-5d84fa243d1f)

3. send rest requests
