### ISSUE TITLE
🐛 [Bug]: v3 Client ignores proxy settings

### ISSUE THREAD

**Issue by timerzz** [gofiber/fiber#3085]
### Bug Description

I used fiber v3 client and used the SetProxyURL method. But the agent didn't actually work.
I checked the source code of fiber. SetProxyUrl sets the proxyURL for the Client, but this attribute is not used in the actual request.

### How to Reproduce

1. just create a client , and SetProxyURL.
2. request 
3. No proxy used

### Expected Behavior

The set proxy should be used when making requests

### Fiber Version

v3.0.0-beta.3 

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by timerzz** [comment]
I looked at the unit test for [Test_Client_SetProxyURL](https://github.com/gofiber/fiber/blob/main/client/client_test.go#L1537) and this unit test doesn't seem to verify that the request goes through the proxy.   
Maybe this unit test needs some modifications

**Comment by timerzz** [comment]
I saw that fasthttp has a [proxy implementation](https://pkg.go.dev/github.com/valyala/fasthttp/fasthttpproxy#FasthttpHTTPDialer). Maybe we can set c.fasthttp.Dial in SetProxyURL without c.proxyURL field.

**Comment by gaby** [comment]
@efectn Thoughts?
