### ISSUE TITLE
🤗 [Question]:  When there will be direct support for a-h/templ?

### ISSUE THREAD

**Issue by NikoMalik** [gofiber/fiber#3094]
### Question Description

lacks direct templates support for fiber functions

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v3"
import "log"

func main() {
  app := fiber.New()

  // An example to describe the question

  log.Fatal(app.Listen(":3000"))
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
we have a thread for this
https://github.com/gofiber/template/issues/302#issuecomment-1762823206 


fiber and templ are completely independent

what is the expected usage here ?
(because you can use it like in other go frameworks)
