### ISSUE TITLE
📝 [Proposal]: Add support to create client from existing client

### ISSUE THREAD

**Issue by goriunov** [gofiber/fiber#3107]
### Feature Proposal Description

I believe there should be a way to pass custom fasthttp client in to the fiber http client, to allow more granular fine tuning by the users. 

### Alignment with Express API

---

### HTTP RFC Standards Compliance

---

### API Stability

---

### Feature Examples

```go
Naming can be improved but something along the lines:

cc := client.NewWithFasthttpClien(&fasthttp.Client{...})
```
```


### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have searched for existing issues that describe my proposal before opening this one.
- [X] I understand that a proposal that does not meet these guidelines may be closed without explanation.

**Comment by gaby** [comment]
@efectn Thoughts? Seems reasonable

**Comment by luk3skyw4lker** [comment]
Couldn't this also be achieved using an option within the existing New method? One option like `CustomFastHttpClient` or something that when omitted defaults to the internal Fiber fasthttp client. Not sure if this is good but just throwing ideas here

**Comment by mitulagr2** [comment]
I'll take this if you'd like!

**Comment by gaby** [comment]
@goriunov You mean a way to override this ? https://github.com/gofiber/fiber/blob/main/client/client.go#L36C2-L36C10

**Comment by efectn** [comment]
> I'll take this if you'd like!

Feel free to create a pull request. You can add new method called `NewWithFasthttpClient`

**Comment by mitulagr2** [comment]
Thanks! I'll start working on it.

**Comment by gaby** [comment]
@efectn `NewWithClient()` might be cleaner.
