### ISSUE TITLE
🐛 [Bug]: fiber prefork on windows

### ISSUE THREAD

**Issue by lorypelli** [gofiber/fiber#3111]
### Bug Description

it cause issue in the terminal

### How to Reproduce

Create a fiber http server with prefork enable and try to start it

### Expected Behavior

it should show fiber startup message, instead it starts to printing randoms things with randoms letters and numbers

### Fiber Version

2.52.5

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by lorypelli** [comment]
![image](https://github.com/user-attachments/assets/7f3f2b23-56f1-40e1-8c5d-13c0e1bf67d4)
![image](https://github.com/user-attachments/assets/572152c8-31e6-42c3-8684-13ce3eb21191)
![image](https://github.com/user-attachments/assets/33ca258a-b6b4-4564-8ee5-d1162023ece1)

**Comment by lorypelli** [comment]
without prefork it works as expected
https://github.com/lorypelli/server

**Comment by gaby** [comment]
Isnt prefork a Linux feature?

**Comment by lorypelli** [comment]
> Isnt prefork a Linux feature?

eh? On linux it doesn't seem to happen

**Comment by gaby** [comment]
@lorypelli Try a simple server with prefork and a GET router without using https://github.com/pterm/pterm

The weird text you are seeing is related to pterm not fiber

**Comment by lorypelli** [comment]
> @lorypelli Try a simple server with prefork and a GET router without using https://github.com/pterm/pterm
> 
> The weird text you are seeing is related to pterm not fiber

But why does it work without prefork enabled?

**Comment by gaby** [comment]
I'm not sure, prefork will run multiple processes using the same port. Maybe that affects pterm?

Try it without pterm first to confirm it works without it

**Comment by gaby** [comment]
@lorypelli Were you able to solve your issue?

**Comment by Skyenought** [comment]
![image](https://github.com/user-attachments/assets/faebc539-888e-4123-bd65-fb8d476577a5)
Actually it may be related to the encoding of your language, you can try something like utf-8.

This program runs on my windows terminal without any problems.

**Comment by lorypelli** [comment]
> ![image](https://github.com/user-attachments/assets/faebc539-888e-4123-bd65-fb8d476577a5)
> Actually it may be related to the encoding of your language, you can try something like utf-8.
> 
> This program runs on my windows terminal without any problems.

Is prefork enabled? If not, try enabling it

**Comment by Skyenought** [comment]
ok, i found my mistake

**Comment by gaby** [comment]
@lorypelli Was this issue solved for you?

**Comment by lorypelli** [comment]
> @lorypelli Was this issue solved for you?

I'm not using prefork as of right now, but I asked a question in the discord server in the `v2` channel about making a custom logger, could you please check and see if you could help?
Thanks
