### ISSUE TITLE
🤗 [Question]: How to populate right resource name when a middleware stops the request early?

### ISSUE THREAD

**Issue by andrii-korotkov-verkada** [gofiber/fiber#3112]
### Question Description

Hello,
I hope your day is going well.
I'm facing an issue with using Go Fiber middleware and Datadog metrics and trace integration. Say, the middleware terminates the request early and is called before another part of the request (e.g. rate limiting). The resolved part of the route is just /, and Datadog uses that to populate the resource name in both traces and metrics. So I don't see 429 error for the actual resource name that was called, but instead for the resource name just equal to /. I've tried to manually set the http.route tag in the middleware, but it didn't seem to work as I've hoped.
Do you know how to resolve this?

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by gaby** [comment]
@andrii-korotkov-verkada Please provide an example code of your middleware. That would help us find the issue

**Comment by andrii-korotkov-verkada** [comment]
A simplified version is
```
func TrafficRulesMiddleware(config Config) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		err := ApplyTrafficRules(
			ctx.UserContext(),
			strings.ToLower(ctx.Method())+"_"+ctx.Path(),
			config,
		)
		if err != nil {
			if span, ok := tracer.SpanFromContext(ctx.UserContext()); ok {
				// A workaround for resource name being "/" when throttling or rate limiting.
				// If handling paths with parameters in the future, may need to use normalized path.
				span.SetTag("http.route", ctx.Path())
			}
			return err
		}
		return ctx.Next()
	}
}
```

**Comment by gaby** [comment]
@andrii-korotkov-verkada Try using `ctx.Route().Path` instead of `ctx.Path()`

Another thing, you have to make copy of them since they will change on the next request.

```go
routePath := utils.CopyString(ctx.Route().Path)
```

Same for Method() and Path()

**Comment by andrii-korotkov-verkada** [comment]
Looks like `ctx.Route()` would not work and only show the currently resolved part of the route, not the full one https://docs.gofiber.io/api/ctx/#route. 
I'll try copying. Can request ctx be modified by other goroutines though?

**Comment by gaby** [comment]
Oh you want the full thing, keep in mind that will lead to high cardinality metric.

In that case try:

```go
string(ctx.Request().URI().Path())
```

You can't modify/pass the context to goroutines. Once your handler returns that context will be re-used by the engine.

**Comment by andrii-korotkov-verkada** [comment]
> Oh you want the full thing, keep in mind that will lead to high cardinality metric.
Yeah, I wanna avoid the high cardinality ideally, relying that my configured endpoints for traffic shedding might have wildcards in them (like `:uid`). So setting a route with the endpoint which I get from the traffic shedding rule overriding default resolved part would be ideal.

**Comment by gaby** [comment]
@andrii-korotkov-verkada Usually what I do is this

```go
routePath := ctx.Route().Path

if routePath == "/" {
    routePath = ctx.Path()
}
```

Try that

**Comment by andrii-korotkov-verkada** [comment]
The `routePath` would always fallback to `ctx.Path()` in my case, since middleware is expected to be used in the beginning of the request. I wonder whether something like this would work to override the resource name retrieved from Datadog:
```
ctx.Route().Path = limitingRoute  // can be retrieved from ApplyTrafficRules
```

**Comment by gaby** [comment]
That won't work, you cant override the context, they are reset/re-used by the engine.

What if you do this

```go
func TrafficRulesMiddleware(config Config) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		err := ApplyTrafficRules(
			ctx.UserContext(),
			strings.ToLower(ctx.Method())+"_"+ctx.Path(),
			config,
		)
		if err != nil {
                        err = ctx.Next()
			if span, ok := tracer.SpanFromContext(ctx.UserContext()); ok {
				// A workaround (that doesn't seem to work) for resource name being "/" when throttling or rate limiting.
				// If handling paths with parameters in the future, may need to use normalized path.
				span.SetTag("http.route", ctx.Route().Path)
			}
			return err
		}
		return err
	}
}
```

**Comment by andrii-korotkov-verkada** [comment]
Datadog uses `c.Route().Path` to set the tag after calling `c.Next()` ([link](https://github.com/DataDog/dd-trace-go/blob/6f8d5e90e94484d6e9534d477cffaadf24b866f5/contrib/gofiber/fiber.v2/fiber.go#L83)), that's why my previous attempt with directly setting `http.route` tag didn't work. I'll try to override `c.Route().Path` and see what happens, given it's in the same request and thread.

**Comment by gaby** [comment]
I'm not folllowing. In what order are your handlers defined in the App?

**Comment by andrii-korotkov-verkada** [comment]
So I may have something like
```
app.Use(TrafficRulesMiddleware(*config))
app.Get("/route1", s.HandleRoute1).Name("HandleRoute1")
app.Post("/route2/:id", s.HandleRoute2WithId).Name("HandleRoute2WithId")
```
I'm trying to get Datadog populate actual values of the normalized path like `/route1` or `/route2/:id` even if the middleware makes the request exit early (without executing route handlers).

**Comment by andrii-korotkov-verkada** [comment]
I've just confirmed that the approach with overriding `c.Route().Path` works.
