### ISSUE TITLE
🤗 [Question]: Validation with body and struct

### ISSUE THREAD

**Issue by redat00** [gofiber/fiber#3114]
### Question Description

Hi everyone ! 

I'm currently working on a new API and I want to use Fiber to do so.

There is one point where I'm struggling a little bit : Validation from body to struct. 

On the official documentation, there is an [example on how to do validation](https://docs.gofiber.io/guide/validation/), but it rely on the idea that you would use query parameters, rather than body. However in my case I want to validate data coming from a body.. 

I'm using the `ctx.Bind().Body(&struct)` syntax to do so currently. But the thing is that if it doesn't bind, I'm return the error, with the following syntax.

```go
err := ctx.Bind().Body(&struct)
if err != nil {
    return err
}
```

How would someone use validation with the `Bind()` method ? 

I'm starting to think that I might have to create my own `BindAndValidate` function, but maybe there is another solution that I'm missing. 

Thanks in advance for any help ! 

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
“Bind” means you are using our v3 version which is not yet fully stable
here is an example of how you can do this with it
https://docs.gofiber.io/next/api/bind#validation

in v2 I would follow the validation guide you already mentioned, there it doesn't matter where the data comes from

if you want to use the body there, use the bodyParser instead of the queryParser with the corresponding anotations if necessary

**Comment by redat00** [comment]
Hi ! 

Didn't even realise I was using the beta version, going through the documentation it seems like it's a really great new version with a lot of cool features, so thanks for the work ! 

Regarding my issue I was in fact able to do this really easily by adding a validator. Now everything's fine, I just need to work on some small issue. 

Thanks a lot for your answer !
