### ISSUE TITLE
📝 [Proposal]: Add support for CBOR codec

### ISSUE THREAD

**Issue by gaby** [gofiber/fiber#3156]
### Feature Proposal Description

Recently a user asked about support for `CBOR` similar to the other functions in the context object  `c.JSON(), c.JSONP(), and c.XML()`.

Several major projects in the industry already support `CBOR` and it's an official RFC.

### Alignment with Express API

N/a

### HTTP RFC Standards Compliance

RFC 8949 - https://www.rfc-editor.org/rfc/rfc8949.html

### API Stability

N/a

### Feature Examples

```go
The industry standard Golang implementation for using `CBOR` is this one: https://github.com/fxamacker/cbor
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have searched for existing issues that describe my proposal before opening this one.
- [X] I understand that a proposal that does not meet these guidelines may be closed without explanation.

**Comment by imsk17** [comment]
Hi, I would like to work on this one.
