### ISSUE TITLE
🐛 [Bug]: CORS Middleware, URL-protocol check too strict

### ISSUE THREAD

**Issue by aaronz-vipaso** [gofiber/fiber#3160]
### Bug Description

When I try to start my fiber application, which has a CORS origin configured with a protocol other than `http` or `https`, the application panics. 

Specifically, [KaiOS devices](https://kaios.dev/2023/04/security-and-privacy-on-kaios/) need to have a CORS origin configured with the protocol: `app://` 

--------

https://github.com/gofiber/fiber/blob/c86c3c0a30a87eba3ada305fc70162ea8c875a54/middleware/cors/cors.go#L49-L52

https://github.com/gofiber/fiber/blob/c86c3c0a30a87eba3ada305fc70162ea8c875a54/middleware/cors/utils.go#L34-L43

### How to Reproduce

1. Configure the origin `app://example.com` in the CORS middleware
2. Start fiber
3. -> App panics

### Expected Behavior

Do not panic, but allow origins with any protocol.

### Fiber Version

v2.52.5

### Code Snippet (optional)

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
)

func main() {
	app := fiber.New()

	app.Use(cors.New(cors.Config{
		AllowOrigins: "https://example.com, app://example.com",
	}))

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})

	app.Listen(":3000")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gaby** [comment]
I have to check the RFC to see which protocol schemes are allowed

**Comment by aaronz-vipaso** [comment]
@gaby 
The RFC of the `Origin` header ([RFC 6454: The Web Origin Concept](https://www.rfc-editor.org/rfc/rfc6454#section-7)) does not restrict the protocol (scheme).

The CORS protocol, in general, is not defined in an RFC but in the W3C recommendation titled ["Fetch standard" under 3.2](https://fetch.spec.whatwg.org/#http-cors-protocol). This one also doesn't restrict the protocol.
