### ISSUE TITLE
🤗 [Question]: Is there any way to log request id on handler?

### ISSUE THREAD

**Issue by gunb0s** [gofiber/fiber#3169]
### Question Description

i'm new to go fiber and develop with uber zap, fx.
The problem is i know how to log request id in middleware logger, But I made a another logger to use on handler and using it by dependency injection.
how can i log request id on second logger?

i guess that i can make a log function to accept `fiber context` as parameter, and extract request id from it, 
but I wish there were other options than this, like in middleware, which can be pre-set

### Code Snippet (optional)

```go
var Module = fx.Module(
	"external",
	fx.Provide(
		database.NewPostgres,
		logger.New,
	),
)

type External struct {
	fx.In

	Logger *logger.Sugared
	DB     *gorm.DB
}

type productService struct {
	ex external.External
}

func (s productService) GetAllProducts(c dto.GetAllProductParam) ([]model.Product, int, error) {
	var products []model.Product
	var count int64
	limit, offset := c.Limit, c.Offset
	queryResult := s.ex.DB.Scopes(database.Paginate(limit, offset)).Find(&products)
	queryResult = s.ex.DB.Model(&model.Product{}).Count(&count)
	
	s.ex.Logger.Printf("request Id needed")

	return products, int(count), queryResult.Error
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
you can use the https://docs.gofiber.io/contrib/fiberzap_v2.x.x/fiberzap/ for this

https://github.com/gofiber/contrib/blob/main/fiberzap/zap.go#L168

**Comment by gunb0s** [comment]
> you can use the https://docs.gofiber.io/contrib/fiberzap_v2.x.x/fiberzap/ for this
> 
> https://github.com/gofiber/contrib/blob/main/fiberzap/zap.go#L168

this way needs fiber context at every situation.. right?

**Comment by ReneWerner87** [comment]
yes as middleware it works directly with the fiber context

https://github.com/gofiber/contrib/blob/f4145f79af4e39b26515340bf92c879ccc350b4f/fiberzap/zap_test.go#L290-L308

the question is whether you need a req/res logger or just want to log additional information

the variant I have shown you is an independent middleware for logging the req/res data

**Comment by gunb0s** [comment]
> yes as middleware it works directly with the fiber context
> 
> https://github.com/gofiber/contrib/blob/f4145f79af4e39b26515340bf92c879ccc350b4f/fiberzap/zap_test.go#L290-L308
> 
> the question is whether you need a req/res logger or just want to log additional information
> 
> the variant I have shown you is an independent middleware for logging the req/res data

my question is about that i want to log additional information, not in req/res logger
like trace id, in opentelemetry

**Comment by ReneWerner87** [comment]
ok, how do you generate this requestID ? with the middleware?
https://docs.gofiber.io/api/middleware/requestid

**Comment by ReneWerner87** [comment]
you can always inject a middleware that logs this id or does other things
```go
	app.Use(func(c *fiber.Ctx) error {
        // log requestId
        log.Println("requestId:", c.Locals("requestId")) // requestId from the locals(context) object
        log.Println("requestId:", c.Get(fiber.HeaderXRequestID)) // requestId from the request header
        return c.Next()
    })
 ```

**Comment by gunb0s** [comment]
Instead of using middleware, if I want to log additional information in an API controller or service, do I always need the Fiber context to get the request ID? If that's the case, it feels inconvenient to pass the context to the logger each time like this:

```go
sugarLogger.With(
	zap.String("requestID", context.Get(fiber.HeaderXRequestID)),
).Infof("Printf-style logging with context: %s", "additional info")
```
I'm looking for a different approach because it seems cumbersome to log this way. The reason I want to implement this is to distinguish logs from the same request when multiple requests come in simultaneously.

**Comment by ReneWerner87** [comment]
all request and response information can be found in the fiber context
in order to access this information, it is necessary to use it
you can also extract this information and pass it on later or add it beforehand

```go
app.Use(func(c *fiber.Ctx) error {
		// extend and (TODO) store this logger
		zap.With(zap.String("requestId", c.Get(fiber.HeaderXRequestID)).Info("requestId"))
		return c.Next()
	})
```

**Comment by gunb0s** [comment]
I think this way is best for my situation, I'll try it thank you!!
