### ISSUE TITLE
📝 [Proposal]: Add Support for Context in RequestID Middleware

### ISSUE THREAD

**Issue by zhangyongding** [gofiber/fiber#3175]
Convenient to get the value of requestid from UserContext

```go
// New creates a new middleware handler
func New(config ...Config) fiber.Handler {
	// Set default config
	cfg := configDefault(config...)

	// Return new handler
	return func(c fiber.Ctx) error {
		// Don't execute middleware if Next returns true
		if cfg.Next != nil && cfg.Next(c) {
			return c.Next()
		}
		// Get id from request, else we generate one
		rid := c.Get(cfg.Header)
		if rid == "" {
			rid = cfg.Generator()
		}

		// Set new id to response header
		c.Set(cfg.Header, rid)

		// Add the request ID to locals
		c.Locals(requestIDKey, rid)

		// Add the request ID to UserContext
		ctx := context.WithValue(c.UserContext(), cfg.Header, rid)
		c.SetUserContext(ctx)

		// Continue stack
		return c.Next()
	}
}
```

### Alignment with Express API

N/a

### HTTP RFC Standards Compliance

N/a

### API Stability

N/a

### Feature Examples

```go
N/a
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have searched for existing issues that describe my proposal before opening this one.
- [X] I understand that a proposal that does not meet these guidelines may be closed without explanation.

**Comment by ReneWerner87** [comment]
can you describe what advantages it has over the value we already have in the locals?

**Comment by zhangyongding** [comment]
Helps to include RequestID when obtaining UserContext, hoping to still carry RequestID when using UserContext as context in some scenarios

**Comment by ReneWerner87** [comment]
what do you think we should expand the context in all middlewares where we also fill the locals? 
@gaby @efectn 

i wouldn't do it only in the requestid mw, because then it wouldn't be consistent

**Comment by JIeJaitt** [comment]
@ReneWerner87 @gaby @efectn I think requestid, keyauth, csrf, session middleware may need this function more, cache, compress, logger, limiter, favicon, pprof, recover, redirect, rewrite, etag, cors and helmet, idempotency, earlydata, encryptcookie may not be so need this function. Maybe we can add those with higher needs first.

**Comment by ReneWerner87** [comment]
ok can you support us with a PR

**Comment by JIeJaitt** [comment]
@ReneWerner87  I'm very happy to finish it. I will finish this PR in the next few days.

**Comment by ReneWerner87** [comment]
@coderabbitai create an issue report for the other middlewares with a task list to check off
