### ISSUE TITLE
🧹 [Maintenance]: Add a straightforward approach for accessing response headers in *fiber.Agent

### ISSUE THREAD

**Issue by xehrad** [gofiber/fiber#3184]
### Maintenance Task Description

Hello, Fiber team!

I’d like to propose a feature enhancement for Fiber’s *fiber.Agent. Currently, retrieving response headers requires extra steps that feel more complex than necessary, especially when compared to Go’s standard net/http package.

## Current Situation
To access response headers, we need to manually set up the request and then access headers from the Response() object by iterating over them, which can be cumbersome. For example:
``` go
agent := app.AcquireAgent()
req := agent.Request()
req.Header.SetMethod(fiber.MethodGet)
req.SetRequestURI("https://example.com")

if err := agent.Do(req); err != nil {
	log.Fatal(err)
}

resp := req.Response()
resp.Header.VisitAll(func(key, value []byte) {
	fmt.Printf("%s: %s\n", string(key), string(value))
})
```

## Proposed Solution
Could we add a more direct and intuitive method to access response headers directly from *fiber.Agent? For example:

``` go
agent := fiber.Get("<URL>")
resp, body, errs := agent.Bytes()
for key, value := range resp.GetRespHeaders() {
	fmt.Printf("%s: %s\n", key, value)
}

fmt.Printf("status: %s\n", resp.statusCode())
```

## Benefits
- Improved Developer Experience: Simplifies code for basic use cases, making it easier for developers to retrieve headers without extra setup.
- Consistency with Go’s Standard Library: Aligns more closely with net/http, making the transition easier for those new to Fiber.

Thank you for considering this feature! It would make working with *fiber.Agent more intuitive and developer-friendly.

### Checklist:

- [X] I have confirmed that this maintenance task is currently not being addressed.
- [X] I understand that this task will be evaluated by the maintainers and prioritized accordingly.
- [X] I am available to provide further information if needed.

**Comment by gaby** [comment]
@efectn Maybe for v3 we should make the functions have the same naming convention as net/http?

**Comment by TusharMohapatra07** [comment]
This seems like an interesting thing to work on ! Can i look into this ? It's my first time trying something like this so i might need some help.

**Comment by TusharMohapatra07** [comment]
Hey, so you want to implement this from scratch or just implement new functions that does the same thing that you've mentioned (in current situation section) under the hood.

**Comment by gaby** [comment]
@TusharMohapatra07 We already have this functionality in `v3`. We are not adding any new features to `v2` at the moment, only bug fixes.

On the other hand, it might be worth revisiting the names of the functions for the `v3` client.

**Comment by efectn** [comment]
> @efectn Maybe for v3 we should make the functions have the same naming convention as net/http?

Yes we can do it for better naming convention

**Comment by VincentK-ZA** [comment]
As this was one of the results I stumbled on when searching for this, I just wanted to add my solution for accessing response headers using `*fiber.Agent`'s [SetResponse](https://docs.gofiber.io/api/client#setresponse)

```go
agent := fiber.Get("https://example.com")

// Acquire a response object to store the result
resp := fiber.AcquireResponse()
agent.SetResponse(resp)

statusCode, body, errs := agent.Bytes()

location := resp.Header.Peek(fiber.HeaderLocation)
fmt.Println("Location: ", string(location))
```
