### ISSUE TITLE
🐛 [Bug]: Automatic Content Type

### ISSUE THREAD

**Issue by lorypelli** [gofiber/fiber#3187]
### Bug Description

Using `app.Static` automatically adds `Content-Type` to file response

### How to Reproduce

Create server with a static directory

### Expected Behavior

It shouldn't do this because it's often wrong, like `go.mod` gets threated as `video/mpeg` file

### Fiber Version

2.52.5

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by gaby** [comment]
@lorypelli We rely on fasthttp for `content-type`. It checks first if the file has a header, else it checks the file extension.

The `.mod` extension is a media extension related to audio/video.

**Comment by lorypelli** [comment]
> @lorypelli We rely on fasthttp for `content-type`. It checks first if the file has a header, else it checks the file extension.
> 
> The `.mod` extension is a media extension related to audio/video.

How can I disable it?

**Comment by ReneWerner87** [comment]
This cannot be deactivated, each file should have a content type
This is determined by fasthttp, usually with standard golang functionalities
However, you can set this manually for various extensions, we already had an issue report for this somewhere before

**Comment by ReneWerner87** [comment]
You can use the ModifyResponse handler for this
https://docs.gofiber.io/api/app#static

**Comment by lorypelli** [comment]
> You can use the ModifyResponse handler for this
> https://docs.gofiber.io/api/app#static 

Thanks, it works, now I'm wonder how is it possible that another webserver even without that header, the browser knows that a `.json` file is a json file type (it doesn't have `Content-Type` as I said)

**Comment by gaby** [comment]
> > You can use the ModifyResponse handler for this
> > https://docs.gofiber.io/api/app#static
> 
> Thanks, it works, now I'm wonder how is it possible that another webserver even without that header, the browser knows that a `.json` file is a json file type (it doesn't have `Content-Type` as I said)

Either by mapping file extension to content type or by reading the file header

**Comment by gaby** [comment]
@lorypelli FastHTTP is already doing 3 separate checks. Anything further requires using an external library. It does the following three checks:

- Check context type by file extension
- Read file header to detect type
- Use golang http.DetectContentType

You can see the code here: https://github.com/valyala/fasthttp/blob/master/fs.go#L1535

That's as good as it gets using native Golang without third-party libraries.

**Comment by lorypelli** [comment]
> @lorypelli FastHTTP is already doing 3 separate checks. Anything further requires using an external library. It does the following three checks:
> 
> * Check context type by file extension
> * Read file header to detect type
> * Use golang http.DetectContentType
> 
> You can see the code here: https://github.com/valyala/fasthttp/blob/master/fs.go#L1535
> 
> That's as good as it gets using native Golang without third-party libraries.

Ok, but vercel http server doesn't add `Content-Type` and even without it in the response the browser detects correct file type

**Comment by ReneWerner87** [comment]
every GET response should include the content-type everything else is bad practice and should be avoided

of course the response still works correctly in some browsers because they have an automatic recognition based on the filename or content
but I would not rely on this, as it can vary from browser to browser

**Comment by lorypelli** [comment]
ok, I tried using a third part library but it wasn't working properly so I removed it, and I'm using default `Content-Type` detection by fiber, the problem is that it isn't checking file content and the library I was using was doing it, not every `mod` or `ts` file is a video...
