### ISSUE TITLE
🐛 [Bug]: Caching static assets

### ISSUE THREAD

**Issue by lorypelli** [gofiber/fiber#3188]
### Bug Description

The browser cache assets and I don't know how to fix

### How to Reproduce

Create server with a static directory

### Expected Behavior

To prevent caching I added a `t` url query param that contains the current unix seconds time

### Fiber Version

2.52.5

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by lorypelli** [comment]
Is there a better way to fix?

**Comment by gaby** [comment]
@lorypelli This is explained in the docs: https://docs.gofiber.io/api/app/#static

```go
// Custom config
app.Static("/", "./public", fiber.Static{
  CacheDuration: -1,
})
```
