### ISSUE TITLE
Hosting two services on the same IP and port

### ISSUE THREAD

**Issue by lorypelli** [gofiber/fiber#3189]
### Bug Description

If I run two instances on a server on the local network IP (192.168.1.9) and same port without a check if it's used, one overwrite the other, but this doesn't happen with 127.0.0.1

### How to Reproduce

Start webserver on local network ip on the same port

### Expected Behavior

It should say port already in use

### Fiber Version

2.52.5

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by ReneWerner87** [comment]
This is normal behavior of web servers, you should use different ip addresses on the same host 
Or use an orchestration system like kubernetes which can use other services on other routes

**Comment by gaby** [comment]
@lorypelli How are you creating your server. You have opened multiple issues on GitHub with 0 code.

**Comment by lorypelli** [comment]
> @lorypelli How are you creating your server. You have opened multiple issues on GitHub with 0 code.

https://github.com/lorypelli/server, also I have trouble if module name is `github.com/lorypelli/server` because it tries to fetch local packages with `go mod tidy`, you can see in actions run

**Comment by ReneWerner87** [comment]
https://github.com/lorypelli/server/blob/5caa05079a98dc009a5e19f68b82e572d86f5b4d/cmd/server/main.go#L57-L60

as we said before, you should not start 2 servers on the same port
this does not work in any other framework

the websocket middleware can be started on the other server and used with a different route

**Comment by lorypelli** [comment]
> https://github.com/lorypelli/server/blob/5caa05079a98dc009a5e19f68b82e572d86f5b4d/cmd/server/main.go#L57-L60
> 
> as we said before, you should not start 2 servers on the same port this does not work in any other framework
> 
> the websocket middleware can be started on the other server and used with a different route

When I said this I wasn't referring to the websocket instance because that one is on a different port you CAN'T use in the main instance so the problem doesn't appear, ok, don't mind, are you able to answer to the other question?
