### ISSUE TITLE
🤔How to add server timing header

### ISSUE THREAD

**Issue by WLun001** [gofiber/fiber#319]
**Question description**
How to attach [server timing](https://w3c.github.io/server-timing/) at response? Need a custom middleware for that?

**Comment by Fenny** [comment]
You mean you want to record the latency / duration / timing of a request?
```go
package main

import (
  "log"
  "time"

  "github.com/gofiber/fiber"
)

func main() {
  app := fiber.New()

  app.Use(Timer())

  app.Get("/", func(c *fiber.Ctx) {
    time.Sleep(2 * time.Second)
  })

  app.Listen(3000)
}

// Timer will measure how long it takes before a response is returned
func Timer() func(*fiber.Ctx) {
  return func(c *fiber.Ctx) {
    // start timer
    start := time.Now()
    // next routes
    c.Next()
    // stop timer
    stop := time.Now()
    // Do something with response
    log.Println("Request took ", stop.Sub(start).String())
  }
}
```
`2020/04/29 05:01:13 Request took  2.0000487s`

**Comment by WLun001** [comment]
@Fenny , yes something like this. But want it to be attached to return response header. Not sure that's possible

**Comment by Fenny** [comment]
Awesome! I suggest using the `c.Set` method
```go
c.Set("Server-Timing", fmt.Sprintf("app;dur=%v", stop.Sub(start).String()))
```

**Comment by WLun001** [comment]
@Fenny any reason use `c.Set` over `c.Append` ?

**Comment by Fenny** [comment]
@WLun001 
https://docs.gofiber.io/context#append
Appends the specified value to the HTTP response header field.

https://docs.gofiber.io/context#set
Sets the response’s HTTP header field to the specified key, value.
