### ISSUE TITLE
🐛 [Bug]: BodyParser doesn't parse form values to map

### ISSUE THREAD

**Issue by sujit-baniya** [gofiber/fiber#3216]
### Bug Description

When trying to parse a form data to map, I'm getting an error `schema: interface must be a pointer to struct`

https://youtu.be/XnhXTXW8JmM

### How to Reproduce

```go
package main

import (
	"bytes"
	"errors"
	"net/url"
	"reflect"
	
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	
	app.Post("/", func(ctx *fiber.Ctx) error {
		var data map[string]any
		err := ctx.BodyParser(&data)
		if err != nil {
			return err
		}
		return ctx.JSON(data)
	})
	app.Listen(":8081")
}
```

```curl
curl -X POST http://localhost:8081 \
-H "Content-Type: application/x-www-form-urlencoded" \
-d "method=GET&path=/user/:id&handlerMsg=User Profile"


```

### Expected Behavior

It should have worked with map, struct or slice

### Fiber Version

v2.52.5

### Code Snippet (optional)

```go
package main

import (
	"bytes"
	"errors"
	"net/url"
	"reflect"
	
	"github.com/gofiber/fiber/v2"
)

func main() {
	app := fiber.New()
	
	app.Post("/", func(ctx *fiber.Ctx) error {
		var data map[string]any
		err := ctx.BodyParser(&data)
		if err != nil {
			return err
		}
		return ctx.JSON(data)
	})
	app.Listen(":8081")
}
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my problem prior to opening this one.
- [X] I understand that improperly formatted bug reports may be closed without explanation.

**Comment by klikpaspor** [comment]
> ```go
> var data map[string]any
> ```

Maybe you have change `var data map[string]any` to `var data map[string]interface{}`

**Comment by sujit-baniya** [comment]
@klikpaspor  It's same for both

**Comment by ksw2000** [comment]
This is not a bug.

https://github.com/gofiber/fiber/blob/6968d51d0dc990f60541536423cc7898b387bae4/ctx.go#L373-L378

See the first line comment of BodyParser:

> BodyParser binds the request body <mark>to a struct</mark>

**Example:**

```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

type binder struct {
	Method     string `json:"method"`
	Path       string `json:"path"`
	HandlerMsg string `json:"handlerMsg"`
}

func main() {
	app := fiber.New()

	app.Post("/", func(ctx *fiber.Ctx) error {
		var data binder
		err := ctx.BodyParser(&data)
		if err != nil {
			return err
		}
		return ctx.JSON(data)
	})
	app.Listen(":8081")
}
```

```sh
$ curl -X POST http://localhost:8081 -H "Content-Type: application/x-www-form-urlencoded" -d "method=GET&path=/user/:id&handlerMsg=User Profile"
{"method":"GET","path":"/user/:id","handlerMsg":"User Profile"}
```

**Comment by ksw2000** [comment]
Besides, `ctx.BodyParser` has been improved in fiber v3. https://github.com/gofiber/fiber/commit/eacde70294be2ca277f6125e62cc1ea04907f2e3

In version v3, it is possible to bind to a map.

https://github.com/gofiber/fiber/blob/ff55cfd7c707a3c74e673bd205d3dd251b1623d4/ctx.go#L1857-L1868

**Comment by sujit-baniya** [comment]
@ksw2000  I see that it's limited to struct. Shouldn't the version (v2) support map parsing as well?
How would I parse data to map as current BodyParser would not work for map?

At the moment, I've to introduce a custom parser using `BodyRaw()` or `Body()`

**Comment by efectn** [comment]
> @ksw2000 I see that it's limited to struct. Shouldn't the version (v2) support map parsing as well? How would I parse data to map as current BodyParser would not work for map?
> 
> At the moment, I've to introduce a custom parser using `BodyRaw()` or `Body()`

Hi @sujit-baniya we don't plan to provide new features for v2. We will only provide bugfixes
