### ISSUE TITLE
🤗 [Question]: bodyParser nested with bracket notation

### ISSUE THREAD

**Issue by adriancmiranda** [gofiber/fiber#3223]
### Question Description

Hi everyone, hope you're doing well!

I'm trying to work with some fields from a form-data request in Go, with the following example structure:

```md
text_prompts[0][text]: "A beautiful sunset over the ocean"
text_prompts[0][weight]: 0.7
text_prompts[1][text]: "mountain range covered in snow"
text_prompts[1][weight]: -0.5
init_image: /path/to/image.jpg
```

When trying to parse these values into a struct, I notice that the `TextPrompts` field is coming as `null`. I did some research and found references to other libraries in discussions here in the repository. My question is: does Fiber handle this kind of form-data request natively, or do I need to add an external library specifically for this?

### Code Snippet (optional)

```go
package main

import "github.com/gofiber/fiber/v2"
import "log"

type TextPrompt struct {
	Text   string  `form:"text" json:"text"`
	Weight float64 `form:"weight" json:"weight"`
}

type Request struct {
	InitImage   string       `form:"init_image" json:"init_image"`
	TextPrompts []TextPrompt `form:"text_prompts" json:"text_prompts"`
}

func main() {
	app := fiber.New()

	app.Post("/v1/generation/:engine_id/image-to-image", func(ctx *fiber.Ctx) error {
		request := Request{}
		if err := ctx.BodyParser(&request); err != nil {
			return ctx.Status(fiber.StatusUnprocessableEntity).JSON(fiber.Map{
				"code":  fiber.StatusUnprocessableEntity,
				"error": err.Error(),
			})
		}
		return ctx.Status(fiber.StatusOK).JSON(fiber.Map{
			"info": request,
		})
	})

	log.Fatal(app.Listen(":3000"))
}
```

**EDIT:**

> multipart/form-data

```sh
curl --request POST \
  --url 'http://0.0.0.0:3000/v1/generation/sxi/image-to-image' \
  --header 'accept: application/json; charset=utf-8' \
  --header 'content-type: multipart/form-data' \
  --form 'text_prompts[0][text]=A lighthouse on a cliff' \
  --form 'text_prompts[0][weight]=0.5' \
  --form 'text_prompts[1][text]=land, ground, dirt, grass' \
  --form 'text_prompts[1][weight]=-0.9' \
  --form init_image=static/assets/sd.jpg
```

> application/x-www-form-urlencoded

```sh
curl --request POST \
  --url 'http://0.0.0.0:3000/v1/generation/sxi/image-to-image' \
  --header 'accept: application/json; charset=utf-8' \
  --header 'content-type: application/x-www-form-urlencoded' \
  --form 'text_prompts[0][text]=A lighthouse on a cliff' \
  --form 'text_prompts[0][weight]=0.5' \
  --form 'text_prompts[1][text]=land, ground, dirt, grass' \
  --form 'text_prompts[1][weight]=-0.9' \
  --form init_image=static/assets/sd.jpg
```

### Checklist:

- [X] I agree to follow Fiber's [Code of Conduct](https://github.com/gofiber/fiber/blob/master/.github/CODE_OF_CONDUCT.md).
- [X] I have checked for existing issues that describe my questions prior to opening this one.
- [X] I understand that improperly formatted questions may be closed without explanation.

**Comment by ReneWerner87** [comment]
@adriancmiranda pls share a curl request for this problem

**Comment by ReneWerner87** [comment]
with "Content-Type: application/x-www-form-urlencoded" it is working
https://github.com/gofiber/fiber/blob/8c84b0fd8a07537572e607057b309681922a0b46/ctx.go#L394-L408

but not with mulitformpart
https://github.com/gofiber/fiber/blob/8c84b0fd8a07537572e607057b309681922a0b46/ctx.go#L422-L427

**Comment by ReneWerner87** [comment]
@coderabbitai create a feature request for the support of square brackets in muliformpart data, so that all features of the normal formdata (i.e. also the separation by comma) are possible in muliformpart data + the transfer of binary data

**Comment by efectn** [comment]
Will work on it this one.

**Comment by ReneWerner87** [comment]
we released a fix with that in [v2](https://github.com/gofiber/fiber/releases/tag/v2.52.6) and [v3](https://github.com/gofiber/fiber/releases/tag/v3.0.0-beta.4)
