### ISSUE TITLE
Suggestion: Rename AddData and AddDatas for clarity

### ISSUE THREAD

**Issue by ksw2000** [gofiber/fiber#3251]
I suggest renaming `AddData` to `AddItem` and `AddDatas` to `AddItems`. The word "data" is already plural, so `datas` is not a standard word in English. Adding an `-s` is grammatically incorrect.

The word **data** comes from Latin, where:
+ **Datum** is the singular form, meaning "a given fact" or "a single piece of information."
+ **Data** is the plural form, referring to multiple facts or pieces of information.

so `AddDatas` is redundant and may cause confusion. `AddItem` and `AddItems` would be clearer and more consistent with common naming conventions.

In `client/request.go`

+ `func (r *Request) AddFormData` → `func (r *Request) AddFormItem`
+ `func (r *Request) AddFormDatas` → `func (r *Request) AddFormItems`
+ `func (r *Request) SetFormData` → `func (r *Request) SetFormItem`
+ `func (r *Request) SetFormDatas` → `func (r *Request) SetFormItems`
+ `func (r *Request) SetFormDatasWithStruct` → `func (r *Request) SetFormItemsWithStruct`
+ `func (r *Request) DelFormDatas` → `func (r *Request) DelFormItems`
+ `func (f *FormData) AddDatas` → `func (f *FormData) AddItemss`
+ `func (f *FormData) SetDatas` → `func (f *FormData) SetItemss`
+ `func (f *FormData) SetDatasWithStruct` → `func (f *FormData) SetItemsWithStruct`
+ `func (f *FormData) DelDatas` → `func (f *FormData) DelItems`

**Comment by gaby** [comment]
@ksw2000 This was already in the to-do list. We had discussed it and forgot to change it during the merge request.

**Comment by ksw2000** [comment]
@gaby Can I create a pull request to rename these functions?

**Comment by ReneWerner87** [comment]
Yeah its ok

**Comment by ReneWerner87** [comment]
@ksw2000 in english the plural of data is already data
can you adjust the current code again so that this is correct in english and a possible difference is recognizable

thx to @sixcolors for pointing this
