### ISSUE TITLE
🤔 Chain middlewares possible?

### ISSUE THREAD

**Issue by datvt9312** [gofiber/fiber#326]
In express.js, I can chain middlewares for a single route, ie. adding middleware 1, middleware 2, and cors, by doing this:

app.get("/greeting", middleware1, middleware2, cors, (req, res, next) => {
  res.send({
        success: true
    })
});

can we implement this feature in fiber?

**Comment by Fenny** [comment]
@datvt9312, this is already implemented :smile: 
```go
app.Get("/hello", mw, mw2, handler)
```
