### ISSUE TITLE
🤔 ctx.QueryMulti

### ISSUE THREAD

**Issue by FriendlyUser** [gofiber/fiber#328]
**Fiber version/commit**
v1.9.3
**Issue description**
Can't use ctx.QueryMulti to get an query parameter array as a list of strings.

When copying the code over from the PR #288 in my local project, it worked fine.
**Expected behavior**

ctx.QueryMulti should exist on v1.9.3
**Steps to reproduce**
Try adding ctx.QueryMulti, this function was not available at 

Do not see ctx.QueryMulti in the source code from [latest master commit](https://github.com/gofiber/fiber/blob/27a7b21716154e0c3fd4afbf1a31896994fec4f5/ctx.go#L658) and the pull request merged in #288 implies it was merged in.
**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  // ..
  app.Get("/", func(c *fiber.Ctx) {
    c.QueryMulti("test") // this should bring up an error
  })
}
```

**Comment by Fenny** [comment]
Hi @FriendlyUser, welcome to Fiber. We didn't merge `ctx.QueryMulti`, explained [here](https://github.com/gofiber/fiber/pull/288#issuecomment-618739905). The [latest master commit](https://github.com/gofiber/fiber/blob/27a7b21716154e0c3fd4afbf1a31896994fec4f5/ctx.go#L658) points to the [ctx.Query](https://docs.gofiber.io/context#query) function.
