### ISSUE TITLE
🐞 Error when parsing .jade template layout

### ISSUE THREAD

**Issue by datvt9312** [gofiber/fiber#330]
**Fiber version/commit**
v1.9.3
**Issue description**
Error when parsing .jade template layout
**Expected behavior**
Can parse .jade template to HTML and return correctly to client
**Steps to reproduce**
1. Config application with Pug as HTML template
```golang
package main

import (
	"gofiber/starter/routes"

	"github.com/gofiber/fiber"
	"github.com/gofiber/logger"
	"github.com/gofiber/template"
)

func main() {
	app := fiber.New()

	app.Settings.TemplateFolder = "./views"
	app.Settings.TemplateEngine = template.Pug()
	app.Settings.TemplateExtension = ".jade"

	app.Use(logger.New())

	app.Static("/", "./public")

	routes.SetupIndexRouter(app.Group("/"))
	routes.SetupUsersRouter(app.Group("/users"))

	app.Use("/*", func(c *fiber.Ctx) {
		bind := fiber.Map{
			"title":   "Page not found",
			"message": "Page not found",
			"error": map[string]interface{}{
				"status": 400,
				"stack":  "",
			},
		}
		if err := c.Render("./error", bind); err != nil {
			c.Status(500).Send(err.Error())
		}
	})

	app.Listen(3000)
}

```
2. Create a .jade file
```jade
doctype html
html
  head
    title= title
    link(rel='stylesheet', href='/stylesheets/style.css')
  body
    block content

```
3. Go to the page -> Error announce that ```golang template: :1: function "title" not defined```

**Code snippet**
```golang
app.Use("/*", func(c *fiber.Ctx) {
		bind := fiber.Map{
			"title":   "Page not found",
			"message": "Page not found",
			"error": map[string]interface{}{
				"status": 400,
				"stack":  "",
			},
		}
		if err := c.Render("./error", bind); err != nil {
			c.Status(500).Send(err.Error())
		}
	})
```

my folder structure
<img width="318" alt="Screen Shot 2020-04-30 at 13 06 22" src="https://user-images.githubusercontent.com/36273288/80743907-6c746c80-8ae3-11ea-931e-4218252f5e52.png">

the error start from here
<img width="741" alt="Screen Shot 2020-04-30 at 13 01 10" src="https://user-images.githubusercontent.com/36273288/80743940-81510000-8ae3-11ea-9266-aef9798cde10.png">

**Comment by Fenny** [comment]
@datvt9312 thanks for submitting a detailed bug report. I can confirm that Jade is indeed broken 😢 We are going to change the way we render templates in Fiber. I opened an discussion that relates to multiple issues including this one, if you have any ideas or feedback please post them here https://github.com/gofiber/fiber/issues/331
