### ISSUE TITLE
🔥 Guidelines for creating Middleware

### ISSUE THREAD

**Issue by ssimk0** [gofiber/fiber#338]
**Is your feature request related to a problem?**
I want create some custom middleware, I try recreated it by look at the existing middleware but it's little bit hard and I don't found any docs around that how it works.

**Describe the solution you'd like**
I would like see small docs section around the middleware and also usage only for one route only

**Comment by Fenny** [comment]
Hi @ssimk0, sorry for the late reply. I think this is a great idea!

Having documented guidelines for creating middleware packages ensures that all third-party contributions are consistent.

Guidelines:
- Third party repo's should start with `fiber-` i.e.: `fiber-session`
- It must contain a [Config](https://github.com/gofiber/requestid/blob/master/main.go#L15)
- Initialization should always be named [New](https://github.com/gofiber/requestid/blob/master/main.go#L27)
- When possible, providing a Config into New should be optional.

Feel free to comment idea's or suggestions so we could get this done asap.

References:
- [gofiber/compression](https://github.com/gofiber/compression)
- [gofiber/basicauth](https://github.com/gofiber/basicauth)
- [gofiber/requestid](https://github.com/gofiber/requestid)
- [gofiber/websocket](https://github.com/gofiber/websocket)
- [gofiber/keyauth](https://github.com/gofiber/keyauth)
- [gofiber/rewrite](https://github.com/gofiber/rewrite)
- [gofiber/recover](https://github.com/gofiber/recover)
- [gofiber/limiter](https://github.com/gofiber/limiter)
- [gofiber/session](https://github.com/gofiber/session)
- [gofiber/adaptor](https://github.com/gofiber/adaptor)
- [gofiber/logger](https://github.com/gofiber/logger)
- [gofiber/helmet](https://github.com/gofiber/helmet)
- [gofiber/embed](https://github.com/gofiber/embed)
- [gofiber/pprof](https://github.com/gofiber/pprof)
- [gofiber/cors](https://github.com/gofiber/cors)
- [gofiber/csrf](https://github.com/gofiber/csrf)
- [gofiber/jwt](https://github.com/gofiber/jwt)

**Comment by ssimk0** [comment]
Hi, @Fenny thanks for your answer I will look at it :), only my question is should I use `Filter func(*fiber.Ctx) bool` for example to filter HTTP methods on which should middleware apply? I use for example JWT middleware but all get requests should be public and you can post/put/delete only with token then I use:
```
func Filter(c *fiber.Ctx) bool {
	return c.Method() == "GET"
}
```

This is how you think about these ?

**Comment by thomasvvugt** [comment]
You can use the Filter function to skip a middleware from being executed. It has `fiber.Ctx` as a parameter to do logic with.
Fiber uses the `Filter` func in the following way;
```go
if cfg.Filter != nil && cfg.Filter(c) {
    c.Next()
    return
}
```
So, in your example this would mean that the specified middleware would skip all requests with the HTTP Method `GET` as the `Filter` func would return `true`.
Let me know if that helps you out!

**Comment by koddr** [comment]
⭐ Wish: try to cover the code with 100% tests at once. 

> This will help future Fiber generations to write supported code for its middlewares at once looking at your references.

**Comment by Fenny** [comment]
@ssimk0, I hope @thomasvvugt answered your question.
We could also discuss to use `cfg.Before` & `cfg.After` where `Before` will have the same behaviour like the current `Filter` and `After` will execute after all routes are handled ( end of the request ).

**Comment by ssimk0** [comment]
@Fenny @thatzacdavis yours answers help a lot. Thank you :)

**Comment by Fenny** [comment]
I think that people can create their own middleware design because Fiber is really flexible, in my opinion, diversity could lead to better design. Therefore we could always correct/review third-party middleware applications.

I'm closing this issue for now but feel free to re-open! Thanks @ssimk0

**Comment by johndiego** [comment]
@Fenny  you have complete code with references import ? I'm using v2
```
func main() {
	app := fiber.New()
	// Dummy middleware
	cfg := middleware.Config{
		// Same as Filter but without bool, need to call c.Next
		Before: func(c *fiber.Ctx) {
			if c.Method() == fiber.MethodGET {
				c.Next()
			}
		},
		// This handler gets called as last
		After: func(c *fiber.Ctx) {
			if c.Fasthttp.Response.Header.Get("X-Demo") != "Success" {
				c.SendStatus(fiber.StatusBadRequest)
			}
		}
	},

	app.Use(middleware.New(cfg))
	app.Get("/", func(c *fiber.Ctx) {
		c.Set("X-Demo", "Success")
	})

	app.Listen(3000)
}
```

**Comment by ReneWerner87** [comment]
Here is an example in the docs https://docs.gofiber.io/guide/routing#middleware

Or you just check the code of our over 20 core middlewares

https://github.com/gofiber/fiber/blob/master/middleware/compress/compress.go#L55
https://github.com/gofiber/fiber/blob/master/middleware/requestid/requestid.go
