### ISSUE TITLE
🤔 app.Static serving JS as text/plain

### ISSUE THREAD

**Issue by fhammoud** [gofiber/fiber#352]
**Question description**
I'm not sure if this is a bug or if I'm doing this wrong, but I created an Angular 9 app to be served by my Fiber app. The Angular app compiles the output to /public. When I add the app.Static middleware I can see that all my angular files have been sent but the JS files have the mime-type text/plain instead of application/javascript, and so the browser is throwing an error: "Failed to load module script: The server responded with a non-JavaScript MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec."

**Code snippet (optional)**

```go
package main

import (
	"fmt"
	"github.com/gofiber/fiber"
	"github.com/gofiber/logger"

	"fiber/api/car"
)

func main() {
        app := fiber.New()

        // Add middleware
	app.Use(logger.New())

	// Serve static files
	app.Static("/", "./public")

	// Setup routes
	car.Routes(app)

	// Start Fiber server
	err := app.Listen(8080)
	if err != nil {
		fmt.Print("Failed to start server")
	}
}
```

**Comment by Fenny** [comment]
What OS are you using and do the javascript files have the `.js` extension?

**Comment by fhammoud** [comment]
I'm on Windows 10, and yes they do have .js extension. They're the typical Angular app files if you're familiar with Angular.
![image](https://user-images.githubusercontent.com/10720157/81505654-b6104480-92a5-11ea-9de3-27a31aa2bd68.png)

**Comment by fhammoud** [comment]
@thomasvvugt Helped me with this. The issue was wrong `Content Type` defined for `.js` in the Windows registry.
In case anyone else sees this, open regedit, go to HKEY_LOCAL_MACHINE > SOFTWARE > Classes > .js (or any other file extension you need). Then modify the Content Type field.

**Comment by thomasvvugt** [comment]
Issue is open on Go itself as well.
See https://github.com/golang/go/issues/32350
