### ISSUE TITLE
🔥 Middleware execution order

### ISSUE THREAD

**Issue by pot-code** [gofiber/fiber#357]
**Is your feature request related to a problem?**
I know that the execution priority of middleware is the same with normal route, but I have used a dependency injection tool and I have to register controller routes before  middlewares, thus all of the middlewares will be useless.

**Describe the solution you'd like**
increase the priority of middleware

**Describe alternatives you've considered**
Like other popular web frameworks

**Additional context**
code snippet:

```go
func main() {
	app := fiber.New()
	cfg := config.ParseConfig("configs/config.yml")
	logger, err := service.GetZapLogger(cfg)

	if err != nil {
		log.Fatal(err)
	}
	defer logger.Sync()

	app.Use(controller.LoggingMiddleware(logger))
	dic := injection.NewDIContainer()
	dic.Register(app)
	dic.Register(cfg)
	dic.Register(logger)
	dic.Register(validator.New())
	dic.Register(new(controller.JWTMiddleware))
	dic.Register(new(controller.EchoController))
	dic.Register(new(controller.LoginController))
	if err := dic.Populate(); err != nil { // initialization order is uncertain
		log.Fatal(err)
	}

	uncheckedJm, _ := dic.Get(controller.JWTMiddleware{})
	jm := uncheckedJm.(*controller.JWTMiddleware)
        // wasted middlewares
	app.Use(controller.CORSMiddleware)
	app.Use(jm.ErrorHandlingMiddleware)
	app.Use(jm.ValidateMiddleware)
	app.Use(jm.RefreshTokenMiddleware)

	port := cfg.Server.Port
	if err := app.Listen(":" + strconv.Itoa(port)); err != nil {
		log.Fatal(err)
	}
}
```

The injection tool will call the pre-defined `Constructor` method of the registered component, like:

```go
// user.go - LoginController
func (lc LoginController) Constructor() *LoginController {
	app := lc.App // instance of fiber app registered in main()
	app.Post("/api/login", lc.handleLogin)
	app.Post("/api/register", lc.handleRegister)
	return &lc
}
```

The point is to avoid massive route registration statement in main function, so I can simply register them in the belonging controller, and it should be easy for management.

While some middlewares(like `JWTMiddleware`) have its own dependencies, they will go in the same initialization process with controllers, and I have no way to control the order.

This is a very particular issue, I won't expect a huge change of the the architecture, but I don't want to replace the fiber framework, so is there any workarounds?

**Comment by Fenny** [comment]
Thank your for your detailed issues @pot-code.
We cannot change the priority due to design, it would break compatibility.

Every route could be considered as a "Middleware" but using the "Use" method allows you to match path prefixes and any HTTP method. Maybe you could assign the path prefixes to your middleware to the routes it should apply too. 

```go
// Match requests starting with /api/
app.Use("/api/", mw)
app.Post("/api/login", lc.handleLogin)
app.Post("/api/register", lc.handleRegister)

// Match any request 
app.Use(mw)
app.Get("/api/logout", lc.handleLogout)

```

**Comment by pot-code** [comment]
Better go change my code, close the issue
