### ISSUE TITLE
🤔 How to use BodyParser with multiple structs?

### ISSUE THREAD

**Issue by phtdacosta** [gofiber/fiber#371]

**Comment by UJPrasad** [comment]
Create a new struct that holds your incoming JSON format with all those structs used?

Example: 

```go

type User struct {
  ...
}

...

type IncomingData struct {
  User
  Address
  Cart
}
data := IncomingData{}
err := c.BodyParser(&data)
```

**Comment by phtdacosta** [comment]
So it means that BodyParser can only dump the body into one and just one struct, then? I need to decompose it manually, right?

**Comment by thomasvvugt** [comment]
Hi @phtdacosta ,
Could you explain what exactly you mean by multiple structs a little further?
Do you mean nested structs, or different structs next to each other from a JSON dictionary?

**Comment by UJPrasad** [comment]
@phtdacosta 

You can even unmarshal the contents into different structs using pointers in go?

```go
type User struct {
	Name string `json:"name"`
        ...
}

...

type IncomingData struct {
	*User
	Cart
	AddressArr []Address `json:"addresses"`
}

user := &User{}
data := IncomingData{
	User: user,
}

err := ctx.BodyParser(&data)

```

**Comment by Fenny** [comment]
I'm closing this issue since the question has been answered.

**Comment by abedshouman** [comment]
Hello, Im trying to convert my current Rest API from nodejs to go using fiber, so i am a bit new to golang, i tried the two posted solution to parse nested json to nested structures, i even tried the same examples you already posted, but i am getting the same error **"schema: converter not found for User"**
