### ISSUE TITLE
🔥 Support Message Broker, Scheduler Tasks and Background Jobs

### ISSUE THREAD

**Issue by itsursujit** [gofiber/fiber#378]
I love the performance of fiber. It would be even best if fiber also provide support for Message Brokers like Redis, RabbitMQ, SQS,  Kafka, ASync.

Also tasks scheduler in fiber would also be a great feature.

With above solution, we could implement and long processing tasks in background while serving the response to user without any delay and wait for the background tasks to be completed.

Use Case:
**Implementing Messaging services like Email/SMS**
Sending EMail/SMS or doing any API Calls (that doesn't require waiting for response) can be sent in background for processing and wait for those tasks to be completed.

**Long processing tasks**
The solution would provide instant response to user for the status of processing meanwhile waiting in the background for the tasks to complete

**Comment by Fenny** [comment]
Hi @itsursujit, Fiber is a minimal framework. One of the key features is simplicity, therefor we made a design choice to separate all middlewares and not extend the API further than expressjs.

We give the user the possibility to create middlewares for Fiber. The examples you named are very use-case specific, and it would be better if you create your own middleware for it.
