### ISSUE TITLE
🐞 Similar routes execute wrong handlers

### ISSUE THREAD

**Issue by st-wong** [gofiber/fiber#379]
**Fiber version/commit**
Version 1.9.5

**Issue description**
Route of a similar path structure doesn't call the right handler. I have 2 routes which have same methods (PATCH), 1st route `/projects/:id` and 2nd route `/projects/:id/metadata`. So PATCH on the 1st route has no issue, however, when performing a PATCH on the 2nd route, it calls the handler for the 1st route and on checking the `Params("id")` it returns `:id/metadata`. I have tried to change both methods to POST and face the same situation, but GET will work for both routes or if both routes use different methods (e.g. 1st route uses POST while 2nd route uses PATCH, or vice versa).

**Expected behavior**
Both routes should be handled with the given handlers, since this is working on GET methods and different methods for each route. Although I do agree that API routes of this design is highly not recommended. =) 

**Steps to reproduce**
1. Create PATCH/POST method to route `/level1/:id`
2. Create same method in 1. to route `/level1/:id/level2`
3. Make API call to route in 2.
4. Result will be from handler found in 1.

**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  app.Patch("/projects/:id", RouteHandler1)
  app.Patch("/projects/:id/metadata", RouteHandler2)
}
```

Finally, keep up the great work!! We're loving the framework and we shifted our entire project because of the performance we read about. =)

**Comment by Fenny** [comment]
Welcome @st-wong, this bug has been fixed in `v1.9.6`.
