### ISSUE TITLE
🤔 Any way to set header instead of appending to existing value?

### ISSUE THREAD

**Issue by boolooper** [gofiber/fiber#382]
Is there any way to completely vanish previous values of a header and set a completely new value?

```
c.Append("foo","bar")
c.Append("foo","jar")
```

will result `Foo: bar, jar`

But I want the output as `Foo: jar`.

Any way?

**Comment by boolooper** [comment]
`ctx.Set` is the solution. But it should be in documentation. Closing....

**Comment by Fenny** [comment]
Welcome @boolooper! Sure thing, remember we almost have a 1:1 API like [expressjs](https://expressjs.com/en/4x/api.html)

Fiber uses the `ctx.Set(key, val)` method, which is documented under the context section https://docs.gofiber.io/context#set

**Comment by boolooper** [comment]
Got it. Btw off-topic,  any work on implementing `context.Context` in `ctx`?
