### ISSUE TITLE
How can I implement a graphql endpoint that uses HandlerFunc?

### ISSUE THREAD

**Issue by roger-king** [gofiber/fiber#393]
**Question description**

A lot of the Graphql libraries out there (gqlgen) use HandlerFuncs which does not align with FastHTTP. I see FastHTTP has a function called `NewFastHTTPHandler` that I thought I would be able to use in hopes of passing that as the method for the HTTP request. Any ideas on how I would be able to implement this?

**Code snippet (optional)**

```go
        // returns fasthttp.RequestHandler
	gqlFunc := fasthttpadaptor.NewFastHTTPHandler(playground.Handler("", ""))
```

**Comment by Fenny** [comment]
We created an [adaptor](https://github.com/gofiber/adaptor) middleware that supports converting `http.Handler` & `http.HandlerFunc` to a `func(*fiber.Ctx)` handler.

**Comment by roger-king** [comment]
> We have an [adaptor](https://github.com/gofiber/adaptor) middleware that supports converting `http.Handler` & `http.HandlerFunc` to a `func(*fiber.Ctx)` handler.

Thank you! I knew I was missing something!

**Comment by Hamzsd** [comment]
Adaptor middleware doesn't supports graphql subscription. Any workaround for this?

**Comment by Hamzsd** [comment]
@ReneWerner87 I am using in the following manner
```
srv := handler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{}}))
app.All("/query", adaptor.HTTPHandler(srv))
app.All("/", adaptor.HTTPHandlerFunc(playground.Handler("GraphQL playground", "/query")))
```
and I get this error when using subscriptions
`unable to upgrade *fasthttpadaptor.netHTTPResponseWriter to websocket websocket: response does not implement http.Hijacker`

**Comment by ReneWerner87** [comment]
can you try https://github.com/arsmn/fastgql#using-with-fiber

**Comment by Hamzsd** [comment]
Thanks for the response. I already tried it, it has this error during auto generation.
`graph/prelude.resolvers.go:19:44: __DirectiveResolver not exported by package generated`

Moreover, `fastgql` doesn't seems to be production ready. Is there any other way around this?

**Comment by ReneWerner87** [comment]
@arsmn can you help here?

**Comment by giancarlosisasi** [comment]
Is there any solution or guidance on how to solve the subscription gqlgen problem?

Sorry to ask but @Hamzsd did you find any solution for this? 🙏
