### ISSUE TITLE
🐞 Group middleware does not work when route has parameters

### ISSUE THREAD

**Issue by jos-** [gofiber/fiber#394]
Thanks for the great framework. However, I encountered the following bug:

**Fiber version/commit**
v1.9.6

**Issue description**
Group middleware is not executed when the group route has parameters.

**Steps to reproduce**
See code below and compare http://localhost:8080/a with http://localhost:8080/b
`myMiddlewareA` is called, but `myMiddlewareB` not.

**Code snippet**

```go
package main

import (
	"log"
	"github.com/gofiber/fiber"
)

func myMiddlewareA(c *fiber.Ctx) {
	log.Println("myMiddlewareA called")
	c.Next()
}

func myMiddlewareB(c *fiber.Ctx) {
	log.Println("myMiddlewareB called") // Never happens
	c.Next()
}

func main() {
	app := fiber.New()

	groupA := app.Group("/a", myMiddlewareA)
	groupA.Get("/", func(c *fiber.Ctx) {
		c.Send("Group A") // Works with middleware
	})

	groupB := app.Group("/:somerouteparameter", myMiddlewareB)
	groupB.Get("/", func(c *fiber.Ctx) {
		c.Send("Group B") // The response is returned, but the middleware is not called
	})

	log.Fatal(app.Listen(8080))
}
```

**Comment by jos-** [comment]
This was just an example. If the group doesn't start with a parameter, but is e.g. `/v1/users/:id`, the same problem occurs.

Starting a group with a parameter can be useful if it's not a root-level group.

**Comment by rof20004** [comment]
@jos- 

I disagree, I think a group need a name to identify it, than it needs to be a static name. In my opinion.

**Comment by jos-** [comment]
Consider part of the GitHub api (https://developer.github.com/v3/repos/branches/) as an example. It has the following routes:

```
/repos/:owner/:repo/branches
/repos/:owner/:repo/branches/:branch
/repos/:owner/:repo/branches/:branch/protection
/repos/:owner/:repo/branches/:branch/protection/required_status_checks
/repos/:owner/:repo/branches/:branch/protection/required_pull_request_reviews
/repos/:owner/:repo/branches/:branch/protection/required_signatures
/repos/:owner/:repo/branches/:branch/protection/enforce_admins
```

Here it can be very useful to have a route group for `/repos/:owner` or `/repos/:owner/:repo` with middleware that checks if the current user is authorized to access these routes.

**Comment by rof20004** [comment]
Like I said, this is a design. What are you doing is a code design, not a rest application design. The Github example is a rest uri design, not a code application design.

https://restfulapi.net/rest-api-design-tutorial-with-example/#model-uris

Your code is this:

```
groupB := app.Group("/:somerouteparameter", myMiddlewareB)
```
If you analize, /:somerouteparameter can be /a, ok? But /a is your first group, your rest uri design is confused.

**Comment by rof20004** [comment]
I code like this, using your example:

```
groupB := app.Group("/v1/users", myMiddlewareB)
groupB.Get("/:id", func(c *fiber.Ctx) {
      c.Send("Group B")
})
```

**Comment by jos-** [comment]
My point was:

1. Parameters in route groups already work, no need to fix this. Removing this possibility would be a bad idea IMO, since many other frameworks support this.
2. I gave a minimal code example to show the issue. Of course this was not according to rest practices. If you want a more restful example from the GitHub api:

```go
package main

import (
	"log"
	"github.com/gofiber/fiber"
)

func someMiddleware(c *fiber.Ctx) {
	// Check if the current user is authorized to access :owner/:repo

	c.Next()
}

func main() {
	app := fiber.New()

	api := app.Group("/v1")
	repo := api.Group("/repos/:owner/:repo", someMiddleware) // Doesn't work
	branch := repo.Group("/branches/:branch")

	repo.Get("/branches", func(c *fiber.Ctx) {
		// ...
	})

	branch.Get("/", func(c *fiber.Ctx) {
		// ...
	})
	branch.Get("/protection", func(c *fiber.Ctx) {
		// ...
	})
	branch.Get("/required_status_checks", func(c *fiber.Ctx) {
		// ...
	})
	
	log.Fatal(app.Listen(8080))
}
```

You can see here that:
1. Parameters in route groups can save a lot of duplicate code.
2. Middleware applied to groups with route parameters doesn't work. It does however work in groups without route parameters, which is confusing.

The current workaround for the above situation is to apply the middleware to every route separately, like:

```go
	repo.Get("/branches", someMiddleware, func(c *fiber.Ctx) {
		// ...
	})
```

But this results again in a lot of duplicate code if you have to pass the middleware to every route separately.

**Comment by Fenny** [comment]
Currently `app.Group` equals `app.Use` but it returns a `*Group` struct instead for chaining the prefix.
In the new update `v1.10` both `app.Group` & `app.Use` will support `:params` & `:optionals`

**Comment by jos-** [comment]
Great, many thanks!
