### ISSUE TITLE
🤔 Router group matches partial path, is this intended?

### ISSUE THREAD

**Issue by jos-** [gofiber/fiber#395]
**Question description**

If I have a router group `/a`,  it matches all requests starting with `a`, e.g. not only `/a/b`, but also `/api`, `/abc`, etc.
I think this is different from how most other routers work, and can be confusing. Is this a bug, or is this intended?

Possibly related: #394 

**Code snippet**

Try running the snippet below and visiting http://localhost:8080/api

```go
package main

import (
	"log"
	"github.com/gofiber/fiber"
)

func main() {
	app := fiber.New()

	app.Group("/a", func(c *fiber.Ctx) {
		log.Println("group with path /a is matched")
		c.Next()
	})

	app.Get("/api", func(c *fiber.Ctx) {
		c.Send("hello world")
	})

	log.Fatal(app.Listen(8080))
}
```

**Comment by Fenny** [comment]
Hi @jos-, related to https://github.com/gofiber/fiber/issues/394#issuecomment-631540930
