### ISSUE TITLE
🔥 Docker-Image for static websites

### ISSUE THREAD

**Issue by Lol3rrr** [gofiber/fiber#397]
**Is your feature request related to a problem?**
Not really

**Describe the solution you'd like**
A simple docker image which is just a simple webserver, that serves static files located in some directory (maybe '/website/' but that is not the point right now). 

**Describe alternatives you've considered**
I first thought about creating it myself in a seperate repository, but this would just add more things to keep up with and it would be hard to automatically create a newer version with a new release.

**Additional context**
Because fiber is pretty fast and is already capable of serving static files, this would be a rather simple addition, but could be really useful when you just need to serve some static files and don't want to use something "heavier" like nginx.
The reason I think it would fit in the main project or a subdirectory/repo, like some middlewares, is simply that it is easier to keep up to date, by automatically creating it with every new release.

**Comment by Lol3rrr** [comment]
When publishing the Docker-Image should it be published to Dockerhub or to Github's docker repository?
I would personally prefer Dockerhub, as it's kind of the default place to look for docker images

**Comment by thomasvvugt** [comment]
Hi @Lol3rrr please see my comment at #398 
Feel free to post a PR in [gofiber/boilerplate](https://github.com/gofiber/boilerplate)!

**Comment by Fenny** [comment]
Merged in [gofiber/boilerplate](https://github.com/gofiber/boilerplate!) 👍
