### ISSUE TITLE
🔥 Official Graphql support

### ISSUE THREAD

**Issue by numToStr** [gofiber/fiber#403]
**Is your feature request related to a problem?**
Thanks for your all effort for making this 🔥 and ♥️ framework. This is my goto framework when I work with go ✌🏻. And I also work extensively with graphql and It would be cool to have a official graphql plugin 🔥.

**Describe the solution you'd like**
An official graphql plugin.

**Additional context**
Official Javascript implemetation: https://github.com/graphql/graphql-js
Fastify.js Implementation: https://github.com/mcollina/fastify-gql

**Comment by thomasvvugt** [comment]
Hi @numToStr , thanks for bringing up this issue!

We have however discussed this feature request in the past, however we do not think a GraphQL library should be official but rather something the end-user can import into their application.

I do recommend checking out https://github.com/arsmn/gqlgen and https://github.com/Just4Ease/fiber-gqlgen for importing GraphQL with Fiber.

Thank you for opening your first issue! 🎉

**Comment by rijine** [comment]
Is there any documentation for using official graphql library (https://github.com/graphql-go/graphql) with fiber?

**Comment by kockok** [comment]
> Hi @numToStr , thanks for bringing up this issue!
> 
> We have however discussed this feature request in the past, however we do not think a GraphQL library should be official but rather something the end-user can import into their application.
> 
> I do recommend checking out https://github.com/arsmn/gqlgen and https://github.com/Just4Ease/fiber-gqlgen for importing GraphQL with Fiber.
> 
> Thank you for opening your first issue! 🎉

Can you create an official recipe as to integrate with [gqlgen](https://gqlgen.com)?
Especially for the context integration.

https://github.com/arsmn/gqlgen raises errors.

![Screenshot 2020-07-17 at 5 35 32 PM](https://user-images.githubusercontent.com/232541/87772493-66756880-c854-11ea-9598-a992c2be7a0f.png)

TnX

**Comment by rijine** [comment]
@kockok  This is how I did it.

```
import (
	"context"
	"fmt"
	"github.com/99designs/gqlgen/example/starwars" // sample
	"github.com/99designs/gqlgen/example/starwars/generated"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/gofiber/adaptor"

	"github.com/gofiber/fiber"
)


```

```
srv := handler.NewDefaultServer(generated.NewExecutableSchema(starwars.NewResolver()))
	srv.AroundFields(func(ctx context.Context, next graphql.Resolver) (res interface{}, err error) {
		rc := graphql.GetFieldContext(ctx)
		fmt.Println("Entered", rc.Object, rc.Field.Name)
		res, err = next(ctx)
		fmt.Println("Left", rc.Object, rc.Field.Name, "=>", res, err)
		return res, err
	})

	app.Get("/graphiql", adaptor.HTTPHandler(playground.Handler("Starwars", "/graphql")))
	app.Post("/graphql", adaptor.HTTPHandler(srv))
```

**Comment by rijine** [comment]
@kockok are you able to fix it?

**Comment by kockok** [comment]
> @kockok are you able to fix it?

No, switched back to `gin`.

**Comment by RobertoOrtis** [comment]
I have implemented gofiber with gqlgen and it is working for queries and mutations; however, subscriptions won't work because I need websockets. I tried to use gofiber websocket but it just not work. Has anyone successfully implemented gqlgen subscriptions with gofiber?

**Comment by Fenny** [comment]
Could you show us what gqlgen subscriptions are?

**Comment by RobertoOrtis** [comment]
> Could you show us what gqlgen subscriptions are?

Got it working with arsmn's fork for fiber.
I have a new issue on: https://github.com/99designs/gqlgen/issues/1281

**Comment by ftomza** [comment]
Hi!
How I solved the problem without subscriptions yet
package main

```golang
import (
	"net/http"
	"github.com/99designs/gqlgen/graphql/playground"
	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/gofiber/fiber"
	"github.com/valyala/fasthttp/fasthttpadaptor"
)

func main() {
	app := fiber.New()

	app.Post("/*", func(ctx *fiber.Ctx) {
		h := handler.NewDefaultServer(NewExecutableSchema(Config{Resolvers: &Resolver{}}))
		fasthttpadaptor.NewFastHTTPHandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
			h.ServeHTTP(writer, request)
		})(ctx.Fasthttp)
	})
	app.Get("/query", func(ctx *fiber.Ctx) {
		h := playground.Handler("GraphQL", "/query")
		fasthttpadaptor.NewFastHTTPHandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
			h.ServeHTTP(writer, request)
		})(ctx.Fasthttp)
	})
	app.Listen(3000)
}
```

**Comment by water-a** [comment]
To use @ftomza 's code on fiber/v2, instead of `ctx.Fasthttp` you have to use `ctx.Context()`.

**Comment by frederikhors** [comment]
@ftomza have you solved for subscriptions?

**Comment by frederikhors** [comment]
https://github.com/99designs/gqlgen/issues/1664

**Comment by drnocam** [comment]
> To use @ftomza 's code on fiber/v2, instead of `ctx.Fasthttp` you have to use `ctx.Context()`.
worked great. Thank you.
`app.All("/query", func(ctx *fiber.Ctx) error {
		h := handler.NewDefaultServer(graph.NewExecutableSchema(graph.Config{Resolvers: &graph.Resolver{}}))
		fasthttpadaptor.NewFastHTTPHandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
			h.ServeHTTP(writer, request)
		})(ctx.Context())
		return nil
	})`

**Comment by kamalkech** [comment]
@ftomza  gqlgen is terrible, it s better to use graphql-go for code first

**Comment by gaby** [comment]
@kamalkech Got an example using GoFiber?

**Comment by cmd777** [comment]
> @kamalkech Got an example using GoFiber?

The official [graphql-go](https://github.com/graphql-go/graphql) repo has a pretty good example
This is what I hacked together quickly:
```go
package main

import (
	"encoding/json"
	"log"

	"github.com/gofiber/fiber/v2"
	"github.com/graphql-go/graphql"
)

func main() {
	fields := graphql.Fields{
		"hello": &graphql.Field{
			Type: graphql.String,
			Resolve: func(p graphql.ResolveParams) (interface{}, error) {
				return "world", nil
			},
		},
	}
	rootQuery := graphql.ObjectConfig{Name: "RootQuery", Fields: fields}
	schemaConfig := graphql.SchemaConfig{Query: graphql.NewObject(rootQuery)}
	schema, err := graphql.NewSchema(schemaConfig)
	if err != nil {
		log.Fatalf("failed to create new schema, error: %v", err)
	}

	app := fiber.New()

	app.Post("/", func(ctx *fiber.Ctx) error {
		query := string(ctx.Body())
		params := graphql.Params{Schema: schema, RequestString: query}
		r := graphql.Do(params)
		if len(r.Errors) > 0 {
			ctx.SendString("failed to execute graphql operation")
		}
		rJSON, err := json.Marshal(r)
		if err != nil {
			ctx.SendString("cannot marshal json")
		}
		return ctx.JSON(string(rJSON))
	})

	log.Fatal(app.Listen(":9090"))
}

```

```bash
curl -X POST -d "{hello}" http://localhost:9090

"{\"data\":{\"hello\":\"world\"}}"
```

**Comment by kamalkech** [comment]
@cmd777 for my case and my project i switch from golang to rust lang because really community of golang is terrible and most of modules not improved correctly and graphql is one of them

**Comment by navicstein** [comment]
@kamalkech what libs in rust did you use for this case?
