### ISSUE TITLE
🔥 Add support or documentation for unit tests

### ISSUE THREAD

**Issue by schweigert** [gofiber/fiber#41]
I loved the framework. Simple and straightforward. Excellent for making microservices. However, I didn't find any support to create unit tests :(

The use of the gin framework is precisely because it allows the use of httptest as a standard, which is already well documented.

Maybe it would be nice to make a mock of the context to test the behaviors, and be able to access all the registered routes if you want to test the association between middleware, methods and routes.

**Comment by Fenny** [comment]
Thanks for your kind words @schweigert, welcome!

This is exactly what we were planning to do asap, I will keep this issue open to provide updates.

**Comment by Fenny** [comment]
Did this help you out @schweigert? If so, let us know so we can close this issue :+1:

**Comment by schweigert** [comment]
This looks good, but I still can't test the status code of the request. I believe that the return should not be a string, but a response, from the http package.

**Comment by Fenny** [comment]
Maybe we should drop the `raw http string` and only work with `http.Request` & `http.Response`.  
@koddr, what do you think?

**Comment by koddr** [comment]
@Fenny I think, we can do this, if it's solve this issue 👍 
@schweigert can you send PR for this fix?

**Comment by Fenny** [comment]
@koddr I will make a PR, thnx for the feedback

**Comment by PK2702** [comment]
> Thanks for your kind words @schweigert, welcome!
> 
> What about a method named `Test` so you can pass a raw HTTP string or `*http.Request` struct to test your application locally.
> 
> _Raw HTTP string_
> ```go
> package main
> 
> import (
>   "fmt"
>   "github.com/gofiber/fiber"
> )
> 
> func main() {
>   app := New()
>   app.Get("/demo", func(c *Ctx) {
>     fmt.Println(c.BaseURL()) // => http://google.com
>   })
> 
>   body, err := app.Test("GET /demo HTTP/1.1\r\nHost: google.com\r\n\r\n")
>   fmt.Println(body, err)
> }
> ```
> 
> _Using http.Request_
> ```go
> package main
> 
> import (
>   "fmt"
>   "github.com/gofiber/fiber"
> )
> 
> func main() {
>   app := New()
>   app.Get("/demo", func(c *Ctx) {
>     fmt.Println(c.BaseURL()) // => http://google.com
>   })
> 
>   req, _ := http.NewRequest("GET", "http://google.com/demo", nil)
>   req.Header.Set("X-Custom-Header", "hi")
> 
>   body, err := app.Test(req)
>   fmt.Println(body, err)
> }
> ```

**Comment by pjebs** [comment]
How can I use this feature from a `_test.go` file? It appears you need a reference to `app` variable.

**Comment by yaliv** [comment]
> How can I use this feature from a `_test.go` file? It appears you need a reference to `app` variable.

You can prepare a function, which creates a Fiber app and use middleware(s) that you want to test.
For example:
```
func setupApp() *fiber.App {
	app := fiber.New()
	app.Use(authenticate.New(), attachuser.Handle, authorize.Handle)
	authenticateduser.Setup(app)

	return app
}
```

Then use that function in your test codes:
```
const bearerToken = "Bearer o8SMWsPx.9wJ7nZ86.XUyQV3yu"

func TestGet(t *testing.T) {
	app := setupApp()

	req := httptest.NewRequest("GET", "/", nil)
	req.Header.Set("Authorization", bearerToken)

	res, _ := app.Test(req)
}

func TestPatch_Profile(t *testing.T) {
	app := setupApp()

	const reqBody = `{
		"scope": "profile",
		"data": {
		  "name": "My New Name"
		}
	}`

	req := httptest.NewRequest("PATCH", "/", strings.NewReader(reqBody))
	req.Header.Set("Authorization", bearerToken)

	res, _ := app.Test(req)
}

func TestPatch_Password(t *testing.T) {
	app := setupApp()

	const reqBody = `{
		"scope": "password",
		"data": {
		  "oldPassword": "qwerty",
		  "newPassword": "12qwaszx"
		}
	}`

	req := httptest.NewRequest("PATCH", "/", strings.NewReader(reqBody))
	req.Header.Set("Authorization", bearerToken)

	res, _ := app.Test(req)
}
```

**Comment by cdunn2001** [comment]
I wish the wiki were in GitHub. https://fiber.wiki is currently unavailable.
