### ISSUE TITLE
🤔 Routing example in readme does not work?

### ISSUE THREAD

**Issue by panda8z** [gofiber/fiber#411]
**Issue description**
![image](https://user-images.githubusercontent.com/24646937/82793757-04c3fe00-9ea4-11ea-8078-20c1f9127c00.png)

**Comment by Fenny** [comment]
Hi @panda8z, thank you for opening your first issue here!

This is expected behaviour because it will stop at the first match `/api/register` will match `/:name/:age?`. You can continue the stack by calling `c.Next()`

```go
func main() {
	app := fiber.New()

	app.Get("/:name/:age?", func(c *fiber.Ctx) {
		fmt.Printf("First route: [name]: %s [age]: %s\n", c.Params("name"), c.Params("age"))
		c.Next()
	})

	app.Get("/api/*", func(c *fiber.Ctx) {
		fmt.Printf("Last route:  [*]: %s\n", c.Params("*"))
	})

	app.Listen(3000)
	// GET /api/register
	// First route: [name]: api [age]: register
	// Last route:  [*]: register
}
```

Maybe the example is unclear, and we should edit it :-)

**Comment by panda8z** [comment]
I got it. I’m so thankful for your reply.  New code is right.

And I found another error in **Static Example**

Original:
![image](https://user-images.githubusercontent.com/24646937/82799310-70aa6480-9eac-11ea-903d-8055c7e86dc0.png) 

I think here should be reletive path, but every `/public` is point to the [root]/public. 

It should be below：
```go
func main() {
  app := fiber.New()

  app.Static("/", "./public")
  // => http://localhost:3000/js/script.js
  // => http://localhost:3000/css/style.css

  app.Static("/prefix", "./public")
  // => http://localhost:3000/prefix/js/script.js
  // => http://localhost:3000/prefix/css/style.css

  app.Static("*", "./public/index.html")
  // => http://localhost:3000/any/path/shows/index/html

  app.Listen(3000)
}
```

**Comment by Fenny** [comment]
Nice catch, fixed this in <https://github.com/gofiber/fiber/pull/415/commits/8303ce88734b6eb34bf08d5bb8d9cbfbbe87fe3f>
