### ISSUE TITLE
🤔 Equivalent to $body_bytes_sent from nginx or %B of apache mod_log

### ISSUE THREAD

**Issue by git001** [gofiber/fiber#414]
**Question description**

I try to create a "combined" Logformat with "github.com/gofiber/logger" and I asked my self exists in fiber a variable which have this value which I can use in the logger module?

http://nginx.org/en/docs/http/ngx_http_core_module.html#var_body_bytes_sent
```
$body_bytes_sent
    number of bytes sent to a client, not counting the response header; 
    this variable is compatible with the “%B” parameter of the 
    mod_log_config Apache module 
```
http://httpd.apache.org/docs/2.4/mod/mod_log_config.html
```
%B | Size of response in bytes, excluding HTTP headers.
```
**Code snippet (optional)**

```go
package main

import (
  "github.com/gofiber/fiber"
  "github.com/gofiber/logger"
)

func main() {
  app := fiber.New()
  app.Use(logger.New(logger.Config{
		TimeFormat: "02/Jan/2006:03:04:05 -0700",
		Format:     "${ip} - - [${time}] \"${method} ${url} HTTP/1.1\" ${status} 0 ${referer} ${ua}\n",
	}))
}
```

**Comment by Fenny** [comment]
This could be added to the logger, we could name it `bytesSent` using `len(c.Fasthttp.Response.Body())`
PR's are welcome https://github.com/gofiber/logger/blob/master/main.go
