### ISSUE TITLE
🤔 Is there anyway to disable template engine?

### ISSUE THREAD

**Issue by leopku** [gofiber/fiber#433]
**Question description**
My app only served as an api server.
How can I disable template engine?

**Comment by Fenny** [comment]
Hello @leopku, the template engine is `nil` by default. So if you do not set an engine, it will not be used.

**Comment by leopku** [comment]
> Hello @leopku, the template engine is `nil` by default. So if you do not set an engine, it will not be used by the `ctx.Render()` function.

Got it. Thanks.
