### ISSUE TITLE
🤔 I cannot upload large file via form file 

### ISSUE THREAD

**Issue by Tantatorn-dev** [gofiber/fiber#442]
**Question description**
I used a form file for uploading file. But when I attached a large file, it responded with 
"412 Request Entity Too Large"
**Code snippet** 

```go
file,err := c.FormFile("img")
if err != nil {
		c.Status(http.StatusBadRequest).Send("form file error")
		return
}

	
if err := c.SaveFile(file, fmt.Sprintf("./img/%s", file.Filename)); err != nil {
		c.Status(http.StatusInternalServerError).Send("save file failed")
		return
}
```

**Comment by Fenny** [comment]
Try to increase the `BodyLimit` it defaults to `4MB +/-` (_4 * 1024 * 1024_)
```go
app := fiber.New(&fiber.Settings{
  BodyLimit: 10 * 1024 * 1024, // 10MB in bytes
})
```

**Comment by Tantatorn-dev** [comment]
It works perfectly. Thank you very much.

**Comment by Koredeoluwafemi** [comment]
For those who my visit this later as I did today, the Bodylimit has been moved. See the snippet below

````
app := fiber.New(fiber.Config{
    BodyLimit: 4 * 1024 * 1024, // this is the default limit of 4MB
})
````

**Comment by semmars** [comment]
> For those who my visit this later as I did today, the Bodylimit has been moved. See the snippet below
> 
> ```
> app := fiber.New(fiber.Config{
>     BodyLimit: 4 * 1024 * 1024, // this is the default limit of 4MB
> })
> ```

the working version:
```
app := fiber.New(&fiber.Settings{
		BodyLimit: 100 * 1024 * 1024, // this is the default limit of 100MB 
})
```


another working version:


```
app := fiber.New()
app.Settings.BodyLimit= 100 * 1024 * 1024
```

https://github.com/gofiber/fiber/issues/442
