### ISSUE TITLE
🤔 Serving directly from compressed files with Static()

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#443]
**Question description**

How to serve directly from already-compressed files with the `Static()` function. Details at

https://github.com/gofiber/compression/issues/2

**Comment by Fenny** [comment]
```go
// Static represents settings for serving static files
type Static struct {
    // Transparently compresses responses if set to true
    // This works differently than the github.com/gofiber/compression middleware
    // The server tries minimizing CPU usage by caching compressed files.
    // It adds ".fiber.gz" suffix to the original file name.
    // Optional. Default value false
    Compress bool
    // Enables byte range requests if set to true.
    // Optional. Default value false
    ByteRange bool
    // Enable directory browsing.
    // Optional. Default value false.
    Browse bool
    // Index file for serving a directory.
    // Optional. Default value "index.html".
    Index string
}
```
```go
app.Static("/", "./public", fiber.Static{
  Compress: true,
})
```

**Comment by suntong** [comment]
Thanks please take a look at
https://github.com/suntong/fiber_demo/commit/434ea4b5aa0cbd7337048952b00dc46c0c53d16e

and this is what I got:

![image](https://user-images.githubusercontent.com/422244/83945639-09f54700-a7da-11ea-887a-71f01bf3d058.png)

**Comment by ReneWerner87** [comment]
@suntong check out release 1.11.0, you can specify the CompressedFileSuffix in the app settings with ".gz"

**Comment by suntong** [comment]
thanks @ReneWerner87, I'll try it out this weekend.

**Comment by Fenny** [comment]
@suntong any luck with the `CompressedFileSuffix` feature?

**Comment by suntong** [comment]
Sorry @Fenny  I don't have much free time to test it during the work days this week, give me two more days, I'll try it out this weekend.

**Comment by suntong** [comment]
I'm still unable even to get `Compress: true` work yet. 

This after I've done `go get -u github.com/gofiber/fiber` just now.
The error is exactly as above, and also, 

![image](https://user-images.githubusercontent.com/422244/84558524-6b994200-ad01-11ea-9b63-48320f63597f.png)

Can someone give me a full working code please? 

Again, my code is at
https://github.com/suntong/fiber_demo/blob/master/app/static1.go

**Comment by Fenny** [comment]
I see the issue now, fasthttp file server requires you to have the original filename along with the compressed files. You can test this out by placing an empty `index.html` in the `sample2` folder and it serve the compressed file.

**Comment by suntong** [comment]
Thanks @Fenny, I now get it working. 

No @ReneWerner87, specifying the CompressedFileSuffix in the app settings with `".gz"` does not work for me, again, after I've done go get -u github.com/gofiber/fiber --

https://github.com/suntong/fiber_demo/blob/master/app/static-gz.go

A full working code appreciated. My fiber_demo repo is super small and can be a great start for you.

**Comment by Fenny** [comment]
@suntong, I tested `CompressedFileSuffix` with your code and it works fine. You just forgot to put the `index.html.fiber.gz` into the `sample-gz` folder and rename it to `index.html.gz`

There is also a minimum size that is required before a file gets compressed:
https://github.com/valyala/fasthttp/blob/master/compress.go#L406

**Comment by suntong** [comment]
Ops, sorry, my bad, don't know how `index.html.gz` was missed as I do them all together. 

Yep, now it is fully working. 
Thanks a lot for your helps, @Fenny & @ReneWerner87 !

**Comment by FrancescoLuzzi** [comment]
If you want to serve **only** precompressed files, here is the solution that I've come up with, hope it helps ✌
https://gist.github.com/FrancescoLuzzi/7ad74721faa8af56e2d03ef452448380
