### ISSUE TITLE
🚀 pion webrtc middleware

### ISSUE THREAD

**Issue by StarMonk** [gofiber/fiber#456]
**Is your feature request related to a problem?**
Webrtc feature

**Describe the solution you'd like**
Gofiber middleware of pion/webrtc module - https://github.com/pion/webrtc

**Describe alternatives you've considered**
Not any at the moment

**Comment by Fenny** [comment]
Hi @StarMonk, thank you for opening your first issue! Could you elaborate a little bit more on what you expect from a `webrtc` middleware for fiber?

**Comment by StarMonk** [comment]
Just a native package like "gofiber/websocket" which supports "fasthttp/websocket"

**Comment by Fenny** [comment]
I don't see the benefit to make a separate repo for webrtc, you could use the official repo along with fiber if that's what you are looking for. It's a different protocol.

**Comment by Fenny** [comment]
@StarMonk thank you for opening this issue, ideas are more than welcome but we think that the webrtc repo would have no benefit to be hosted on the gofiber organization.

Feel free to re-open, but for the time being, this will be tagged as #wontfix
