### ISSUE TITLE
🚀 Add Fiber to the roadmap

### ISSUE THREAD

**Issue by maplerichie** [gofiber/fiber#462]
**Question description**
Create a PR at https://github.com/Alikhll/golang-developer-roadmap

**Comment by Fenny** [comment]
Hi @maplerichie, good idea! Would you like to create a PR?

**Comment by Fenny** [comment]
@maplerichie thank you for the suggestion, I'm closing this because it got merged 👍 https://github.com/Alikhll/golang-developer-roadmap
