### ISSUE TITLE
Did you have a list of example projects? 🤔 

### ISSUE THREAD

**Issue by enBonnet** [gofiber/fiber#467]
**Question description**
I be learning Golang, in this way found Fiber and totally love it. 😍
Already made two repository, i think would help some others on they learning path, so there is any official way to share it?

[API Fiber with Gorm](https://github.com/enBonnet/api-fiber-gorm)
[API Fiber with Gorm and JWT](https://github.com/enBonnet/fiber-jwt)

**Comment by Fenny** [comment]
Hi @enBonnet, welcome to the Fiber! We do have a [recipes](https://github.com/gofiber/recipes) repo where you could create a PR to add your examples. Other than that, we promote [third party middleware](https://github.com/gofiber/fiber#-third-party-middlewares) and [media articles](https://github.com/gofiber/fiber#-media) on our main readme.

Thank you for creating these awesome repositories, I'm sure this would help other people getting started with Fiber!

**Comment by enBonnet** [comment]
Thanks @Fenny, then i will do some PR to [recipes](https://github.com/gofiber/recipes).

My question was successfully answered
