### ISSUE TITLE
🚀 Session Interface

### ISSUE THREAD

**Issue by hendratommy** [gofiber/fiber#479]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Right now the `gofiber/session` is more like a store than a middleware.
In every handlers that need session, we need to get the `sessions`, `session.Get(c)`, then save it.
It became very repetitive tasks, became dependent to the session store implementation, and if we have handlers in separate package then we need to pass it around. While we can abstract the store and let the handlers to use the session without referencing to the variable directly.

```go
type Session interface {
    ID() string
    Get(key string) interface{}
    Set(key string, value interface{})
    Destroy()
    Regenerate()
}
```
and in Ctx have function to get and set the Session
```go
func (c *Ctx) SetSession(session Session) {}
func (c *Ctx) Session() Session
```

finally, use it like:
```go
sessions := session.New()

app.Use(func(c *fiber.Ctx) {
    store := sessions.Get(c)
    defer store.Save()
    c.SetSession(store)
    c.Next()
})

app.Get("/web", func(c *fiber.Ctx) {
    c.Session().ID()                   // returns session id
    c.Session().Destroy()              // delete storage + cookie
    c.Session().Get("john")            // get from storage
    c.Session().Regenerate()           // generate new session id
    c.Session().Delete("john")         // delete from storage
    c.Session().Set("john", "doe")     // save to storage
})
```

**Additional context**
- This will not have breaking changes
- This will also enable third party middleware that requires or optionally use session to get the session more easily (ie. `csrf` store the token to session instead of cookies).
- Switch to any session store including custom one more doable, and can be done without breaking any middlewares and handlers.
- If by any chances in the future, templates can access `Ctx` they can access the session too

**Comment by enBonnet** [comment]
This feature looks great! Can improve use of sessions

**Comment by Fenny** [comment]
I'm closing this proposal after discussions with the @gofiber/maintainers, at this time we are not planning to extend the session me to the Fiber core. Maybe later in the future we could re-open this issue and discuss the possibilities.

I appreciate your proposal @hendratommy, thank you 👍
