### ISSUE TITLE
Security Disclosure Policy?

### ISSUE THREAD

**Issue by humaidq** [gofiber/fiber#481]
Hello.

While trying out the project, I discovered a bug in regards to routing which may be a security issue.

I am creating this issue since I couldn't find a way to report this issue safely, and nothing regarding disclosure can be found in the "Security" tab or the website.

**Comment by renanbastos93** [comment]
> Hello.
> 
> While trying out the project, I discovered a bug in regards to routing which may be a security issue.
> 
> I am creating this issue since I couldn't find a way to report this issue safely, and nothing regarding disclosure can be found in the "Security" tab or the website.

Wow, please tell us more details about it

**Comment by humaidq** [comment]
> Wow, please tell us more details about it

I'd rather email the issue privately to a maintainer of the project.

**Comment by renanbastos93** [comment]
> > Wow, please tell us more details about it
> 
> I'd rather email the issue privately to a maintainer of the project.

Why?
this project is open source, I am using it on production so I do wish to know about it, can you send an email for me too?

**Comment by Fenny** [comment]
@humaidq are you able to join us on [Discord](https://gofiber.io/discord)?

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/pull/482#merged-event
