### ISSUE TITLE
🚀 How about compatibling with httpexpect

### ISSUE THREAD

**Issue by kiyonlin** [gofiber/fiber#485]
**Is your feature request related to a problem?**
 No

**Describe the solution you'd like**
[httpexpect](https://github.com/gavv/httpexpect) already supports [fasthttp binder](https://github.com/gavv/httpexpect/blob/master/binder.go#L101-L102).

The only thing to do is making `app.handler` accessable.

Simple example:
```
// fiberHTTPTester returns a new Expect instance to test FiberHandler().
func fiberHTTPTester(t *testing.T) *httpexpect.Expect {
	app := fiber.New()
	app.Get("ping", func(c *fiber.Ctx) {
		c.SendString("pong")
	})
	return httpexpect.WithConfig(httpexpect.Config{
		Client:   &http.Client{Transport: httpexpect.NewFastBinder(app.Handler)},
		Reporter: t,
	})
}

func TestFastHTTP(t *testing.T) {
	e := fiberHTTPTester(t)

	e.GET("/ping").Expect().
		Status(200).
		Text().Equal("pong")
}
```

**Comment by ReneWerner87** [comment]
https://github.com/gofiber/fiber/pull/504
added the possibility to access the handler

**Comment by Fenny** [comment]
Will be tagged in `v1.12.1` :+1:
