### ISSUE TITLE
🤔  A rate limiter implemented with delay calculate of token bucket algorithm.

### ISSUE THREAD

**Issue by kiyonlin** [gofiber/fiber#486]
**Question description**
Here is my [rate limiter](https://github.com/kiyonlin/fiber_limiter) middleware for fiber:
- no timer
- no extra background gorouting
- support burst
- custom limiter for different keys

**Code snippet** _Optional_

```go
package main

import (
	"github.com/gofiber/fiber"
	limiter "github.com/kiyonlin/fiber_limiter"
)

func main() {
	app := fiber.New()

	// 10 requests per second, support 10 burst
	cfg := limiter.Config{
		Limit: 10,
		Burst: 10,
	}

	app.Use(limiter.New(cfg))

	app.Get("/", func(c *fiber.Ctx) {
		c.Send("Welcome!")
	})

	app.Listen(3000)
}
```

**Comment by Fenny** [comment]
Awesome work @kiyonlin, I'm willing to accept a PR to add this to the _Third-Party Middleware_ list in all README's 👍
