### ISSUE TITLE
🚀  add 405 method not allowed handler

### ISSUE THREAD

**Issue by kiyonlin** [gofiber/fiber#492]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Assuming that we have code like: 
```go
app := New()

app.Setting.HandleMethodNotAllowed = true

app.Post("/path", func(ctx *Ctx) {
	ctx.Send("hello")
})

app.Listen(3000)
```

and when we use the wrong method:
```
curl localhost:3000/path -I
> HTTP/1.1 405 Method Not Allowed
> Date: Sat, 20 Jun 2020 08:54:13 GMT
> Content-Type: text/plain; charset=utf-8
> Content-Length: 18
```

**Additional context**
- This feature will not bring breaking changes
- More friendlier to users
- Users can provide custom handler to handle 405

**Comment by Fenny** [comment]
We could add a boolean option in Settings named `MethodNotAllowed` `bool` and if set to true, instead of sending a 404 it will check the stack of it matches a different method and returns a `405 Method Not Allowed` with the correct `Allow` header <https://tools.ietf.org/html/rfc2616#section-10.4.6>

**Comment by kiyonlin** [comment]
Yes, that’s my intention:smile:

**Comment by Fenny** [comment]
Fiber will respond with a 405 by default if another method is available on the same path.
This feature will be shipped in `v1.12.1` next week, thank you for your suggestion 🥳

**Comment by Aoi-hosizora** [comment]
@Fenny I use `1.12.4`, but I can't see the 405 response you described, here is my code:

```go
func InitRoute(app *fiber.App) {
	v1 := app.Group("/v1")
	app.Get("/v2", func(ctx *fiber.Ctx) {})
	v1.Get("/v2", func(ctx *fiber.Ctx) {})
}
```

app.Get (200)
![image](https://user-images.githubusercontent.com/31433480/86616463-738a9000-bfe8-11ea-8e71-d03ea2e1a24d.png)

app.Post (405 but 404)
![image](https://user-images.githubusercontent.com/31433480/86616449-6ec5dc00-bfe8-11ea-8bed-f6d7faae310e.png)

v1.Get (200)
![image](https://user-images.githubusercontent.com/31433480/86616492-7d13f800-bfe8-11ea-8104-3afeda1f632f.png)

v1.Post (405 but 404)
![image](https://user-images.githubusercontent.com/31433480/86616510-8309d900-bfe8-11ea-94c9-4a8f6577fe99.png)

**Comment by Fenny** [comment]
@Aoi-hosizora, thank you for your detailed bug report. Do you mind creating a separate issue regarding this matter?

**Comment by Aoi-hosizora** [comment]
@Fenny Yes, new issue: https://github.com/gofiber/fiber/issues/556

**Comment by subzero911** [comment]
Trying to create a simple API, got 405 error on DELETE request:
![image](https://user-images.githubusercontent.com/12999702/113521149-3fa4c100-95a0-11eb-83a0-ba64b7069e99.png)
