### ISSUE TITLE
🤔  Is it possible to proxy connection without being closed right afterwards?

### ISSUE THREAD

**Issue by jkuri** [gofiber/fiber#494]
Hi, I am trying to use [gobwas/ws](https://github.com/gobwas/ws) WebSocket server with `fiber`. I need to proxy connection to the websocket server running on `localhost:7100`. If you check code snippet below, it actually works but connection get closed right after it is established. Is it possible for this connection to remain open? Thanks.

```go
package main

import (
	"fmt"

	"github.com/gofiber/fiber"
	"github.com/gofiber/fiber/middleware"
	"github.com/valyala/fasthttp"
)

func main() {
	app := fiber.New()

	app.Use(middleware.Logger())

	app.Get("/ws", func(c *fiber.Ctx) {
		req := &c.Fasthttp.Request
		res := &c.Fasthttp.Response
		client := &fasthttp.HostClient{Addr: "0.0.0.0:7100"}
		if err := client.Do(req, res); err != nil {
			fmt.Printf("error: %v\n", err)
		}
		c.Fasthttp.Conn().Close()
	})

	app.Listen(":3300")
}
```

**Comment by Fenny** [comment]
Remove the `c.Fasthttp.Conn().Close()`

```go
package main

import (
	"fmt"
	"log"
	"net/http"

	"github.com/gobwas/ws"
	"github.com/gobwas/ws/wsutil"
	"github.com/gofiber/fiber"
	"github.com/gofiber/fiber/middleware"
	"github.com/valyala/fasthttp"
)

func main() {
	go websocket()

	app := fiber.New()

	app.Use(middleware.Logger())

	app.Get("/ws", func(c *fiber.Ctx) {
		req := &c.Fasthttp.Request
		res := &c.Fasthttp.Response
		client := &fasthttp.HostClient{Addr: "0.0.0.0:7100"}
		if err := client.Do(req, res); err != nil {
			fmt.Printf("error: %v\n", err)
		}
	})

	log.Fatal(app.Listen(":3300"))
}

func websocket() {
	log.Fatal(http.ListenAndServe(":7100", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		conn, _, _, err := ws.UpgradeHTTP(r, w)
		if err != nil {
			fmt.Println(err)
		}
		go func() {
			defer conn.Close()

			for {
				msg, op, err := wsutil.ReadClientData(conn)
				if err != nil {
					fmt.Println(err)
					break
				}
				if err := wsutil.WriteServerMessage(conn, op, msg); err != nil {
					fmt.Println(err)
					break
				}
			}
		}()
	})))
}
```
![](https://i.imgur.com/LrhTVHa.png)

**Comment by jkuri** [comment]
Hi @Fenny, thanks alot for your answer. I tried with that and it gets connected, but I have issues when refreshing the browser websocket hits `GET /` but I never set url without `/ws` path. If I close the connection with `c.Fasthttp.Conn().Close()` then this does not happen.
I extracted parts from my project, if you have time to check this would awesome.

[fiber-example.zip](https://github.com/gofiber/fiber/files/4809368/fiber-example.zip)

just run `make install && make web` and `make && ./fiber-example`

Thanks!

**Comment by Fenny** [comment]
I'm not sure what you mean, I run your example and everything seems to work correctly. Could you try to be more specific what you mean with:

> but I have issues when refreshing the browser websocket hits GET / but I never set url without /ws path.

**Comment by jkuri** [comment]
Try refreshing browser couple of times, error happens randomly. 
This is my log:
```sh
        _______ __
  ____ / ____(_) /_  ___  _____
_____ / /_  / / __ \/ _ \/ ___/
  __ / __/ / / /_/ /  __/ /
    /_/   /_/_.___/\___/_/ v1.12.0
Started listening on 0.0.0.0:3300
websocket connection upgraded!
01:01:16 GET /ws - 127.0.0.1 - 101 - 1.529007ms
websocket connection upgraded!
01:01:21 GET /ws - 127.0.0.1 - 101 - 407.584µs
01:01:23 GET / - 127.0.0.1 - 404 - 11.437µs
websocket connection upgraded!
01:01:25 GET /ws - 127.0.0.1 - 101 - 332.52µs
```

sometimes requests `GET /` and not `GET /ws` as expected.

**Comment by Fenny** [comment]
I tried it again but everything seems to work fine.
`/` results in a 404
`/ws` in the browser results in a 400 bad handshake
`/ws` using the WebSocket protocol works fine

So everything works accordingly, could be on your end ( browser plugins? ).
I even tried it using curl in cmd, same results.

```go
Started listening on 0.0.0.0:3000
error: handshake error: bad "Connection" header
01:08:33 GET /ws - 127.0.0.1 - 400 - 4.9992ms
01:08:34 GET /ws - 127.0.0.1 - 400 - 0s
error: handshake error: bad "Connection" header
01:08:34 GET /ws - 127.0.0.1 - 400 - 2.9702ms
error: handshake error: bad "Connection" header
01:08:35 GET /ws - 127.0.0.1 - 400 - 4.0261ms
error: handshake error: bad "Connection" header
01:08:35 GET /ws - 127.0.0.1 - 400 - 983.8µs
error: handshake error: bad "Connection" header
error: handshake error: bad "Connection" header
01:08:36 GET /ws - 127.0.0.1 - 400 - 2.0174ms
01:08:36 GET /ws - 127.0.0.1 - 400 - 2.0005ms
error: handshake error: bad "Connection" header
01:08:37 GET /ws - 127.0.0.1 - 400 - 3.002ms
error: handshake error: bad "Connection" header
01:08:37 GET /ws - 127.0.0.1 - 400 - 1.9944ms
error: handshake error: bad "Connection" header
websocket connection upgraded!
01:08:41 GET /ws - 127.0.0.1 - 101 - 2.9992ms
```

**Comment by jkuri** [comment]
its not a problem on frontend side, I just use rxjs to autoreconnect if connection fails. but its true this issue seems like more related to the fasthttp directly than fiber. I can close the issue and ask there if you'd like.

**Comment by Fenny** [comment]
Yeah, that might be a better option, sorry I cannot help you :(

**Comment by jkuri** [comment]
no problem, I can still use gofiber/websocket package.
