### ISSUE TITLE
🚀 Signed and Temporary Routes

### ISSUE THREAD

**Issue by itsursujit** [gofiber/fiber#498]
**Is your feature request related to a problem?**
No
**Describe the solution you'd like**
Most of the 2FA or verification process required to have one time access to specific URL. If Fiber could provide interface to define Temporary Routes or Signed Routes.

Possible Interface:

```go
app.Temporary("/coupon/:code", func(c *fiber.Ctx) {

}
// Some way to define Expiry for the specific tempory route. For .e.g &Temporary{Expiry: 1 * time.Hour}
```

```go
app.SignedGet("/email/verify/:token", func(c *fiber.Ctx) { // GET | POST | PUT | DELETE

}
// Some way to define Expiry for the specific tempory route. For .e.g &Temporary{Expiry: 1 * time.Hour, UseOnce: true}
```
And we could generate Temporary or Signed Routes via
`url.SignedRoute` or `url.TemporaryRoute`

**Comment by Fenny** [comment]
I'm not sure if this logic belongs within a _Web Framework_. I think it's up to the user to handle specific tasks/logic within the routes. Correct me if I'm wrong, but you are trying to remove the specific route if after _x_ amount of time from the stack?

**Comment by itsursujit** [comment]
I mean something like this: 
https://www.atyantik.com/signed-url-signed-routes-laravel-5-6/
https://medium.com/@DarkGhostHunter/laravel-combining-signed-routes-with-temporal-tokens-c5177769b432

system would not remove the route but invalidate the route based on configurations we set for the route
It does not actually fall under Web Framework. I'm assuming it to be middleware.

**Comment by Fenny** [comment]
Thanks for the links, this could be a possible feature as a third-party middleware.
Fiber tries to simulate the same API/behavior as expressjs, and personally I think that signed/expiring routes should be handled by the user.

I'm willing to add a third-party middleware it to the official list, please re-open this issue if you have further questions/remarks. Thank you 👍
