### ISSUE TITLE
🤔  kill prefork master

### ISSUE THREAD

**Issue by kiyonlin** [gofiber/fiber#501]
**Question description**
When using prefork mode, and i kill master process manually, but all the children processes are alive.

And when I killed nginx master process, all the processes were terminated.

So is it possible for Fiber to manage all processes?

**Comment by ReneWerner87** [comment]
@Fenny i think we need this logic https://github.com/valyala/fasthttp/blob/master/prefork/prefork.go#L186

**Comment by Fenny** [comment]
Working on it, next tag will also support Prefork for windows using `REUSEADDR` instead of `REUSEPORT` 👍
