### ISSUE TITLE
🤔 what about providing other json packages tags

### ISSUE THREAD

**Issue by kiyonlin** [gofiber/fiber#515]
**Question description**
Users can replace the standard json package to improve performance.

**Code snippet** _Optional_

```bash
go build -tags=jsoniter
```

**Comment by Fenny** [comment]
Related: https://github.com/json-iterator/go/issues/455 https://github.com/gofiber/fiber/issues/381
@kiyonlin are you already part of our [Discord](https://gofiber.io/discord) community?

**Comment by kiyonlin** [comment]
Wow that’s amazing! Thanks for the benchmark info!

Btw, I join the discord already but not use the very often.

I’ll close the issue. I’m not search the older issues. Sorry for that.
