### ISSUE TITLE
HTTP2 support

### ISSUE THREAD

**Issue by bashery** [gofiber/fiber#521]
Is there a plan to support HTTP2
Thank you

**Comment by koddr** [comment]
Hi! 👋 

Please, look at this issue: valyala/fasthttp/issues/144
Fiber can support HTTP/2 only when Fasthttp implements it.

**Comment by Fenny** [comment]
Duplicate https://github.com/gofiber/fiber/issues/262

**Comment by bashery** [comment]
Thanks to all
