### ISSUE TITLE
🚀 support for openid connect middleware

### ISSUE THREAD

**Issue by adpande** [gofiber/fiber#527]
It would be really good to have openid connect middleware to authenticate against 3rd party auth services like keycloak.

Thanks!

**Comment by thomasvvugt** [comment]
Hi @adpande, thanks for bringing this up!
However, I'd rather see multi-provider OAuth middlewares, afaik OpenID is an identification layer on top of OAuth 2.0.

**Comment by Fenny** [comment]
I'm closing this, for now, third-party middleware implementations are always welcome.
