### ISSUE TITLE
🚀 AWS Lambda Go Api Proxy

### ISSUE THREAD

**Issue by lucasmdomingues** [gofiber/fiber#536]
Fiber package to use on aws lambda with proxy.

[https://github.com/awslabs/aws-lambda-go-api-proxy](https://github.com/awslabs/aws-lambda-go-api-proxy)

**Comment by renanbastos93** [comment]
I liked it. @Fenny I believe that we must update the development board to Fiber with this issue.

**Comment by Fenny** [comment]
I made a start https://github.com/Fenny/aws-lambda-go-api-proxy/tree/master/fiber :+1:
