### ISSUE TITLE
🤔 Having problem with static files with build to docker

### ISSUE THREAD

**Issue by maxlibin** [gofiber/fiber#543]
**Question description**

Hi, I am having a weird problem with docker build.

I am server the static file with wildcard like this

```
app.Static("/*", "./client")
```

this works with local `go run main.go`
however it does not work when I build in docker, any idea why? the reason that I am doing this is because I need to server the client side( react app) with react-router when I refresh the page it return 404 without wildcard.

**Comment by Fenny** [comment]
Hi @maxlibin, what Fiber version are you using?

**Comment by maxlibin** [comment]
Hi @Fenny I am using `github.com/gofiber/fiber v1.12.4`.
Well at first I have a lower version but even when I upgraded to v1.12.4 and still having same problem.

**Comment by Fenny** [comment]
Oke great, let's try to resolve this issue.
Could you provide a little bit more information so I could reproduce the issue on my end?

- What kind of files/folders fall under `./client`
- What OS are you using
- What is your docker command

If you could answer these questions that would be great!

**Comment by maxlibin** [comment]
Thanks for the quick response, here's my dockerfile command.
I am using Mac, and the file inside `./client` is a simple react built source. with index.html and a javascript file. Between just to be clear what do I mean by notworking, if I use `"/*"` I get a blank page with `uncaught syntaxError: unexpected token '<'`

```
FROM golang:1.14 AS builder

ADD . /app
WORKDIR /app/server

# Copy go mod and sum files
# COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-w" -a -o /main ..

# Build the React application
FROM node:alpine AS node_builder
COPY --from=builder /app/frontend ./
# RUN npm install -g yarn
RUN yarn && yarn build

# Final stage build, this will be the container
# that we will deploy to production
FROM alpine:latest
RUN apk --no-cache add ca-certificates
COPY --from=builder /main ./
COPY --from=node_builder /build ./client

RUN chmod +x ./main
EXPOSE 8080
CMD ./main
```

**Comment by Fenny** [comment]
I tested the same setup using only a `index.html` file on Windows with success. I'm running out of time, I will take a deeper look tomorrow to see if I can reproduce the same behavior.

PS: Did you also test if a single file works instead of a directory?

**Comment by maxlibin** [comment]
As far as I can see `index.html` works, but not with loading Js files,
`app.Static("/", "./client")` works, however if I refresh the react-router localhost:8000/xxxx, it returns 404.

<img width="752" alt="Screenshot 2020-07-05 at 1 21 08 PM" src="https://user-images.githubusercontent.com/1277038/86526142-83a84f80-bec2-11ea-88b9-180b707b42c3.png">

**Comment by kiyonlin** [comment]
@maxlibin Could you please capture the network tab?

**Comment by maxlibin** [comment]
<img width="1418" alt="Screenshot 2020-07-05 at 2 43 59 PM" src="https://user-images.githubusercontent.com/1277038/86527084-fb2fac00-becd-11ea-9213-13a0e3617f2a.png">

**Comment by kiyonlin** [comment]
Interesting 🤔️

This is my spa solution:
```go
package main

import (
	"github.com/gofiber/fiber"
	"log"
)

func main() {
	// Create new Fiber instance
	app := fiber.New()

	// serve Single Page application on "/public"
	// assume static file at dist folder
	app.Static("/", "public")

    // intercept api routes
	apiGroup := app.Group("/api")
	{
		apiGroup.Get("/user", func(c *fiber.Ctx) {
			c.JSON(fiber.Map{"id": 1, "name": "kiyon"})
		})
	}
    // other routes just return `public/index.html`, angular will handle them
	app.Get("/*", func(c *fiber.Ctx) {
		if err := c.SendFile("public/index.html"); err != nil {
			c.Next(fiber.ErrInternalServerError)
		}
	})

	// Start server on http://localhost:3000
	log.Fatal(app.Listen(3000))
}
```

I wonder if it will help you.

And here's the simple [demo](https://github.com/kiyonlin/fiblar-demo)

**Comment by maxlibin** [comment]
@kiyonlin  wow this solutions works great, I am missing 

```
app.Get("/*", func(c *fiber.Ctx) {
		if err := c.SendFile("public/index.html"); err != nil {
			c.Next(fiber.ErrInternalServerError)
		}
	})
```

what I did previously is I am server public folder with  just `app.Static("/*", "public")`

case closed, thanks for the help guys!
