### ISSUE TITLE
🐛 405 is not responded when use middleware

### ISSUE THREAD

**Issue by Aoi-hosizora** [gofiber/fiber#556]
**Version**

Fiber: 1.12.4
Golang: 1.14

**Description**

Although there is another method on the same path, it still respond 404 if I use middleware. And if there is no middleware, 405 will be responded.

Refer from https://github.com/gofiber/fiber/issues/492.

**Code snippet**

Here is my code:

```go
func main() {
	app := fiber.New()

	app.Use(recover.New()) // <<<
	app.Use(logger.New()) // <<<

	app.Get("/v1", func(ctx *fiber.Ctx) {})
	app.Post("/v1", func(ctx *fiber.Ctx) {})

	_ = app.Listen("2333")
}
```

Some result with middleware:

```log
$ curl 127.0.0.1:2333/v1 -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 2333 (#0)
> GET /v1 HTTP/1.1
> Host: 127.0.0.1:2333
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 07 Jul 2020 03:47:19 GMT
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact

$ curl 127.0.0.1:2333/v1 -X PUT -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 2333 (#0)
> PUT /v1 HTTP/1.1
> Host: 127.0.0.1:2333
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Tue, 07 Jul 2020 03:47:43 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 14
<
Cannot PUT /v1* Connection #0 to host 127.0.0.1 left intact
```

![image](https://user-images.githubusercontent.com/31433480/86704990-fbec4d80-c047-11ea-93e8-8266d4cf41d8.png)

Some result without middleware:

```log
$ curl 127.0.0.1:2333/v1 -X POST -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 2333 (#0)
> POST /v1 HTTP/1.1
> Host: 127.0.0.1:2333
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Date: Tue, 07 Jul 2020 03:48:14 GMT
< Content-Length: 0
<
* Connection #0 to host 127.0.0.1 left intact

$ curl 127.0.0.1:2333/v1 -X PUT -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 2333 (#0)
> PUT /v1 HTTP/1.1
> Host: 127.0.0.1:2333
> User-Agent: curl/7.55.1
> Accept: */*
>
< HTTP/1.1 405 Method Not Allowed
< Date: Tue, 07 Jul 2020 03:48:35 GMT
< Content-Type: text/plain; charset=utf-8
< Content-Length: 14
< Allow: GET, HEAD, POST
<
Cannot PUT /v1* Connection #0 to host 127.0.0.1 left intact
```

![image](https://user-images.githubusercontent.com/31433480/86704923-ed059b00-c047-11ea-8a2a-cfc060255d50.png)

**Comment by seefs001** [comment]
Please go to middleware to post the issue

**Comment by kiyonlin** [comment]
@seefs001 It's related to fiber core.
```
func Test_App_MethodNotAllowed(t *testing.T) {
	app := New()
	app.Use(func(ctx *Ctx) {
		ctx.Next()
	})
	// ...
}
```
Add any middleware will failed the `Test_App_MethodNotAllowed`.

**Comment by Fenny** [comment]
Thanks for providing good information regarding this bug report @Aoi-hosizora, I can confirm that this is related to the Fiber core router. I will investigate and keep you updated 👍 

PS: Both [Recover()](https://github.com/gofiber/fiber/blob/master/middleware/recover.md) & [Logger()](https://github.com/gofiber/fiber/blob/master/middleware/logger.md) are now part of the Fiber middleware core.
```go
import (
  "github.com/gofiber/fiber"
  "github.com/gofiber/fiber/middleware"
)

func main() {
  // ...

  app.Use(middleware.Recover())
  app.Use(middleware.Logger())

  // ...
```

**Comment by Fenny** [comment]
@Aoi-hosizora shipped with `v1.12.5` 👍

**Comment by Aoi-hosizora** [comment]
@Fenny Oh yeah, response code is 405 now, but middleware still outputs 404 (`c.Fasthttp.Response.StatusCode()`).

![image](https://user-images.githubusercontent.com/31433480/87052640-92309700-c233-11ea-99d5-56e2b95d8539.png)

**Comment by kiyonlin** [comment]
Hey @Aoi-hosizora , I think it’s fixed in master branch. Please wait for the next version :smile:

**Comment by Fenny** [comment]
@Aoi-hosizora, could try it with our core logger?
import (
  "github.com/gofiber/fiber"
  "github.com/gofiber/fiber/middleware"
)

func main() {
  // ...

  app.Use(middleware.Logger())

  // ...
}

**Comment by Aoi-hosizora** [comment]
@Fenny Yes, it is same with `github.com/gofiber/logger` I used. Also I developed my own logger middleware, I want the `StatusCode` field to be right as I need it.

![image](https://user-images.githubusercontent.com/31433480/87056758-a9be4e80-c238-11ea-9985-139577a63795.png)

**Comment by Fenny** [comment]
Should be fixed with this PR https://github.com/gofiber/fiber/pull/564

**Comment by Fenny** [comment]
@Aoi-hosizora Tagged in [v1.12.6](https://github.com/gofiber/fiber/releases/tag/v1.12.6) 👍
