### ISSUE TITLE
🤔 How can i get response body after Next()

### ISSUE THREAD

**Issue by ferdigokdemir** [gofiber/fiber#571]
Example for Gin framework here. How can do this in fiber?

```go
package main

import (
	"bytes"
	"fmt"

	"github.com/gin-gonic/gin"
)

type responseBodyWriter struct {
	gin.ResponseWriter
	body *bytes.Buffer
}

func (r responseBodyWriter) Write(b []byte) (int, error) {
	r.body.Write(b)
	return r.ResponseWriter.Write(b)
}

func logResponseBody(c *gin.Context) {
	w := &responseBodyWriter{body: &bytes.Buffer{}, ResponseWriter: c.Writer}
	c.Writer = w
	c.Next()
	fmt.Println("Response body: " + w.body.String())
}

func sayHello(c *gin.Context) {
	c.JSON(200, gin.H{
		"hello": "privationel",
	})
}

func main() {
	r := gin.Default()
	r.Use(logResponseBody)
	r.GET("/", sayHello)
	r.Run()
}
```

**Comment by Fenny** [comment]
Hi @ferdigokdemir, you can still access the Fasthttp core properties if you want to modify/visit the response directly.
```go
c.Fasthttp.Response.Body()
```

**Comment by ferdigokdemir** [comment]
> Hi @ferdigokdemir, you can still access the Fasthttp core properties if you want to visit the response body.
> 
> ```go
> c.Fasthttp.Response.Body()
> ```
Like this?
app.Use(func(c *fiber.Ctx) {
		c.Next()
		print(c.Fasthttp.Response.Body())
	})

**Comment by ferdigokdemir** [comment]
> Hi @ferdigokdemir, you can still access the Fasthttp core properties if you want to visit the response body.
> 
> ```go
> c.Fasthttp.Response.Body()
> ```

Working! thanks a lot.
But i have a another problem. When i activate gzip, body returning byte array :)
I disable it, and i  can see json response.
Must i disable gzip? have a another fix for this?

Example byte array response here

<img width="817" alt="Screen Shot 2020-07-09 at 21 24 00" src="https://user-images.githubusercontent.com/23097465/87076537-95735500-c22a-11ea-99af-0a54a70c78df.png">

**Comment by ferdigokdemir** [comment]
I found a solution :) c.Fasthttp.Response.BodyGunzip() for gzip body.

```go
	app.Use(func(c *fiber.Ctx) {
		c.Next()
		body, err := c.Fasthttp.Response.BodyGunzip()
		if err != nil {
			log.Println(err)
		}
		log.Println(string(body))
	})
```

**Comment by ferdigokdemir** [comment]
Fixed!
