### ISSUE TITLE
🚀  `methodInt` refactor to contain `USE` method

### ISSUE THREAD

**Issue by songjiayang** [gofiber/fiber#589]
**Is your feature request related to a problem?**

currently , the `methodInt` method in `utils.go`  looks like: 

```go
func methodInt(s string) int {
	switch s {
	case MethodGet:
		return 0
        .......
	default:
		return 0
	}
}
```

and we use it check a method is valid method or `USE` in `app.go`, it's too cumbersome:

```go
func (app *App) register(method, pathRaw string, handlers ...Handler) *Route {
         .....
	if method != "USE" && methodInt(method) == 0 && method != MethodGet {
		log.Fatalf("Add: Invalid HTTP method %s", method)
	}
       ....
}
```

**Describe the solution you'd like**

- change `methodInt` default value to -1.
- add MethodUSE to `methodInt` case.

code looks like:

```go
func methodInt(s string) int {
	switch s {
	case MethodUse:
		return 9
        .......
	default:
		return -1
	}
}
```

then the above check code can change to :

```
func (app *App) register(method, pathRaw string, handlers ...Handler) *Route {
         .....
	if methodInt(method) == -1 {
		log.Fatalf("Add: Invalid HTTP method %s", method)
	}
       ....
}
```

**Comment by Fenny** [comment]
PR https://github.com/gofiber/fiber/pull/594 got merged, thanks guys 👍

**Comment by thomasvvugt** [comment]
Nice work, let us know whether the issue is resolved! 👍🏼

**Comment by songjiayang** [comment]
fixed so quickly，confirm  it resolved
