### ISSUE TITLE
🤔 Dynamically Remove Routes

### ISSUE THREAD

**Issue by Zeedinstein** [gofiber/fiber#600]
Is there a way to dynamically remove routes from `fiber.App` or a `fiber.Group`, so that the route can not be accessed anymore and removed from memory. This is something I could do in express by accessing the `app.stack` which was just an array of the configured routes. 

I see in fiber I can get all the configured routes using `app.Routes()` but I don't have access to `app.stack`

Is this possible to do with fiber?

**Comment by Fenny** [comment]
Hi @Zeedinstein, our private `stack` is not really user friendly and rather complex that could cause problems when changing it.
I suggest we add some kind of `Remove()` / `Delete()` method and the `Route` struct, since `app.Routes()` returns route pointers we could make a safe function that will remove it from the stack.

We have to think this through before making any changes, so feedback is welcome!

**Comment by Zeedinstein** [comment]
Yeah looking at the source code I can see why it's complicated. 

You would probably have to rebuild the app's stack array.

**Comment by Zeedinstein** [comment]
Here is the code I tried to get working(It's probably not the best code to do this):

```
func (app *App) Remove(method string, path string) {
	method = strings.ToUpper(method)
	methodINT := methodInt(method)
	if methodINT != -1 {
		removed := false
		newStack := make([][]*Route, len(intMethod))
		for x, route := range app.stack[methodINT] {
			if route.path == path {
				app.routes--
				removed = true
				continue
			}
			if removed {
				app.stack[methodINT][x].pos = x - 1
				newStack[methodINT] = append(app.stack[methodINT], app.stack[methodINT][x])
			} else {
				newStack[methodINT] = append(app.stack[methodINT], app.stack[methodINT][x])
			}
		}
		app.stack = newStack
	}
}
```

This passes this test:
```
func Test_App_Remove(t *testing.T) {
	app := New()
	h := func(c *Ctx) {}
	app.Get("/Get", h)
	app.Head("/Head", h)
	app.Post("/post", h)
	utils.AssertEqual(t, 3, len(app.Routes()))
	app.Remove("GET", "/Get")
	utils.AssertEqual(t, 2, len(app.Routes()))
}
```

But fails for this test:
```
func Test_App_Remove(t *testing.T) {
	app := New()
	h := func(c *Ctx) {}
	app.Get("/Get", h)
	app.Head("/Head", h)
	app.Post("/post", h)
	utils.AssertEqual(t, 3, len(app.Routes()))
	app.Remove("GET", "/Get")
	utils.AssertEqual(t, 2, len(app.Routes()))
	resp, err := app.Test(httptest.NewRequest("GET", "/Get", nil))
	utils.AssertEqual(t, nil, err)
	utils.AssertEqual(t, 404, resp.StatusCode)
}
```

So it updates the `app.stack` but not the actual routes. So I'm not sure how the routes are getting registered in memory.

**Comment by kiyonlin** [comment]
Thanks for your suggestion @Zeedinstein . Removing routes dynamically will effect requests which are matching routes. That’ll cost a lot to ensure data security.

Let us know whether the issue is resolved!

**Comment by Fenny** [comment]
I have to agree with @kiyonlin, I don't think a web framework should solve use case specific problems.

A better approach would be to have an one catch all handler and execute your application logic there.
I.e. lookup the user registered routes and act accordingly.

**Comment by jozsefsallai** [comment]
I would like to see a real-world use case of deleting routes dynamically

**Comment by camdenorrb** [comment]
Modular routes, boom big use case
