### ISSUE TITLE
End this framework; it's a total copy of Gin

### ISSUE THREAD

**Issue by DGKSK8LIFE** [gofiber/fiber#631]

**Comment by Fenny** [comment]
Hi @DGKSK8LIFE, welcome to to Fiber! Could you please elaborate why we are a copy of Gin?

**Comment by DGKSK8LIFE** [comment]
> Hi @DGKSK8LIFE, welcome to to Fiber! Could you please elaborate why we are a copy of Gin?

Your syntax is the almost the exact same as Gin. Sorry I see that the codebase is different now. My bad

**Comment by Fenny** [comment]
I can assure you that we do not copy code without crediting the authors. Our API is inspired by the [expressjs](https://github.com/expressjs/express) framework.
