### ISSUE TITLE
🐛 1.13.0 breaks logger for Windows

### ISSUE THREAD

**Issue by MarvinJWendt** [gofiber/fiber#639]
**Fiber version:** 1.13.0

The new color support for the logger Middleware doesn't display the colors correctly in Windows.

![image](https://user-images.githubusercontent.com/31022056/87863892-1a641a00-c961-11ea-9720-7e15cd3585c0.png)

**Comment by Fenny** [comment]
We are working on a fix, expect a hotfix tomorrow 👍 
To avoid this issue on Windows for now, just pass an own io.Reader to the logger.

**Comment by Fenny** [comment]
@MarvinJWendt tagged under `v1.13.1` 👍
