### ISSUE TITLE
🤔 Server Sent Events

### ISSUE THREAD

**Issue by bashery** [gofiber/fiber#646]
**Question description**

Would providing sse as a Middleware -or any plugin type - be a good idea for fiber?. I think it would be useful for some cases covered by websocket are a lot complicated and resource consumption

**Comment by Fenny** [comment]
Hi @bashery, sorry for the late reply! I personally never worked with SSE, but we are willing to add this to our middleware list if you made one 👍

**Comment by rafaelgfirmino** [comment]
This issue is close, but I can use fiber and Server-Sent Events using a [gofiber/adaptor](https://github.com/gofiber/adaptor)

This is a part of the code where I add gofiber/adaptor
```go
app.Get("/sse/dashboard", adaptor.HTTPHandler(handler(dashbaordHandler)))
```
I'm using this [example ](https://www.youtube.com/watch?v=xbGYiJ_u7_4) bellow
```go 
// main.go
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/gofiber/fiber/v2"
	"math/rand"
	"net/http"
	"time"
	"github.com/gofiber/adaptor/v2"

	log "github.com/sirupsen/logrus"
)

var (
	counter     int
	clients     map[string]*Client
	clientsList []string
)

type (
	Client struct {
		name   string
		events chan *DashBoard
	}
	Currency float64
	Item     struct {
		Name     string   `json:"name,omitempty"`
		Quantity int      `json:"quantity,omitempty"`
		Price    Currency `json:"price,omitempty"`
	}
	Store struct {
		Items map[string]Item `json:"items,omitempty"`
	}
	DashBoard struct {
		Users         uint       `json:"users,omitempty"`
		UsersLoggedIn uint       `json:"users_logged_in,omitempty"`
		Inventory     *Store     `json:"inventory,omitempty"`
		ChartOne      []int      `json:"chart_one,omitempty"`
		ChartTwo      []Currency `json:"chart_two,omitempty"`
	}
)

func main() {
	app := fiber.New()
	clients = make(map[string]*Client)
	go updateDashboard()
	http.Handle("/teste", http.FileServer(http.Dir("client")))
	app.Get("/sse/dashboard", adaptor.HTTPHandler(handler(dashbaordHandler)))
	app.Listen(":3000")
}

func handler(f http.HandlerFunc) http.Handler {
	return http.HandlerFunc(f)
}
func dashbaordHandler(w http.ResponseWriter, r *http.Request) {
	log.Infof("Client: %v", r.RemoteAddr)
	client := clients[r.RemoteAddr]
	if nil == client {
		client = addClient(r.RemoteAddr)
	}

	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type")
	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")

	timeout := time.After(1 * time.Second)
	select {
	case ev := <-client.events:
		var buf bytes.Buffer
		enc := json.NewEncoder(&buf)
		enc.Encode(ev)
		fmt.Fprintf(w, "data: %v\n\n", buf.String())
		fmt.Printf("data: %v\n", buf.String())
	case <-timeout:
		fmt.Fprintf(w, ": nothing to sent\n\n")
	}

	if f, ok := w.(http.Flusher); ok {
		f.Flush()
	}
}
func addClient(s string) *Client {
	c := &Client{name: s, events: make(chan *DashBoard, 10)}
	clients[s] = c
	clientsList = append(clientsList, s)
	return c
}
func updateDashboard() {
	for {
		inv := updateInventory()
		db := &DashBoard{
			Users:         uint(rand.Uint32()),
			UsersLoggedIn: uint(rand.Uint32() % 200),
			Inventory:     inv,
			ChartOne:      []int{2, 35, 634, 93, 390432},
			ChartTwo:      []Currency{3.59, 6.09, 563.90},
		}

		client := getClient()
		if nil != client {
			client.events <- db
		}
	}
}
func getClient() *Client {
	if 0 == len(clientsList) {
		return nil
	}

	r := rand.Int() % len(clientsList)
	s := clientsList[r]
	return clients[s]
}
func updateInventory() *Store {
	inv := &Store{}
	inv.Items = make(map[string]Item)
	a := Item{Name: "Books", Price: 33.59, Quantity: int(rand.Int31() % 53)}
	inv.Items["book"] = a
	a = Item{Name: "Bicycles", Price: 190.89, Quantity: int(rand.Int31() % 232)}
	inv.Items["bicycle"] = a
	a = Item{Name: "Water Bottles", Price: 10.02, Quantity: int(rand.Int31() % 93)}
	inv.Items["wbottle"] = a
	a = Item{Name: "RC Car", Price: 83.19, Quantity: int(rand.Int31() % 73)}
	inv.Items["rccar"] = a
	return inv
}
```

call this function in you HTML page

```js
//js file
export default function onLoad() {
    var source = new EventSource("http://localhost:3000/sse/validation")
    source.onmessage = (event) => {
        console.log("OnMessage Called:")
        console.log(event)
        console.log(JSON.parse(event.data))
    }
}
```

**Comment by H0mAUnm** [comment]
I'm new to fiber
i couldn't make it work without issues.
there is some error in the browser console.
and the timing of sending data is not controllable.
`
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math/rand"
	"net/http"
	"time"

	"github.com/gofiber/adaptor/v2"
	"github.com/gofiber/fiber/v2"
)

// Client represents a connected client with an address and a channel for user events.
type Client struct {
	address      string          // The address of the connected client
	eventChannel chan *UserEvent // Channel to send user events to the client
}

// UserEvent represents the data structure sent to clients.
type UserEvent struct {
	UserID uint `json:"user_id"` // The unique identifier for the user
}

func main() {
	app := fiber.New() // Create a new Fiber application

	app.Static("/", "./public") // Serve static files from the "public" directory

	// Set up the SSE endpoint for user events
	app.Get("/sse/user-events", adaptor.HTTPHandler(http.HandlerFunc(handleUserEvents)))
	app.Listen(":3000") // Start the server on port 3000
}

// handleUserEvents handles incoming SSE connections and streams user events.
func handleUserEvents(w http.ResponseWriter, r *http.Request) {
	fmt.Printf("Client connected: %v\n", r.RemoteAddr) // Log the client's address

	// Create a new Client instance for the connected client
	client := &Client{
		address:      r.RemoteAddr,              // Set the client's address
		eventChannel: make(chan *UserEvent, 10), // Create a buffered channel for user events
	}
	go generateUserEvents(client) // Start generating user events in a separate goroutine

	// Set headers for SSE
	w.Header().Set("Access-Control-Allow-Origin", "*")             // Allow cross-origin requests
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type") // Allow specific headers
	w.Header().Set("Content-Type", "text/event-stream")            // Set content type for SSE
	w.Header().Set("Cache-Control", "no-cache")                    // Prevent caching of the response
	w.Header().Set("Connection", "keep-alive")                     // Keep the connection open

	// Stream events from the channel with a timeout
	select {
	case event := <-client.eventChannel: // Wait for an event from the channel
		var buffer bytes.Buffer                         // Create a buffer to hold the encoded event
		encoder := json.NewEncoder(&buffer)             // Create a JSON encoder
		encoder.Encode(event)                           // Encode the event as JSON
		fmt.Fprintf(w, "data: %s\n\n", buffer.String()) // Send the event data to the client
		fmt.Printf("Sent data: %s\n", buffer.String())  // Log the sent data
	case <-time.After(5 * time.Second): // Wait for 5 seconds for an event
		fmt.Fprintf(w, ": no data to send\n\n") // Send a message if no event is received
	}

	// Flush the response to the client
	if flusher, ok := w.(http.Flusher); ok {
		flusher.Flush() // Flush the buffered data to the client
	}
}

// generateUserEvents continuously generates user events and sends them to the client.
func generateUserEvents(client *Client) {
	for {
		event := &UserEvent{
			UserID: uint(rand.Uint32()), // Generate a random UserID
		}
		client.eventChannel <- event       // Send the new event to the channel
		time.Sleep(500 * time.Millisecond) // Sleep for 0.5 seconds before generating the next event
	}
}
` 

`
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Server-Sent Events Example</title>
</head>

<body>
    <h1>Server-Sent Events Example</h1>

    <script>
        // Function to set up the EventSource connection
        function setupEventSource() {
            // Create a new EventSource to listen for events from the server
            const source = new EventSource("/sse/user-events");

            // Event handler for receiving messages
            source.onmessage = function (event) {
                console.log("OnMessage Called:"); // Log when a message is received
                console.log(event); // Log the entire event object

                // Parse the JSON data received from the server
                let data = JSON.parse(event.data);
                console.log(data); // Log the parsed data
            };

            // Event handler for errors
            source.onerror = function (event) {
                console.error("EventSource failed:", event); // Log any errors
                // source.close(); // Uncomment to close the connection on error
            };
        }

        // Call the setup function on window load
        window.onload = setupEventSource; // Initialize the EventSource connection when the page loads
    </script>
</body>

</html>
`
