### ISSUE TITLE
🐛  Port is in use 

### ISSUE THREAD

**Issue by mahendrabagul** [gofiber/fiber#647]
**Fiber version**
1.13.1
**Issue description**
When the port(e.g. 3000) is being used by some other process and gofiber code is run, there is no message printed on the console to know the user that **the port is in use**  
**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  // Steps to reproduce

  app.Listen(3000)
}
```
You can run any service on port 3000 and then run sample gofiber code on the same port. The command `go run main.go` won't show you any error.

![Screenshot from 2020-07-19 23-21-28](https://user-images.githubusercontent.com/6149190/87881543-90c35380-ca17-11ea-8b3d-f9ee8f0cf759.png)

**Comment by ReneWerner87** [comment]
thanks for the bug report

as described here in the signature, app.Listen returns an error, 
https://docs.gofiber.io/app#listen

use the log or fmt package to display the error
https://github.com/gofiber/recipes/blob/master/hello-world/main.go#L21

```go
func main() {
	app := fiber.New()

	log.Fatal(app.Listen(3001))
}
```
then you get the error output
![image](https://user-images.githubusercontent.com/7063188/87886440-34fbc900-ca1d-11ea-8a2d-af16af8831bc.png)

**Comment by Fenny** [comment]
Added to the TODO list 👍
