### ISSUE TITLE
🚀 Cancel the context if the client closes the connection

### ISSUE THREAD

**Issue by doingodswork** [gofiber/fiber#648]
**Is your feature request related to a problem?**

Servers usually do some kind of "expensive" operation, like a DB lookup or insertion, some computation, network requests to other services etc.

If the client has set a timeout of for example 1s and the connection is closed after 1s, then the server should be able to be notified of this and stop continueing with these operations.

The regular pattern for this in Go, independent from server-side software, is to pass a `context.Context` across all function calls as first parameter, and *before* starting some expensive operation, check if the context was canceled or if it timed out.

Here's an example to reproduce that it's currently not implemented:

```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/gofiber/fiber"
)

func main() {
	fmt.Println("hello world")

	app := fiber.New()
	app.Get("/ping", func(c *fiber.Ctx) {
		log.Println("handler starting")
		time.Sleep(5 * time.Second) // Some expensive operation
		// Another expensive operation is about to start. Let's check if the context is already canceled first though!
		if err := c.Context().Err(); err != nil {
			log.Printf("context canceled or timed out: %v\n", err)
			c.SendStatus(fiber.StatusRequestTimeout)
			return
		}
		log.Println("starting second expensive operation")
		time.Sleep(5 * time.Second) // Another expensive operation
		log.Println("responding")
		c.SendString("pong")
		log.Println("handler finished")
	})
	log.Fatal(app.Listen("localhost:8080"))
}
```
It already takes 5s for some operation, then checks for a canceled context before another 5s operation.

A client with a 1s timeout is this: `curl -v -m 1 localhost:8080/ping`  
It prints something like this:
```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /ping HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.47.0
> Accept: */*
>
* Operation timed out after 1001 milliseconds with 0 bytes received
* Closing connection 0
curl: (28) Operation timed out after 1001 milliseconds with 0 bytes received
```

While the server prints:
```
2020/07/19 19:00:00 handler starting
2020/07/19 19:00:05 starting second expensive operation
2020/07/19 19:00:10 responding
2020/07/19 19:00:10 handler finished
```

**Describe the solution you'd like**

`fiber.Ctx.Context()` should return a context which is canceled as soon as the client connection is closed.

As it probably requires copying the context with something like `context.WithCancel(...)`, which produces garbage, this feature could be opt-in and configurable via `fiber.Settings`.

**Describe alternatives you've considered**

1. In a handler we can create our own such context, with our own fixed timeout, like so: `ctx := context.WithTimeout(c.Context(), time.Second)` (with `c` being the `fiber.Ctx`), but that only helps us stopping before our *own* set timeout - we still won't know about the client's timeout
2. There's the official [timeout middleware](https://github.com/gofiber/fiber/blob/1129a85058919968103d85a127180d6b47c3029f/middleware/timeout.go), but that also doesn't take the closed client connection into account

**Additional context**

When using the stdlib it works as expected:

```go
package main

import (
	"fmt"
	"log"
	"net/http"
	"time"
)

func main() {
	http.HandleFunc("/ping", func(w http.ResponseWriter, r *http.Request) {
		log.Println("handler starting")
		time.Sleep(5 * time.Second) // Some expensive operation
		// Another expensive operation is about to start. Let's check if the context is already canceled first though!
		if err := r.Context().Err(); err != nil {
			log.Printf("context canceled or timed out: %v\n", err)
			w.WriteHeader(http.StatusRequestTimeout)
			return
		}
		log.Println("starting second expensive operation")
		time.Sleep(5 * time.Second) // Another expensive operation
		log.Println("responding")
		fmt.Fprintf(w, "pong")
		log.Println("handler finished")
	})

	log.Fatal(http.ListenAndServe("localhost:8080", nil))
}
```

Prints (when sending a request with `curl -m 1 localhost:8080/ping`):

```
2020/07/19 19:00:00 handler starting
2020/07/19 19:00:05 context canceled or timed out: context canceled
```

**Comment by thomasvvugt** [comment]
Hi @doingodswork,
I do also see a large performance impact regarding your issue.
You might to take a look at `ctx.Fasthttp.Hijack`, according to [their documentation](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.Hijack) the server skips calling the handler in the following cases:

* 'Connection: close' header exists in either request or response.
* Unexpected error during response writing to the connection.

Let me know if this might help you find a solution in the right direction.
Thanks for bringing up this issue! 🚀

**Comment by Fenny** [comment]
I'm afraid this is not possible and would be hard to add. `net/http` serves the connection in a separate goroutine and is, therefore, able to detect when the connection closes. Fasthttp serves the connection in the same goroutine gained from the workerpool that runs the handler so while your handler is processing the request we can't detect any changes to the connection.
