### ISSUE TITLE
🚀 Document the panic when using the timeout middleware

### ISSUE THREAD

**Issue by doingodswork** [gofiber/fiber#649]
**Is your feature request related to a problem?**

When using the [timeout middleware](https://github.com/gofiber/fiber/blob/1129a85058919968103d85a127180d6b47c3029f/middleware/timeout.go) and the timeout is reached, using the `fiber.Ctx` in a handler leads to a nil pointer panic.

Example code:

```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/gofiber/fiber"
	"github.com/gofiber/fiber/middleware"
)

func main() {
	fmt.Println("hello world")

	app := fiber.New()
	handler := func(c *fiber.Ctx) {
		log.Println("handler starting")
		time.Sleep(2 * time.Second) // Some expensive operation that exceeds the middleware's timeout
		// Another expensive operation is about to start. Let's check if the context is already canceled first though!
		if err := c.Context().Err(); err != nil { // c.Context().Err() panics!
			log.Printf("context canceled or timed out: %v\n", err) // Never reached because of the panic
			c.SendStatus(fiber.StatusRequestTimeout)
			return
		}
		log.Println("responding") // Never reached because of the panic
		c.SendString("pong")      // Without the above `c.Context().Err()` call it would be this place where the panic occurs
		log.Println("handler finished")
	}
	app.Get("/ping", middleware.Timeout(handler, time.Second))
	log.Fatal(app.Listen("localhost:8080"))
}
```

**Describe the solution you'd like**

There's probably not much that can be done here, but it should be documented! When documented, the handler could check the status of the context to see if it can be used or not.

**Describe alternatives you've considered**

**Additional context**

**Comment by thomasvvugt** [comment]
Hi @doingodswork,
Correct me if I am wrong, but the behavior of the errors is documented in timeout.md; `the timeout error is set and forwarded to the error handler`.
We are looking for a neat way to update this into our existing documentation site, [docs.gofiber.io](https://docs.gofiber.io).

**Comment by Fenny** [comment]
We are currently working on adding all middleware documentation to our [website](https://docs.gofiber.io) 👍 I will tag this issue when we make the PR, expect a website update in 1 week +/-
