### ISSUE TITLE
🐛 BodyParser doesn't detect chartset content-types without spaces

### ISSUE THREAD

**Issue by eduardohitek** [gofiber/fiber#650]
**Fiber v1.13.1**

**Fiber is unable to parse a application/json;charset=utf-8 content-type. It was working on v1.12.x version.**

**Code snippet**

```go
type DadosLogin struct {
	Email string `json:"email"`
	Senha string `json:"password"`
}

func recuperarDadosLogin(c *fiber.Ctx) (DadosLogin, error) {
	dadosLogin := new(DadosLogin)
	erro := c.BodyParser(dadosLogin)
	return *dadosLogin, erro
}

"bodyparser: cannot parse content-type: application/json;charset=utf-8"
```

**Comment by ReneWerner87** [comment]
thanks for the bug report

problem is that the content-type header of your request is not perfect, there must be a space between the mime type and the charset declaration

```go
your header:
content-type: application/json;charset=utf-8

expected header:
content-type: application/json; charset=utf-8
```

we have optimized the bodyparser in https://github.com/gofiber/fiber/releases/tag/v1.13.0 and this new behaviour is more strictly, which brings performance

the change:
https://github.com/gofiber/fiber/commit/d61e4785780fb97df19e611cc9d01f73655a3d50#diff-8500aba9f2dd08390bcbe6a506b66564R232

https://github.com/gofiber/fiber/blob/master/utils.go#L305
https://github.com/gofiber/fiber/blob/master/utils.go#L315

**Comment by eduardohitek** [comment]
Thanks for the clarification. I just changed this in my app and everything works fine now. Hope this will help if anyone else face this situation.

**Comment by jos-** [comment]
Thanks for the explanation, the extra space fixes it 👍

It might be good to consider allowing the header without space or update the documentation, since `application/json;charset=utf-8` is the default header axios sends, which is currently difficult to change. See also https://github.com/axios/axios/issues/2623.

**Comment by jos-** [comment]
Thanks for the explanation, the extra space fixes it.

However, this causes many issues while the performance gain is minimal. E.g.

- Axios uses `application/json;charset=utf-8` (without space) as default Content-Type header, which is currently difficult to change, see https://github.com/axios/axios/issues/2623.
- Chrome often sets any charset you specify to `UTF-8` (uppercase), which I haven't found a workaround for yet, see e.g. https://github.com/angular/angular.js/issues/11558.

Please reopen this, thanks.

**Comment by eduardohitek** [comment]
@jos- I was able to solve this, setting an interceptor into my axios.

```
axios.interceptors.request.use((config) => {
  config.headers['Content-Type'] = 'application/json; charset=utf-8'
  return config
})

**Comment by Fenny** [comment]
@jos- our body-parser should be able to handle case insensitive content headers

@eduardohitek _The specification of media types, RFC 2045, does not require a space. Neither does it prohibit a space; this is more implicit, since RFC 2045 refers to the extended BNF as defined in RFC 822, which clarifies this in clause 3.4.2._
Look at the above statement, it might be a good idea to add the _non-space_ variant to the body-parser's switch case

**Comment by jos-** [comment]
@eduardohitek Thanks, I was able to do the same by specifying `headers: { 'Content-Type': 'application/json; charset=utf-8' }` in the axios config.

This works in e.g. Firefox, but not in Chrome/Brave/Chromium, which somehow always sets the charset of PUT/POST requests to uppercase UTF-8 when you specify a charset.

@Fenny Thanks for reopening the issue.

**Comment by Fenny** [comment]
@jos- , @eduardohitek fixed in <https://github.com/gofiber/fiber/releases/tag/v1.13.2> 👍

**Comment by jos-** [comment]
Thanks for the quick fix. Thanks for this great framework 👍

**Comment by eduardohitek** [comment]
Thank u guys!!!!
