### ISSUE TITLE
🤔 render: template login.jet.html does not exist

### ISSUE THREAD

**Issue by petersephrin** [gofiber/fiber#653]
**render: template login.jet.html does not exist**
I am trying to render a view using the jet template engine and somehow it can not be found. It used to work before the update though
Is there something that I'm doing wrong?
**Code snippet** 

```go
app := fiber.New()

	//let app know what template engine we use for the views and shit
	// engine := jet.New("./views", ".jet")
	// app.Settings.Views = engine

	//all images to be accessed in views
	app.Static("/images", "./public/images")

	engine := jet.New("./views/", ".jet")
	app.Settings.Views = engine

```
```go
func GetLogin(c *fiber.Ctx) {
	err := c.Render("login.jet.html", nil)
	if err != nil {
		logrus.Warn(err)
		c.Send(err)
	}

}
```

**Comment by thomasvvugt** [comment]
Hi @petersephrin,
Small question, did you import `github.com/gofiber/template/jet`? You might want to follow the example as shown [here](https://github.com/gofiber/template/tree/master/jet).
Let me know if you have the right imports and are running our latest and compatible versions by running `go get -u` in your project's directory.

**Comment by petersephrin** [comment]
I did. I made the following changes and it works now
```go
	engine := jet.New("./views", ".jet")
```

```go
func GetLogin(c *fiber.Ctx) {
	err := c.Render("login", nil)
	if err != nil {
		logrus.Warn(err)
		c.Send(err)
	}

}
```

I also renamed my views to **login.jet** instead of **login.jet.html**

**Comment by Fenny** [comment]
I'm closing this issue since it's resolved. Make sure you pass the correct template extension on engine initialization 👍
