### ISSUE TITLE
🐛 ctx.IPs() returns wrong result when there is no X-Forwarded-For  in request header

### ISSUE THREAD

**Issue by abowloflrf** [gofiber/fiber#670]
**Fiber version**
v1.13.3

**Issue description**
`fiber.Ctx.IPs()` returns slice of string with one empty string (`[]string{""}`) in it when there is no `X-Forwarded-For`  header. But what I espect is an empty slice of string. I think it's cased by a recent change in #612 

https://github.com/gofiber/fiber/pull/612/files#diff-8500aba9f2dd08390bcbe6a506b66564R501

```go
ips = make([]string, bytes.Count(header, []byte(","))+1)
```

In line L501. I think it's not a good idea to calculate the forward ips' length by the counting the comma becase there could be no `X-Forwarded-For`  field in header.

BTW, should we consider the non-standard HTTP headers? For example in the `X-Forwarded-For` header:

```
a,b,  c # no space or extra space after comma
,a,b    # comma in wrong place
a,,b    # and this
,       # only comma
```

What should  `IPs()` return?  I assume `[]string{a,b,c}` `[]string{a,b}` `[]string{a,b}` `[]string{}` is what we expected, right?

**Comment by abowloflrf** [comment]
What about switching back to the `strings.Split` way, with some improvement:

```go
func (ctx *Ctx) IPs() []string {
	ips := []string{}
	for _, ip := range strings.Split(ctx.Get(HeaderXForwardedFor), ",") {
		trimmedIP := strings.TrimSpace(ip)
		if len(trimmedIP) != 0 {
			ips = append(ips, trimmedIP)
		}
	}
	return ips
}
```

In most cases, there could be only one ip or empty in the `X-Forwarded-For` header.  I think this part is only slight impact on performance 🤔

**Comment by kiyonlin** [comment]
Thanks for your reporting! If the value of `X-Forwarded-For` header is empty, the answer should be empty slice(or nil). 

And we don’t consider non-standard Http headers until now.

**Comment by Fenny** [comment]
@abowloflrf, nice find 👍 should be tagged next week
