### ISSUE TITLE
🤗 

### ISSUE THREAD

**Issue by doctor-windroldev** [gofiber/fiber#674]
**Please help me!  How can I implement authentication and sessions?. With more real project examples.  I've read documentation but doesn't seem to be grasped well when comes to applying them.  May be just because I still have NodeJs mindset**

**Comment by itsursujit** [comment]
@doctor-windroldev In this boilerplate https://github.com/itsursujit/fiber-boilerplate, I've tried to implement authentication and session. Please take a look into the repository and let me know what you think

**Comment by doctor-windroldev** [comment]
Thanks much for quick reply! ..It has helped me so much in understanding sessions though i had to find another boiler-plate for auth, since I didn't focus on jwt...and the reason may be just because I was not specific on which type of auth:) but by the way  I appreciate your support!!! I love fiber!
>>Jesus bless you

**Comment by doctor-windroldev** [comment]
Sorry can you advice me ?... should i use reddis session storage or memcache?

**Comment by itsursujit** [comment]
I think it totally based on case scenario.
Memcache also works just fine.

In my I'm using different ways of authorization:

- Basic Auth with session (Redis)
- JWT based auth

**Comment by doctor-windroldev** [comment]
Thanks dude!
