### ISSUE TITLE
🤗 How about route names for reverse url building by name?

### ISSUE THREAD

**Issue by max107** [gofiber/fiber#676]
**Question description**
How about route names for reverse url building by name?

**Comment by Fenny** [comment]
Hi @max107, could you show us an use-case/example?

**Comment by max107** [comment]
@Fenny 

use-case: easy maintain, generate and refactoring routes. 

With a large number of routes in the application, it becomes difficult to navigate and difficult to change the URL.

## gorilla mux

**Comment by max107** [comment]
@Fenny  

use-case: easy maintain, generate and refactoring routes. 

With a large number of routes in the application, it becomes difficult to navigate and difficult to change the URL.

## gorilla mux

```
r := mux.NewRouter()
r.Host("{subdomain}.example.com").
  Path("/articles/{category}/{id:[0-9]+}").
  Queries("filter", "{filter}").
  HandlerFunc(ArticleHandler).
  Name("article")

// http://news.example.com/articles/technology/42?filter=gorilla
url, err := r.Get("article").URL("subdomain", "news",
                                 "category", "technology",
                                 "id", "42",
                                 "filter", "gorilla")
```

## echo framework

```
func h(c echo.Context) error {
  	return c.String(http.StatusOK, "Hello, World!")
}
e.GET("/hello/:id", h).Name = "foobar"

e.Reverse("foobar", 1234) // /hello/1234
```

**Comment by Fenny** [comment]
@max107 thanks for the example, I will try to see if this is possible to implement with the current [Router](https://godoc.org/github.com/gofiber/fiber#Router) interface 👍

**Comment by Fenny** [comment]
After some discussions and testing, the Team decided that this will not be implemented in the Fiber web framework. We appreciate the idea and feedback either way!

**Comment by max107** [comment]
![https://media1.tenor.com/images/304e3929bb70184f18f85759acf4cb42/tenor.gif?itemid=5240448](https://media1.tenor.com/images/304e3929bb70184f18f85759acf4cb42/tenor.gif?itemid=5240448)
