### ISSUE TITLE
🤔 Help with local packages

### ISSUE THREAD

**Issue by slusarczyk41** [gofiber/fiber#677]
I fight with that for few hours already and still get only errors. Please help me and explain in clear manner 
### How do I import a local package?
The case: 
GOPATH=/home/jacek/Projects - Place where I keep al my projects, including the ones written in Golang

I create a project folder with app.go, where I want to import a local package, so it looks like this:
my_project
-- my_package
-- -- package_file.go
-- app.go

And, obviously, I want to import at app.go "my_project/my_package".

app.go: import("my_project/my_package")
package_file.go: I have a "package my_package" line at the top.

I tried few times with two re-installs of golang, including use of go mod init, and a few blog/videos and stackoverflow questions, and still get either "package is not in GOROOT" or "import cycle is not allowed"

I feel really dumb about that, so don't make it worse and try to explain me like you would explain to complete idiot.

**Comment by itsursujit** [comment]
@slusarczyk41 In simple words, Go doesn't allow round trip between the local packages.
For e.g. 
-- my_package
-- -- package_file.go // content
```go
package my_package

import (
    "your_package"
)

func DoSomeStuff() {
    fmt.Println(third_package.I_HAVE_THIS)
}
```
and on app.go

```go
package your_package

import (
    "my_package"
)

var I_HAVE_THIS string

func main() {
    I_HAVE_THIS = "test"
    my_package.DoSomeStuff()
}
```
and you want to run `go run app.go`.

This will give you that error `import cycle is not allowed`

So only solution is either: 

- define everything that you need in my_package in same level/folder/package OR
- create new package, define commonly used item there. then you can initiate the third package in app.go and package_file.go both.

So as a solution, something like this pseudo code works

```go
package third_package

var I_HAVE_THIS string
```

package_file.go
```go
package my_package

import (
    "third_package"
)

func DoSomeStuff() {
    fmt.Println(third_package.I_HAVE_THIS)
}
```

app.go
```go
package my_package

import (
    "third_package"
    "my_package"
)

func DoSomeStuff() {
    third_package.I_HAVE_THIS = "test"
    my_package.DoSomeStuff()
}
```

Hope that clears your doubt :).

**Comment by Fenny** [comment]
Maybe this is unrelated, but I personally use the `replace` keyword in my `go.mod` files to override external imports
```go
module main

go 1.14

require (
	github.com/gofiber/fiber v1.13.3
)

replace github.com/gofiber/fiber => ../fiber
```

**Comment by youngkin** [comment]
Reading the question I don't see any kind of import cycle defined, only an attempt to import `my_project/my_package` in app.go. Assuming the import really looks like this:
```
 import(
    "my_project/my_package"
)
```

Also assuming your source code is located at `$GOPATH/src/github.com/slusarczyk41/my_project`, then your import needs to look like this:
```
import(
    "github.com/slusarczyk41/my_project/my_package"
)
```

**Comment by Fenny** [comment]
@slusarczyk41, did you managed to make it work?
