### ISSUE TITLE
🚀 Structured logging

### ISSUE THREAD

**Issue by akshaybabloo** [gofiber/fiber#683]
**Describe the solution you'd like**

Google cloud platform's logging can viewed with structured logging, it would be good to have one.

**Describe alternatives you've considered**

I have tried using zap, writing a custom logger, but for some reason the status code comes as 200, and then there is an error.

**Comment by kiyonlin** [comment]
Hey @akshaybabloo Do you mean the middleware logger should support structured logging(e.g. json)?

**Comment by akshaybabloo** [comment]
Ya it would render something like this on GCP:

![Screen Shot 2020-07-29 at 5 30 11 PM](https://user-images.githubusercontent.com/7360286/88760639-94966900-d1c1-11ea-9131-ff87a4b0b448.png)

**Comment by kiyonlin** [comment]
How about this:
```go
package main

import (
	"github.com/gofiber/fiber"
	"github.com/gofiber/fiber/middleware"
)

func main() {
	app := fiber.New()
	app.Use(middleware.Logger(`{"pid":${pid}, "timestamp":"${time}", "status":${status}, "latency":"${latency}", "method":"${method}", "path":"${path}"}` + "\n"))
	app.Get("/", func(_ *fiber.Ctx) {})
	app.Listen(3000)
}
```
And log contents are:
```
{"pid":21327, "timestamp":"2020/07/29 13:41:03", "status":200, "latency":"0s    ", "method":"GET", "path":"/"}
{"pid":21327, "timestamp":"2020/07/29 13:46:53", "status":200, "latency":"0s    ", "method":"GET", "path":"/"}
```

**Comment by akshaybabloo** [comment]
OK I will give that a try. thank you.

**Comment by kiyonlin** [comment]
Feel free to re-open this issue if you have any further question.

**Comment by esoteloferry** [comment]
Hello!,  taking the title as structured logger, I started using go and gofiber recently (so very new , but enthusiastic!). 

So I am using the middleware logger to record the requests , but what if I I want to record other events f.e. in gracefully shutdown recipe, I can use logger to save the cleaning tasks. Or simply , to log some events inside the handler. Or to log errors . 
What is your approach or recommended guideline for this? keeping everything in one file? I was initially considering to use the middleware logger (but did not figure out how to do it). But now I think that it does not make sense to use it for other reasons as middleware things.
