### ISSUE TITLE
🚀 Custom validation for BodyParser

### ISSUE THREAD

**Issue by yuzuy** [gofiber/fiber#688]
**Describe the solution you'd like**
Using [go-playground/validator](https://github.com/go-playground/validator) to validate by struct tags like [gin-gonic/gin](https://github.com/gin-gonic/gin#custom-validators).
Create a parsing(binding) package.

An example:
```go
type Person struct {
    Name string `parsing:"required"`
    Age  int    `parsing:"required,min=18"`
}

func Parse(ctx *fiber.Ctx) {
    p := new(Person)
    if err := ctx.BodyParser(p); err != nil {
        ctx.Status(400).JSON(fiber.Map{"error": err.Error})
        return
    }
    ...
}
```

Using custom validation example:
```go
type User struct {
	ID   string `parsing:"required,user_id"`
	Name string `parsing:"required"`
	Age  int    `parsing:"required,min=18"`
}

func Parse(ctx *fiber.Ctx) {
    u := new(User)
    if err := ctx.BodyParser(u); err != nil {
        ctx.Status(400).JSON(fiber.Map{"error": err.Error})
        return
    }
    ...
}

func init() {
	v, ok := parsing.Validator.Engine().(*validator.Validate)
	if ok {
		v.RegisterValidation("user_id", validateUserID)
	}
}

func validateUserID(fl validator.FieldLevel) bool {
	val := fl.Field().String()
	return !regexp.MatchString(`^\d`, val)
}
```

Q. If it decides to implement this function, can I implement it?

**Comment by kiyonlin** [comment]
Thanks for your suggestion! But it may duplicated with #474 .

**Comment by yuzuy** [comment]
I'm sorry to lack of confirmation.
When I come up with other ideas, I suggest again!

**Comment by kiyonlin** [comment]
> I'm sorry to lack of confirmation.
> When I come up with other ideas, I suggest again!

No problem, I close this for now. But feel free to re-open it when you have more ideas about this topic.
