### ISSUE TITLE
🚀 Extending Ctx using an interface

### ISSUE THREAD

**Issue by thomasvvugt** [gofiber/fiber#691]
**Is your feature request related to a problem?**
Fiber uses a `struct` type for it's Context whereas other frameworks like Echo use an `interface` type. Using the `interface` type allows extending the current Ctx struct.

**Describe the solution you'd like**
A guide on how to do this in Echo can be found here: https://echo.labstack.com/guide/context

**Describe alternatives you've considered**
As can be seen from the following example, interfaces are the best way to extend both the fields and the methods of an object in GoLang: https://gist.github.com/josephspurrier/55d76c2a10026e085226#file-structs_interface-go-L160

**Additional context**
The main difference between Fiber's Ctx and Echo's Context can be compared here:
https://github.com/gofiber/fiber/blob/master/ctx.go#L33
https://github.com/labstack/echo/blob/master/context.go#L19

**Comment by Fenny** [comment]
Will be shipped in `v1.14.0` 👍

**Comment by gulien** [comment]
Perfect, thank you! 🚀
