### ISSUE TITLE
🤗  Http.FileServer

### ISSUE THREAD

**Issue by bashery** [gofiber/fiber#698]
How can I do something like:
     ```http.FileServer(http.Dir("/path/to/myFolder"))```
In Fiber?
Thank you

**Comment by Fenny** [comment]
Hi @bashery, yes we have a middleware for that https://github.com/gofiber/fiber/blob/master/middleware/filesystem.md 👍

**Comment by bashery** [comment]
thank you very much.

I was using static fiber static. For static files.

I am trying to make a simple video rendering server, 
The standard library provides the ability to query any piece of video. I mean, I can open the video from the first, from the middle, from the last, or from any point in time. A query and response are sent with the 200 status. 
With fiber I can only play the video from the first. I cannot present it forward or inquire about any moment from the middle or the last. I do not see any request. No response to any situation.

Maybe the reason is the header information is not available on the video. I'm not sure.

**Comment by Fenny** [comment]
Hi @bashery, do you mean range requests? Or a custom implementation to load specific parts of the video using query parameters E.g: `/?range=0-500` ?

**Comment by bashery** [comment]
Yeah. I mean downloading certain parts of the video. Or in other words: download the video starting from certain parts. For example, in case I want to watch video from mid to last, click in the middle of the play bar. But without implementing any custom settings for the router parameters.
The idea of implementing custom parameters setting for the router seems very useful. For the ability to share the most important part of the video.
Thank you very much for this idea.

**Comment by Fenny** [comment]
> if I want to watch a video from mid to next, I click in the middle of the play bar.

Yeah these are [range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests) and our [Static](https://docs.gofiber.io/app#static) supports this options.

```go
// With static
app.Static("/video", "./public/movie.mp4", fiber.Static{
  ByteRange:  true,
})

// With SendFile ( ByteRange is enabled by default )
ctx.SendFile("/video", "./public/movie.mp4")
```

**Comment by bashery** [comment]
Oh, my goodness. That's what I'm looking for. Thank you very much, @Fenny.
Sorry, I didn't ask the question clearly. Thank you.
