### ISSUE TITLE
🤗 How to compress response myself?

### ISSUE THREAD

**Issue by Terisback** [gofiber/fiber#699]
**Question description**

I'm doing some forbidden magic, sending the generated CSS to the user, but I can't find a way to do it with compression. So, how can I do that with fiber?

**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  
  app.Get("/css/app.css", NewCSSHandler("./public/css"))
}

func NewCSSHandler(dir string) func(*fiber.Ctx) {
  // Getting content of all css files in dir and minifies it
  var data []byte = doMagic()

  return func(ctx *fiber.Ctx) {
    ctx.Set("Content-Type", "text/css")
    ctx.Set("Content-Length", strconv.Itoa(len(data)))

    ctx.SendBytes(data)
  }
}
```

**Comment by Fenny** [comment]
Hi @Terisback, use our compress middlware to enable compression for gzip or brotli:

```go
app.Get("/css/app.css", middleware.Compress(), NewCSSHandler("./public/css"))
```

You can find more examples here https://github.com/gofiber/fiber/blob/master/middleware/compress.md

**Comment by Terisback** [comment]
@Fenny I forgot to mention that I already using compression, but on site I get css without it

**Comment by Terisback** [comment]
Will check your case in hour

**Comment by Fenny** [comment]
Could you show us the response headers for the css file? Keep in mind that the browser automatically unpacks the compressed response. Maybe you are talking about minification ( https://github.com/tdewolff/minify#css )

You could compare the content length when turning compression on and off to see if it has effect.

PS: In order to compress, the response needs to be bigger than xKb (I forgot what the threshold is)

**Comment by Terisback** [comment]
![image](https://user-images.githubusercontent.com/26527529/89120400-81d8a880-d4cf-11ea-8a3a-c7c48e86ff4d.png)
![image](https://user-images.githubusercontent.com/26527529/89120403-8604c600-d4cf-11ea-80ba-4eecec823496.png)

**Comment by Terisback** [comment]
`br` is brotli?
I guess it's compressing?

**Comment by Terisback** [comment]
If it is, compressing is working

**Comment by Terisback** [comment]
so, thanks 👌

**Comment by Fenny** [comment]
Yeah, seems to work like it should 👍 

PS: Fiber sets the content-length header for you 😉
