### ISSUE TITLE
🐛 Behavior of function Next

### ISSUE THREAD

**Issue by FerMG** [gofiber/fiber#701]
**Fiber version**
v1.13.3
**Issue description**
I was testing this example from the official website: https://docs.gofiber.io/ctx#next
```go
app.Get("/", func(c *fiber.Ctx) {
  fmt.Println("1st route!")
  c.Next()
})

app.Get("*", func(c *fiber.Ctx) {
  fmt.Println("2nd route!")
  c.Next(fmt.Errorf("Some error"))
})

app.Get("/", func(c *fiber.Ctx) {
  fmt.Println(c.Error()) // => "Some error"
  fmt.Println("3rd route!")
  c.Send("Hello, World!")
})
```
It is clear from the example that I should see in the terminal:
```
1st route!
2nd route!
Some error
3rd route!
```
But what appears in the terminal:
```
1st route!
2nd route!
```

I checked the file "ctx.go" from gofiber where the function Next is defined:
```go
(...)
func (ctx *Ctx) Next(err ...error) {
	if len(err) > 0 {
		ctx.err = err[0]
		ctx.app.Settings.ErrorHandler(ctx, ctx.err)
		return //If i comment out this return I get the expected behavior from the official example
		(...)
	}
(...)
```
In earlier versions of "ctx.go" file the 'return' isn't there, but there was no ErrorHandle function as well. So I imagine this isn't a bug but a intended change in behavior and a outdated example.

Thanks

**Comment by kiyonlin** [comment]
Thanks for reporting @FerMG 

I think you are right, the `c.Next()` example is outdated.

**Comment by Fenny** [comment]
Nice catch, it's indeed an outdated example because the [error handler](https://docs.gofiber.io/error-handling) was introduced at a later stage.

I updated the [next example](https://docs.gofiber.io/ctx#next)
