### ISSUE TITLE
Sorry, How can I configure mongodb session as a session store provider ?

### ISSUE THREAD

**Issue by doctor-windroldev** [gofiber/fiber#702]
I'm working with mongodb as my database...For my beginner's perspective i just think it will be a must go using mongodb session store...I know it may be wrong to think in that way since i have no experience with sessions . Please help me how to configure mongo session store if it is a must go for my scenario, but if not so...feel free to educate me with ur advice and configuration examples in case you have a suitable solution in this scenario

**Comment by Fenny** [comment]
We currently do not have a `mongodb` adaptor for our session middleware. Since you are a beginner, It would be a challenge to write one on your own. So I recommend using postgres or redis as your storage provider for the session middleware.

**Redis example**
```go
package main

import (
	"log"
	"time"

	"github.com/gofiber/fiber"
	"github.com/gofiber/session"
	"github.com/gofiber/session/provider/redis"
)

func main() {
	app := fiber.New()

	provider := redis.New(redis.Config{
		KeyPrefix:   "session",
		Addr:        "127.0.0.1:6379",
		PoolSize:    8,
		IdleTimeout: 30 * time.Second,
	})

	sessions := session.New(session.Config{
		Provider: provider,
	})

	app.Get("/", func(c *fiber.Ctx) {
		store := sessions.Get(c) // get/create new session
		defer store.Save()

		store.ID()               // returns session id
		store.Destroy()          // delete storage + cookie
		store.Get("john")        // get from storage
		store.Regenerate()       // generate new session id
		store.Delete("john")     // delete from storage
		store.Set("john", "doe") // save to storage
	})

	log.Fatal(app.Listen(3000))
}
```
