### ISSUE TITLE
🐛 Redirect with full url

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#703]
**Fiber version**
1.13.3

**Issue description**

Reposting from https://github.com/gofiber/docs/issues/116 as now I tend to think it is a bug to be fixed

```go
app.Get("/", func(c *fiber.Ctx) {
  c.Redirect("/foo/bar")
  c.Redirect("../login")
  c.Redirect("http://example.com")
  c.Redirect("http://example.com", 301)
})
```

Does it has to be either host or path-only? Can it be host + path? 

I tried:

**Code snippet**

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()

  // Steps to reproduce
app.Get("/", func(c *fiber.Ctx) {
c.Redirect("http://10.xx.xx.xx:3000/login")})
}

  app.Listen(3000)
}
```

but got

```
Oops!
404 Not Found
Sorry, an error has occured, Requested page not found!
```

Visiting that url directly within my browser OK. 

Is the problem of host + path, or host + path + port? 

Thx!

**Comment by Fenny** [comment]
Should work fine, could you test the code below?
```go
package main

import (
	"log"

	"github.com/gofiber/fiber"
)

func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) {
		c.Redirect("http://localhost:3000/hello")
	})

	app.Get("/hello", func(c *fiber.Ctx) {
		c.Send("Hello 👋!")
	})

	log.Fatal(app.Listen(3000))
}
```

**Comment by suntong** [comment]
True!

OK. I'll see what's wrong with my code then...

**Comment by suntong** [comment]
I'm still getting 404 at my end with my code. Is there any way to get more insights into what is happening behind that simple `c.Redirect()` statement? Any way for the log to be more verbose? thx.

**Comment by suntong** [comment]
Finally got to the bottom of the problem, take a look at this innocent change:

https://github.com/suntong/boilerplate/commit/44190aa8555dfe0328557a7ef90174d4c7b76f7e

With that, will bring:

```
Oops!
404 Not Found
Sorry, an error has occured, Requested page not found!
```

**Comment by Fenny** [comment]
Fiber respects the stack order, try to place your 404 handler under all the other handlers.

https://docs.gofiber.io/faq#how-do-i-handle-custom-404-responses

```go
	app.Get("/f", func(c *fiber.Ctx) {
		c.Redirect("https://github.com:443/gofiber/fiber")
	})
	app.Use(handlers.NotFound)
```

**Comment by suntong** [comment]
Ah, thanks!
