### ISSUE TITLE
how Can Full pagination Result

### ISSUE THREAD

**Issue by Rasoul-Karimi** [gofiber/fiber#704]
**Create Pagination**

how can create pagination for JSON response in controller return like:

perPage
current page
nextPage
total page
and others...

something like Laravel (php) pagination or Rails or other frameworks

**Comment by renanbastos93** [comment]
you can create a middleware to treat it or a method too
e.g
```go
func Pagination(data interface{}, pageActual, limitItems int) (result []interface{}, err error) {
	// your logic
}
app.Get("/", func(c *fiber.Ctx) {
    result := Pagination(...)
    c.JSON(fiber.Map{
        "data": result,
        "nextPage: ...
        ....
    })
}

```
