### ISSUE TITLE
🐛 directory need auto redirect

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#705]
**Fiber version**
v1.11.1 & v1.13.3

**Code snippet**

Take a look at 
https://github.com/suntong/fiber_demo/blob/master/app/static-gz.go

**Issue description**

The results of visiting 

- http://localhost:3000/sample0
- http://localhost:3000/sample1
- http://localhost:3000/sample-gz

are wrong, while visiting the following are right:

- http://localhost:3000/sample0/
- http://localhost:3000/sample1/
- http://localhost:3000/sample-gz/

Normal web servers would redirect `http://site/directory` to `http://site/directory/` automatically (note the extra trailing `/`), so they would not exhibit such differences. I think so should fiber too.

**Comment by thomasvvugt** [comment]
Hi @suntong,
Fiber has a setting called `StrictRouting` to change it's behavior to treat `/foo` and `/foo/` as the same.
Redirecting `/foo` to `/foo/` would require you to write a middleware to check for the trailing `/`, and redirect the client if it's not present.
To my knowledge, there are no such guidelines to specifically use/not use a trailing `/` for a URL.

**Comment by suntong** [comment]
Thanks for your reply @thomasvvugt, so I took a look and found that `StrictRouting` would actually _**remove**_ the trailing slashes, which would actually make things worse and not working any more. 

Maybe there is no obvious guidelines, but if you take a look at every web server, the above described behaviors are what they actually doing. So maybe it is such a common sense that there is no need for a written guidelines for it. 

OK. I'll write a middleware on my own, and submit a PR against this issue. 

Thanks

**Comment by thomasvvugt** [comment]
Hi @suntong,

By default, `StrictRouting` is disabled. When `StrictRouting` is enabled, it will indeed redirect the client if it requests a route with any trailing slashes (`/`).
So we can take advantage of Fiber's default behavior by using a simple middleware which does the job of redirecting the client if there are no trailing slashes present in the original URL. I also took note of the fact that clients can also request files with file extensions.
Take a look at my example below, and let me know if that helps you out!

```go
package main

import (
	"log"
	"regexp"
	"strings"
	
	"github.com/gofiber/fiber"
	"github.com/gofiber/utils"
)

func main() {
	app := fiber.New(&fiber.Settings{
		// By default -> StrictRouting: false,
	})

	// Custom middleware to redirect routes with a trailing `/`
	app.Use(func(c *fiber.Ctx) {
		originalUrl := utils.ImmutableString(c.OriginalURL())

		// Check if the client is requesting a file extension
		extMatch, _ := regexp.MatchString("\\.[a-zA-Z0-9]+$", originalUrl)

		if !strings.HasSuffix(originalUrl, "/") && !extMatch {
			c.Redirect(originalUrl + "/")
		}
		c.Next()
	})

	// Route definitions
	app.Get("/foo/", func(c *fiber.Ctx) {
		c.SendString("I am Foo!")
	})

	log.Fatal(app.Listen(8080))
}
```

Thanks for asking! 🚀

**Comment by suntong** [comment]
Why it is closed?

**Comment by thomasvvugt** [comment]
Hi @suntong,

Like I pointed out in my previous comment, there are no such guidelines to specifically use/not use a trailing `/` for a URL.
I have also provided a working code example which adds a trailing slash, mimicking the behavior you stated.

Let me know if there are any additional comments regarding the issue or the given code example.

**Comment by suntong** [comment]
Fine. 

Giving the fact that all normal web servers would redirect directories automatically with the extra trailing, I'm still thinking this should be a builtin feature, not even an added middleware, but

It's your software and you make the call.

**Comment by Fenny** [comment]
It's something we worked on a while back, please see <https://github.com/gofiber/fiber/blob/master/app.go#L183>. But we never finished the implementation because it impacted the performance. Since I'm so busy with other parts of the Framework, I never had time to finish this.

PR's are welcome, in the meantime I have to focus on the `v1.14.0` release notes and maybe we can take another look at `RedirectFixedPath `

**Comment by suntong** [comment]
Ah, yeah, that make perfect sense. I.e., 

- adding it as a middleware will have to run the detection for every single request, doing FS IO determining if it is a directory or not, so it will definitely have negative impact on the performance
- however, if it is a builtin feature from the static file server, since the code would have to know if it is a directory or file anyway, and treat it differently, adding a trailing "/" would literately have nearly zero cost. We just have to find the perfect spot to add it.

**Comment by suntong** [comment]
> Giving the fact that all normal web servers would redirect directories automatically with the extra trailing, I'm still thinking this should be a builtin feature, not even an added middleware...

Took a further look at the issue to determine where exactly the problem came from, as fiber is relying on the `fasthttp` to provide the file server service. So I have added a `fasthttp-fileserver` check --

https://github.com/suntong/fiber_demo/commit/8ab9321a1fc26f4915ebf097b6339ba1dc965e7e

```sh
cd fiber_demo/fasthttp-fileserver
go run fileserver.go -dir ../web 
```

The check points out that fasthttp-fileserver clearly has such feature builtin -- it would redirect directories automatically with the extra trailing -- http://localhost:8080/sample0 would become http://localhost:8080/sample0/ automatically. 

So the problem is somewhere within `fiber`, not the `fasthttp`.

**Comment by suntong** [comment]
> So the problem is somewhere within fiber, not the fasthttp.

Seems to have come from
https://github.com/gofiber/fiber/blob/29e8f12a13966ed67161eae2fc0a856f4603bdfa/router.go#L273-L285

What is logic behind such PathRewrite? 
Would it a better idea just to leave PathRewrite to `fasthttp` to handle that?

**Comment by suntong** [comment]
See https://github.com/gofiber/fiber/pull/819

**Comment by quarkcms** [comment]
> Hi @suntong,
> 
> By default, `StrictRouting` is disabled. When `StrictRouting` is enabled, it will indeed redirect the client if it requests a route with any trailing slashes (`/`). So we can take advantage of Fiber's default behavior by using a simple middleware which does the job of redirecting the client if there are no trailing slashes present in the original URL. I also took note of the fact that clients can also request files with file extensions. Take a look at my example below, and let me know if that helps you out!
> 
> ```go
> package main
> 
> import (
> 	"log"
> 	"regexp"
> 	"strings"
> 	
> 	"github.com/gofiber/fiber"
> 	"github.com/gofiber/utils"
> )
> 
> func main() {
> 	app := fiber.New(&fiber.Settings{
> 		// By default -> StrictRouting: false,
> 	})
> 
> 	// Custom middleware to redirect routes with a trailing `/`
> 	app.Use(func(c *fiber.Ctx) {
> 		originalUrl := utils.ImmutableString(c.OriginalURL())
> 
> 		// Check if the client is requesting a file extension
> 		extMatch, _ := regexp.MatchString("\\.[a-zA-Z0-9]+$", originalUrl)
> 
> 		if !strings.HasSuffix(originalUrl, "/") && !extMatch {
> 			c.Redirect(originalUrl + "/")
> 		}
> 		c.Next()
> 	})
> 
> 	// Route definitions
> 	app.Get("/foo/", func(c *fiber.Ctx) {
> 		c.SendString("I am Foo!")
> 	})
> 
> 	log.Fatal(app.Listen(8080))
> }
> ```
> 
> Thanks for asking! 🚀

Although it can solve this problem, but it is not the best solution
