### ISSUE TITLE
🐛 Files get removed when in compress mode 

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#706]
**Fiber version**
v1.11.1 & v1.13.3

**Code snippet**

Take a look at
https://github.com/suntong/fiber_demo/blob/master/app/static-gz.go

**Issue description**

- The `index.html.gz` file get removed when visiting `http://localhost:3000/ot-gz`, for both v1.11.1 & v1.13.3. 
- When in v1.11.1, and when visiting `http://localhost:3000/ot-gz/OverTime.htm`, then all .gz files under `OverTime_files/` get removed with v1.11.1. The v1.13.3 fixes this issue, but still have the above removing  `index.html.gz` file issue.

**Comment by Fenny** [comment]
If the file date does not match the `.gz` file, Fiber will re-compress and override the compressed file.

**Comment by suntong** [comment]
Ehm, that's a nice consideration. 

Can we make it optional? My `.gz` files are true static ones, so after `gzip` turns them form ordinary files into `.gz` files by itself, I need to `touch` the sources files again to recreate them. 

Also, Is `index.html` being zero length to be the cause of `index.html.gz` being completely removed from the files system?

**Comment by ReneWerner87** [comment]
This feature is deeply embedded in the fasthttp filehandler and is intended to prevent old compressed files from being delivered. I think preventing this would take too much effort than it would help.

**Comment by suntong** [comment]
OK then. Thanks for looking into it. 

I guess I'll have to keep two sets of files then.

**Comment by suntong** [comment]
**Conclusion**

> I guess I'll have to keep two sets of files then.

Found that it is OK to keep only one sets of files as my .gz files are true static ones. --

> If the file date does not match the `.gz` file, Fiber will re-compress and override the compressed file.

This is the key!

I.e., it's OK to empty the non-compressed files, after the corresponding .gz files have been created. Just make sure their file date are the same or older than the `.gz` files.
