### ISSUE TITLE
🚀 Add @ to param delimiter

### ISSUE THREAD

**Issue by falsandtru** [gofiber/fiber#707]
**Is your feature request related to a problem?**
I want to match a pattern `/@:name` to a path `/@name`.

**Describe the solution you'd like**
Make it possible.

**Describe alternatives you've considered**
Any workaround?

**Additional context**
echo (https://github.com/labstack/echo) supports this feature.

**Comment by falsandtru** [comment]
I use the next workaround for now.

```go
	app.Get("/:name", func(c *fiber.Ctx) {
		var name = c.Params("name")
		if name == "@" || !strings.HasPrefix(name, "@") {
			c.Next()
			return
		}
		c.Type("html")
		c.Send(name)
	})
```

**Comment by Fenny** [comment]
Hey @falsandtru, thanks for opening your first issue!

Fiber currently supports `/`, `-` and `.` for param delimiters, we could add `@` to the list.
I will do some testing today, suggestions for other characters are welcome 👍

**Comment by falsandtru** [comment]
Thanks for your quick response!

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/releases/tag/v1.14.2
