### ISSUE TITLE
🤗 How to show directory content

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#709]
**Question description**

How to show directory content when the index.html file does not exist?
I searched https://docs.gofiber.io/?q=content but didn't find good hits. 

thanks

**Comment by Fenny** [comment]
Hi, check out https://docs.gofiber.io/app#static
```go
app.Static("/", "./public", fiber.Static{
  Browse: true,
})
```

**Comment by suntong** [comment]
Ops, just about to check that, :) thx!!

**Comment by suntong** [comment]
What's wrong with the following lines @Fenny ?

https://github.com/suntong/boilerplate/blob/c70090651f8d5cf2160c573cd2fca3ad788e3079/app.go#L44-L46

I'm getting `Oops!
404 Not Found` again.

**Comment by Fenny** [comment]
Try to remove the `/test` route since its a duplicate for the route above and move the browse setting to the `/` route.

**Comment by suntong** [comment]
Oh, so we can only have one `app.Static()` call per program?

**Comment by suntong** [comment]
> Oh, so we can only have one `app.Static()` call per program?
> 
> I was planning to have a `static/test/` in parallel to `static/public/`, apparently it is not feasible now.

FTR, we _**can**_ have more than one `app.Static()` call per program. So 

having a `static/test/` in parallel to `static/public/`, _**is**_ feasible.
