### ISSUE TITLE
🐞 static.go path wildcard support

### ISSUE THREAD

**Issue by zhongwei** [gofiber/fiber#71]
**Fiber version/commit**
v1.4.0
**Issue description**
static.go  line 36 can't support "/static/*"
**Expected behavior**

**Steps to reproduce**

**Code snippet**
	// Check if wildcard for single files
	if prefix == "*" || prefix == "/*" {
		wildcard = true
	}

       // line 76
      //  if prefix is "/*"  and in windows then generate \*\xxx\a.js
```go
package main

func main() {

}
```

**Comment by koddr** [comment]
@zhongwei thx for reporting! 👍 

Can you please send PR for fix this?

**Comment by Fenny** [comment]
https://github.com/gofiber/fiber/pull/121 fixed absolute paths on windows
```go
app.Static("public")
// http://localhost:3000/index.html
// http://localhost:3000/style.css
// http://localhost:3000/main.js

app.Static("public/index.html")
// http://localhost:3000 => index.html

app.Static("*", "public/index.html")
// http://localhost:3000/john => index.html

```
