### ISSUE TITLE
🚀 Add Controller ( MVC Architecture )

### ISSUE THREAD

**Issue by Mahdihp** [gofiber/fiber#718]
Add a controller layer to this framework if possible
like this:
[https://beego.me/docs/intro/#the-execution-logic-of-beego](url)

**Comment by kiyonlin** [comment]
Hi @Mahdihp I think `fiber.Handler` is already a controller layer. Could you provide more specific examples?

**Comment by Mahdihp** [comment]
Add Layer MVC Architecture like this :https://beego.me/docs/mvc/

**Comment by Mahdihp** [comment]
Add MVC Architecture like this : [https://github.com/kataras/iris/wiki/MVC](url)

**Comment by Fenny** [comment]
Could you show a code example @Mahdihp?

**Comment by Mahdihp** [comment]
this:
[https://github.com/kataras/iris/blob/c4843a4d82aae53518bb7c247923007d1d99893c/_examples/mvc/hello-world/main.go](url)

**Comment by Dumbeldor** [comment]
Aye @Mahdihp 

I don't think that's a good idea. The goal of fiber is to be a framework as simple and minimalist as possible as expressjs is.

So adding an MVC architecture makes the framework more complexe for nothing. The goal is to let the user choose to organize himself as he wants. Currently you can choose to write your own app in MVC.

But maybe i'm wrong ?

**Comment by mikeychowy** [comment]
In fact, the fiber-boilerplate uses MVC architecture.

And it tries its best to mimic laravel in terms of developer convenience, i
think you should check it out.q

**Comment by Fenny** [comment]
I'm closing this issue because I personally don't see any real benefit to implement MVC within the framework, like @Dumbeldor said: Fiber's goal is to be simple and minimalistic but flexible, so the user can decide if he wants to use the MVC architecture.

Thanks for your suggestion though, PR's are always welcome!
