### ISSUE TITLE
🤗 Is there any quick way to get http.ResponseWriter and http.Request from fiber.Context

### ISSUE THREAD

**Issue by leopku** [gofiber/fiber#721]
**Question description**
I want to find a quick way to get http.ResponseWriter and http.Request from fiber.Context.
Yes, I know there is `adaptor` middleware to converting between them. And I now using `adaptor` to make it working.
But I still wanna ask wether there is a elegant method to get http.ResponseWriter and http.Request from fiber.Context.

For example, I wanna use `gofiber` to work with `markbates/goth`. Many methods of `goth` just can accept http.ResponseWriter and http.ResponseWriter. But when jobs related with goth done, I wanna using gofiber but not net/http to another things, like sending json result etc.

**Code snippet** _Optional_

```go
func main()  {
	// prepare goth
	// ...

	app := fiber.New()
	app.Get("/auth", func(c *fiber.Context) {
		
		w, r := getResponseAndRequestFromFiberContext(c) // get http.ResponseWriter and http.Request
		
		user, err := gothic.CompleteUserAuth(w, r)
		if err != nil {
			log.Println(err)
		}
		c.JSON(user)
	})
}
```

**Comment by kiyonlin** [comment]
Hey @leopku 
I don't think it is possible to get http.ResponseWriter and http.Request from `fiber.Ctx`. They are totally in different worlds 😝

**Comment by leopku** [comment]
> Hey @leopku
> I don't think it is possible to get http.ResponseWriter and http.Request from `fiber.Ctx`. They are totally in different worlds 😝

Thank you, @kallydev .

Maybe it can be done by manually copy URL, Header, Body etc from `fiber.Ctx` to ResponseWriter and Request.
I'll try it later when I was released.

**Comment by kallydev** [comment]
> Thank you, @kallydev .

@leopku I don’t think i’m the person you want. 🤣

**Comment by leopku** [comment]
> > Thank you, @kallydev .
> 
> @leopku I don’t think i’m the person you want. 🤣

aaaah.....

Thanks @kinbiko .
Also thank you @kallydev :)

**Comment by thomasvvugt** [comment]
@Fenny I am also wonder if this is available at all, and if so, is this available backwards as well, such as;

```go
func IsAdmin(request *http.Request) bool {
    // Something like ctx := fiber.CtxFromHttpRequest(request)
    store := session.Get(ctx)
    return store.Get("admin").(bool)
}
```

**Comment by Fenny** [comment]
It would be possible, but it will cause a big overhead to the point where it's better to just stick to `net/http`. You would also lose some flexibility because the `Ctx` is also dependant on the `App` object ( router ).
