### ISSUE TITLE
🚀 Add route level json schema validation and serialization 

### ISSUE THREAD

**Issue by mhf-ir** [gofiber/fiber#723]
**Is your feature request related to a problem?**

Move from express to fastify as inspiration nodejs framework

- Route base validation using Fastify approach https://www.fastify.io/docs/latest/Routes/#routes-option
- Also serialization for stripout or normalize output of the route responses like Fastify
- Add additional open api 3 properties for auto generation OpenAPI JSON for swagger UI like https://github.com/SkeLLLa/fastify-oas

Note: 
_It's important to open api json must be generated from Routes not define in JSON file as reference. Application routes is run and validation so reference must be itself not another thing._

**Describe the solution you'd like**

Add json schema libraries:
https://json-schema.org/implementations.html#validator-go
Or better one if you seek or even write

JS Version: https://ajv.js.org/

**Describe alternatives you've considered**

Repeat our self for standard REST API / OpenAPI, validation serialization and etc... :cry: 

**Additional context**

This is big movement for gofiber and golang on the web application.

Fastify also upgrade node.js http to next level.

**Comment by mhf-ir** [comment]
That's will be awesome.

Currently i dont use this mechanism, code like express check all input for exist then validate them, but if validation exist as part of router input so we just can write the logic.

After that try to repeat my self to generate the open api schema for who using our API.
Another option will came after adding schema in router that the OpenAPI schema will be generated automatically for swagger, redoc and other sandbox of Open API.

**Comment by Fenny** [comment]
After some discussions in our [Discord channel](https://gofiber.io/discord) most people agreed that any kind of validation should be a middleware or third-party package. I'm closing this issue with a #nofix, feel free to re-open if you have further comments or ideas.

Thank you for opening this issue <3
