### ISSUE TITLE
🤗 In version 1.4.1 shows 1.3.3

### ISSUE THREAD

**Issue by judemvm** [gofiber/fiber#729]
**Why shows version 1.3.3?**

https://github.com/gofiber/fiber/blob/v1.14.1/app.go#L35

**Comment by Fenny** [comment]
We forgot to update the Version variable 😆

**Comment by thomasvvugt** [comment]
Any solutions on how we can prevent this in the future?

**Comment by judemvm** [comment]
for example use task list

- [ ] change version

**Comment by Fenny** [comment]
Fixed in <https://github.com/gofiber/fiber/releases/tag/v1.14.2>
