### ISSUE TITLE
🚀 Does fiber app supporting be deployed to vercel.com(zeit.co originally)

### ISSUE THREAD

**Issue by leopku** [gofiber/fiber#731]
**Question description**
I wanna deploy my project powered by gofiber to be deployed to vercel.com.
Any solutions?

**Comment by thomasvvugt** [comment]
It seems that Vercel is [only supporting Javascript-based frameworks](https://vercel.com/docs/build-step) such as Angular, React and Vue.
Running Go would require different build steps to deploy your application.

**Comment by leopku** [comment]
@thomasvvugt One of my project powered by echo now running on Vercel.  I'm now confused by how to run my new project powered by fiber on it too.

**Comment by Fenny** [comment]
It seems that vercel supports Go but it's in alpha. I contacted them to request a demo to explore the possibilities. I will post updates here.

**Comment by leopku** [comment]
@Fenny Thanks a lot.

I found a repo with simple [demo](https://github.com/pankajhirway/vercelGoDemo)

For conclusion, Vercel would search a package named with `handler` and a method named with `Handler`. Aslo `vercel.json` was needed.

**Comment by Fenny** [comment]
I had contact with some people at vercel.com, it is possible to deploy a fiber app but it would require the adaptor middleware. I personally think this won't benefit your application performance. If you have to use the adaptor to be compatible with a cloud platform, it's better to use the original net/http library.

**Comment by leopku** [comment]
> ith some people at vercel.com, it is possible to deploy a fiber app but it would require the adaptor mid

Thank you @Fenny .

**Comment by mobiTech1** [comment]
you can use Railway to deploy your app. Railway supports go fiber, and it's free until you decide to upgrade.
https://railway.app/

**Comment by sudityashrivastav** [comment]
@jamm59  railway's server up time is 1 hours.. You have to wait 1+ hour to get first response from server.
