### ISSUE TITLE
🐛 Using the logger middleware causes application cpu usage to rise to 20% 

### ISSUE THREAD

**Issue by mayowa** [gofiber/fiber#734]
**Fiber version**
v1.14.1, v1.14.2

**Issue description**
Using the logger middleware causes application cpu usage to immediately rise to 20%  
downgrading to 1.13.3 resolves this

System specs
OS: Linux
Distro: Ubuntu 20.04
Go version: go1.14.3 linux/amd64

Was reproduced by someone else on Windows 10 using Ubuntu 20.04 via WSL

**Code snippet**

```go
package main

import (
    "github.com/gofiber/fiber"
    "github.com/gofiber/fiber/middleware"
)

func main() {
    app := fiber.New()
    app.Use(middleware.Logger())

    app.Get("/", func(c *fiber.Ctx) {
        c.Send("Hello, World 👋!")
    })

    app.Listen(3000)
}
```

**Comment by Fenny** [comment]
Fixed in [v1.14.3](https://github.com/gofiber/fiber/releases/tag/v1.14.3)
