### ISSUE TITLE
📢 v2 - Changelog

### ISSUE THREAD

**Issue by Fenny** [gofiber/fiber#736]
__Updated September 14, 2020__ ( [**🚀 v2 benchmark results**](https://github.com/gofiber/fiber/issues/773) )

<p align="center">
  <a href="https://gofiber.io">
    <img alt="Fiber" height="125" src="https://raw.githubusercontent.com/gofiber/docs/master/static/fiber_v2_logo.svg">
  </a>
</p>

Dear Gophers, after long discussions in our <a href="https://gofiber.io/discord"><img src="https://img.shields.io/discord/704680098577514527?style=flat&label=%F0%9F%92%AC%20discord&color=00ACD7" height="15"></a>, we decided to release `v2.0.0` on **15 September 2020**. We will summarize our current API proposal in this post, feedback is more than welcome.

---
⚠ **Breaking Changes**
-
- ***func(c \*fiber.Ctx) error*** is the new ***Handler*** type accepting an error return, this will simplify error handling and create cleaner code because you can directly return outgoing methods like ***c.Send()***, ***c.Next()***, ***c.SendStatus()***, ***c.Redirect()***  etc... https://github.com/gofiber/fiber/issues/218
```go
// func(c *fiber.Ctx) {}
   func(c *fiber.Ctx) error {}
```
```go
app.Use(func(c *fiber.Ctx) error {
    if c.Get("x-john") == "doe" {
        return c.Next()
    }
    return c.SendStatus(fiber.StatusForbidden)
})

app.Use("/teapot", func(c *fiber.Ctx) error {
    return c.Send([]byte("Helllo, Teapot ☕!"))
})

app.Get("/world", func(c *fiber.Ctx) error {
    return c.SendString("Hello, World 👋!")
})

app.Get("/redirect", func(c *fiber.Ctx) error {
    return c.Redirect("https://google.com")
})
```
- ***fiber.New()*** takes an optional ***Config*** struct as value that will replace the ***\*Settings*** pointer.
```go
// func New(settings ...*Settings) *App {}
   func New(config... Config) *App {}
```
- ***app.Listen()*** now contains a strong typed signature accepting an `string` addr argument.
To enable TLS, provide your own listener ***app.Listener(ln net.Listener)*** https://github.com/gofiber/fiber/issues/555
```go
// func (app *App) Listen(address interface{}, tlsconfig ...*tls.Config) error {}
   func (app *App) Listen(addr string) error {}
```
- ***app.Listener()*** will remove the optional ***\*tls.Config*** argument, this should be set within the given listener. `Prefork` will be compatible with custom listeners.
```go
// func (app *App) Listener(ln net.Listener, tlsconfig ...*tls.Config) error {}
   func (app *App) Listener(ln net.Listener) error {}
```
- ***c.Next()*** returns an error to be used with the new Ctx handler signature. Passing an error through ***c.Next*** is not necessary anymore since we return all errors within the handler.
```go
// func (c *Ctx) Next(err ...error) {}
   func (c *Ctx) Next() error {}
```
- ***c.Body()*** now returns ***[]byte*** type instead of a ***string***
```go
// func (c *Ctx) Body() string {}
   func (c *Ctx) Body() []byte {}
```
- ***c.Write()*** will comply with the io.Writer interface.
```go
// func (c *Ctx) Write(bodies ...interface{}) {}
   func (c *Ctx) Write(p []byte) (n int, err error) {}
```
- ***c.Context()*** returns the original [`*fasthttp.RequestCtx`](https://godoc.org/github.com/valyala/fasthttp#RequestCtx) and is still compatible with the [`context.Context`](https://golang.org/pkg/context/) interface.
```go
// func (c *Ctx) Context() context.Context
   func (c *Ctx) Context() *fasthttp.RequestCtx
```
- ***app.IsChild()*** will be available on the package layer
```go
// func (app *App) IsChild() bool {}
   func IsChild() bool {}
```

🧹 **Updates**
-
- ***c.Send()*** now contains a strong typed signature accepting a single ***[]byte*** type
Other outgoing _Send_ methods also return an error to comply with the new Handler signature
```go
// func (c *Ctx) Send(bodies ...interface{}) {}
   func (c *Ctx) Send(body []byte) error {}

// func (c *Ctx) SendStatus(status int) {}
   func (c *Ctx) SendStatus(status int) error {}

// func (c *Ctx) SendString(body string) {}
   func (c *Ctx) SendString(body string) error {}

// func (c *Ctx) SendStream(stream io.Reader, size ...int) {}
   func (c *Ctx) SendStream(stream io.Reader, size ...int) error {}
```
- ***c.Redirect()*** now returns an error
```go
// func (c *Ctx) Redirect(location string, status ...int) {}
   func (c *Ctx) Redirect(location string, status ...int) error {}
```
- ***c.FormValue()*** now supports the optional `defaultValue` argument
```go
// func (c *Ctx) FormValue(key string) string {}
   func (c *Ctx) FormValue(key string, defaultValue ...string) string {}
```
⚠ **Removed**
-
- ***c.SendBytes()*** will be removed and is replaced by ***c.Send***
```go
// func (c *Ctx) SendBytes(body []byte) {}
```
- ***c.Error()*** will be removed because errors can be accessed using the error return in ***c.Next() error***
```go
// func (c *Ctx) Error() error {}
```

🔥 **New**
-
- ***c.Request()*** is a replacing method to access [`*fasthttp.Request`](https://godoc.org/github.com/valyala/fasthttp#Request).
```go
// c.Fasthttp.Request.Header.Peek("x-version")
   c.Request().Header.Peek("x-version")
```
- ***c.Response()*** is a replacing method to access [`*fasthttp.Response`](https://godoc.org/github.com/valyala/fasthttp#Response).
```go
// c.Fasthttp.Response.Header.Peek("x-version")
   c.Response().Header.Peek("x-version")
```
- ***app.Config.ErrorHandler*** will replace the ***app.Settings.ErrorHandler*** to override the default error handler.
```go
app := fiber.New(fiber.Config{
	ErrorHandler: func(c *fiber.Ctx, err error) error {
		return c.Status(404).SendString("hi, i'm an custom error")
	},
})

app.Get("/", func(c *fiber.Ctx) error {
	return c.SendFile("../there/is/nothing/here")
})
```
- ***Config.ProxyHeader*** will enable `c.IP()` to return the value of the given header key. By default `c.IP()` will return the Remote IP from the tcp connection, this property can be useful if you are behind a load balancer e.g. _X-Forwarded-*_.
```go
app := fiber.New(fiber.Config{
	ProxyHeader: "CF-Connecting-IP",
})
app.Get("/", func(c *fiber.Ctx) error {
	return c.SendString(c.IP()) // value from CF-Connecting-IP header
})
```
- ***Config.GETOnly*** rejects all non-GET requests if set to true. This option is useful as anti-DoS protection for servers accepting only GET requests and will return an `ErrMethodNotAllowed` to the error handler. The request size is limited by ReadBufferSize if GETOnly is set. Server accepts all the requests by default.
```go
app := fiber.New(fiber.Config{
	GETOnly: true,
})
app.Post("/", func(c *fiber.Ctx) error {
	return c.SendString("This method is not allowed")
})
```

🚀 **Routing**
-
- The logic for parsing the route now better recognizes the parts which are not parameters, so the parameter can be placed anywhere, it is only important that the normal non-optional parameters are terminated by a delimiter character:
```go
// Route
app.Get("/test::param/", handler)
// GET /test:fiber/

// Route
app.Get("/shop/product/color::color/size::size", handler)
// GET /shop/product/color:blue/size:xs

// Route
app.Get("/@:name", handler)
// GET /@Fiber
```

- Added support for the plus parameter, this is greedy like the wildcard parameter with the difference that it is required:
```go
// Route
app.Get("/config/+.json", func(c *fiber.Ctx) error {
	ctx.Params("+1") //  abc
        ctx.Params("+")   //  abc
})
// GET /config/abc.json  // match
// GET /config/.json     // no match
```

- Support for multiple wildcard and plus parameters has been added, they can now be accessed via wildcard or plus character with the counter in the route or normally for the first as in the current fiber version:
```go
// GET /customer/v1/cart/proxy
app.Get("/*v1*/proxy", func(c *fiber.Ctx) error {
        c.Params("*")    //   customer/
	c.Params("*1")  //   customer/
	c.Params("*2")  //   /cart
})
```

📦 **Middleware**
-
- [github.com/gofiber/fiber/v2/middleware/basicauth](https://github.com/gofiber/fiber/tree/master/middleware/basicauth)
- [github.com/gofiber/fiber/v2/middleware/compress](https://github.com/gofiber/fiber/tree/master/middleware/compress)
- [github.com/gofiber/fiber/v2/middleware/cors](https://github.com/gofiber/fiber/tree/master/middleware/cors)
- [github.com/gofiber/fiber/v2/middleware/csrf](https://github.com/gofiber/fiber/tree/master/middleware/csrf)
- [github.com/gofiber/fiber/v2/middleware/favicon](https://github.com/gofiber/fiber/tree/master/middleware/favicon)
- [github.com/gofiber/fiber/v2/middleware/filesystem](https://github.com/gofiber/fiber/tree/master/middleware/filesystem)
- [github.com/gofiber/fiber/v2/middleware/limiter](https://github.com/gofiber/fiber/tree/master/middleware/limiter)
- [github.com/gofiber/fiber/v2/middleware/logger](https://github.com/gofiber/fiber/tree/master/middleware/logger)
- [github.com/gofiber/fiber/v2/middleware/pprof](https://github.com/gofiber/fiber/tree/master/middleware/pprof)
- [github.com/gofiber/fiber/v2/middleware/proxy](https://github.com/gofiber/fiber/tree/master/middleware/proxy)
- [github.com/gofiber/fiber/v2/middleware/recover](https://github.com/gofiber/fiber/tree/master/middleware/recover)
- [github.com/gofiber/fiber/v2/middleware/requestid](https://github.com/gofiber/fiber/tree/master/middleware/requestid)
- [github.com/gofiber/fiber/v2/middleware/timeout](https://github.com/gofiber/fiber/tree/master/middleware/timeout)

🚀 **Improvements**
-
- The new version will use the [segmentio/encoding](https://github.com/segmentio/encoding) package to encode JSON, this will improve performance drastically.
```go
// v1.14.x
Benchmark_Ctx_JSON-16            4596667               260 ns/op              64 B/op          2 allocs/op
Benchmark_Ctx_JSON-16            4603731               259 ns/op              64 B/op          2 allocs/op
Benchmark_Ctx_JSON-16            4652700               259 ns/op              64 B/op          2 allocs/op
Benchmark_Ctx_JSON-16            4598620               259 ns/op              64 B/op          2 allocs/op

// v2.0.0
Benchmark_Ctx_JSON-16            7186842               165 ns/op              64 B/op          2 allocs/op
Benchmark_Ctx_JSON-16            7214056               164 ns/op              64 B/op          2 allocs/op
Benchmark_Ctx_JSON-16            7227295               164 ns/op              64 B/op          2 allocs/op
Benchmark_Ctx_JSON-16            7227291               165 ns/op              64 B/op          2 allocs/op
```
- `405 Method Not Allowed` will be passed to the global error handler, in the old version this behavior was not controllable.
- This version will ship with [fasthttp v1.16.0](https://github.com/valyala/fasthttp/releases/tag/v1.16.0) which contains the [statusLine/statusMessage PR](https://github.com/valyala/fasthttp/pull/855) found by @ReneWerner87, @Fenny and @kiyonlin
- `v2.0.0` allows us to implement a hybrid [radix tree](https://en.wikipedia.org/wiki/Radix_tree) router which will remove the remaining allocation when `CaseSenstitive` is disabled and increase performance drasticly. The reason why we went with the hybrid implementation is because we still want to respect the router stack order 😉 thnx @reneWerner87
```go
// v1.14.x
Benchmark_Router_NotFound-16                      235243              4843 ns/op              80 B/op          2 allocs/op
Benchmark_Router_Handler-16                      1721277               696 ns/op              16 B/op          1 allocs/op
Benchmark_Router_Handler_Strict_Case-16          1848582               651 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Chain-16                        9300248               129 ns/op               1 B/op          1 allocs/op
Benchmark_Router_WithCompression-16              8693692               137 ns/op               1 B/op          1 allocs/op
Benchmark_Router_Next-16                         1960342               619 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Handler_CaseSensitive-16        1862936               649 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Handler_Unescape-16              255260              4573 ns/op              16 B/op          1 allocs/op
Benchmark_Router_Handler_StrictRouting-16        1857168               647 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Github_API-16                      3634            317628 ns/op               0 B/op          0 allocs/op

// v2.0.0
Benchmark_Router_NotFound-16                     2919049               411 ns/op              48 B/op          1 allocs/op
Benchmark_Router_Handler-16                      8331446               145 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Handler_Strict_Case-16          9675211               124 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Chain-16                        9088828               132 ns/op               0 B/op          0 allocs/op
Benchmark_Router_WithCompression-16              9020534               133 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Next-16                        14454469                81 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Handler_CaseSensitive-16        9597826               124 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Handler_Unescape-16             6059216               196 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Handler_StrictRouting-16        9753892               123 ns/op               0 B/op          0 allocs/op
Benchmark_Router_Github_API-16                      5452            214098 ns/op               0 B/op          0 allocs/op
```

See: ( [**🚀 v2 benchmark results**](https://github.com/gofiber/fiber/issues/773) )

**Comment by Fenny** [comment]
__reserved comment__

**Comment by StarMonk** [comment]
Since, `c.Fasthttp()` is coming, is it possible to pass custom function hook an argument inside "`FastHttp FileServer PathNotFound handler` ?  https://github.com/gofiber/fiber/blob/0d31dc193c235560436df8ac9f64cc0f43af5a68/router.go#L285 ?

**Comment by Fenny** [comment]
@StarMonk wouldn't the following achieve the same result?
```go
func main() {
    app := fiber.New()

    app.Static("/", "./public")

    app.Use(func(c *fiber.Ctx) {
        c.Status(fiber.StatusNotFound).SendString("I find your lack of navigation disturbing")
    })

    log.Fatal(app.Listen(3000))
}
```

**Comment by songjiayang** [comment]
API is clear more, can't wait to use it

**Comment by numToStr** [comment]
Error handling gonna be 🔥

**Comment by pofl** [comment]
Changes sound good.
But why is it v1.15 and not v2.0?

**Comment by Fenny** [comment]
Hey @pofl, good question!

We definitely considered moving to `v2` and eventually moved away from that idea after long discussions with the [Community](https://gofiber.io/discord)

It's a fact that Go has a problem when it comes to the `v2+` ecosystem, @donatj wrote an awesome article about this topic:
[Go Modules have a v2+ Problem](https://donatstudios.com/Go-v2-Modules)

The majority did not want to move to `v2`, some didn't even know about the naming requirements on modules version 2 or greater. This shows that the Go Team needs to do a better job of shining a light on this rule.

For what it's worth, the official [Go Blog](https://blog.golang.org/v2-go-modules) tried to clear the situation up some and posted a write-up about it.
Personally I found this write-up somewhat impenetrable. For how important and unusual of a requirement this is, the write-up is not accessible enough.

There are many other reasons that let up to this discussion, but we feel this is the right way to go to avoid future problems.

Here is a list of some issues people post when a repository move to `v2+`

https://github.com/labstack/echo/issues/1475
https://github.com/labstack/echo/issues/1427
https://github.com/labstack/echo/issues/1382
https://github.com/labstack/echo/issues/1374
https://github.com/labstack/echo/issues/1329
https://github.com/labstack/echo/issues/1291
https://github.com/labstack/echo/issues/1272
https://github.com/labstack/echo/issues/1244
https://github.com/go-chi/chi/issues/462
https://github.com/go-chi/chi/issues/490
https://github.com/go-chi/chi/issues/381
https://github.com/go-chi/chi/issues/366
https://github.com/go-chi/chi/issues/349
https://github.com/micro/micro/issues/1223
https://github.com/micro/micro/issues/835
https://github.com/micro/micro/issues/522
https://github.com/micro/micro/issues/481
https://github.com/micro/micro/issues/273
https://github.com/goadesign/goa/issues/2567
https://github.com/goadesign/goa/issues/2511
https://github.com/goadesign/goa/issues/2488
https://github.com/goadesign/goa/issues/2320
https://github.com/goadesign/goa/issues/2181
https://github.com/goadesign/goa/issues/2111
https://github.com/goadesign/goa/issues/2106
https://github.com/goadesign/goa/issues/1925
https://github.com/emicklei/go-restful/issues/374
https://github.com/go-gorm/gorm/issues/3356
https://github.com/go-gorm/gorm/issues/3038
https://github.com/go-gorm/gorm/issues/2886
https://github.com/go-gorm/gorm/issues/3300
https://github.com/go-gorm/gorm/issues/3310
https://github.com/argoproj/argo/issues/2602
https://github.com/golang/go/issues/35732
https://github.com/tensorflow/tensorflow/issues/39307
... this is only a fraction I bothered to copy-paste, but you get the idea.

It's hard to deny that `v2+` modules bring their own problems.

"_Sometimes you gotta zig while everyone else is zagging_"

**Comment by pofl** [comment]
Okay, I mean you run this project as you think is best. And I want to express my gratefulness for this great library.

But the way I see it is that many projects introduce v2+ without major issues. I worked with one of those, https://github.com/jackc/pgx, and it was made quite obvious to me how I should use it. Just `import "github.com/jackc/pgx/v4"` and all works.

I just wanted to give you my opinion on this. I think getting 5 Github issues asking about problems with v2 is the lesser issue compared to surprising people with breaking changes. But that is just my opinion. I'll shut up now. Thanks again for the great work.

**Comment by e3b0c442** [comment]
I understand that module versioning is not perfect, but @pofl  is correct: by introducing breaking changes within a major version, you are going to cause _more_ problems for users.

 Looking through the issues that you've cherrypicked, they for the most part seem to be easily resolved, due to misunderstandings by the user on how to use v2+, or not even related to modules at all (there was one where somebody was complaining about dep not working). That's not to say there aren't legitimate issues, but most of the problems seem to be related to understanding and documentation rather than inherent failure of the syste.m

Please reconsider your decision. They're not perfect, but modules are the path forward, and it would be better to work with the Go team to make them better than stepping on the boat halfway (using modules, but not adhering to the backward compatibility promise).

**Comment by Fenny** [comment]
Thanks, @pofl, and @e3b0c442 for taking the time to shine some light on this decision!
We became trending on [Project introduces breaking changes to library](https://www.reddit.com/r/golang/comments/iqoiok/project_introduces_breaking_changes_to_library/) and I'm glad to see all the opinions regarding this matter.

I'm always open to learn new things and change my decision accordingly, I always want to make the right call for the community ❤️
After all the feedback I received in the last 6 hours, I can say that most people would mark this project as _badly maintained_ if we introduce breaking changes to `v1`. So I decided moving to `v2` is the right decision, and here is my plan to do so:

- We move the master branch to a `v1` branch to be able to maintain it for security issues.
- The master branch will be updated with the changes and tagged under `v2.0.0`

I'm not sure if we can still support legacy pre-module users this way, but that's a sacrifice we have to make.

Thanks for sharing your opinions and idea's, this is what open-source is all about 💪

**Comment by komuw** [comment]
1. 

> We definitely considered moving to `v2` and eventually moved away from that idea after long discussions with the [Community](https://gofiber.io/discord)
> 
> 

2.   
> We became trending on Project introduces breaking changes to library and I'm glad to see all the opinions regarding this matter.  


I do not use `fiber` and neither do I have a preference on whether to move to `v2` or make breaking changes in `v1`, but if you have to choose either, I would say choose the option that the current users & maintainers of  `fiber` are more comfortable with.  


it's all trade-offs.

**Comment by peterbourgon** [comment]
If you're going to use modules, and "decide" to push breaking changes without bumping the major version, you're breaking a core assumption of the package management machinery, and you're creating potentially un-fixable errors for your users. It is of course technically possible to do this, as there's no way to programmatically assert a backwards-incompatible change, but it violates semantic versioning, it breaks the tooling, and consequently it's incredibly user-hostile. In short: this isn't a decision you get to make, you need to use v2.

**Comment by marcuxyz** [comment]
its a greating. Thank you! I have suggest:

Could be cool, if , we can get header with contex. E.g:

`c.Header["Authorization"]`

**Comment by Fenny** [comment]
> Could be cool, if , we can get header with contex. E.g:
> c.Header["Authorization"]
@marcuxyz we have the [ctx.Get](https://docs.gofiber.io/api/ctx#get) method to fetch the request header.
```go
app.Get("/", func(c *fiber.Ctx) {
  c.Get("Authorization") // "Basic YWxhZGRpbjpvcGVuc2VzYW1l"
})
```

**Comment by pofl** [comment]
Yo @Fenny I created that Reddit thread. My aim was to kick off a discussion about the v2 methods in the larger Go community. I didn't want to put you on the spot. And I hate that you have been accused of doing a bad job as the maintainer of this project.

Nevertheless I love the fact that you are so open-minded to just change direction in this matter. This project is in good hands.

**Comment by marcuxyz** [comment]
> > Could be cool, if , we can get header with contex. E.g:
> > c.Header["Authorization"]
> 
> @marcuxyz we have the [ctx.Get](https://docs.gofiber.io/api/ctx#get) method to fetch the request header.
> 
> ```go
> // Authorization: Basic YWxhZGRpbjpvcGVuc2VzYW1l
> app.Get("/", func(c *fiber.Ctx) {
>   c.Get("Authorization") // "Basic YWxhZGRpbjpvcGVuc2VzYW1l"
> })
> ```

Yes... I think that using header before its a more expressive

**Comment by kinbiko** [comment]
Thanks for being so open minded about going to 2.0 after listening to the feedback from the community. This decision has increased my confidence in using and endorsing this package even further.

**Comment by mikeychowy** [comment]
Man, i really can't wait for 2.0 😍  . What timezone will the release be on, Fenny? EST? Because if so, i've got an extra one day of waiting to do then.... 😭

**Comment by Fenny** [comment]
@mikeychowy v2 is tagged <https://github.com/gofiber/fiber/releases/tag/v2.0.0> 🥳

**Comment by AntonioSun** [comment]
`app.Listen`'s argument type changed from `int` to `string`, right?

Might be a small miss.
