### ISSUE TITLE
🤔 Trailer Headers?

### ISSUE THREAD

**Issue by rhodee** [gofiber/fiber#74]
**Question description**

👋 I was pleasantly surprised by this library and wanted to learn about adding (advocating?) for HTTP Trailer support.

I would like to try this library out with a problem that requires streaming and trailers are very helpful in this case.

Further reading: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Trailer

I reviewed the documentation for Fiber to learn if this was possible. It does not appear to be the case. I did further research and it seems that the underlying http layer does not yet support Traillers (yet) https://github.com/valyala/fasthttp/issues/210. The messaging in the Issue is promising and so I was wondering/hoping if this is something the Fiber team could get behind and advocate for as a desired use case?

Best of luck on this project!

**Comment by Fenny** [comment]
@rhodee, I will leave this issue open for now. I will take a look at the [RFC 7230](https://tools.ietf.org/html/rfc7230#section-4.4)

**Comment by rhodee** [comment]
I will do just that @Fenny thank you for giving this a look!

**Comment by erikdubbelboer** [comment]
@rhodee I'm guessing we are talking about receiving Trailers here or responding with Trailers? At least not sending them in an outgoing request right?

**Comment by rhodee** [comment]
Hi @erikdubbelboer I am seeking an approach where I can define Trailer Headers, then set them after writing the chunk response. I think the semantics which best capture my intent are in this URL: 

https://golang.org/pkg/net/http/#example_ResponseWriter_trailers

Does that make sense? If not I can try to explain further.

**Comment by erikdubbelboer** [comment]
The problem I'm having with this is that fasthttp will always wait with sending a response until the handler function has returned. The only ways to send the response body after the handler has returned are [`SetBodyStream()`](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.SetBodyStream) and [`SetBodyStreamWriter()`](https://godoc.org/github.com/valyala/fasthttp#RequestCtx.SetBodyStreamWriter). These functions allow you to either specify an `io.Reader` to read the body from or write it yourself to an `bufio.Writer`. Neither of these give us the ability to allow you to add trailers after it all.

So to be able to send Trailers we'll need to add some form of API that allows you to set these after the handler has returned already.

In your use case, what are you using? `SetBodyStream` or `SetBodyStreamWriter`?

**Comment by rhodee** [comment]
@erikdubbelboer this is a very helpful discussion. I am starting the `fiber` project from scratch (moving away from a gRPC implementation) and wanted to use Trailers (which I have in my gRPC implementation). So it is a clean slate 😄

**Comment by erikdubbelboer** [comment]
What will the trailers be used for? Is your response body so big that you can't wait with returning the initial headers until it is completely generated? I'm curious as I have never seen a use case for trailers before.

**Comment by rhodee** [comment]
> Is your response body so big that you can't wait with returning the initial headers until it is completely generated?

They will not be. I use the trailer for timings or arbitrary messages, however it is trivial to meet my needs without `Trailers`.

**Comment by rhodee** [comment]
I @Fenny @erikdubbelboer I really appreciate your attention to my question. I believe we can close this issue because there is an alternative.

**Comment by Fenny** [comment]
Thabks @erikdubbelboer for jumping in :+1:

**Comment by pckhoi** [comment]
In my case I'm using trailer headers to notify a down stream proxy to purge session since it is expensive to find out whether the session is done unless the body is completely generated. It is not a deal breaker to not support trailer but it still would be nice to have.
