### ISSUE TITLE
🐛 Logger not logging abrupt TCP Resets on large body requests

### ISSUE THREAD

**Issue by DarthBenro008** [gofiber/fiber#743]
**Fiber version**  1.14.4 running on Go1.14.6

**Issue description**
TCP Gets Shutdown abruptly when multipart with relatively huge size file is passed with default Fiber Settings on server side.

_Steps to reproduce:_
- Run the snippet below
- Send a multipart with relatively huge file as payload

I noticed that when you send a file let's say 20-30mb in multipart from Postman you get an ECONNRESET error instead of the "Entity Too Large" Response . 

![image](https://user-images.githubusercontent.com/31009634/91599845-8be1b000-e984-11ea-8321-43a0f9740e86.png)

I was puzzled with this issue as I forgot to increase the body limit in Go Fiber App Settings , however thanks to @renanbastos93 for helping me out in the discord channel. 

**Real Issue** : 
On Further Investigation , i found out native fasthttp behaves the same , but informs us in the terminal about the abrupt connection reset which the GoFiber Logger Middleware doesn't . Would be really helpful if this is added in logger to make it easier to debug.
 

**Code snippet**

```go
func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) {
		c.Send("Hello, World 👋!")
	})

	app.Post("/api", func(c *fiber.Ctx) {
		file, _ := c.FormFile("file")
		c.SaveFile(file, file.Filename)
	})

	app.Listen(3000)
}
```

**Comment by ReneWerner87** [comment]
we could trace the problem back to postman, please search in the existing posts for a solution or open a new one

https://github.com/postmanlabs/postman-app-support/issues/2214
https://github.com/postmanlabs/postman-app-support/issues?q=is%3Aissue+ECONNRESET

with direct curl requests the application will give the response
![image](https://user-images.githubusercontent.com/7063188/91714353-d123fe80-eb8b-11ea-8d7b-0bcba1e73458.png)

please use this for logging output
```go
app.Use(middleware.Logger("#${pid} - ${time} ${status} - ${latency} ${method} ${path} ${error}\n"))
```
