### ISSUE TITLE
🤗  ctx.JSON with empty slice

### ISSUE THREAD

**Issue by ahan** [gofiber/fiber#753]
**Question description**
```
var founds []Product
err = db.Model(&founds).
	Where("status = ?", "on").
	Select()

// if founds = [], found nothing with status=on
c.JSON(founds)
```

If I make a postgres query, and make fiber response with empty slice.
The browser received with null, not the `[]` response.

![WX20200908-150524](https://user-images.githubusercontent.com/654880/92443906-be8d7300-f1e4-11ea-849a-55d190640a0a.png)

How can we make the fiber ctx.JSON with empty slice, and browser client received with `[]`?

**Comment by kiyonlin** [comment]
Please check this
```go
// nil slice => null
var founds []Product
// empty slice => []
founds := []Product{}
```

**Comment by kiyonlin** [comment]
If you don't have any further questions, I'll close this issue. Feel free to re-open it.
