### ISSUE TITLE
🤔 How do I run a set of unit test?

### ISSUE THREAD

**Issue by slalbertojesus** [gofiber/fiber#756]
**I want to set up a bunch of test**

- What command do i use to run them or link them to a fiber project?

- How do i link a bunch of files with test functions on it?

Again, i am really sorry if this seems easy or obvious, i am quite new to go and fiber. 
i would really appreciate some light on here.

**I have already applied the examples below, i just dont get how to link them or run them** 

- [Example on docs](https://docs.gofiber.io/api/app#test)
- [Example on recipes](https://github.com/gofiber/recipes/tree/master/unit-test)

**Comment by hi019** [comment]
What do you mean by "link"? To run the tests you can do `go test -run Test_Function` (to run the recipie's test you would do `go test -run TestIndexRoute`). You can also do `go test` to run all tests. [Golang basics - writing good unit tests](https://blog.alexellis.io/golang-writing-unit-tests/) is a good guide.

**Comment by Fenny** [comment]
I recommend watching this video <https://www.youtube.com/watch?v=sOeUf1YICSA> that explains how to write your first unit test in Golang.

To run a test on your Fiber handler you can do the following.
```go
// myfile_test.go
package main

import (
	"net/http/httptest"
	"testing"

	fiber "github.com/gofiber/fiber"
	utils "github.com/gofiber/utils"
)

// go test -run -v Test_Handler
func Test_Handler(t *testing.T) {
	app := New()

	app.Get("/test", func(c *Ctx) {
		c.SendStatus(400)
	})

	req := httptest.NewRequest("GET", "/test", nil)
	resp, err := app.Test(req)

	utils.AssertEqual(t, nil, err, "app.Test")
	utils.AssertEqual(t, 400, resp.StatusCode, "Status code")
}

**Comment by Fenny** [comment]
@slalbertojesus did my advice help you creating unit tests? Please let us know so we can close this issue as solved 👍

**Comment by Mahi** [comment]
Looking at the example provided by @Fenny, why are we defining a new route handler in our test case?
```go
app.Get("/test", func(c *Ctx) {
	c.SendStatus(400)
})
```
I would like to test the existing routes from my main application, not rewrite all my routes in my test cases. How would I go about doing this?

**Comment by ogost** [comment]
Having same question as @Mahi above: I would like to test existing routes in my main application. Any good resource on this?

**Comment by ReneWerner87** [comment]
what fenny wanted to show here is how easy it is to test the routes

of course you should not define the routes and the app in the tests

This is defined outside in the main and used in the tests(he just put it in a script for understanding)

it is actually described here in the recipe
https://github.com/gofiber/recipes/blob/c512a21fb05cace6ba104f38c295d9d105c5332c/unit-test/main_test.go#L43

this recipe is linked in the first post

**Comment by ogost** [comment]
Ooh, I see, thank you.
Second week on go, coming from Java/Python, sorry for asking stupid questions.
