### ISSUE TITLE
🤗 Brotli Compression with template/layout

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#757]
**Question description**

This is the weirdest problem that I can think of. So, I've got Brotli Compression working before, and now I want to apply it to the fiber template/layout, with this code:

https://github.com/suntong/fiber_demo/blob/master/template-html/main.go

Note the added line:

https://github.com/suntong/fiber_demo/blob/d68f5048d76520170000c4b516d6912888dee997/template-html/main.go#L23

When I'm accessing it with my latest Chrome,

`User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36`

I saw the header

`Accept-Encoding: gzip, deflate`

The weirdest part is that, with the same Chrome, just a different tab next to my fiber demo, I'm opening google, and saw the header

`accept-encoding: gzip, deflate, br`

I.e., it is the exact same Chrome client, why it is accepting `br` for google, but not for my fiber demo? This is so strange!

Moreover, on the Response header, I saw `br` encoding for google, but nothing for my fiber demo, not even `gzip` encoding:

```
HTTP/1.1 200 OK
Date: Thu, 10 Sep 2020 18:21:45 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 54
```

Why is that? This is fiber `v1.13.3` (then updated to `v1.14.5-pre` as of now for retest and the result is the same). Hmm... I vaguely remember that I read somewhere that compression is only turned on for certain size, is that so?

**Code snippet** _Optional_

```go
package main

import "github.com/gofiber/fiber"

func main() {
  app := fiber.New()
  app.Use(middleware.Compress())
  // ..
}
```

**Comment by Fenny** [comment]
You are correct, it only compresses on a minimum of  `1 * 1024` kb

**Comment by suntong** [comment]
Thanks Fenny! 

Would the trick you posted at 
https://github.com/gofiber/fiber/issues/726#issuecomment-690855370

be the reason and solution for Chrome client not accepting `br` for my fiber demo?

**Comment by Fenny** [comment]
Could be, you can test it with `v1.14.5`
