### ISSUE TITLE
fasthttp's 'reuseport', how ?!

### ISSUE THREAD

**Issue by DevDevious** [gofiber/fiber#760]
Hello,

[fasthttp](https://github.com/valyala/fasthttp) in their `Performance optimization tips for multi-core systems` [recommends](https://github.com/valyala/fasthttp#performance-optimization-tips-for-multi-core-systems) the usage of a so called [reuseport](https://pkg.go.dev/github.com/valyala/fasthttp/reuseport?tab=doc) module.  

Being new to the **Go** ecosystem, I am a bit confused about how one might ... **go** (pun intended) about plugging in the `SO_REUSEPORT support` provided by that package in **fiber**. Any hints would be greatly appreciated.

**Comment by DevDevious** [comment]
Thank you for the quick reply @Fenny . 

So **fiber** does this automatically for us, that's **quite nice**. However, taking a peek at [prefrotk's](https://github.com/gofiber/fiber/blob/master/prefork.go) code it appears that the number of processes spanned is hard coded to the number of cores available on the system.

```
	// create variables
	var max = runtime.GOMAXPROCS(0)
```

That is not so nice. :-)

Would it be possible to expose the desired number of processes (parallelism) in settings/config, so that if one runs servers with a large number of cores, one can allocate a desired subset of cores to fiber instead of all the cores?

**Comment by Fenny** [comment]
This should work 👍 
```go
runtime.GOMAXPROCS(4) // 4 childs max
app := fiber.New(&fiber.Settings{
    Prefork: true,
})
// ...
```

**Comment by DevDevious** [comment]
It does, just tested. Awesome!

**Comment by DevDevious** [comment]
@Fenny 

`runtime.GOMAXPROCS(4) // 4 threads/childs max`

This will result in 5 processes, by the way (master + 4 children). Which is confusing. I mean the user expectation is that setting GOMAXPROCS=4 will result in 4 processes not 5. Am I missing something here?

And also, since the process is forked, wouldn't `runtime.GOMAXPROCS(4)` allow for 4 threads per each process now ?
