### ISSUE TITLE
🐛 go get isn't working in v2.

### ISSUE THREAD

**Issue by whiskygrandee** [gofiber/fiber#788]
**Fiber version**
v2
**Issue description**
I tried installing fiber with the g
import "github.com/gofiber/fiber/v2"
go get command and it is not working, go get -u or the go modules are also of no help. [](url)
**Code snippet**

```go
package main
func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen(":3000"))
}
```
![Screenshot from 2020-09-15 23-48-25](https://user-images.githubusercontent.com/59775990/93250188-1103fc00-f7b0-11ea-8d4c-927df3a06743.png)

**Comment by ReneWerner87** [comment]
```go
go clean -cache -modcache -i -r
```
please try this
article: https://lecstor.com/go-clear-cache/

![image](https://user-images.githubusercontent.com/7063188/93256493-b791d200-f79b-11ea-9740-778af63d9b2e.png)
it runs on my machine

**Comment by Fenny** [comment]
Try to initiate a `go.mod` and run `go mod tidy` after you imported `v2` in your project.

![image](https://user-images.githubusercontent.com/25108519/93257301-ebb9c280-f79c-11ea-8370-9215f4ec0ca2.png)

![image](https://user-images.githubusercontent.com/25108519/93256824-3dae1880-f79c-11ea-92f0-11fa80c3cf31.png)

**Comment by eternity-wing** [comment]
I have the same problem and it won't work.

**Comment by TheBoringDude** [comment]
I had this problem with me. 

What i did is remove the gofiber package or folders from the `src` and `pkg` folder.

Then check the `go env`. Set the `GO111MODULE=on` (My machine didn't set it automatically.)

Do not use the go get cause it will not work. Go to your project directory, then...
![Screenshot from 2020-09-18 21-40-37](https://user-images.githubusercontent.com/37932956/93604321-cf659200-f9f7-11ea-8f8b-c8a44468c640.png)

**Comment by eternity-wing** [comment]
I had the 

> I had this problem with me.
> 
> What i did is remove the gofiber package or folders from the `src` and `pkg` folder.
> 
> Then check the `go env`. Set the `GO111MODULE=on` (My machine didn't set it automatically.)
> 
> Do not use the go get cause it will not work. Go to your project directory, then...
> ![Screenshot from 2020-09-18 21-40-37](https://user-images.githubusercontent.com/37932956/93604321-cf659200-f9f7-11ea-8f8b-c8a44468c640.png)

Actually I am totally a newbee in golang and I didn't know that I should use `go mod init ... ` before starting a new project, and after wasting couple of hours I've found the problem.

**Comment by hrzp** [comment]
In ubuntu I just do this:

`export GO111MODULE=on
go get github.com/gofiber/fiber/v2
`

before doing this, be sure that your .profile variables set like this:

open your profile:
`sudo nano ~/.profile`
if you put the golang to /usr/local/go
then edit the .profile like this:

`
export GOPATH=$HOME/work
export GOROOT=/usr/local/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
`

**Comment by Metrakit** [comment]
Same issue here. Good to know that @hzrp. Now its work. Why we shoud enable this tag for download the last version ? In a fresh Gitlab CI pipeline i have this issue

**Comment by felipetesc** [comment]
I had the same problem, than I have installed with the command **go get -u github.com/gofiber/fiber** on Ubuntu 20.04 and the version 2 was correctly installed. (no v2)

**Comment by aminabvaal** [comment]
> I had the same problem, than I have installed with the command **go get -u github.com/gofiber/fiber** on Ubuntu 20.04 and the version 2 was correctly installed. (no v2)

yes you right and i do it

**Comment by Tazeg** [comment]
> In ubuntu I just do this:
> 
> `export GO111MODULE=on`
> `go get github.com/gofiber/fiber/v2`
> 
> before doing this, be sure that your .profile variables set like this:
> 
> open your profile:
> `sudo nano ~/.profile`
> if you put the golang to /usr/local/go
> then edit the .profile like this:
> 
> ```
> export GOPATH=$HOME/work
> export GOROOT=/usr/local/go
> export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
> ```

No `sudo` needed about a file in your home directory.
