### ISSUE TITLE
Processes, threads and current code behavior

### ISSUE THREAD

**Issue by DevDevious** [gofiber/fiber#799]
Following on #760 . 

I believe the are a couple of issues related to the suggested method of controlling processes and threads (pasted below for brevity).

```
runtime.GOMAXPROCS(4) // 4 threads/childs max

app := fiber.New(&fiber.Settings{
    Prefork: true,
})
// ...
```

- This results in **5** (**1 master + 4 children**) processes being spawned and not 4 processes as expected by the user.
- As this code shows

```
if IsChild() {
		// use 1 cpu core per child process
		runtime.GOMAXPROCS(1)
                ...
	}
```

the children are set-up to use 1 thread/process, however the master still uses the original GOMAXPROCS (4 in this example). This results in: **1 master @ 4 threads + 4 children @ 1 thread each, doesn't it?**

The below changes will give N processes as requested by the users specifying in their code runtime.GOMAXPROCS(N), each process bound to 1 CPU thread.

- On line 64 change from `var max = runtime.GOMAXPROCS(0)` to `var max = runtime.GOMAXPROCS(1)` . Assuming the user has set `runtime.GOMAXPROCS(4) `, the **max** variable will take a value of 4 (previous value of GOMAXPROCS as returned by the function **runtime.GOMAXPROCS(n)** ) while the runtime will have the GOMAXPROCS set to 1.

- On line 79 change from `for i := 0; i < max; i++ {` to `for i := 1; i < max; i++ {` . This will spawn N processes not N + 1, therefore configuring runtime.GOMAXPROCS(4) in user code will result in 4 processes not 5.

**Comment by Fenny** [comment]
@DevDevious, this is intended behavior because the master process does not handler TCP connections but rather controlling the children when to exit or restart.

**Comment by DevDevious** [comment]
@Fenny how about the number of threads/process? If my understanding is correct, the children get 1 CPU thread/process while the master gets the original GOMAXPROCS (potentially multiple threads per process). If one specifies say runtime.GOMAXPROCS(4), then the master is allowed 4 parallel threads. I think it's too much. What if I want the master bound to 1 CPU thread/process as well? 

Therefore, what are your thoughts on:

> - On line 64 change from var max = runtime.GOMAXPROCS(0) to var max = runtime.GOMAXPROCS(1) . Assuming the user has set runtime.GOMAXPROCS(4) , the max variable will take a value of 4 (previous value of GOMAXPROCS as returned by the function runtime.GOMAXPROCS(n) ) while the runtime will have the GOMAXPROCS set to 1.

**Comment by Fenny** [comment]
I did some testing and it would not affect the current implementation 👌 As you said, you just have to change [prefork.go#64](https://github.com/gofiber/fiber/blob/master/prefork.go#L64) to `var max = runtime.GOMAXPROCS(0)`

Do you want to make a PR for this? Nice catch btw 👍

**Comment by Fenny** [comment]
Awesome work, this change will be shipped with the next tag 👍

**Comment by DevDevious** [comment]
@Fenny thanks and keep up the great work on **fiber**. ;)

**Comment by kiyonlin** [comment]
Hey @DevDevious thanks for bringing this issue.I have something to say about it.

In most cases the master will block, so it will rarely use CPU even it own all of them. Therefore, limiting the number of CPUs in the master process will not yield great benefits.  

However, if I need the master process to do some work that is inconvenient for workers (we can't assume that the user just use the worker processes), this is not a good idea.  

To give a few examples, 

1. Read data from the database and make statistics; 
2. Store the shared data in redis which are needed by worker processes; 
3. Do some crontab tasks.  

Of course these things can be done in another program, but this is another approach.  

My thought is that fiber provides configuration (like FIBER_MASTER_PROC and FIBER_CHILD_PROC) of the number of CPU cores occupied by the master and worker processes, which is controlled by the user. Would it be better?

Let me know what you think:smile:

**Comment by DevDevious** [comment]
Hey @kiyonlin . I agree that the benefits depend largely on one's goals and obviously if you wish to do work in the master process then maybe you would benefit from multiple threads. I also agree with having configuration settings for threads/master and number of worker processes. I think making thing configurable is almost always a great idea, however I am not a decision maker on the process. Maybe @Fenny wishes to have a say in on the subject ?

**Comment by Fenny** [comment]
After giving it some extra thought, @kiyonlin has a good point. In case you want to perform some caluclations on the master proc using `!fiber.IsChild()`, you might want to use as many threads as possible. 

I did some tests to make sure that having multiple idle master procs impacts performance and it does not, if no other work is defined the master proc only spawns child procs and remains idle until exit.

I'm not a big fan of implementing `FIBER_MASTER_PROCS` and `FIBER_CHILD_PROCS`, so it's better to keep it dumb and simple and revert the 1 thread max on the master process. ( https://github.com/gofiber/fiber/pull/821 )

What do you think @DevDevious?

**Comment by DevDevious** [comment]
@Fenny , if adding configuration flags like suggested by @kiyonlin is not an option and the defaults will be reverted as they were before I guess I'll go ahead and fork.
