### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by tredoe** [gofiber/fiber#80]
This is the first web framework/library at Go that really like to me.

**Comment by koddr** [comment]
@tredoe you're welcome! 👍 

Please, read [docs](https://fiber.wiki) and explore [recipes](https://github.com/gofiber/recipes) to be more productivity with Fiber 😉 

> If you want to write review for Fiber and share your feelings to all Fiber community on your own blog or Medium/Dev.to — we can add link to it on our repository (at new `README` version).
