### ISSUE TITLE
🤗 Should we check for context done/cancel on every handler

### ISSUE THREAD

**Issue by WLun001** [gofiber/fiber#805]
**Question description**
Should we check for context done/cancel on every handler? For the case like client cancel the request, and the handler should cancel the ongoing operation (db query etc). 

Possible to achieve with middleware, so that we don't keep repeating?

**Comment by Fenny** [comment]
If you are doing a database query it would be good practice to pass the `c.Context()`, but I personally always set a timeout with the db adaptor instead. It's up to you 👍

**Comment by WLun001** [comment]
@Fenny I get the idea, but how to implement it? `c.Context()` is not type of `context.Context`

How to make the context cancel when the response is canceled by client?

```go
func main() {
	app := fiber.New()

	app.Get("/", func(c *fiber.Ctx) error {
		go func() {
			select {
			case <-c.Context().Done():
				log.Println("done")
			}
		}()
		// assume some heavy operation will take 2 seconds
		// to make it cancelable
		_ = heavyOperation(c.Context())
		return c.SendString("Hello, World 👋!" + time.Now().Format(time.Kitchen))
	})
	log.Fatal(app.Listen(":3000"))
}

func heavyOperation(ctx context.Context) error {
	deadline, _ := ctx.Deadline()
	if deadline.Before(time.Now()) {
		time.Sleep(2 * time.Second)
		return nil
	}
	return nil
}
```

**Comment by Fenny** [comment]
The problem is that `*fiber.Ctx` is returned to the `sync.Pool` when you return from the handler. So `c.Context().Done()` becomes non-existent. It is better to handle the request in a separate thread while waiting for the context to be done.
```go
type Data struct {
	Data []int `json:"data"`
}

func main() {
	app := fiber.New()

	app.Get("/", func(ctx *fiber.Ctx) error {
		c, cancel := context.WithTimeout(ctx.Context(), 50*time.Millisecond)
		defer cancel()

		res := Data{}
		ch := make(chan Data)

		go process(ctx, ch)

		select {
		case <-c.Done():
			fmt.Printf("error: processing timeout\n")
			break
		case res = <-ch:
			fmt.Printf("finished processing\n")
		}

		return ctx.JSON(res)
	})
	log.Fatal(app.Listen(":3000"))
}

func process(ctx *fiber.Ctx, ch chan<- Data) {
	fmt.Printf("processing started...\n")
	time.Sleep(time.Duration(2 * time.Second)) // uncomment this
	fmt.Printf("ended after 50ms\n")

	a := []int{1, 2, 3, 4, 5, 6, 7, 8}
	rand.Seed(time.Now().UnixNano())
	rand.Shuffle(len(a), func(i, j int) { a[i], a[j] = a[j], a[i] })

	ch <- Data{a}
}
```

**Comment by WLun001** [comment]
Thanks for the example. If that is the case, then we can't extract it to a middleware i guess like `timeout`?
Because of `ch <- Data{a}`, it expects data from channel

**Comment by Fenny** [comment]
I'm afraid that is not possible nor efficient with fasthttp sync.pool design

**Comment by WLun001** [comment]
I guess the best alternative is limit response with `timeout` middleware. Close it for now.

**Comment by phxism** [comment]
> I guess the best alternative is limit response time with `timeout` middleware. Close it for now.

so for now it is impossible that when the client cancel the api request,  fiber sever cancel the process of this outdated request, like cancel db query, data-caculating?
while **net/http** supports this
````
func (s *Service) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	db := s.db
	switch r.URL.Path {
	default:
		http.Error(w, "not found", http.StatusNotFound)
		return
	case "/sleep":
		ctx, cancel := context.WithCancel(r.Context())
		defer cancel()

		_,err := db.QueryContext(ctx,"SELECT SLEEP(?)",10)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		io.WriteString(w, "ok")
		return`
```
