### ISSUE TITLE
🤗Freeze after upgrade

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#807]
**Question description**

After I [upgrade to /v2](https://github.com/suntong/fiber_demo/commit/8caf82751cf4b1406427b5b7f88b58d72b71ae9f#diff-3e887576511bb10e22463b74dabcbf34), all my fiber programs are frozen, like this:

```
go run app/shoes.go 

 âââââââââââââââââââââââââââââââââââââââââââââââââââââ
```

I need to ^-C to break them out.

For **Code snippet**,  please check out https://github.com/suntong/fiber_demo/blob/master/app/shoes.go

All of my Go modules are fine:

```sh
$ go mod verify
all modules verified
```

Please help

**Comment by kiyonlin** [comment]
I downloaded you demo repo and could run it normally:

![WX20200918-090625](https://user-images.githubusercontent.com/1214670/93543502-5120d580-f98e-11ea-951b-ec191524f803.png)

**Comment by kiyonlin** [comment]
BTW, I add go mod locally
```bash
fiber_demo [master] go mod init fix
```

**Comment by suntong** [comment]
Oh, thanks for the response, I continue to explore after I asked my question. 

Here are what I did:

```
rm go.*
go clean -cache -modcache -i -r
go mod init fiber_demo

$ go get -v -u github.com/gofiber/fiber/v2
go: downloading github.com/gofiber/fiber/v2 v2.0.1
go: downloading github.com/gofiber/fiber v1.14.6
go: github.com/gofiber/fiber/v2 upgrade => v2.0.1
go: downloading github.com/valyala/fasthttp v1.16.0
go: downloading golang.org/x/sys v0.0.0-20200909081042-eff7692f9009
go: downloading github.com/klauspost/compress v1.11.0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/andybalholm/brotli v1.0.0
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: github.com/klauspost/compress upgrade => v1.11.0
go: golang.org/x/sys upgrade => v0.0.0-20200917073148-efd3b9a0ff20
go: downloading golang.org/x/sys v0.0.0-20200917073148-efd3b9a0ff20
github.com/gofiber/fiber/v2/internal/encoding/ascii
golang.org/x/sys/internal/unsafeheader
github.com/gofiber/fiber/v2/internal/bytebufferpool
github.com/valyala/bytebufferpool
github.com/gofiber/fiber/v2/internal/schema
golang.org/x/sys/unix
github.com/gofiber/fiber/v2/utils
github.com/valyala/fasthttp/fasthttputil
github.com/klauspost/compress/flate
github.com/valyala/tcplisten
github.com/gofiber/fiber/v2/internal/encoding/json
github.com/valyala/fasthttp/stackless
github.com/andybalholm/brotli
github.com/valyala/fasthttp/reuseport
github.com/klauspost/compress/zlib
github.com/klauspost/compress/gzip
github.com/gofiber/fiber/v2/internal/isatty
github.com/gofiber/fiber/v2/internal/colorable
github.com/valyala/fasthttp
github.com/gofiber/fiber/v2
```

Then run it again, and got the exact same problem.

**Comment by kiyonlin** [comment]
I don't see go.mod in the repo, maybe you should upload it to github.

**Comment by suntong** [comment]
[done](https://github.com/suntong/fiber_demo/commit/a6f4e299387d21e34b87d00510356d5e7589c124)

**Comment by kiyonlin** [comment]
No problem here. 

Could you try to create a new demo with the quick start code?

**Comment by kiyonlin** [comment]
Do you have any chance to join our [Discord](https://discord.com/invite/bSnH7db)?

**Comment by suntong** [comment]
Fixed!

Upgraded from go version `go1.14.3` to the latest, `go1.15.2` fixed the problem. 

The `go1.14.3` is what comes default in Ubuntu 20.04 LTS:

```
$ apt-cache policy golang-1.14-go
golang-1.14-go:
  Installed: 1.14.3-2ubuntu2~20.04.1
  Candidate: 1.14.3-2ubuntu2~20.04.1
  Version table:
 *** 1.14.3-2ubuntu2~20.04.1 500
        500 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1.14.2-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

Better warn people about the minimum go version requirement. So I'd leave this one open until it is fixed.

**Comment by kiyonlin** [comment]
> Better warn people about the minimum go version requirement. So I'd leave this one open until it is fixed.

Fiber v2 just requires go 1.14.

And I use go 1.14.4 on my machine

```bash
go version go1.14.4 darwin/amd64
```

So I don't think go version is the key point.

**Comment by suntong** [comment]
Yes, you're right @kiyonlin. It turns out that my go cache was corrupted. Weird that `go clean -cache -modcache -i -r` and `go mod init ` weren't able to fix it. 

Thanks for all your help @kiyonlin !

**Comment by suntong** [comment]
I have two of my accounts with the same group id. I got one working, but can't get the other one work _no matter what_. 

    mkdir ~/gotest
    
    $ go mod init gotest
    go: creating new go.mod: module gotest

    $ go get -v -u github.com/gofiber/fiber/v2
    go: github.com/gofiber/fiber/v2 upgrade => v2.0.1
    
    $ cat go.mod 
    module gotest
    
    go 1.14
    
    require (
            github.com/gofiber/fiber/v2 v2.0.1 // indirect
            golang.org/x/sys v0.0.0-20200917073148-efd3b9a0ff20 // indirect
    )
        

    # prepare quickstart.go as follows

```
sudo rm -rf ${HOME}/go/

$ find ${HOME}/go/ | wc -l 
1
# only single empty dir left

$ go run quickstart.go
go: downloading github.com/gofiber/fiber/v2 v2.0.1
go: downloading github.com/valyala/fasthttp v1.16.0
go: downloading golang.org/x/sys v0.0.0-20200917073148-efd3b9a0ff20
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/klauspost/compress v1.11.0
go: downloading github.com/andybalholm/brotli v1.0.0
go: downloading github.com/valyala/bytebufferpool v1.0.0

 âââââââââââââââââââââââââââââââââââââââââââââââââââââ^C

$ find ${HOME}/go/ -type d | wc -l
140
# freshly downloaded by `go run`

$ cat quickstart.go
package main

import "github.com/gofiber/fiber/v2"

func main() {
        app := fiber.New()

        app.Get("/", func(c *fiber.Ctx) error {
                return c.SendString("Hello, World ð!")
        })

        app.Listen(":3000")
}

```

What else can I do? Pls help.

**Comment by suntong** [comment]
I can't get it working no matter what, so I build a brand new Debian 10 VM today and tried the above steps -- _I get the exact same result as above_. 

Having covered every possible case already, I've run out of ideas long time ago, so what was left were random wild guesses and trials, one of them being try with `uxterm` instead of the `xterm` that I had always been using. 

lo and behold, _it works!_

So all these time my failure has nothing to do with the new Go module, but the new `fiber` display and my beloved  `xterm` that I had always been using for decades. 

Please for the sake of  `xterm` users change the new `fiber` console display frame. 

To duplicate the freeze, run under `xterm` in Debian/Ubuntu, with `LANG=C`. 

Thanks

**Comment by hi019** [comment]
@suntong I've just tried with `xterm` and while the startup message was displayed incorrectly, the app still worked.
![image](https://user-images.githubusercontent.com/65871571/93670760-be566880-fa6b-11ea-8ae4-de533858d179.png)


For now you can disable the startup message:
```	
app := fiber.New(fiber.Config{
		DisableStartupMessage: true,
	})
```

**Comment by suntong** [comment]
Thanks @hi019, What's your `LANG` setting? I bet it is not `LANG=C`. What chartset are you using with `xterm`? Are you sure it is  `xterm`, not  linking to `uxterm` somehow underneath?

Thank for the way of disabling the startup message, I'll give it a try...

**Comment by hi019** [comment]
I'm on Arch so it may be my OS. You're right, I didn't set `LANG` to `C`. I've just reran the program with it set, and I get the same thing
![image](https://user-images.githubusercontent.com/65871571/93685606-83116500-fa7e-11ea-9357-453528fa58f1.png)

Do you still need my charset? How can I check?

**Comment by suntong** [comment]
Yeah, that looks like the output that I got when things were working. 
I do hope that the we can use a different startup message style, but feel free to close it...
