### ISSUE TITLE
can you not use emojis in commit messages? 

### ISSUE THREAD

**Issue by qlcom** [gofiber/fiber#811]

**Comment by kiyonlin** [comment]
Any reasons?

**Comment by qlcom** [comment]
it doesn't look good to read git log this way

**Comment by kiyonlin** [comment]
> it doesn't look good to read git log this way

Do you mean if there is no emoji font so that emojis are white squares?

**Comment by qlcom** [comment]
> Do you mean if there is no emoji font so that emojis are white squares?

that's one more reason.

**Comment by hi019** [comment]
Can you provide more info? The only issue I see when running `git log` is that there are white squares instead of emoji, which can be solved by installing the appropriate fonts.

**Comment by qlcom** [comment]
the issue is that emojis don't express the message properly.
