### ISSUE TITLE
🐛 v2 listening behavior changed

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#813]
**Fiber version**

`v2.0.1`

**Issue description**

v2 listening behavior changed -- previously it was listening on the networks, HOST 0.0.0.0, but now it is listening to localhost only, which doesn't make much sense any more, since `fiber` is supposed to be web server, that should be able to accept connecting from everywhere, not just originated from localhost only.

I tried to set to `0.0.0.0` again:

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

  // Steps to reproduce

  log.Fatal(app.Listen("0.0.0.0:3000"))
}
```

But the result is still listening to localhost only:

```
$ go run app/quickstart.go

 ┌───────────────────────────────────────────────────┐
 │                    Fiber v2.0.1                   │
 │               http://127.0.0.1:3000               │
 │                                                   │
 │ Handlers ............. 2  Threads ............ 12 │
 │ Prefork ....... Disabled  PID ............ 302968 │
 └───────────────────────────────────────────────────┘
```

**Comment by kiyonlin** [comment]
`http://127.0.0.1:3000` is shown on purpose(click it will open browser directly). 

The actually listen address is still `0.0.0.0:3000`

**Comment by suntong** [comment]
ok.
