### ISSUE TITLE
🔥 Consider adding support for custom Context

### ISSUE THREAD

**Issue by cgiacomi** [gofiber/fiber#82]
**Is your feature request related to a problem?**
I find myself in need to instantiate a validator and pass it to all the routes. I don't want to have any singletons in the application and so I am looking for a way to extend fiber.Context. 

**Describe the solution you'd like**
I would like to be able to extend the Context with my own custom Context which contains a 'Validator' property which I can set at server startup. The custom Context would be passed to all the routes and I could access the custom properties when needed in my routes.

**Describe alternatives you've considered**
The alternative is to have a singleton that I can access from my routes. But we all know why Singletons are not a good idea.

Another alternative would be to have a middleware to do this, but I don't want to instantiate a validator on every request.

**Comment by Fenny** [comment]
Hey @cgiacomi, could you show me an example on how you initiate your validater?

**Comment by ansarizafar** [comment]
Here is an example how echo framework allow to customize context and validator
https://echo.labstack.com/guide/context
https://echo.labstack.com/guide/request

**Comment by cgiacomi** [comment]
@Fenny tnx and sorry for the late reply, I saw the Locals method, but wasn't sure what the intended use was. I will try to see how it works out with that. 

By the way great work with the framework... I usually use Echo, but looking at Fiber it feels more like what I like. Again tnx for the great work!

**Comment by Fenny** [comment]
I'm closing this issue, if you got further questions feel free to re-open!

**Comment by risardi123** [comment]
Hello, @Fenny why there is error while make that function you give?, sorry i am very new in go languange
<img width="551" alt="image" src="https://user-images.githubusercontent.com/29408156/94124649-75455080-fe7f-11ea-9b50-53febb7d1bec.png">
