### ISSUE TITLE
🤔 Go 1.15 cannot find v2 package

### ISSUE THREAD

**Issue by liaohongxing** [gofiber/fiber#824]
When using "go run demo.go" in go1.15, it prompts that the package cannot be found

![20200924142213](https://user-images.githubusercontent.com/35255844/94108179-6b1c5580-fe71-11ea-8393-56518834d542.jpg)

**Comment by WLun001** [comment]
@liaohongxing  how is your `app.go` looks like?

**Comment by Fenny** [comment]
Try to use Go modules
```go
go mod init app
go mod tidy
```

**Comment by liaohongxing** [comment]
Thanks, the problem has been resolved.

**Comment by liaohongxing** [comment]
I’m an expressjs developer, and I’m trying out golang
