### ISSUE TITLE
🚀  app.Test should take `time.Duration` and not an int

### ISSUE THREAD

**Issue by kinbiko** [gofiber/fiber#827]
**Is your feature request related to a problem?**

Not really. Just noticed something unidiomatic.

**Describe the solution you'd like**

Change `Test()` signature from

```go
func (app *App) Test(req *http.Request, msTimeout ...int) (resp *http.Response, err error)
```

to

```go
func (app *App) Test(req *http.Request, timeout ...time.Duration) (resp *http.Response, err error)
```

so users don't have to read up on what unit the integer represents.

**Describe alternatives you've considered**

Unfortunately this is a breaking change, so I don't expect that it will happen anytime soon. But, maybe it can go on the backlog for a v3 in the distant future. Happy for this ticket to be closed, and considered in the future.

**Comment by Fenny** [comment]
I agree that `time.Duration` would be a better alternative, but like you said we cannot change the signature in v2. Noted for `v3` 👍
