### ISSUE TITLE
🤗  What's the equivalent of net/http's request.WithContext?

### ISSUE THREAD

**Issue by kinbiko** [gofiber/fiber#832]
**Question description**

I'd like to set a context value on the underlying `context.Context` (or `*fasthttp.Context` as retrievable in `c.Context()`) in a custom middleware, for logging/error reporting purposes.
I'm using a 3rd party library that takes  a `context.Context` as input and returns a `context.Context` with a value set.
How can I attach the returned `context.Context` to the `*fiber.Ctx` in the middleware?

In net/http I could use `req.WithContext(ctx)` to override the value that's returned by `req.Context()`, but I can't find this method in `*fiber.Ctx`.

```go
// req is *http.Request
ctx := req.Context()
ctx = bugsnag.NewSession(ctx)
ctx = log.WithField(ctx, "method", req.Method)
// etc.

req = req.WithContext(ctx)

// invoke next handler...
```

**Comment by Fenny** [comment]
`*fasthttp.RequestCtx` complies with the `context.Context` interface, so you can do the following:
```go
// c is *fiber.Ctx
ctx := c.Context()
ctx = bugsnag.NewSession(ctx)
ctx = log.WithField(ctx, "method", req.Method)
// etc.
```

**Comment by kinbiko** [comment]
That's not the problem I tried to describe above.

Getting ctx from `*fiber.Ctx` (`req.Context()` equivalent) 👍  .

Attaching updated ctx to `fiber.Ctx` (`req.WithContext()` equivalent) 👎 😖 .

**Comment by Fenny** [comment]
Fiber does not support the `WithContext` method, sorry.

**Comment by kinbiko** [comment]
@Fenny 
Would you accept a PR to add it? I don't know the codebase well enough to know if it's feasible to implement. Maybe it's not.

**Comment by Fenny** [comment]
If you could provide a good use-case for it, we can consider adding it to the API 👌

**Comment by morigs** [comment]
@Fenny Good use case IMO: creating a middleware for OpenTelemetry integration. OpenTelemetry creates new context when starting span and extracting context using propagator. This context should be passed down in order to provide tracing

**Comment by morigs** [comment]
I just found out about `SetUserContext`. It seems this is what had been requested
