### ISSUE TITLE
🐛 filesystem middleware doesn't work for routes with params

### ISSUE THREAD

**Issue by doingodswork** [gofiber/fiber#834]
## Fiber version

Both `v1.14.6` and `v2.0.2`

## Issue description

When using the filesystem middleware for a route that contains parameters, like `/:myparam/web`, it doesn't work.

## Code snippet

The following code is for v2, but as mentioned above it's the same for v1:

```go
package main

import (
	"net/http"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/filesystem"
)

func main() {
	app := fiber.New()

	// Works fine
	app.Use("/foo", filesystem.New(filesystem.Config{
		Root: http.Dir("./assets"),
	}))
	// Doesn't work
	app.Use("/:myparam/web", filesystem.New(filesystem.Config{
		Root: http.Dir("./assets"),
	}))

	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, World!")
	})

	app.Listen(":3000")
}
```

<details><summary>For your convenience, here's an `index.html` for testing (click me)</summary>
<pre>
<code>
&lt;html lang=&quot;en&quot;&gt;
&lt;head&gt;
    &lt;meta charset=&quot;UTF-8&quot;&gt;
    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
    &lt;title&gt;Fiber filesystem middleware test&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
    Fiber is great!
&lt;/body&gt;
&lt;/html&gt;
</code>
</pre>
</details>

## Reason

The reason is the same for v1 and v2:

v1 `filesystem.go`:
```go
// Set prefix
if len(prefix) == 0 {
	prefix = c.Route().Path // ===> Leads to what I declared in the route, like "/:myparam/web"
}

// Strip prefix
path := strings.TrimPrefix(c.Path(), prefix) // ===> The path is different, like "/123/web", so nothing is trimmed
if !strings.HasPrefix(path, "/") {
	path = "/" + path
}
```
v2 `filesystem.go`:
```go
// Set prefix once
once.Do(func() {
	prefix = c.Route().Path // =====> Same
})

// Strip prefix
path := strings.TrimPrefix(c.Path(), prefix) // =====> Same
if !strings.HasPrefix(path, "/") {
	path = "/" + path
}
```

## Potential fix

A fix requires the middleware to understand that ":param" is a param and can be anything. I'm sure the regular Fiber router already does something like that to properly find and call a handler that was registered with "/:foo/bar" and a request is to "/123/bar".

**Comment by Fenny** [comment]
This would mean we would have to parse the parameters on each request, it would be better to adjust your route logic since we are not using the param value within the handler:
```go
    // GET /123/web/movie.mp4 -> OPEN ./assets/:myparam/web/movie.mp4
    app.Use("/:myparam/web", filesystem.New(filesystem.Config{
        Root: http.Dir("./assets"),
    }))
    // GET /123/web/movie.mp4 -> OPEN ./assets/123/web/movie.mp4
    app.Use(filesystem.New(filesystem.Config{
        Root: http.Dir("./assets"),
    }))
```

**Comment by doingodswork** [comment]
In Discord you said:

> Yeah that won't work, because the filesystem just looks up the virtual file by prefix + path

But the middleware clearly intents *not* to do that, which is why it's calling `strings.TrimPrefix` to remove the prefix.

>  it would be better to adjust your route logic

That's not possible in my case, the `:myparam` value can be *anything*, so I can't add a million routes for all values. And I also can't move this value to a query param or request body, because the client that does the requests is from a third party and I'm just creating a service that has to respond to the client's request.

> This would mean we would have to parse the parameters on each request

The regular Fiber router already does that, no? That's what I was suggesting in the "Potential fix" section in my original comment.
You'd only have to do that for routes that have parameters, which you know at the time they're registered. So there's no performance hit for other routes. And the performance hit for routes with param is a thousand times better than the routes not working at all!

**Comment by renanbastos93** [comment]
Guys, I want to know more details about it, because I will be contributing later. Well, I understood that are wishing using parameters with the filesystem, right?

e.g
```go
app.Use("/:myparam/web", filesystem.New(filesystem.Config{
	Root: http.Dir("./assets"),
        handler: func(c *fiber.Ctx) error {
              // logic to use param
        },
}))
```

**Comment by doingodswork** [comment]
Hi @renanbastos93, thanks for considering to work on this!

In my case it's currently not important to access the parameter (yet), but more important to make the website show up at all. I'm creating a server for a third-party client and the client always sends some data as `:myparam`, so I can't use `/web` as route to my HTML files, I have to use `/:myparam/web`. But that doesn't work with Fiber's filesystem middleware, because it doesn't intelligently match the URL from the request with the registered route (i.e. the request is `/foo/web`, it sees a route `/:myparam/web` and matches it), but instead it just uses `strings.TrimPrefix` on the request URL to *remove* what I registered as route from the request URL. But that doesn't do anything because `":myparam" != "foo"`.

My current workaround is a redirect from `/:myparam/web` to `/web`. Another workaround could be a middleware that rewrites the path. But these workarounds are only enough when it's about showing the HTML files, it's not enough if someone wants to access `myparam`.

So I believe a proper solution would indeed match the path, and like you said, even put the `:myparam` data into the `myparam` parameter so it can later be fetched from the context to work with it.

I guess the regular Fiber router already has this logic baked in, how else would it match `/:myparam/foo` lines to regular API endpoints. So I'm sure there's some code that can be reused, maybe it's already a package or maybe it can be turned into a package and then imported in the filesystem middleware package.

**Comment by renanbastos93** [comment]
> Hi @renanbastos93, thanks for considering to work on this!
> 
> In my case it's currently not important to access the parameter (yet), but more important to make the website show up at all. I'm creating a server for a third-party client and the client always sends some data as `:myparam`, so I can't use `/web` as route to my HTML files, I have to use `/:myparam/web`. But that doesn't work with Fiber's filesystem middleware, because it doesn't intelligently match the URL from the request with the registered route (i.e. the request is `/foo/web`, it sees a route `/:myparam/web` and matches it), but instead it just uses `strings.TrimPrefix` on the request URL to _remove_ what I registered as route from the request URL. But that doesn't do anything because `":myparam" != "foo"`.
> 
> My current workaround is a redirect from `/:myparam/web` to `/web`. Another workaround could be a middleware that rewrites the path. But these workarounds are only enough when it's about showing the HTML files, it's not enough if someone wants to access `myparam`.
> 
> So I believe a proper solution would indeed match the path, and like you said, even put the `:myparam` data into the `myparam` parameter so it can later be fetched from the context to work with it.
> 
> I guess the regular Fiber router already has this logic baked in, how else would it match `/:myparam/foo` lines to regular API endpoints. So I'm sure there's some code that can be reused, maybe it's already a package or maybe it can be turned into a package and then imported in the filesystem middleware package.

@doingodswork 

Hi, I'm sorry I left, I had an accident. So, I believe I did understand that we need to give the possibility to use parameters in the route when using the file system. Right? 

Now I will investigate and doing many tests to understand this behavior after that fix it.

**Comment by Fenny** [comment]
What if we add a method to the middleware to serve single files?
```go
app.Get("/:user", func(c *fiber.Ctx) error {
  return filesystem.Send(c.Params(":users") + ".txt")
})
```
