### ISSUE TITLE
🚀 Support max-age directive on cookie config

### ISSUE THREAD

**Issue by falsandtru** [gofiber/fiber#858]
**Is your feature request related to a problem?**
Can't use max-age instead of expires.
**Describe the solution you'd like**
```
Cookie: &fiber.Cookie{
	MaxAge: 24 * time.Hour,
	// Omit the expires directive.
	Expires: nil, // or time.Unix(0, -1)?
},
```
**Describe alternatives you've considered**

**Additional context**

**Comment by Fenny** [comment]
Adding support for `Max-Age` in https://github.com/gofiber/fiber/pull/860, keep in mind that `Max-Age` is the newer version of 'expires' and some browsers may not support it. <https://mrcoles.com/media/test/cookies-max-age-vs-expires.html>.

To cross-platform expire a cookie you can use
```go
Cookie: &fiber.Cookie{
	Expires: time.Now().Add(-1 * time.Second),
},
```
