### ISSUE TITLE
🤗 Congratulations. Is JSON:API supported?

### ISSUE THREAD

**Issue by frederikhors** [gofiber/fiber#859]
Congratulations on this project! I only found out today.

Can I ask if it natively supports https://jsonapi.org?

**Comment by Fenny** [comment]
Thank you @frederikhors!

Could you try to explain what you mean by _natively supporting https://jsonapi.org?_

Fiber supports serializing JSON <https://docs.gofiber.io/api/ctx#json>

**Comment by frederikhors** [comment]
Forgive me.

I meant if there is any nice example of JSON: API server already working to replace Rails in use with projects like ember-data.

But I realized the question was wrong.

Thanks for your great work!

**Comment by jozsefsallai** [comment]
Someone could make a middleware for that or a boilerplate or something :eyes:

**Comment by yaliv** [comment]
To conform with the [Client Responsibilities of JSON:API](https://jsonapi.org/format/#content-negotiation-clients), I hope the mimetype `application/vnd.api+json` could be injected to `c.BodyParser()`.

Example in Express:
```js
const router = express.Router()
router.use(bodyParser.json({ type: "application/vnd.api+json" }))
```
