### ISSUE TITLE
🤔 unable to to install fiber v2

### ISSUE THREAD

**Issue by birraasmile** [gofiber/fiber#870]
**Fiber version**
V2

**Issue description**
-unable to install fiber using:  go get github.com/gofiber/fiber/v2

output:
➜  ~ go get github.com/gofiber/fiber/v2
cannot find package "github.com/gofiber/fiber/v2" in any of:
	/usr/local/go/src/github.com/gofiber/fiber/v2 (from $GOROOT)
	/Users/birraasmile/go/src/github.com/gofiber/fiber/v2 (from $GOPATH)

**Comment by Fenny** [comment]
Please check out https://github.com/gofiber/fiber/issues/824, https://github.com/gofiber/fiber/issues/788 to see if it solves your problem.

**Comment by birraasmile** [comment]
thanks for your reply , I see that the Go module for a project is a must to use  for v2. 

I wish I had option to use v2 without Go module :)

**Comment by Fenny** [comment]
To be fair, go modules are the default since Go 1.13 <https://blog.golang.org/using-go-modules>
I don't see any advantages to not use a `go.mod`, I'm closing this issue since it's solved!

Feel free to re-open if you have further problems.
