### ISSUE TITLE
👚 Hacktoberfest 2020 🍁

### ISSUE THREAD

**Issue by Fenny** [gofiber/fiber#873]
![](https://user-images.githubusercontent.com/7844510/94886159-35163d00-0440-11eb-8310-717517021b40.png)

To earn your Hacktoberfest **t-shirt** or **tree** reward, you must register and make **four** valid pull requests (PRs) between **October 1-31**, read the [participation details](https://hacktoberfest.digitalocean.com/details) to learn how to earn your Hacktoberfest tee or tree reward.

## Ways to contribute
- Extend [function descriptions](https://pkg.go.dev/github.com/gofiber/fiber/v2#App) with more detailed explanation
- Update / fix [docs](https://github.com/gofiber/docs) with better explanation / examples
- Create more [recipes](https://github.com/gofiber/recipes)
- Add more test cases for all [middleware packages](https://github.com/gofiber/fiber/tree/master/middleware)

## Hacktoberfest information
- Be sure to sign up at https://hacktoberfest.digitalocean.com so you can qualify to pick a limited edition t-shirt :womans_clothes:
- Create a Pull Request between October 1-31 of 2020 to count towards your 4 PRs
- See https://hacktoberfest.digitalocean.com for more details

**Comment by eacp** [comment]
Hello. I am fluent in both english and spanish. If I help translating untranslated sections, would that count for hacktoberfest?

**Comment by kiyonlin** [comment]
Wait for Tee 😄 
![image](https://user-images.githubusercontent.com/1214670/97077754-c9775800-1618-11eb-9eb6-882b8ef28e5d.png)

**Comment by codemicro** [comment]
Exciting! I've got 12 days to wait until I can claim mine 😁
