### ISSUE TITLE
🤗 LTS for gofiber will be nice !

### ISSUE THREAD

**Issue by alfuhigi** [gofiber/fiber#887]
**Question description**
isn't is good idea if **gofiber**  has version **LTS** for long term support and not quickly change API AS you do  🤗🤗🤗

**Comment by renanbastos93** [comment]
> **Question description**
> isn't is good idea if **gofiber** has version **LTS** for long term support and not quickly change API AS you do 🤗🤗🤗

Hey dude, I liked your suggestion we can plan a timeline to versions the like NodeJS for continuous maintenance.

e.g
![image](https://user-images.githubusercontent.com/8202898/95253258-859cea00-07f4-11eb-8ae1-95e7583ff729.png)

**Comment by Fenny** [comment]
We maintain all versions regarding security issues / bugs, `v1` is still available <https://github.com/gofiber/fiber/tree/v1>.
Every major version will not change its API design in a breaking way, and all versions are stable and production-ready.
