### ISSUE TITLE
🤗 How to set request headers in middleware, and access them from a handler

### ISSUE THREAD

**Issue by kumarvadivel** [gofiber/fiber#890]
**Is your feature request related to a problem?**
yes
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
documentation should be updated no context for basic auth and stuffs..

**Comment by napei** [comment]
Hey @kumarvadivel 
Not too sure what you're referring to. I assume you want to modify a request header in a middleware, then see that in a handler?

You can achieve this like so:
```go
package main

import (
	"github.com/gofiber/fiber/v2"
)

func mwTest(c *fiber.Ctx) error {
	c.Request().Header.Add("test", "testvalue")
	return c.Next()
}

func main() {
	app := fiber.New()

	app.Get("/", mwTest, func(c *fiber.Ctx) error {
		return c.SendString(c.Get("test"))
	})

	app.Listen(":3000")
}
```

**Comment by napei** [comment]
Regarding your comment about documentation, middleware docs are available here https://docs.gofiber.io/api/middleware

**Comment by kumarvadivel** [comment]
thanks
