### ISSUE TITLE
🤗 how to make fiber graceful shutdown

### ISSUE THREAD

**Issue by koungkub** [gofiber/fiber#899]
How to implement graceful shutdown

**Comment by hi019** [comment]
Take a look at `app.Shutdown`: https://github.com/gofiber/fiber/blob/5d8e5339464fdbddc46db44534e9e00446adc3cc/app.go#L550

**Comment by codemicro** [comment]
To add to this - if you would like to implement a graceful shutdown that is triggered by an interrupt signal, you could do something like the following:

```go
package main

import (
    "log"
        "fmt"
        "github.com/gofiber/fiber/v2"
        "os"
        "os/signal"
)

func main() {

        app := fiber.New()

        c := make(chan os.Signal, 1)
        signal.Notify(c, os.Interrupt)
        go func() {
                _ = <-c
                fmt.Println("Gracefully shutting down...")
                _ = app.Shutdown()
        }()

        // ...

        if err := app.Listen(":3000"); err != nil {
                log.Panic(err)
        }

        fmt.Println("Running cleanup tasks...")
        // Your cleanup tasks go here
}
```

Output
```
K: via 🐹 v1.15.2 took 1m29s
❯ go run .\main.go

 ┌───────────────────────────────────────────────────┐
 │                    Fiber v2.0.6                   │
 │               http://127.0.0.1:3000               │
 │                                                   │
 │ Handlers ............. 0  Threads ............. 8 │
 │ Prefork ....... Disabled  PID ............. 18672 │
 └───────────────────────────────────────────────────┘

^CGracefully shutting down...
Running cleanup tasks...
```

**Comment by codemicro** [comment]
If you need any more help, feel free to re-open.

**Comment by frederikhors** [comment]
@codemicro Can we add this to recipes, what do you think?

**Comment by codemicro** [comment]
@frederikhors that sounds like a great idea! I'll submit a pull request today, unless you want to?

**Comment by frederikhors** [comment]
> @frederikhors that sounds like a great idea! I'll submit a pull request today, unless you want to?

I do not have time right now.

**Comment by codemicro** [comment]
No worries! I'll do it.

**Comment by frederikhors** [comment]
I do not understand with your code how to change Shutdown timeout. Is there a way or I have to use custom code for this?

**Comment by frederikhors** [comment]
I think this code is not working, @codemicro.

I cannot get `fmt.Println("Gracefully shutting down...")` printed for example.

**Comment by frederikhors** [comment]
It works. My fault.

The only problem is timeout now.

**Comment by codemicro** [comment]
This example has no shutdown timeout - as soon as an interrupt is received, `app.Shutdown` is called.

**Comment by frederikhors** [comment]
Ok. I was talking about something like this: https://github.com/go-chi/chi/tree/master/_examples/graceful.

Thanks again!

**Comment by mdaliyan** [comment]
Is fiber still lack shutdown timeout? What happens if one connection doesn't close for any reason for minutes?

**Comment by juliankoehn** [comment]
@mdaliyan guess that's why we could use https://github.com/gofiber/fiber/tree/master/middleware/timeout 🍡

**Comment by mdaliyan** [comment]
> @mdaliyan guess that's why we could use https://github.com/gofiber/fiber/tree/master/middleware/timeout 🍡

That solves the problem in one way and adds another one in the other way. This way we define the timeout to the routes, possibly with different values set for different routes. So, to understand there is a timeout in work, we need to read the code and realize there is a timeout defined somewhere.

What I mean is it's not just obvious with one glance, which I personally don't like it that much.

**Comment by Mattioli** [comment]
@codemicro sorry for bringing this up after a long time, but I was reading on how to make a shutdown using fiber and reading `Shutdown`'s documentation I had a doubt. The documentation says:

```
// Shutdown gracefully shuts down the server without interrupting any active connections.
// Shutdown works by first closing all open listeners and then waiting indefinitely for all connections to return to idle and then shut down.
//
// Make sure the program doesn't exit and waits instead for Shutdown to return.
//
// Shutdown does not close keepalive connections so its recommended to set ReadTimeout to something else than 0.
```

As I understood, `Shutdown` will, in that order: (1) close all open listeners and then (2) wait for all connections to return and then (3) shut down. Which means that it will make `Listen` return `nil` as soon the step (1) runs, meaning that we need to wait for step (2) to actually happen, otherwise we might kill handlers' processing without them have finished. This is explicited by the line `Make sure the program doesn't exit and waits instead for Shutdown to return.`.

As your suggestion doesn't wait for `Shutdown` (because it's running inside a not synced go routine), then we might kill those still alive connections and its processings; is that correct? If so, maybe the solution is just to wait for the shutdown ending with a channel or some wait group, something like the following?

```go
package main

import (
    "log"
        "fmt"
        "github.com/gofiber/fiber/v2"
        "os"
        "os/signal"
)

func main() {

        app := fiber.New()

        c := make(chan os.Signal, 1)
        signal.Notify(c, os.Interrupt)
        
        gracefulShutdown := make(chan struct{})
        
        go func() {
                _ = <-c
                fmt.Println("Gracefully shutting down...")
                _ = app.Shutdown()
                gracefulShutdown <- struct{}{}
        }()

        // ...

        if err := app.Listen(":3000"); err != nil {
                log.Panic(err)
        }
        
        <-gracefulShutdown

        fmt.Println("Running cleanup tasks...")
        // Your cleanup tasks go here
}
```

Please, correct me if I'm wrong and thanks for the help!

**Comment by codemicro** [comment]
> is that correct?

I don't remember - it's been a long time since I looked at this, and I'm also no longer on the maintainers team. I don't have the time to look at this, I'm afraid.

**Comment by lucasoares** [comment]
> @codemicro sorry for bringing this up after a long time, but I was reading on how to make a shutdown using fiber and reading `Shutdown`'s documentation and then I had a doubt. The documentation says:
> 
> ```
> // Shutdown gracefully shuts down the server without interrupting any active connections.
> // Shutdown works by first closing all open listeners and then waiting indefinitely for all connections to return to idle and then shut down.
> //
> // Make sure the program doesn't exit and waits instead for Shutdown to return.
> //
> // Shutdown does not close keepalive connections so its recommended to set ReadTimeout to something else than 0.
> ```
> 
> As I understood, `Shutdown` will, in that order: (1) close all open listeners, (2) wait for all connections to return and then (3) shut down. Which means that it will make `Listen` return `nil` as soon the step 1 runs, meaning that we need to wait for step 2 to actually happen, otherwise we might kill handlers' processing without having them finish their work. This is explicit by the line `Make sure the program doesn't exit and waits instead for Shutdown to return.`.
> 
> As your suggestion doesn't wait for `Shutdown` (because it's running inside a not synced go routine), then it might happen that still alive connections and its processing might be killed; is that correct? If so, maybe the solution is just to wait for the shutdown ending with a channel or some wait group, something like the following?
> 
> ```go
> package main
> 
> import (
>     "log"
>         "fmt"
>         "github.com/gofiber/fiber/v2"
>         "os"
>         "os/signal"
> )
> 
> func main() {
> 
>         app := fiber.New()
> 
>         c := make(chan os.Signal, 1)
>         signal.Notify(c, os.Interrupt)
>         
>         serverShutdown := make(chan struct{})
>         
>         go func() {
>                 _ = <-c
>                 fmt.Println("Gracefully shutting down...")
>                 _ = app.Shutdown()
>                 serverShutdown <- struct{}{}
>         }()
> 
>         // ...
> 
>         if err := app.Listen(":3000"); err != nil {
>                 log.Panic(err)
>         }
>         
>         <-serverShutdown
> 
>         fmt.Println("Running cleanup tasks...")
>         // Your cleanup tasks go here
> }
> ```
> 
> And just for clarity, in case someone use the solution above: assuming the solution is correct, another attention point arises: the documentation also says (last line) that `Shutdown` doesn't kill keepalive connections and now that the application is actually waiting for connections to end, we need to set the config's `ReadTimeout` variable for something other than 0, otherwise we might wait forever for keepalive connections to be closed.
> 
> Please, correct me if I'm wrong and thanks for the help!

Correct. You may also use a WaitGroup to wait for the shutdown.

About the second part I honestly don't know if the keepalive connection will force shutdown to wait indefinately. We should test it.

**Comment by rrandall91** [comment]
> @codemicro sorry for bringing this up after a long time, but I was reading on how to make a shutdown using fiber and reading `Shutdown`'s documentation and then I had a doubt. The documentation says:
> 
> ```
> // Shutdown gracefully shuts down the server without interrupting any active connections.
> // Shutdown works by first closing all open listeners and then waiting indefinitely for all connections to return to idle and then shut down.
> //
> // Make sure the program doesn't exit and waits instead for Shutdown to return.
> //
> // Shutdown does not close keepalive connections so its recommended to set ReadTimeout to something else than 0.
> ```
> 
> As I understood, `Shutdown` will, in that order: (1) close all open listeners, (2) wait for all connections to return and then (3) shut down. Which means that it will make `Listen` return `nil` as soon the step 1 runs, meaning that we need to wait for step 2 to actually happen, otherwise we might kill handlers' processing without having them finish their work. This is explicit by the line `Make sure the program doesn't exit and waits instead for Shutdown to return.`.
> 
> As your suggestion doesn't wait for `Shutdown` (because it's running inside a not synced go routine), then it might happen that still alive connections and its processing might be killed; is that correct? If so, maybe the solution is just to wait for the shutdown ending with a channel or some wait group, something like the following?
> 
> ```go
> package main
> 
> import (
>     "log"
>         "fmt"
>         "github.com/gofiber/fiber/v2"
>         "os"
>         "os/signal"
> )
> 
> func main() {
> 
>         app := fiber.New()
> 
>         c := make(chan os.Signal, 1)
>         signal.Notify(c, os.Interrupt)
>         
>         serverShutdown := make(chan struct{})
>         
>         go func() {
>                 _ = <-c
>                 fmt.Println("Gracefully shutting down...")
>                 _ = app.Shutdown()
>                 serverShutdown <- struct{}{}
>         }()
> 
>         // ...
> 
>         if err := app.Listen(":3000"); err != nil {
>                 log.Panic(err)
>         }
>         
>         <-serverShutdown
> 
>         fmt.Println("Running cleanup tasks...")
>         // Your cleanup tasks go here
> }
> ```
> 
> And just for clarity, in case someone use the solution above: assuming the solution is correct, another attention point arises: the documentation also says (last line) that `Shutdown` doesn't kill keepalive connections and now that the application is actually waiting for connections to end, we need to set the config's `ReadTimeout` variable for something other than 0, otherwise we might wait forever for keepalive connections to be closed.
> 
> Please, correct me if I'm wrong and thanks for the help!

This is exactly what I needed. Thanks!

**Comment by mdaliyan** [comment]
> > @codemicro sorry for bringing this up after a long time, but I was reading on how to make a shutdown using fiber and reading `Shutdown`'s documentation and then I had a doubt. The documentation says:
> > ```
> > // Shutdown gracefully shuts down the server without interrupting any active connections.
> > // Shutdown works by first closing all open listeners and then waiting indefinitely for all connections to return to idle and then shut down.
> > //
> > // Make sure the program doesn't exit and waits instead for Shutdown to return.
> > //
> > // Shutdown does not close keepalive connections so its recommended to set ReadTimeout to something else than 0.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > As I understood, `Shutdown` will, in that order: (1) close all open listeners, (2) wait for all connections to return and then (3) shut down. Which means that it will make `Listen` return `nil` as soon the step 1 runs, meaning that we need to wait for step 2 to actually happen, otherwise we might kill handlers' processing without having them finish their work. This is explicit by the line `Make sure the program doesn't exit and waits instead for Shutdown to return.`.
> > As your suggestion doesn't wait for `Shutdown` (because it's running inside a not synced go routine), then it might happen that still alive connections and its processing might be killed; is that correct? If so, maybe the solution is just to wait for the shutdown ending with a channel or some wait group, something like the following?
> > ```go
> > package main
> > 
> > import (
> >     "log"
> >         "fmt"
> >         "github.com/gofiber/fiber/v2"
> >         "os"
> >         "os/signal"
> > )
> > 
> > func main() {
> > 
> >         app := fiber.New()
> > 
> >         c := make(chan os.Signal, 1)
> >         signal.Notify(c, os.Interrupt)
> >         
> >         serverShutdown := make(chan struct{})
> >         
> >         go func() {
> >                 _ = <-c
> >                 fmt.Println("Gracefully shutting down...")
> >                 _ = app.Shutdown()
> >                 serverShutdown <- struct{}{}
> >         }()
> > 
> >         // ...
> > 
> >         if err := app.Listen(":3000"); err != nil {
> >                 log.Panic(err)
> >         }
> >         
> >         <-serverShutdown
> > 
> >         fmt.Println("Running cleanup tasks...")
> >         // Your cleanup tasks go here
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And just for clarity, in case someone use the solution above: assuming the solution is correct, another attention point arises: the documentation also says (last line) that `Shutdown` doesn't kill keepalive connections and now that the application is actually waiting for connections to end, we need to set the config's `ReadTimeout` variable for something other than 0, otherwise we might wait forever for keepalive connections to be closed.
> > Please, correct me if I'm wrong and thanks for the help!
> 
> This is exactly what I needed. Thanks!

This one might freeze in case the server can't start (i.e. the port is already in use).

**Comment by codemicro** [comment]
If people are going to keep quote replying to this, _please_ remove the @mention of me.

**Comment by josephjang** [comment]
> This one might freeze in case the server can't start (i.e. the port is already in use).

Actually, it does not freeze because `log.Panic()` will exist when `app.Listen()` fails.
But, we would not want to depend on `app.Listen()`'s behavior or how to handle a failure from it.
It seems better to use a WaitGroup. This code does not freeze even when `app.Listen()` fails and it does not panic.

```go
package main

import (
        "log"
        "fmt"
        "github.com/gofiber/fiber/v2"
        "os"
        "os/signal"
        "sync"
)

func main() {

        app := fiber.New()

        c := make(chan os.Signal, 1)
        signal.Notify(c, os.Interrupt)
        
        var serverShutdown sync.WaitGroup
        
        go func() {
                _ = <-c
                fmt.Println("Gracefully shutting down...")
                serverShutdown.Add(1)
                defer serverShutdown.Done()
                _ = app.ShutdownWithTimeout(60 * time.Second)
        }()

        // ...

        if err := app.Listen(":3000"); err != nil {
                log.Panic(err)
        }
        
        serverShutdown.Wait()

        fmt.Println("Running cleanup tasks...")
        // Your cleanup tasks go here
}
```

**Comment by yusrenaltair** [comment]
Can I combine this function with prefork feature? how to place the code so that panic doesn't appear?
Thanks in advance.

**Comment by yusrenaltair** [comment]
> > This one might freeze in case the server can't start (i.e. the port is already in use).
> 
> Actually, it does not freeze because `log.Panic()` will exit when `app.Listen()` fails. But, we would not want to depend on `app.Listen()`'s behavior or how to handle a failure from it. It seems better to use a WaitGroup. This code does not freeze even when `app.Listen()` fails and it does not panic.
> 
> (Sorry for digging this out but it seems still relevant to Google ;) )
> 
> ```go
> package main
> 
> import (
>         "log"
>         "fmt"
>         "github.com/gofiber/fiber/v2"
>         "os"
>         "os/signal"
>         "sync"
> )
> 
> func main() {
> 
>         app := fiber.New()
> 
>         c := make(chan os.Signal, 1)
>         signal.Notify(c, os.Interrupt)
>         
>         var serverShutdown sync.WaitGroup
>         
>         go func() {
>                 _ = <-c
>                 fmt.Println("Gracefully shutting down...")
>                 serverShutdown.Add(1)
>                 defer serverShutdown.Done()
>                 _ = app.ShutdownWithTimeout(60 * time.Second)
>         }()
> 
>         // ...
> 
>         if err := app.Listen(":3000"); err != nil {
>                 log.Panic(err)
>         }
>         
>         serverShutdown.Wait()
> 
>         fmt.Println("Running cleanup tasks...")
>         // Your cleanup tasks go here
> }
> ```
Hi @josephjang.
Can I combine this function with prefork feature? how to place the code so that panic doesn't appear?
(I have tried turning on the prefork feature but it failed)
Thanks in advance.

**Comment by Pavelt132** [comment]
This one might freeze in case the cancellation arrives before the server starts.
