### ISSUE TITLE
🚀 middleware/monitor do lot of memory allocation

### ISSUE THREAD

**Issue by TomasVojacek** [gofiber/fiber#910]
**Fiber version**
2.0.6
**Issue description**
with monitor enabled total allocation of application increased from 102MB to 513MiB
after 30seconds memory allocation stabilize to +50MB each 10sec
without monitor it is  +0MB each 10sec
**Code snippet**

```go
package main

import (
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"runtime"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/monitor"

	"bmb-api/controller"
)

func main() {
	go WatchMemory()
	app := fiber.New()
	app.Get("/serverstats", monitor.New())
	app.Get("/hello", controller.NotImplemented)
	// Steps to reproduce
	for i:=1;i<100;i++{
		go GetHello()
	}
	log.Fatal(app.Listen(":8099"))


}
func WatchMemory() {
	for {
		var m runtime.MemStats
		runtime.ReadMemStats(&m)
		fmt.Printf("\tTotalAlloc = %v MB", m.TotalAlloc/1000000)
		time.Sleep(time.Second * 10)
	}
}

func GetHello(){
	time.Sleep(time.Second*2)
	fmt.Println("Start")
	for i:=1;i<100;i++{
	req, err := http.NewRequest("GET", "http://127.0.0.1:8099/hello", nil)
	if err != nil {
		fmt.Println(err)
		return
	}
	req.Header.Add("Content-Type", "application/json")
		client := &http.Client{
		}
	res, err := client.Do(req)
	if err!=nil{
		fmt.Println(err)
		return
	}

	defer res.Body.Close()
	_, err = ioutil.ReadAll(res.Body)
	if err!=nil{
		fmt.Println(err)
		return
	}
	}
	fmt.Println("get Done")
}

```

**Comment by codemicro** [comment]
Hi!

The `monitor` middleware works by starting a goroutine that runs in the background of your Fiber app. This updates a set of stored values (CPU usage, memory usage, etc) every single second, hence the increasing amount of allocated memory that you're seeing here.

https://github.com/gofiber/fiber/blob/9856573d418d9e959a3165dc20795f45e9814734/middleware/monitor/monitor.go#L59-L66

https://github.com/gofiber/fiber/blob/9856573d418d9e959a3165dc20795f45e9814734/middleware/monitor/monitor.go#L90-L108

When a Fiber app is running with the `monitor` middleware, I'm seeing a pretty consistent 14MB of memory usage, regardless of the amount of memory that's being allocated.

![Taskmgr_2020-10-10_14-22-29](https://user-images.githubusercontent.com/25284325/95656410-31507d80-0b06-11eb-8b13-147cb36e2058.png)

**Comment by kiyonlin** [comment]
Hi @TomasVojacek ! Besides what @codemicro showed above, please see the document of `runtime.MemStats`:

> 	// TotalAlloc is cumulative bytes allocated for heap objects.
	//
	// TotalAlloc increases as heap objects are allocated, but
	// unlike Alloc and HeapAlloc, it does not decrease when
	// objects are freed.
	TotalAlloc uint64

and

> 	// HeapAlloc is bytes of allocated heap objects.
	//
	// "Allocated" heap objects include all reachable objects, as
	// well as unreachable objects that the garbage collector has
	// not yet freed. Specifically, HeapAlloc increases as heap
	// objects are allocated and decreases as the heap is swept
	// and unreachable objects are freed. Sweeping occurs
	// incrementally between GC cycles, so these two processes
	// occur simultaneously, and as a result HeapAlloc tends to
	// change smoothly (in contrast with the sawtooth that is
	// typical of stop-the-world garbage collectors).
	HeapAlloc uint64

You should use `HeapAlloc` in the snippet.

**Comment by TomasVojacek** [comment]
As I under stand part of fiber performance optimatization is low memory allocation. Monitor allocate significantly more memory than fiber it self.
I have rerun the test and there is no perfomance hit.
Closing
