### ISSUE TITLE
🐛 Display message misses 1 PID when GOMAXPOCS >= 5

### ISSUE THREAD

**Issue by DevDevious** [gofiber/fiber#912]
**Fiber version**

master

**Issue description**

When `Prefork=true`  and `GOMAXPROCS >= 5` , the display message always misses (fails to display) one PID.

**Comment by codemicro** [comment]
Hi @DevDevious, nice catch and thanks for reporting!

Looks like I missed this when I was implementing the child PID display. It misses one PID for every line that's added to it display, not just when `GOMAXPROCS >= 5`.

For example, `10752` is missing from here, despite it being in the raw PID list.
![image](https://user-images.githubusercontent.com/25284325/95664803-15b79800-0b43-11eb-8ef0-5bd348696df4.png)

**Comment by DevDevious** [comment]
Hi @codemicro, It happens, I am sure you worked too fast. :)
