### ISSUE TITLE
🎉 Fiber Updates

### ISSUE THREAD

**Issue by Fenny** [gofiber/fiber#92]
<img src="https://user-images.githubusercontent.com/25108519/74117516-37c5d880-4bb8-11ea-8ddd-82eaf64cd102.gif" height="100">**Fiber reached** `2k` **stars in only [3 weeks](https://starchart.cc/gofiber/fiber)!** 🌟

We want to thank everybody for supporting this young ( but ambitious ) project!

**Fiber v2.0.0-pre-release**
Add multiple handlers inside routes & groups.
```go
func main() {
  // ...
  app.Get("/", middleware(), middleware(), handler())
}
```
Pass optional settings in the app initiation.
```go
func main() {
  app := fiber.New(&fiber.Settings{
    Prefork:       true,
    CaseSensitive: true,
    StrictRouting: true,
    ServerHeader:  "Go",
    // etc...
  })
}
```
Chain groups
```go
func main() {
  app := fiber.New()
  
  api := app.Group("/api", cors())  // /api

  v1 := api.Group("/v1", mysql())   // /api/v1
  v1.Get("/list", handler)          // /api/v1/list
  v1.Get("/user", handler)          // /api/v1/user

  v2 := api.Group("/v2", mongodb()) // /api/v2
  v2.Get("/list", handler)          // /api/v2/list
  v2.Get("/user", handler)          // /api/v2/user
  
  app.Listen(3000)
}
```
Recover from panics
```go
func main() {
  app := fiber.New()

  app.Get("/", func(c *fiber.Ctx) {
    panic("Something went wrong!")
  })

  app.Recover(func(c *fiber.Ctx) {
    c.Status(500).Send(c.Error())
    // => 500 "Something went wrong!"
  })

  app.Listen(3000)
}
```
Websocket support using [gorilla *Conn](https://godoc.org/github.com/gorilla/websocket#Conn)
```go
func main() {
  app := fiber.New()

  app.WebSocket("/ws/:name", func(c *fiber.Conn) {
    log.Println(c.Params("name"))
    for {
      mt, msg, err := c.ReadMessage()
      if err != nil {
        log.Println("read:", err)
        break
      }
      log.Printf("recv: %s", msg)
      err = c.WriteMessage(mt, msg)
      if err != nil {
        log.Println("write:", err)
        break
      }
    }
  })
  // ws://localhost:3000/ws/john
  app.Listen(3000)
}
```
**New features**
ctx.BodyParser / https://fiber.wiki/context#bodyparser
ctx.Error / https://fiber.wiki/context#error
ctx.Next / https://fiber.wiki/context#next
ctx.Render / https://fiber.wiki/context#render

app.New / https://fiber.wiki/application#settings
app.Recover / https://fiber.wiki/application#recover
app.Group / https://fiber.wiki/application#group
🎉 app.WebSocket / https://fiber.wiki/application#websocket
app.Settings / https://fiber.wiki/application#settings

**Deprecated**
~~ctx.BasicAuth~~
~~ctx.Json~~
~~ctx.JsonBytes~~
~~ctx.JSONBytes~~
~~ctx.JsonString~~
~~ctx.JSONString~~
~~ctx.Xml~~
~~ctx.XML~~

~~app.Prefork~~
~~app.Engine~~
~~app.Banner~~

If you got suggestions, ideas or criticism please leave a comment!

**Comment by izacximenes** [comment]
I was testing it and i did create my own group-prefix system based on function. what do you think about that?

![image](https://user-images.githubusercontent.com/33349688/74173217-7b4c3100-4c10-11ea-96f6-e49e30008344.png)

**Comment by EdneyMesquita** [comment]
> I was testing it and i did create my own group-prefix system based on function. what do you think about that?
> 
> ![image](https://user-images.githubusercontent.com/33349688/74173217-7b4c3100-4c10-11ea-96f6-e49e30008344.png)

Do you have some picture?

**Comment by Fenny** [comment]
@izacximenes thats an interesting way to go about it, thanks for your idea!

**Comment by 1995parham** [comment]
I have implemented a simple URL shortener with `gofiber` and it was an awesome experience for me. `gofiber` is simple and yet powerful. I am writing tests and more documentation for my project that is available [here](https://github.com/1995parham/koochooloo).

**Comment by simoneromano96** [comment]
Hello, I am interested in using this HTTP framework, as a prerequisite I need Redis based session, I saw that the session middleware is empty so I get that sessions are not yet implemented, where could I start in implementing them?

**Comment by Fenny** [comment]
@simoneromano96, I do not have time until next week to work on a session middleware. But you can start here if you want https://github.com/gofiber/middlewares/blob/master/session.go
https://fiber.wiki/context#locals
