### ISSUE TITLE
🤗 Difficulties during installation process

### ISSUE THREAD

**Issue by iapicca** [gofiber/fiber#925]
Hi all,
similarly to this [issue](https://github.com/gofiber/fiber/issues/788) I'm having difficulties to install fiber

<details>
<summary>logs</summary>

```bash
 francesco@francesco-yoga720  ~  go version             ✔  4486  01:51:35 
go version go1.15.2 linux/amd64
 francesco@francesco-yoga720  ~  which go               ✔  4487  01:51:39 
/home/francesco/development/go/go/bin/go
 francesco@francesco-yoga720  ~  go clean -cache -modcache -i -r      

 francesco@francesco-yoga720  ~  go get -u github.com/gofiber/fiber/v2

cannot find package "github.com/gofiber/fiber/v2" in any of:
	/home/francesco/development/go/go/src/github.com/gofiber/fiber/v2 (from $GOROOT)
	/home/francesco/development/go/golib/src/github.com/gofiber/fiber/v2 (from $GOPATH)
	/home/francesco/projects/go/src/github.com/gofiber/fiber/v2
 francesco@francesco-yoga720  ~  go get github.com/gofiber/fiber/v2   

cannot find package "github.com/gofiber/fiber/v2" in any of:
	/home/francesco/development/go/go/src/github.com/gofiber/fiber/v2 (from $GOROOT)
	/home/francesco/development/go/golib/src/github.com/gofiber/fiber/v2 (from $GOPATH)
	/home/francesco/projects/go/src/github.com/gofiber/fiber/v2
 francesco@francesco-yoga720  ~                       1 ↵  4491  01:52:08 

```
                      

</details>

<details>
<summary>.\zshrc </summary>

```bash
# GOLANG
export GOROOT=/home/francesco/development/go/go
export PATH=$GOROOT/bin:$PATH
# this is for downloaded library
export GOPATH=/home/francesco/development/go/golib
export PATH=$GOPATH/bin:$PATH
# this is for my projects
export GOPATH=$GOPATH:/home/francesco/projects/go
```

</details>

I've seen this [answer](https://github.com/gofiber/fiber/issues/788#issuecomment-692940175), but I'm not sure what action should I take
I'm really new to go in general, I could use some help
Thank you

**Comment by hi019** [comment]
Hi, have you ran `go mod init [project-name]` to initialize the module?

**Comment by alfuhigi** [comment]
> Hi, have you ran `go mod init [project-name]` to initialize the module?

This will create ``` go.mod ``` then you can ran ``` go get -u github.com/gofiber/fiber/v2 ``` that will create another file named ``` go.sum ```  if I am correct :)

**Comment by hi019** [comment]
Yes, you're correct

**Comment by kiyonlin** [comment]
You can try `go get -u gitHub.com/gofiber/fiber-cli/fiber` and run `fiber new project-name [mod name]` 😃

**Comment by iapicca** [comment]
@hi019 @alfuhigi 
what is the correct location where to create `go.mod`?
GOPATH GOROOT or my app directory?

@kiyonlin 

> You can try `go get -u gitHub.com/gofiber/fiber-cli/fiber` and run `fiber new project-name [mod name]` 
> 
> `fiber new` creates some fiber boilerplate code and runs `go mod init`

this doesn't work for me

```bash
go get -u gitHub.com/gofiber/fiber-cli/fiber
package gitHub.com/gofiber/fiber-cli/fiber: unrecognized import path "gitHub.com/gofiber/fiber-cli/fiber": reading https://gitHub.com/gofiber/fiber-cli/fiber?go-get=1: 404 Not Found
```

thanks for the help

**Comment by kiyonlin** [comment]
> this doesn't work for me
@iapicca Oops, I make a typo (`gitHub`)

**Comment by kiyonlin** [comment]
> can I suggest to update the installation in the readme.MD

Of course PRs are always welcome.

**Comment by iapicca** [comment]
@kiyonlin now works thank you
I never heard about modules until now, 
I'll go ahead and learn how to use it before bothering you any further
(google search pointed me [here](https://blog.golang.org/using-go-modules))

if fiber is as fast as your response time I feel that I've picked up the right framework to learn <3

I'm closing for now, I might submit the pr when I know what I'm doing
Thank you all
