### ISSUE TITLE
URL redirection

### ISSUE THREAD

**Issue by MohamedGouaouri** [gofiber/fiber#931]
**URL redirection**

Is there a way to redirect from one URL to another ?

**Comment by itsursujit** [comment]
@MohamedGouaouri  Maybe you're looking for:
https://github.com/gofiber/redirect For Redirect

**Comment by MohamedGouaouri** [comment]
> @MohamedGouaouri Maybe you're looking for:
> https://github.com/gofiber/redirect For Redirect
