### ISSUE TITLE
🤗 Using with Authboss, issues and doubts

### ISSUE THREAD

**Issue by frederikhors** [gofiber/fiber#941]
**Question description**

[Authboss](https://github.com/volatiletech/authboss) is a great project and is used a lot in corporate Golang projects.

I'm using it with [go-chi](https://github.com/go-chi/chi/) right now.

I wanna switch to Fiber but I have one problem and one doubt:

1. For the problem I opened https://github.com/gofiber/adaptor/issues/27

1. For the doubt I cannot understand if using Authboss with [`LoadClientStateMiddleware`](https://github.com/volatiletech/authboss/blob/master/client_state.go#L123) before all routes can affect the speed I get from Fiber if I start processing all requests through that middleware

I think it would be amazing a recipe with Authboss. Super useful!

Thanks for your amazing work!

**Comment by Fenny** [comment]
AuthBoss seems heavily attached to the `net/http` library, it would require some work to be compatible with fasthttp. 

I personally do not have the time to do that, I'm sorry. Maybe someone else wants to take a look?
