### ISSUE TITLE
TUS support, external middleware? 

### ISSUE THREAD

**Issue by G2G2G2G** [gofiber/fiber#944]
https://tus.io/

**Is your feature request related to a problem?**
I don't think so

**Describe the solution you'd like**
Have a "tus" / "tusd" easily implemented in fiber, similar to how the JWT can be easily implemented

**Describe alternatives you've considered**
I have done a lot of research on uploading on the web, there are an insane amount of options, tons of jquery and javascript, the resumablejs, etc. None of them have a very standardized protocol except tus... So because it is a protocol, and their main backend implementation is in Go.. and of course their browser front end is in JS, I think it is the best choice.
There are lots of solutions to uploading a file, but I don't think many/any are as robust and well documented. 

**Additional context**
tus related libraries are/is (as far as I can tell) the most used browser upload things that exist, the company that is behind it does the "uppy" thing which seems to be their most popular (front end for the tus-js etc):
https://github.com/transloadit/uppy

tus protocol is also not limited to browsers!

Some extra stuff:
https://github.com/tus/tus-js-client/blob/master/docs/api.md
This is how to use it "programmatically" I think that would be the best solution as an **"external middleware"** 
https://github.com/tus/tusd/blob/master/docs/usage-package.md

Hopefully I have sold you on the idea, I think the resumability of tus (especially with really bad internet), and the very well documented standards/standardization is worth being an external middleware, I think it won't "disappear" like many of the other upload projects have over the years, mostly because it isn't just a simple javascript front end, but an entire protocol.

Thank you for consideration & reading.

**Comment by hi019** [comment]
The project looks useful, thanks for putting it on my radar. From a quick look at the handler code, porting it to Fiber would be quite a bit of a work. If someone wants to make their own tus middleware, they can make a pr to get it added to Fiber. What do you think @Fenny ?

For now you can use our [Adaptor middleware](https://github.com/gofiber/adaptor) to make the handler compatible with fiber.

**Comment by Fenny** [comment]
@hi019 sounds good, if someone wants to work on this you can make a PR here so we can add it to the list 👍

**Comment by maulanashalihin** [comment]
🎉 Great news — [tusdfiber](https://github.com/maulanashalihin/tusdfiber) now implements the TUS resumable upload protocol natively on Go Fiber!

No `adaptor.HTTPHandler` needed — all handlers accept `func(c *fiber.Ctx) error` directly.

**Features:**
- TUS v1 + IETF Resumable Upload Draft (v2)
- Streaming body via fasthttp (no full buffering)
- Compatible with all tusd storage backends (FileStore, S3, GCS, Azure)
- File, HTTP, and gRPC hooks via tusd hook system
- Prometheus metrics (native Fiber, no adaptor)
- CORS, locking, method override, concatenation, deferred length
- 53 unit tests + E2E tests

**Quick Start:**
```go
go get github.com/maulanashalihin/tusdfiber
go get github.com/tus/tusd/v2/pkg/filestore
go get github.com/tus/tusd/v2/pkg/filelocker

app := fiber.New(fiber.Config{StreamRequestBody: true})

store := filestore.New("./uploads")
locker := filelocker.New("./uploads")
composer := tusdfiber.NewStoreComposer()
store.UseIn(composer.StoreComposer)
locker.UseIn(composer.StoreComposer)

handler, _ := tusdfiber.NewHandler(tusdfiber.Config{
    StoreComposer: composer,
    BasePath:      "/files/",
})
app.Use(tusdfiber.DefaultMiddlewareStack(nil)...)
handler.Register(app)
```

Thought this would be a great update to this issue — 2 years later, we finally have a native TUS solution for Fiber! 🚀

**Comment by gaby** [comment]
@maulanashalihin You add support for github.com/gofiber/fiber/v3

The v2 is not getting any new features.
