### ISSUE TITLE
🐛  Wildcard parameter persists between requests.

### ISSUE THREAD

**Issue by sandro** [gofiber/fiber#945]
**Fiber version**
v2.1.0

**Issue description**
When I declare a wildcard route and print out the wildcard parameter, sometimes, the parameter sticks around on the next request.
I expect the wildcard parameter to match the path each time.

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()
  app.Get("*", func(c *fiber.Ctx) error {
    fmt.Println("param", c.Params("*"))
    return c.SendStatus(fiber.StatusOK)
  })
  log.Fatal(app.Listen(":3000"))
}
```

```sh
# 1st request
curl http://localhost:3000/
param

# 2nd request
curl http://localhost:3000/favicon.ico
param favicon.ico

# 3rd request
curl http://localhost:3000/
param favicon.ico
```

I expect the server to print out an empty string on the third request instead of printing out favicon.ico.

**Comment by kiyonlin** [comment]
Nice found @sandro

**Comment by sandro** [comment]
Thanks for submitting a fix @kiyonlin !

**Comment by Fenny** [comment]
Merged with https://github.com/gofiber/fiber/pull/946, thanks guys for the report. Fix will ship with the next tag 👍
