### ISSUE TITLE
🐛  Can't get added header by proxy

### ISSUE THREAD

**Issue by jney** [gofiber/fiber#947]
**Fiber version**

v2.1.0

**Issue description**

Can't get the added header by proxy in targeted server.
Look at the following code, I can't get "test" header.

**Code snippet**

```go
	app := fiber.New()

	app.Use(compress.New())
	app.Use(cors.New(cors.Config{AllowCredentials: true}))

	app.Use(proxy.Balancer(proxy.Config{
		Servers: []string{"http://localhost:9090"},
		ModifyRequest: func(c *fiber.Ctx) error {
			c.Set("test", "ok")
			return nil
		},
	}))

	app.Listen(":8888")
```

in targeted server

```go
c.Get("test") // returns ""
```

**Comment by Fenny** [comment]
Quick question, are you testing this with CORS requests specifically?

**Comment by jney** [comment]
Hi @Fenny , I tested without it too, same result. I should have removed it from example to avoid confusion.

You can try it with this very minimal code:

proxy:

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/proxy"
)

func main() {
	app := fiber.New()

	app.Use(proxy.Balancer(proxy.Config{
		Servers: []string{
			"http://localhost:8001",
		},
		ModifyRequest: func(c *fiber.Ctx) error {
			c.Set("hello", "world")
			return nil
		},
	}))

	app.Listen(":8000")
}
```

server:

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
	app := fiber.New()

	app.All("/*", func(c *fiber.Ctx) error {
		return c.SendString("hello "+c.Get("hello"))
	})

	app.Listen(":8001")
}
```

run both, then `curl 'http://0.0.0.0:8000/'`: still empty header

**Comment by jney** [comment]
I figured out. It looks like I have to use `c.Request().Header.Add` instead of `c.Set`.
Maybe is it me, or the README is confusing?

**Comment by Fenny** [comment]
I will update the example 👍
