### ISSUE TITLE
Route & Group sequence problem

### ISSUE THREAD

**Issue by bluesoulx** [gofiber/fiber#952]
**Fiber version**
2.1.1

**Question description**
In my situation, some URI need middleware, and some are not.
Therefore, I use 

```go
group := app.Group("/", middleware.m1(), middleware.m2())
```
for any handlers need these middlewares.

In the following code, 

```go
group := app.Group("/", middleware.m1(), middleware.m2())
app.Get("/path1", func(c *fiber.Ctx) {...})
group.Get("/path2", func(c *fiber.Ctx) {...})
```
The path1 will also execute m1 & m2.

But if the sequence different as follow.

```go
app.Get("/path1", func(c *fiber.Ctx) {...})
group := app.Group("/", middleware.m1(), middleware.m2())
group.Get("/path2", func(c *fiber.Ctx) {...})
```

It will work very well.
Is this the normal case?

Thank you.

**Comment by kiyonlin** [comment]
Hey @bluesoulx 
> Is this the normal case?

The answer is yes.

Because Fiber registers routes in order. `Group("/")` will cover `Get("/path1")` in the first snippet.

**Comment by bluesoulx** [comment]
Hi @kiyonlin 

Thank you for the answer.
I will change my code for this. 👍
