### ISSUE TITLE
🚀 Middleware of Analytics Tools like Google Analytics

### ISSUE THREAD

**Issue by suntong** [gofiber/fiber#954]
**Is your feature request related to a problem?**

It'll be super to have Analytics capability like Google Analytics.

**Describe the solution you'd like**

To have an Internal or external Middleware, even a Third Party Middlewares, that can have some Analytics functionality like Google Analytics, and open source it. 

**Describe alternatives you've considered**

Use Google Analytics.

**Additional context**

What else Analytics Tools are you using, to analyze in-depth detail about the visitors on your website? 

That's vitally important for sites to understand their customer, where and how they are coming from, etc.

**Comment by codemicro** [comment]
Hi @suntong!

This is an interesting proposal. As I'm sure you're aware, Google Analytics is predominantly used as part of the frontend of an application. While there is the [GA measurement protocol](https://developers.google.com/analytics/devguides/collection/protocol/v1/) that allows you to send HTTP requests directly to record activity, this is probably out of scope for Fiber to implement. I think it's probably better for a third party middleware to be made, if someone wanted to do that.

If I were to implement Google Analytics on the frontend using Fiber, I'd most likely use templating to populate the unique identifier. 

If backend analytics were really wanted, I'd look into using a library like [Pirsch](https://github.com/pirsch-analytics/pirsch), or one of the others that exist. If they have their own middlewares, they can be used with Fiber through [gofiber/adaptor](https://github.com/gofiber/adaptor).

**Comment by suntong** [comment]
Cool! I don't know the details how everything works together in this regards. Thanks for all your suggestions, am sure to look into them...
