### ISSUE TITLE
🤗 QueryParser() returns nil even there are params required.

### ISSUE THREAD

**Issue by ckcks12** [gofiber/fiber#967]
**Question description**

QueryParser() returns no error(nil) if no query arguments sent. However, what if there are required parameter? Its very first if statement checks arguments count with no considering params' requirement. So even though I tagged params as required, QueryParser() doesn't return any error with an empty query argument.

I expected error returned because it's required but didn't get anything.

**Code snippet** _Optional_

```go
func (hc *HTTPController) list(c *fiber.Ctx) {
	type Input struct {
		Offset int64  `query:"offset,required"`
		Limit  int64  `query:"limit,required"`
		Test   string `query:"test,required"`
	}

	input := Input{}
	if err := c.QueryParser(&input); err != nil {
		c.Next(fiber.NewError(http.StatusBadRequest, err.Error()))
		return
	}
	// below codes think user sent input correctly.
}
```

Is it what you intended? [Code](https://github.com/gofiber/fiber/blob/8d9224dbfe310d8d4a56e904dfbf869a034ca9a8/ctx.go#L718)

**Comment by Fenny** [comment]
We should return an error there, I assume if people call `QueryParser` at least 1 or more query params should be available.

I will accept a PR for this 👍

**Comment by ckcks12** [comment]
Sure, my pleasure.

**Comment by kiyonlin** [comment]
Hey @ckcks12 I think user should validate the result by themselves if there is no error returned by `QueryParser`, like using [go-playground/validator](https://github.com/go-playground/validator).

And here is an simple [example](https://github.com/kiyonlin/dawn/blob/master/fiberx/fiberx.go#L54-L62).

**Comment by ckcks12** [comment]
@kiyonlin Let's put it in this way.

User wrote `required` to the field.
Input is empty.
What does user expect? 
If no error, it means required field has been set. 

Moreoever if there's any input then it gives an error. This is why I think it's a bug.
If there's no such a `required` option, user should validate. Yeah it does make sense.

I'm just gonna remove the arg length based condition.

**Comment by Fenny** [comment]
@ckcks12 I prefer if you return an error on the arg len statement, it's more efficient since it won't touch the decoder pool and allocate a map.

**Comment by kiyonlin** [comment]
> I prefer if you return an error on the arg len statement, it's more efficient since it won't touch the decoder pool and won't allocate a map. Something like:
> 
> ```go
> 	if c.fasthttp.QueryArgs().Len() < 1 {
> 		return errors.New("Missing query parameters")
> 	}
> ```

@Fenny What if user set parts of parameters? 😆

**Comment by Fenny** [comment]
@kiyonlin could you elaborate, I'm not sure what ya mean with _set parts_?

**Comment by kiyonlin** [comment]
@Fenny I mean like `?offset=0` but no `limit` param in query string.

**Comment by Fenny** [comment]
> @Fenny I mean like `?offset=0` but no `limit` param in query string.

Yeah that too, totally forgot that use case. Thanks guys 👍

**Comment by Fenny** [comment]
@ckcks12 tagged! 🎊
