### ISSUE TITLE
Handling cross-origin requests

### ISSUE THREAD

**Issue by peterdee** [gofiber/fiber#975]
Hey guys, I've been stuck with a small problem for quite some time. It is related to the cross-origin requests.

I have a server, that uses the `cors` middleware.

Here's the example code:

```golang
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"
)

func main() {
	app := fiber.New()

	app.Use(cors.New(cors.Config{
		AllowOrigins: "*",
		AllowMethods: "GET,POST,PATCH",
	}))
	app.Use(logger.New())

	app.Get("/", func(ctx *fiber.Ctx) error {
		return ctx.Status(fiber.StatusOK).JSON(fiber.Map{
			"info":   "OK",
			"status": fiber.StatusOK,
		})
	})

	// launch the app
	launchError := app.Listen(":8000")
	if launchError != nil {
		panic(launchError)
	}
}
```

I send requests to the server from the browser console, like that:

```javascript
(async function () {
  try {
    const response = await fetch('http://localhost:8000', {
      method: 'GET',
    });
    const json = await response.json();
    return console.log('fetch response', json);
  } catch (error) {
    return console.log('fetch error', error);
  }
}())
```

I am getting the following error:

```text
Refused to connect to 'http://localhost:8000/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

I get the same error if I am sending requests to the server via `axios` or `ajax` (`JQuery`). 

I feel like I'm missing something small here, maybe a header in the request. 

The server works fine if requests are sent via Postman or if I just simply open the page in the browser:

```json
// 20201027161824
// http://localhost:8000/

{
  "info": "OK",
  "status": 200
}
```

I would really appreciate any ideas of why the `CSP` error is caused and how it can be resolved.

As a side note, I created a small project, that uses the templates, and I did not have this problem there (since everything was on the same origin).

**Comment by hi019** [comment]
This looks like an issue with Content-Security-Policy. The page you're running the Javascript on must have a CSP that prevents requests to `localhost:8000`. This isn't something that can be solved by Fiber, a change to the policy needs to be made on the frontend. I don't know much about CSP, but try `<meta http-equiv="Content-Security-Policy: connect-src http://localhost:*/">`

**Comment by peterdee** [comment]
Hey @hi019, thank you for your response.

I've realized that the issue was on my side.

I used a Koa server with `koa-helmet` to serve some static pages.

`koa-helmet` was basically blocking all of the `cross-origin` requests and was causing the CSP error.

I'm closing this issue.
