### ISSUE TITLE
Possible to put a section on main page to advertise the users of fiber?

### ISSUE THREAD

**Issue by hiqsociety** [gofiber/fiber#980]
1. would like to see the performance on actual running production websites etc.

2. any websocket example? is it good for doing websocket stuff?

great work by the way

**Comment by hi019** [comment]
> I would like to see the performance on actual running production websites etc.

Cc @Fenny , I think he has done some professional work with Fiber. But you could likely benchmark if yourself by replacing time consuming things with a sleep call. 

> any websocket example? is it good for doing websocket stuff?
https://github.com/gofiber/websockets

**Comment by renanbastos93** [comment]
About benchmarks, you can see in this link: https://docs.gofiber.io/miscellaneous/benchmarks

**Comment by codemicro** [comment]
Hi @hiqsociety!

You can take a look at benchmarks run independently by TechEmpower [here](https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=plaintext&l=zijocf-1r&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zieepr-zik0zj-zik0zj-73). You can see Fiber's performance across various different tasks, like responding with plaintext or JSON, or performing common database queries. If you want, you can also choose specific filters to compare these across other frameworks (this isn't just limited to Go frameworks either - you'll see various other frameworks like Express for JS and Flask for Python).

Regarding websockets - we have [our own websocket middleware](https://github.com/gofiber/websocket) that you can use. We've also got an usage examples of using websockets foir a basic chat application, which you can find [here](https://github.com/gofiber/recipes/tree/master/websocket).
