### ISSUE TITLE
Replacement for nginx with fastcgi for running php7.4-fpm for wordpress

### ISSUE THREAD

**Issue by gitmko0** [gofiber/fiber#982]
Instead of this using net/http
https://github.com/beberlei/fastcgi-serve

possible to make one php? That'll really increase adoption. Wordpress multisite compatible replacement to nginx

**Comment by kiyonlin** [comment]
Hey @gitmko0 Do you have any issue about fiber?

**Comment by gitmko0** [comment]
my issue is ... it's too fast growing! so i will adopt it but i think i will like it so much i would like it to be also replace nginx for fastcgi.
I have no idea how u are able to pop up suddenly early this yr and outdone the rest of the framework which i've been looking at for the past 3 years.

well done. it's very impressive the achievement in "adoption" though i hv yet to see any use case production ready type but i'm willing to support this project based on the "star" power.

so pls fastcgi nginx replacement. thx

**Comment by mikeychowy** [comment]
@gitmko0 I don't want to sound like one of the users from SO, but the fiber team has no obligation whatsoever to make the things you want/need if i'm getting what you're saying right.

They provides us tools to write HTTP(S) servers. That's it.
They can certainly consider making a module or a project outside of the core of fiber, but if they don't want / need to do it, it's our job to write it ourselves.

That, or wait until someone with more free time consider building it.

**Comment by kiyonlin** [comment]
Fiber is a web framework not a web server. [Caddy](https://github.com/caddyserver/caddy) do the same thing as nginx, maybe that is what you want.
