### ISSUE TITLE
Difference between Fiber csrf in v1 and v2 

### ISSUE THREAD

**Issue by hleinan** [gofiber/fiber#989]
Hey, I have a working application using Fiber v1 and Fiber csrf from version 1.

I just did an upgrade to V2 for both of them, and now I am getting a 403 after server restart. I do see that the csrf token is updated on every restart when using V2, so that the client version is out of sync. My quess is that the client is caching the token string in the cookie, and this is not over written when the server is restaring.

What would be te proper way of handling this issue?

**Comment by hleinan** [comment]
After some more investigation, it looks like the new token is not sent to the client. If i manually delete the old _csrf cookie, and refresh, a new and correct token is set. If not deleted, a 403 is sent from the server. Note that this only happens after a server restart, and once the server is running and the token is refresh from server, it all works as expected. I did not have this problem using Fiber v1 and Fiber csrf v1

**Comment by hi019** [comment]
Massive PR #1009 should fix this :)

**Comment by Fenny** [comment]
@hleinan please try the updated csrf middleware in `v2.2.0` <https://github.com/gofiber/fiber/tree/master/middleware/csrf>
