### ISSUE TITLE
🐛 fiber.Static changes wont take immediate effect

### ISSUE THREAD

**Issue by anton7r** [gofiber/fiber#990]
**Fiber version**
v2.1.2 (Go 1.15.2)
**Issue description**
fiber.Static changes made to the files that recide in the `./public` folder wont take immediate effect
**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

  // Steps to reproduce
  app.Static("/", "./public", fiber.Static{
    Compress: false,
  })
}
```

**My observations**
the CacheDuration that is set here seems to be the source of the issue: 
https://github.com/gofiber/fiber/blob/30228a1e7514bf45d27de0e1e330504c38439421/router.go#L324

**Possible solutions**
that every file under the `./public` folder is loaded into the memory on startup and then it sets up filesystem event listeners that would update the changes that was made to the files.

One problem may arise with the solution provided above is that if the `./public` directory is large and it has alot of files that wont be used immediately and therefore it would waste alot of ram.

Or one other solution is that the cacheDuration remain as is, but file system event listeners could override the cache and the cacheDuration could be made longer like 10mins.

**Comment by Fenny** [comment]
We are discussing the option to either lower the `CacheDuration` or make it a public setting, I will keep you updated.

Regarding your concern about memory <https://github.com/valyala/fasthttp/blob/master/fs.go#L475> files above 8MB are not cached in memory.

**Comment by anton7r** [comment]
ok. 
making it a public setting would be pretty neat since this issue pretty much comes up when editing css and js so the fiber user could have the `CacheDuration` set to `0` in development and then on production they could set it to something like `320`

**Comment by Fenny** [comment]
@anton7r `CacheDuration` is added in https://github.com/gofiber/fiber/releases/tag/v2.2.0 👍
