### ISSUE TITLE
🤗 CI lint seems not to work normally

### ISSUE THREAD

**Issue by leozhantw** [gofiber/fiber#994]
**Question description**

Hi,

I found that the CI lint seems not to work normally.

```
Run reviewdog/action-golangci-lint@v1
🐶 Installing reviewdog ... https://github.com/reviewdog/reviewdog
Installing golangci-lint ... https://github.com/golangci/golangci-lint
Running golangci-lint with reviewdog 🐶 ...
reviewdog: This is Pull-Request from forked repository.
GitHub token doesn't have write permission of Check API, so reviewdog will
report results via logging command [1].
[1]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
reviewdog: Reporting results for "golangci"
reviewdog: No results found for "golangci". 82 results found outside diff.
```

Have you considered replacing the linter with the official version which maintains by **golangci-lint**?

https://github.com/golangci/golangci-lint-action

**Comment by Fenny** [comment]
From my understanding reviewdog had more to offer compared to golangci-lint, but please correct me if I'm wrong.

**Comment by leozhantw** [comment]
Hum ... the functions should be similar, but considering the UI part, reviewdog really looks more beautiful.

Below is my comparisan:

[reviewdog/action-golangci-lint](https://github.com/leozhantw/fiber/pull/6/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR323)
[golangci/golangci-lint-action](https://github.com/leozhantw/fiber/pull/7/files#diff-6c4b6ed7dc8834cef100f50dae61c30ffe7775a3f3f6f5a557517cb740c44a2dR323)
