### ISSUE TITLE
🐛 mounting a fiber instance doesnt work for views

### ISSUE THREAD

**Issue by ryano3000** [gofiber/fiber#996]
**Fiber version**
latest

**Issue description**
Mounting a fiber instance with its own views doesn't work. 
Get this error instead on below code:
http://localhost:1323/admin --> open index: no such file or directory

**Code snippet**

```go
package main

import "github.com/gofiber/fiber/v2"

func main() {
  app := fiber.New()

	admin_engine := html.New("./admin/views", ".html")

	admin := fiber.New(fiber.Config{
		Views: admin_engine,
	})

	admin.Get("/", func(c *fiber.Ctx) error {
		// Render index template
		return c.Render("index", fiber.Map{
			"Title": "Hello, World!",
		})
	})


	app.Mount("/admin", admin)



  log.Fatal(app.Listen(":3000"))
}
```

**Comment by Fenny** [comment]
@ryano3000 can you share your views folder structure? And does it work when not mounting the app?
