### ISSUE TITLE
🐛 redirect from / apply also to  /*/ but not to /* or /*/*

### ISSUE THREAD

**Issue by TomasVojacek** [gofiber/fiber#997]
**Fiber version**
v2.0.6 and v2.1.3
**Issue description**
if redirect set from "/" to "/swagger"
curl  "http://127.0.0.1:3005/api/" is redirected
while following is not redirected as expected
curl  "http://127.0.0.1:3005/api" 
curl -i "http://127.0.0.1:3005/api/anything" 

**Code snippet**

```go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/redirect/v2"
)

func main() {
	app := fiber.New()

	app.Use(redirect.New(redirect.Config{
		Rules: map[string]string{
			"/":   "/swagger",
		},
		StatusCode: 301,
	}))

	app.Get("/redirect", func(c *fiber.Ctx) error {
		return c.SendString("You have been redirected")
	})

	app.Get("/api/*", func(c *fiber.Ctx) error {
		return c.SendString("API")
	})

	app.Listen(":3005")
}

```
curl -i http://127.0.0.1:3005/api/

**Comment by renanbastos93** [comment]
Thanks a lot for reporting it. Well, I am fix the redirect.
https://github.com/gofiber/redirect/pull/21

**Comment by renanbastos93** [comment]
@TomasVojacek Can you to update package redirect doing `go get -u github.com/gofiber/redirect/v2` ? 
After you can test again. I am waiting your feedback.

**Comment by TomasVojacek** [comment]
Version redirect/v2 v2.0.2 resolved problem, 
thank you.
