### ISSUE TITLE
Any real life example or reactapp tutorial type? a real reactapp foundation to work with.

### ISSUE THREAD

**Issue by gitmko0** [gofiber/fiber#998]
Any real life example or reactapp tutorial type? a real createreactapp foundation to work with.

just to standardize most things

**Comment by hi019** [comment]
The closest thing we have to a tutorial is probably [our docs](https://docs.gofiber.io/). It should get you started, and questions are always welcome in our [Discord](https://gofiber.io/discord). As for create-react-app, we do have a [cli](https://github.com/gofiber/cli) which scaffolds a Fiber starter for you.

**Comment by anton7r** [comment]
you can use cra and then `eject` from it to edit the scripts so that you can add a proxy to your fiber app. so all the requests made to `/api/` on the webpack devserver would be proxied to your fiber backend. 

Hope this helps!

**Comment by gitmko0** [comment]
coz it's so new, will be best if have a "hand holding" tutorial on it... i'm new to node too

**Comment by hi019** [comment]
I'm not sure if that's necessary, our API is straightforward and the [Hello World](https://docs.gofiber.io/#hello-world) example and [Basic Routing](https://docs.gofiber.io/#basic-routing) guide should have you covered. We welcome PRs, though!

**Comment by lightyen** [comment]
See the cra document: [**Back-End Integration**](https://create-react-app.dev/docs/proxying-api-requests-in-development)
